### ISSUE TITLE
Investigate Dependabot Integration That Works with Assembly Load Context

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#1002]
This is part of #998. We need to ensure dependencies in the Assembly Load Context are always updated when dependabot detects updates.

References:
- [PowerShell assembly dependency conflicts](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.2)
- [Our dependency resolver](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Authentication/Authentication/Utilities/DependencyAssemblyResolver.cs#L14)

**Comment by ddyett** [comment]
not feasible to use dependabot with powershell model.
