### ISSUE TITLE
[Feature request] Remove "nightlies" from the GitHub releases.atom feed

### ISSUE THREAD

**Issue by o-l-a-v** [microsoftgraph/msgraph-sdk-powershell#1004]
I wanted to subscribe to the releases.atom feed for new releases, but saw that it also includes the nightlies/ automatic builds.

I don't know if it's anything the maintainers of the repo can do about it, but would it be possible to keep those out of the releases.atom feed?

For reference:

* [/Releases](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases)
  * Does not show nightlies.
* [/Releases.atom](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases.atom)
  * Shows nightlies.
* [/Tags](https://github.com/microsoftgraph/msgraph-sdk-powershell/tags)
  * Shows nightlies.
* [/Tags.atom](https://github.com/microsoftgraph/msgraph-sdk-powershell/tags.atom)
  * Shows nightlies.

**Comment by peombwa** [comment]
We will look into this soon.

**Comment by peombwa** [comment]
Closing as resolved. Nightly build tags are no longer published to GitHub for v2 builds.
