### ISSUE TITLE
Is there a way to get Application Password IDs and expiration dates?

### ISSUE THREAD

**Issue by harre096** [microsoftgraph/msgraph-sdk-powershell#1005]
I want to build a script that pulls all password ids and their expiration dates. Is there a commandlet that I can use to get this data?

**Comment by harre096** [comment]
You can close it. I am using [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0) directly instead.

If I use this code, I can get a token
```
  $resource = "https://graph.microsoft.com"
  $context = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile.DefaultContext
  $token = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, $resource).AccessToken
  
  $global:authHeader = @{
      'Content-Type'='application/json'
      'Authorization'='Bearer ' + $token
      'ConsistencyLevel'='eventual'
  }
```
and then call it easily enough with something like
```
function ListApplications{
  Param(
    [Parameter(Mandatory = $false)][string]$nextLink,
    [Parameter(Mandatory = $false)][object]$accumlator
)
  if($nextLink){
    $restUri = $nextLink
  }else{
    $restUri = "https://graph.microsoft.com/v1.0/applications?`$select=displayName,id,passwordCredentials&`$count=true"
  }
  $allAppsResp = Invoke-RestMethod -Uri $restUri -Method GET -Headers $global:authHeader
  $allAppsResp | Add-Content $OutputFile
  $accumlator += $allAppsResp.value
  $nextLink = $null
  $nextLink = $allAppsResp | Select-Object -ExpandProperty "@odata.nextLink" -EA SilentlyContinue
  if($nextLink){
    Write-Host "Doing recurstive call to get more applications: $nextLink"
    ListApplications $nextLink $accumlator
  }else{
    Write-Host "Fetched $($accumlator.Count) Applications from AAD."
    return $accumlator
  }
}
```

**Comment by peombwa** [comment]
Or you could use `Get-MgApplication | select Id, DisplayName, PasswordCredentials`.

**Comment by harre096** [comment]
> Or you could use `Get-MgApplication -All | select Id, DisplayName, PasswordCredentials`.

Wow. Yeah, that is awesome! Clearly I just reinvented the wheel. :)

The [docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.applications/get-mgapplication?view=graph-powershell-1.0) didn't really help me find this on my own. Maybe it should just link to the [full properties list from the API page](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties)? Aside from finding it in the code (which I tried to do but failed to find), I don't how how else I would have figured out what you just shared. Can more info be added to the docs on the powershell side? Even what you just posted would be a great sample for that docs page.

**Comment by maisarissi** [comment]
Hi @harre096 . 
We deeply appreciate your feedback, and we are working to improve the documentation.

I will close this issue since the work to have enhanced documentation on the PowerShell side is being tracked by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/876
