### ISSUE TITLE
New-MgGroup command

### ISSUE THREAD

**Issue by aremo-ms** [microsoftgraph/msgraph-sdk-powershell#1008]
Hello guys
I'm part of IDG group and working on some automation for [Azure-Samples](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2)

My issue is with New-MgGroup command - please see the screenshot
Please advise what do I miss here
![image](https://user-images.githubusercontent.com/85962119/149531667-a1d989e5-27a6-4c34-9b40-f574e2feaaeb.png)

**Comment by peombwa** [comment]
@aremo-ms, it looks like there is a version mismatch of installed modules. Could you update/reinstall the latest version of the SDK (1.9.1) - `Install-Module Microsoft.Graph -Force -AllowClobber`.

**Comment by aremo-ms** [comment]
@peombwa 
I've reinstalled the modules and now get next error. Please advise
![image](https://user-images.githubusercontent.com/85962119/151217474-c5621af9-fa3e-4cea-997f-4df794d86329.png)

My current version:
![image](https://user-images.githubusercontent.com/85962119/151217613-d0cb583f-b416-448e-bd78-f7d09e2e96a4.png)

**Comment by aremo-ms** [comment]
@peombwa 
After reinstalling the Graph I still have an issue with New-MgGroup, for some reason it looks for ver 1.9.0.0
Please advise. It holds us back for almost two weeks now
![image](https://user-images.githubusercontent.com/85962119/151256563-724f6a4c-7832-4a22-bfd1-fa3a514f465c.png)

**Comment by maisarissi** [comment]
Hi @aremo-ms . I couldn't repro your issue.
I was able to create the group by running the [code snippets](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=powershell#request) provided in the docs.
![image](https://user-images.githubusercontent.com/22648831/152234718-95fe86de-fa04-4b28-a5b9-3a59a58c11ab.png)

I don't know if you tried the command @peombwa suggested, but can you try to follow the [uninstall guide](https://docs.microsoft.com/en-us/graph/powershell/installation?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#uninstalling-the-sdk) and then, install again?

**Comment by aremo-ms** [comment]
@maisarissi and @peombwa
I'm reopening this issue. 
**Cannot reproduce** doesn't resolve it for me. I have same standard PowerShell with same standard terminal and cannot get through it. I even installed 1.9.0 version for Microsoft.Graph.Authentication and still have this issue.
I need real help with chat and not msfbot trying to shake me off with inactivity claims.

Found [similar issue](https://github.com/pnp/PnP-Sites-Core/issues/2548) that was "successfully" archived and forgotten

This issue holds us back for Azure-Samples
![image](https://user-images.githubusercontent.com/85962119/169599029-c7ea6547-279a-4fbd-9fbf-c9c2322ca2a8.png)
