### ISSUE TITLE
Get-MgBookingBusiness & Bookings Commandlets are not available with v1.0

### ISSUE THREAD

**Issue by Amol04outlook** [microsoftgraph/msgraph-sdk-powershell#1019]
Hi Team,

Get-MgBookingBusiness & other Bookings Commandlets are not available with v1.0. We need to connect to Beta using Select-mgprofile -Name "Beta".

Please update the SDK with latest available Bookings commandlets so that it can be accessible from v1.0.

Thanks & Regards
Amol

**Comment by peombwa** [comment]
Hi @Amol04outlook, Business Bookings cmdlets are now available in v1.0 as part of 1.9.2 release - https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.9.2.
