### ISSUE TITLE
Error\Bug with Get-MgDeviceManagementDeviceConfiguration

### ISSUE THREAD

**Issue by cr45h0v3rwr173** [microsoftgraph/msgraph-sdk-powershell#1020]
We Tried to Implement a automation script to read all DeviceManagment Profiles out from Intune and save them into a Backup database in case that we lose our Tenant or an Human error of deleting a Profile.

We tried the command Get-MgDeviceManagementDeviceConfiguration and the problem is we get only some of the Profiles but not all

The Command only returns the 
- Device restrictions
- Custom Profiles

But its not returning all the Other Profile Types like
- Scep-certificate
- Email
- Trusted certificate
- Wi-Fi

and so on. Is this a Bug or a Feature? :D 

How we can return this type of Profiles out of Intune to create a complete Backup of this Profiles

Thanks with best regards

Andreas

**Comment by peombwa** [comment]
Are you able to fetch other profile types using the REST API? You can test this in Graph Explorer - https://developer.microsoft.com/en-us/graph/graph-explorer.

Please use https://developer.microsoft.com/en-us/graph/support for service-related questions or feature requests.

**Comment by cr45h0v3rwr173** [comment]
@peombwa  Hi Sorry for the Late Response but we have at the moment a Lots of Trouble. 
We can fetch all Profiles via Postman and GraphCalls, so we get only if we use the Cmdled not the Profiles Back. So there is an Issue with the Cmdlets in Powershell i Tryed it in PowershellCore ,7 and 5 but nowere we get an result back from the Get-MgDeviceManagementDeviceConfiguration.

**Comment by maisarissi** [comment]
Hello @cr45h0v3rwr173 . Can you share the request you are making? You can test your REST call directly in the [Graph Explorer](https://aka.ms/ge) as pointed out by @peombwa . 
Also, it would be great if you could share the output you are getting from Get-MgDeviceManagementDeviceConfiguration -Debug.

To call this cmdlet you need to have admin consent for one of the following scopes: DeviceManagementConfiguration.Read.All or DeviceManagementConfiguration.ReadWrite.All
![image](https://user-images.githubusercontent.com/22648831/152218715-5ad03f48-223c-442c-9932-0047401bc5a0.png)

To use your own applicationId when connecting to Graph via PowerShell, use the following:
```powershell
Connect-MgGraph -ClientId "<clientId>" -CertificateThumbprint "<thumbrprint>" -TenantId "<tenantId>" -Scopes "DeviceManagementConfiguration.Read.All"
```

Make sure you have the certificate installed in your machine and uploaded to your app registration:
![image](https://user-images.githubusercontent.com/22648831/152219128-80fae831-a4d4-4b7b-8c79-e5ad123ea49d.png)

**Comment by cr45h0v3rwr173** [comment]
Hi @maisarissi ,
Hi @peombwa

![cert](https://user-images.githubusercontent.com/23104978/152749819-27e1d51c-817a-
![Permissions](https://user-images.githubusercontent.com/23104978/152749843-b1c1c8d5-5ebe-4a7c-9203-044ba2e2a6a9.jpg)
4127-93fe-e56d45506a5e.JPG)
![Profileexamples](https://user-images.githubusercontent.com/23104978/152749858-c0311b03-c90b-4d6c-a670-d8becdd91f98.jpg
![login](https://user-images.githubusercontent.com/23104978/152749889-580db480-15c9-4b0b-a8cb-a88ee4dc103f.JPG)
)
![Result_powershell](https://user-images.githubusercontent.com/23104978/152749905-d8e96179-8568-49b8-a7c9-9ab4964f5e60.JPG)

**Comment by maisarissi** [comment]
Hi @cr45h0v3rwr173 
Thanks for the additional information. We will investigate further and get back to you!

**Comment by peombwa** [comment]
@cr45h0v3rwr173, the response you are getting is what the SDK receives from the service and is reproducible in Postman/Graph Explorer as well. Please reach out to the service owner by opening a question/ticket at https://developer.microsoft.com/en-us/graph/support to get further assistance on this.

**Comment by amirjs** [comment]
@cr45h0v3rwr173 
This is an old thread but I have stumbled upon the same issue. 
The solution is using 
Get-MgBetaDeviceManagementConfigurationPolicy 
as well as 
Get-MgbetaDeviceManagementDeviceConfiguration

Get-MgBetaDeviceManagementConfigurationPolicy will show you the missing "profiles" that you would see in the console

**Comment by bendingunit** [comment]
> @cr45h0v3rwr173 This is an old thread but I have stumbled upon the same issue. The solution is using Get-MgBetaDeviceManagementConfigurationPolicy as well as Get-MgbetaDeviceManagementDeviceConfiguration
> 
> Get-MgBetaDeviceManagementConfigurationPolicy will show you the missing "profiles" that you would see in the console

Alternative solution doesn't seem to work, at least in my case. While Intune is showing about 120 policies, both mentioned commands will only retrieve a subset of them, where at least 30 others were missing.

**Comment by amirjs** [comment]
> where

Interesting, what is the profile type for the missing ones? anything in common? Let me know please and I will try to reproduce

**Comment by amirjs** [comment]
> > @cr45h0v3rwr173 This is an old thread but I have stumbled upon the same issue. The solution is using Get-MgBetaDeviceManagementConfigurationPolicy as well as Get-MgbetaDeviceManagementDeviceConfiguration
> 
> > 
> 
> > Get-MgBetaDeviceManagementConfigurationPolicy will show you the missing "profiles" that you would see in the console
> 
> 
> 
> Alternative solution doesn't seem to work, at least in my case. While Intune is showing about 120 policies, both mentioned commands will only retrieve a subset of them, where at least 30 others were missing.

Interesting, what is the profile type for the missing ones? anything in common? Let me know please and I will try to reproduce
