### ISSUE TITLE
Missing Error action in New-MgSiteListItem CMD

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoftgraph/msgraph-sdk-powershell#1021]
Hello, I am looking something to handle error in MG Graph PowerShell SDK

 New-MgSiteListItem -ListId $SPOListID -SiteId $SPOSiteID -Fields @{ "Title" = $SPOApp.DisplayName;"AADServiceID" = $SPOApp.id }  -**ErrorAction -Stop**

**Comment by peombwa** [comment]
Hi @sharmajitendralal, the command supports [common parameters](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/common-parameter-names?view=powershell-7.2) which has `-ErrorAction`.
![image](https://user-images.githubusercontent.com/7061532/150835023-e73a756d-c2b2-41cd-97c1-940ad9424ade.png)

The issues seem to be with how you are using `-ErrorAction`. `-ErrorAction` accepts `Stop` and not  `-Stop`, i.e.,`-ErrorAction Stop`.

**Comment by sharmajitendralal** [comment]
Yes, Thanks I got it 
Its working fine now : New-MgSiteListItem -ListId $SPOListID -SiteId $SPOSiteID -BodyParameter $Params -ErrorAction Stop
