### ISSUE TITLE
Wrong Cmdlet names for `*-MgDeviceManagement*`

### ISSUE THREAD

**Issue by nicolonsky** [microsoftgraph/msgraph-sdk-powershell#1022]
It seems that the `s` character gets stripped off to only use singular nouns but this leads to wrong Cmdlet names:

*  ~~New-MgDeviceManagementWindowAutopilotDeploymentProfile~~ ` New-MgDeviceManagementWindow[s]AutopilotDeploymentProfile`

*  ~~New-MgDeviceManagementNdeConnector~~ ` New-MgDeviceManagementNde[s]Connector`

**Comment by peombwa** [comment]
We will address this in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/867 when move to v2 to avoid breaking change.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/867.
