### ISSUE TITLE
Update-MgDevice - issue with changing accountEnabled status

### ISSUE THREAD

**Issue by iBowler1995** [microsoftgraph/msgraph-sdk-powershell#1025]
Hi,

I'm trying to disable devices using Update-MgDevice. According to the documentation, -AccountEnabled should be a switch that accepts a boolean (true or false)

I can _get_ the accountEnabled property status, whether true or false, using Get-MgDevice, but I can't seem to enable or disable using Update-MgDevice

Whether or not I use Update-MgDevice -AccountEnabled $True/'true'true or use Update-MgDevice -AccountEnabled $False/'false'/false I get the same error:

`Update-MgDevice : A positional parameter cannot be found that accepts argument 'True'.`
or
`Update-MgDevice : A positional parameter cannot be found that accepts argument 'False'.`

Am I just not understanding the switch properly?

**Comment by peombwa** [comment]
@iBowler1995, please see the example here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/968#issue-1075270275. `-AccountEnabled` is a switch and not a Boolean. You can explicitly set values to PowerShell switches like in PowerShell like this: `Update-MgDevice -DeviceId $AADDevice.Id -AccountEnabled:$false`.
