### ISSUE TITLE
New-MgApplication command fails when logo is provided via -LogoInputFile

### ISSUE THREAD

**Issue by JanneMattila** [microsoftgraph/msgraph-sdk-powershell#1028]
Following command fails:

```powershell
    $spaApp = New-MgApplication -DisplayName $spaAppName `
        -SignInAudience AzureADandPersonalMicrosoftAccount `
        -Web @{ HomePageUrl = $SPAUri } `
        -Spa @{ RedirectUris = $SPAUri } `
        -LogoInputFile Logo_48x48.png
```

To error message: `New-MgApplication_CreateExpanded1: Unexpected contents in request body.`

If executed with `-Verbose -Debug` flags then body contains this:

```json
{
  "displayName": "My App",
  "logo": "<base64 encoded image>",
  "signInAudience": "AzureADandPersonalMicrosoftAccount",
  "spa": {
    "redirectUris": [
      "http://localhost:5000/"
    ]
  },
  "web": {
    "homePageUrl": "http://localhost:5000/"
  }
}
```

Error response:

```json
{
  "error": {
    "code": "Request_BadRequest",
    "message": "Unexpected contents in request body.",
    "innerError": {
      "date": "2022-01-25T19:26:04",
      "request-id": "6d8d234b-85cd-4e23-83ba-b085ba0d916d",
      "client-request-id": "6d8d234b-85cd-4e23-83ba-b085ba0d916d"
    }
  }
}
```

And according to this documentation [Application](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties) contains `logo` property but it says type to be `Stream`.

Similar to [935](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/935).

**Comment by peombwa** [comment]
@JanneMattila, thanks for your question. As setting a logo when creating an application is not documented in the [API reference docs](https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http), I suggest you open a question at [Microsoft Graph Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) to get a response from the workload owners.

**Comment by peombwa** [comment]
See my response and workaround in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/935#issuecomment-1072897650.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/935.
