### ISSUE TITLE
The term 'Get-MgDeviceAppMgtMobileAppInstallSummary' is not recognized as a name of a cmdlet, function, script file, or executable program.

### ISSUE THREAD

**Issue by JakeMoe** [microsoftgraph/msgraph-sdk-powershell#1041]
In v1.9.1, I could run "Get-Mg\*install\*" and see "Get-MgDeviceAppMgtMobileAppInstallSummary" was in "Microsoft.Graph.Devices.CorporateManagement" module, but when I imported the module, I'd get the error in the subject.  So I ran Update-Module in the hopes that 1.9.2 would fix it, but instead, it no longer appears in the Get-Command output, and obviously I get the same error message if I try to run it.

If I look at the [PSGallery page](https://www.powershellgallery.com/packages/Microsoft.Graph.Devices.CorporateManagement/1.9.2) under "Package Details" -> "Functions", it lists Get-MgDeviceAppMgtMobileAppInstallSummary, but PowerShell tells me it's not available.

I've tried under both PowerShell Core 7.1 and Windows PowerShell 5.1 with the same result.

Is it because [installSummary](https://docs.microsoft.com/en-us/graph/api/intune-apps-mobileappinstallsummary-get?view=graph-rest-beta) is a beta endpoint?  I think I read something about having to use Connect-MgGraph differently if I want to use a Beta endpoint?

I'm trying to get the install status for Win32Apps, and I'm guessing this is the method I should be using; is there a better way?

**Comment by peombwa** [comment]
The command you are looking for is [only available in beta](https://docs.microsoft.com/en-us/graph/api/intune-apps-mobileappinstallsummary-get?view=graph-rest-beta). You'll need to switch to beta profile as described here - https://docs.microsoft.com/en-us/graph/powershell/get-started#api-version.

You can also use `Find-MgGraphCommand -Command` to find where a command lives and what it calls as such:
``` powershell
➜ Find-MgGraphCommand -Command "Get-MgDeviceAppMgtMobileAppInstallSummary"

   APIVersion: beta

Command                                   Module                      Method URI
-------                                   ------                      ------ ---
Get-MgDeviceAppMgtMobileAppInstallSummary Devices.CorporateManagement GET    /deviceAppManagement/mobileApps/{mobileApp-id}/installSumma…

```
