### ISSUE TITLE
New-MgGroupMember* fails with "Insufficient privileges to complete the operation" even if executed as an owner of the target AAD group

### ISSUE THREAD

**Issue by scratch85** [microsoftgraph/msgraph-sdk-powershell#1052]
Migrating from AzureAD (Add-AzureADGroupMember), I am using [Example 1: Add a member to a group
](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=powershell#example-1-add-a-member-to-a-group) from the docs, in my code to add AAD users/applications to an AAD group.

```
$params = @{
	"@odata.id" = ("https://graph.microsoft.com/v1.0/directoryObjects/{0}" -f $PrincipalId)
}
New-MgGroupMemberByRef -GroupId $groupId -BodyParameter $params
```

I also tried it using

`New-MgGroupMember -GroupId $groupId -DirectoryObjectId $PrincipalId`

The code ends up in "Insufficient privileges to complete the operation", even the user executing the code is owner of the target AAD group.
What could be missing to make this work again?!

**Comment by peombwa** [comment]
@scratch85, have you consented to the required permission(s) in https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=powershell#permissions? With Microsoft Graph, customers must consent to permissions before using an API.

**Comment by scratch85** [comment]
Hi, sorry for my late response. I understand I would need to give my app the following additional permissions: "`Delegated GroupMember.ReadWrite.All`"

The Docs say:
**GroupMember.ReadWrite.All**
`Allows the app to list groups, read basic properties, read and update the membership of the groups the signed-in user has access to. Group properties and owners cannot be updated and groups cannot be deleted.`

As it is a delegated permission, this still means I can only edit membership for aad groups where my user is "owner", correct?
Maybe it is the part "read and update the membership of the groups the signed-in user has access to" that confuses me.

**Comment by scratch85** [comment]
up

**Comment by kjkent** [comment]
Unsure if this is helpful -- but I'm having a similar issue trying to add a member to a group using the Graph API from a POST request, so it may be an issue with Graph:

```shell
{
  code: 'Authorization_RequestDenied',
  message: 'Insufficient privileges to complete the operation.',
  innerError: {
    date: '2022-07-21T12:54:48',
    'request-id': 'fccb7806-efb8-4abf-ace4-651c642b4f6f',
    'client-request-id': 'fccb7806-efb8-4abf-ace4-651c642b4f6f'
  }
}
```

**Comment by aaron-asdf** [comment]
I am also experiencing an issue with this Powershell Graph API with other Powershell Graph APIs working. Turning on Azure AD Graph permissions is now disabled for service principals so until this is resolved it appears there is no way to add users to group via powershell (I.e. the Az.Resources and AzureAD modules aren't useful in my use case given that I can no longer grant permission to use them).

Example below with lots of permissions added for testing:

PS C:\Windows\system32> (Get-MgContext).Scopes
DeviceManagementServiceConfig.ReadWrite.All
Device.Read.All
Device.ReadWrite.All
Group.Read.All
Directory.ReadWrite.All
Group.ReadWrite.All
Directory.Read.All
GroupMember.Read.All
RoleManagement.ReadWrite.Directory
GroupMember.ReadWrite.All

PS C:\Windows\system32> New-MgGroupMember -GroupId $az_group.id -DirectoryObjectId $aad_dev.Id
New-MgGroupMember : Insufficient privileges to complete the operation.

**Comment by pflatt** [comment]
I just wanted to note that I'm seeing the same behavior described by aaron-asdf in this post: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1052#issuecomment-1209359492
It doesn't appear that the New-MgGroupMember commandlet is working at this time, at least when using app permissions. Please consider reopening and triaging this issue.

**Comment by itpropro** [comment]
This is a bug in the PowerShell module, can you please reopen and triage @peombwa ?

**Comment by ondragcze** [comment]
Finally got to migrate my automations from AzureAD PowerShell module, as it is going to be deprecated soon, to MS Graph. Synchronisation of nested on-prem AD groups to Azure AD groups is one of the most used in my company so this New-MgGroupMember or Remove-MgGroupMember is quite important if I want to migrate. 
Can I ask @peombwa what is the status here? Thanks!

**Comment by seanlillis** [comment]
I am seeing the same issue, keen for an update from @peombwa

**Comment by The-House** [comment]
I also am seeing this issue, specifically for groups that I am an owner on. Sometimes on others, but if run multiple times, can intermittently work which is strange.

**Comment by peombwa** [comment]
Sorry for the late response.

Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner. This problem appears to be a service related as shown in the repro steps at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1052#issuecomment-1209359492:
> PS C:\Windows\system32> (Get-MgContext).Scopes
DeviceManagementServiceConfig.ReadWrite.All
Device.Read.All
Device.ReadWrite.All
Group.Read.All
Directory.ReadWrite.All
Group.ReadWrite.All
Directory.Read.All
GroupMember.Read.All
RoleManagement.ReadWrite.Directory
GroupMember.ReadWrite.All:

> PS C:\Windows\system32> New-MgGroupMember -GroupId $az_group.id -DirectoryObjectId $aad_dev.Id
New-MgGroupMember : Insufficient privileges to complete the operation.

You've already consented to the required permission (assuming ` $aad_dev.Id` is a group), but the API is failing with `403 - Insufficient privileges to complete the operation`. You can see this by running `New-MgGroupMember` with `-Debug`. Remember to include the `requestId` and `date` of the failing request in your question/ticket. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details.

Permission validation is done by the API, not the SDK.

This repository is intended for issues related to the functionality of the module. We may not be the best place to answer some queries that are tied to the functionality of the API.

**Comment by brian975** [comment]
I finally solved this problem yesterday by requesting the permission **_Directory.AccessAsUser.All_**
It's totally undocumented, but I have verified it several times. It seems that, after your PowerShell session authenticates, it still needs permissions to pass that authentication to the Graph API, which is what Directory.AccessAsUser.All all does.

PS C:\Scripts\NewUser> Find-MgGraphPermission Directory.AccessAsUser.All

   PermissionType: Delegated

Id                                   Consent Name                       Description
--                                   ------- ----                       -----------
0e263e50-5827-48a4-b97c-d940288653c7 Admin   Directory.AccessAsUser.All Allows the app to have the same access to information in the directory as the signed-in user.

PS C:\Scripts\NewUser> Get-MgContext

ClientId              : xxxxxxxxxxxxxxxxxx
TenantId              : xxxxxxxxxxxxxxxxxx
CertificateThumbprint :
Scopes                : {Directory.AccessAsUser.All, Directory.ReadWrite.All, Group.ReadWrite.All, GroupMember.ReadWrite.All…}
AuthType              : Delegated
AuthProviderType      : InteractiveAuthenticationProvider
CertificateName       :
Account               : xxxxxxxxxxxxxxxxxx
AppName               : Microsoft Graph Command Line Tools
ContextScope          : CurrentUser
Certificate           :
PSHostVersion         : 7.3.4

PS C:\Scripts\NewUser> Get-MgContext|select -ExpandProperty Scopes
Directory.AccessAsUser.All
Directory.ReadWrite.All
Group.ReadWrite.All
GroupMember.ReadWrite.All
openid
Organization.ReadWrite.All
PrivilegedAccess.ReadWrite.AzureADGroup
profile
User.ReadWrite.All
email

**Comment by ondragcze** [comment]
Hi all, 

after a long time on MS support I was able to resolve the issue via assigning one more permission: _RoleManagement.ReadWrite.Directory_.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/127087416/9b6e7487-8a90-47be-b7ba-c9314536e6e4)

Hopefully it will help you also.
Regards!

**Comment by jantari** [comment]
Another reason why you may get an inexplicable

```
Insufficient privileges to complete the operation.
```

error from `New-MgGroupMember` is: You may be trying to add a member to a *DYNAMIC* group 🤦 

I just ran into that and spent a few minutes figuring that out. Thought I'd add it here in case anyone else makes the same mistake. I don't think the error is optimal for this case but yea, it makes sense why I couldn't do that 😄

**Comment by ved-leachim** [comment]
I had the same problem with the `New-MgGroupMember` Command using the **GroupMember.ReadWrite.All** Application Permissions only. The description of the Permission implies that it would be sufficient for adding or removing members to a AAD Security group. But for me it just started to work with a MI after adding the **Group.ReadWrite.All** Permission as well.

An actually if you read the [documentation](https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#permissions) carefully, it states that both Permissions are required.

**Comment by Sean-FFC** [comment]
Directory.AccessAsUser.All was what worked for me. I did not need Group.ReadWrite.All

**Comment by dwarfered** [comment]
Yep, can confirm, for a user altering the membership of a Role Assignable group they own, they need Directory.AccessAsUser.All.
They do not need this 'RoleManagement.ReadWrite.Directory' that is too broad.

If this is an application (Service Principal or Managed Identity) you don't need any App Permissions, ownership of the group is all and make the graph call.
