### ISSUE TITLE
Graph API/SDK - SharePoint List item filter not working 

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoftgraph/msgraph-sdk-powershell#1059]
Hello Team,

I am not able to use filter for SharePoint Graph API/SDK CMD

Here I am trying to use Graph API

Invoke-MgGraphRequest -Method GET -Uri "https://graph.microsoft.com/v1.0/sites/$SPOSiteID/lists/$SPOServicePrincipleCleanupList/items?`$filter=Name eq 'test'"
Error Message: 500 Internal Server Error and  General exception while processing

#Graph SDK
Get-MgSiteListItem -ListId $ListID -SiteId $siteID -Filter "Title eq 'test'"
Error Message  : Get-MgSiteListItem_List1 : General exception while processing

Both are failing to get the result 

Please guide me to resolve this issue

Thanks ,
Jitendra Sharma

**Comment by lkubat** [comment]
Are you sure you're not trying to do `$filter=fields/Title eq 'test'` instead of `$filter=Name eq 'test'`?

**Comment by sharmajitendralal** [comment]
Thanks for your help now its working using this $filter=fields/Title eq 'test'
