### ISSUE TITLE
Installation of Microsoft.Graph 0.1.1 takes more than 10 mins on a PC with nvme ssd

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoftgraph/msgraph-sdk-powershell#106]
I installed Microsoft.Graph 0.1.1 on a 6 core laptop with nvme ssd but it took well over 10 mins to even install that I decided to just leave it. Import-Module also takes a long time, on the order of 5 mins or so.

**Comment by MIchaelMainer** [comment]
We agree that it takes a long time. If speed is an issue, please install only the modules you need. 

Here are the search results for all of the individual packages:
https://www.powershellgallery.com/packages?q=microsoft.graph

**Comment by tristanbarcelon** [comment]
Our company has onboarded AD accounts via Azure AD. That being the scenario, which of these graph modules do I need to install if all I needed to do was to find a user in Azure AD and then use that entry to query related entries in Azure Devops created by that user? For example, I wanted to use this [pull requests api](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/get%20pull%20requests?view=azure-devops-rest-5.1#uri-parameters) and supply the Azure AD user as searchCriteria.creatorId.

**Comment by peombwa** [comment]
@tristanbarcelon. If all you need is it find a user in Azure AD, then [Microsoft.Graph.Users](https://www.powershellgallery.com/packages/Microsoft.Graph.Users/1.2.0) module is all you need.

**Comment by peombwa** [comment]
This being tacked, and will be fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/428
