### ISSUE TITLE
Feature Request: Privileged Access Group cmdlets

### ISSUE THREAD

**Issue by aydeisen** [microsoftgraph/msgraph-sdk-powershell#1064]
Are there any plans to add cmdlets to query and manipulate eligibility assignments for [privileged access groups](https://docs.microsoft.com/azure/active-directory/privileged-identity-management/groups-features)?

My specific use-case is for audit reporting.  For Privileged Access Groups, those assigned as eligible won't show up as a group member unless the user has activated the privileged access group and associated privileges.  It makes it difficult to programmatically determine which accounts have the ability to activate certain roles.

**Comment by peombwa** [comment]
@aydeisen, I believe Microsoft Graph API does not currently support this. You can find all the supported PIM-related APIs at https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagementv3-overview?view=graph-rest-beta&preserve-view=true.

Please submit this as a feature request at https://developer.microsoft.com/en-us/graph/support for the workload to consider your scenario. for the workload to consider your scenario. As an SDK, there is little we can do if the service does not support an API.
