### ISSUE TITLE
 Invoke-MgGraphRequest

### ISSUE THREAD

**Issue by joerodgers** [microsoftgraph/msgraph-sdk-powershell#1086]
Executing the following command:

`Invoke-MgGraphRequest -Uri 'https://graph.microsoft.com/v1.0/sites?search=*'`

Results in this HTTP request being executed:

`https://graph.microsoft.com/v1.0/sites?$search=*`

Notice, the $ sign being added before search=, which is an invalid query and results in a HTTP 400 with details:

```
{
	"error": {
		"code": "BadRequest",
		"message": "Syntax error: character '*' is not valid at position 0 in '*'.",
		"innerError": {
			"date": "2022-02-11T18:05:47",
			"request-id": "45141d5e-2b79-4466-8d9d-f4a64ab72170",
			"client-request-id": "45141d5e-2b79-4466-8d9d-f4a64ab72170"
		}
	}
}	
```	

Module Version

```
ModuleType Version    Name                                ExportedCommands                                                                                                            
---------- -------    ----                                ----------------                                                                                                            
Script     1.9.2      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext...}                                                  

```

**Comment by timayabi2020** [comment]
> Executing the following command:
> 
> `Invoke-MgGraphRequest -Uri 'https://graph.microsoft.com/v1.0/sites?search=*'`
> 
> Results in this HTTP request being executed:
> 
> `https://graph.microsoft.com/v1.0/sites?$search=*`
> 
> Notice, the $ sign being added before search=, which is an invalid query and results in a HTTP 400 with details:
> 
> ```
> {
> 	"error": {
> 		"code": "BadRequest",
> 		"message": "Syntax error: character '*' is not valid at position 0 in '*'.",
> 		"innerError": {
> 			"date": "2022-02-11T18:05:47",
> 			"request-id": "45141d5e-2b79-4466-8d9d-f4a64ab72170",
> 			"client-request-id": "45141d5e-2b79-4466-8d9d-f4a64ab72170"
> 		}
> 	}
> }	
> ```
> 
> Module Version
> 
> ```
> ModuleType Version    Name                                ExportedCommands                                                                                                            
> ---------- -------    ----                                ----------------                                                                                                            
> Script     1.9.2      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext...}                                                  
> ```

@joerodgers Kindly let me know your results when you try running the command below.

Import-Module Microsoft.Graph.Sites

Get-MgSite -Search "*"

**Comment by timayabi2020** [comment]
@joerodgers for any queries involving sites, Kindly use the Sites cmdlets as per the documentation https://docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-1.0&tabs=http


![Image](https://user-images.githubusercontent.com/10947120/169844528-88a9bd05-7fd8-4a4b-9ce2-3c6d4642bf76.png)
