### ISSUE TITLE
Searching for equivalent command

### ISSUE THREAD

**Issue by Tiberriver256** [microsoftgraph/msgraph-sdk-powershell#1090]
I was directed here via [this issue](https://github.com/Azure/azure-docs-powershell-azuread/issues/759https://github.com/Azure/azure-docs-powershell-azuread/issues/759).

I am looking for the equivalent to this command here:

```pwsh
Set-MsolUserPassword -UserPrincipalName juser@techwizard.cloud -ForceChangePassword:$true
```

The typical use-case for this command is to force users to change their password the next time they log in. In widespread security incidents, it's even commonly referred to as [a method for forcing all users to change their passwords](https://www.michev.info/Blog/Post/1419/force-password-change-for-all-users-in-office-365). As explained in [this blog post](https://techwizard.cloud/2021/03/08/tip-office-365-force-password-change-without-updating-existing-password/), there was unfortunately never an equivalent command created for the AzureAD PowerShell module.

With Azure AD Graph being disabled in June, I'm hoping to find an equivalent command in the newer supported modules.

**Comment by peombwa** [comment]
@Tiberriver256, this can be done in Microsoft Graph by updating the `PasswordProfile` of a `User`. The command/API you are looking for is https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=powershell#example-3-update-the-passwordprofile-of-a-user-to-reset-their-password.

The `Password` property in the `PasswordProfile` is optional. Setting `ForceChangePasswordNextSignIn` to `$true` should be enough to trigger a reset from my testing:
``` powershell
Update-MgUser -UserId $UserId -PasswordProfile @{ ForceChangePasswordNextSignIn = $true }
```

**Comment by Tiberriver256** [comment]
Thank you!
