### ISSUE TITLE
Selecting fields with Get-MgSiteListItem

### ISSUE THREAD

**Issue by lkubat** [microsoftgraph/msgraph-sdk-powershell#1094]
If I want to select all items in a list and get their Id and Title, in graph api I can use:
https://graph.microsoft.com/v1.0/sites/{siteId}/lists/{listId}/items/?expand=fields($select=title)

But within the PowerShell api, I cannot use 
``Get-MgSiteListItem -SiteId {siteId} -ListId {listId} -Expand "fields(`$select=title)" -All``
It does not throw an error, but the result's Fields property does not contain the additional fields.  I have tried a variety of syntaxes.

For anyone that comes across this issue, here is a workaround till it can be fixed:

```
$reqUrl = "https://graph.microsoft.com/v1.0/sites/$($siteId)/lists/$($listId)/items/?expand=fields(`$select=Title)&`$top=999"
for ($page = Invoke-MgGraphRequest -Uri $reqUrl; $null -ne $page; $page = If ($page.ContainsKey("@odata.nextLink")) {Invoke-MgGraphRequest -Uri $page.'@odata.nextLink'} Else { $null }) {
    foreach ($item in $page.value) {
        Write-Output "$($item.id): $($item.fields.Title)"
    }
}
```

**Comment by peombwa** [comment]
@lkubat, since [FieldValueSet](https://docs.microsoft.com/en-us/graph/api/resources/fieldvalueset?view=graph-rest-beta) is an OpenType (user-defined key-value pairs), you can find the properties of the field in the additionalProprties bag as shown below:
``` powershell
$ListItems = Get-MgSiteListItem -SiteId {siteId} -ListId {listId} -Expand "fields(`$select=title)" -All
$ListItems | %{ Write-Output "$($_.id): $($_.fields.AdditionalProperties.Title)" }
```

**Comment by JeremyTBradshaw** [comment]
Hi @peombwa - hope all is well.  FYI, the documentation for Get-MgSiteListItem does not show ``` `$select``` as you have in your example (which solved my issue).  The example there shows ```-ExpandProperty "fields(select=.......)```

If we follow their example, we get this:
```powershell
Get-MgSiteListItem : Parsing OData Select and Expand failed: Term '(select=ID,WhenCreated,Created)' is not valid in a $select or $expand
expression.
Status: 400 (BadRequest)
ErrorCode: BadRequest
```
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.sites/get-mgsitelistitem?view=graph-powershell-1.0#example-1-code-snippet

Just as a comment on Get-MgSiteListItem - having to retrieve the custom fields this way, via fields.additionalproperties, feels like something easier has been made far more difficult.  If I just send an Invoke-WebRequest / Invoke-RestMethod, all the columns are there in value.fields and even including the ID column/field, which is NOT there in fields.additionalproperties from Get-MgSiteListItem.

Shouldn't it be sort of illegal to have these PS commands making it so much more difficult?  We have to build a custom object out of this stuff now if we want to have all the columns and ID in a new PSCustomObject.

**Comment by JeremyTBradshaw** [comment]
As FYI, to get an array that is all the fields including ID, and their values (supposing $spListItems is the original request response):
```powershell
$splistItemFields = foreach ($item in $splistItems.fields) {
    
    New-Object -TypeName PSObject -Property ($item.AdditionalProperties) |
    Add-Member -NotePropertyName ID -NotePropertyValue $item.ID -PassThru
}
```
I hope this helps somebody who wanted to complete this task and come out with a simple array with the fields, including ID.

**Comment by JeremyTBradshaw** [comment]
@Titus1024  I don't see ID in the list.
