### ISSUE TITLE
Investigate paging of collections

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#11]
[AB#4595](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4595)

**Comment by peombwa** [comment]
Investigate how to support paging of collections using NextLink.

**Comment by ChrisB9907** [comment]
There is currently no way to get more than 999 users without paging and the -skip param isn't available on Get-MgUser

**Comment by darrelmiller** [comment]
@ChrisB9907 That is correct.  We have prototyped a solution that enables automatic paging and once we figure out how to turn it off by default, we will add it to our packages.

**Comment by Windos** [comment]
My preference is adding a -All switch parameter that returns all.

The key to avoid backlash, regardless of the name that ends up being used is **not** making it a Boolean parameter.

I [really](https://twitter.com/WindosNZ/status/1016791902841028609?s=20) [hate](https://twitter.com/WindosNZ/status/1104863709954891776?s=20) AzureAD's [implementation](https://twitter.com/WindosNZ/status/1220231277644677120?s=20) with ["-All $true"](https://twitter.com/WindosNZ/status/1236782220691398657)

**Comment by darrelmiller** [comment]
## Option 1

Get-MgUser   -> Return first page
Get-MgUser -top 100    -> return a page of 100
Get-MgUser -top All    -> would page all results
Get-MgUser -top 2000    -> would page all results up to 2000
Get-MgUser -Limit 2000    -> Limit is an alias top

Can we make paging off by default?
Can we bypass the top paramter integer datatype to add support for all?
Can we implement our on limit on a set of pages.

## Option 2

Get-MgUser   -> Return first page
Get-MgUser -top 100    -> return a page of 100
Get-MgUser -All   -> return all pages
Get-MgUser -All -top 2000   -> return all pages up to 2000
Get-MgUser -top 2000   -> Values larger than 999 cause implicit -All
Get-MgUser -Limit 2000   -> Limit is an alias to top

**Comment by ChrisB9907** [comment]
I would say Option 2 would be better as it would be consistent with the existing Graph API (unless that is planning on being changed as well) or as something that would be better (in my eyes anyhow) give the user the ability to pick as many pages they want to get back, defaulting the users to 100 per page something like Get-MgUser -PageLimit 1 (this would also be the default if the parameter is excluded) and to get all results Get-MgUser -All. This might also help out slower connections as less data per page is being returned.

**Comment by rbalsleyMSFT** [comment]
@peombwa @darrelmiller should -skip $true work for Get-MgAuditLogSignIn? If it's supposed to work, how do I set AllowedQueryOptions?

```
PS C:\Windows\system32> Get-MgAuditLogSignIn -Skip $True | export-csv -Path c:\temp\signin.csv -Force
Get-MgAuditLogSignIn : Query option 'Skip' is not allowed. To allow it, set the 'AllowedQueryOptions' property on
EnableQueryAttribute or QueryValidationSettings.
At line:1 char:1
+ Get-MgAuditLogSignIn -Skip $True | export-csv -Path c:\temp\signin.cs ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...= , Expand =  }:<>f__AnonymousType2`8) [Get-MgAudit
   LogSignIn_List], Exception
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List
```

**Comment by BrianTJackett** [comment]
I prefer option 2 approach.  I am most familiar with the way PowerShell modules for SharePoint Online and Exchange Online handle this.  Both return a default number of results but then require adding a parameter (-Limit  and -ResultSize respectively) for additional results.  I don't like the inconsistency where SPO has -Limit "All" and EXO has -ResultSize "Unlimited" to get all results but understand built by completely different teams.  Hopefully other teams / modules have an example or common consensus of the preferred approach.

**Comment by peombwa** [comment]
@rbalsleyMSFT, that looks like service issue. Please post it on StackOverflow with `intune`, `microsoft-graph-intune` and `microsoftgraph` tags so that the workload owners can respond to it. The issue can also be reproed on Graph Explorer.
