### ISSUE TITLE
Update-MgUserEvent throws expeption but is running fine

### ISSUE THREAD

**Issue by fabianseither** [microsoftgraph/msgraph-sdk-powershell#110]
When running  `Update-MgUserEvent -UserId X -EventId X -Subject  X`  i get the folling error but subject gets changed as expected.

```
Update-MgUserEvent : The server responded with an unrecognized response, Status: OK
At line:11 char:10
+          Update-MgUserEvent -UserId $Mail -EventId $_.Id -Subject $_. ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = surf...oftGraphEvent }:<>f__AnonymousType513) [Update-MgUserEvent_UpdateExpanded], RestException1
    + FullyQualifiedErrorId : OK,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUserEvent_UpdateExpanded
```

**Comment by dolauli** [comment]
Please add the switch '-debug' for debug info when running the command. Besides, it is better if the swagger file could be provided.

**Comment by peombwa** [comment]
The OpenAPI [document](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/Beta/Users.Calendar.yml#L17877) and our [docs](https://docs.microsoft.com/en-us/graph/api/group-update-event?view=graph-rest-beta&tabs=http#response-1) page say the service should return HTTP status code 204, yet what's returned is a 200 status code. This is what causes the `unrecognized response` error. cc @dolauli 

The same issue is also present in `Update-MgUserCalendar`. The service returns a 200, yet the [OpenAPI doc](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/Beta/Users.Calendar.yml#L100) say it should return a 204.

@darrelmiller Is there a way to ensure Graph explorer API returns the proper HTTP status code in the OpenAPI docs?

**Comment by darrelmiller** [comment]
Removing the OpenApi-Dependency label because this needs to be fixed by the PowerShell SDK handling all the status codes and not relying on them being documented in the OpenAPI description.

**Comment by peombwa** [comment]
AB#5066
