### ISSUE TITLE
Users should use Authentication Providers to securely connect to Microsoft Graph

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/msgraph-sdk-powershell#1104]

**Comment by peombwa** [comment]
@sebastienlevert, we don't expose authentication providers in PowerShell. The auth process is wrapped in an easy to use command, `Connect-MgGraph`, that calls the .NET auth providers under the cover. See https://github.com/microsoftgraph/msgraph-sdk-powershell/wiki/Generation-Process#introduction.

**Comment by sebastienlevert** [comment]
This can be deleted 😁 It's me trying Zenhub and creating issues in the default repo. Sorry for the useless noise!

**Comment by peombwa** [comment]
No worries!
