### ISSUE TITLE
Powershell Microsoft.Graph- How to set MaxRetry

### ISSUE THREAD

**Issue by MarkDordoy** [microsoftgraph/msgraph-sdk-powershell#1106]
Is there a way to set the max retry value for the Microsoft.Graph powershell modules. 

I'm hitting an issue from time to time, where a particular cmdlet retries 3 times then fails. Ideally i'd like a way to increase this somehow. Is this supported? 

[This](https://docs.microsoft.com/en-us/dotnet/api/microsoft.graph.retryhandleroption.maxretry?view=graph-core-dotnet) supports the theory that it is set to 3 and backs up what im seeing. 

Thanks

**Comment by peombwa** [comment]
@MarkDordoy, the PowerShell SDK does currently not support this. The MaxRetry is currently locked at 3, and the implementation is based on https://microsoftgraph.github.io/msgraph-sdk-design/middleware/RetryHandler.html.

Which command are you using? Ideally, the service should respond with a `retry-after` header that SDK will honor.

We will consider exposing a way for customers to set their preferred MaxRetry. This will likely be through a global variable.

**Comment by MarkDordoy** [comment]
I came across this issue when using this call: `Get-MgAuditLogDirectoryAudit -Filter "targetResources/any(t: t/id eq '$($user.Id)') and activityDisplayName eq 'Enable account' and activityDateTime gt $gracePeriodStr" -Top 1`

Ifs fine for a while, but i was running this within a foreach-Object -Parallel script block so i guess i was hitting 429s and 3 retries was not enough (I think).

**Comment by maisarissi** [comment]
@peombwa I have the impression the max retries and retry after was already covered by another PR of the v2 work you did. Just checking.

**Comment by peombwa** [comment]
@maisarissi, this is still an open feature request. It hasn't been implemented in v2.

**Comment by ArmaanMcleod** [comment]
Hi @peombwa. When will this be available for `beta` v2 commands?
