### ISSUE TITLE
Unable to access deviceEnrollmentConfigurations via Get-IntuneDeviceEnrollmentConfiguration or Invoke-MSGraphRequest

### ISSUE THREAD

**Issue by ThoughtContagion** [microsoftgraph/msgraph-sdk-powershell#1116]
This recently broke, as it was working a little more than a week ago.
When using Application Registration authentication accessing the Device Enrollment Configurations results in a '403 Forbidden' error.

```
\"Message\": \"Application is not authorized to perform this operation as called in app only context but does not have application
permissions configured. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000
```

I have run the following to authenticate:

```
Update-MSGraphEnvironment -AppId $appID -AuthUrl "https://login.microsoftonline.com/$organization"
Connect-MsGraph -ClientSecret $clientSecret
```

I know the authentication works and the permissions are correct 
```
Get-MgContext | Select -ExpandProperty Scopes | findstr -i "device"
```
returns
```
DeviceManagementManagedDevices.Read.All
Device.Read.All
DeviceManagementServiceConfig.Read.All
DeviceManagementServiceConfig.ReadWrite.All
DeviceManagementRBAC.Read.All
DeviceManagementConfiguration.Read.All
DeviceManagementApps.Read.All
TeamworkDevice.Read.All
```

Other commands in the same module work without issue, it seems to be only this command.
Others are seeing this as well.
https://stackoverflow.com/questions/71240915/ms-graph-cannot-interact-with-deviceenrollmentconfigurations-using-app-registra

**Comment by peombwa** [comment]
@ThoughtContagion, it looks like you are not using our SDK. [Connect-MsGraph](https://www.powershellgallery.com/packages/Microsoft.Graph.Intune/6.1907.1.0) is not a Microsoft Graph PowerShell SDK command. Everything works as expected when using the [Microsoft Graph PowerShell SDK](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-beta):
``` powershell
Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All, DeviceManagementServiceConfig.Read.All"
Get-MgDeviceManagementDeviceEnrollmentConfiguration
```
![image](https://user-images.githubusercontent.com/7061532/156268739-88bcd24c-4806-4f91-8d13-3b36ae9ffc53.png)

**Comment by roelrulezz** [comment]
It is working for user authentication (delegated), but not for application authentication (Azure registered app).
