### ISSUE TITLE
401 or 403 on deviceManagement/deviceCompliancePolicies endpoint

### ISSUE THREAD

**Issue by stephen-liongard** [microsoftgraph/msgraph-sdk-powershell#1120]
Get requests to https://graph.microsoft.com/v1.0/deviceManagement/deviceCompliancePolicies  and GET /v1.0/deviceManagement/deviceEnrollmentConfigurations.
These intune specific endpoints began having issues around 2/12-2/13 across many customers that run as application with all the appropriate permission scopes turned on and consented. These have worked for over a year+ and suddenly started giving forbidden/ permission errors.
Have seen a few different posts with similar issues and there is definitely some kind of change or outage on the microsoft side.

**Comment by peombwa** [comment]
@stephen-liongard, sorry about that. For service issues, please go to https://developer.microsoft.com/en-us/graph/support to open a question/support ticket.
