### ISSUE TITLE
Get-MgSiteListItem does not return Number field value

### ISSUE THREAD

**Issue by Attila-FIN** [microsoftgraph/msgraph-sdk-powershell#1126]
List items with all the field values can be received by executing

`Get-MgSiteListItem -SiteId $SiteiD -ListId $ListId -All -ExpandProperty Fields`

However, when a SharePoint list field is a **Number** type, the returned value is **empty**.
Changing the field type in SharePoint to **Singe line of text** the correct value is returned. 

Module:    Microsoft.Graph.Sites
Module version: 1.9.2

**Comment by peombwa** [comment]
@Attila-FIN, this works on my end without any issue. From my testing, it looks like the service won't return a field if it has no value:

![image](https://user-images.githubusercontent.com/7061532/156850376-5e0da30e-f379-468f-b84f-519ae1945e3e.png)
![image](https://user-images.githubusercontent.com/7061532/156850468-c82114d5-74c9-401d-ba1c-8d89347180fe.png)

**Comment by Attila-FIN** [comment]
This is the result of  $ListItems[0].Fields.AdditionalProperties  when having the columns as single line of text:

![image](https://user-images.githubusercontent.com/26542497/156897843-93beefe3-492a-4501-8c15-d91ae951935a.png)

In SharePoint it look like this:

![image](https://user-images.githubusercontent.com/26542497/156897945-4ab37530-f82d-4c1b-a0ab-a6d02e2c8a3e.png)


**If I change the columns to Number, the result in PowerShell:**

![image](https://user-images.githubusercontent.com/26542497/156897971-b918f5ea-43a0-4a95-abaf-cbe630ede497.png)

In SharePoint it look like this:

![image](https://user-images.githubusercontent.com/26542497/156898061-3a85c517-d431-4938-8fff-cb6342138148.png)

If I change back to text, the columns values are available in PowerShell.

**Comment by peombwa** [comment]
This behavior is still not reproducible using the latest version of the module.

Steps followed:
1. Add PostCode column of single line of text type to a list item. PostCode is returned in `AdditionalProperties` as string:
![image](https://user-images.githubusercontent.com/7061532/217924570-e2b1a5fc-2c88-4982-a3e1-05a64a775bd8.png)
![image](https://user-images.githubusercontent.com/7061532/217924587-988781cf-e2ef-4d1f-89a5-76c549043a24.png)

2. Change PostCode column to Number. PostCode is returned in `AdditionalProperties` as single:
![image](https://user-images.githubusercontent.com/7061532/217924758-f8f6922e-584f-4ede-a232-e8ae097b8d1c.png)
![image](https://user-images.githubusercontent.com/7061532/217924775-3c8a4ba0-00be-4d5f-93b9-cf0eca001f66.png)

Please use `-Debug` switch to confirm that the field is included in the response from the service.

**Comment by andersidahl** [comment]
I am experiencing the exact same thing. I am on the newest version of Graph.
