### ISSUE TITLE
Update-MgUserEvent - Can´t Update Event with Parameter

### ISSUE THREAD

**Issue by StefanSchulzeITP** [microsoftgraph/msgraph-sdk-powershell#1127]
When running the Command:
`Update-MgUserEvent -UserId $User.Id -EventId $UserEvent.Id -Subject "Test" ` 
im getting the following error: 
`Update-MgUserEvent : The property 'subject' does not exist on type 'Microsoft.OutlookServices.Event'. Make sure to only use property names that are defined by the type or mark the type as open type. REST APIs for this mailbox are currently in preview. You can find more 
information about the preview REST APIs at https://dev.outlook.com/.`

When just running the Command:
`Update-MgUserEvent -UserId $User.Id -EventId $UserEvent.Id `
i don´t get an Issue 

Creating a new Event is possible when i don´t provide any parameters like Subject.

Pulling all information is also successfully by using the command
`Get-MgUserEvent -UserId $User.Id -EventId $UserEvent.Id` 

Environment
- Exchange Hybrid
- Exchange Server 2016 CU 20
- Mailbox OnPremise
- User Licence activ
- PowerShell Module
- `1.9.2      Microsoft.Graph.Authentication; 1.9.2      Microsoft.Graph.Calendar; 1.9.2      Microsoft.Graph.CloudCommunications; 1.9.2      Microsoft.Graph.Users`

**Comment by peombwa** [comment]
@StefanSchulzeITP, from the error message, it looks like the API/command you are trying to use is not yet available for mailboxes in hybrid deployments.
>Only v1.0 of the Mail, Calendar and Contacts API are available for mailboxes in hybrid deployments. Other v1.0 API sets, such as the Groups API, or APIs in other versions, are not. If you attempt to use an API that is not part of the supported set in a hybrid deployment, you will get the following error message:

> "REST APIs for this mailbox are currently in preview. You can find more information about the preview REST APIs at https://dev.outlook.com."

Please note that the availability of REST APIs in hybrid deployments is currently in preview. See https://docs.microsoft.com/en-us/graph/hybrid-rest-support.

For now, you can open a feature request to the service team at https://developer.microsoft.com/en-us/graph/support.
