### ISSUE TITLE
All the reference content autogenerated the SDK has this build error 'disallowed-html-tag' returned as part of the build report on any PR in this docset.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1135]
[This article](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/disallowed-html-tag?branch=main) contains info on how to remedy this error. @georgend 

See [an example ](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C1%5Cc847a38e-33de-63ed-4ac9-5917fc04e540%5CPullRequest%5C202203010812458767-31%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-01T08%3A19%3A54Z&sr=b&sp=r&sig=xTpVGOilzbZXiR9SZ4dxOjkiqYIhCa5BjWaxg5Kssfo%3D)of this error in a sample build report.

**Comment by msewaweru** [comment]
Moved this issue to the PowerShell docs. https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/44

**Comment by georgend** [comment]
The issue needs to resolved by escaping the properties in [AutoRest.PowerShell](https://github.com/Azure/autorest.powershell/issues/928) during docs generation.

**Comment by timayabi2020** [comment]
This [PR](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/76) sorted out the issue. It includes a powershell script locally run to address those validation errors i.e 'disallowed-html-tag'
