### ISSUE TITLE
Get-Help Reset-MgUserPassword returns 404 error

### ISSUE THREAD

**Issue by iBowler1995** [microsoftgraph/msgraph-sdk-powershell#1137]
Trying to set up a password reset form for my technicians, but was a bit unclear on context/parameters for Reset-MgUserPassword. Get-Help returns 404, and I can't seem to find a link anywhere to MS documentation on it either.

**Comment by iBowler1995** [comment]
Hi peombwa, I was going off of this Microsoft Documentation: https://docs.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-beta#devices

I'm unable to use the Update-MgUser route because that command, for whatever reason, returns insufficient privileges, even though my account has all read AND write privileges for User and UserAuthenticationMethod permission branches

**Comment by peombwa** [comment]
The documentation is wrong and should be updated. I'll bring it up to the docs team.

Have you consented to the required permission (`Directory.AccessAsUser.All`)?
> The calling user must be assigned the Directory.AccessAsUser.All delegated permission to update this property.

I'm able to perform the request on my tenant with the required delegated permissions.
