### ISSUE TITLE
Get-MgSiteByPath requires a SiteId which defeats the purpose

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-sdk-powershell#1139]
Command: Get-MgSiteByPath, module: Microsoft.Graph.Sites

When I run Get-MgSiteByPath, SiteId is a required property. It should not be required, since the goal of the command is to retrieve a site ID by a site's path.

**Comment by peombwa** [comment]
@joshtransient, you can use `Find-MgGraphCommand` to see which API a Microsoft Graph command calls. In this case, `Get-MgSiteByPath` calls `/sites/{site-id}/getByPath(path='{path}')`, which is valid API path according to the service metadata.

Please note that you can use `Get-MgSite -SiteId "serve-relative-path"` to retrieve a site by server URL as described in https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=powershell#access-a-site-by-server-relative-url.

**Comment by mmascolino** [comment]
> @joshtransient, you can use `Find-MgGraphCommand` to see which API a Microsoft Graph command calls. In this case, `Get-MgSiteByPath` calls `/sites/{site-id}/getByPath(path='{path}')`, which is valid API path according to the service metadata.
> 
> Please note that you can use `Get-MgSite -SiteId "serve-relative-path"` to retrieve a site by server URL as described in https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=powershell#access-a-site-by-server-relative-url.

That's really good info @peombwa  - How can useful hints like this get added to the actual Get-Help pages for the commandlet?
