### ISSUE TITLE
update team photo

### ISSUE THREAD

**Issue by zhanlpmo** [microsoftgraph/msgraph-sdk-powershell#1148]
q1：I want to update the photo of team with Microsoft Graph PowerShell Cmdlets.
Connect-MgGraph successfully,and also [Update-MgTeam].
but  there is a error when I run 「Get-MgTeamPhoto 」

**Comment by peombwa** [comment]
@zhanlpmo, what error message are you getting?

**Comment by peombwa** [comment]
Please note that reading and updating a Team's photo is only supported in beta (`Select-MgProfile beta`) - https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&tabs=http.

You can the use:
`Get-MgTeamPhotoContent -TeamId $TeamId -OutFile "PATH\logo.png"` - to download a Team's photo.
`Set-MgTeamPhotoContent -TeamId $TeamId -InFile "PATH\newLogo.png"` - to upload a Team's photo.

**Comment by zhanlpmo** [comment]
@peombwa 
Error message:
Get-MgTeamPhoto: The term'Get-MgTeamPhoto' is the name of a cmdlet, function, script file, or operable program. Not recognized as before. Make sure the name is written correctly, and if it contains a path, make sure it is correct Please try again.

**Comment by zhanlpmo** [comment]
@peombwa 
Thank you for your answer.I changed my  profile to the "beta" version,run Get-MgTeamPhoto,not successfully.
I will try Get-MgTeamPhotoContent.
Error:
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ TeamId = 1d25...ndProperty =  }:<>f__AnonymousType47`3) [Get-MgTeam
   Photo_Get]、RestException`1
    + FullyQualifiedErrorId : Forbidden,Microsoft.Graph.PowerShell.Cmdlets.GetMgTeamPhoto_Get

**Comment by peombwa** [comment]
The forbidden error means that you need to consent to necessary permissions before using the command. The necessary scopes can be found in https://docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta#permissions. See https://docs.microsoft.com/en-us/graph/powershell/get-started?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#sign-in.

**Comment by zhanlpmo** [comment]
I have added all API access of Microsoft Graph on the azure portal.
![image](https://user-images.githubusercontent.com/83522150/159100592-443d4bb1-8c6f-4051-9a1b-1e94470b057a.png)

**Comment by peombwa** [comment]
@zhanlpmo, please share the complete output of `Get-MgTeamPhotoContent -TeamId $TeamId -OutFile "PATH\logo.png" -Debug` for us to investigate this further. I can get the team photo content using `Get-MgTeamPhotoContent` without any issue.
