### ISSUE TITLE
Connect-MgGraph 'CertificateThumbprint' must have a length of 40

### ISSUE THREAD

**Issue by kimlaurits** [microsoftgraph/msgraph-sdk-powershell#1150]
Trying to connect to MS Graph with a service principal, like this:
Connect-MgGraph -CertificateThumbprint ‎$cert.Thumbprint -ClientID $appID -TenantId $tenantID

It fails with this error:
Connect-MgGraph : 'CertificateThumbprint' must have a length of 40. Ensure you have the right certificate thumbprint then try again.
The thumbprint is 40 characters. Verified with ($cert.thumbprint).length
I can use the exact same thumbprint with Connect-AzureAD  -CertificateThumbprint $cert.Thumbprint -ApplicationId $appID -TenantId $tenantID

Have tried with both version 1.9.2 and 1.9.3.

**Comment by timayabi2020** [comment]
@kimlaurits I'm just curious, do you get the same results if you run the command directly from powershell. Something like this:
Connect-MgGraph -TenantId $env:TenantID -Client $env:ClientID -CertificateThumbprint $env:CertificateThumbprint.
The values above are set as environment variables.

**Comment by kimlaurits** [comment]
Yes, it is directly from Powershell that I have tested. Found out that it only seems to check the user certificate store - not the computer store. I only had the certificate in the computer store.

But then I found out, that the parameter -Certificate seems to look in the computer store.
So this seems to work:
$thumbprint = 'Thumbprint of the needed certificate'
$MachineCert = Get-ChildItem -Path Cert:\LocalMachine -Recurse | Where-Object { $_.Thumbprint -eq $thumbprint }
Connect-MgGraph -Certificate $MachineCert -TenantId <tenant-id> -ClientId <app-id>

**Comment by peombwa** [comment]
@kamilamireh, please see the response in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/916#issuecomment-953288208 for the certificate thumbprint length validation.

>Yes, it is directly from Powershell that I have tested. Found out that it only seems to check the user certificate store - not the computer store. I only had the certificate in the computer store.
>
>But then I found out, that the parameter -Certificate seems to look in the computer store.
So this seems to work:
$thumbprint = 'Thumbprint of the needed certificate'
$MachineCert = Get-ChildItem -Path Cert:\LocalMachine -Recurse | Where-Object { $_.Thumbprint -eq $thumbprint }
Connect-MgGraph -Certificate $MachineCert -TenantId -ClientId

You are right. The SDK looks for the certificate in the current user store when `-CertificateThumbprint` or `-CertificateName` is specified. This is a known issue, and the workaround is to use the workaround you have above as documented in https://github.com/microsoftgraph/msgraph-sdk-powershell#usage. We are tracking the feature request in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/936.
