### ISSUE TITLE
Update-MgUserPassword Not Working "Unexpected invalid input parameters."

### ISSUE THREAD

**Issue by GoodThings2Life** [microsoftgraph/msgraph-sdk-powershell#1153]
Hello!

New member here, but I've been searching for information about Update-MgUserPassword as a means to replace Set-AzureADUserPassword which I'm aware is being sunset soon. I referenced the documentation at https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users.actions/update-mguserpassword?view=graph-powershell-beta but found it to be a bit less than useful.

Previously, I would do something like:

Get-AzureADUser "..." | Set-AzureADUserPassword -Password $password ... where $password was a secure string prompted or passed in as a parameter. That would set the user's password how we wanted it to be, and we'd use other relevant commands to set expiration, etc. forcing user to change it on next logon.

I'm attempting to reproduce this with Update-MgUser, and using the command always results in "Unexpected invalid input parameters" which is perhaps the least helpful error I've ever seen and reminds me of "An error occurred."

Ideally, from the syntax, I expected it would be something like:

Update-MgUserPassword -UserId $Username -NewPassword $Password

But apparently no such luck. Can anyone provide better guidance on the correct usage of this module or indicate if this is some sort of bug?

For what it's worth, I'm using Connect-MgGraph -Tenant $Tenant -Scopes User.ReadWrite.All and Select-MgProfile -Name "beta".

Thank you,
Aaron

**Comment by peombwa** [comment]
@GoodThings2Life, please see https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=powershell#example-3-update-the-passwordprofile-of-a-user-to-reset-their-password, https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1137#issuecomment-1064250684, and https://docs.microsoft.com/en-us/graph/api/user-changepassword?view=graph-rest-1.0&tabs=powershell#request.

Please note that MS Graph API is a new API and is not identical to the old AzureAD Graph API that's being deprecated; thus, certain APIs/commands won't work as they did in Azure AD. In this case, [Update-MgUserPassword](https://docs.microsoft.com/en-us/graph/api/user-changepassword?view=graph-rest-1.0&tabs=powershell#request) requires the `-CurrentPassword` and `-NewPassword` to work. Alternatively, you can use `Update-MgUser -PasswordProfile` as described in https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=powershell#example-3-update-the-passwordprofile-of-a-user-to-reset-their-password.

**Comment by GoodThings2Life** [comment]
I appreciate the response on this and the helpful update on how these commands are working.

I would recommend that the Update-MgUserPassword DOCS page be updated to make its usage clearer as a resolution. It's not at all obvious that -currentpassword is a required parameter (and honestly, the error it produces doesn't help either).

That said, the Update-MgUser solution is exactly what I needed. Thank you!
