### ISSUE TITLE
New-MgChat command throw error, InvalidOperation: ({ body = Micros...oftGraphChat1 }:<>f__AnonymousType1`1) [New-MgChat_Create1]

### ISSUE THREAD

**Issue by guptarajesh001** [microsoftgraph/msgraph-sdk-powershell#1154]
We are creating the team group chat by the powershell script:

Version:
Microsoft.Graph.Teams: 1.9.2/1.9.3 - checked with two versions
PowerShell: 1.5.1

Code:
````
Connect-MgGraph -ClientId $clientId -TenantId $tenantID -Certificate "$ScriptPath\testCert.pfx"
$groupJSONBodies = @{                #dynamic created body by script
    "chatType":  "group",
    "topic":  "ITGroup",
    "members":  @[
                    @{
                        "@odata.type":  "#microsoft.graph.aadUserConversationMember",
                        "roles":  ["owner"],
                        "user@odata.bind":  "https://graph.microsoft.com/v1.0/users/316c7b00-0d17-418f-b9ce-3c0976319734"
                    },
                    @{
                        "@odata.type":  "#microsoft.graph.aadUserConversationMember",
                        "roles":  ["owner"],
                        "user@odata.bind":  "https://graph.microsoft.com/v1.0/users/e4d4db5e-2531-4e12-89e3-099800a5c723"
                    },
                    @{
                        "@odata.type":  "#microsoft.graph.aadUserConversationMember",
                        "roles":  ["owner"],
                        "user@odata.bind":  "https://graph.microsoft.com/v1.0/users/232cc001-ad50-46c7-954e-b7e7491e9553"
                    }
                ]
}

 $chatId = New-MgChat -BodyParameter $groupJSONBodies
```

On executing it we are getting below error:

New-MgChat : BadRequest
At E:\Chats.ps1:595 char:41
+ ...                  $chatId = New-MgChat -BodyParameter $groupJSONBodies
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ body = Micros...oftGraphChat1 }:<>f__AnonymousType1`1) [New-MgChat_Create1], RestException`1
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgChat_Create1


Note: Previously it was running successfully, but add only 98 users

**Comment by peombwa** [comment]
@guptarajesh001, the issue with how you are creating and assigning arrays in `$groupJSONBodies` hence the `BadRequest` response from the service. See the example in https://docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&tabs=powershell#example-2-create-a-group-chat on how to use the command.

**Comment by guptarajesh001** [comment]
Hi @peombwa, thanks for replying. Initially, we were tried to add 450 users by the above assigning array $groupJSONBodies, then it was throwing above error. However, if we have split the arrays into two, one of 94 size and other of 356 size. Then, we have created chat group with 94 size array with  "New-MgChat -BodyParameter $groupJSONBodies" command and then, other 356 size array with New-MgChatMember -ChatId  $chatIdId -BodyParameter $group command one by one, then its not throwing any error. But here also its add ony 94 users. Please help.

**Comment by peombwa** [comment]
@guptarajesh001, this sounds like a service issue and not an issue with the SDK. Please post your question to https://developer.microsoft.com/en-us/graph/support for the service owners to get back to you on this.
