### ISSUE TITLE
No PowerShell command for runHealthCheck API

### ISSUE THREAD

**Issue by AshleyYangSZ** [microsoftgraph/msgraph-sdk-powershell#1161]
See this link https://docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&tabs=http
No PowerShell script generate for this API
![image](https://user-images.githubusercontent.com/72924235/159154305-fe5c185d-1504-45e2-b866-6ca35504f50e.png)

**Comment by georgend** [comment]
@AshleyYangSZ 
We recently added a new Cmdlet that allows you to search for cmdlets that correspond to a URL. 
`Find-MgGraphCommand`
For Example:-
```powershell
❯ Find-MgGraphCommand -Uri "https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/onPremisesConnections/{Id}/UpdateAdDomainPassword"

   APIVersion: beta

Command                                                                    Module                   Method URI                                                                                                             OutputType Permissions Variants
-------                                                                    ------                   ------ ---                                                                                                             ---------- ----------- --------
Update-MgDeviceManagementVirtualEndpointOnPremisConnectionAdDomainPassword DeviceManagement.Actions POST   /deviceManagement/virtualEndpoint/onPremisesConnections/{cloudPcOnPremisesConnection-id}/updateAdDomainPassword            {}          {Update, UpdateExpanded, U…
```

Does the cmdlet `Update-MgDeviceManagementVirtualEndpointOnPremisConnectionAdDomainPassword` achieve the desired results?

**Comment by peombwa** [comment]
Thanks for looking into this @georgend!

@AshleyYangSZ, the HTTP snippet is not correct in this case. In the snippet, `updateAdDomainPassword` sends a `PATCH` request, yet `updateAdDomainPassword` is declared as an OData action in the metadata:
``` xml
<Action Name="updateAdDomainPassword" IsBound="true">
  <Parameter Name="bindingParameter" Type="graph.cloudPcOnPremisesConnection" />
  <Parameter Name="adDomainPassword" Type="Edm.String" Unicode="false" />
</Action>
```
OData actions should always be `POST` requests.

**Comment by AshleyYangSZ** [comment]
Hi @peombwa thanks for digging the reason, could you first add the Update-MgDeviceManagementVirtualEndpointOnPremisConnectionAdDomainPassword PS script first? Then we will switch to use POST in https request next month.

**Comment by peombwa** [comment]
@AshleyYangSZ, the command is already available in the latest version of the SDK:
``` powershell
➜ Find-Command Update-MgDeviceManagementVirtualEndpointOnPremisConnectionAdDomainPassword | select ModuleName, Version

ModuleName                               Version
----------                               -------
Microsoft.Graph.DeviceManagement.Actions 1.9.3
```

**Comment by AshleyYangSZ** [comment]
Thanks  a lot! @peombwa we really appreciated your effort on this.
