### ISSUE TITLE
The PowerShell script of reporvision API should be Invoke-MgReprovisionDeviceManagementManagedDevice -ManagedDeviceId $managedDeviceId

### ISSUE THREAD

**Issue by AshleyYangSZ** [microsoftgraph/msgraph-sdk-powershell#1163]
The API is here https://docs.microsoft.com/en-us/graph/api/manageddevice-reprovisioncloudpc?view=graph-rest-beta&tabs=powershell
![image](https://user-images.githubusercontent.com/72924235/159154546-ec7eb5cc-d11f-45b6-a599-5600670b9ca4.png)

Current command is Invoke-Mg**Cloud**DeviceManagementManagedDevice -ManagedDeviceId $managedDeviceId, it expected to be Invoke-MgReprovisionDeviceManagementManagedDevice -ManagedDeviceId $managedDeviceId

**Comment by peombwa** [comment]
Thanks for bringing this to our attention. We will address in #1165.

Closing as duplicate of #1165.
