### ISSUE TITLE
No PowerShell script generated for bulk reprovision API

### ISSUE THREAD

**Issue by AshleyYangSZ** [microsoftgraph/msgraph-sdk-powershell#1164]
The API is here: https://docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&tabs=http

![image](https://user-images.githubusercontent.com/72924235/159154573-aaae5248-a223-4e4a-ad6f-298bcb213927.png)

The PS script should be 
Invoke-MgBulkReprovisionCloudPcDeviceManagementManagedDevice -BodyParameter $params

**Comment by georgend** [comment]
The powershell snippets are generated and updated from time to time. I will investigate when the next update will be.
