### ISSUE TITLE
The bulkRestore API PS script is incorrect

### ISSUE THREAD

**Issue by AshleyYangSZ** [microsoftgraph/msgraph-sdk-powershell#1165]
The API is here https://docs.microsoft.com/en-us/graph/api/manageddevice-bulkrestorecloudpc?view=graph-rest-beta&tabs=powershell
![image](https://user-images.githubusercontent.com/72924235/159154863-4328f525-5f8d-45d0-97b6-ee1613be281e.png)

The PS script should be Invoke-MgBulkRestoreDeviceManagementManagedDevice -BodyParameter $params

**Comment by peombwa** [comment]
We should also rename [Invoke-MgCloudDeviceManagementManagedDevice](https://docs.microsoft.com/en-us/graph/api/manageddevice-reprovisioncloudpc?view=graph-rest-beta&tabs=powershell) to `Invoke-MgReprovisionDeviceManagementManagedDevice`.

**Comment by peombwa** [comment]
@AshleyYangSZ, just circling back to this. Shouldn't `Invoke-MgBulkDeviceManagementManagedDeviceRestoreCloudPc` be renamed to `Invoke-MgBulkRestoreDeviceManagementManagedDeviceCloudPc`? The API doc says
> Restore multiple Cloud PC devices with a single request that includes the IDs of Intune managed devices and a restore point date and time.

The same applies to [Invoke-MgCloudDeviceManagementManagedDevice](https://docs.microsoft.com/en-us/graph/api/manageddevice-reprovisioncloudpc?view=graph-rest-beta&tabs=powershell) -> `Invoke-MgReprovisionDeviceManagementManagedDeviceCloudPc`
>Reprovision a Cloud PC with an Intune [managed device](https://docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta) ID.
