### ISSUE TITLE
Authorization v1.9.3 | Can't specify both "-AccessToken" and "-ContextScope", why?

### ISSUE THREAD

**Issue by o-l-a-v** [microsoftgraph/msgraph-sdk-powershell#1166]
If using an access token when authenticating with ```Microsoft.Graph.Authorization``` cmdlet ```Connect-MgGraph```, one can't specify both ```-AccessToken``` and ```-ContextScope```. 

Is that intended? Why? Because you'll lose access when the token expires anyway?

Working:

```powershell
$null = Connect-MgGraph -AccessToken $AccessToken.'access_token'
```

Not working:

```powershell
$null = Connect-MgGraph -ContextScope 'Process' -AccessToken $AccessToken.'access_token'
```

![image](https://user-images.githubusercontent.com/6450056/159238373-8f3c5f34-ec0f-46d4-a4cb-7c1a84288372.png)

## Environment

* Windows 11 21H2 22000.556
* PowerShell ISE / Windows PowerShell 5.1
* Microsoft.Graph v1.9.3 modules

**Comment by peombwa** [comment]
@o-l-a-v. This is by design. If you specify a `-AccessToken`, we will automatically default to `-ContextScope Process` since we can't refresh the specified access token (no refresh token), and most tokens expire in ~60 minutes.

Is there a reason you need to change the `-ContextScope`?

**Comment by o-l-a-v** [comment]
In theory, if I used -AccessToken, closed the PowerShell session, opened it again before access token expires, the session would still be usable? But if -Scope Process was possible, it (the session) would die when closing PowerShell?

Then yes, I'd like to have the ability to specify "process".

**Comment by peombwa** [comment]
Then in this case, you or the auth library you used to get the access should cache the access token and not us. My assumption is that the access token being passed to `-AccessToken` is read from somewhere. i.e.,
``` powershell
$accessToken = # read it from your cache, environment variable, or auth lib.
Connect-MgGraph -AccessToken $accessToken
```

**Comment by peombwa** [comment]
How is the access token acquired in your scenario? The acquirer should be the one caching the access token. If you are using MSAL (recommended) to acquire the access token, it can cache your token.
> MSAL caches a token after it's been acquired. Your application code should first try to get a token silently from the cache before attempting to acquire a token by other means.

See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-acquire-cache-tokens.
