### ISSUE TITLE
Get-MgAuditLogSignIn -All  -  each time new number of records

### ISSUE THREAD

**Issue by TiredFindingUserName** [microsoftgraph/msgraph-sdk-powershell#1167]
Hello
I am using MgGraph with the beta profile. 
Each time I run my script (it should grab all the sign-ins from the previous day) I get a different number of records - 14k, 12k, 7k...
The same request, the same filters, just run the same script once again and once again.
Is there any limit for requests (like once in a day or in an hour or something else)?
This is how I am downloading:

Connect-MgGraph -ClientId XYZ -TenantId ABC -Certificate $cert 
Select-MgProfile -Name beta

#Create a yesterday date
#Note - this is UTC
$yesterdayDate = (Get-Date).AddDays(-1).AddHours(-(Get-Date).Hour).AddMinutes(-(Get-Date).Minute).AddSeconds(-(Get-Date).Second).AddMilliseconds(-(Get-Date).Milliseconds)

Write-Host
Write-Host "Downloading data... Start time:" $(Get-Date -Format "hh:mm:ss")

$signIns = Get-MgAuditLogSignIn -All -Filter "CreatedDateTime gt $($yesterdayDate.ToString("yyyy-MM-ddTHH:mm:ssZ")) and CreatedDateTime lt $($yesterdayDate.AddHours(24).ToString("yyyy-MM-ddTHH:mm:ssZ")) and ClientAppUsed ne 'Browser' and ClientAppUsed ne 'Mobile Apps and Desktop clients' and ClientAppUsed ne ''"  

Write-Host "Done downloading data... End time:" $(Get-Date -Format "hh:mm:ss")

The same result, actually, I am getting using the v1.0 graph.

**Comment by peombwa** [comment]
@TiredFindingUserName, I'm not able to repro this in a tenant with 1k signins records. This looks like a service issue from the description above since the SDK is not throwing any errors.

Do you get differing counts when making the same request via `Invoke-MgGraphRequest` as shown below?
``` powershell
Connect-MgGraph -ClientId XYZ -TenantId ABC -Certificate $cert
$yesterdayDate = (Get-Date).AddDays(-1).AddHours(-(Get-Date).Hour).AddMinutes(-(Get-Date).Minute).AddSeconds(-(Get-Date).Second).AddMilliseconds(-(Get-Date).Milliseconds)

$signInsUrl = "https://graph.microsoft.com/beta/auditLogs/signIns?`$filter=CreatedDateTime gt $($yesterdayDate.ToString("yyyy-MM-ddTHH:mm:ssZ")) and CreatedDateTime lt $($yesterdayDate.AddHours(24).ToString("yyyy-MM-ddTHH:mm:ssZ")) and ClientAppUsed ne 'Browser' and ClientAppUsed ne 'Mobile Apps and Desktop clients' and ClientAppUsed ne ''"
$signins = @()
do{
    try {
        $response = Invoke-MgGraphRequest -Uri $signInsUrl
        $signins += $response.value
        $signInsUrl = $response.'@odata.nextLink'
    } catch {
        throw $_.Exception
    }
} while($signInsUrl)

# Are you seeing the same behavior here?
$signins.Count
```

I would recommend you open a support ticket/question at https://developer.microsoft.com/en-us/graph/support for the service owners to investigate if the same behavior is still present with the above script.

**Comment by TiredFindingUserName** [comment]
> @TiredFindingUserName, I'm not able to repro this in a tenant with 1k signins records. This looks like a service issue from the description above since the SDK is not throwing any errors.
> 
> Do you get differing counts when making the same request via `Invoke-MgGraphRequest` as shown below?


Hi
Yes, unfortunately, the result is the same. Instead of getting about 3 million records (in case I use 5-minute chunks) it returns 10-20k records.

**Comment by peombwa** [comment]
I would recommend you open a support ticket/question at https://developer.microsoft.com/en-us/graph/support for the service owners to investigate.
