### ISSUE TITLE
Issues when fetching members list from a group in PowerShell SDK

### ISSUE THREAD

**Issue by MehtabSiddiq** [microsoftgraph/msgraph-sdk-powershell#1169]
Hello,
           I am using PowerShell to run a query for fetching a list of members from a particular group from the [DOC](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=powershell#example-1-get-the-direct-membership-in-a-group) but every time it is giving me errors as resource not found, but the same query is running perfectly in MS graph explorer for the same group ID. Here below is screenshot of the error.
![image](https://user-images.githubusercontent.com/99253045/159636517-3a53afce-6729-4d96-9be6-6188d0422742.png).

There is also one similar issue with the same query going on and the errors we are getting is different, Its related to [SO question](https://stackoverflow.microsoft.com/questions/298271).
The Error:
Connect-MgGraph Welcome To Microsoft Graph! PS C:\Users\whoskins> Get-MgGroupMember -GroupId 703a7a71-3546-4a10-b5d1-0dcf9176561a Get-MgGroupMember : Insufficient privileges to complete the operation. At line:1 char:1 + Get-MgGroupMember -GroupId 703a7a71-3546-4a10-b5d1-0dcf9176561a + + CategoryInfo : InvalidOperation: ({ GroupId = 703...ndProperty = }:<>f__AnonymousType279) [Get-MgGrou    pMember_List3], RestException1 + FullyQualifiedErrorId : Authorization_RequestDenied, (cut).
![Error in powershell](https://user-images.githubusercontent.com/99253045/159639426-c948ee89-58cb-49ab-ae7c-0661d42edb71.PNG)

**Comment by peombwa** [comment]
@MehtabSiddiq, that's a service error you are getting (404 Not Found). Can you verify that:
- The GroupId is of a group in your tenant (`Get-MgGroup -GroupId "YOUR_GROUP_ID" -Debug`).
- You've signed into the right tenant.
- You've consented to the required permissions as described in https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=powershell#permissions. Please note that all the permissions need to make this call will require an admin consent - https://docs.microsoft.com/en-us/graph/permissions-reference#group-permissions.

You can use `Get-MgContext | select TenantId, Scopes` to confirm the above.

**Comment by MehtabSiddiq** [comment]
Thanks @peombwa for replying to my queries, yes this was an issue from my side of the group id I got the confirmation from the debug query. The issue with admin consent also I have gone through the DOC and checked with the permissions also.

**Comment by peombwa** [comment]
Sounds good! I'll close the issue.
