### ISSUE TITLE
get-mguser with -Filter returns empty attributes

### ISSUE THREAD

**Issue by exwhyz** [microsoftgraph/msgraph-sdk-powershell#1171]
I am getting user entity information from O365 Azure AD using PS:

`(Get-Host).Version`

Major: 7  Minor: 1  Build: 5  Revision: -1

Using -Filter switch to get a user record by name does not populate certain attributes:

`(Get-MgUser -Filter "displayName eq 'John Doe'") | Select AdditionalProperties`

Returns Empty: 
AdditionalProperties:{}

Using -UserId switch to get a user record populates all attributes:

`(Get-MgUser -UserId '8888b0fd-1e96-4fc2-b525a-32f77a52ee0f') | Select AdditionalProperties`

Returns:
AdditionalProperties: {[@odata.context, https://graph.microsoft.com/v1.0/$metadata#users/$entity]}

Is this by design and if so is there a way to overcome the behavior and force -Filter to also populate all properties on return?

Thanks!

**Comment by peombwa** [comment]
@exwhyz, which properties of the [user entity](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta#properties) are you looking for? Please note that `.AdditionalProperties` on the user response object only holds "additional" properties not currently available in the user entity.

In this case, the `-Filter` should work as expected, and all user properties will be returned in the response user object ` Get-MgUser -Filter "displayName eq 'John Doe'" | fl *`. See the examples in https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/get-mguser?view=graph-powershell-beta#examples.

**Comment by exwhyz** [comment]
I need to extract odata which is embedded in the AdditionalProperties attribute of the user entity. I understand that AdditionalProperties holds "additional" properties. As I indicated in my ticket, when I use get-mguser with -Filter on a user DisplayName, AdditionalProperties are returning empty {}, however when I use get-mguser for the same user but with the -UserId it returns the AdditionalProperties correctly populated with the @odata value. So my question is - why does get-mguser with -Filter return AdditionalProperties attribute as empty when it is not.

**Comment by peombwa** [comment]
@exwhyz, Got it! This is by design. `@odata.context` is a service annotation that holds the [context URL](https://docs.microsoft.com/en-us/openspecs/odata_standards/ms-odatajson/1259ce6b-273d-4c01-9e79-48a0be630f39?msclkid=212957a2ac8111eca3568f1af8216d95) and is not a property of a user entity. This means that annotation will be outside the `value` property of the HTTP response object when the response is a collection, i.e.,
- `Get-MgUser -UserId`: response is a [single entity](http://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_IndividualPropertyorOperationRespons):
``` powershell
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
  "displayName": "John Doe",
  ...
}
```

- `Get-MgUser -Filter`: response is a [collection](http://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_IndividualPropertyorOperationRespons):
``` powershell
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users",
  # For collections, we deserialize objects inside the value property and ignore everything outside it.
  "value": [
    {
      "displayName": "John Doe"
    }
  ]
}
```
You can verify this by running the above commands with `-Debug` and inspecting the HTTP response body.

Why do you need access to `@odata.context` in this case? The command should automatically deserialize all the properties of a user entity to the return object.

**Comment by exwhyz** [comment]
@peombwa  I have AdditionalProperties stored in that attribute that I am trying to access. And here is another thing that I find inconsistent in accessing AdditionalProperties. When I expand the user's Manager attribute and then get the AdditionalProperties it returns all the properties stored therein - as expected. 

Here is the cmdlet that spits out all the AdditionalProperties as expected for the Manager of the user I am querying:

`(Get-MgUser -UserId '8888b0fd-1e96-4fc2-b525a-32f77a52ee0f' -ExpandProperty Manager).Manager.AdditionalProperties
`

Output:
```
Key                                                      Value
---                                                      -----
@odata.type                                              #microsoft.graph.user
accountEnabled                                           True
businessPhones                                           {xxx-xxx-xxxx}
city                                                     xxx
companyName                                              xxx
country                                                  xxx
createdDateTime                                          2018-09-18T05:00:45Z
department                                               xxxx
displayName                                              John Doe
...
...
...
```

So **how do I get the AdditionalProperties for the User entity directly**? Obviously I can get it for their Manager (as I demonstrate above), but I am having no luck in getting those AdditionalProperties for the User. My attempt to use the following cmdlet does not return any  AdditionalProperties stored in the attribute, only the odata.context URL:

`(Get-MgUser -UserId '9799b0fd-1e69-4fc2-b52a-23f77a25ee0f').AdditionalProperties`

Output:
```
Key            Value
---            -----
@odata.context https://graph.microsoft.com/v1.0/$metadata#users/$entity
```

**Comment by mendepa** [comment]
Have you try to invoke this command in beta api? @exwhyz 

In Beta call object is returned with all additional properties

```
Get-MgUser -UserId $USER_ID | Select -ExpandProperty AdditionalProperties

Key                                                      Value
---                                                      -----
@odata.context                                            https://graph.microsoft.com/beta/$metadata#users/$entity
securityIdentifier                                        XXXXXXXXXXXXXXXXXXXX
extension_XXXXX                                           XXXXXXXXXXXXXXXXXXXX         
extension_XXXXX                                           XXXXXXXXXXXXXXXXXXXX       
extension_XXXXX                                           XXXXXXXXXXXXXXXXXXXX        
extension_XXXXX                                           XXXXXXXXXXXXXXXXXXXX        
extension_XXXXX                                           XXXXXXXXXXXXXXXXXXXX       
extension_XXXXX                                           XXXXXXXXXXXXXXXXXXXX
```

**Comment by exwhyz** [comment]
@mendepa yes I have tried with the beta API and it returns a few additional extension_ prefixed properties but it still does **not** return the AdditionalProperties for the User. So still the same issue, the AdditionalProperties are returned when I get them for a User's manager:

(Get-MgUser -UserId '8888b0fd-1e96-4fc2-b525a-32f77a52ee0f' -ExpandProperty Manager).Manager.AdditionalProperties

but they are not returned for the User:

(Get-MgUser -UserId '8888b0fd-1e96-4fc2-b525a-32f77a52ee0f').AdditionalProperties

**Comment by Janooski** [comment]
Let me begin with, I can confirm everything that was written but it still doesn't solve my problem. I can see all attributes when using `Get-MgUser -UserId $USER_ID | Select -ExpandProperty AdditionalProperties` but when using -Filter it returns the AdditionalProperties as {} (as written in this thread). 

My problem isn't solved, as extensionAttributes remain under AdditionalProperties and are not returned when using -Filter. I get all users with a license with the following neat command:

`Get-MgUser -Filter 'assignedLicenses/$count ne 0' -ConsistencyLevel eventual -CountVariable unlicensedUserCount -All -Property "id, assignedLicenses, givenName, surname, userPrincipalName, AdditionalProperties"`

But I need a value stored in the extensionAttributes for further filtering, but this doesn't work conveniently as the extensionAttributes are just not returned. I can work around this by starting a new Get-MgUser -UserId request for each user, which then returns the needed extensionAttribute value, but increases the time the script takes massively (from under 10 minutes to multiple hours). I would appreciate any help on this. Thanks!
