### ISSUE TITLE
Is Update-MgDirectoryDeletedItem the cmdlet to restore a deleted directory object? If yes, rename to Restore-MgDirectoryDeletedItem.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1176]
The URI I get from PowerShell does not match the URI for the API that does the restore unless I'm missing something.

![image](https://user-images.githubusercontent.com/73849846/160147172-5f79158d-0ce4-47eb-9d1e-917d42324c91.png)

vs

![image](https://user-images.githubusercontent.com/73849846/160147311-27e1c2a3-f25f-44d5-9572-bf6dea376fe7.png)

**Comment by peombwa** [comment]
@msewaweru, these are two different APIs (`/directory/deleteditems/{id}/restore` vs `/directory/deleteditems/{id}`).

`/directory/deleteditems/{id}/restore` is currently missing the OpenAPI document. This is already being tracked in https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/837.

**Comment by peombwa** [comment]
Closing as duplicated of https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/837.
