### ISSUE TITLE
Is there a way to get MSGraph using manual installation?

### ISSUE THREAD

**Issue by Petri-X** [microsoftgraph/msgraph-sdk-powershell#1183]
Hi,
When you are working in normal security company, then your local administrator account does not have access to go to internet. So to get different kind of PS modules installed requires from me to download the .nupkg files using my regular account and do the manual installation using my admin account.

I already get MS Graph on my workstation but when trying to load it, I got error message:
"**Import-Module : The required module 'Microsoft.Graph.Authentication' is not loaded. Load the module or remove...**"
Which I did as well. And the next was:
"**Import-Module : The required module 'Microsoft.Graph.Financials' is not loaded. Load the module or remove the modul...**"

Before I go one by one all of these, I would like to ask if there is a list of the packages needed, or is there a simple way to get all of those packages downloaded at once?

**Comment by peombwa** [comment]
@Petri-X, all our modules are distributed via PowerShell Gallery. You can find a list of all the required modules and their dependencies in PowerShell Gallery under the package details - https://www.powershellgallery.com/packages/Microsoft.Graph/1.9.3.

**Comment by Petri-X** [comment]
@peombwa 
Thanks, somehow I did not found those details.
But is there an easy way to download those, instead one by one clicking them? Or based on those modules generate PS1 script like:
`Invoke-WebRequest -Uri https://psg-prod-eastus.azureedge.net/packages/microsoft.graph.applications.1.9.3.nupkg  -OutFile C:\Temp\GraphModules\microsoft.graph.applications.1.9.3.nupkg
`
etc..

**Comment by peombwa** [comment]
@Petri-X The required modules are all listed in PowerShell Gallery.
![image](https://user-images.githubusercontent.com/7061532/161311050-0184f9d0-689b-4aba-b2d8-7f7c418605a5.png)

You can manually download `.nupkg` package form PS Gallery as stated in https://aka.ms/psgallery-manualdownload. All our modules are strictly distributed through PS Gallery for security reasons.

**Comment by peombwa** [comment]
@Petri-X You also consider using [Save-Module](https://docs.microsoft.com/en-us/powershell/module/PowershellGet/Save-Module?view=powershell-7.2#example-1-save-a-module) command to save the module to a file share or save it to another source and manually copy it to other machines.

``` powershell
Save-Module -Name Microsoft.Graph -Path "DESTINATION_PATH" -Repository PSGallery
```

**Comment by Petri-X** [comment]
@peombwa  COOOL !! 
The Save-Module really did it !
Big thanks to you for this!
