### ISSUE TITLE
Valid values for -ContextScope with Connect-MgGraph

### ISSUE THREAD

**Issue by jimmart-dev** [microsoftgraph/msgraph-sdk-powershell#1187]
I am connecting to my tenant using Connect-MgGraph as a global Admin. When I try to use command Get-MgUser to list all users, it only shows the profile info for the global admin. If I run Get-MgContext it shows the ContextScope is CurrentUser. I suspect that is why I am only seeing the global Admin's profile. 

There is a ContextScope parameter for Connect-MgGraph but I cannot determine what the other valid values are. Th ehelp info wasn't useful.

Update: Further research led me to try the value "Process" for ContextScope but I still get the same results.

**Comment by peombwa** [comment]
@jimmart-dev, `-ContextScope` is used to control where the access token is cached (current user or process session). 

From
> When I try to use command Get-MgUser to list all users, it only shows the profile info for the global admin.

It looks like you haven't consented to the permissions needed to list all users as stated in https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#permissions. Use `Connect-MgGraph -Scopes User.ReadBasic.All, User.Read.All` to consent to the permissions then try again. See https://docs.microsoft.com/en-us/graph/powershell/get-started?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#sign-in for more info.
