### ISSUE TITLE
Working with AD application after New-MgApplication is unreliable

### ISSUE THREAD

**Issue by erwinkramer** [microsoftgraph/msgraph-sdk-powershell#1191]
Consider a script where you create a new azure ad application with New-MgApplication. If you immediately work with the new application by adding a related enterprise app, adding owners, removing original owner, getting the application again, updating again with other properties etc... things get rather unstable, working with the fresh azure ad application might return an error because the object wasn't found (yet), while waiting a few seconds will make it work.

I've been particularly noticing this at busy times and in large tenants. My original thought was that the graph API is pretty stable in terms of keeping all changes at 1 'chosen' zone primarily and then replicating this to others in the same 'region' for redundancy (roughly speaking), as long as you use the same library inside the same session. In my case I'm exclusively using the Mg PowerShell library for every call and running in the latest pscore with a single authentication call.

Currently it feels like it's just randomly picking whatever server, so you need to hope (or wait) before it's fully replicated if you want to work with your new objects. What's the consensus on this? Should I just accept the fact that my create call might not be there yet in the same script when I work with it? 

Fyi: I'm in the west europe region

**Comment by peombwa** [comment]
Thanks for taking the time to open this issue. These are good performance points that you should bring to the attention of the workloads. Please post your comments as a question/feature request at https://developer.microsoft.com/en-us/graph/support to surface them to the workload owners.

As an SDK, there isn't much we can do to optimize this besides handling throttling and 202 status codes.

**Comment by peombwa** [comment]
Closing as a service-related perf issue.
