### ISSUE TITLE
Get-MgUser fails for a tenant with a large number of users, but Get-MgUser -All -PageSize 400 succeed.

### ISSUE THREAD

**Issue by mr-oliva** [microsoftgraph/msgraph-sdk-powershell#1192]
I create a test tenant with 40,000 users.

Using PowerShell 5.1, "Get-MgUser -All" causes the StackOverflowExeption.
Given the related issue (#949), This result is to be expected.

Howerver, "Get-MgUser -All -PageSize 400" succeed.

Why does it work with large PageSize ?

The result of verification is as follows:

```
PS C:\Users\kutsu> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.593
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.593
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\kutsu> (Get-MgUser -All -PageSize 400).count
40002
PS C:\Users\kutsu> (Get-MgUser -All).count

Process is terminated due to StackOverflowException.
```

**Comment by peombwa** [comment]
Thanks for bringing this to our attention. We are investigating the root cause of this error as it is isolated to PowerShell 5.1.

**Comment by peombwa** [comment]
We've traced the bug to a recursion depth issue in PS 5.1 when there are more than ~250 pages to be fetched. Thanks, @mr-oliva, and the team, for the memory dumps.

The workaround is to increase the `-PageSize` to something like `Get-MgUser -All -PageSize 400` to reduce the number of pages or upgrade to PowerShell 7.x.

We will provide a fix in the upcoming release.

**Comment by peombwa** [comment]
A fix will be provided by https://github.com/Azure/autorest.powershell/pull/932.

**Comment by mr-oliva** [comment]
I'm sorry for my late response and understand that there is a problem.
Thank you for check this issue.
I'll try again after update autorest.powershell.

**Comment by peombwa** [comment]
@mr-oliva, we've just release version 1.9.6 with the fix - https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.9.6. Please give it a try and let us know if the issue persists. Thanks!

**Comment by watahani** [comment]
@peombwa Thank you for your assistance. It works fine for me!

**Comment by mr-oliva** [comment]
@peombwa I confirmed that the problem has been resolved. Thanks!
