### ISSUE TITLE
Calendar Graph API request return duplicates listing user events

### ISSUE THREAD

**Issue by mdurini-swisscom** [microsoftgraph/msgraph-sdk-powershell#1198]
Hello, I wrote a script to fetch all events for a specific user specifying the top value to 1000 and handling the "odata.nextLink" to fetch the next results, storing everything in an array to be able to process later all the events. I saw that the last result of "page 1" is duplicated as first result in "page 2". The funny thing is that if I try to decrease the top value to 100, the problem is still present but in a later page with a different duplicated event. The worst thing is that also the powershell command Get-MailboxFolderStatistics seems to be affetced because the counter result match the "odata.count" value from Graph API call, but if I count the unique events based on iCalUId value, I get a lower number of results.

**Comment by peombwa** [comment]
@mdurini-swisscom, thanks for taking time to open this issue.

Are you seeing this with commands in [Microsoft Graph PowerShell](https://www.powershellgallery.com/packages/Microsoft.Graph/1.9.4) SDK - https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-beta&tabs=powershell#example? If so, please share a snippet of how you are calling Microsoft Graph PowerShell commands.

For API-related questions, please use https://developer.microsoft.com/en-us/graph/support to open service questions/bugs, as this repo is for issues related to Microsoft Graph PowerShell SDK.

**Comment by mdurini-swisscom** [comment]
@peombwa the problem is with the graph api but if you can tell me which command I can use from the Microsoft Graph PowerShell SDK module to retrieve all the events of a specific user, I will be more than happy to test if the problem is also present here. 

thank you in advance.

best regards

**Comment by peombwa** [comment]
@mdurini-swisscom, you could use `$UserEvents = Get-MgUserEvent -UserId $userId -All` to get all the events of a user. See https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-beta&tabs=powershell#example for more details.

**Comment by mdurini-swisscom** [comment]
hello @peombwa , sorry for the late reply. Yes I can confirm you that I'm getting the duplicates also using the Get-MgUserEvent command


`Connect-MgGraph -AccessToken $request.access_token
 $events = Get-MgUserEvent -UserId xxxxx@xxxx.xx-All
 $events.Id | Group-Object -CaseSensitive | Where-Object {$_.Count -gt 1}`

grouping the result with the latest command, I got the duplicated event.

**Comment by peombwa** [comment]
Sorry about this. As this is a service issue, I'd recommend you open a question/ticket at https://developer.microsoft.com/en-us/graph/support for the service owners to investigate. This repo is for issues related to Microsoft Graph PowerShell SDK.
