### ISSUE TITLE
Get-MgDirectoryRoleTemplateDirectoryRoleTemplateDirectoryRoleTemplate cmdlet seems misnamed

### ISSUE THREAD

**Issue by marcgoff** [microsoftgraph/msgraph-sdk-powershell#120]
Seems like the Get-MgDirectoryRoleTemplate cmdlet got misnamed to Get-MgDirectoryRoleTemplateDirectoryRoleTemplateDirectoryRoleTemplate.

**Comment by peombwa** [comment]
@marcgoff This has now been resolved in [Microsoft.Graph.Identity.DirectoryRoleTemplates 0.3.0](https://www.powershellgallery.com/packages/Microsoft.Graph.Identity.DirectoryRoleTemplates/0.3.0).
``` ps
Install-Module -Name Microsoft.Graph.Identity.DirectoryRoleTemplates
```
