### ISSUE TITLE
Get-MgTeamChannel, how to filter using email address? (Ver. 1.9.3)

### ISSUE THREAD

**Issue by Petri-X** [microsoftgraph/msgraph-sdk-powershell#1203]
Hi,
I believe I'm not the only one who needs to find which Team contains a channel which email address is xxxyy@cccc.msteams.ms.

I already found one possibility to use followings:
#1 Find all Team Groups
`Get-MgGroup -Filter "resourceProvisioningOptions/Any(x:x eq `'Team`')" -Property id, DisplayName`

#2 Get all Channels from each Team with email addresses:
`Get-MgTeamChannel -TeamId $_.id -Property DisplayName, email`

#3 Find the channel:
`Where-Object {$_.email -eq "abc12345.company.onmicrosoft.com@emea.teams.ms" }`

And if I put this into one liner:
`Get-MgGroup -Filter "resourceProvisioningOptions/Any(x:x eq `'Team`')" -Property id, DisplayName | % { $grpIDTemp = $_.id; $grpDispName = $_.DisplayName ; Get-MgTeamChannel -TeamId $_.id -Property DisplayName, email   }  | Where-Object {$_.email -eq "abc12345.company.onmicrosoft.com@emea.teams.ms" }  | ft @{Label = "GroupID"; Expressio = {$grpIDTemp} }, @{Label = "GroupDisplayName"; Expressio = {$grpDispName} }, DisplayName, Email`

That list me GroupID, Group's Displayname, Channel's displayname and channel's Email address

But problem is, this lists the first 100 groups only, which I could solve by using parameter "**-All**" and then using paging. But then it means, I must went through all of our 150 000 Teams and all the channels in them. From time point of view this means 2 weeks, and perhaps even longer unless my sessions expires before that.

Questions:
1. Does anybody knows if I could filter on **Get-MgTeamChannel** and search channel based on email address? I'm so new with Graph, so the logic behind filter is a bit confusing at the moment for me :)
2. **Get-MgTeamChannel** has other problem as well, **-TeamID** is a mandatory parameter. So I'm unable to search without giving the TeamID at the same time. Meaning I need to search again all of those 150k Teams. And time flies again. In my mind, if I'm using "**-filter**" there should be no need to identify the Team anymore. Or how do you others see this?

May I ask, how have you solved the problem to find channel based on email address?

**Comment by peombwa** [comment]
***Question 1:*** You can use `-Filter` to filter Team channels by email, as shown below.
``` powershell
Get-MgTeamChannel -TeamId $TeamId -Filter "email eq '$TeamEmail'"
```
This performs a server-side filter using OData `$filter` as described in https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter.

***Question 2:*** The API does not support this. Channels are bound to Team, i.e., a `TeamId` is required to access a team's channel. You could narrow down your search for a team by using [Get-MgUserJoinedTeam -UserId $UserId](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=powershell#request) or `Get-MgGroup -Filter "resourceProvisioningOptions/Any(x:x eq 'Team') and displayName eq '$TeamDisplayName'" -Property id, DisplayName`.

You should also open a feature request for the service team at https://developer.microsoft.com/en-us/graph/support for them to consider your scenario.

**Comment by Petri-X** [comment]
Hi @peombwa 
Super big thanks for the link to use the Filter. That would would be great help! Lot of more learning :D

Looks like I still need to go through all of the Teams we have to find certain channel based on its email address. But definitely, I will put a feature request to get improvements to this.

Have a great day !
