### ISSUE TITLE
Remove-MgUser returns null

### ISSUE THREAD

**Issue by tensline** [microsoftgraph/msgraph-sdk-powershell#1208]
Judging from the MS official document, "Remove-MgUser" is supposed to return boolean value, true or false.
However, the actual returned value was null whether the command execution result in successful or not.

I just wanted to get the command success status based on the returned boolean value, is this possible?

The result of verification is as follows:
> PS C:\Users\ttaniguchi>  $PSVersionTable
> 
> Name                           Value
> ----                           -----
> PSVersion                      5.1.22000.282
> PSEdition                      Desktop
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> BuildVersion                   10.0.22000.282
> CLRVersion                     4.0.30319.42000
> WSManStackVersion              3.0
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> 
> 
> PS C:\Users\ttaniguchi> Connect-MgGraph -scope User.ReadWrite.All
> Welcome To Microsoft Graph!
> PS C:\Users\ttaniguchi> $result = Remove-MgUser -UserId 'b986a2cf-33e2-4826-b5b5-1f379aa1f0fd'
> PS C:\Users\ttaniguchi> $result.GetType()
> You cannot call a method on a null-valued expression.
> At line:1 char:1
> + $result.GetType()
> + ~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : InvokeMethodOnNull
> 
> PS C:\Users\ttaniguchi> $result = Remove-MgUser -UserId '5c442efb-5e66-484a-936a-91b6810bed14'
> Remove-MgUser : Resource '5c442efb-5e66-484a-936a-91b6810bed14' does not exist or one of its queried reference-property objects are not present.
> At line:1 char:1
> + $result = Remove-MgUser -UserId '5c442efb-5e66-484a-936a-91b6810bed14 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: ({ UserId = 5c44...4, IfMatch =  }:<>f__AnonymousType68`2) [Remove-MgUser_Delete], RestException`1
>     + FullyQualifiedErrorId : Request_ResourceNotFound,Microsoft.Graph.PowerShell.Cmdlets.RemoveMgUser_Delete
> PS C:\Users\ttaniguchi> $result.GetType()
> You cannot call a method on a null-valued expression.
> At line:1 char:1
> + $result.GetType()
> + ~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : InvokeMethodOnNull

[Reference]
Title: Remove-MgUser - Outputs
URL: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/remove-mguser?view=graph-powershell-beta#outputs
///// Excerpt /////
Outputs
System.Boolean
////////////////////

**Comment by peombwa** [comment]
@tensline, the command supports `–PassThru` parameter, which will return `true` when the command succeeds.
``` powershell
 if (Remove-MgUser -UserId $userId -PassThru){ Write-Host 'Done!' } else { Write-Error 'Failed!' }
```
When an [API returns no content](https://docs.microsoft.com/en-us/graph/api/user-delete?view=graph-rest-1.0&tabs=http#response-1) (HTTP status code 204), we will provide `-PassThru` parameter that customers can use to get the boolean status of an operation.

See https://devblogs.microsoft.com/scripting/use-the-powershell-passthru-parameter-and-get-back-objects/ for more details.
