### ISSUE TITLE
Unable to install AzureAD module from ARM Powershell deployment script

### ISSUE THREAD

**Issue by WhitWaldo** [microsoftgraph/msgraph-sdk-powershell#1210]
I'm trying to build out an end-to-end greenfield deployment via ARM templates in Azure. As one of the last pieces, I need to modify an AAD application's reply URLs to reflect a new endpoint not known until a prerequisite deployment completes.

Ideally, I'd have my user-assigned identity have the permissions necessary in the Graph to modify the reply URLs on the applications since it's otherwise created alongside the deployment with other managerial permissions. As part of the greater ARM deployment then, I'm attempting to execute the following Powershell as a [deployment script](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-script-template):

```
var psScript = '''
param (
	[string] $TenantId,
	[string] $UaiObjectId,
	[string] $UaiPrincipalId,
	[string] $PermissionName	
)

# The Microsoft Graph App ID
$GraphAppId = "00000003-0000-0000-c000-000000000000"

# Log into Azure so we can secure a token
Connect-AzAccount -Identity

# Retrieve the access token
$context = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile.DefaultContext
$graphToken = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, "https://graph.microsoft.com").AccessToken
$aadToken = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, "https://graph.windows.net").AccessToken

#Install the necessary AzureAD module
Install-Module AzureAD

#Log into AzureAD
Connect-AzureAD -AadAccessToken $aadToken -AccountId $context.Account.id -TenantId $context.Tenant.id

#Get the graph service principal
$GraphServicePrincipal = Get-AzureADServicePrincipal -Filter "appId -eq '$GraphAppId'"

#Get the app's identifier
$AppRole = $GraphServicePrincipal.AppRoles | Where-Object {$_.Value -eq $PermissionName -and $_.AllowedMemberTypes -contains "Application"}

#Create the new role assignment
New-AzureAdServiceAppRoleAssignment -ObjectId $UaiObjectId -PrincipalId $UaiPrincipalId -ResourceId $GraphServicePrincipal.ObjectId -Id $AppRole.id
'''

var psArgs = '-TenantId ${subscription().tenantId} -UaiObjectId ${UAI.id} -UaiPrincipalId ${UAI.properties.principalId} -PermissionName ${permissionName}'
```

During execution, it doesn't throw an error installing the AzureAD module, but when running that next line, it indicates it cannot identify the cmdlet for Connect-AzureAD which suggests that the install didn't work as expected.

Do you have any recommended paths forward to either 1) get the module to properly install in a deployment script or 2) have a suggestion of an alternative way to assign this app role to the UAI so it can modify the reply URLs of my AAD application without human interaction?

Thank you!

**Comment by peombwa** [comment]
@WhitWaldo, please consider switching to the Microsoft Graph PowerShell SDK (this repo). We do not own the AzureAD module.

You can use the Microsoft Graph PowerShell SDK to assign an app role to a user, group, or client service principal, as explained in https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-1.0&tabs=powershell#request. See the example in https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-consent-single-user#grant-consent-on-behalf-of-a-single-user for more details.

**Comment by WhitWaldo** [comment]
@peombwa Same problem even if using the MSGraph SDK - in an ARM deployment script, I still cannot install the Graph PowerShell SDK as I lack administrator privileges.

**Comment by peombwa** [comment]
Unfortunately, there isn't much that we can help with as an SDK since you are facing permission issues with ARM templates. I'd suggest you reach out to Azure support at https://azure.microsoft.com/en-us/support or post a question to https://docs.microsoft.com/en-us/answers for further assistance.
