### ISSUE TITLE
Permission (scope or role) cannot be deleted or updated unless disabled first.

### ISSUE THREAD

**Issue by gfrid** [microsoftgraph/msgraph-sdk-powershell#1211]
Scenario: 

 $AppRole = @{
     allowedMemberTypes = "user"
         description = "test233"
         displayName = "tes22t343"
         id = "31297833-105c-46dd-954d-9dd0b2426a35"
         isEnabled = true
         value = "test12"
    }

Update-MgApplication -ApplicationId $applicationId -AppRoles $AppRole

Error: Permission (scope or role) cannot be deleted or updated unless disabled first.

Problem: After adding initial AppRole there is not way to add additional AppRole. Update-MgApplication tries to update the existing AppRole. Graph Api missing function to update new AppRole. If it exist there no documentation. Even if ID is changed it tries to overwrite the same AppRole

**Comment by peombwa** [comment]
@gfrid, please see the answer at https://docs.microsoft.com/en-us/answers/questions/748037/cannot-disable-scope-what-do-i-miss.html.  

The is a service issue that is not related to the behavior of the PowerShell command. In the future, I'd suggest you post the question/open a ticket at https://developer.microsoft.com/en-us/graph/support to get feedback directly from the workload owners.

**Comment by peombwa** [comment]
Closing as non-sdk related. Answer has been provided at https://docs.microsoft.com/en-us/answers/questions/748037/cannot-disable-scope-what-do-i-miss.html.
