### ISSUE TITLE
Missing function 'Assign groups to Enterprise Applications'

### ISSUE THREAD

**Issue by gfrid** [microsoftgraph/msgraph-sdk-powershell#1212]
Missing function: 

Seems there is missing function that allows assigning groups to Enterprise Applications
you can assign AppRoles to Groups and AppRoles to Users but not able to assign Groups and Users to Ent. Apps.

if exist, missing documentation

**Comment by peombwa** [comment]
@gfrid, please open a feature request at https://developer.microsoft.com/en-us/graph/support for the workload to consider this scenario. This repo is for SDK issues only. The SDK is just a mirror of the service, i.e., if the service does not support an API, then it won't be available via the SDK.
