### ISSUE TITLE
get-mgsite cmdlet broken with new mandatory parameter (-Path) in version 1.9.3+

### ISSUE THREAD

**Issue by pecjag** [microsoftgraph/msgraph-sdk-powershell#1214]
Hello,

cmdlet: Get-MgSite
Module: Microsoft.Graph.Sites
Working version: 1.9.2
Broken versions: 1.9.3, 1.9.4, 1.9.5

The documentation for Get-MgSite includes this parameterset:
`
Get-MgSite
   -SiteId <String>
   [-ExpandProperty <String[]>]
   [-Property <String[]>]
   [<CommonParameters>]
`
https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.sites/get-mgsite?view=graph-powershell-1.0

In version 1.9.2 this is available:

PS C:\Users\u49266> get-help get-mgsite

    Get-MgSite -SiteId <String> [-ExpandProperty <String[]>] [-Property <String[]>] [-Break] [-HttpPipelineAppend
    <SendAsyncStep[]>] [-HttpPipelinePrepend <SendAsyncStep[]>] [-Proxy <Uri>] [-ProxyCredential <PSCredential>]
    [-ProxyUseDefaultCredentials] [<CommonParameters>]

But in 1.9.5 a new mandatory parameter has been added (-Path) that is not documented, and I don't think should be required.

 Get-MgSite -Path <String> -SiteId <String> [-Break] [-HttpPipelineAppend <SendAsyncStep[]>] [-HttpPipelinePrepend
    <SendAsyncStep[]>] [-Proxy <Uri>] [-ProxyCredential <PSCredential>] [-ProxyUseDefaultCredentials]
    [<CommonParameters>]

**Comment by peombwa** [comment]
Thanks for bringing this to our attention. The new parameterSet was recently added to v1.0 endpoint hence the breaking change. We will address this in the upcoming release.
