### ISSUE TITLE
Get-MgGroup, returns System error

### ISSUE THREAD

**Issue by Petri-X** [microsoftgraph/msgraph-sdk-powershell#1215]
Hi,

I made a one liner, where I try to break the loop when I found what I'm looking for. I'm able to break it, but get an error. The easiest way to test this is run the following:
**Get-MgGroup  | % { break }**

And that returns:
```
Get-MgGroup : System error.
At line:1 char:1
+ Get-MgGroup  | % { break }
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgGroup_List], BreakException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List
```

You do not need to complain if above code is smart :D That is only for demonstrating the case. My one liner looks something like this:
Get-MgGroup |  % { Get-MgTeamChannel ; if found break }
The idea is, I try to found the correct channel. When founded, I do not need to go through the rest of the Teams.

**Comment by peombwa** [comment]
@Petri-X, this is a known PowerShell issue. In this case, `break` terminates `Get-MgGroup` enumerator (`$Error.Exception.StackTrace`).
> Using break inside a pipeline break, such as a ForEach-Object script block, not only exits the pipeline, it potentially terminates the entire runspace.

See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_break?view=powershell-7.2#do-not-use-break-outside-of-a-loop-switch-or-trap for more info. The same behavior can also be seen with other commands that enumerate the response e.g., `Get-AzVM | % { break }`.

What property are you trying to filter on? Consider using a server-side filter which is much faster (`-Filter`)- https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=powershell#example-2-get-a-filtered-list-of-groups-including-the-count-of-returned-objects.

**Comment by Petri-X** [comment]
Hi @peombwa 
But is this a problem in PowerShell itself or issue on Graph module? Or how do you see that there are many other CMDLets which don't break by this:
```
 Get-Service | % { break }
 Get-ChildItem| % { break }
```

The reason I end to this issue was the following problem:
[GitHub: Get-MgTeamChannel, how to filter using email address?](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1203)
When I go trough 170000 groups, that takes ages. So I though to speed this up so, that when I found what I'm looking for, the queries can be terminated. If I'm having luck I **could** get results quite fast.

The link you shared about "Do not use break outside of a loop, switch, or trap" is missing one information, what else I should use then, if break is not valid?

**Comment by peombwa** [comment]
The PowerShell commands referenced above don't page through the result (they return a single collection with all the items). MS Graph commands enumerate results asynchronously when fetching all pages (`-All`). i.e., we follow the [OData.NextLink](https://docs.microsoft.com/en-us/graph/paging?context=graph%2Fapi%2F1.0&view=graph-rest-1.0) URL until the last page is fetched. Using a break before the command is done fetching all pages causes the pipeline to throw an exception, as described in https://stackoverflow.com/questions/51981048/how-to-stop-get-content-wait-after-i-find-a-particular-line-in-the-text-file-us/60341948#60341948. See https://github.com/PowerShell/PowerShell/issues/12742 for more details.

One workaround is to avoid using `break` and instead use `Select -First 1` after a `where-object` as shown below:
``` powershell
 Get-MgGroup -Select Id, DisplayName -All | where { $_.DisplayName -eq "Test Group" } | select -First 1
```
This should safely exit the loop once the item in the where-object is found.
