### ISSUE TITLE
Add Raptor E2E Tests

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#122]
[AB#6782](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6782)

**Comment by MIchaelMainer** [comment]
You may want to look at https://github.com/Pester/Pester for this.

**Comment by peombwa** [comment]
Proposed order for implementing this:
1. Generate snippets for MS Graph docs.
2. Run those snippets in a test environment against sample data via Raptor.

**Comment by ddyett** [comment]
closing as tracked by other issues in raptor.
