### ISSUE TITLE
Get-MgUserCalendarGroup not supported

### ISSUE THREAD

**Issue by ChristopheLux** [microsoftgraph/msgraph-sdk-powershell#1223]
Hello
When using this in Graph Powershell (v1.0 or beta)  I have the following error message Specified method is not supported

Thanks in advvance

**Comment by peombwa** [comment]
@ChristopheLux, the command works as expected on our end. See https://docs.microsoft.com/en-us/graph/api/user-list-calendargroups?view=graph-rest-1.0&tabs=powershell#example for more details.

Please share the output of `-Debug` or `-ErrorVariable` with us:
``` powershell
Get-MgUserCalendarGroup -UserId $UserId -ErrorVariable CalendarGroupError
$CalendarGroupError.Exception # Share the output of this.
```

**Comment by ChristopheLux** [comment]
Hello,
Sorry I can't get out as text as this is in a very controlled org but here the screenshot 
![GraphErrorj](https://user-images.githubusercontent.com/11833461/164388916-cf2ff879-34b2-4d5c-9543-7d4bf0e9722a.jpg)

**Comment by peombwa** [comment]
@ChristopheLux The error you are getting is a service error and not an error related to the SDK. Could you verify that you've granted the app the necessary permissions as stated in https://docs.microsoft.com/en-us/graph/api/user-list-calendargroups?view=graph-rest-1.0&tabs=http#permissions? You can use ` Get-MgContext | select Scopes, AuthType` to find the permissions you've already granted the app.

If this doesn't work, please open a question, or support ticket at https://developer.microsoft.com/en-us/graph/support for the service owners to investigate. This repo is for SDK issues only.

**Comment by ChristopheLux** [comment]
Thanks Peter
I have opened a question to graph support and my context was delegated and Calendars.read as mentioned in the link you provided
