### ISSUE TITLE
No samples for New-MgAppCatalogTeamApp/Update-MgAppCatalogTeamApp cmdlets

### ISSUE THREAD

**Issue by paul-sk** [microsoftgraph/msgraph-sdk-powershell#1226]
It is unclear how to specify teams app zip in the BodyParameter of these cmdlets.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention. The APIs are currently not marked as supporting zip files in service metadata (that the SDK is generated from). I've opened an issue at https://github.com/microsoftgraph/msgraph-metadata/issues/163 for us to review and fix this in the service metadata.

As a workaround, you can use `Invoke-MgGraphRequest` to publish an app to the app catalog:
``` powershell
Invoke-MgGraphRequest -Uri "v1.0/appCatalogs/teamsApps" -ContentType "application/zip" -InputFilePath PATH_TO.zip
```

**Comment by peombwa** [comment]
This is a metadata issue. Issue was transferred to https://github.com/microsoftgraph/msgraph-metadata/issues/163.
