### ISSUE TITLE
Object types on New-MgIdentityConditionalAccessPolicy are incorrect

### ISSUE THREAD

**Issue by jspern** [microsoftgraph/msgraph-sdk-powershell#1236]
The object types listed for New-MgIdentityConditionalAccessPolicy all begin with a letter "I" which is incorrect. Trying to generate new objects using these types results in errors. The leading "I" needs to be removed.

**Comment by peombwa** [comment]
The object types are interfaces hence the `I` prefix. How are you creating new objects and which errors are you getting? Interfaces are valid types in PowerShell/.NET and serve a purpose in the commands.

The interfaces (optional) can be used to [create a new non-custom object](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_object_creation?view=powershell-7.2#create-non-custom-objects-from-hash-tables) as shown below without any issue:
``` powershell
$params = [Microsoft.Graph.PowerShell.Models.IMicrosoftGraphConditionalAccessPolicy]@{
	DisplayName = "Access to EXO requires MFA"
	State = "enabled"
	# Add more properties.
}

New-MgIdentityConditionalAccessPolicy -BodyParameter $params
```
See the examples at https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-1.0&tabs=powershell#example-1-require-mfa-to-access-exchange-online-outside-of-trusted-locations for more details.

**Comment by jspern** [comment]
After further testing it appears the issue is in PowerShell 7. Building the object the way you demonstrated and then running the command to create the policy works fine in Windows PowerShell, but in PowerShell 7 you will get errors similar to this:

`New-MgIdentityConditionalAccessPolicy_Create1: 1010: At least one include rule in 'users' condition is required. Try 'includeUsers' = ['none'] to start with. For examples, please see API documentation at https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-1.0.`

**Comment by peombwa** [comment]
@jspern, that's a validation error from the service saying you need to specify all the required properties. See the complete example at https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-1.0&tabs=powershell#example-1-require-mfa-to-access-exchange-online-outside-of-trusted-locations for more details.

**Comment by peombwa** [comment]
I've opened an issue against the PSReadLine module for them to fix the pasting issue. A fix will be provided by https://github.com/PowerShell/PSReadLine/issues/3306.
