### ISSUE TITLE
https://graph.microsoft.com/v1.0/groups?$filter=NOT groupTypes/any(c:c eq 'Unified')&$count=true

### ISSUE THREAD

**Issue by satyajit321** [microsoftgraph/msgraph-sdk-powershell#1238]
https://graph.microsoft.com/v1.0/groups?$filter=NOT groupTypes/any(c:c eq 'Unified')&$count=true is not working as expected, the count and the values contains a mix of output, both normal groups and Teams.

https://docs.microsoft.com/en-us/graph/query-parameters

List all non-Microsoft 365 groups in an organization. | GET ../groups?$filter=NOT groupTypes/any(c:c eq 'Unified')&$count=true. This is an advanced query.

In the Sandbox environment its working, but not working on actual tenant

The issue is visible on the Count variable as well.

#Count doesn't seem to bother, it gives all the groups - the values still has Teams, NOT isn't working
$NongroupCount = Invoke-MgGraphRequest -Method "GET" -Uri "https://graph.microsoft.com/v1.0/groups?$filter=NOT groupTypes/any(c:c eq 'Unified')&`$count=true" -Headers @{ConsistencyLevel='eventual'}
$NongroupCount.'@odata.count' 
$NongroupCount.Value

**Comment by peombwa** [comment]
Thanks for taking the time to open this issue. As this is a service issue that you are facing in your tenant, I'd recommend you open a question/ticket at https://developer.microsoft.com/en-us/graph/support to get assistance from the service workload. This repo is meant for SDK issues and not service issues.
