### ISSUE TITLE
Get-MgPrivilegedAccessRoleSetting is missing required parameter ResourceId

### ISSUE THREAD

**Issue by commawarcholik** [microsoftgraph/msgraph-sdk-powershell#1249]
I am unable to use Get-MgPrivilegedAccessRoleSetting, because it seems to be missing the ResourceID Parameter (also not listed in the documentation at 

https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.governance/get-mgprivilegedaccessrolesetting?view=graph-powershell-beta

```powershell
Get-MgPrivilegedAccessRoleSetting -PrivilegedAccessId AADRoles      
>>Get-MgPrivilegedAccessRoleSetting_List: The required parameters ResourceId is missing.

Get-MgPrivilegedAccessRoleSetting -PrivilegedAccessId AADRoles -ResourceId <tenantId>     
>>Get-MgPrivilegedAccessRoleSetting: A parameter cannot be found that matches parameter name 'ResourceId'.
```

The Update Method has the ResourceID Parameter, so I guess this is a bug?

edit: Same seems to be true for Get-MgPrivilegedAccessRoleDefinition

**Comment by peombwa** [comment]
@commawarcholik, this is an issue with the API; more specifically, the wording of the error message is misleading.

The command calls the right API with the correct parameters, but the service expects a customer to specify the `ResourceId` as a filter, as shown in the HTTP request example on [the API reference page](https://docs.microsoft.com/en-us/graph/api/governancerolesetting-list?view=graph-rest-beta#http-request):
> GET /privilegedAccess/azureResources/roleSettings?$filter=resourceId+eq+'<resourceId>'

In this case, you should use the command with the resourceId in the `-Filter` clause as shown below:
``` powershell
Get-MgPrivilegedAccessRoleSetting -PrivilegedAccessId AADRoles -Filter "resourceId eq '<tenantId>'"
``` 

I'll open an issue with the workload to fix the error message.

**Comment by commawarcholik** [comment]
Thank you, that solved my problem :)

**Comment by markmassad** [comment]
I see the issue is closed, but the workaround does not match the documentation.  Hopefully, that gets addressed without falling thru the crack.  Thanks!
