### ISSUE TITLE
Get-MgUser - AccountEnabled available from graph v1.0 but not the v1.0 MgProfile

### ISSUE THREAD

**Issue by rfeagley** [microsoftgraph/msgraph-sdk-powershell#1250]
We have found that while the AccountEnabled attribute is available and returns valid data directly from the v1.0 version of Graph, the Get-MgUser module must be called using the beta profile (Select-MgProfile -Name "beta") in order to return this data.

Graph Explorer:
![image](https://user-images.githubusercontent.com/34409513/167661401-32d73f1f-7353-4baa-8234-71f93249e3c3.png)

Get-MgUser:
![image](https://user-images.githubusercontent.com/34409513/167662759-08fe3c20-accb-4dd5-8625-226ee2964172.png)

**Comment by peombwa** [comment]
@rfeagley, you are missing `$select` equivalent parameter on the PowerShell command - `-Property`, i.e.,
``` powershell
Get-MgUser -Property Id, DisplayName, UserPrincipalName, AccountEnabled | select Id, DisplayName, UserPrincipalName, AccountEnabled
```
``` powershell
➜ Get-Help Get-MgUser -Parameter Property

-Property <String[]>
    Select properties to be returned

    Required?                    false
    Position?                    named
    Default value
    Accept pipeline input?       false
    Accept wildcard characters?  false
```
PowerShell's `Select-Object` (`| select`) is only used for output formatting.

**Comment by rfeagley** [comment]
I greatly appreciate the assistance.  I would highly recommend outlining this further in the documentation (https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/get-mguser).  Perhaps add a list of the default attributes returned (different between v1 and beta profiles) and an examples that utilize this property.  My issue is resolved.

**Comment by peombwa** [comment]
Thanks for the feedback. We will consider this as part of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/876.
