### ISSUE TITLE
[Intelligent Default] Get-MGSite SiteID Property should default to 'Root'

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#126]
Get-MGSite should default to -SiteId Root if no parameters specified, so a new user just typing "get-mgsite" gets their organization's root site by default.

Also SiteID should be Position=0 so that it can be specified implicity e.g. Get-MGSite root

**Comment by peombwa** [comment]
Thanks for reporting this to us. We have added this to our current milestone and we will have it available in our next release.

**Possible Solution:**
To fix this, we will default the `SiteId` parameter with `root` as its value for `Get-MgSite` cmdlet. It's worth reviewing other cmdlets that may need a default value as well.
Ref: https://github.com/Azure/autorest/blob/master/docs/powershell/directives.md#default-values

**Comment by peombwa** [comment]
Another candidate is `Get-MgGroupSite` - https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-beta&tabs=http#access-a-group-team-site
