### ISSUE TITLE
Cmdlet naming: Get-MgReportApplicationSign and Get-MgReportAzureAdApplicationSign

### ISSUE THREAD

**Issue by janegilring** [microsoftgraph/msgraph-sdk-powershell#1262]
Why aren`t Get-MgReportApplicationSign and Get-MgReportAzureAdApplicationSign named Get-MgReportApplicationSignIn and Get-MgReportAzureAdApplicationSignIn?

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

I can confirm that this is a bug with the code generator. I've opened an issue at https://github.com/Azure/autorest.powershell/issues/955 for the team to review and provide a fix. The proper command name should be `Get-MgReportApplicationSignInDetailedSummary`.

We will provide a temporary fix in our next release by aliasing the command name to the correct name to avoid a breaking change.

**Comment by ddyett** [comment]
this issue will track the work to use a directive to correct this.
