### ISSUE TITLE
About PreferredDataLocation

### ISSUE THREAD

**Issue by km-63** [microsoftgraph/msgraph-sdk-powershell#1266]
Is it possible to set the PreferredDataLocation value in the Microsoft Graph PowerShell SDK?

**Comment by peombwa** [comment]
@km-63, is this related to `PreferredDataLocation` property of a Group, `New-MgGroup -PreferredDataLocation "EU"`?.
> The preferred data location for the Microsoft 365 group. By default, the group inherits the group creator's preferred data location. To set this property, the calling user must be assigned one of the following [Azure AD roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference):
Global Administrator
User Account Administrator
Directory Writer
Exchange Administrator
SharePoint Administrator

> For more information about this property, see [OneDrive Online Multi-Geo](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-introduction).

> Nullable. Returned by default.

See https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#properties.
