### ISSUE TITLE
get-mguser doesn't support endswith?

### ISSUE THREAD

**Issue by Mike-Crowley** [microsoftgraph/msgraph-sdk-powershell#1268]
This article states that we can use endswith on user objects, with specific attributes, such as mail.

https://docs.microsoft.com/en-us/graph/aad-advanced-queries?tabs=powershell#support-for-filter-on-properties-of-azure-ad-directory-objects

it works as expected in graph, however the mg cmdlets throw an error: "get-mguser : Unsupported Query."

to repro: 
`get-mguser -Filter "endswith(mail, 'domain.com')"`

**Comment by Mike-Crowley** [comment]
Please disregard. I didn't realize ConsistencyLevel and CountVariable were mandatory parameters, when using advanced queries.

this works:

` get-mguser -Filter "endswith(mail, 'domain.com')" -ConsistencyLevel eventual -CountVariable countVar`

**Comment by mjabacor** [comment]
Hi Mike, 

Is it possible to use this  endswith(mail, '$_.domain'), What I'm trying to do is to get all email addresses with specific domain.
I don't know how this works.

I appreciate if you can provide your sample script.

Newbie

**Comment by Mike-Crowley** [comment]
List users and their onedrive site via graph:
```
Connect-MgGraph -Scopes Directory.Read.All -TenantId mikecrowley.us 

$Users = Get-MgUser -Select id -Filter "endsWith(mail, '@mikecrowley.us')" -ConsistencyLevel eventual -CountVariable countVar

#Apparently cannot combine queries with attributes that require select, so we have to run get-mguser twice
$Users | foreach {Get-MgUser -UserId $_.id -select id, displayname, mail, mysite} | select id, displayname, mail, mysite | sort mail
```

When filters get too complicated, I usually move them to their own variable(s):


```
$MyDomain = "@mikecrowley.us"

$Filter = 'endsWith(mail, ''' + $MyDomain + ''')'

$Users = Get-MgUser -Select id -Filter $Filter -ConsistencyLevel eventual -CountVariable countVar

$Users
```

**Comment by mjabacor** [comment]
Thank you Mike.
I thought Graph API can help to get this result thru multiple domains.

I appreciate your help :)

**Comment by Mike-Crowley** [comment]
It can, but I thought you were looking to take pipeline input.

- Mike Crowley
________________________________

**Comment by mjabacor** [comment]
sorry for the confusion.
your command is an excellent example but is there a way to run this with multiple domains?
like example, adding more domain in here?
$Filter = 'endsWith(mail, ''' + $MyDomain + ''')'

**Comment by mjabacor** [comment]
Hi Mike,

You are a GENIUS!
This is FIXED

Thank you!
