### ISSUE TITLE
Failed to get license information for the user

### ISSUE THREAD

**Issue by Johan-Claesson** [microsoftgraph/msgraph-sdk-powershell#1270]
Hello, 
Im writing a Powershell Script to restart our Teams Room Devices trough graph API, using the CMDLET Get-MgTeamworkDevice. 
I'm currently managing multiple Office365 Tenants and in one of them I get the following error:
```Powershell
Get-MgTeamworkDevice : Failed to get license information for the user. Ensure user has a valid Office365 license assigned to them.
At line:1 char:1
+ Get-MgTeamworkDevice
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType15`8) [Get-MgTeamworkDevice_List], RestException`1
    + FullyQualifiedErrorId : Forbidden,Microsoft.Graph.PowerShell.Cmdlets.GetMgTeamworkDevice_List
```

I found that it was a similar issue posted here: https://github.com/OfficeDev/microsoft-teams-apps-requestateam/issues/355

**Comment by zaaj** [comment]
@Johan-Claesson - what was the fix?  I'm still getting the same error on windows 10, windows powershell 5.1, Microsoft.Graph module version 1.27.0

**Comment by bsj17** [comment]
> @Johan-Claesson - what was the fix? I'm still getting the same error on windows 10, windows powershell 5.1, Microsoft.Graph module version 1.27.0
@Johan-Claesson
I'm also getting this error. Querying all teamworkdevices and on one device there's a user signed-in without a license. Query stops with an error. It looks to me this was never fixed
