### ISSUE TITLE
New-MgInvitation Insufficient privileges when using system assigned managed identity in runbook

### ISSUE THREAD

**Issue by DBLHB** [microsoftgraph/msgraph-sdk-powershell#1274]
New-MgInvitation fails with "Insufficient privileges to perform requested operation by the application '00000003-0000-0000-c000-000000000000'. ControllerName=MSGraphInviteAPI, ActionName=CreateInvite" when using it with a system assigned managed identity in a powershell runbook (runtime version 5.1).

The Automation Account has a system assigned managed identity, its service principal has the "Directory.writers" role assigned in AAD. 

In the runbook I'm connecting to the Graph using:

```
Connect-AzAccount -Identity | Out-Null
$token = Get-AzAccessToken -ResourceUrl "https://graph.microsoft.com"
Connect-MgGraph -AccessToken $token.Token | Out-Null
```

It works for other tasks (i.e. updating user accounts etc.).

It fails when using:

```
$invitation = New-MgInvitation -InvitedUserEmailAddress $email -InvitedUserDisplayName $name -InviteRedirectUrl $redirectUrl
    
    $invDetails = @{
            Email     = $invitation.InvitedUserEmailAddress                 
            URL      = $invitation.InviteRedeemUrl
            ObjectId = $invitation.InvitedUser.Id
            }
```

I've also tried using this:

`Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/invitations" -Body $body -ContentType "application/json; charset=utf-8"`

But it fails with:

Response status code does not indicate success: Unauthorized (Unauthorized).

**Comment by peombwa** [comment]
@DBLHB, the error message indicates that the app is not authorized to create an invitation. Please verify that your token has the required permissions as documented in https://docs.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0&tabs=http#permissions. See https://docs.microsoft.com/en-us/graph/permissions-reference.

You can use http://jwt.ms/ to inspect the `scp` claim, which contains your app's permission

**Comment by DBLHB** [comment]
Hi @peombwa 

thanks for pointing me in the right direction - I finally managed to assign the Graph permission to the system assigned managed identity using this article:

https://gotoguy.blog/2022/03/15/add-graph-application-permissions-to-managed-identity-using-graph-explorer/

So, I guess we just need to wait until Connect-MgGraph supports the use of Managed Identities.

Thanks...

**Comment by ddyett** [comment]
looks like this is resolved and work tracks other issues.
