### ISSUE TITLE
Connect-MgGraph doesn't support app ID + secret

### ISSUE THREAD

**Issue by Nazul** [microsoftgraph/msgraph-sdk-powershell#1279]
We cannot use Connect-MgGraph with an app/client ID and secret, just certificates.

There was an old issue saying that was going to be considered for the GA release, but it's still missing.
https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/242

Is this still considered to be included? Secrets, although not the best practice, are still present in app registrations and other Graph SDKs.

**Comment by ddyett** [comment]
@maisarissi to you on support for this.

**Comment by peombwa** [comment]
Client secret is now supported in v2 - https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/docs/upgrade-to-v2.md#client-secret-credentials.
