### ISSUE TITLE
Help with adding a tab

### ISSUE THREAD

**Issue by tintong** [microsoftgraph/msgraph-sdk-powershell#1287]
Hello,

I'm looking for some help with adding a website as a tab to a new team via the Graph SDK please.

I've found the command that I think is correct which is "New-MgTeamChannelTab" but I'm unsure on how I use this with the various switches and / or hashtables.

Could anyone please help with an example?

I'd be very grateful for this.

Thanks

**Comment by peombwa** [comment]
Please consider posting "how-to" questions at https://docs.microsoft.com/en-us/answers/products/graph in the future for faster responses. This repo is only meant for blocking issues related to the SDK.

Using the instructions at https://docs.microsoft.com/en-us/graph/api/channel-post-tabs?view=graph-rest-1.0 and configuration details at https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs, you can add (pin) a website to a Team's channel as shown below:
``` powershell
$TeamId = "TEAM_ID"
$ChannelId = "CHANNELL_ID"
$Params = @{
    displayName = "My Web Tab"
    "teamsApp@odata.bind" = "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.web"
    configuration = @{
        contentUrl = "https://bing.com"
        websiteUrl = "https://bing.com"
    }
}
New-MgTeamChannelTab -TeamId $TeamId -ChannelId $ChannelId -BodyParameter $Params
# or
New-MgTeamChannelTab -TeamId $TeamId -ChannelId $ChannelId -DisplayName $Params.displayName -Configuration $Params.configuration -AdditionalProperties @{"teamsApp@odata.bind" = $Params."teamsApp@odata.bind" }
```

Please note that the commands in this SDK mirror the API design and behavior as-is. i.e., API request bodies mirror command parameters. See https://docs.microsoft.com/en-us/powershell/microsoftgraph/navigating?toc=%2Fgraph%2Ftoc.json&view=graph-powershell-1.0.

**Comment by ontorder** [comment]
i wanted to report that the doc for this cmdlet
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.teams/new-mgteamchanneltab
has Get in the examples instead of New
