### ISSUE TITLE
Alternative of MSOnline Set-MsolDomainAuthentication in the Microsoft Graph module

### ISSUE THREAD

**Issue by weijinrippling** [microsoftgraph/msgraph-sdk-powershell#1292]
Since the Powershell MSOnline module is being deprecated, what is the alternative of MSOnline Set-MsolDomainAuthentication in the Microsoft Graph module?

**Comment by peombwa** [comment]
Please open a feature request for the workload at https://developer.microsoft.com/graph/support, as the service does not currently support this. This SDK only supports Microsoft Graph APIs that are publicly available.

According to the [API reference page](https://docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta#properties), `authenticationType` is marked as read-only, indicating that changing a domain's authentication type is not yet supported on Microsoft Graph.
