### ISSUE TITLE
Can't seem to be able to assign app permissions to a managed identity service principal

### ISSUE THREAD

**Issue by josefehse** [microsoftgraph/msgraph-sdk-powershell#1293]
Trying to assing microsoft graph permissions to a managed identify azure function.
The old method (AzureAD) works fine. With the new module, here's the issue:
I can get application ID and object ID of the MI using Get-azadServicePrincipal.
When trying to use Add-AzADPermission it fails:
![image](https://user-images.githubusercontent.com/13967863/171255801-85a373ef-7962-4fec-bc65-13edb447a058.png)
You can see the module uses get-azadapplication:
![image](https://user-images.githubusercontent.com/13967863/171255881-39acaa96-3f16-4ea8-8ad4-b3629f379e89.png)
However, get-azadapplication won't find service principals for Managed Identities, only Enterprise Applications.
Am I missing something or is it a gap?

Thank you.
Latest az modules.

**Comment by peombwa** [comment]
The commands referenced above belong to the Az module and not Microsoft Graph PowerShell SDK. Please open an issue for them at https://github.com/Azure/azure-powershell.
