### ISSUE TITLE
MS Graph powershell needs updated permissions to see CA policies in Azure AD sign-in logs

### ISSUE THREAD

**Issue by besiler** [microsoftgraph/msgraph-sdk-powershell#1316]
As part of a security hardening effort required by MSRC, Azure AD engg recently made a breaking change that requires users or apps to have conditional access read permissions to view CA policies in the sign in logs (in addition to permission to view the sign-in logs generally). In the MS Graph docs, you can see the required permissions: [Get signIn - Microsoft Graph v1.0 | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-1.0&tabs=http#viewing-applied-conditional-access-ca-policies-in-sign-ins)

Currently, customers are trying to use powershell to view CA policies in the sign-in logs but they can't since powershell doesn't have the right CA view permissions: https://www.yammer.com/cepartners/#/threads/show?threadId=1772062637826048

Can you please add one of the permissions listed in the doc above to MS Graph Powershell so that users with the right role can view CA permissions? The required permissions are one of the following:

Policy.Read.All
Policy.ReadWrite.ConditionalAccess
Policy.Read.ConditionalAccess

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

Customers should be able to consent to the necessary permissions using `Connect-MgGraph -Scopes Policy.Read.All` without any issue.

**Comment by besiler** [comment]
@peombwa Thanks! Will you add that to the powershell docs? 

I'll pass this info along to customers and let you know if they have any further comments.

**Comment by peombwa** [comment]
@besiler, we are not able to preemptively ask customers to consent to permissions given our resource-based incremental scope consent model, i.e., customers need to know ahead of time which permissions they need and call `Connect-MgGraph -Scopes` to incrementally consent to them. Also, `Policy.Read.All` is not required to get sign-in logs; customers can still list them without it, minus the extra properties it adds.

We plan to create a link from the command reference docs to API reference docs to aid in permission discoverability. We are tracking this in #1302.

**Comment by besiler** [comment]
@peombwa thank you for the clarification! I appreciate your guidance on this
