### ISSUE TITLE
Get-MGUserLicenseDetail Fails for some accounts

### ISSUE THREAD

**Issue by sheabryarly** [microsoftgraph/msgraph-sdk-powershell#1323]
Hello,

For some reason the cmdlet fails with the following error message:

Command:
$licenses = Get-MGUserLicenseDetail -UserId $u.Id -ErrorAction Stop

Result:
     |
     |          $scriptCmd = {& $wrappedCmd @PSBoundParameters}
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Expected literal (number, boolean, or null). Was '<'._

I've verified that the account exists in the tenant and that it was definitely passing a user GUID (im getting them from get-mguser). It fails on the same exact accounts and I don't know what makes the difference. 

Any thoughts?

**Comment by peombwa** [comment]
@sheabryarly, please ensure you are using the latest version of the SDK (`1.9.6`). 

See https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1204.
