### ISSUE TITLE
Get-MgDrive -Search doesn't appear to do anything

### ISSUE THREAD

**Issue by mattgrif** [microsoftgraph/msgraph-sdk-powershell#133]
No matter what I search unless it throws an error due to . being invalid character it returns the same 2 document libraries for the root SharePoint Site Collection (Shared Documents and PreservationHoldLibrary) 
[AB#7436](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7436)

**Comment by darrelmiller** [comment]
Do you have the same problem if you try making the query in Graph Explorer?  

Here is a sample query in Graph Explorer:
https://developer.microsoft.com/en-us/graph/graph-explorer/preview?request=me/drive/root/search(q='finance')?select=name,id,webUrl&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=e30=

**Comment by mattgrif** [comment]
> Do you have the same problem if you try making the query in Graph Explorer?
> 
> Here is a sample query in Graph Explorer:
> https://developer.microsoft.com/en-us/graph/graph-explorer/preview?request=me/drive/root/search(q='finance')?select=name,id,webUrl&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=e30=

I searched the term IS and through Graph explorer I receive more then 20 results - the command just returns the Documents and Preservation Hold Libraries.

**Comment by peombwa** [comment]
This is an SDK bug. We are missing the following paths in our OpenAPI docs:
- `'/drives/{drive-id}/root/microsoft.graph.search(q='{q}')'` => `Search-MgDrive`.
- `'/groups/{group-id}/drive/root/microsoft.graph.search(q='{q}')'` => `Search-MgGroupDrive`.
- `'/sites/{site-id}/drive/root/microsoft.graph.search(q='{q}')'` => `Search-MgSiteDrive`.
- `'/users/{user-id}/drive/root/microsoft.graph.search(q='{q}')'` => `Search-MguserDrive`.
