### ISSUE TITLE
Invoke-MgGraphRequest not respecting $value (beta endpoint)

### ISSUE THREAD

**Issue by ericmatenaer** [microsoftgraph/msgraph-sdk-powershell#1332]
In attempting to get B2C Trust Framework Policies, Graph Explorer returns the correct data however using 'Invoke-MgGraphRequest' will only return the policy, not the value of the policy.

URI used in GE: https://graph.microsoft.com/beta/trustFramework/policies/<policyid>/$value
Graph SDK example: Invoke-MgGraphRequest -Method GET -URI "https://graph.microsoft.com/beta/trustFramework/policies/<policyid>/$value"

**Comment by peombwa** [comment]
@ericmatenaer, you need to escape `$` in `$value`. `$` is used to access variables in PowerShell. See PowerShell's quoting rules at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.2.
