### ISSUE TITLE
Concurrent jobs issues in Azure Automation with MS Graph

### ISSUE THREAD

**Issue by lucas-tessi** [microsoftgraph/msgraph-sdk-powershell#1337]
Hello,

I am facing some issues when an Azure Runbook is running several times in the same Azure sandbox.
I am using some Graph PowerShell commands and in some executions, the graph module is getting disconnected by the "disconnect-mggraph" command from the another execution.

Microsoft support told me to create an issue here so you can help me better on my problem

Could you help me please ?

**Comment by ddyett** [comment]
@peombwa have we come across this before?

**Comment by peombwa** [comment]
@lucas-tessi, please use `Connect-MgGraph -ContextScope Process` when authenticating to isolate the auth context to the current process.

By default, signing in as a user sets the `ContextScope` to `CurrentUser` i.e., the auth context is shared by all processes of the current OS user.

**Comment by deanlongstaff** [comment]
@peombwa Apologies to pickup on an old thread. I have a scenario where I need to concurrently manage multiple tenants using the graph powershell SDK. Running this in Azure Functions which uses runspaces by default because they're nice and efficient. However do runspaces share the same process?

I'm wondering if runspaces are unsuitable with the graph SDK due to a change in connection running at the process level and affecting all other runspaces in that process? Let me know your thoughts. Thanks

**Comment by salbeck-sit** [comment]
@deanlongstaff I found this in an old blog: Runspaces create a new thread **on the existing proces** so it appears your hunch is correct that -ContextScope Process is of no real use. Unless MS uses a different kind of isolation.
See https://devblogs.microsoft.com/scripting/beginning-use-of-powershell-runspaces-part-1/

**Comment by deanlongstaff** [comment]
> @deanlongstaff I found this in an old blog: Runspaces create a new thread **on the existing proces** so it appears your hunch is correct that -ContextScope Process is of no real use. Unless MS uses a different kind of isolation.
> See https://devblogs.microsoft.com/scripting/beginning-use-of-powershell-runspaces-part-1/

Thanks @salbeck-sit. I ran some tests on this yesterday and can confirm that runspaces do share the processes state. So if you need secure context isolation between invocations, you can only have a maximum of 1 runspace per process.

Bit of a bummer as that's a huge performance hit for things like server-less functions where concurrency is king and memory is finite.
