### ISSUE TITLE
Get-MgDevice -DeviceId does not work with Device ID

### ISSUE THREAD

**Issue by i-windows** [microsoftgraph/msgraph-sdk-powershell#1343]
When using 
get-MgDevice -DeviceId _deviceID_
with the deviceID published in the Azure properties an error is thrown. resource <guid> does not exist...

when using get-MgDevice -DeviceId _ObjectID_
with the ObjectID published in Azure properties the command runs successfully

please update the command either to accept the correct deviceID, or rename the deviceID param to ObjectID

example.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/6116167/175500491-d422dc03-da16-4937-8b77-5fc376b2cb6b.png">

<img width="440" alt="image" src="https://user-images.githubusercontent.com/6116167/175500659-2efcc88e-26a3-45b0-b094-766757a43b44.png">

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

We are already tracking this in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906.
