### ISSUE TITLE
Microsoft.Graph.Groups module reference is incomplete - missing Remove-MgGroupMemberByRef

### ISSUE THREAD

**Issue by CelesteDG** [microsoftgraph/msgraph-sdk-powershell#1345]
See the comments in GitHub issue https://github.com/microsoftgraph/microsoft-graph-docs/issues/17422 for more info.

CC @msewaweru @FaithOmbongi

**Comment by peombwa** [comment]
@timayabi2020, can you help with refreshing the PowerShell reference docs? The command is available as of https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.10.0 released 2 days ago.

We should also review the current CI/CD infrastructure to ensure we have timely refreshes of the reference docs.

**Comment by timayabi2020** [comment]
@peombwa The weekly powershell docs refresh pipeline failed, therefore no latest branch related to docs was automatically published to the powershell repo. I've just manually triggered the run again

**Comment by timayabi2020** [comment]
@msewaweru please see the [review link](https://review.docs.microsoft.com/en-us/powershell/module/microsoft.graph.groups/remove-mggroupmemberbyref?view=graph-powershell-1.0&branch=pr-en-us-66).
This is the equivalent [PR](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/66) to that link
