### ISSUE TITLE
Get-MgBookingBusinessAppointment -All only returns the first 100 appointments

### ISSUE THREAD

**Issue by cookmatt** [microsoftgraph/msgraph-sdk-powershell#1351]
Executing:
```
$bookingBusinessId='bookingbusiness@sometenant.onmicrosoft.com'
Get-MgBookingBusinessAppointment -BookingBusinessId $bookingBusinessId -All
```

returns 100 appointments.

However, via the API more than 100 are returned, for example -
```
$appointments=@()
$uri="/v1.0/solutions/bookingBusinesses/$bookingBusinessId/appointments"
do {
    $result=Invoke-MgGraphRequest -Method GET -uri $uri
    $appointments+=$result.value
    $uri=$result.'@odata.nextLink'
} until ($null -eq $result.'@odata.nextLink')
```
The issue was initially spotted in 1.9.4 but appears to still be present in 1.10.0

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

This is partly a service issue. The API is not returning an OData nextLink when we request `$top` of 100. APIs should return a nextLink when a `$top` of any value is specified when there are more pages to fetched. This is necessary to support pagination. I'll follow up with the workload owner internally to see if this can be fixed.

We also plan to drop our default page size of 100 and just work with the page size we are getting from the service. We are tracking this in #1141.
