### ISSUE TITLE
Microsoft.Graph.Teams: Cannot manage or enumerate Teams App Permission Policies

### ISSUE THREAD

**Issue by tdemgit** [microsoftgraph/msgraph-sdk-powershell#1353]
With the removal of the commands to manage Teams App Permission policies in the MicrosoftTeams powershell module, we are left with no solution to assess whether an admin has deployed an app without approval (i.e. added this app to a teans app permission policy and installed it in a team).

Get-MgAppCatalogTeamApp returns all apps available for installation
Get-MgTeamsInstalledApp returns all apps installed in a specific team

These are of no help to cross reference which apps are in a Teams app permission policy

This is a big issue, we cannot allow apps to be deployed without having been vetted first, so they are not approved for being added to a Teams app permission policy and until June 15 we were able to enumerate these policies and find out if someone (teams admin) had added an app. This feature is no longer available.

How can we find out which apps are whitelisted for installation via a Teams App Permission policy?  Teams app permission policies can only be managed via the Teams admin portal.

**Comment by peombwa** [comment]
Thanks for following up on this.

As this repository is intended for issues related to the functionality of the SDK, we may not be the best placed to answer some queries that are tied to the functionality of the API.

Please open a feature request at https://developer.microsoft.com/en-us/graph/support for the workload owner to add this API to Microsoft Graph.
