### ISSUE TITLE
New-MgUser issue with Manager assign

### ISSUE THREAD

**Issue by RikuKyomiya** [microsoftgraph/msgraph-sdk-powershell#1380]
I wasn't able to use manager parameter in New-MgUser and got an error as below. Any help is appreciated.
![image](https://user-images.githubusercontent.com/35610066/178159169-54eb629a-15c4-4fb7-9012-3761a7deee85.png)

**Comment by peombwa** [comment]
@RikuKyomiya, the API does not allow you to assign a manager while creating a user. You should use `Set-MgUserManagerByRef` to assign a user's manager after creating the user. See the example at https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=powershell#request.

**Comment by RikuKyomiya** [comment]
@peombwa 
I see.
But what is the -manager in New-MgUser used for?
https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/new-mguser?view=graph-powershell-1.0

**Comment by peombwa** [comment]
Unfortunately, the OpenAPI file that is used to generate the command says all the entire properties of a [`User`](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties) resource type, relationships included, can be set during a create operation. We are working to address this in the OpenAPI file conversion process at https://github.com/microsoft/OpenAPI.NET.OData.

**Comment by peombwa** [comment]
Closing as the original question has been answered.

The unnecessary parameter will be fixed in https://github.com/microsoft/OpenAPI.NET.OData/issues/254.
