### ISSUE TITLE
Connect-MgGraph: Environment parameter does not support auto-complete

### ISSUE THREAD

**Issue by adamedx** [microsoftgraph/msgraph-sdk-powershell#1386]
The `Environment` parameter of `Connect-MgGraph` requires the user to use `Get-MgEnvironment` to enumerate environments. Instead, we should add a parameter completer that does this so the user gets auto-complete.

We should also add this completer to any other commands in `Microsoft.Graph.Authentication` that take `Environment` as a parameter, such as `Get-MgEnvironment`.

**Comment by FehintolaObafemi** [comment]
https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/fehintolaobafemi/parameter-completers
