### ISSUE TITLE
Get-MgAuditLogSignIn : Invalid Skip Token, skip token is null

### ISSUE THREAD

**Issue by pretzelise** [microsoftgraph/msgraph-sdk-powershell#1388]
Hello!

Since yesterday morning, running `Get-MgAuditLogSignIn -All:$True -Filter "Status/ErrorCode eq 0"` returns a slew of the same error:

```
Get-MgAuditLogSignIn : Invalid Skip Token, skip token is null
At line:1 char:1
+ $SignIns = Get-MgAuditLogSignIn -All:$True -Filter "Status/ErrorCode  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = 100, Sk...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgAuditLogSignIn_List1], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List1
```

I have tried to change my MgProfile to "beta" but that hasn't changed anything. I also can't find any mention of this issue online from the past few days.

**Comment by peombwa** [comment]
Thanks for following up on this.

This is a transient issue with the service that has been reported before in other repositories - https://github.com/microsoftgraph/microsoft-graph-docs/issues/8612.

Please open a question/support ticket at https://developer.microsoft.com/en-us/graph/support to get assistance from the workload owner. You can run the command with `-Debug` to log the `request-id` header of the failing request.
