### ISSUE TITLE
msgraph support for Bash

### ISSUE THREAD

**Issue by R-LIBIN** [microsoftgraph/msgraph-sdk-powershell#1398]
Hello Team , 

We see predominantly bash seen the enterprise use and has lot applications in systems automation. As, we move through cross platform support with linux from microsoft. It makes the cross platform support from powershell to bash the native requirement. As we move in the future we should be in progress in all ways. I have humble request to implement a bin yum/apt package for graph api in bash for  g unix/linux. 

Please help. 

I would be happy if this bears fruit. 

Also, include support for large attachment in one function. 

Thank you. 

Regards, 
Libin

**Comment by R-LIBIN** [comment]
Hope, it includes error support like errors, auth error, email not sent and unable to send due to wrong email.

**Comment by R-LIBIN** [comment]
Plese take it further with all support of cross support with the c# env.

**Comment by peombwa** [comment]
@R-LIBIN, PowerShell is already cross-platform and can be install on major Linux distros - https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2.

This module is cross-platform and works on Windows, macOS, and Linux. See supported features at https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?toc=%2Fgraph%2Ftoc.json&view=graph-powershell-1.0#features :
> Cross-platform support and available on PowerShell 7 and above: Microsoft Graph PowerShell module works with PowerShell 7 and later and on all platforms including Windows, macOS, and Linux. It's also compatible with Windows PowerShell 5.1.

**Comment by R-LIBIN** [comment]
For enterprise, people don't allow powershell just for one thing. So, it is
quite a need to have bash support with the graph API.

**Comment by peombwa** [comment]
Then https://github.com/microsoftgraph/msgraph-cli is what you are looking for. The Microsoft Graph CLI is still in development. It will cover scenarios where customers are unable to use PowerShell in their environments.

As far as this repo is concerned, the module is supported on Linux and works as expected.
