### ISSUE TITLE
Missing cmdlets for identity protection module

### ISSUE THREAD

**Issue by cuixi1222** [microsoftgraph/msgraph-sdk-powershell#1400]
1. Dismiss risky users
    https://docs.microsoft.com/en-us/graph/api/riskyusers-dismiss?view=graph-rest-beta&tabs=http
2. Confirm Safe for Sign in
    https://docs.microsoft.com/en-us/graph/api/signin-confirmsafe?view=graph-rest-beta&tabs=http
3.  Confirm compromised for sign in
    https://docs.microsoft.com/en-us/graph/api/signin-confirmsafe?view=graph-rest-beta&tabs=http

**Comment by cuixi1222** [comment]
found invoke-mgdismissriskyuser for #1, still missing #2 & #3
https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/invoke-mgdismissriskyuser?view=graph-powershell-beta

**Comment by peombwa** [comment]
2 & 3 are available in the `Reports` modules and can be called via [Confirm-MgAuditLogSignInSafe](https://docs.microsoft.com/en-us/graph/api/signin-confirmsafe?view=graph-rest-beta&tabs=powershell#request) and [Confirm-MgAuditLogSignInCompromised](https://docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&tabs=powershell#request):
``` powershell
❯❯ Find-MgGraphCommand -Uri "/auditLogs/signIns/confirmSafe"

   APIVersion: beta

Command                      Module  Method URI                            OutputType Permissions Variants
-------                      ------  ------ ---                            ---------- ----------- --------
Confirm-MgAuditLogSignInSafe Reports POST   /auditLogs/signIns/confirmSafe            {}          {Confirm, ConfirmExpanded}

❯❯ Find-MgGraphCommand -Uri "/auditLogs/signIns/confirmCompromised"

   APIVersion: beta

Command                             Module  Method URI                                   OutputType Permissions Variants
-------                             ------  ------ ---                                   ---------- ----------- --------
Confirm-MgAuditLogSignInCompromised Reports POST   /auditLogs/signIns/confirmCompromised            {}          {Confirm, ConfirmEx…
```
