### ISSUE TITLE
Connect-MgGraph hangs with UseDeviceAuthentication

### ISSUE THREAD

**Issue by ElSrJuez** [microsoftgraph/msgraph-sdk-powershell#1403]
**Description:**
I am trying to log in to use the Microsoft.Graph module with UseDeviceAuthentication, but when using the parameter It hangs.

Similar to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/305
**Expected Behavior:** 
I get a text line on the console with a web link and a one-time code to log in on a separate browser  

**Example:**
```
PS C:\> $GraphContext = Connect-MgGraph -UseDeviceAuthentication -TenantId $TenantID
Connect-MgGraph : Device code terminal timed-out after 120 seconds. Please try again.
At line:1 char:17
+ ... phContext = Connect-MgGraph -UseDeviceAuthentication -TenantId $TenantID ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MgGraph], Exception
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph
```

**Comment by peombwa** [comment]
@ElSrJuez, you are holding the output in `$GraphContext` variable hence no device code is printed on your session.

Please invoke the command without holding the output in a variable:
``` powershell
PS C:\> Connect-MgGraph -UseDeviceAuthentication -TenantId $TenantID
```

You can get the auth context by calling `Get-MgContext` after `Connect-MgGraph`.

**Comment by ElSrJuez** [comment]
Ok, but then the bug is that this cmdLet outputs the prompt to the pipeline instead of the host/console!
