### ISSUE TITLE
Update-MgDeviceManagementManagedDeviceUser (Feature Request)

### ISSUE THREAD

**Issue by othyssen** [microsoftgraph/msgraph-sdk-powershell#1404]
Microsoft.Graph.Devicemanagement
Version 1.10.0

While **Get-MgDeviceManagementManagedDeviceUser** is working like a charm to retrieve the Primary User of an Intune device,  there should be a _simple_ command available to update the primary user, like

**_Update_-MgDeviceManagementManagedDeviceUser** -ManagedDeviceId "xxxx" -UserId "yyyyy"

as mentioned in Issue #634 there is _New-MgDeviceManagementManagedDeviceUserByRef_ available but it requires to build a hash table within the script first.

**Comment by othyssen** [comment]
I tried various ways in **Graph Explorer** with POST to have have an idea how _New-MgDeviceManagementManagedDeviceUserByRef_ is working but I'm ending up with "An error has occurred" or sometimes with "Write requests are only supported on contained entities or navigation properties with bindings."
Nice example of the request body much appreciated

**Comment by peombwa** [comment]
Thanks for following up on this.

Unfortunately, this is one of those API that requires you to build a hash table with the id of the reference object to be added - `New-MgDeviceManagementManagedDeviceUserByRef`. The examples should ideally be available in https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-update?view=graph-rest-beta#example as other workloads do, but this is currently not the case.

As for the errors you are getting, please open a question/ticket at https://developer.microsoft.com/en-us/graph/support to get help from the API owners/workload owner.

**Comment by othyssen** [comment]
The documentation [new-mgdevicemanagementmanageddeviceuserbyref](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement/new-mgdevicemanagementmanageddeviceuserbyref) isn't accessible anymore which makes it difficult to select the attributes for the hash table

**Comment by peombwa** [comment]
It looks like the workload owner removed the `new-mgdevicemanagementmanageddeviceuserbyref` API from the service schema:
``` powershell
➜ Find-MgGraphCommand -Uri "/deviceManagement/managedDevices/{managedDevice-id}/users.*"

   APIVersion: v1.0

Command                                 Module           Method URI                                                       OutputType          Permissions Variants
-------                                 ------           ------ ---                                                       ----------          ----------- --------
Get-MgDeviceManagementManagedDeviceUser DeviceManagement GET    /deviceManagement/managedDevices/{managedDevice-id}/users IMicrosoftGraphUser {}          {List}

   APIVersion: beta

Command                                 Module           Method URI                                                       OutputType           Permissions Variants
-------                                 ------           ------ ---                                                       ----------           ----------- --------
Get-MgDeviceManagementManagedDeviceUser DeviceManagement GET    /deviceManagement/managedDevices/{managedDevice-id}/users IMicrosoftGraphUser1 {}          {List1}
```

Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support to get help from the API owner as this is an service related question.
