### ISSUE TITLE
ENHANCEMENT: Get-MgTeam: Support -Filter / -DisplayName parameters

### ISSUE THREAD

**Issue by woter1832** [microsoftgraph/msgraph-sdk-powershell#1407]
It is very difficult to find the `TeamId`. One has to go through the process of generating a link to extract the `GroupId`.

It would be very helpful if you could:

- Remove `-TeamId` as a mandatory parameter. It would be handy to be able to list all objects within the tenant.
- Add support for `-Filter` parameter, where I could do `Get-MgTeam -Filter "displayName eq 'MyChannel'"` (Filter is common amongst other MG cmdlets).
- Add support for `-DisplayName`, where I could do `Get-MgTeam -DisplayName "MyChannel"`. If you added wildcard support, that would be awesome. e.g. `Get-MgTeam -DisplayName "*xyz*`

**Comment by peombwa** [comment]
Thanks for following up on this.

The module is generated based on what is described as possible in the service metadata - https://graph.microsoft.com/v1.0/$metadata.

Currently, there isn't an [API](https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0#methods) that allows you to list teams `GET \teams` (coming soon in beta). `-Filter` will be supported once the API to list teams is available.

OData already supports [$search query parameter](https://docs.microsoft.com/en-us/graph/search-query-parameter?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=http) (-Search in PowerShell) for the scenario you are looking for with `-DisplayName`. Unfortunately, Teams APIs does not currently support `$search` query parameter. Please log a feature request for the API owner at https://developer.microsoft.com/en-us/graph/support if this is something you'd like to be supported. Once supported, you will be able to search for a team using:
``` powershell
Get-MgTeam -Search "MyChannel"
# or using KQL syntax.
Get-MgTeam -Search "displayName:MyChannel"
```
