### ISSUE TITLE
Investigate missing System.Security.Cryptography.ProtectedData error in PS core 6.X

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#141]
Investigate missing System.Security.Cryptography.ProtectedData error in PS core 6.2.4.

This works in PS core 7+.

**Comment by tobvil** [comment]
I'm getting this error when trying to "Connect-Graph" from an Azure Function.

**Comment by peombwa** [comment]
This issue can easily be reproed in Azure Functions which also uses PowerShell 6.2.4. This doesn't happen in PowerShell 5 and 7+. 
The error is raised due to a mismatched dependency version of  [System.Security.Cryptography.ProtectedData](https://www.nuget.org/packages/System.Security.Cryptography.ProtectedData/4.6.0) between [Microsoft.Identity.Client](https://www.nuget.org/packages/Microsoft.Identity.Client/4.8.2) and our project. We will fix this issue in the next release.
