### ISSUE TITLE
Get-MgTeamMember requires TeamMember.ReadWrite.All

### ISSUE THREAD

**Issue by woter1832** [microsoftgraph/msgraph-sdk-powershell#1410]
Why does a `Get` command require `write` permissions?

```
Get-MgTeamMember -TeamId $oTeam.Id
Get-MgTeamMember_List1: Caller does not have the required permissions for accessing this API. AllowedPermissions:'TeamMember.Read.All,TeamMember.ReadWrite.All,TeamMember.Read.Group'
```

![image](https://user-images.githubusercontent.com/68354513/180178067-d4a2b692-df9e-4d42-a328-6789cedae69a.png)

I also note, there is no such permissions as `TeamMember.Read.Group`:
![image](https://user-images.githubusercontent.com/68354513/180177895-1ab7c7d4-057d-42f5-80ac-059846e025bf.png)

Thanks

**Comment by peombwa** [comment]
@woter1832, `TeamMember.ReadWrite.All` supports both `Read` and `Write` operations; not just `Write`. The permissions are presented from least to most privileged, where `TeamMember.ReadWrite.All` is a superset of `TeamMember.Read.All`. See Microsoft Graph permissions model at https://docs.microsoft.com/en-us/graph/permissions-reference#team-member-permissions.

You can find the required permissions to call the API at https://docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&tabs=http#permissions:
> One of the following permissions is required to call this API.


`TeamMember.Read.Group` is resource-specific permission. See resource-specific consent documentation at https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent.

Given the thousands of APIs available through Microsoft Graph, customers are encouraged to first inquire the [API reference documentation](https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0) to find the right permissions they need for their scenarios.
