### ISSUE TITLE
Conceptual documentation around Authentication module

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#1411]

**Comment by maisarissi** [comment]
PR https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/70

**Comment by maisarissi** [comment]
The conceptual documentation is already available: https://docs.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0

Closing this issue.
