### ISSUE TITLE
Update get-mginformationprotectionbitlockerrecoverykey doc

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/msgraph-sdk-powershell#1414]
The following article needs to be update:
https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/get-mginformationprotectionbitlockerrecoverykey?view=graph-powershell-1.0

Please add information about using -Select and a example to use -Select Key

The most common usage for the cmdlet is...
Get-MgInformationProtectionBitlockerRecoveryKey -BitlockerRecoveryKeyId $KeyId -Select key

**Comment by peombwa** [comment]
Example has already been updated to show the use of `-Property` (-Select) - https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/get-mginformationprotectionbitlockerrecoverykey?view=graph-powershell-1.0#example-1-using-the-get-mginformationprotectionbitlockerrecoverykey-cmdlet.
