### ISSUE TITLE
Get/Set Password Expiration Policy via Graph

### ISSUE THREAD

**Issue by adhilto** [microsoftgraph/msgraph-sdk-powershell#1416]
Need to be able to programmatically check the organization's password expiration policy. Specifically referring to the policy managed in the GUI here: admin.microsoft.com -> Settings -> Org Settings ->Security & privacy -> Password expiration policy.

It seems like the only way to do this currently is with an old MSOnline commandlet, but given its imminent deprecation, this needs to be translated to graph.

**Comment by peombwa** [comment]
Thanks for following up on this.

As this repository is intended for issues related to the functionality of the SDK, we may not be the best placed to answer some queries that are tied to the functionality of the API.

Please post the question to https://developer.microsoft.com/en-us/graph/support to get an answer from the API experts/owners.

**Comment by TiloGit** [comment]
in case anyone stumbles over this ticket. 
https://learn.microsoft.com/en-au/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0#msonline-to-microsoft-graph-powershell

`Get-MsolPasswordPolicy` 	via Graph : `Get-MgDomain`
`Set-MsolPasswordPolicy` 	via Graph : `Update-MgDomain`
