### ISSUE TITLE
Connect-Graph Enhancements - Metaissue

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#142]
Related to issues: #125 ,  #123, #102, #46, #52, #113 
[AB#7439](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7439)

**Comment by tseward** [comment]
I would rename `Connect-Graph` to `Connect-MgService`. This makes a bit more sense than `Connect-MgGraph` (Connect Microsoft Graph Graph?) and `Connect-MgAccount` since we're connecting to the Microsoft Graph _service_ and not a reference to an _account_.

Plus it would be like the SPO cmdlets and hopefully would start a movement to get other services to adopt the same format :-)

**Comment by darrelmiller** [comment]
@tseward Thanks for your input.  I shopped the "service" suffix around a bit and the feedback is that the term is a bit overloaded and it conflicts with some of the other work that is going on.   There wasn't much enthusiasm for the Account suffix and there wasn't much objection to `Connect-MgGraph`.  So for the moment, we are planning to go with Connect-MgGraph and alias Connect-Graph so that we don't break existing folks.

**Comment by darrelmiller** [comment]
Parameter | Delegated | Application-Only | MSI | Plan |
-- | -- | -- | --| --|
-Scopes | X |   | |  
-TenantId | X | X |  |
-ClientId (ApplicationId) |   | X |  Alias ApplicationId |
-CertificateName |   | X |  |
-CertificateThumbprint |   | X |  |
-ForceRefresh | X | X |  |
-AccessToken | ? | ? | ?| Post V1 |
-Credential |   | ? |  Post V1 | 
-Environment | X | X | X | Post V1 |
-Identity |   |   | X| Waiting for Graph Core 2 | 
-Certificate |   | ? |  Post V1 |
-ContextName | ? | ? |  No decision | 
-UseDeviceAuthentication | ? |   |   Default in Linux, Option in Windows|

**Comment by BrianTJackett** [comment]
On my work machine I have a number of Connect-* commandlets.  Here are a few:

- Connect-AzureAD              <-- only the module prefix of "AzureAD"
- Connect-SPOService          <-- <prefix> + "Service", already mentioned above
- Connect-AzAccount           <-- <prefix + "Account", not really notion of Account in Graph
- Connect-PnPOnline            <-- <prefix> + "Online", to distinguish from on-prem SharePoint
- Connect-ExchangeOnline   <-- not the prefix nor an alias, module then uses "EXO" as prefix


Using the <prefix> + <something> seems to be the norm (at least for MSFT created modules).  I would be in favor of these:

- **Connect-Mg** with alias to Connect-Graph
- **Connect-MgGraph** with alias Connect-Graph

**Comment by ddyett** [comment]
support for interactive credential by default on windows.

**Comment by maisarissi** [comment]
Closing this since all enhancements were addressed.
