### ISSUE TITLE
Get-MgTeamworkDevice -All switch does not work

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-sdk-powershell#1423]
When running `Get-MgTeamworkDevice -All`, the output says:

`The query specified in the URI is not valid. The limit of '50' for Top query has been exceeded. The value from the incoming request in '100'.`

Adding `-Top 50` to the command in addition to `-All` only returns the top 50 devices.

**Comment by peombwa** [comment]
@joshtransient, could you please confirm if this has been addressed in [v1.11.0](https://www.powershellgallery.com/packages/Microsoft.Graph/1.11.0)? We made changes to how pagination works, and we no longer set a default page size of 100 when making requests.

Use `Update-Module Microsoft.Graph` to update to v1.11.0.

**Comment by joshtransient** [comment]
Hi @peombwa, I created this request on-the-fly during a training session with a customer and cannot confirm this myself since I don't have any teamwork devices in my lab tenant. I will reach out to the customer to confirm the fix action, but if you don't hear anything from me in a week, please close.
