### ISSUE TITLE
Permissions required to run cmdlet Get-MgDirectoryRoleMember

### ISSUE THREAD

**Issue by y5158** [microsoftgraph/msgraph-sdk-powershell#1427]
Where can I find the role or permissions required for running the cmdlet Get-MgDirectoryRoleMember
on this https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Identity.DirectoryManagement/Identity.DirectoryManagement/docs/v1.0/Get-MgDirectoryRoleMember.md   documentation? This doc should have mentioned the permissions required.

Please check.

**Comment by peombwa** [comment]
@y5158, please use `Find-MgGraphCommand -Command Get-MgDirectoryRoleMember` and the API reference docs at https://docs.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-1.0&tabs=http#permissions.

See https://docs.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-command?view=graph-powershell-1.0 for more information.
