### ISSUE TITLE
Get-MgUser -UserId [UPN] | Select Skills, PastProjects returns empty information

### ISSUE THREAD

**Issue by ThomasGDK** [microsoftgraph/msgraph-sdk-powershell#143]
I've tested to fetch Skills and PastProjects using the Get-MgUser function.
This returns empty / nothing information. (no errors)

Update-MgUser -Skills [Something] and
Update-MgUser -PastProjects [Something]
Works fine, this overwrites whatever was there before.

Using 
https://graph.microsoft.com/v1.0/users/[UPN]/?$select=displayName,skills,PastProjects returns the requested information on the Graph Explorer website:
https://developer.microsoft.com/en-us/graph/graph-explorer

Please provide any information about this, thanks :-)

/Thomas

**Comment by darrelmiller** [comment]
Unfortunately Skills, PastProjects are not returned unless you explicitly request them.  You can do this using the -select parameter

```pwsh
Get-MgUser -UserId admin@M365B870128.onmicrosoft.com -select "Skills,PastProjects"  | Select Skills, PastProjects
```
