### ISSUE TITLE
New-MgInvitation BodyParameter: Add properties to guest user at invitation time

### ISSUE THREAD

**Issue by RylandDeGregory** [microsoftgraph/msgraph-sdk-powershell#1432]
I am working on automating the sending of invitations to new guest users within our Azure AD tenant.

Following the documentation for the cmdlet [New-MgInvitation](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mginvitation?view=graph-powershell-1.0#notes), I have constructed the following PowerShell script using the `BodyParameter` parameter in an attempt to pass additional properties to the user invitation operation.

```PowerShell
$User = @{
    Email     = 'testuser@ryland.dev'
    GivenName = 'Test'
    Surname   = 'User'
}

Write-Output "Processing: $($User.Email)"
$Body = @{
    'InvitedUserEmailAddress' = $User.Email
    'InvitedUserDisplayName'  = "$($User.GivenName) $($User.Surname)"
    'InvitedUserType'         = 'Member'
    'SendInvitationMessage'   = $true
    'InviteRedirectUrl'       = 'https://ryland.dev'
    'InvitedUser' = @{
        'GivenName'     = $User.GivenName
        'Surname'       = $User.Surname
        'UsageLocation' = 'US'
        'CompanyName'   = 'Testing'
        'Department'    = 'Development'
    }
}

$NewUser = New-MgInvitation -BodyParameter $Body -Debug
```

When I execute the cmdlet, I see that all of the properties are successfully parsed as JSON in the request
![image](https://user-images.githubusercontent.com/18073815/181600778-b18a113d-286a-4e13-92a2-812a49719b34.png)

However, when I check in the Azure AD Portal I see that the properties in the top-level of the body *are* set correctly, but those within the `InvitedUser` object *are not* being set on the user.
![screenshot_2022-07-28_13-32-11](https://user-images.githubusercontent.com/18073815/181601586-4a5e1fab-a171-4627-85ac-333b3df4c5d3.png)

Am I missing something here, or constructing my body incorrectly? It seems like this should work...I've found that in other languages ([like ASP.NET](https://damienbod.com/2022/07/11/invite-external-users-to-azure-ad-using-microsoft-graph-and-asp-net-core/)), this *is* the correct body structure (a user object inside the invite object), I'm just not sure if there are any "gotchas" in the PowerShell SDK.

Any guidance or resources you are able to provide are greatly appreciated! :)

**Comment by peombwa** [comment]
Thanks for following up on this.

According to the [API reference](https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0), `invitedUser` is read-only and can't be set when creating an invite. The API should ideally fail with a 400 Bad Request error.

The invitation payload can only have the properties specified in https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0#properties.

Please open a question/feature request at https://developer.microsoft.com/en-us/graph/support to have your scenario supported.

**Comment by RylandDeGregory** [comment]
Thank you! I appreciate all the links. What would be your recommended command sequence in order to perform these actions, if it can’t be completed in 1?

**Comment by peombwa** [comment]
You'll have to use the API/command with only the supported properties since the API does not support setting an `InvitedUser` when creating an invite. You can additionally open a feature request at https://developer.microsoft.com/en-us/graph/support if setting an `InvitedUser` when creating an Invite is something you'd like to have supported by the API.

So, you request body will be:
``` powershell
$Body = @{
    'InvitedUserEmailAddress' = $User.Email
    'InvitedUserDisplayName'  = "$($User.GivenName) $($User.Surname)"
    'InvitedUserType'         = 'Member'
    'SendInvitationMessage'   = $true
    'InviteRedirectUrl'       = 'https://ryland.dev'
}

$NewUser = New-MgInvitation -BodyParameter $Body -Debug
```

**Comment by RylandDeGregory** [comment]
Thank you, Peter!

**Comment by Borgquite** [comment]
Obviously you can use New-MgInvitation, then retrieve the created user ID from the result (invitedUser.Id) and use that with Update-MgUser to change the remaining properties.
