### ISSUE TITLE
MSGraph.Autorest > Get-AzADAppCredential - Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by erwinkramer** [microsoftgraph/msgraph-sdk-powershell#1433]
Even though I'm not using the graph SDK directly, I'm posting the issue here since it's hitting an error in the graph SDK. I've hit `Object reference not set to an instance of an object.` on a script. But I have a hard time reproducing it. All runs are doing fine today. 

```
  69 |  $x.value | ForEach-Object -Parallel {
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The running command stopped because the preference variable
     | "ErrorActionPreference" or common parameter is set to Stop:
     | x > Update-X unexpected failure. With stack
     | trace error: 'at Get-AzADApplication<Process>,
     | /usr/share/az_8.1.0/Az.Resources/6.0.1/MSGraph.Autorest/internal/ProxyCmdletDefinitions.ps1: line 1065 at Get-AzADApplication<Process>, /usr/share/az_8.1.0/Az.Resources/6.0.1/MSGraph.Autorest/custom/Get-AzADApplication.ps1: line 208 at Get-AzADAppCredential<Process>, /usr/share/az_8.1.0/Az.Resources/6.0.1/MSGraph.Autorest/custom/Get-AzADAppCredential.ps1: line 103 at Get-AzADAppCredential<Process>, /usr/share/az_8.1.0/Az.Resources/6.0.1/MSGraph.Autorest/exports/ProxyCmdletDefinitions.ps1: line 1444 at Update-X, /agent/_work/3/.../platform/somescript.psm1: line 170 at <ScriptBlock>, <No file>: line 37'.

```

Line 170 in `somescript.psm1` is: ` $oldCredentials = Get-AzADAppCredential -ApplicationId $adApplicationObject.AppId | Where-Object { $_.DisplayName -eq $keyDisplayname }
`

I'm using module `Az` version `8.1.0` as you can see in the trace.

**Comment by peombwa** [comment]
@erwinkramer, please transfer the issue to right repository - https://github.com/Azure/azure-powershell/issues. `Get-AzADAppCredential` is part of the `Az` module. `MSGraph.Autorest` is just a directory name.
