### ISSUE TITLE
Missing ability to Remove-MgGroup*(etc)

### ISSUE THREAD

**Issue by jantoney** [microsoftgraph/msgraph-sdk-powershell#144]
Wondering if we're able to get Remove-MgGroup* commands. There is a * star there because there are only 3 current commands that fit the bill (IE: Remove-MgGroup is there) and I'm wondering if we're able to flesh it out please.

IE: One that would be handy is **Remove-MgGroupCalendarEvent**
Express link to check out the MgGroupCalendar* commands [HERE](https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/82f8d340febe1ed9cf17788c22c178dfad61fc56/src/Beta/Groups.Calendar/Groups.Calendar/docs)

Actually before I hit submit. On a related note, there are really only 2 Remove-MgGroup* commands, the 3rd I think is just generally buggy and might also need some love.

1. Remove-MgGroup
2. Remove-MgGroupLifecyclePolicyGroup
3. Remove-MgGroupLifecyclePolicyGroupLifecyclePolicyGroupLifecyclePolicy

Version   Name                                  
-------     ----                                  
0.2.0       Microsoft.Graph.Authentication        
0.2.1       Microsoft.Graph.Groups.Calendar       
0.2.1       Microsoft.Graph.Groups.DirectoryObject
0.2.1       Microsoft.Graph.Users.User

Keep up the good work team <3  
[AB#7440](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7440)

**Comment by peombwa** [comment]
This should have been resolved by now. Get-Command `Remove-MgGroup*` now yields 54 commands.

You can also delete an event from a group's calendar via `Remove-MgGroupEvent -GroupId $GroupId -EventId $EventId`
