### ISSUE TITLE
New-MgUserContact : were unable to deserialize

### ISSUE THREAD

**Issue by shaun-borlinghaus** [microsoftgraph/msgraph-sdk-powershell#1442]
The following code (can't get it to show as code for some reason):

`Import-Module Microsoft.Graph.PersonalContacts

Connect-MgGraph

Select-MgProfile –Name "beta"

$params = @{
	GivenName = "Given"
	Surname = "Sur"
	EmailAddresses = @(
		@{
			Address = "email@address.com"
			Name = "Given Sur"
		}
	)
	BusinessPhones = @(
		"+1 555 555 5555"
	)
}
$userId = "my@email.com"

New-MgUserContact -UserId $userId -BodyParameter $params`

fails with:

New-MgUserContact : were unable to deserialize
At line:1 char:1
+ New-MgUserContact -UserId "my@address.com" -BodyPara ...

**Comment by ddyett** [comment]
bug is resolved for PowerShell V2, need to investigate further for PowerShell V1 if a separate fix is needed.

**Comment by peombwa** [comment]
@shaun-borlinghaus, there is slight difference in how business phone numbers are set in the request body between [v1.0](https://learn.microsoft.com/en-us/graph/api/user-post-contacts?view=graph-rest-1.0&tabs=powershell#request) and [beta](https://learn.microsoft.com/en-us/graph/api/user-post-contacts?view=graph-rest-beta&tabs=powershell#request) version of the API.

What you currently have only works in v1.0 (`Select-MgProfile –Name "v1.0"`). To use the command in beta, you'll need to set business phone number in the `phones` property as shown in https://learn.microsoft.com/en-us/graph/api/user-post-contacts?view=graph-rest-beta&tabs=powershell#request.

**Comment by peombwa** [comment]
Closing as by design according to the API.

See the beta example at https://learn.microsoft.com/en-us/graph/api/user-post-contacts?view=graph-rest-beta&tabs=powershell#request for more info.
