### ISSUE TITLE
PowerShell Documentation $outFileId param doesn't exist

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/msgraph-sdk-powershell#1443]
Original issue filed here https://github.com/microsoftgraph/microsoft-graph-docs/issues/17967

> Get-MgUserTransitiveMemberOf -UserId $userId -OutFile $outFileId
> -> the parameter "OutFile" doesn't exist for the module

I see Graph Explorer renders the same snippets as docs. However, this parameter isn't documented in the [cmdlet reference](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/get-mgusermemberof?view=graph-powershell-1.0).

Kindly assist to resolve this and refresh the snippets if required.

cc @t0w0ru, @msewaweru for visibility.

**Comment by timayabi2020** [comment]
> Original issue filed here [microsoftgraph/microsoft-graph-docs#17967](https://github.com/microsoftgraph/microsoft-graph-docs/issues/17967)
> 
> > Get-MgUserTransitiveMemberOf -UserId $userId -OutFile $outFileId
> > -> the parameter "OutFile" doesn't exist for the module
> 
> I see Graph Explorer renders the same snippets as docs. However, this parameter isn't documented in the [cmdlet reference](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/get-mgusermemberof?view=graph-powershell-1.0).
> 
> Kindly assist to resolve this and refresh the snippets if required.
> 
> cc @t0w0ru, @msewaweru for visibility.

@FaithOmbongi I have also noticed that issue and raised it [here](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1135)

**Comment by timayabi2020** [comment]
@FaithOmbongi This [PR](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1135) provided a solution to this issue. I have confirmed from [docs](https://docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=powershell) that the outfile parameter is only included where it is required. Please confirm too

**Comment by FaithOmbongi** [comment]
Thank you @timayabi2020 for the feedback. Glad this is resolved.
