### ISSUE TITLE
Get-MgReportOffice365ActivationUserDetail : Expected '{' or '['. Was String: Report.

### ISSUE THREAD

**Issue by mjgerena** [microsoftgraph/msgraph-sdk-powershell#1447]
Trying to get reports for MgReportOffice365ActivationUserDetail  and getting the following error Get-MgReportOffice365ActivationUserDetail : Expected '{' or '['. Was String: Report.

**Comment by peombwa** [comment]
Please update your SDK to the latest version - https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.11.0 (`Update-Module Microsoft.Graph`).

The command works as expected using the latest version of the module.

**Comment by mjgerena** [comment]
I am still getting the same error

Update-Module Microsoft.Graph

PS C:\Windows\system32> Get-MgReportOffice365ActivationUserDetail -OutFile D:\Export\LicensingReport\Dev-MgReportOffice365ActivationUserDetail.csv
Get-MgReportOffice365ActivationUserDetail : Expected '{' or '['. Was String: Report.
At line:1 char:1
+ Get-MgReportOffice365ActivationUserDetail -OutFile D:\Export\Licensin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgReportOff...nUserDetail_Get], ParserException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgReportOffice365ActivationUserDetail_Get





________________________________



DISCLAIMER & CONFIDENTIALITY NOTICE: This email neither constitutes an agreement to conduct transactions by electronic means nor creates any legally binding contract or enforceable obligation in the absence of a fully signed written contract. The information contained in this email and any attachments may be confidential, legally privileged and/or exempt from disclosure under applicable law. It has been sent for the sole use of the intended recipient(s). If the reader of this message is not an intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any unauthorized review, use, disclosure, dissemination, distribution, or copying of this communication, or any of its contents, is strictly prohibited. Any inadvertent or accidental disclosure of confidential, legally privileged and/or exempt information contained in this email does not constitute a knowing waiver of any rights regarding such information or materials. If you have received this communication in error, please reply to the sender and destroy all copies of the message (including any attachments).
