### ISSUE TITLE
Get-MgApplication : One or more parameters of the function import 'getByIds' are missing from the request payload. The missing parameters are: ids.

### ISSUE THREAD

**Issue by Donovand4** [microsoftgraph/msgraph-sdk-powershell#145]
Get-MgApplication | Select-Object DisplayName, Appid, WebRedirectUris
Get-MgApplication : One or more parameters of the function import 'getByIds' are missing from the request payload. The missing parameters are: ids.

ID's are not accepted as well.

**Comment by darrelmiller** [comment]
Thanks for reporting, we will investigate.
