### ISSUE TITLE
Retrieving the Status Code & Response Header without -Debug

### ISSUE THREAD

**Issue by potluri96** [microsoftgraph/msgraph-sdk-powershell#1452]
Hello,

How do I get the status code and response header when invoking "Invoke-MgGraphRequest" without -Debug

Invoke-MgGraphRequest

**Comment by peombwa** [comment]
@potluri96, you can use `-ResponseHeadersVariable ResponseHeader`. See `Get-Help Invoke-MgGraphRequest -Parameter ResponseHeadersVariable`.

**Comment by Mike-Crowley** [comment]
BTW, this parameter seems to populate only if the connection is successful, making it pretty useless. 

For example, if I do two calls, one that works and one that doesn't, and and send the status code to a $statusCode variable, the second (failed) call will not return a status, so the variable will remain '200'.
