### ISSUE TITLE
New-MgApplicationOwnerByRef not functional in PowerShell Core

### ISSUE THREAD

**Issue by TahaBenseddik** [microsoftgraph/msgraph-sdk-powershell#1456]
While writing/testing an Powershell script to run through a pipeline powershell task I noticed that New-MgApplicationOwnerByRef doesn't work with the specified parameters. It does however work with version 1.10.0 of the Microsoft.Graph module, but not with 1.11.0

    $params = @{
        "@odata.id" = "https://graph.microsoft.com/v1.0/directoryObjects/$ownerObjectId"
    }
    
    New-MgApplicationOwnerByRef -ApplicationId $appobjectId -BodyParameter $params

...throws: A parameter cannot be found that matches parameter name 'BodyParameter'

when I run the get-help New-MgApplicationOwnerByRef

output is: 

SYNTAX
    New-MgApplicationOwnerByRef -ApplicationId <String> [-Break] [-HttpPipelineAppend <SendAsyncStep[]>]
    [-HttpPipelinePrepend <SendAsyncStep[]>] [-PassThru] [-Proxy <Uri>] [-ProxyCredential <PSCredential>]
    [-ProxyUseDefaultCredentials] [-WhatIf] [-Confirm] [<CommonParameters>]

    New-MgApplicationOwnerByRef -InputObject <IApplicationsIdentity> [-Break] [-HttpPipelineAppend <SendAsyncStep[]>]
    [-HttpPipelinePrepend <SendAsyncStep[]>] [-PassThru] [-Proxy <Uri>] [-ProxyCredential <PSCredential>]
    [-ProxyUseDefaultCredentials] [-WhatIf] [-Confirm] [<CommonParameters>]

As you can see the 'BodyParameter' is missing here....

According to the Microsoft Documentation this parameter should be usable with this command:

https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.applications/new-mgapplicationownerbyref?view=graph-powershell-1.0

**Comment by peombwa** [comment]
Sorry about this, and thanks for surfacing the error with us. We've released a patch that fixes the issues at https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.11.1.

Please upgrade to the latest version of the module (`1.11.1`) using `Update-Module Microsoft.Graph`. Let me know if the patch addresses the issue on your end.

Related to #1440.

**Comment by TahaBenseddik** [comment]
Thank you. It is working again after updating to version 1.11.1
