### ISSUE TITLE
Get-MgUser first example is wrong

### ISSUE THREAD

**Issue by robinmalik** [microsoftgraph/msgraph-sdk-powershell#1469]
**Problem:**

[Example 1: Get the list of all the users](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/get-mguser?view=graph-powershell-1.0#example-1-get-the-list-of-all-the-users)
This command returns a list of all users.

The command is `Get-MgUser  | Format-List  ID, DisplayName, Mail, UserPrincipalName` and this does not get all users. 

**Solution?**

Update the example command to include `-All` or insert some information and/or a link to how to page.

**Comment by robinmalik** [comment]
Example 3 also has this problem: "The example gets a list of all users."

**Comment by timayabi2020** [comment]
@msewaweru kindly share insights on this request

**Comment by msewaweru** [comment]
@robinmalik , thanks for highlighting this issue. You are right. I will add the -all parameter to correct that. Thanks.

<html>
<body>


ID | Work Item Type | Title | Assigned To | State | Tags
-- | -- | -- | -- | -- | --
2076145 | Product Backlog Item | GitHub issue: Get-Mguser first example correction. | Eunice Waweru | New |  


</body>
</html>
