### ISSUE TITLE
New-MgGroupMemberByRef and New-MgGroupOwnerByRef Issues

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#1471]
Based on our documentation, we should be using the -BodyParameter param to specify the user to add to a group, however this parameter doesn't exist on the cmdlet. How can we add members and owners to groups using the -InputObject parameter instead?

https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.groups/new-mggroupownerbyref?view=graph-powershell-1.0

**Comment by peombwa** [comment]
Sorry about this, and thanks for surfacing the error with us. We've just released a patch that fixes the issues at https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.11.1.

Please upgrade to the latest version of the module (`1.11.1`) using `Update-Module Microsoft.Graph`. Let me know if the patch addresses the issue on your end.

Related to #1440.

**Comment by peombwa** [comment]
Fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.11.1.
