### ISSUE TITLE
Help using the SDK for reporting.

### ISSUE THREAD

**Issue by AdeptNorth** [microsoftgraph/msgraph-sdk-powershell#1476]
I'm looking for a way to access the usage report data in Office 365 through the SDK. Such as if a user has a a license assigned , the last time they used a feature (Sharepoint,exchange,teams etc).

I can see there's some functionlity using the Graph API but have no clue how to use it - I've been creating powershell scripts I can run using the SDK to pull what I need off for our tenants. Any advice on this would be great - not sure if it's even available currently.

**Comment by mmascolino** [comment]
`Get-MgReportOffice365ActiveUserDetail` will let you get detailed user data per user for all users in your tenant including licensing and latest usage date on a per vertical basis (i.e. Exchange or SharePoint or Teams or xxxx).

AFAIK, there is no other way for you to get this type of last feature usage date on a per user basis save for running crazy Audit Log Queries which I wouldn't recommend you attempt.

**Comment by ddyett** [comment]
Please leverage the support page here for assistance.

https://developer.microsoft.com/en-us/graph/support
