### ISSUE TITLE
Get-MgDirectory Not Functional

### ISSUE THREAD

**Issue by Snozzberries** [microsoftgraph/msgraph-sdk-powershell#1477]
The Get-MgDirectory cmdlet does not appear fully implemented in v1.10

![image](https://user-images.githubusercontent.com/431932/186455458-f3ff66a0-d677-4c25-a503-814dacb2bd77.png)

**Comment by timayabi2020** [comment]
Hi @Snozzberries ,
Thanks for noticing and raising this issue, however this error message originates from the service and not the sdk. Kindly open a question [here](https://developer.microsoft.com/en-us/graph/support) and the API owners will respond. You can follow the troubleshooting guide on [this](https://docs.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) to find the necessary request Id
