### ISSUE TITLE
Get-MgUser not returning EmployeeId

### ISSUE THREAD

**Issue by tomdan-MSFT** [microsoftgraph/msgraph-sdk-powershell#1478]
Working with a client we noticed the Get-MgUser does not return the EmployeeId attribute correctly.  It always shows blank data in the output :

![image](https://user-images.githubusercontent.com/56908729/186554089-a557bc71-feb9-4be5-bd3c-248ed762608e.png)

Using the older AAD PS cmdlets it will properly return the employee ID :

![image](https://user-images.githubusercontent.com/56908729/186554195-43cf9a34-8b73-4812-98ad-3004ee2113cd.png)

From another thread I tried setting the MgProfile to beta and it actually fixes the issue :

![image](https://user-images.githubusercontent.com/56908729/186555482-86be349a-5804-4e78-b089-e54073dcc69d.png)

Can we get this fixed without having to load the beta profile?  At least having this documented in the Get-MgUser section would be very helpful.

**Comment by timayabi2020** [comment]
Hi @tomdan-MSFT,
Thanks for identifying and raising this issue, however when I test on my end I get employee Id on both old and latest AAD PS cmdlets.
Please confirm again from your tenant if the requested user has the employee Id property set to a value. 
Also confirm the sdk version that you are using by running this command ```Get-Module -Name Microsoft.Graph -ListAvailable```



![Image](https://user-images.githubusercontent.com/10947120/190379922-4612f348-7e51-4e1f-a380-1b297e1b1848.png)





![Image](https://user-images.githubusercontent.com/10947120/190380080-5820b030-f1e7-4690-a42e-d06236cd7d2e.png)

**Comment by lewisevelyn** [comment]
I have the same issue

![image](https://user-images.githubusercontent.com/91122289/194392528-2aab0240-8d91-42b5-b9ba-db5f59797a8e.png)
![image](https://user-images.githubusercontent.com/91122289/194393415-a868f5a1-8d78-469d-8422-cce851fa70fb.png)

**Comment by ryeguy637** [comment]
I have the same issue.  EmployeeID appears blank from module microsoft.graph.users 1.10.0.  It is not blank when viewed form portal.azure.com console.

![image](https://user-images.githubusercontent.com/37934378/195135930-eddd310c-e9e9-417c-8342-420997418cdc.png)

**Comment by lewisevelyn** [comment]
I managed to resolve the issue by using Select-mgprofile beta, running the get-MgUser command then swapping back to v1.0.

Hope this helps!
________________________________

**Comment by MrV8Rumble** [comment]
This is still occurring on current modules. Changing to the beta profile allows it to pull the information correctly. Can this be looked into? You shouldn't have to go backwards for this.

**Comment by worldsdream** [comment]
Confirmed that this is still not working. Please fix this.

**Comment by toddalbers** [comment]
Still not working.  Please fix.

**Comment by toddalbers** [comment]
Found the solution to "Employee ID" not being returned from Get-MgUser.

(1) First, when you connect to MSGraph, include scope of "User.Read.All"

-      Example:        Connect-MgGraph -Scopes "User.Read.All"

(2) Then when you call Get-MgUser make sure you include -All parameter.

-      Example:         Get-MgUser -All

**Comment by olaimonas** [comment]
I have the same issue. Is there any update on this?

**Comment by olaimonas** [comment]
I found a solution after reading [Microsoft Graph REST API v1.0 documentation](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http):

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/25246410/29aeb2bd-cfc6-4735-a498-e87364d7a654)

$user1 = Get-MgUser -Filter "DisplayName eq 'Alex Wilber'"
$user1.EmployeeId
$select = "DisplayName, GivenName, PostalCode, Identities, EmployeeId"
$user = Get-MgUser -Filter "DisplayName eq 'Adele Vance'" -Property $select
$user.EmployeeId
1

According to the documentation, specific properties should be selected explicitly, and looks like EmployeeId is one of them. Interestingly, it won't be retrieved if an asterisk is used:
Get-MgUser -Filter "DisplayName eq 'Adele Vance'" -Property *
$user2.EmployeeId
returns nothing.
