### ISSUE TITLE
Get-MgIdentityConditionalAccessPolicy - possible with Application instead of Delegated?

### ISSUE THREAD

**Issue by plk** [microsoftgraph/msgraph-sdk-powershell#1479]
With the following (admin consented) permissions:

```
Application.Read.All
Policy.Read.All
Policy.ReadWrite.ConditionalAccess
```

An app (using certificate auth) can connect to MsGraph using `Connect-MsGraph` but when running:

```
Get-MgIdentityConditionalAccessPolicy
```

I get the error:

"Applications without a signed-in user are not allowed to access this report or data."

Does this mean only the Delegated model is supported here?

**Comment by plk** [comment]
Ah, works with Powershell 5, not 7. Is there any chance this will be fixed so it works with PS 7?

**Comment by timayabi2020** [comment]
Hi @plk ,
The error message originates from the service and not the sdk. Kindly open a question [here](https://developer.microsoft.com/en-us/graph/support) and the API owners will respond. You can follow the troubleshooting guide on [this](https://docs.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) to find the necessary request Id
See related [issue](https://github.com/microsoft/Microsoft365DSC/issues/1800).
