### ISSUE TITLE
Add support for -Credential for Connect-Graph for user ROPC Grant flow

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/msgraph-sdk-powershell#148]
This may be something that was purposefully left out for conscious security reasons, but is here any plan to support a `-Credential` parameter to `Connect-Graph` to pass an Azure AD user credential to support non-interactive scenarios (in what would likely be a Resource Owner Password Credential (ROPC) Grant flow under the covers)?

I ask only because, there are certain things that can only be automated against the Graph with delegated permissions, and if this is trying to be done in an unattended fashion it often still necessitates the use of an Azure AD user credential (typically a standalone "service account" user that's been granted the proper permissions within the resource). In the absence of this option, we wind up building our own helper functions as wrappers around `Invoke-RestMethod` to get access_tokens and call the graph for these use cases.

I know for the `AzureAD` PS module we can supply a `-Credential` parameter and assuming the account is not subject to MFA by conditional access policies it will go through.

If ROPC flow won't be integrated into `Connect-Graph` in this way, an alternative may be to provide an `-AccessToken` parameter so that we can supply an access_token which we've called to the token endpoint to retrieve with `Invoke-RestMethod` already and use.

Thanks for working on this great module! I'm excited about it.

**Comment by darrelmiller** [comment]
I created a task to track our plans for Connect-Graph here #124 .  I do think we can justify adding a -Accesstoken parameter, however, I don't believe adding ROPC grant is in our future.  We are also actively working to encourage all teams to support app-only as well as delegated permissions.

**Comment by ryanspletzer** [comment]
@darrelmiller I think this can be closed since we have the `-AccessToken` param now? So can do ROPC flow on the outside of the module.

**Comment by peombwa** [comment]
Closing since `-AccessToken` is now available.
