### ISSUE TITLE
Change the app registration to "Microsoft Graph Command Line Tools"

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-powershell#1481]
We should rename the app registration to just Microsoft Graph Command Line Tools as we will use the same app for both PowerShell and CLI so we can give users single sign-on when using both SDKs.

**Comment by ddyett** [comment]
will need to interweave this with Torus changes as well.

**Comment by maisarissi** [comment]
We are still not sure if PowerShell app will move to Torus per my understanding, as the Torus might not be the path to get the publish verified. @ddyett 
Can we just rename the application for now? @peombwa @timayabi2020

**Comment by ddyett** [comment]
@MIchaelMainer developer a plan for migration in azure.  this work should be factored into that plan.

**Comment by peombwa** [comment]
Name change happened on `05/01/2023`. See https://devblogs.microsoft.com/microsoft365dev/new-azure-ad-app-name-for-microsoft-graph-powershell-sdk-and-cli for more details.
