### ISSUE TITLE
Get-MgEntitlementManagementCatalog fails with error "User is not authorized to perform the operation. Reason: Unauthorized"

### ISSUE THREAD

**Issue by vlijmenfileer** [microsoftgraph/msgraph-sdk-powershell#1482]
Hi, I try:
"Get-MgEntitlementManagementCatalog" and get an error:
"User is not authorized to perform the operation. Reason: Unauthorized".

Graph version v1.0.  As far as I have been able to find, it should work with scope `EntitlementManagement.ReadWrite.All` alone already, which my test user has.  For this reason I am filing this as an issue.

Perhaps of interest: I am connected to a test tenant created from my main Pay-as-you-Go tenant, and I have activated the P2 trial license in that test tenant.

```
PS <HIDDEN>> (Get-MgContext).Scopes
Directory.AccessAsUser.All
Directory.ReadWrite.All
EntitlementManagement.ReadWrite.All
openid
profile
User.Read
User.ReadWrite.All
email
PS <HIDDEN>> Get-MgEntitlementManagementCatalog
Get-MgEntitlementManagementCatalog_List: C:\Program Files\PowerShell\Modules\Microsoft.Graph.Identity.Governance\1.11.0\custom\Get-MgEntitlementManagementCatalog.ps1:159:5
Line |
 159 |      Microsoft.Graph.Identity.Governance.private\Get-MgEntitlementMana …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | User is not authorized to perform the operation. Reason: Unauthorized
```

**Comment by timayabi2020** [comment]
Hi, @vlijmenfileer.
Kindly confirm the sdk version you are using.

**Comment by vlijmenfileer** [comment]
Hi @timayabi2020 .
That would be v1.0.

**Comment by timayabi2020** [comment]
Hi @vlijmenfileer 
Kindly run this command and share the output. 
```Get-Module -Name Microsoft.Graph -ListAvailable```
