### ISSUE TITLE
Specifying old versions of Graph SDK PS not respected with dependencies

### ISSUE THREAD

**Issue by anpiskai** [microsoftgraph/msgraph-sdk-powershell#1483]
We ran into some issues with some code that relied on an older version of the Microsoft Graph SDK PowerShell (1.10.0) when trying to specify a non-current version of the module. We've been able to reproduce on a clean Azure VM, but the behavior is as follows.

When we install a sub-module (like Microsoft.Graph.Users), it automatically also installs the most current version of the Microsoft.Graph.Authentication module.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/48796638/187735127-75b8ab4e-0f3c-484a-98e4-875b133a64bf.png">

Similarly, when we try to install the Microsoft.Graph.Authentication module for the old version ahead of time, we still end up in a scenario where the more current version gets installed as well.
<img width="808" alt="image" src="https://user-images.githubusercontent.com/48796638/187735345-92a556b4-1562-444a-909d-cd6f578f5456.png">
<img width="806" alt="image" src="https://user-images.githubusercontent.com/48796638/187735399-e3980e85-262c-49dc-95f1-eefddc8d8fbd.png">

Unfortunately, due to the mismatched module versions this introduces, any of the old submodule MG commands fail because the version mismatches. 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/48796638/187735573-014a1364-0665-4fdb-ba1a-30e11b67c4a5.png">

The ask here would be that if a specific version is specified, that it is respected by what is actually installed so that version compatibility works. In other words, if I install 1.10.0 for Microsoft.Graph.Users, it should install Microsoft.Graph.Authentication for 1.10.0 as well.

**Comment by timayabi2020** [comment]
Duplicate [issue](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/591). We are working on a fix in upcoming versions.
