### ISSUE TITLE
How Microsoft Graph loads the sub modules?

### ISSUE THREAD

**Issue by Petri-X** [microsoftgraph/msgraph-sdk-powershell#1487]
Hi,
I have tried to understand why the Azure PS module is unable to load the sub modules which it is requires. I have stored them into same way I have done for Microsoft Graph. The Graph PS loads all modules successfully, but Azure just fails to find required modules.

Because Microsoft Graph works so well, I wonder that something has done well on here. That was the reason I though to come and ask from here :)

The folder structure for Microsoft Graph is following:
```
 Directory of C:\Program Files\WindowsPowerShell\Modules\MicrosoftGraph

15.08.2022  14.07    <DIR>          .
15.08.2022  14.07    <DIR>          ..
15.08.2022  14.07    <DIR>          Microsoft.Graph
15.08.2022  14.07    <DIR>          Microsoft.Graph.Applications
15.08.2022  14.07    <DIR>          Microsoft.Graph.Authentication
15.08.2022  14.07    <DIR>          Microsoft.Graph.Bookings
15.08.2022  14.07    <DIR>          Microsoft.Graph.Calendar
. . .
. .
.
```

And for AZ it looks identical:
```
 Directory of C:\Program Files\WindowsPowerShell\Modules\AZ

15.08.2022  14.04    <DIR>          .
15.08.2022  14.04    <DIR>          ..
12.08.2022  16.19    <DIR>          Az
12.08.2022  16.19    <DIR>          Az.Accounts
12.08.2022  16.19    <DIR>          Az.Advisor
12.08.2022  16.19    <DIR>          Az.Aks
12.08.2022  16.19    <DIR>          Az.AnalysisServices
. . .
. .
.
```

Could it be so that I have done something for Graph and that is cached into somewhere and is working well because of that? Or could there be something else?

I'm not sure if you were able to follow my mind flow, but wish to hear if you knows something more about this.

**Comment by peombwa** [comment]
@Petri-X, I'd recommend you open an issue at https://github.com/Azure/azure-powershell/issues for the Azure SDK team to investigate why the sub modules are not loading for you.

For Microsoft Graph PowerShell, we let PowerShell handle installing and loading our submodules by specifying them as `RequiredModules` in the main module manifest (Microsoft.Graph). See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_module_manifests?view=powershell-7.2#requiredmodules.

**Comment by Petri-X** [comment]
Eh...? You really believe I haven't asked that from there? :) 
Yes, I have and as the answer from there was very hard to get, I though to come here to ask as someone on Graph side should know it.

But surprising surprising, it seems to be one of the greatest secrets.

Need to learn more from Powershell fundamentals.


"_If you have knowledge, let others light their candles at it._"
-Margaret Fuller.
