### ISSUE TITLE
Update-MsIdGroupWritebackConfiguration failed with not enough permissions

### ISSUE THREAD

**Issue by ErisMeiyang** [microsoftgraph/msgraph-sdk-powershell#1489]
Executed below command and failed with error:
Get-mggroup -filter "groupTypes/any(c:c eq 'Unified')" | Update-MsIdGroupWritebackConfiguration -WriteBackEnabled $false

Update-MsIdGroupWritebackConfiguration : Additional scope needed, call Connect-MgGraph with one of the following scopes: Directory.ReadWrite.All, Group.ReadWrite.All
At line:260 char:58
+ ... nified')" | Update-MsIdGroupWritebackConfiguration -WriteBackEnabled  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Update-MsIdGroupWritebackConfiguration

However, get-mgcontext shows the permission has been assigned as scope:

Get-MgContext

ClientId              : 14d82eec-204b-4c2f-b7e8-296a70dab67e
TenantId              : 4cd0900a-acc2-47f2-b5af-15f4d9d4e06d
CertificateThumbprint : 
Scopes                : {Directory.ReadWrite.All, Group.ReadWrite.All, openid, profile...}
AuthType              : Delegated
AuthProviderType      : InteractiveAuthenticationProvider
CertificateName       : 
Account               : Eris@jsecury.onmicrosoft.com
AppName               : Microsoft Graph PowerShell
ContextScope          : CurrentUser
Certificate           : 
PSHostVersion         : 5.1.22000.832
ClientTimeout         : 00:05:00

**Comment by peombwa** [comment]
From the provided log, `FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Update-MsIdGroupWritebackConfiguration`, the error is coming from `Update-MsIdGroupWritebackConfiguration`.

Unfortunately, `Update-MsIdGroupWritebackConfiguration` is not a command provided by this module and there is little we can do to help resolve the error. Please contact the author command for assistance with the error at https://github.com/AzureAD/MSIdentityTools/issues.
