### ISSUE TITLE
List All Rooms using PowerShell SDK

### ISSUE THREAD

**Issue by TREYNOL1** [microsoftgraph/msgraph-sdk-powershell#1491]
Please update the PowerShell SDK to allow the ability to List all the rooms defined in the tenant.

**Comment by timayabi2020** [comment]
Thanks @TREYNOL1, this has been noted and we will work towards having this feature in a future release. Meanwhile you can try getting those rooms by using the below command

```Invoke-MgGraphRequest -OutputType Json -Uri "https://graph.microsoft.com/v1.0/places/microsoft.graph.room"```

**Comment by ddyett** [comment]
duplicate #423
