### ISSUE TITLE
Setting TwoWayPhone Authentication for AzureAD User MFA

### ISSUE THREAD

**Issue by ITpro789** [microsoftgraph/msgraph-sdk-powershell#1495]
Hi,

Currently the only way I know how to set MFA twowayphone authentication for users via powershell is using set-msol (below), I do not see this functionality in PowerShell SDK MSGraph?

$TwoWayVoiceMobile = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationMethod
$TwoWayVoiceMobile.IsDefault = $true
$TwoWayVoiceMobile.MethodType = "TwoWayVoiceMobile"
Set-MsolUser -UserPrincipalName $dwpEmail -StrongAuthenticationMethods $methods

**Comment by peombwa** [comment]
@ITpro789, you can find all the Microsoft Graph supported properties of phone authentication method at https://docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-1.0. Please note that with Microsoft Graph, a phone can be used by a user to authenticate using [SMS or voice calls](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-methods#phone-options) as allowed by policy. See https://docs.microsoft.com/en-us/graph/authenticationmethods-get-started for more details.

It's worth noting that [changing the default authentication method](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0#what-authentication-methods-can-be-managed-in-microsoft-graph) is currently not supported in Microsoft Graph. Please upvote on this [existing feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/include-support-for-viewing-and-changing-the-default/idi-p/3064015) for it be added by the workload owner.

**Comment by mortenlerudjordet** [comment]
> @ITpro789, you can find all the Microsoft Graph supported properties of phone authentication method at https://docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-1.0. Please note that with Microsoft Graph, a phone can be used by a user to authenticate using [SMS or voice calls](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-methods#phone-options) as allowed by policy. See https://docs.microsoft.com/en-us/graph/authenticationmethods-get-started for more details.
> 
> It's worth noting that [changing the default authentication method](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0#what-authentication-methods-can-be-managed-in-microsoft-graph) is currently not supported in Microsoft Graph. Please upvote on this [existing feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/include-support-for-viewing-and-changing-the-default/idi-p/3064015) for it be added by the workload owner.

This is an important feature and hope MS adds this to Graph before retiring MSOnline / AAD Graph
