### ISSUE TITLE
Get-MgUser not returning Initials

### ISSUE THREAD

**Issue by weyCC81** [microsoftgraph/msgraph-sdk-powershell#1500]
Working with a client we noticed the Get-MgUser does not return the Initials attribute correctly. 
It always shows blank data in the output :
`Connect-MgGraph -Scopes User.ReadWrite.All`
`Select-MgProfile -Name "beta"`
`Get-MgUser -UserId {userid} -Property * | fl Profile`

> Profile : Microsoft.Graph.PowerShell.Models.MicrosoftGraphProfile

`(Get-MgUser -UserId {userid} -Property *).Profile`

> Names : 

`(Get-MgUser -UserId {userid} -Property *).Profile.Names`

> (Nothing is returend here!)

The expected behavior would be to give back multiple values from the object names set on the user (tested over graph explorer):
GET https://graph.microsoft.com/beta/users/{userid}/profile/names?$select=displayName,Initials

![image](https://user-images.githubusercontent.com/26062079/189714876-34d2643c-19d8-4487-aa0c-6df368012e8b.png)

Initials can be synced by AD Connect: https://docs.microsoft.com/de-de/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized

References:
- https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1478
- https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/retrieve-middlename-and-initials-attributes-from-azure-ad-graph/idi-p/3255482
- https://stackoverflow.com/questions/54292487/microsoft-graph-api-initials-attribute

**Comment by peombwa** [comment]
@weyCC81, the command you are looking for is [Get-MgUserProfileName](https://docs.microsoft.com/en-us/graph/api/profile-list-names?view=graph-rest-beta&tabs=powershell#examples). `Get-MgUser` calls `GET https://graph.microsoft.com/beta/users/{userid}`.

Please note that you can also use the snippets tab in Graph Explorer to find the command that corresponds to API you are calling:
![image](https://user-images.githubusercontent.com/7061532/190284324-2be13c1f-e64f-44d9-8d19-e7993fc00ee0.png)

**Comment by weyCC81** [comment]
Hi @peombwa 

I would like to request the ObjectID from the Initials and not the otherway around, is that not possible?
```
(Get-MgUserProfile -UserID [ObjectID] -Property *).Names | fl *
(Get-MgUserProfile -UserID [ObjectID] -Property *).Names.Initials
```

For 39 objects it takes around 21 seconds, this would mean 8-9minutes for 1000 objects:
```
Measure-Command { 
    (Get-MgUser | %{Get-MgUserProfile -UserID $_.Id} ).Names.DisplayName
}
```

**Comment by peombwa** [comment]
@weyCC81, `Names` is a relationship (containment navigation property) of a profile. Navigation property can only be called via an API path. Please see the [API reference](https://docs.microsoft.com/en-us/graph/api/resources/profile?view=graph-rest-beta#relationships) for more details.

Yes, you should use the commands in the same way you would make the REST API call. This module is just a pass through to the service. The command names follow the API path. This is described in https://docs.microsoft.com/en-us/powershell/microsoftgraph/navigating?toc=%2Fgraph%2Ftoc.json&view=graph-powershell-1.0#command-naming-conventions.

You can also open a feature request at https://developer.microsoft.com/en-us/graph/support for the workload owners to add missing API functionality to cover your scenario.

**Comment by weyCC81** [comment]
Nice, thanks for this explanation so this is a limit of the current API. Thank you!

**Comment by peombwa** [comment]
That's right! You are welcome.
