### ISSUE TITLE
New-MgApplication error when passing Oauth2RequirePostResponse parameter

### ISSUE THREAD

**Issue by JamieH-risual** [microsoftgraph/msgraph-sdk-powershell#1502]
When creating a new AAD app it fails when the Oauth2RequirePostResponse parameter is passed with the error: 

Resource '' does not exist or one of its queried reference-property objects are not present.

### Command executed
```powershell
New-MgApplication -DisplayName "P2P Server" -IdentifierUris @('urn:p2p_cert') -Oauth2RequirePostResponse:$False -SignInAudience 'AzureADMyOrg' -Verbose
```

This is impacting the usage of the Microsoft365DSC module as it is configured as a required parameter. 

[https://github.com/microsoft/Microsoft365DSC/issues/2276](url)

**Comment by andikrueger** [comment]
Same applies for the Update-MgApplication cmdLet.

**Comment by peombwa** [comment]
Thanks for following up on this.

According to the [service metadata](https://graph.microsoft.com/v1.0/$metadata), `Oauth2RequirePostResponse` is a valid property of an application resource:
![image](https://user-images.githubusercontent.com/7061532/190466808-cc7cc23d-b9e2-4f32-85d7-bea121ecd3d6.png)

Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support for the API owner to investigate why you are getting that error when setting the property. I'll also follow up with workload owner to understand why this is failing.
