### ISSUE TITLE
Connect-MgGraph - Object reference not set to an instance of an object. when using -ClientId

### ISSUE THREAD

**Issue by BigMcPatty** [microsoftgraph/msgraph-sdk-powershell#1504]
I'm attempting to authentication using the clinetId for my app registration. 

My command for the connection is 
`Connect-MgGraph -Scopes "User.Read","Group.Read.All" -ClientId "$ClientId" -TenantId "$TenantId"`

Everything starts as expected my browser opens and I authenticate with my account but then I receive an error in my terminal. 
`Connect-MgGraph: Object reference not set to an instance of an object.`

I'm not sure if I'm missing some required parameter. Or a setting in my app registration? 
When I run the command with using only the -TenantId and -Scopes parameters it works as expected but using the generic Graph app.

**Comment by peombwa** [comment]
I'm not able to repo this on my end using the latest version of the module (1.11.1):
![image](https://user-images.githubusercontent.com/7061532/190469591-8cf1a71a-deef-4fa0-b198-661a5cd26324.png)

Please share the out of the following for us to try repro this behavior:
- `Get-Module Microsoft.Graph.Authentication`
- `$PSVersionTable`
- Detailed repro steps. e.g., what steps did you do before invoking `Connect-MgGraph`.

Also, could you go through the steps at https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues to clear you token cache to see if this helps.

**Comment by p-zim** [comment]
I have the exact same issue. Also removing and installing Microsoft.Graph did not help.

![image](https://user-images.githubusercontent.com/61678937/191681046-5aea7dc5-0bab-41c5-978b-dcdd9db64d2c.png)
