### ISSUE TITLE
functions in Microsoft.Graph.Reports don't format parameters properly

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#151]
![image](https://user-images.githubusercontent.com/447694/77193736-190b0980-6ab5-11ea-93ed-83a487f1493a.png)
The D7 value needs to be quoted for it to work.

e.g. 
https://graph.microsoft.com/beta/reports/microsoft.graph.getTeamsUserActivityCounts(period='D7')

**Comment by irvinesunday** [comment]
Is this only an issue in `Microsoft.Graph.Reports`? I see similar instances elsewhere, e.g. 

/users({id})/microsoft.graph.reminderView(StartDateTime={StartDateTime},EndDateTime={EndDateTime})' 

and 

/workbooks({id})/microsoft.graph.delta(token={token})'
