### ISSUE TITLE
JWT token failed signature validation

### ISSUE THREAD

**Issue by Brijeshoo7** [microsoftgraph/msgraph-sdk-powershell#1519]
Hi,

when i try to run command connect-mggraph and login with my global admin account which has no MFA enabled it gives me below error.

![image](https://user-images.githubusercontent.com/88958817/190622677-3db5de14-bd64-4f0b-bdea-709e0063b6b6.png)

Please share on thoughts on this and let me know if i am missing something in azure tenant to check.

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/190627990-859edc26-813a-49fc-99dd-f6ea988cde3b.png)

Same thing happens when i try to run : Update-M365DSCAllowedGraphScopes -All -Type 'Update' -Environment 'Global'.

**Comment by peombwa** [comment]
@Brijeshoo7, which environment/national cloud are you trying to sign in to? The error message can occur when you try to use different national cloud account to sign into the global environment/national cloud.

Please share the following details for us to help you:
- The environment/cloud are you connecting to? See MS Graph supported clouds at https://docs.microsoft.com/en-us/graph/deployments#microsoft-graph-and-graph-explorer-service-root-endpoints.
- The version of the imported module. `Get-Module Microsoft.Graph.Authentication`.
- Steps taken during the sign in process. e.g., Did a browser/window pop-up? At what point in the authentication process does the error appear?

**Comment by Brijeshoo7** [comment]
@peombwa thanks for your reply. I have tried with the .US domain user too if there is GCC issue as you mentioned but facing the same issue.

can you give me the proper steps to check everything one by one in tenant if I am missing out at some point.

thanks.

**Comment by Brijeshoo7** [comment]
@peombwa thanks very much. based on the link you have provided i have found solution. closing this issue now.

Connect-MgGraph -Environment USGov

it was US gov tenant so needed to add this things i wasn't aware of.
