### ISSUE TITLE
Get-MgUser -All: A parameter cannot be found that matches parameter name 'All'

### ISSUE THREAD

**Issue by GnXeyTfY7zBWhzUw** [microsoftgraph/msgraph-sdk-powershell#1527]
v1.12.0 does not have parameters for -All or -PageSize.

v1.11.0 does.

I cannot locate a parameter in v1.12.0 that allows query of all users.

**Comment by MikeRhg** [comment]
Same for **Get-MgSubscribedSku** and **Get-MgGroupMemberWithLicenseError**

**Comment by swalker1988** [comment]
Confirming same issue for Get-MgGroupMember.

**Comment by dsolodow** [comment]
Get-MgUser only has a -Filter for the v1.0 content not beta with 1.12; 1.11.1 was fine.

**Comment by peombwa** [comment]
Sorry for the unintentional change.

We've traced the issue back to OpenAPI document that was used to generate the module. See tracking issue https://github.com/microsoft/OpenAPI.NET.OData/issues/282.

We will issue a patch to address this issue in `v1.12.1`. The patch should go out later today.

Sorry for the inconvenience caused.

**Comment by akaRookieDev** [comment]
Is this issue causing other versions not to work as well? I am running 1.11 of the Microsoft.Graph.Calendar and im getting this error.
```
Get-MgUserEvent : One or more errors occurred.
At line:1 char:1
+ Get-MgUserEvent -UserId $UserID -Filter "isOrganizer eq true and star ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgUserEvent_List1], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Graph.PowerShell.Cmdlets.GetMgUserEvent_List1
 ```

**Comment by terrencemcbride** [comment]
-all parameter is not found on get-MgGroupMember
I've tried all the versions of microsoft.graph I can find.... god help me.
