### ISSUE TITLE
Get-MgUser Issuer Identity for guest user

### ISSUE THREAD

**Issue by lucafabbri365** [microsoftgraph/msgraph-sdk-powershell#1534]
Hello,
I need to retrieve the **Identity Issuer** (_ExternalAzureAD, MicrosoftAccount, google.com_ or _mail_) for an Azure AD guest user via PowerShell. 
I can do it via **Microsoft Graph Explorer**:

`https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}?$select=identities`

Response:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(identities)/$entity",
    "identities": [
        {
            "signInType": "federated",
            "issuer": "MicrosoftAccount",
            "issuerAssignedId": null
        },
        {
            "signInType": "userPrincipalName",
            "issuer": "*** Data omitted for security reasons ***",
            "issuerAssignedId": "*** Data omitted for security reasons ***"
        }
    ]
}

```
The guest user above has a **Microsoft Account**.

If I use the **Get-MgUser** cmdlet, it returns empty object:
```
Get-MgUser -UserId $userId -Property "identities"

Id DisplayName Mail UserPrincipalName UserType
-- ----------- ---- ----------------- --------
```
The user querying it has **User.Read.All** and **Directory.Read.All** permissions.

Do I miss something or is it a **Get-MgUser** limit ?

Thank you,
Luca

**Comment by peombwa** [comment]
You should pipe the command to `Select-Object` to select/show properties outside the default pre-selected properties (Id, DisplayName, Mail, UserPrincipalName, and UserType):
``` powershell
 Get-MgUser -UserId $userId -Property "identities" | Select-Object Identities
``` 

See known issues at https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues.

**Comment by lucafabbri365** [comment]
Hello @peombwa,
adding the `Select-Object -ExpandProperty Identities` gave the same (empty) results. I resolved updating PowerShell module to latest version **1.11.1** (previously 1.9.2 - pretty "old"; my fault !!!).

Thank you,
Luca
