### ISSUE TITLE
Connect-MgGraph - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by p-zim** [microsoftgraph/msgraph-sdk-powershell#1535]
I'm attempting to authentication to Graph in PowerShell and receive the error "Object reference not set to an instance of an object"

See screenshot for command and version information:

![image](https://user-images.githubusercontent.com/61678937/192206352-9546a607-5a87-494d-a3e1-faa7300b38d5.png)

Re-installing the module does not help. Same behavior with PowerShell ISE.

**Comment by p-zim** [comment]
note: Same error occures when I add -UseDeviceAuthentication

**Comment by timayabi2020** [comment]
@p-zim Thanks for identifying and raising this issue. 
That is indeed a bug on the SDK version you are using. Meanwhile you can rollback to the previous stable version (1.11.1) while the team works to resolve the issue


![Image](https://user-images.githubusercontent.com/10947120/192982270-834be4e6-00b9-4da2-aca2-5e936946971b.png)

**Comment by p-zim** [comment]
Unfortunately that does not work for me:

![image](https://user-images.githubusercontent.com/61678937/193198951-df4b9c82-279b-4f9b-8e43-1704613d459e.png)

**Comment by p-zim** [comment]
just fyi: In the meantime Microsoft.Graph 1.15.0 is available but still the same issue.

**Comment by ddyett** [comment]
@timayabi2020 let's prioritize this investigation

**Comment by cookiecop** [comment]
Hello I just wanted to comment that I am experiencing this as well.
I am using Connect-MgGraph -scopes "User.Read.All" - ClientId $AppID -TenantID $tenantID -UseDeviceRegistration

i go to the devicelogin page... it says i have logged into my app then in my console i get

and i get Connect-MgGraph " Object reference not set to an instance of an object

first i tried upgraphing my version which was 1.12 and it upgraded to 1.16.0 then i tried reverting my graph version.. i uninstalled and then tried to re-install with -requiredversion 1.11.1 but when i check my graph.authentication it still says 1.16.0 so i am not sure what is going on there... if there is any workarounds anyone knows about ?

**Comment by timayabi2020** [comment]
@p-zim , @cookiecop you can try resetting the token cache by using the command ``Disconnect-MgGraph``. If you still get the same error, run the command ``Remove-Item "$env:USERPROFILE\.graph" -Recurse -Force`` then run ``Connect-MgGraph -contextScope Process -TenantId $env:TenantID -clientId $env:ClientID -scopes "User.Read"`` again to reconstruct the token cache.

**Comment by p-zim** [comment]
@timayabi2020 Same result with "Connect-MgGraph: Object reference not set to an instance of an object."
I have currently Microsoft.Graph.Authentication 1.15.0 installed.

**Comment by timayabi2020** [comment]
@p-zim that's weird. I am also not able to reproduce your scenario on my end.  What do you get if you run the command with TenantId and scopes only? i.e ``Connect-MgGraph -TenantId $env:TenantID -scopes "User.Read"``

**Comment by cookiecop** [comment]
@timayabi2020 
just wanted to write an update. I ran your commands. didn't change anything. the error for me only occurs when i use:
-UseDeviceRegistration
and only when I try to use my own app ID. I need to use -UseDeviceRegistration because of the way I am setting up my script (the script is run doing some onprem  stuff with onprem credentials and then midway in the script it needs to do something in the cloud)

so maybe its something wrong with the way I have setup my app?
I have it configured as:
Desktop App:
https://login.microsoftonline.com/common/oauth2/nativeclient
https://localhost

**Comment by timayabi2020** [comment]
@cookiecop 
Please share the output of this command ```$Error[0].Exception``` after running the Connect-MgGraph -UseDeviceRegistration.
Also share the output of this command ```Get-Module Microsoft.Graph* | select Name, Version```

**Comment by cookiecop** [comment]
[PS] C:\scripts\azure>Connect-MgGraph -Scopes "User.Read.All" -ClientId $AppID -TenantId $TenantID -UseDeviceAuthentication -Verbose
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code EC3HZ88ML to authenticate.
Connect-MgGraph : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-MgGraph -Scopes "User.Read.All" -ClientId $AppID -TenantId $T ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MgGraph], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph

[PS] C:\scripts\azure>$Error[0].Exception
Object reference not set to an instance of an object.
[PS] C:\scripts\azure>Get-Module Microsoft.Graph* | select Name, Version

Name                           Version
----                           -------
Microsoft.Graph.Authentication 1.16.0


:(

**Comment by timayabi2020** [comment]
@cookiecop was there any success? I am still not able to reproduce the error you are getting. Perhaps you should check on how your app has been set up . Please follow the steps [here](https://learn.microsoft.com/en-us/graph/tutorials/java?tabs=aad&tutorial-step=1) to set up your app for authentication.

**Comment by Fefke** [comment]
I had the "Connect-MgGraph: Object reference not set to an instance of an object" several times, always around 4pm (Europe/Berin) - might be a coincidence.. or not.
