### ISSUE TITLE
Get-MgRoleManagemtnDirectoryRoleEligibilitySchedule : no more "-all" parameter

### ISSUE THREAD

**Issue by vincentmiens** [microsoftgraph/msgraph-sdk-powershell#1536]
The parameter disappears since the 1.12.1 version :(
Thanks.

**Comment by peombwa** [comment]
`Get-MgRoleManagementDirectoryRoleEligibilitySchedule` has `-All` parameter in version `1.12.1` and it works as expected:

![image](https://user-images.githubusercontent.com/7061532/192583269-97ce0150-2c85-4eb9-a8f0-a5486c592dc8.png)

Please note that we unlisted version `1.12.1` due to #1532. You can follow the steps at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1532#issuecomment-1256426537 to revert back to version `1.11.1` if version `1.12.1` is causing issues for you.

**Comment by peombwa** [comment]
Closing as unlisted. Please follow the steps at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1532#issuecomment-1256426537 to revert back to version 1.11.1.

**Comment by vincentmiens** [comment]
Hello,
I can say you the -All parameter was disappeared from my 1.12.1 version :

***@***.***

But anyway, yes, I rollbacked to the 1.11.1 version.
It works now 😊

Thanks,
Vincent.

[nouveau logo]
Vincent Miens
Développeur - Escouade IaaS Azure

Direction Principale Services Infonuagiques
Mouvement Desjardins




De : Peter Ombwa ***@***.***>
Envoyé : 27 septembre 2022 12:37
À : microsoftgraph/msgraph-sdk-powershell ***@***.***>
Cc : Vincent Miens ***@***.***>; Author ***@***.***>
Objet : Re: [microsoftgraph/msgraph-sdk-powershell] Get-MgRoleManagemtnDirectoryRoleEligibilitySchedule : no more "-all" parameter (Issue #1536)

COURRIEL EXTERNE CONTENANT UNE PIÈCE JOINTE OU UN LIEN URL / EXTERNAL EMAIL WITH AN ATTACHMENT OR A URL LINK
Soyez vigilant, développez les bons réflexes et ne téléchargez aucune pièce jointe non sollicitée! Au besoin, cliquez sur l’icône Signaler ou faites suivre ce courriel à ***@***.******@***.***>. / Be vigilant, develop the right instincts and do not download any unsolicited attachment! If required, click the Report button or forward the email at ***@***.******@***.***>


Closed #1536<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmsgraph-sdk-powershell%2Fissues%2F1536&data=05%7C01%7Cvincent.miens%40desjardins.com%7C9e770432ed8b4f0d620208daa0a68bae%7C728d20a50b4447dd947020f37cbf2d9a%7C0%7C0%7C637998934411590693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vItZmCJjLwu%2F04erBaSaYq0dTI6IrzMiQQwj9Oug1Ng%3D&reserved=0> as completed.
