### ISSUE TITLE
field is not recognized [Update-MgSiteListItem] PowerShell MS Graph API

### ISSUE THREAD

**Issue by MarianoGoettel** [microsoftgraph/msgraph-sdk-powershell#1537]
Hey all,

i want to update a Sharepoint ListItem via the MS Graph API in an PowerShell Script. When I am adding other column´s besides 'Signed' I got the issue that the 'field '...' is not recognized'. Makes no sense, because the other columns are right next to the 'signed' column for which the command works.

`for ($i = 0; $i -lt $Item.Fields.AdditionalProperties.length; $i++) {
    if ($Item.Fields.AdditionalProperties.Mitarbeiter_x002d_Name[$i] -eq $UserName) {
        $ItemMitarbeiterName = $Item.Fields.AdditionalProperties.Mitarbeiter_x002d_Name[$i]
        $ItemTeamsValue = $Item.Fields.AdditionalProperties.Teams[$i]
        $ItemId = $Item.Id[$i]
        
        $Fields = @{
            fields = @{
                Signed = $true 
                Teams = $true
            }
        }    
        Update-MgSiteListItem -SiteId $siteId -ListId $NeueMitarbeiterListId -ListItemId $ItemId -BodyParameter $Fields 
    }
}`

The commands via the MG Graph Explorer are working.

Thanks for you help.

Much Greetings,
Mariano

**Comment by peombwa** [comment]
The properties of fields object are case sensitive. Please ensure you are using the correct casing for the `signed` and `teams` properties.

See related issue at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1185#issuecomment-1145190155.

**Comment by MarianoCalabrese** [comment]
Hey peombwa, thanks for you response. 

Sadly, i got the same failure message.

**Comment by peombwa** [comment]
Please share the output of the following details for us to repro this on our end:
- `Get-Module Microsoft.Graph, Microsoft.Graph.Authentication`.
- `$PSVersionTable`.

**Comment by MarianoCalabrese** [comment]
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by peombwa** [comment]
I'm still not able to reproduce the error when using the right casing for the `fields` properties.

The error is only reproducible when the casing does not match the List Item's column name.
![image](https://user-images.githubusercontent.com/7061532/193341527-4437d29e-b157-4192-aeb0-93f8e5411c2a.png)

What error do you get when you use `Invoke-MgGraphRequest` as shown below?
``` powershell
$Body = @{
      fields = @{
          Signed = $true 
          Teams = $true
      }
}

Invoke-MgGraphRequest -Method POST -Uri "/v1.0/sites/$SiteId/lists/$ListId/items" -body ($body | ConvertTo-Json) 
```
