### ISSUE TITLE
Remove-MgGroupMemberbyRef Cosmetic Error

### ISSUE THREAD

**Issue by lsimon17** [microsoftgraph/msgraph-sdk-powershell#1539]
I have an offboarding script and am trying to remove all of the users' groups using the following command:
`Connect-MgGraph -Scopes "User.ReadWrite.All","Group.ReadWrite.All"
            $groupList =  Get-MgUserMemberOf -UserId $userId
            ForEach ($Group in $groupList)
            {
            Remove-MgGroupMemberbyRef -GroupID $Group.ID -DirectoryObjectID $userID
            }`

I get an error multiple times saying I have insufficient privileges. My account I am running these commands with is a global administrator, and I have consented Graph permissions on behalf of our organization.
`
Remove-MgGroupMemberbyRef : Insufficient privileges to complete the operation.
At C:\Users\admin\Desktop\Offboarding.ps1:153 char:13          Remove-MgGroupMemberbyRef -GroupID $Group.ID -DirectoryOb ...  CategoryInfo          : InvalidOperation: ({ GroupId = 5e6...tch = , Id =  }:<>f__AnonymousType96 4) [Remove-MgGroupMemberByRef_Dele te1], RestException1+ FullyQualifiedErrorId Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.RemoveMgGroupMemberByRef_Delete1
`
It looks like the groups get removed, but is there something like an error action I can add so these errors don't continue to show up every time?

**Comment by lsimon17** [comment]
?

**Comment by peombwa** [comment]
`Insufficient privileges to complete the operation` is a service error and not a client error.

Please ensure that:
- The group does not have dynamic membership.
  > You can't remove a member from groups with dynamic membership

  See https://learn.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=http
- Ensure the calling user has `RoleManagement.ReadWrite.Directory` ff the group is a role-assignable group:
  > To remove members from a role-assignable group, the calling user must also be assigned the RoleManagement.ReadWrite.Directory permission.

  See https://learn.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=http#permissions.
  Related issue - https://github.com/microsoftgraph/microsoft-graph-docs/issues/14806.

As this repository is intended for issues related to the functionality of the SDK, we may not be the best placed to answer some queries that are tied to the functionality of the API.

Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support to get an answer from the API owners if the above suggestions don't work.
