### ISSUE TITLE
Connect-Graph fails to cast roles into String[] if there is only 1 permission

### ISSUE THREAD

**Issue by genorex** [microsoftgraph/msgraph-sdk-powershell#154]
An example below is when there is only 1 API application permission:
Connect-Graph : Error converting value "Reports.Read.All" to type 'System.String[]'. Path 'roles', line 1, position 441.

**Comment by darrelmiller** [comment]
@genorex  Can you provide some details of the module versions that you are using?  We are not able to repro this.

**Comment by peombwa** [comment]
@genorex This issue is due to how we are reading the claims from the access token. This will be fixed by PR https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/164.
