### ISSUE TITLE
Graph /reports URLs are redirected to a server that requires TLS1.2

### ISSUE THREAD

**Issue by genorex** [microsoftgraph/msgraph-sdk-powershell#155]
https://graph.microsoft.com/v1.0/reports redirects the available report for download to reportsweu.office.com.
If the powershell session doesn't support TLS1.2 the connection is dropped and the error is only visible when performing a trace.

Perhaps it is wise to report this error or set it as required if many endpoints will require this.
Enabling strong crypto or adding the following below fixes this issue.
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
[AB#7441](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7441)

**Comment by peombwa** [comment]
The SDK should now throw transport related errors as part of the fix made in https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/973. PowerShell uses the system default security protocol.
