### ISSUE TITLE
Cmdlets should accept request headers

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-powershell#1570]
Some APIs such as https://docs.microsoft.com/en-us/graph/api/plannertaskdetails-update?view=graph-rest-1.0&tabs=http#request-headers require the caller to set a request header. Currently, there is no option for one to set request headers to the generated PS cmdlets when making a call.

ASK
Allow customers to pass a list of request headers as a parameter to the generated cmdlets.

**Comment by peombwa** [comment]
This should be a feature request for AutoREST.PowerShell. AutoREST does not currently support setting of arbitrary request headers on generated cmdlets.

The current AutoREST design requires the supported headers to be explicitly declared in the CSDL metadata. See `ConsistencyLevel` header example at https://github.com/microsoftgraph/msgraph-metadata/issues/38.
