### ISSUE TITLE
Update-MgOrganizationBranding: "Resource '<guid>' does not exist or one of its queried reference-property objects are not present."

### ISSUE THREAD

**Issue by mreagan-epion** [microsoftgraph/msgraph-sdk-powershell#1574]
When trying to update the branding on a tenant, I get this error: "Resource '<guid>' does not exist or one of its queried reference-property objects are not present."

$companyLogo is a PNG photo located on local C:
$tenantID is the GUID ID found in Azure AD
The exact command I'm running is "Update-MgOrganizationBranding -BackgroundImageInputFile "$companyLogo" -BannerLogoInputFile $companyLogo -OrganizationId $tenantID"

Here is the Debug out: 
[updateMgOrgDebug.txt](https://github.com/microsoftgraph/msgraph-sdk-powershell/files/9803801/updateMgOrgDebug.txt)

**Comment by peombwa** [comment]
@mreagan-epion, the error message suggests that the provided `-OrganizationId` is not the correct tenant id for the signed in user. Please verify that you have the right `OrganizationId` by running `Get-MgOrganization` to get your organization's details. See https://learn.microsoft.com/en-us/graph/api/organization-get?view=graph-rest-beta&tabs=powershell.

**Comment by mreagan-epion** [comment]
Below is the requested information:

[Text  Description automatically generated]

From: Matthew J. Reagan
Sent: Monday, October 24, 2022 10:46 AM
To: microsoftgraph/msgraph-sdk-powershell ***@***.***>; microsoftgraph/msgraph-sdk-powershell ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoftgraph/msgraph-sdk-powershell] Update-MgOrganizationBranding: "Resource '<guid>' does not exist or one of its queried reference-property objects are not present." (Issue #1574)

Hi Peter,

I will check the Organization ID and get back to you.

Thanks

**Comment by mreagan-epion** [comment]
![Screenshot 2022-10-24 105658](https://user-images.githubusercontent.com/109161704/197571733-88ade53b-dc81-4d7b-95f1-188f7f84c84b.png)

**Comment by peombwa** [comment]
Sorry for the delayed response. I would also recommend you open a question at https://developer.microsoft.com/en-us/graph/support to get an answer from the API owners. The issue is API related and can be reproduced through Graph Explorer.

As this repository is intended for issues related to the functionality of the module, we may not be the best placed to answer some queries that are tied to the functionality of the API.
