### ISSUE TITLE
Get-MgDrive does not show full property info

### ISSUE THREAD

**Issue by rogers14k** [microsoftgraph/msgraph-sdk-powershell#1575]
Hi, Im somewhat new to graph so sorry if this is a trivial question. My overall goal is to be able to add a new Site Collection Owner to a OneDrive using powershell. Im stuck trying to at least list the owners of a specific OneDrive as it just shows Microsoft.Graph.PowerShell.Models.MicrosoftGraphIdentitySet . Any idea how I should proceed? Im a global admin btw and can make any change needed to achieve my goal. Thanks in advance for any help!

**Comment by peombwa** [comment]
@rogers14k, I'd recommend you start by going through the [API reference docs](https://learn.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0) to first identify the API you need to call. Once you've found the API you are interested in, scroll down to the example section and click on the PowerShell tab to find the right PowerShell command needed to call the API.

The owner property is a .NET object type (`Microsoft.Graph.PowerShell.Models.MicrosoftGraphIdentitySet`) than can be accessed using PowerShell's `Select-Object` by:
``` powershell
Get-MgUserDrive -UserId $UserId  -Debug | Select-Object -ExpandProperty Owner | Select-Object -ExpandProperty User
# or
$UserDrive = Get-MgUserDrive -UserId $UserId -Debug
$UserDrive.Owner.User # gives you back the owner of user.
# or
$Owner = (Get-MgUserDrive -UserId $UserId  -Debug).Owner
$Owner.User
```

According to the API reference doc, the owner property of a drive is read-only and cannot be changed - https://learn.microsoft.com/en-us/graph/api/resources/drive?view=graph-rest-1.0#properties. Feel free to open a feature request/question at https://developer.microsoft.com/en-us/graph/support If an API is not available for your scenario.
