### ISSUE TITLE
Creating new user event in user's secondary calendar

### ISSUE THREAD

**Issue by blanalex** [microsoftgraph/msgraph-sdk-powershell#1580]
I'm trying to create events to a user's secondary calendar with the following command:
```
New-MgUserEvent -UserId $userid -Calendar @{Id=$calendarId} -Subject "Hello" -Start $start -End $End
```
No matter what, the event gets created into the users primary calendar.

I tried with Invoke-MgGraphRequest and the following works (with the same variable values as the New-MgUserEvent command above):
```
$graphURI="/v1.0/users/{0}/calendars/{1}/events" -f $userid,$calendarId
$graphRequestBody=@{
    Subject = "Hello"
    Start   = $Start
    End     = $End
} | ConvertTo-Json
Invoke-MgGraphRequest -Method POST -Uri $graphURI -Body $graphRequestBody
```

So am I missing something in my New-MgUserEvent command or is this a bug?
Tested with Microsoft.Graph.Calendar 1.13.0

**Comment by peombwa** [comment]
@blanalex, please use [Find-MgGraphCommand](https://learn.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-command?view=graph-powershell-1.0) or the [API reference](https://learn.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0) to lookup the right command needed to call API.

In this case, according to `Find-MgGraphCommand`, the right command to use is `New-MgUserCalendarEvent`:
``` powershell
➜ Find-MgGraphCommand -Uri "/v1.0/users/{0}/calendars/{1}/events" -Method POST

   APIVersion: v1.0

Command                 Module   Method URI                                             OutputType            Permissions           Varia
                                                                                                                                    nts
-------                 ------   ------ ---                                             ----------            -----------           -----
New-MgUserCalendarEvent Calendar POST   /users/{user-id}/calendars/{calendar-id}/events IMicrosoftGraphEvent1 {Calendars.ReadWrite} {Cre…
```
`New-MgUserCalendarEvent -UserId $UserId -CalendarId $CalendarId -Start $Start -End $End -Subject "Hello!" -Debug`
