### ISSUE TITLE
RecipientType missing in Get-MgReportMailboxUsageDetail

### ISSUE THREAD

**Issue by Focus182** [microsoftgraph/msgraph-sdk-powershell#1581]
When you download the Mailbox Usage Detail report from the Admin portal, the CSV contains the property RecipientType (User/Shared).

This information is not available when running the Get-MgReportMailboxUsageDetail. Please update and add this information into the CSV output.

**Comment by peombwa** [comment]
@Focus182, `RecipientType` is only available in beta. Please use [Select-MgProfile beta](https://learn.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0#api-version) to load the beta profile.

See related issue - https://github.com/microsoftgraph/microsoft-graph-docs/issues/17968.
