### ISSUE TITLE
Found unused cmdlets for CA Templates

### ISSUE THREAD

**Issue by xuchen1122** [microsoftgraph/msgraph-sdk-powershell#1586]
Hi, in the MS Graph API PowerShell these cmdlets exist:
 
Get-MgIdentityConditionalAccessTemplate
New-MgIdentityConditionalAccessTemplate
Remove-MgIdentityConditionalAccessTemplate
Update-MgIdentityConditionalAccessTemplate
 
However,  ~/beta/identity/conditionalaccess/templates API only support Get calls, which Get-MgIdentityConditionalAccessTemplate uses. The rest is unused and shouldn't be generated. How to remove these? Also, how can I prevent unneeded commands from getting generated?

Thank you!

**Comment by peombwa** [comment]
Both [v1.0](http://graph.microsoft.com/v1.0/$metadata) and [beta](http://graph.microsoft.com/beta/$metadata) CSDL say that API methods are supported as there is no capability annotations restricting them:
 
Please add the following OData capability annotations to restrict the insertability, updatability, and delectability of the containment navigation property:
-	[InsertRestrictions](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md#insertrestrictionstype)
-	[UpdateRestrictions](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md#UpdateRestrictionsType)
-	[DeleteRestrictions](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md#deleterestrictionstype)

Closing the issue as we are already engaged with the customer.
