### ISSUE TITLE
Support for Accepting, Cancelling, Declining Events

### ISSUE THREAD

**Issue by Staja** [microsoftgraph/msgraph-sdk-powershell#160]
The ability to [accept](https://docs.microsoft.com/en-us/graph/api/event-accept?view=graph-rest-beta), [tentatively accept](https://docs.microsoft.com/en-us/graph/api/event-tentativelyaccept?view=graph-rest-beta),  [cancel](https://docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-beta) and [decline](https://docs.microsoft.com/en-us/graph/api/event-decline?view=graph-rest-beta) [event](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta)s would be helpful.

**Comment by darrelmiller** [comment]
We are working to generate these actions and will be available in a future release.
