### ISSUE TITLE
Incorrect URI

### ISSUE THREAD

**Issue by JamesE84** [microsoftgraph/msgraph-sdk-powershell#1602]
Correct (confirmed via MsGraph Online): https://graph.microsoft.com/beta/deviceManagement/manageddevices('164386e5-44e9-4089-9756-51029fb6d62b')?$expand=detectedApps

Incorrect (Generated by Cmdlet): https://graph.microsoft.com/beta/users/ec15c0d0-ca6e-49d9-acca-0695966b4e5e/managedDevices/164386e5-44e9-4089-9756-51029fb6d62b?Expand=detectedApps

The userid should not be mandatory for:

Get-MgUserManagedDevice cmdlet.

**Comment by peombwa** [comment]
@JamesE84, please use `Find-MgGraphCommand` to locate the command you are interested in by passing it the request URI. In this case, `Find-MgGraphCommand` yields `Get-MgDeviceManagementManagedDevice` as the right command to use:
``` powershell
➜ Find-MgGraphCommand -Uri "https://graph.microsoft.com/beta/deviceManagement/manageddevices/164386e5-44e9-4089-9756-51029fb6d62b"

   APIVersion: beta

Command                                Module           Method URI                                                 OutputType
-------                                ------           ------ ---                                                 ----------
Get-MgDeviceManagementManagedDevice    DeviceManagement GET    /deviceManagement/managedDevices/{managedDevice-id} IMicrosoftGraphManage…
Remove-MgDeviceManagementManagedDevice DeviceManagement DELETE /deviceManagement/managedDevices/{managedDevice-id}
Update-MgDeviceManagementManagedDevice DeviceManagement PATCH  /deviceManagement/managedDevices/{managedDevice-id}
```

According to the metadata CSDL (service schema), a `User` entity has a relationship to `managedDevices`. See https://learn.microsoft.com/en-us/graph/api/resources/intune-devices-user?view=graph-rest-1.0#relationships:
``` xml
<EntityType Name="user" BaseType="graph.directoryObject" OpenType="true">
    <Property Name="signInActivity" Type="graph.signInActivity" />
    <Property Name="accountEnabled" Type="Edm.Boolean" />
    <Property Name="schools" Type="Collection(Edm.String)" />
    <Property Name="skills" Type="Collection(Edm.String)" />
    <NavigationProperty Name="managedDevices" Type="Collection(graph.managedDevice)" ContainsTarget="true" />
</EntityType>
```

**Comment by JamesE84** [comment]
Thanks! That was very helpful. I appreciate it.
