### ISSUE TITLE
/beta/teamwork/devices REST Endpoint - Works on some tenants, but not others

### ISSUE THREAD

**Issue by william-soler** [microsoftgraph/msgraph-sdk-powershell#1603]
This endpoint did work for us about a week ago, but just stopped working this week on our production O365 tenant
GET https://graph.microsoft.com/beta/teamwork/devices

We have one true production tenant with ~3K devices and 200k+ users and a number of QA and Staging tenants.

This endpoint works fine when targeting any of our Staging or QA tenants,.  Obviously using distinct Enterprise App ID/secrets to generate appropriate Auth headers per tenant, but otherwise common code to make the REST call, and it returns without issue in non-production O365 tenants, but produces this error in our production environment.

```
Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.
At line:1 char:18
+ ... s_Request = Invoke-RestMethod -Uri $calls_uri -Headers $Header -Metho ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

It is very straightforward call (See below).  No issues with permissions as I use the same App for other functions and the tenants were this works have apps that are all configured identically with the appropriate permissions. 

'''
$calls_uri ="https://graph.microsoft.com/beta/teamwork/devices"
$Calls_Request = Invoke-RestMethod -Uri $calls_uri -Headers $Header -Method Get -ContentType "application/json"
'''

For completeness sake, we have `TeamworkDevice.ReadWrite.All` permission granted for this application

**Comment by peombwa** [comment]
@william-soler, please open a service ticket/question at https://developer.microsoft.com/en-us/graph/support to get an answer from the API owners as this is a service issue.

This repository is only intended for issues related to the functionality of the Microsoft Graph PowerShell module.
