### ISSUE TITLE
New-MgEntitlementManagementAssignmentRequest | Provide Mandatory Answers

### ISSUE THREAD

**Issue by timd19** [microsoftgraph/msgraph-sdk-powershell#1607]
I have an access package that has a policy containing required questions. How would I use the New-MgEntitlementManagementAssignmentRequest cmdlet and pass in the required information?

the documentation does not provide examples for this - https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.governance/new-mgentitlementmanagementassignmentrequest?view=graph-powershell-1.0

thanks.

**Comment by peombwa** [comment]
Thanks for following up on this.

Can you share a snippet of what you've tried thus far?

For how-to questions/ API questions, we recommend you open a question at https://developer.microsoft.com/en-us/graph/support to get an answer from the API owners. We may not be the best placed to answer some queries that are tied to the functionality of the API.

You can also refer to the API documentation at https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&tabs=powershell for instructions on how to use the API. `New-MgEntitlementManagementAssignmentRequest` simply calls `POST /identityGovernance/entitlementManagement/assignmentRequests` as is.
