### ISSUE TITLE
No signature on Microsoft.Graph.Authentication.psm1

### ISSUE THREAD

**Issue by Prefix42** [microsoftgraph/msgraph-sdk-powershell#1612]
The psm1 for Microsoft.Graph.Authentication as published on the PowerShell Gallery has not been signed. I have spot checked multiple version and this appears to have been the case since v0.2.0 (First release) through to v1.14.0 (Current).

**Comment by peombwa** [comment]
Fixed by #1652.

Signed psm1 and psd1 will ship in v2 preview in a couple of weeks.
