### ISSUE TITLE
Look into parameter casing in PowerShell as some queries fail when some parameters are in upper camel case instead of lower camel case. When the HTTPS example is converted to PowerShell, the parameter casing should be maintained.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1626]
See customer issue [19168](https://github.com/microsoftgraph/microsoft-graph-docs/issues/19168).

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

I've transferred the issue to DevX API for the snippet logic to be corrected. See https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1252.
