### ISSUE TITLE
Get-MgUserMailFolderMessageContent calls a URL that gives an HTTP 405

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-sdk-powershell#1627]
This cmdlet calls `GET /users/{user-id}/mailFolders/{folder-id}/messages/{message-id}/$value`, which returns a 405.

Workaround: use `Get-MgUserMessageContent` instead.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

Unfortunately, the service CSDL metadata (our source of truth) says that `GET /users/{user-id}/mailFolders/{folder-id}/messages/{message-id}/$value` is a valid path. We will suppress the command in our subsequent releases.

**Comment by timayabi2020** [comment]
Closed by https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2875
