### ISSUE TITLE
Lack of proper documentation (Possibility to update Azure AD -> Group -> General settings)

### ISSUE THREAD

**Issue by akumarnc** [microsoftgraph/msgraph-sdk-powershell#1636]
Hi,
I have been exploring to update below settings using 'MS Graph PS' but unfortunately cannot see any proper documentation on how to achieve this. As per my current investigation it seems to be feasible using 'Update-MgOrganization' command, but I am missing details on how to practically achieve it. Any guidance is appreciated.

![image](https://user-images.githubusercontent.com/101809041/202113218-ac20456c-40a8-4726-ad91-e10253766ada.png)

**Comment by salbeck-sit** [comment]
I believe this will get you at least part of the way: https://learn.microsoft.com/en-us/graph/api/resources/groupsetting?view=graph-rest-1.0&preserve-view=true in combination with https://learn.microsoft.com/en-us/graph/group-directory-settings#groupunified

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

Group settings APIs are currently not covered by the module. I've open issue https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1643 to track this ask. The APIs should be available in our next releases.

As a workaround, you can use `Invoke-MgGraphRequest` to make REST calls to the APIs linked above. See https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-invoke-mggraphrequest.

**Comment by peombwa** [comment]
Group settiings commands will be provided by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1643.
