### ISSUE TITLE
Get-MgApplication -Filter web/redirectUris https://VisualStudio/SPN

### ISSUE THREAD

**Issue by Daleyon** [microsoftgraph/msgraph-sdk-powershell#1646]
Per our internal Cloud Security requirement, I need to get a list of SPNs provisioned by Azure DevOps + passwordCredentials expiration date.
Using this call:
Get-MgApplication -Filter "web/redirectUris/any(p:p eq 'https://VisualStudio/SPN')" -ConsistencyLevel eventual -CountVariable appCount
Response:
I can only receive (1) or First in Applications list containing redirectUris 'https://VisualStudio/SPN'.

However, building a script with filtering the output... Where-Object -Property RedirectUri -Contains 'https://VisualStudio/SPN'... all is good.
Expected response:
Get-MgApplication -Filter "web/redirectUris/any(p:p eq 'https://VisualStudio/SPN')" -ConsistencyLevel eventual -CountVariable appCount
Returns all applications containing redirectUris 'https://VisualStudio/SPN'

**Comment by peombwa** [comment]
Thanks for following up on this.

Please post the question to https://developer.microsoft.com/en-us/graph/support to get assistance from the API owners as this is a service issue. The same behavior can be reproduced through [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=applications%3F%24filter%3Dweb%2FredirectUris%2Fany(p%3Ap%2Beq%2B'https%3A%2F%2FVisualStudio%2FSPN')%26%24count%3Dtrue&method=GET&version=beta&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d). `web/redirectUris` property is listed as supporting `$filter` when `ConsistencyLevel` header and/or `$count=true` is present. See https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#application-properties.

As this repository is intended for issues related to the functionality of the module, we may not be best placed to answer some queries that are tied to the functionality of the API.

**Comment by peombwa** [comment]
Closing as service issue.
