### ISSUE TITLE
update-mguser - Where do I fail?

### ISSUE THREAD

**Issue by enricogiacomin** [microsoftgraph/msgraph-sdk-powershell#1649]
I'm trying to set the attribute CompanyName and Department to some users.

```
PS /Users/enrico> Connect-MgGraph -Scopes "User.Readwrite.All", -TenantId nanosoftdemo.onmicrosoft.com  
Welcome To Microsoft Graph!
PS /Users/enrico> update-MgUser -UserId user@nanosoftdemo.onmicrosoft.com -CompanyName "NanosoftDemo"

```
The attribute is set on AAD Portal, but not if I launch the command:

```
PS /Users/enrico> Get-MgUser -UserId m.panzeri@nanosoft365.com | ft companyName

CompanyName
-----------

```

Could you please check if it is common and why? Thank you. I tried on PSCore 7.3 on Windows and macOS.

Enrico

**Comment by peombwa** [comment]
@enricogiacomin, please see the API reference at https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties. The property is only returned on `$select` in `v1.0`:
``` powershell
Get-MgUser -UserId "User_Id" -Select CompanyName, Id -Debug | ft companyName
```
