### ISSUE TITLE
New-MgGroup -owners  issue

### ISSUE THREAD

**Issue by tikesavage** [microsoftgraph/msgraph-sdk-powershell#1650]
having trouble with setting the owners parameter when using new-mggroup -owners. 
I have tried using UPN and Object ID.i am currently trying different iterations of the below code. (user id is santizied)

provides error 1
$Owner = (Get-MgUser -UserId 'test@domain.com').id
$GroupOwner = "https://graph.microsoft.com/v1.0/users/" + $Owner 

provides error 2
$temp = (Get-MgUser -UserId 'test@domain.com) 
$GroupOwner = $temp.Values

$GroupParameters = @{
DisplayName = "GraphTest" 
Description = "Graph SDK  for Powershell test " 
GroupTypes = "Unified" 
MailNickname = "GraphTest" 
SecurityEnabled = $true 
MailEnabled = $false 
MembershipRuleProcessingState = "On" 
Visibility = "private" 
owners = $GroupOwner }

New-MgGroup @GroupParameters

error 1
Cannot process argument transformation on parameter 'Owners'. Cannot convert value "System.Collections.Generic.Dictionary`2+ValueCollection[System.String,System.Object]" to type "Microsoft.Graph.PowerShell.Models.IMicrosoftGraphDirectoryObject[]". Error: "Cannot convert the "https://graph.microsoft.com/v1.0/$metadata#users/$entity" value of type "System.String" to type "Microsoft.Graph.PowerShell.Models.IMicrosoftGraphDirectoryObject"."

error 2
New-MgGroup_CreateExpanded:
The context URL 'https://graph.microsoft.com/v1.0/$metadata#users/$entity' is invalid.

**Comment by peombwa** [comment]
@tikesavage, please use the example at https://learn.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=powershell#example-2-create-a-group-with-owners-and-members.

Creating a group with an owner or member requires you to specify the owner/member via OData bind.

**Comment by tikesavage** [comment]
Sorry but Do i really need to query for a users upn or Object Id, then concatenate that to 'https://graph.microsoft.com/v1.0/users/' per user, then format that into odata query ,  instead of  being able to reference upn or object id directly ? or am i missing some other option? because as it stands the other option which i 3 additional cmdlets  is to create a new m365 group with the default owner (automation account) add new owners with new-mggroupowner, then remove the automation account with remove-mggroupownerbyref. 

Is there some other way i can get get an array of users Odata.id and store as an array to pump in here?

if thats the case than this cmdlet is not useable for me in its current state. 
this cmdlet really needs the ability accept owners and members by explicit  UPNs or ObjectIDs, and an array of them.
something like "-ownerbyRef " or "-memberbyRef" this is  how New-MgGroupMember and New-MgGroupOwner cmdlets accept input.

**Comment by ztrhgf** [comment]
Graph API is a nightmare for Windows admins, this is just another example of that :)
