### ISSUE TITLE
The cmdlet Update-MgPolicyAdminConsentRequestPolicy returns the error 'No HTTP resource was found that matches the request URI'

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1661]
This is on both V1.0 and beta profile.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/73849846/205139967-8533fbfd-bc76-4270-88f4-64d85ddd08b3.png">

**Comment by peombwa** [comment]
Duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/218.

We will need to open ICM to surface this to the workload owner. The CSDL currently says the API supports PATCH instead of PUT for updates.

**Comment by peombwa** [comment]
Closing as duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/218

**Comment by peombwa** [comment]
I've opened ICM # 352593620 for the workload to fix the missing annotation.

**Comment by YenNantes** [comment]
Hi,
Any update?
It's been a while that this issue was raised and so far it does not seem to be fixed.
