### ISSUE TITLE
Get-mgdirectory role throws non-specific error

### ISSUE THREAD

**Issue by zealoususer** [microsoftgraph/msgraph-sdk-powershell#1662]
Using PS version 5.1.14393.5127
MSGraph version 1.0

When running a "get-mgdirectoryrole -all" command, PowerShell throws a non-specific error.

PS C:\> Connect-MgGraph -Scopes "RoleManagement.Read.Directory", "Directory.Read.All"
$roles = get-mgdirectoryrole -All
Welcome To Microsoft Graph!
get-mgdirectoryrole : One or more errors occurred.
At line:2 char:1
+ $roles = get-mgdirectoryrole -All
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgDirectoryRole_List1], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Graph.PowerShell.Cmdlets.GetMgDirectoryRole_List1

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

Please share the output of the following with us:
- `Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version`.
- `$PSVersionTable`.

**Comment by zealoususer** [comment]
Thank you for your response. Here is the output you requested:

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.5127
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.5127
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1



PS C:\> Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version

PS C:\> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

PS C:\> Install-Module microsoft.graph.identity.directorymanagement
WARNING: Version '1.17.0' of module 'Microsoft.Graph.Identity.DirectoryManagement' is already installed at 'C:\Program Files\WindowsPowerShell\M
odules\Microsoft.Graph.Identity.DirectoryManagement\1.17.0'. To install version '1.18.0', run Install-Module and add the -Force parameter, this
command will install version '1.18.0' in side-by-side with version '1.17.0'.

PS C:\> Install-Module microsoft.graph.authentication

PS C:\>

When I ran the original MS Graph commands, there was no output. I tried to install the DirectoryManagement module, but it indicated it was already installed. When I tried to install the authentication module, there was no output.

Mike Edwards


From: Peter Ombwa ***@***.***>
Sent: Tuesday, December 6, 2022 4:27 PM
To: microsoftgraph/msgraph-sdk-powershell ***@***.***>
Cc: Edwards, Mike ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoftgraph/msgraph-sdk-powershell] Get-mgdirectory role throws non-specific error (Issue #1662)

CAUTION: This email was sent from an EXTERNAL source. Use caution when clicking links or opening attachments.
________________________________

Thanks for bringing this to our attention.

Please share the output of the following with us:

  *   Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version.
  *   $PSVersionTable.

**Comment by peombwa** [comment]
Thanks for the output.

We are still missing the output of the loaded modules. Please provide us with the output of:
- `Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version` immediately after the error has occurred.
- `$error[0].exception`.

The error above can occur if you are not loading the correct version of the modules. i.e., ensure `Microsoft.Graph.Identity.DirectoryManagement` and `Microsoft.Graph.Authentication` are the same version. Version 1.18.0 is our latest release.

**Comment by zealoususer** [comment]
Apologies – here is the output.

***@***.***

Mike Edwards | Enterprise Directory Services| McKesson Technology | 678-853-3897
ISRM Services Intake Requests <https://app.smartsheet.com/b/form/e7067c6210bc4f2596c151fdcd88649c>


From: Peter Ombwa ***@***.***>
Sent: Friday, December 9, 2022 7:06 PM
To: microsoftgraph/msgraph-sdk-powershell ***@***.***>
Cc: Edwards, Mike ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoftgraph/msgraph-sdk-powershell] Get-mgdirectory role throws non-specific error (Issue #1662)

CAUTION: This email was sent from an EXTERNAL source. Use caution when clicking links or opening attachments.
________________________________

Thanks for the output.

We are still missing the output of the loaded modules. Please provide us with the output of:

  *   Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version immediately after the error has occurred.
  *   $error[0].exception.

The error above can occur if you are not loading the correct version of the modules. i.e., ensure Microsoft.Graph.Identity.DirectoryManagement and Microsoft.Graph.Authentication are the same version. Version 1.18.0 is our latest release.

**Comment by peombwa** [comment]
Thanks for the output!

It looks like you are importing both `1.18.0` and `1.17.0` of `Microsoft.Graph.Authentication` in the same PowerShell session. This will cause dll conflicts, hence the `One or more errors occurred.` error.

To resolve the issue:
- Update to the latest version `Update-Module Microsoft.Graph`.
- Import the right module version - `Import-Module Microsoft.Graph.Identity.DirectoryManagement -RequiredVersion 1.19.0`.

**Comment by zealoususer** [comment]
Thank you - that appears to have resolved the issue.

**Comment by peombwa** [comment]
Awesome! I'll close the issue.
