### ISSUE TITLE
New-MgChat : Failed to get license information for the user. Ensure user has a valid Office365 license assigned to them.

### ISSUE THREAD

**Issue by JackVp** [microsoftgraph/msgraph-sdk-powershell#1666]
Hello, I'm trying to start a chat and Im receiving "New-MgChat : Failed to get license information for the user. Ensure user has a valid Office365 license assigned to them.", account has M365 License, has api permission.
![image](https://user-images.githubusercontent.com/119893181/205731606-9f26da42-4239-4a7a-b242-93214a9103b6.png)

**Comment by PaulSIsaac** [comment]
How can this be closed? There is literally nothing in this?

**Comment by JulesVR** [comment]
Same issue
