### ISSUE TITLE
Get-MgConditionalAccessPolicy - Reauthenticating

### ISSUE THREAD

**Issue by Donovand4** [microsoftgraph/msgraph-sdk-powershell#167]
Hi All,
I ran the Get-MgConditionalAccessPolicy and authenticated using an in-private brower session but directly after that I execute the command with the conditionalaccessID. I received another authentication prompt. The time line between the two commands is approximately seconds.

Get-MgConditionalAccessPolicy                                                                                                                                                                                        To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CODE to authenticate.

Id                                   CreatedDateTime Description DisplayName                    ModifiedDateTime State
--                                   --------------- ----------- -----------                    ---------------- -----

Get-MgConditionalAccessPolicy -ConditionalAccessPolicyId *******                                                                                                                        To sign in, use a web browser to open the page https://microsoft.com/devicelogin

**Comment by peombwa** [comment]
@Donovand4 What version of `Connect-Graph` are you using? Run `Get-Command Connect-Graph` to get the version.

**Comment by Donovand4** [comment]
Connect-Graph - 0.2.0

**Comment by peombwa** [comment]
Try upgrading to version 0.7.0. We've made some improvements to Connect-Graph since 0.2.0 - ` Update-Module -Name Microsoft.Graph`
