### ISSUE TITLE
confused about "clientId" pass in get-ms0authPermissiongGrant ?

### ISSUE THREAD

**Issue by esdccs1** [microsoftgraph/msgraph-sdk-powershell#1682]
Hello,

I notice when I use 
`get-ms0authPermissiongGrant  -All -Filter "clientId eq 'XXXXXXX-XXXX-XXXX-XXXXXXXXX'"`

that the clientId is the ServicePrincipal's AAD ObjectID.... 
but I would expect clientID to mean `the App Registration's App ID` ? below with "Client" word 

![aad_getoauth2_permission](https://user-images.githubusercontent.com/98773628/207637827-5e758c3f-d66d-45c5-bb04-99a6cc31a07b.png)

**Comment by peombwa** [comment]
Are you using `Get-MgOauth2PermissionGrant` command? If so, see [Microsoft Graph API reference](https://learn.microsoft.com/en-us/graph/api/resources/oauth2permissiongrant?view=graph-rest-1.0#properties) for what each property of `oAuth2PermissionGrant` resource type corresponds to.

In this case, according to the API, `clientId` is equal to:
> The id of the client [service principal](https://learn.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0) for the application which is authorized to act on behalf of a signed-in user when accessing an API. Required. Supports $filter (eq only).

Please open a feature request at https://developer.microsoft.com/en-us/graph/support to provide feedback to the API owner on the property name. This module supports property names as provided by the API.
