### ISSUE TITLE
Setting specific Password for ServicePrincipal

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoftgraph/msgraph-sdk-powershell#1689]
Hi
Is there any way, to set a Password with a given value like we were able in MSOnline

`New-MsolServicePrincipalCredential -AppPrincipalId $appId -Type Password -Usage Verify -Value $newClientSecret   -StartDate $dtStart  -EndDate $dtEnd` 

or AAD-Module

`New-AzureADServicePrincipalPasswordCredential -ObjectId $App.ObjectId -StartDate $StartDate -EndDate $EndDate -Value "MyNewClientSecretGoesHere"`

The current migration-path directs to Add-MgServicePrincipalPassword, but that does not accept a given Value for the Secret. 

But we do have needs for eg renewing/extending existing secrets

**Comment by peombwa** [comment]
@LeopoldLerch, with Microsoft Graph API, the `addPassword` method will return a `secretText` property containing an AAD generated strong password. See the example at https://learn.microsoft.com/en-us/graph/api/serviceprincipal-addpassword?view=graph-rest-1.0&tabs=powershell#request.
> If successful, this method returns a 200 OK response code and a new [passwordCredential](https://learn.microsoft.com/en-us/graph/api/resources/passwordcredential?view=graph-rest-1.0) object in the response body. The secretText property in the response object contains the strong passwords generated by Azure Active Directory that are 16-64 characters in length. There is no way to retrieve this password in the future.

In your case, the command will be something like:
``` powershell
$PasswordCredential = @{
    DisplayName = "Password friendly name"
    EndDateTime = "2022-12-18T00:00:00Z"
    StartDateTime = "2022-12-15T00:00:00Z"
}

$SpPassword = Add-MgServicePrincipalPassword -ServicePrincipalId $appId -PasswordCredential $PasswordCredential
```

**Comment by LeopoldLerch** [comment]
@peombwa Thanks, but thats not what I asked for. I know, that I will get a Secret when adding a new Password via the new Graph-SDK.  

But my problem is, that I have to PROVIDE the new Secret that should be added, like I was able in the previous SDKs.

I need to be able to set the Secret to an specific one or being able to extend the existing Secret. Getting a completely new Secret does not fit to my current needs.

**Comment by peombwa** [comment]
Microsoft Graph API is different from MSOL and AzureAD Graph API. Providing your own application password is not supported by Microsoft Graph API or even Azure Portal.

See https://learn.microsoft.com/en-us/graph/api/resources/passwordcredential?view=graph-rest-1.0#properties
>secretText = **Read-only;** Contains the strong passwords generated by Azure AD that are 16-64 characters in length. The generated password value is only returned during the initial POST request to [addPassword](https://learn.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0). There is no way to retrieve this password in the future.

I'd recommend you open a service feature request at https://developer.microsoft.com/graph/support.

**Comment by peombwa** [comment]
Closing as not supported by the service.

The service will generate the secret text when using:
``` powershell
$PasswordCredential = @{
    DisplayName = "Password friendly name"
    EndDateTime = "2022-12-18T00:00:00Z"
    StartDateTime = "2022-12-15T00:00:00Z"
}

$SpPassword = Add-MgServicePrincipalPassword -ServicePrincipalId $appId -PasswordCredential $PasswordCredential
```

**Comment by captainhook** [comment]
@LeopoldLerch did you find a solution to this?
I have some 'legacy' systems which unfortunately don't support longer than 20 characters for password/secret, so I need to find a solution. Thanks!

**Comment by LeopoldLerch** [comment]
No, had to work with the new provided passwords. You might be able to use a certificate and add the path to the certificate in the field. (maybe that´s lesser than 20 characters). however, just an idea.
