### ISSUE TITLE
New-MgGroupMemberByRef : Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by maxall93** [microsoftgraph/msgraph-sdk-powershell#1695]
Getting this issue no matter what I try, have seen others post with the same issue on here and around the internet but not seen anyone with a fix ?

I've updated to Microsoft.Graph 1.19.0

If I run Get-MgContext, it says I have the correct permissions:

```
PS C:\Git> Get-MgContext

ClientId              : 14d82eec-204b-4c2f-....
TenantId              : 593eb8de-b372-4efe-...
CertificateThumbprint :
Scopes                : {Application.Read.All, Application.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All...}

PS C:\Git> $Scopes = Get-MgContext
PS C:\Git> $Scopes.scopes
Application.Read.All
Application.ReadWrite.All
Directory.Read.All
Directory.ReadWrite.All
Group.ReadWrite.All
GroupMember.ReadWrite.All
openid
profile
User.Read
User.Read.All
User.ReadWrite.All

```

But if I try and run New-MgGroupMemberByref, I get the below error

```
PS C:\Git> New-MgGroupMemberByRef -GroupId $groupId -BodyParameter $params
New-MgGroupMemberByRef : Insufficient privileges to complete the operation.
```

the $groupId is the Object ID of a non role assignable AAD group. When I read the MS Documentation at: https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=powershell it says I need any of these permissions, which I do have as per code snippet above:

```
Permission type | Permissions (from least to most privileged)
-- | --
Delegated (work or school account) | GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All

```

Am I missing something ? I have tried using an App Registration with the correct Graph roles assigned and Admin consented, but the same issue.

**Comment by peombwa** [comment]
Thanks for following up on this.

Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support as this is a service issue. `Insufficient privileges to complete the operation` comes is a service response. You can see this in the `-Debug` log.

In your ticket/question, please include the `requestId` and `date` of the affected calls. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details. 

We may not be the best place to answer some queries that are tied to the functionality of the API.

**Comment by peombwa** [comment]
Closing as a service issue. Service issues should be channeled to https://developer.microsoft.com/en-us/graph/support.
