### ISSUE TITLE
Issues with the Microsoft Graph PowerShell SDK V2 Proposal

### ISSUE THREAD

**Issue by 12Knocksinna** [microsoftgraph/msgraph-sdk-powershell#1698]
Have had quite a conversation on this topic with people like Fabian Williams, Darrel Miller, and Maisa Rissi. I see trouble ahead and wrote up my feelings in the article below. I hope the Graph team makes it a lot easier for customers to continue using the SDK and avoids the need to update cmdlet names in scripts that have already been written. Don't erect barriers to adoption when they're not needed!

**_Flaws in the Plan for Microsoft Graph PowerShell SDK V2_**

Microsoft has released the first public preview of the Microsoft Graph PowerShell SDK V2.0. Although the new version delivers some welcome functionality, it contains some contentious proposals such as dividing the SDK into V1.0 and beta modules and using different names for the beta cmdlets. It would be nice if Microsoft fixed some of the basic group and user cmdlets before they imposed more work on PowerShell developers.

https://office365itpros.com/2022/12/20/microsoft-graph-powershell-sdk-v2/

**Comment by peombwa** [comment]
Thanks for the valuable feedback @12Knocksinna!

We will review the concerns raised in the blog post to see if we can provide tools/revisions to aid in migration from v1 to v2 while the module is still in preview.

Keep sharing your feedback on v2 preview.

**Comment by CarolKigoonya** [comment]
Hello @12Knocksinna , my name is Carol, the new MS Graph PowerShell PM. We have identified you as one of the recipients of an [early adopter program](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-early-adopter-recognition-program/). Please share your email address with me so that we can send the badge to you.

**Comment by 12Knocksinna** [comment]
***@***.***

**Comment by peombwa** [comment]
Closing as there is an existing discussion for this at https://github.com/microsoftgraph/msgraph-sdk-powershell/discussions/1705 and v2 is now GA.
