### ISSUE TITLE
need sample for connecting to workbook in team site

### ISSUE THREAD

**Issue by mgreenegit** [microsoftgraph/msgraph-sdk-powershell#170]
Request for a sample:
Connect to graph
Get ID for Team
List Excel workbooks stored in team site
Get data from tab of workbook 
[AB#7443](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7443)

**Comment by maisarissi** [comment]
API reference documentation now has a PowerShell tab that contains code snippets based on the HTTP samples as well as Graph Explorer.
Also, we have now documented the Authentication module: https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0
