### ISSUE TITLE
Adding Notification Email to Body of Add-MgServicePrincipalTokenSigningCertificate

### ISSUE THREAD

**Issue by AFK-Python** [microsoftgraph/msgraph-sdk-powershell#1701]
Running this [tutorial](https://learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?tabs=powershell%2Cpowershell-script#activate-the-custom-signing-key) to try to automate SAML SSO to my use case.

I was wondering if it was possible to configure the `SAML Certificates` section, specifically the `Token signing certificate` with a notification email parameter. There doesn't seem to be anything in the docs for this. I tried adding it as a parameter to the tutorial code (listed below), but it seemed to do nothing.

Tutorial code:

```
Import-Module Microsoft.Graph.Applications

$params = @{
	DisplayName = "CN=AWSContoso"
	EndDateTime = [System.DateTime]::Parse("2024-01-25T00:00:00Z")
}

Add-MgServicePrincipalTokenSigningCertificate -ServicePrincipalId $servicePrincipalId -BodyParameter $params
```

I am not super familiar with configuring SAML certificates - is this field even necessary for a trust to work? It does not state `Optional` in the portal like other fields, but rather `Missing`. This indicates to me that I likely need it. If it is necessary and this cmdlet does not support it, are there alternative solutions to adding this field programmatically?

Again, happy to provide an extra information needed.

**Comment by peombwa** [comment]
Thanks for following up on this.

Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from subject matter experts as this is an API question.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

**Comment by AFK-Python** [comment]
Once again, appreciate the rapid response! Will raise the issue there. Cheers!

**Comment by peombwa** [comment]
Closing as API question.
