### ISSUE TITLE
Can't retrieve Bitlocker Recovery Keys

### ISSUE THREAD

**Issue by TiredFindingUserName** [microsoftgraph/msgraph-sdk-powershell#1709]
Trying to retrieve Bitlocker keys with no success.
Issue #1 - the process can't be scripted (no application-based permission, delegated only). Why?
Issue #2 - "key" value does not exist in Graph Explorer and it is empty running Get-MgInformationProtectionBitlockerRecoveryKey.

For #2 - Azure AD does show the key

**Comment by peombwa** [comment]
Thanks for following up on this.

For issue 1: This is an API question. Please open a question/feature request at https://developer.microsoft.com/en-us/graph/support.

For issue 2: The [API reference](https://learn.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-1.0#properties) says `key` is returned only on $select. Use `$select` or `-Property Key` to have the service return the property.
> The BitLocker recovery key. Returned only on $select. Not nullable.

**Comment by peombwa** [comment]
Closing the issue as this repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API. Please post API related queries to https://developer.microsoft.com/en-us/graph/support.
