### ISSUE TITLE
set-mgdevicemanagementdeviceconfiguration throws NullReferenceException when successful

### ISSUE THREAD

**Issue by read-0nly** [microsoftgraph/msgraph-sdk-powershell#1710]
Like the title says - here's the way I've handled it in my own project

```powershell
connect-mggraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"
$devconf = (read-host "Device Config ID")
$group = (read-host "AAD Group Obj ID")
$params=@{
	"assignments" = @(
		@{
			"@odata.type"="#microsoft.graph.deviceConfigurationAssignment"
			"id"=(New-Guid).ToString()
			target=@{
				"@odata.type"="#microsoft.graph.groupAssignmentTarget"
				"groupId"=$group
			}
		}
	)
}
set-mgdevicemanagementdeviceconfiguration -deviceconfigurationid $devconf -BodyParameter $params -erroraction silentlycontinue
if($error[0].Exception.GetType() -eq [System.NullReferenceException]) {
	write-host "Probably worked!" -foregroundcolor green
}else{
	write-host $error[0] -foregroundcolor red
}

```

The issue seems to be born from an apparent mismatch between how graph is documented and how it actually behaves - per [the assign action article](https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileapp-assign?view=graph-rest-1.0) the expectation is that the endpoint will return the assignment details in the response. But if you test it with graph explorer, you get a 200 success, but no response body. 

From what I understand, the cmdlet, expecting a response body and getting a null response, throws the nullref.

After a cursory glance at things, I think the solution (at least, from a ps side of things) would be to return early if collectionOfDeviceConfigurationAssignment is null in onOk - it looks like most of this code is autogen'd, not sure how to translate this to autorest config. I wasn't able to test this solution.

**Comment by read-0nly** [comment]
Just to make it easier to test, here's my modules folder
[Modules.zip](https://github.com/microsoftgraph/msgraph-sdk-powershell/files/10282627/Modules.zip)

**Comment by peombwa** [comment]
Thanks for bringing this to our attention and the detailed repro steps!

This is a service issue as the API returns a 200 status code with no message body in the response. As you have noted, the API should ideally return a 204 (No content) status code as described in the [API reference](https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileapp-assign?view=graph-rest-1.0). The current response status code goes against [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-200-ok):
> Aside from responses to CONNECT, a 200 response is expected to contain message content unless the message framing explicitly indicates that the content has zero length. If some aspect of the request indicates a preference for no content upon success, the origin server ought to send a 204 (No Content) response instead.

I'll surface this to the API owner for the response status code to be fixed. I'd also recommend you open a ticket/question at https://developer.microsoft.com/en-us/graph/support to bring it to the attention of the API owner. In your ticket/question, please include the `requestId` and `date` of the affected calls. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details.

**Comment by peombwa** [comment]
Tracking issue in ICM under #357654803.
