### ISSUE TITLE
update-mggroup -members

### ISSUE THREAD

**Issue by tikesavage** [microsoftgraph/msgraph-sdk-powershell#1711]
MSFT documentation is useless and links back to the same article. https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/update-mggroup?view=graph-powershell-1.0
  its using a filter and not specify whether its expecting Object ID, UPN or Odata.

this is for automation  i have that takes multiple groups (using object ID) and a criteria for users in scope.
i have a very  complex user query against AD. which stores the users in scope in an array.  based on what the cmdlet takes i will either for each loop or pass the entire array. Property.
update-MgGroup -Identity $group.ObjectID -Members $_.userPrincipalName}

what does the -members parameter expect?  please provide single user and multi user example.

**Comment by peombwa** [comment]
See the example at https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=powershell#example-2-add-multiple-members-to-a-group-in-a-single-request for an example on how to add members to a group in bulk.
``` powershell
$params = @{
	"Members@odata.bind" = @(
		"https://graph.microsoft.com/v1.0/directoryObjects/{User-id}"
		"https://graph.microsoft.com/v1.0/directoryObjects/{User-id}"
		"https://graph.microsoft.com/v1.0/directoryObjects/{User-id}"
	)
}
Update-MgGroup -GroupId $groupId -BodyParameter $params
```

We strongly encourage customers to use the API reference as their first starting point when trying to figure out how to consume resources through Microsoft Graph API. This module is just a wrapper for the APIs available through Microsoft Graph. The commands call the APIs as is. We've provided PowerShell examples for most of the API examples in the API reference doc to get you started with consuming the API resources in PowerShell. You can also post/find answers to questions on how to use the API/commands at https://learn.microsoft.com/en-us/answers/products/graph.


For 
> what does the -members parameter expect? please provide single user and multi user example.

`-Members` on `Update-MgGroup` has been removed from our [new v2.x preview](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview1) module. Customers cannot add members to a group directly using `-Members`.
![image](https://user-images.githubusercontent.com/7061532/209241019-f75df5e1-86f0-401c-99aa-0a4406bcd12c.png)

Members can only be added to a group using `New-MgGroupMemberByRef` or in bulk via OData bind as shown in the API reference.

We are tracking adding a PowerShell friendly way of using OData bind in #1673.

**Comment by tikesavage** [comment]
Looking at the documentation for New-MgGroupMemberByRef cmdlet. This  cmdlets aswell is asking for Object ID. 
These really need to accept upn;  User Object ID are not written back to On-Prem AD User objects, and there is no plan to setup immutable IDs in AAD. 
having to do a get-mguser then concatenate each Object ID onto "https://graph.microsoft.com/v1.0/directoryObjects/{User-id}"  then add to an Array, is going to add massive over head when when i am looping through 100k users for 100s of AAD groups.

can you please add the ability for the cmdlet to directly accept UPNs & accept arrays of UPNs or Object IDs. I hope you can see the issue with the overhead.

**Comment by peombwa** [comment]
I'd recommend you open feature request at https://developer.microsoft.com/en-us/graph/support for the API owner to consider your scenario as the API does not support it. Once supported by the API, you should be able to use the UPN as a substitute for the objectId. This module simply calls the API as it.

Closing as service feature request.
