### ISSUE TITLE
New-MgGroup team property

### ISSUE THREAD

**Issue by Powersquids** [microsoftgraph/msgraph-sdk-powershell#1712]
I've been playing around with creating unified groups with teams and came across a slight snag. Google has not been my friend for an answer either. 

$TeamParams = @{
"Template@odata.bind" = "https://graph.microsoft.com/v1.0/teamsTemplates('standard')"    
IDisplayName = "Testing"
IDescription = "Test"
}

new-mggroup -displayname "testing" `
 -grouptypes "Unified" `
 -mailnickname "testing" `
 -mailenabled:$true `
 -SecurityEnabled:$true `
 -Team $TeamParams

New-MgGroup_CreateExpanded: C:\Users\Zacharry\OneDrive\Desktop\Scripts\Testmggroup.ps1:9:1
Line |
   9 |  new-mggroup -displayname "testing testers2" `
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The following properties cannot be set in the initial POST request. Please set them in a subsequent PATCH request: team

I get the feeling that it's something dumb, but I'm not seeing it. 

I can create the group and unify them with new-mggroup after. But not during.

**Comment by peombwa** [comment]
You cannot create a team when creating a group. The [create group API](https://learn.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http) says:
> Note: Although Microsoft Teams is built on Microsoft 365 groups, you can't currently create a team via this API. You can use the other group APIs to manage a team that has been created in the Microsoft Teams UI.

To create a team from a group, you'll need to first create a group, wait ~15 minutes, then [create a team from the group](https://learn.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=powershell#example-4-create-a-team-from-group) you just created. See the explanation at https://learn.microsoft.com/en-us/graph/teams-create-group-and-team.

`-Team` is generated in error and will be removed in `v2.x` of the module.

**Comment by Powersquids** [comment]
Hey @peombwa, 

I totally followed that part of the API documentation. Which is why I'm confused as to why the '-team' flag is even available. I'd understand if it started like a sleep or another process or something but the fact that it's available in 'new-mggroup' is, well, counter intuitive and should be addressed.

**Comment by peombwa** [comment]
`-team` is currently surfaced in the OpenAPI document, used to generate this module, as a property that can be modified.

I've opened an issue to have this resolved at https://github.com/microsoft/OpenAPI.NET.OData/issues/325. The fix will be available as part of v2.

**Comment by peombwa** [comment]
Issue being tracked in https://github.com/microsoft/OpenAPI.NET.OData/issues/325.
