### ISSUE TITLE
Connect-MgGraph - How is ClientId defined automatically?

### ISSUE THREAD

**Issue by WayneAASPLLC** [microsoftgraph/msgraph-sdk-powershell#1716]
How does Client ID get defined when you never have to enter it to connect the MsGraph?
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Authentication/Authentication/Cmdlets/ConnectMgGraph.cs

**Comment by RayGHeld** [comment]
The app registration for MS Graph PowerShell SDK resides in the Microsoft Tenant.  You will have a service principal in your enterprise apps for the SDK.  The application itself knows its client id, hence it is not required when you authenticate with it.

**Comment by WayneAASPLLC** [comment]
This is good info; do you know where in the src folder here in github this is programmed?

**Comment by peombwa** [comment]
@WayneAASPLLC, as answered by RayGHeld, the client id can be found in your tenant as an enterprise app. Alternatively, you can find the client id by using `Get-MgContext`.

Why do you need access to the client id in the source code?

**Comment by WayneAASPLLC** [comment]
I have learned that the client ID is stored somewhere on the machine which is all I needed to know.
I was trying to get rid of needing one completely in C# since it is always required for public clients.
I thought PowerShell may have been doing this somehow, but instead it is just storing it somewhere.
