### ISSUE TITLE
Question: How to add user to directory role

### ISSUE THREAD

**Issue by bergmeister** [microsoftgraph/msgraph-sdk-powershell#172]
There is  `Get-MgDirectoryRoleMember` cmdlet but not something like a `New-MgDirectoryRoleMember` or `Add-MgDirectoryRoleMember` cmdlet to add role members to a directory role.
I couldn't figure out if it is possible if and how to add members to a directory role. 
[AB#7444](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7444)

**Comment by MIchaelMainer** [comment]
This is an issue for openapi.net.odata.

**Comment by peombwa** [comment]
This is now supported via `New-MgDirectoryRoleMemberByRef` and can be use like this:
``` powershell
New-MgDirectoryRoleMemberByRef -DirectoryRoleId $DirectoryRoleId `
    -AdditionalProperties @{ "@odata.id" = "https://graph.microsoft.com/v1.0/directoryObjects/$UserId" }
```

[Docs Ref](https://docs.microsoft.com/en-us/graph/api/directoryrole-post-members?view=graph-rest-1.0&tabs=http#example-1-add-a-new-member-to-a-directory-role-using-role-objectid)

**Comment by peombwa** [comment]
Closing since it has been resolved.

**Comment by JustinGrote** [comment]
@peombwa maybe add a DOC TODO to add your usage to the examples, I couldn't make heads or tails how to use this and had to search for this issue to figure it out :)
