### ISSUE TITLE
 Update-MgUser -updating the user's country  doe not update the CountryorRegion in Exchange Online

### ISSUE THREAD

**Issue by nikki-c** [microsoftgraph/msgraph-sdk-powershell#1727]
If I update the user's country for example  `Update-MgUser -UserId '173cbdb4-5251-4652-8437-bab680c70834' -Country France` then the country attribute is not being updated in Exchange Online. 

When I run `Get-Recipient` is shows that the CountryorRegion as the United States whereas `Get-MgUser` shows the country as France

![image](https://user-images.githubusercontent.com/69439002/210185091-70a4c62b-df7c-455f-9d9b-bdded015a5bb.png)

This causes confusion as if i create an Azure AD Dynamic group based on a country = France then the user in the Group. However, if I create a Purview dynamic Adaptive scope based on a country = France then the user is not in the scope because Adaptive scopes are using the CountryorRegion in Exchange Online which shows the user in United States as the attribute was not updated.

If I update the country in Exchange Online it is also updated in Azure AD

**Comment by peombwa** [comment]
Thanks for following up on this.

Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support as this is a service issue. This looks like a synchronization issue between Microsoft Graph API and Exchange Online.

This repository is intended for issues related to the functionality of the module. We may not be the best place to answer some queries that are tied to the functionality of the API.
