### ISSUE TITLE
get-mgchat bug?

### ISSUE THREAD

**Issue by ansarm** [microsoftgraph/msgraph-sdk-powershell#173]
So I am running get-mgchat to list all my chats in teams and it's returning a graph API error.

After cracking open the session with fiddler I notice that get-mgchat is calling /beta/chats, when it should be calling /beta/me/chats.

I am using graph powershell 0.2.1

**Comment by MIchaelMainer** [comment]
Please pass in the userid via `get-mguserchat -userid` using a upn or user id.
