### ISSUE TITLE
`Query option 'Expand' is not allowed` on Teams-related queries

### ISSUE THREAD

**Issue by Occhioverde** [microsoftgraph/msgraph-sdk-powershell#1732]
Good morning.
I'm not sure whether this problem is caused the Microsoft.Graph module or by Graph itself, so I apologize in advance in case this is the wrong place to ask this question.
Today I was trying to optimize a reporting script that I wrote to keep track of the various users, groups, mailboxes, and teams in a client's tenant and I noticed that I can reduce the number of API call by using the `-ExpandProperty` parameter, which works quite well to get group members along with the group list itself but throws the `The query specified in the URI is not valid. Query option 'Expand' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.` error when trying to execute `$Teams = Get-MgTeam -All -ExpandProperty Channels`.
While searching the Internet for this error message, I found out [on Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/1001444/query-option-39expand39-not-working-on-teams-chann.html#answer-1001598) that "not all properties or resources support $expand" and thought that team.channels might just be one of them, but in this case I'm curious to know how can I populate it, since I find quite strange for the schema to include an empty property that can't be filled.
In case it can be useful, I'm using the Micorsoft.Graph module version 1.19.0 with the Beta profile on PowerShell Core 7.2.3 on a NixOS machine.
Thank you in advance for your help.
Have a nice day.

**Comment by peombwa** [comment]
The reason for the error message is similar to the answer to the Q&A question you've shared above. The API does not support `$expand` on `Channels`.

Please use the [list team channels API/Command](https://learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&tabs=powershell#example-1-list-all-channels) to get a collection of channels associated with your teams.

You can also open/upvote on a service feature request at https://developer.microsoft.com/en-us/graph/support to have your scenario supported by the API.

**Comment by peombwa** [comment]
Closing as a known service limitation.
