### ISSUE TITLE
Connect-Graph in 21vianet Azure AD reported AADSTS700016

### ISSUE THREAD

**Issue by sscchh2001** [microsoftgraph/msgraph-sdk-powershell#1735]
Command to execute:
Connect-Graph -TenantId "<tenantid>" -Environment China

Error received in prompted page after authentication:
AADSTS700016: Application with identifier '14d82eec-204b-4c2f-b7e8-296a70dab67e' was not found in the directory 'CSS Mooncake'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. 

When I tried to register the application with New-AzureADServicePrincipal, I got followig error, which indicates that the AAD application used by MgGraph module is not existed in 21vianet AAD:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PS C:\Users\username\Desktop> New-AzureADServicePrincipal -AppId '14d82eec-204b-4c2f-b7e8-296a70dab67e'
New-AzureADServicePrincipal : Error occurred while executing NewServicePrincipal
Code: Request_BadRequest
Message: The appId '14d82eec-204b-4c2f-b7e8-296a70dab67e' of the service principal does not reference a valid
application object.
RequestId: fd7d47db-111c-4913-9cb2-3e2ccf292b97
DateTimeStamp: Fri, 06 Jan 2023 02:44:05 GMT
Details: PropertyName  - appId, PropertyErrorCode  - NoBackingApplicationObject
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ New-AzureADServicePrincipal -AppId '14d82eec-204b-4c2f-b7e8-296a70dab ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADServicePrincipal], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.NewServ
   icePrincipal
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Please make sure that this application has been configured in 21vianet AAD, so that the users can sign-in the module correctly with the default application.

**Comment by peombwa** [comment]
This is a known limitation with the module that's documented at https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-get-mgenvironment.
> Globally registered apps don't replicate to Azure China. You'll need to register your own applications in Azure China and use them when connecting to Microsoft Graph.

Customers in 21vianet AAD are encouraged to create their own app id and use it with the module via - `Connect-MgGraph -ClientId $appId -Environment China`.

We are tracking adding support for 21vianet in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/802.
