### ISSUE TITLE
Get-MgUser always returns empty Manager and Authentication properties

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#1737]
`Get-MgUser` returns the `Manager` and `Authentication` properties. They are always empty, even if you explicitly specify them using the `-Property` parameter. There is no difference if you use the `-ExpandProperty` and the `-Select` parameters.

How can we get their values?

**Comment by peombwa** [comment]
Thanks for following up on this.

`Manager` is a relationship (nav property), and it can be retrieved via `$expand` (`-ExpandProperty`) or https://learn.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=powershell. According to the [entity reference docs](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#relationships), `Manager` is :
> The user or contact that is this user's manager. Read-only. (HTTP Methods: GET, PUT, DELETE.). Supports $expand.

`Authentication` on the other hand fails with an "UnknownError" code on `$expand`. This seems to suggest that the API does not support `$expand` or the API is broken. Unfortunately, this is not documented in the API reference.

I'd suggest you open a question for the API owner at https://developer.microsoft.com/en-us/graph/support to get assistance from subject matter experts on why you can't expand on `Authentication`. This behavior is tied to the API and is not specific to the module (It can be repro'd via [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=me%3F%24expand%3Dauthentication&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com)).

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

**Comment by peombwa** [comment]
Closing as service issue. Please post the question at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner.
