### ISSUE TITLE
Error on "Connect-MgGraph" command

### ISSUE THREAD

**Issue by LilianJude** [microsoftgraph/msgraph-sdk-powershell#1738]
Hi ! I installed the msgraph module with this command :
`Install-Module Microsoft.Graph`

But when I execute the command to connect, I have this error :
```
Connect-MgGraph : Impossible de charger le type 'Microsoft.Identity.Client.OsCapabilitiesExtensions' à partir de l'assembly 'Microsoft.Identity.Client, Version=4.21.0.0, Culture=neutral, 
PublicKeyToken=0a613f4dd989e8ae'.
```

Anyone can help me to resolve this error ?

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

The error seems to suggest a dll conflict with a module that's using an older version of Microsoft.Identity.Client. Our module uses `Microsoft.Identity.Client` version ` 4.29.0`:
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/46f874ad36092430ad3f194bb5fdfe7b61c46d08/src/Authentication/Authentication.Core/Microsoft.Graph.Authentication.Core.csproj#L11

Could you please share more info on:
1. Loaded assemblies before and after running Import-Module:
``` powershell
# Provide output of [System.AppDomain]::CurrentDomain.GetAssemblies() here.

```

2. Loaded modules before and after running Import-Module: 
``` powershell
# Provide output of Get-Module here.

```

3. Error record of the failed command - `Get-Error -Newest 1`:
``` powershell
# Provide output of Get-Error -Newest 1 here.

```

4. Your version table:
``` powershell
# Provide output of $PSVersionTable here.

```

5. Detailed repro steps, if any:
``` powershell
# Provide repro steps here.

```
