### ISSUE TITLE
It appears that 2.0.0-preview2 has removed `-SingleValueExtendedProperties` parameter from cmdlets in Microsoft.Graph.Mail 

### ISSUE THREAD

**Issue by gmatev** [microsoftgraph/msgraph-sdk-powershell#1743]
Support for `SingleValueExtendedProperties` seems to have been dropped from New-MgUserMessages and New-MgUserMailFolderMessages in 2.0.0-preview2 compared to 1.19.0. The parameter (including the ability to specify it in `bodyParams` appears to no longer be available. 

Was this intentional and what is the path forward for folks who rely on setting `SingleValueExtendedProperties` for advanced use cases.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention!

I've traced the issue to how the property is declared in the service metadata, our sole source of truth. The service metadata currently says that the property can only be created via `New-MgUserMessageSingleValueExtendedProperty`, which is wrong.

In v2.x, we are using a stricter logic to surface modifiable properties as parameters to reduce blot. As part of this logic, we are removing contained nav properties as they are not modifiable directly on a resource.

I've opened an in the metadata repro at https://github.com/microsoftgraph/msgraph-metadata/issues/246 to have this resolved. In the meantime, you can use `-AdditionalProperties ` to add the property to the resource being created:

``` powershell
$SingleValueExtendedProp = @{
    Id = "String {66f5a359-4659-4830-9070-00040ec6ac6e} Name Fun"
    Value = "Food"
}

New-MgUserMessage -UserId $UserId -AdditionalProperties @{ SingleValueExtendedProperties = @($SingleValueExtendedProp) } -Debug
```

**Comment by gmatev** [comment]
@peombwa Thank you! This helps.

**Comment by peombwa** [comment]
Closing as fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview6
