### ISSUE TITLE
Get-MgUser throws ProfileAccessDeniedException

### ISSUE THREAD

**Issue by RDavis3000** [microsoftgraph/msgraph-sdk-powershell#1747]
I'm trying to follow the quickstart at https://learn.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0

I have used the interactive authentication process and my user is the Global Admin.

I've tried various combinations of scopes but I keep getting the ProfileAccessDeniedException:

`PS C:\Users\Richa> Find-MgGraphCommand -command Get-MgUser | Select -First 1 -ExpandProperty Permissions

Name IsAdmin Description FullDescription

Directory.Read.All True Read directory data Allows the app to read data in your organization's director…
Directory.ReadWrite.All True Read and write directory data Allows the app to read and write data in your organization'…
User.Read.All True Read all users' full profiles Allows the app to read the full set of profile properties, …
User.ReadBasic.All False Read all users' basic profiles Allows the app to read a basic set of profile properties of…
User.ReadWrite.All True Read and write all users' full profiles Allows the app to read and write the full set of profile pr…

PS C:\Users\Richa> Connect-MgGraph -Scopes "User.Read.All,Group.ReadWrite.All, Directory.Read.All,Directory.ReadWrite.All,User.ReadBasic.All,User.ReadWrite.All,Directory.AccessAsUSer.All"
Welcome To Microsoft Graph!
PS C:\Users\Richa> Get-MgUser
Get-MgUser_List1: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.
PS C:\Users\Richa>`

Can anyone tell me what I am doing wrong?

EDIT:

Get-MgContext shows that no scopes have been set.

PS C:\Users\Richa> Get-MgContext

ClientId              : xxx
TenantId              :
CertificateThumbprint :
Scopes                :
AuthType              : Delegated
AuthProviderType      : InteractiveAuthenticationProvider
CertificateName       :
Account               :
AppName               :
ContextScope          : CurrentUser
Certificate           :
PSHostVersion         : 7.3.1

No idea where I am going wrong!

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

The error message points to a request being made without the required permissions. Can you try performing the same [HTTP request(s)](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http) within [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to see if you're running into the same issue? I'm not able to reproduce this behavior using the latest version of the module (`1.20.0`).

Could you please share more info on:
1. `Date` and `request-Id` of the failing request. See [troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details:
``` powershell
# Provide date and request-id here.

```

2. Loaded modules: 
``` powershell
# Provide output of Get-Module here.

```

3. Error record of the failed command - `Get-Error -Newest 1`:
``` powershell
# Provide output of Get-Error -Newest 1 here.

```

4. Your version table:
``` powershell
# Provide output of $PSVersionTable here.

```

**Comment by peombwa** [comment]
Also, please specify the bare minimum permissions/scopes you need to make the call in `Connect-MgGraph -Scopes`. In this case, `User.ReadBasic.All` should be sufficient to read basic profile properties of all users in your tenant.
