### ISSUE TITLE
[v2.x] Connect-MgGraph's -CertificateSubjectName used to be -CertificateName

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#1748]
In v1.x, Connect-MgGraph has the -CertificateName parameter (and its alias -CertificateSubject).
In v2.x, Connect-MgGraph has the -CertificateSubjectName parameter (and its alias -CertificateSubject).

This is unnecessary (and undocumented) breaking change. If you want the new name for that parameter, the old one should be just added as another parameter alias. The new -CertificateSubjectName parameter should have 2 aliases: -CertificateSubject and -CertificateName.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

The parameter name change was made to align with X509Certificate2's SubjectName property (subject distinguished name), which is what customers provide via `-CertificateSubjectName`.

I agree on adding an alias for `-CertificateName` to provide backward compatibility with v1.x. We will add the alias in the next update to v2.x.

**Comment by peombwa** [comment]
Closing as resolved.

The alias is now available as part https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview4.
