### ISSUE TITLE
Example not working due to unsupported functonality.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1749]
The PowerShell example below does not work since the -Count and ConsistencyLevel parameters are not supported when fetching a single item.
`Get-MgUser -UserId $userId -ExpandProperty "manager(`$levels=max;`$select=id,displayName)" -Property "id,displayName" -CountVariable CountVar -ConsistencyLevel eventual `

Example 2 on [this page](https://learn.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=powershell).

**Comment by peombwa** [comment]
The example goes against [OData's `$count` guidance](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount).

According to OData:
> The $count system query option with a value of true specifies that the total count of items within a collection matching the request be returned along with the result.
>
> Example 56: return, along with the results, the total number of products in the collection
> GET http://host/service/Products?$count=true
>
> The count of related entities can be requested by specifying the $count query option within the $expand clause.
> Example 57:
> GET http://host/service/Categories?$expand=Products($count=true)

> The $count system query option ignores any [$top](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop), [$skip](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip), or [$expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) query options, and returns the total count of results across all pages including only those results matching any specified [$filter](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter) and [$search](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionsearch).

The example on the other hand uses $count on `/me` (alias for `/users/{user-id}`), which goes against the above OData guidance. This results in our clients not generating a `Count` parameter for the example. Count parameter is only supported on APIs/commands that return a collection.

We will follow up with the API owner to have the HTTP example corrected.

**Comment by peombwa** [comment]
Merging issue with #1792.
