### ISSUE TITLE
Get-MgDirectoryObjectAvailableExtensionProperty Unable to cast object of type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonObject' to type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonArray'.

### ISSUE THREAD

**Issue by blackadi** [microsoftgraph/msgraph-sdk-powershell#1750]
Hi,

The below error is thrown when executing `Get-MgDirectoryObjectAvailableExtensionProperty`

![image](https://user-images.githubusercontent.com/16793335/213391702-ec6c9ec2-6969-429d-b49a-b5b27be4f545.png)

**Comment by peombwa** [comment]
@blackadi, you must be using an older version of the module. The command works fine in the latest version - `1.20.0`:
![image](https://user-images.githubusercontent.com/7061532/213517191-514b9f6d-5f7c-4279-9f4e-295e6c7cabef.png)

Please update your module to the latest version using the instructions at https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.20.0.

**Comment by blackadi** [comment]
@peombwa its working now.

Thanks for your clarification.
