### ISSUE TITLE
Update-MgUser fails as unauthorized when modifying user's schools

### ISSUE THREAD

**Issue by Vilican** [microsoftgraph/msgraph-sdk-powershell#1751]
Command `Update-MgUser` fails when setting user's school attribute as unauthorized even with signed-in global admin account and consented `Directory.AccessAsUser.All`.

```
Import-Module Microsoft.Graph.Users
Connect-MgGraph -Scopes Directory.AccessAsUser.All
Select-MgProfile -Name beta

$users = Import-Csv -Path .\schools.csv -Delimiter ";"

$users | ForEach-Object -Process {
    Update-MgUser -UserId $_.objectid -Schools [$_.school]
}
```
![image](https://user-images.githubusercontent.com/11300407/213488488-e62bb7a6-521e-4621-9686-87d95c606017.png)

**Comment by peombwa** [comment]
Thanks for following up on this.

Unfortunately, nothing in the [API reference](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http) talks about which permission is needed to update the property. Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from subject matter experts as this is an API related question. In your question, please include the `request-id` and `date` of the failing as shown in [Microsoft Graph PowerShell Troubleshooting](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug).

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API such as permissions.
