### ISSUE TITLE
[2.x] In-box help for *-MgServicePrincipalAppRoleAssignedTo cmdlets doesn't have examples

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#1755]
In-box help for Get/New/Update/Remove-MgServicePrincipalAppRoleAssignedTo cmdlets doesn't have examples.
You get {Add code here} instead.

Also, online help for the Update-MgServicePrincipalAppRoleAssignedTo cmdlet doesn't have examples.

Synopsis and description in both, in-box and online, help for Remove-MgServicePrincipalAppRoleAssignedTo and Update-MgServicePrincipalAppRoleAssignedTo cmdlets are incorrect.

```
"Delete navigation property appRoleAssignedTo for servicePrincipals"
"Update the navigation property appRoleAssignedTo in servicePrincipals"
```

A description for New-MgServicePrincipalAppRoleAssignedTo is not complete. It ends with:
```
To grant an app role assignment, you need three identifiers:
```

**Comment by timayabi2020** [comment]
@alexandair Thanks for identifying this issue, It is related to #1559 which has been closed. The examples will be available on the next V2 release.

**Comment by alexandair** [comment]
#1559 is not closed, it's still open. 
And this issue should be reopened until it's fixed.
I've marked the title of this issue with [2.x] because that's the version I am using, but that issue exists for v1 as well. Users of the help for v1 don't get any examples either.

**Comment by alexandair** [comment]
@peombwa @maisarissi Why is this issue closed when it's not fixed. And it affects v1 and v2.

**Comment by maisarissi** [comment]
Hi @timayabi2020. Even though this issue can be fixed with the #1559 work, can you validate whether the issues described by @alexandair are indeed being fixed with v2?

**Comment by timayabi2020** [comment]
@alexandair we currently have examples for Get, Remove and Add. I have logged an issue with the documentation team, to add the remaining example for patch/update.


![Image](https://user-images.githubusercontent.com/10947120/236126317-c073c271-d2f2-4a2f-9016-52b6cc34aba9.png)

**Comment by timayabi2020** [comment]
Closing this issue because the API only supports GET, POST and DELETE operations. Therefore, we will only have examples for those operations. 
Another issue has been opened [here](https://github.com/microsoftgraph/msgraph-metadata/issues/364) to prevent cmdlet for UPDATE operation from being generated.
