### ISSUE TITLE
Module name doesn't match the API for Microsoft.Graph.DeviceManagement.Enrolment

### ISSUE THREAD

**Issue by triplanedave** [microsoftgraph/msgraph-sdk-powershell#1759]
The module name is Microsoft.Graph.DeviceManagement.Enrolment which I assume is the UK spelling of the work Enrolment. But the cmdlets in the module uses double l which is the US spelling. It gets a bit confusing when the spelling is not the same. 

Darrel suggests that we modify the module to match (versus changing the API).

**Comment by peombwa** [comment]
@triplanedave, we've already renamed the module in v2 preview - https://www.powershellgallery.com/packages/Microsoft.Graph.DeviceManagement.Enrollment. Renaming the module in v1 will result in a breaking change.

The goal is to GA v2 this quarter.

**Comment by triplanedave** [comment]
Thanks, I'll share feedback with the original requestor.
