### ISSUE TITLE
Update-MgUser - Reset Password not writing back

### ISSUE THREAD

**Issue by TassieTrooper** [microsoftgraph/msgraph-sdk-powershell#1761]
Hi,

This may not be specifically related to Graph API, as the Set-AzureADUserPassword has the same issue, but when I run the command below (or the AzureADUserPassword) the **password will reset on AAD** for both Graph and AzureAD, however the password is not written back to OnPrem.

The anomaly is that when we reset a user's password via AAD Users console 'Reset password', the password is written back to onprem, which I believe rules out and AAD Connect configuration problem.

I have reviewed the AAD Sync logs and there appears to be no errors.

$params = @{
                        PasswordProfile = @{
                            ForceChangePasswordNextSignIn = $true
                            Password = $NewPlainPWD
                        }
                    }
                    Write-host "Now resetting the AAD Password for $EmailAddress"
                    Update-MgUser -UserId $EmailAddress -BodyParameter $params

**Comment by TassieTrooper** [comment]
I forgot to add that I am using Graph Beta API and the scope applied is Directory.AccessAsUser.All

**Comment by peombwa** [comment]
@TassieTrooper, sorry for the delayed response.

I'd recommend you ask the question at https://developer.microsoft.com/en-us/graph/support to get assistance from subject matter experts as this is an API question. As a client, we simply send requests to the service as-is.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

**Comment by TassieTrooper** [comment]
OK I will check with them thanks!
