### ISSUE TITLE
Connect-Graph with AAD app sign in error: Object reference not set to an instance

### ISSUE THREAD

**Issue by MandarbZA** [microsoftgraph/msgraph-sdk-powershell#177]
Hi

I'm trying to write a script to add tabs to Teams, that is only possible with the Graph at the moment.
I'm trying to use Connect-Graph with a Azure AD app registration, like this:
`Connect-Graph -ClientId "<ID>" -TenantId "<ID> -CertificateThumbprint "<Thumbrpint>" -CertificateName "CN=CertName"`

But I get this error every time:
```
Connect-Graph : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-Graph -ClientId "<ID>" -Tenan ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-Graph], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectGraph
```
I get the same error on three different PCs, on the one I tried debugging the Microsoft.Graph.Authentication project, where I saw it is failing at line 108 in ConnectGraph.cs.
`authProvider.AuthenticateRequestAsync(httpRequestMessage).GetAwaiter().GetResult();`

I tried with a different app registration as well, and get the same error, but haven't tried a different tenant yet. At the moment I've reached the amount of time I'm willing to spend trying to find a solution I'm on my own, and I'm not sure if it is something that I've done wrong on the config, or something in the project.

**Comment by MIchaelMainer** [comment]
Related to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1719.

Make sure that you use a certificate signed with a private key or else you will get this error.
