### ISSUE TITLE
[Graph Explorer] Generated PowerShell code snippet is incorrect

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#1770]
Generated PowerShell code snippet for the following query is incorrect:
```
https://graph.microsoft.com/v1.0/users?$search="displayName:di" OR "displayName:al"&$count=true&$orderby=displayname
```
The value specified for the -Search parameter wouldn't work in PowerShell:
```powershell
Import-Module Microsoft.Graph.Users

Get-MgUser -Search "displayName:di"+OR+"displayName:al" -CountVariable CountVar -Sort "displayname" -ConsistencyLevel eventual 
```
The correct snippet is:
```powershell
Get-MgUser -Search '"displayName:di" OR "displayName:al"' -CountVariable CountVar -Sort "displayname" -ConsistencyLevel eventual
```

**Comment by timayabi2020** [comment]
@alexandair thank you for identifying and logging this issue. This is indeed a bug and ww will work on a solution to fix it.

**Comment by peombwa** [comment]
Closing as fixed by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1350
