### ISSUE TITLE
Need URIs - Unable to add modules from galleries during automatic deployment.

### ISSUE THREAD

**Issue by wrharper** [microsoftgraph/msgraph-sdk-powershell#1780]
I am using Azure.ResourceManager.Automation in C# to deploy modules automatically. I need a direct URI for the dependency for Microsoft.Graph.Users.Actions and Microsoft.Graph.Users.Actions itself.
```csharp
            AutomationAccountResource response = (await SelectedGroup.GetAutomationAccounts().CreateOrUpdateAsync(WaitUntil.Completed, "automationaccountname", content)).Value;
            _ = response.GetAutomationAccountModules().CreateOrUpdateAsync(WaitUntil.Completed, "Microsoft.Graph.Authentication", new(new()
            {
                ContentHash = new("???","???"),
                Uri = new Uri("???"),
                Version = "1.21.0"
            }));
            _ = response.GetAutomationAccountModules().CreateOrUpdateAsync(WaitUntil.Completed, "Microsoft.Graph.Users.Actions", new(new()
            {
                ContentHash = new("???","???"),
                Uri = new Uri("???"),
                Version = "1.21.0"
            }));
```

**Comment by wrharper** [comment]
Reference link: https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.automation.models.automationcontentlink?view=azure-dotnet

**Comment by wrharper** [comment]
I ended up using direct links from the PowerShell gallery and used nuget packages. ContentHash was not required, and it seems to of imported successfully. It did require trying twice though due to dependencies. the "WaitUntil.Completed" is not working as intended. Is there any way to make the 2nd important wait until the 1st one is completed?

**Comment by wrharper** [comment]
![image](https://user-images.githubusercontent.com/117128832/215843630-ffae5b49-d458-4f8c-83c5-258c88049c29.png)
Microsoft.Graph.Users.Actions shouldn't start until the 1st one is finished. this results in dependency errors.

**Comment by peombwa** [comment]
Our modules are published to PowerShell Gallery. PowerShell Gallery will show you the dependencies of all modules:
![image](https://user-images.githubusercontent.com/7061532/216192134-cc708c23-d6e4-4d78-9fb0-d91764a4f663.png)

You can simply use `Find-Module Microsoft.Graph.Users.Actions | select -ExpandProperty Dependencies` or [PowerShell Gallery API](https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Microsoft.Graph.Users.Actions') to programmatically read dependencies.

**Comment by peombwa** [comment]
> Is there any way to make the 2nd import wait until the 1st one is completed?

Please post the question to the Azure SDK repo to get help from experts on this. The question is related to sequentially importing modules in Azure Automation.

**Comment by wrharper** [comment]
Yes, the issue has changed. Originally, I just needed the URIs, but have worked around it.
