### ISSUE TITLE
Find-MgGraphCommand: differentiate delegated vs app permissions?

### ISSUE THREAD

**Issue by jazuntee** [microsoftgraph/msgraph-sdk-powershell#1781]
It would be beneficial if Find-MgGraphCommand would return both Delegated Permissions and App Permissions by either:
1) Add Permission Type (Delegated vs App) property to Microsoft.Graph.PowerShell.Authentication.Models.GraphPermission
Or
2) Add AppPermission property to Microsoft.Graph.PowerShell.Authentication.Models.GraphCommand with list of app permissions

![image](https://user-images.githubusercontent.com/17210677/215886925-1f76c97b-d06c-4aee-a96a-6edf8ff813be.png)

**Comment by peombwa** [comment]
Thanks for following up on this.

The permissions are not categorized by type from the source. I've transferred the feature request to the DevX repo, where the permissions are fetched, for the team to support this - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1355.

We will add `PermissionType` to `GraphPermission` model class once https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1355 is supported by the service.

**Comment by andikrueger** [comment]
@peombwa the referenced issue within the Devx api project got resolved. Is there anything on the SDK side happening? Would be great to have this feature within Find-MgGraphCommand.

will the command outline the various permission levels and is there a “rating” available to get the least permissive permissions for the command?
