### ISSUE TITLE
metadata schema and additionalProperties

### ISSUE THREAD

**Issue by William-Francillette** [microsoftgraph/msgraph-sdk-powershell#1787]
Hi,

I am trying to extract from the metadata schema some conditions when a parameter will be part of AdditionalProperties to generate M365DSC resource automatically from the metadata

I have assumed that it will be added to AdditionalProperties if:
- the properties are inherited from an entity where the baseType is not "graph.Entity"
- the properties are inherited from a complex type which is not abstract
- any '@odata' properties

Could you confirm if this is correct, missing something?, and if there is an easier way to detect those properties from AdditionalProperties 

AdditionalProperties is heavily used in the Intune Mg cmdlets

Thanks,
William

**Comment by peombwa** [comment]
@William-Francillette, that's right!

In addition to the above, AdditionalProperties can also have:
- new properties that have not yet been added to the service metadata and are available via the REST API and. (This is rare though).
- dynamic properties are on an open type (OpenType="true"). Both EntityTypes and ComplexTypes can be open.
- properties inherited from an abstract base type. e.g., https://learn.microsoft.com/en-us/graph/api/ediscovery-sourcecollection-post-additionalsources?view=graph-rest-beta&tabs=http#example-1-add-a-user-or-group-mailbox-to-the-additional-sources.

**Comment by William-Francillette** [comment]
@peombwa , that makes sense thanks - I mainly missed the last one you mentioned

You can close that issue - and again many thanks for the support !
