### ISSUE TITLE
Help for Get-MgUserManagerByRef contains examples for Get-MgUserManager and Get-MgUser

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#1791]
Help for Get-MgUserManagerByRef doesn't contain examples for that cmdlet.
Examples are for Get-MgUserManager and Get-MgUser (btw, this one is failing with an error).

**Comment by timayabi2020** [comment]
@alexandair thanks for noticing and reporting this issue. As we investigate the missing examples issues. Kindly list the steps to reproduce the ``Get-MgUser`` error. Kindly also confirm the PowerShell Microsoft.Graph Sdk version you are using. I would also advise that you open a different issue for that error.

**Comment by alexandair** [comment]
Thanks. I've already opened the issue for that Get-MgUser error.

**Comment by alexandair** [comment]
This issue is closed now, but it's still not fixed. Wrong examples are still there.
