### ISSUE TITLE
Provide v1.x to v2.x migration advisor script

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#1796]
The migration script should provide a find and replace experience for renaming `v1.x` beta commands to `v2.x` beta commands as stated in the [v2 migration guide](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/docs/upgrade-to-v2.md#breaking-changes).

**Comment by sebastienlevert** [comment]
I find it very challenging to change customer's content without fully understanding their context. Updating a file is challenging and bring tons of edge cases. Could we change the scope of the migration script to a migration "report" in a markdown format that could indicate to the users "how" to do the migration, in the context of their scripts? You can see how the CLI for Microsoft 365 open source project took this approach for their SharePoint Framework upgrade commands : https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade/

@maisarissi What do you think?

**Comment by maisarissi** [comment]
Yes! I do agree that having an advisor that can tell users how to do it is better than changing their script.

Thanks for the insight @sebastienlevert .

**Comment by alexandair** [comment]
Why not both? Give user a report about changes, but also provide a way to make them. You can control that easy with a parameter. Kind of like the -WhatIf parameter.

**Comment by timayabi2020** [comment]
@maisarissi  @alexandair you can install the migration advisor from [here](https://www.powershellgallery.com/packages/Microsoft.Graph.Migration.Tool/1.0.0)
