### ISSUE TITLE
Manage permissions for recipients in Exchange Online

### ISSUE THREAD

**Issue by ericoevering** [microsoftgraph/msgraph-sdk-powershell#1799]
is it possible to manage permissions for recipients? 

https://learn.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-permissions-for-recipients

**Comment by peombwa** [comment]
Thanks for following up on this.

You've opened the issue in the wrong repository. Please contact the Exchange PowerShell module author for assistance.

This repository is intended for issues related to the functionality of the Microsoft Graph PowerShell module, which calls the [Microsoft Graph REST API](https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0).

**Comment by peombwa** [comment]
Closing as external/service question.
