### ISSUE TITLE
adding multi-geo sharepoint site resource to catalog

### ISSUE THREAD

**Issue by praveenbattula** [microsoftgraph/msgraph-sdk-powershell#1801]
Hello, 
we are using the PowerShell SDK to provision catalog in entitlement management and add SharePoint as a resource. We found there are few articles that the entitlement management supports Multi-Geo. Here is the article from Microsoft: [Multi-geo add resource to catalog](https://learn.microsoft.com/en-us/azure/active-directory/governance/entitlement-management-catalog-create#add-a-multi-geo-sharepoint-site).

When I am using the command New-MgEntitlementManagementAccessPackageResourceRequest and use url parameter as europe region provisioned site, it just fails to add.

$params = @{
            CatalogId             = $catalogObj.Id
            RequestType           = "AdminAdd"
            Justification         = ""
            AccessPackageResource = @{
                DisplayName  = $requestObj.requestTitle
                Description  = $requestObj.requestTitle
                Url          = "https://companyeur.sharepoint.com/teams/testeurope"
                ResourceType = "SharePoint Online Site"
                OriginId     = $requestObj.siteUrl
                OriginSystem = "SharePointOnline"
            }
        }
New-MgEntitlementManagementAccessPackageResourceRequest -BodyParameter $params | Out-Null

Anyone please help in adding multi-geo site as a resource in the catalog? Thanks

**Comment by peombwa** [comment]
Please use the [feedback options](https://learn.microsoft.com/en-us/azure/active-directory/governance/entitlement-management-catalog-create#next-steps) on the bottom of the page to submit the question to the author of the article:
![image](https://user-images.githubusercontent.com/7061532/220494315-80644518-d87b-4212-8a11-a1b4a3d9a180.png)

Alternatively, you can ask the question at https://developer.microsoft.com/en-us/graph/support to get help from the subject matter experts/ API owner. 

@markwahl-msft, are you able to help with the question?

**Comment by markwahl-msft** [comment]
To assign the geolocation environment for a multi-geolocation Sharepoint Online resource, include the accessPackageResourceEnvironment relationship in the accessPackageResource object.   It appears you are using the approach of specifying the originId parameter of the accessPackageResourceEnvironment.  Your code snippet is showing that the value is coming from a request object, so I cannot tell what is the value of originId that is being sent?
 
 See also https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&preserve-view=true&tabs=powershell#request-1

**Comment by praveenbattula** [comment]
Sorry, I have resolved the issue last week and forgot to update here. Yes environment property is what we should be adding: 

$params = @{
CatalogId = $catalogObj.Id
RequestType = "AdminAdd"
Justification = ""
AccessPackageResource = @{
DisplayName = $requestObj.requestTitle
Description = $requestObj.requestTitle
Url = "https://companyeur.sharepoint.com/teams/testeurope"
ResourceType = "SharePoint Online Site"
OriginId = $requestObj.siteUrl
OriginSystem = "SharePointOnline"
accessPackageResourceEnvironment=@{
originId=<multi-geo-admin-url>
}
}
}
New-MgEntitlementManagementAccessPackageResourceRequest -BodyParameter $params | Out-Null

**Comment by praveenbattula** [comment]
thanks for the comments and suggestions. closing now.
