### ISSUE TITLE
New-MgTeam -Channels

### ISSUE THREAD

**Issue by DanielBradley1** [microsoftgraph/msgraph-sdk-powershell#1802]
I seem to be able to create a standard channel when creating a team, for example:

```
$Template = @{
    "Template@odata.bind" = "https://graph.microsoft.com/beta/teamsTemplates('standard')"
}
$Channel = @(
    @{
	DisplayName = "Test Channel"
	Description = "Test Channel"
    }
)
New-MgTeam -DisplayName "New Team" -AdditionalProperties $Template -Channels $channel
```
However, if I then add the following line to set the membership type as 'Private' it is ignored:

```
$Channel = @(
    @{
	DisplayName = "Test Team"
	Description = "Test Team"
    MembershipType = 'Private'
    }
)
```
I have even tried to define the Channel owner at the same time:

```
$Channel = @(
    @{
	DisplayName = "Test Team"
	Description = "Test Team"
    MembershipType = 'Private'
    Members = @(
		@{
			"@odata.type" = "#microsoft.graph.aadUserConversationMember"
			"User@odata.bind" = "https://graph.microsoft.com/beta/users('UserID')"
			Roles = @(
				"owner"
			)
		}
	)
    }
)
```

**Comment by peombwa** [comment]
Thanks for following up on this.

Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner as this is a service issue. The command serializes `MembershipType` as expected in the request body that's sent to the service. You can see this in the `-Debug` log:
![image](https://user-images.githubusercontent.com/7061532/220493833-3eba2ae6-4042-427f-8d08-55ae1171fad7.png)

In your ticket/question, please include the `requestId` and `date` of the affected requests. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details. 

This repository is intended for issues related to the functionality of commands in the module. We may not be the best place to answer some queries that are tied to the functionality of the API.
