### ISSUE TITLE
Certificate login and Update-MgUser

### ISSUE THREAD

**Issue by ThomasGDK** [microsoftgraph/msgraph-sdk-powershell#181]
Hi There,

I'm trying to update users "Skills" and "PastProjects" in Graph using the Microsoft.Graph module (0.2.1).
This works fine when connecting through delegated access with the devicelogin web page.
When using the Enterprise App Registration and granting Directory.ReadWrite.All, Group.ReadAll and Users.ReadWrite.All - I can read everything I need.
But Update-MgUser -UserId user1@contoso.com -Skills "Test Manager" fails with this error:

"Update-MgUser : Attempted to perform an unauthorized operation.
At line:1 char:1
"+ Update-MgUser -UserId user1@contoso.com -Skills "Test Manager ...
"+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = use....softGraphUser }:<>f__AnonymousType6`2) [Update-MgUser_UpdateExpanded], Exception
    + FullyQualifiedErrorId : -1, Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_UpdateExpanded"

Is this because "App only access via Client Credential Flow with a certificate" is not allowed to make changes or is it because I'm doing something wrong (e.g. what permissions are missing for the enterprise app)?

Thanks for you help :-)

/Thomas

**Comment by MIchaelMainer** [comment]
Client credential flow itself isn't an issue as I was able to update skills (not with the PowerShell SDK). 

Can you share a sanitized fiddler capture?

**Comment by ThomasGDK** [comment]
Hi Michael,

This is the sanitized response (raw) from Graph in Fiddler - let me know if you need anything else:

--------------------------------------
[Request:]

PATCH https://graph.microsoft.com/beta/users/user1@contoso.com HTTP/1.1
SdkVersion: Graph-powershell-Microsoft.Graph.Authentication-0.2.0, Graph-dotnet-1.20.0
FeatureFlag: 00000047
Cache-Control: no-store, no-cache
Authorization: Bearer [Certificate]
Accept-Encoding: gzip
Content-Type: application/json
Host: graph.microsoft.com
Content-Length: 38
Expect: 100-continue
Connection: Keep-Alive

{
  "skills": [ "Test Manager" ]
}

[Response:]

HTTP/1.1 500 Internal Server Error
Cache-Control: private
Content-Type: application/json
request-id: [snip]
client-request-id: [snip]
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"somewhere","Slice":"SliceX","Ring":"X","ScaleUnit":"000","RoleInstance":"AGSFE_IN_7"}}
Strict-Transport-Security: max-age=31536000
Date: Fri, 01 May 2020 07:05:23 GMT
Content-Length: 313

{
  "error": {
    "code": "-1, Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException",
    "message": "Attempted to perform an unauthorized operation.",
    "innerError": {
      "request-id": "[snip]",
      "date": "2020-05-01T07:05:23"
    }
  }
}
--------------------------------------

Thanks for your help :-)

/Thomas

**Comment by MIchaelMainer** [comment]
This doesn't look to be a PowerShell client issue. This is an unexpected service issue. @dkershaw10

**Comment by ThomasGDK** [comment]
Hi @MIchaelMainer,

I just saw your feature request for additional user properties that allow apps with application permissions to update.
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/35395435-bug-unable-to-update-birthday-or-hiredate-using-g

Would this cover the above "problem" as well?

Thanks :-)

/Thomas

**Comment by MIchaelMainer** [comment]
Hello @ThomasGDK, 

The user voice post would cover the same problem. Please have your entire family up vote that feature request. 😉 

With regards,
Michael

**Comment by peombwa** [comment]
Closing this since it's being tracked as a service feature request under https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/35395435-bug-unable-to-update-birthday-or-hiredate-using-g
