### ISSUE TITLE
Owner Issue

### ISSUE THREAD

**Issue by goldfinger3** [microsoftgraph/msgraph-sdk-powershell#1817]
It seems that there is a race condition and sometimes the owner of the schema extensions is not registered properly.
I have used the latest Powerhell 7.3.2 and Microsoft Graph. But I have had the problem with older versions as well.

The problem:
I expect Get-MgSchemaExtension -Filter "owner eq '<appid>'" to show all extensions created with the app.
But sometimes no extensions are shown, or only one or two. See attachment.
It seems that there is a race condition or that Microsoft Graph has internally more than the 5 allowed schemas per app.

The code to reproduce the issue:
```
Import-Module Microsoft.Graph.SchemaExtensions

Connect-MgGraph -Scopes "User.ReadWrite.All","Group.ReadWrite.All","Application.ReadWrite.All", "Directory.AccessAsUser.All", "Directory.ReadWrite.All"

Get-MgContext

$appid = "ff31f0d2-5637-4e71-8fdb-aaefb6a576db"
$appname= "TestAppJf01"

# First Schema Def
$params1 = @{
        Id = $appname
	Description = "AddOnTest1"
        TargetTypes = @(
		"User"
	)
        Owner = $appid
	Properties = @(
		@{
			Name = "trousersize"
			Type = "String"
		}
		
		@{
			Name = "tshirtsize"
			Type = "String"
		}
	)
}


$s1 = New-MgSchemaExtension -BodyParameter $params1

# Second Schema Def
$params2 = @{
        Id = $appname
	Description = "AddOnTest2"
        TargetTypes = @(
		"User"
	)
        Owner = $appid
	Properties = @(
		@{
			Name = "brasize"
			Type = "String"
		}
		
		@{
			Name = "underwearsize"
			Type = "String"
		}
	)
}

$s2 = New-MgSchemaExtension -BodyParameter $params2

# Third Schema Def
$SchemaProperties3 = New-Object -TypeName System.Collections.ArrayList

# define our keys and the types
$prop1 = @{
    'name' = 'shoesize';
    'type' = 'String';
}
$prop2 = @{
    'name' = 'socksize';
    'type' = 'String';
}

[void]$SchemaProperties3.Add( $prop1)
[void]$SchemaProperties3.Add( $prop2)

# Show Schema Properies
$params1
$params2
$SchemaProperties3

# Create

$s3 = New-MgSchemaExtension -TargetTypes  @('User') `
    -Properties $SchemaProperties3 `
    -Id $appname `
    -Description 'AddOnTest3' `
    -Owner $appid 

# Show schema 
$s1
$s2
$s3

# sometimes not working 
# Race Condition
# Internal more than 5 schema per app?
Get-MgSchemaExtension  -Filter "owner eq 'ff31f0d2-5637-4e71-8fdb-aaefb6a576db'"
```

![error1](https://user-images.githubusercontent.com/62419481/218978229-e2d65a7b-e20f-4a85-994d-567d52769d4b.PNG)
![error2](https://user-images.githubusercontent.com/62419481/218978235-565a9467-d870-4dcf-ad0a-780ea2f5e070.PNG)

**Comment by peombwa** [comment]
Thanks for following up on this.

Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support as this is a service issue. `Get-MgSchemaExtension  -Filter "owner eq 'ff31f0d2-5637-4e71-8fdb-aaefb6a576db'"` get the inconsistent response from the API. You can call the command with `-Debug` to see what the service returns. The same behavior should also be reproducible through Graph Explorer.

Please include the `requestId` and `date` of the affected calls in your ticket/question. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details. 

This repository is intended for issues related to the functionality of the module. We may not be the best place to answer some queries that are tied to the functionality of the API.

**Comment by drewid** [comment]
Please reopen this issue.  This is a complete failure and is also seen when using GraphServiceClient.
Filtering does not work for any field (id does not count as that is not really a filter).
