### ISSUE TITLE
Enable cmdlets to access to non-json responses 

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#182]
Need to access user Photos, reports, files, mail attachments, OneNote pages, etc.

[AB#4643](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4643)

**Comment by peombwa** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/166, https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/190, https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/222

**Comment by soroshsabz** [comment]
@darrelmiller Did you mean we cannot download attachment file with `Get-MgUserMessageAttachment` ?

**Comment by peombwa** [comment]
Closing since downloading of files was fixed in 1.1.0. The only open item is downloading of reports which is being tracked by #190

**Comment by fagalliu** [comment]
> Closing since downloading of files was fixed in 1.1.0. The only open item is downloading of reports which is being tracked by #190

Hi peombwa,

Can you help me how to download files attached to a mailbox?
I am trying with Out-File, the file donwloads but then it doesnt open and gives a message that the file has to be decoded.
I tried to decode with this comand but no success:

[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("$contentBytes")) | Out-File ".\$name"

Can you help me please?
