### ISSUE TITLE
New-MgEntitlementManagementAccessPackageAssignmentPolicy -BodyParameter $pparams Error

### ISSUE THREAD

**Issue by nickletelliersi** [microsoftgraph/msgraph-sdk-powershell#1821]
I ran this: New-MgEntitlementManagementAccessPackageAssignmentPolicy -BodyParameter $pparams
And got the following error: 
New-MgEntitlementManagementAccessPackageAssignmentPolicy : The model is invalid.
At line:1 char:5
+     New-MgEntitlementManagementAccessPackageAssignmentPolicy -BodyPar ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ body = Micros...gnmentPolicy1 }:<>f__AnonymousType55`1) [New-MgEntitleme...ntPolicy_Create], RestException`1
    + FullyQualifiedErrorId : InvalidModel,Microsoft.Graph.PowerShell.Cmdlets.NewMgEntitlementManagementAccessPackageAssignmentPolicy_Create

The $pparams is:

$pparams = @{
        AccessPackageId = $ap.Id
        DisplayName = $ap.DisplayName
        Description = $ap.Description
        CanExtend = $true
        DurationInDays = 365
        ExpirationDateTime = $null
        RequestorSettings = @{
            ScopeType = "AllExistingDirectoryMemberUsers"
            AcceptRequests = $true
            AllowedRequestors = @()
        }
        RequestApprovalSettings = @{
            IsApprovalRequired = $true
            IsApprovalRequiredForExtension = $true
            IsRequestorJustificationRequired = $true
            ApprovalMode = "SingleStage"
            ApprovalStages = @(
                @{
                    ApprovalStageTimeOutInDays = 14
                    IsApproverJustificationRequired = $true
                    IsEscalationEnabled = $false
                    EscalationTimeInMinutes = 11520
                    PrimaryApprovers = @(
                        @{
                            "@odata.type" = "#microsoft.graph.groupMembers"
                            IsBackup = $false
                            Id = (Get-AzureADGroup -Filter "DisplayName eq 'IdentityGovernance_RequestApprovers'" | Select-Object -ExpandProperty ObjectId)
                            Description = "Approvers Group"
                        }
                    )
                    EscalationApprovers = @()
                }
            )
        }
    }

**Comment by peombwa** [comment]
@nickletelliersi, `The model is invalid` is an error from the service indicating that the request body is invalid (run the command with `-Debug`).

Please review the value being set on `-BodyParameter`. You can use Graph Explorer and the [API reference](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&tabs=powershell#example-1-create-a-direct-assignment-policy) to validate the correctness of the request body.
