### ISSUE TITLE
v2.0.0: Missing parameters in Cmdlets

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#1822]
Several cmdlets are missing parameters in comparison to their 1.22+ alternatives:

* New-MgDirectoryAdministrativeUnit cmdlet is missing the Members parameter:
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/new-mgdirectoryadministrativeunit?view=graph-powershell-1.0

* Update-MgBetaDeviceManagementConfigurationPolicy is missing the settings parameter: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement/update-mgdevicemanagementconfigurationpolicy?view=graph-powershell-beta

* New-MgBetaDeviceManagementDeviceCompliancePolicy is missing the ScheduledActionsForRule parameter: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement/new-mgdevicemanagementdevicecompliancepolicy?view=graph-powershell-1.0

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

The parameters a missing due to the introduction of `readOnly` nav properties in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1605. This was added to reduce the number of parameters surfaced in update/set/new commands.

We will reverse this change since most workloads don't fully comply with OData conventions as stated in - https://github.com/microsoft/OpenAPI.NET.OData/issues/254.

**Comment by peombwa** [comment]
Closing as fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview6.

``` powershell
➜ Get-Help New-MgDirectoryAdministrativeUnit

NAME
    New-MgDirectoryAdministrativeUnit

SYNOPSIS
    Use this API to create a new administrativeUnit.


SYNTAX
    New-MgDirectoryAdministrativeUnit [-AdditionalProperties <Hashtable>] [-DeletedDateTime <DateTime>] [-Description <String>]
    [-DisplayName <String>] [-Extensions <IMicrosoftGraphExtension[]>] [-Id <String>] [-Members <IMicrosoftGraphDirectoryObject[]>]
    [-ScopedRoleMembers <IMicrosoftGraphScopedRoleMembership[]>] [-Visibility <String>] [-Break] [-HttpPipelineAppend <SendAsyncStep[]>]
    [-HttpPipelinePrepend <SendAsyncStep[]>] [-Proxy <Uri>] [-ProxyCredential <PSCredential>] [-ProxyUseDefaultCredentials] [-WhatIf]
    [-Confirm] [<CommonParameters>]
```

The reference docs will be updated in the next cycle.
