### ISSUE TITLE
Get-MgBetaSitePage gives error

### ISSUE THREAD

**Issue by DutchHarry** [microsoftgraph/msgraph-sdk-powershell#1825]
Get-MgBetaSitePage -SiteId $siteId -SitePageId $sitePageId
gives a.o.
Get-MgBetaSitePage : Caller does not have required permissions for this API
At line:1 char:1
+ Get-MgBetaSitePage -SiteId $siteId -SitePageId $sitePageId
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ SiteId = mala...ndProperty =  }:<>f__AnonymousType110`4) [Get-MgBetaSitePage_Get], Exception
    + FullyQualifiedErrorId : accessDenied,Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaSitePage_Get
    

whereas access via graph explorer works OK!

**Comment by peombwa** [comment]
@DutchHarry, as stated in the error message - ` Caller does not have required permissions for this API`. The caller needs consent to the required permissions listed in the [API reference doc](https://learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&tabs=http#permissions). Please consent to the required permissions then try again - `Connect-MgGraph -Scopes "Sites.ReadWrite.All"`.

You can use [Get-MgContext](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-get-mgcontext) to view permissions you've already consented to.

The command works fine for me:
![image](https://user-images.githubusercontent.com/7061532/221244020-883ac77d-3e26-4e23-992a-f3aed6228389.png)
