### ISSUE TITLE
Failed to get alert information

### ISSUE THREAD

**Issue by sam-wang-1991** [microsoftgraph/msgraph-sdk-powershell#1828]
Alert information cannot be scraped through Graph PowerShell
API             :  https://graph.microsoft.com/beta/security/alerts
Permissions :  SecurityEvents.ReadWrite.All
Graph Module:  Microsoft.Graph.Security
We can successfully fetch the results of this API in Graph Explorer, but PowerShell cannot
PowerShell's feedback is:
WARNING: 199 - 'Microsoft/Office 365 Security and Compliance/403/602'

**Comment by peombwa** [comment]
@sam-wang-1991, have you switched to the [beta profile](https://learn.microsoft.com/en-us/powershell/microsoftgraph/get-started)? The API (https://graph.microsoft.com/beta/security/alerts) you've shared calls the beta endpoint. Please share the `-Debug` output with us.

Which API are you calling in Graph Explorer? There are two versions of the security alerts API: `security/alerts` and `security/alerts_v2`. We will be adding support for `security/alerts_v2` in the next release of the module. See https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1820#issuecomment-1439274837.

The warning is picked from the warning header in the API response:
![image](https://user-images.githubusercontent.com/7061532/221241627-c71017e8-eb2c-4952-9696-afc84ac72df1.png)
