### ISSUE TITLE
Get-MgSite -Search "*" returns null

### ISSUE THREAD

**Issue by jachaohk** [microsoftgraph/msgraph-sdk-powershell#1829]
Hi,

At some point in the last month, we have lost the ability to use the following command:

get-mgsite -search "*"

This command would result in a listing of all the Sharepoint Online sites in my tenant. Now it returns nothing. In fact, most terms that I enter in the -search query field return nothing.

get-mgsitelist requires the siteid as a parameter and I am not sure how I can get the site ID if I cannot search for the site by name. For example:

```
$siteid = (Get-MgSite -Search "*" | where {$_.name -eq "<SiteName>"}).id
$listid = (Get-MgSiteList -SiteId $siteid| where {$_.name -eq "<listname>"}).id
```

How do you list all the sites in the tenant now?  Was there a change in the permissions structure in SPO?  I have tried both application permission and my delegated permission and the results are the same.   I have Sites.ReadWrite.All and Sites.fullcontrol.all applied.

I work around this issue by performing the following to get site directly:

Get-MgSite -siteid "<domain>.sharepoint.com:/sites/<sitename>"

I have also posted this question to both the Sharepoint Team at Microsoft and to the Q&A forum.  

The Microsoft Sharepoint Team refered me to you.  They were able to replicate the issue using the powershell cmdlets but were able to get the results using Graph Explorer.

https://learn.microsoft.com/en-us/answers/questions/1178627/get-mgsite-search-*

**Comment by peombwa** [comment]
Sorry I missed your question above.

> Question: with delegated permissions to Graph with Sites.ReadWrite.All and Sites.FullControl.All, do you need to have SPO level permissions (within SharePoint not graph) to the site on top of that in order to see it in graph or do these permissions give your account "admin" level permissions?

I'm not entirely sure if you need SPO level permissions on top of the Microsoft Graph permissions since we are not experts on the API. For this, please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner. The best practices for calling SharePoint APIs in Microsoft Graph are however documented at https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online&preserve-view=true.

You can also use the [list sites](https://learn.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0&tabs=powershell#list-all-site-collections) or [getAllSites](https://learn.microsoft.com/en-us/graph/api/site-getallsites?view=graph-rest-1.0&tabs=powershell) API/command to list all sites using application permissions. This works on my end.

**Comment by alexyvic** [comment]
This issue still exist.

**Comment by prattay56** [comment]
> This issue still exist.

I found that the issue is delegated users only. If you use a n application instead registered in azure ad , then it works. One thing I understood that if any Graph end point returns empty results. with 200 response, it means it will work with application permission only.

**Comment by prattay56** [comment]
Here is a screenshot of my powershell 
![git](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/74849664/84752648-81ce-46fe-a27f-db1d271cbaea)

**Comment by prattay56** [comment]
Here is the working screenshot.
![git](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/74849664/fbd79ce3-6bfe-4950-85a7-f974f60cfe37)

**Comment by jachaohk** [comment]
You are correct.  I just tested it using the Managed Identity and it appears to be listing all the websites.  I hadn't checked again since I posted about this issue because I had a work around and moved on.  Glad that it is working now. 

When I did post about this issue, the PS Module Team did say it was an API issue.  Since I have not updated or changed the modules I am using, I bet they fixed the API directly on the back end.

Thanks for posting.

**Comment by jachaohk** [comment]
> Wait, so couldn't we reasonably expect "get-mgsite -all" to work out of the box, without having to jump through silly hoops of creating a whole app registration, just for this single purpose ?

If I am not mistaken, -all just lists all pages available.  The issue was that no values were even being presented so there are no pages for the -all to work against.  I am not sure what your question is.  Plus if you are wanting to use the cmd in an unintended fashion, it is recommended that you use application permissions which mean you need either a managed identity or an app registration with a secret.  Otherwise, you have to save a user name and password into the script which is not as secure.
