### ISSUE TITLE
Unable to work with curly quotes within text for SPO Column

### ISSUE THREAD

**Issue by eduardomb08** [microsoftgraph/msgraph-sdk-powershell#1845]
Hi,

I am trying to add an item to a list in SPO using PowerShell and Graph. The item has the following title: "Something “else” here" (notice the curly quotes). I am able to add this same item from Graph Explorer. But not from PowerShell. I've tried using Invoke-MgGraphRequest and Invoke-Rest method.

Can someone please help?

I've created a post in StackFlow for this issue [here](https://stackoverflow.com/questions/75549393/how-to-add-a-list-item-to-spo-containing-curly-quotes-using-powershell).

**Comment by eduardomb08** [comment]
@timayabi2020 , please let me know if there's anything I can do to help. My test is in a dev tenant, so I can grant access if needed. (although the test should be pretty simple to replicate in any environment).

**Comment by peombwa** [comment]
Sorry for the delayed response.

In your SO example, you are using `Invoke-RestMethod`, which is external to this SDK. What's the output when you use `Invoke-MgGraphRequest` instead?
``` powershell
$result = Invoke-MgGraphRequest -Method POST -Uri $uri -Body $batch -Debug
```

**Comment by eduardomb08** [comment]
> Sorry for the delayed response.
> 
> In your SO example, you are using `Invoke-RestMethod`, which is external to this SDK. What's the output when you use `Invoke-MgGraphRequest` instead?
> 
> ```powershell
> $result = Invoke-MgGraphRequest -Method POST -Uri $uri -Body $batch -Debug
> ```

Hi @peombwa ,

I had tried that before, but just tested it again for you. Find the results in the image below. The only thing I changed from the first try to the second one is the present of curly quotes in the first highlighted rectangle.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/11743735/eff14242-bc5d-4951-a1f3-631bcb6726a7)

**Comment by eduardomb08** [comment]
I was finally able to figure it out:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/11743735/9979f35e-88c1-440c-ae49-8da85cb30a51)


And here is what it looks like in SPO:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/11743735/2a3a1e56-4680-49ed-9852-fe70b38ed32f)


Closing...
