### ISSUE TITLE
Get-MgGroup returns Owners property only with ExpandProperty

### ISSUE THREAD

**Issue by ztrhgf** [microsoftgraph/msgraph-sdk-powershell#1846]
Hi,
why the **property** parameter of Get-MgGroup doesn't return group owners, but instead parameter **ExpandProperty** has to be used?
![image](https://user-images.githubusercontent.com/2930419/222490575-221bd247-d02b-4938-8fcc-be25195fa81b.png)

And how should I know this when this is not stated anywhere in the command documentation? There is only cryptic 
![image](https://user-images.githubusercontent.com/2930419/222490858-823e4f5d-66a8-4def-a70c-cc4895576849.png)

**Comment by timayabi2020** [comment]
@ztrhgf Unfortunately I am not able to replicate the same issue as yours. I have tried with both parameters and it's working as expected.  PowerShell graph SDK Version. 1.23.0
<img width="658" alt="image" src="https://user-images.githubusercontent.com/10947120/223113439-bcb02139-d324-45c0-b2fd-c778375930ca.png">

Please refer to this [documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/get-mggroup?view=graph-powershell-1.0) on the command usage.

**Comment by ztrhgf** [comment]
I've tried 1.23.0 version but same behavior.
![image](https://user-images.githubusercontent.com/2930419/223124689-c68e2d89-edf9-46b7-9d78-92f6c3f24795.png)

Result without expandproperty parameter.

![image](https://user-images.githubusercontent.com/2930419/223123324-12b1969d-9ba1-44bd-851b-337ac2182846.png)
![image](https://user-images.githubusercontent.com/2930419/223123347-8a7e2afc-02cf-4898-b68d-66effa81a315.png)

Notice **there is no owners property at all**.

And result **with** expandproperty parameter.
![image](https://user-images.githubusercontent.com/2930419/223123955-8cb69ae6-cf7b-4ed4-988d-0edad78f8dd6.png)
![image](https://user-images.githubusercontent.com/2930419/223124221-d82c98c4-0adc-4f41-9164-c238726717b9.png)

**Comment by timayabi2020** [comment]
@ztrhgf if you get to the service [metadata](https://graph.microsoft.com/v1.0/$metadata#groups(owners)/$entity), you will realize that "owners" is a navigation property bound to group entity. 
<img width="754" alt="image" src="https://user-images.githubusercontent.com/10947120/223429671-0d3c95af-5994-4208-a786-39a4f1ef0f04.png">
You can only get the owners data if you pass the -ExpandProperty parameter. If the service had defined it as a property of collection type then the -Property parameter would work.

**Comment by ztrhgf** [comment]
OK, but the question is the same. How I am suppose to know that expandProperty needs to be used? I mean in general.

PS: it would be nice if cmdlet warns about not placing property XYZ into property parameter, but expandproperty parameter

**Comment by timayabi2020** [comment]
@ztrhgf apologies for completely missing and misunderstanding the question. You can refer to the service reference doc [here](https://learn.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=powershell#response-1), which lists the default properties contained in a response. 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/10947120/223436017-990df520-4b7f-41a4-ad0c-e012e04117c4.png">
"Owners" is not among them and so you can try it out as a navigation property. I.e., ```-ExpandProperty owners```. If any value passed to that parameter is not a navigation property, then you should get an error stating that the value passed is not a navigation property.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/10947120/223438686-0e7f8ab2-bbf8-45c3-86d4-54c79407c9d4.png">

**Comment by ztrhgf** [comment]
"Owners" isn't among the response output, but there is also the note "Note: The response object shown here might be shortened for readability. All the default properties are returned in an actual call." So it doesn't mean much.

Also, it still doesn't clarify that I need to use _expandproperty_ instead of _property_ parameter.

Or are you telling me that in general when I want to get additional property, I should start with _expandproperty_ parameter. And if that throws an error, I should use _property_ parameter instead? So it's just guessing??

Thanks.

**Comment by timayabi2020** [comment]
Unfortunately for now you need to get and interpret the information in the metadata so as to know when to and when not to use ExpandProperty as we work on improving our documentation for such cases. Therefore, for similar cases, these are the alternatives based on what one picks out from the metadata file:

1. Navigation Property => ``-ExpandProperty``
2. Property => ``-Property``

**Comment by ztrhgf** [comment]
Thats unfortunate but ok. This whole Graph API needs a lot of love btw :) 
If you want some feedback and what things could be improved check [this post](https://doitpsway.com/graph-api-and-microsoft-graph-sdk-module-gotchas)
