### ISSUE TITLE
Cannot update ﻿onPremisesExtensionAttributes

### ISSUE THREAD

**Issue by joergrenn** [microsoftgraph/msgraph-sdk-powershell#1854]
I am unable to update the user property "onPremisesExtensionAttributes" using the update-mguser cmdlet.
The following cmd does not work:
`Update-MgUser -UserId <uid> -OnPremisesExtensionAttributes @{extensionAttribute1 = "Test123"}`
I get the error message: 
>Update-MgUser_UpdateExpanded: Unable to update the specified properties for objects that have originated within an external service.

Reading the Extension Attributes works no problem:
`(get-mguser -UserId <uid> -Property "id,displayName,onPremisesExtensionAttributes").OnPremisesExtensionAttributes`
 
 I can update the extension attributes without issues using the ExchangeOnline Powershell or the ExchangeOnline Admin Center, but not via the GraphApi.
 
 Before someone asks, I should mention. These are cloud only user objects. They are not (and have never been) synched from on-prem.  Then I would understand why it does not work.

**Comment by ericmatenaer** [comment]
Give this a try :) 

`$params = @{
    onPremisesExtensionAttributes = @{
        extensionAttribute4 = $sid
    }
}

Update-MgUser -UserId <uid> -BodyParameter $params`

**Comment by joergrenn** [comment]
Hello @ericmatenaer ,

thanks for the suggestion.
I gave it a try, but I am getting the same error message. :(

**Comment by peombwa** [comment]
Sorry for the delayed response.

@joergrenn, this is a service error (`-Debug`). Please see the explanation at https://learn.microsoft.com/en-us/answers/questions/456452/cant-edit-extension-attributes-with-graph-api.

Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from API experts if the linked answer doesn't apply to you.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

**Comment by joergrenn** [comment]
Hello @peombwa ,
what do you mean by "service error (-Debug)"?
After reading the explanation you linked to, I understand this is a limitation of the Graph API?
Do you agree?
So I think that you cannot to anything in the Powershell SDK at this point.
Then you can close this issue here. 
I will try to take this to the graph api support.
thanks

**Comment by peombwa** [comment]
I meant using `-Debug` switch to inspect the response from the service - https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug.

That's right. This is an API limitation. I'd recommend you open a service feature request for this scenario at https://developer.microsoft.com/en-us/graph/support.

Closing as external.
