### ISSUE TITLE
Error using Connect-MgGraph with Microsoft live/personal account

### ISSUE THREAD

**Issue by mikef-nl** [microsoftgraph/msgraph-sdk-powershell#1857]
When trying to use `Connect-MgGraph -Scopes Tasks.ReadWrite,Tasks.ReadWrite.Shared` we receive the following when authenticating with a Microsoft personal/live account:

Error details: error invalid_request error_description: The parameters 'username' and 'login_hint' cannot both be provided.

It did work in the past and we have tried version 1.23.0 of the SDK which gives the same error.

**Comment by peombwa** [comment]
I'm not able to reproduce this on my end using a personal account. However, what is clear is that `Tasks.ReadWrite.Shared` does not support Microsoft personal accounts - https://learn.microsoft.com/en-us/graph/permissions-reference#tasks-permissions.

Could try consenting to just `Connect-MgGraph -Scopes Tasks.ReadWrite`, which supports Microsoft personal account, to see if this fixes the error.
