### ISSUE TITLE
Get-MgSubscribedSKU does not show subscriptions

### ISSUE THREAD

**Issue by Obenscripe** [microsoftgraph/msgraph-sdk-powershell#1868]
Get-MgSubscribedSKU does not show subscriptions. it shows the total owned of each license!!
Get-MgSubscribedSKU is listed as the replacement for both Get-MsolSubscription and Get-MsolAccountSku here...

https://learn.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0#msonline-to-microsoft-graph-powershell

...but these two MSOL commands are very different. 
Get-MsolAccountSku lists the SKU's currently owned. Get-MsolSubscription lists the individual subscriptions. I have a report which uses Get-MsolSubscription but as yet there is no replacement mgGraph command. 

Please Can we have additional switches on Get-MgSubscribedSKU to show subscriptions or a new command. This may be related to work items 1338153 & 2105064.  Is it possible for an ETA for this functionality?
Many Thanks
Dan

**Comment by peombwa** [comment]
Please open a service feature request for the API at https://developer.microsoft.com/en-us/graph/support if the API does not return the expected properties.

`Get-MgSubscribedSKU` simply calls the REST API, which is documented at https://learn.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-1.0&tabs=http:
> Get the list of commercial subscriptions that an organization has acquired. For the mapping of license names as displayed on the Azure portal or the Microsoft 365 admin center against their Microsoft Graph skuId and skuPartNumber properties, see [Product names and service plan identifiers for licensing](https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference).

The commands in this module are limited to what's supported by the Microsoft Graph API.
