### ISSUE TITLE
Get-MGUser filter onPremisesUserPrincipalName

### ISSUE THREAD

**Issue by thanordic** [microsoftgraph/msgraph-sdk-powershell#1869]
Hi,

Im trying to filter on onPremisesUserPrincipalName. But this does not return any reaults.
`get-mguser -filter "onPremisesUserPrincipalName eq 'xxxx@xxxx'" -Property SignInActivity,lastPasswordChangeDateTime,onPremisesUserPrincipalName -ConsistencyLevel eventual`

If i filter on UserPrincipalName the object is returned. And i can see the property of onPremisesUserPrincipalName is correct.
`get-mguser -filter "UserPrincipalName eq 'xxxx@xxxx'" -Property SignInActivity,lastPasswordChangeDateTime,onPremisesUserPrincipalName -ConsistencyLevel eventual`

Any ideas?

**Comment by TestagonEins** [comment]
"onPremisesUserPrincipalName" is not part of accepted filter query as described [here](https://learn.microsoft.com/en-us/graph/aad-advanced-queries)

**Comment by thanordic** [comment]
Sorry, I didn't know that. Thanks for educating me :)
