### ISSUE TITLE
[v2] Investigate Intermittent Runtime Error in PS 5.1

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#1872]
Some customers have reported getting runtime exceptions when using v2.x preview in PowerShell 5.1.

**Comment by SeniorConsulting** [comment]
Hi peombwa,

Was this issue the "An error occurred while sending the request"? issue?
![image](https://user-images.githubusercontent.com/110941550/228957419-1a94e8a6-35e6-48c3-9a01-b371851f0fd0.png)

I've seen this issue in both VS Code, and running on Azure Automation. If this isn't the issue you've described, then I'll raise a separate issue.

**Comment by peombwa** [comment]
@SeniorConsulting, I'll close this as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1916. We will investigate and provide a fix once we figure out what the root cause is.
