### ISSUE TITLE
Get-MgReportFormUserActivityUserDetail command not found exception

### ISSUE THREAD

**Issue by antoinegenot** [microsoftgraph/msgraph-sdk-powershell#1875]
When trying to use cmdlet _Get-MgReportFormUserActivityUserDetail_, I only get following exception :

> CategoryInfo          : ObjectNotFound: (Get-MgReportFormUserActivityUserDetail:String) [], ParentContainsErrorRecordException   
> FullyQualifiedErrorId : CommandNotFoundException

Same problem occurred on versions 1.23.0 and 2.0.0-preview5
Is it because the graph API is still in Beta ?
`https://graph.microsoft.com/beta/reports/microsoft.graph.getFormsUserActivityUserDetail(period='{period_value}')`
Is it possible to use it in an other way ?

As a workaround, I figured out that I can call the API with cmdlet Invoke-MgGraphRequest but I must handle pages (limitation of maximum 999 elements by call)...
`Invoke-MgGraphRequest -Method GET -Uri ("https://graph.microsoft.com/beta/reports/getFormsUserActivityUserDetail(period='{period_value}')?top=999")`

**Comment by peombwa** [comment]
@antoinegenot, the command exists in both versions. In:
-  v1.23.0, you must use `Select-MgProfile beta` before running beta commands.
- v2.0.0-preview5, the command exists as `Get-MgBetaReportFormUserActivityUserDetail` as explained in the upgrade guide at https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/docs/upgrade-to-v2.md#command-names.

You can always use `Find-MgGraphCommand` to look-up commands by URLs. For example:
``` powershell
Find-MgGraphCommand -Uri "https://graph.microsoft.com/beta/reports/microsoft.graph.getFormsUserActivityUserDetail(period='{period_value}')"

   APIVersion: beta

Command                                Module  Method URI                                                  OutputType Permissions Variant
                                                                                                                                  s
-------                                ------  ------ ---                                                  ---------- ----------- -------
Get-MgReportFormUserActivityUserDetail Reports GET    /reports/getFormsUserActivityUserDetail(date={date})            {}          {Get, …
```

**Comment by antoinegenot** [comment]
Thanks @peombwa, you are right I needed to use Select-MgProfile Beta.

Unlike other GraphReports cmdlets, only first elements are returned and the output is not in the same format.
So, I would continue to call /reports/getFormsUserActivityUserDetail API myself until those points are not resolved.

**Comment by peombwa** [comment]
Thanks for pointing that out!

The command does not support paging due to how the API response is currently defined in the service metadata. The service metadata says the API should return a file (stream type), yet the API returns JSON. This mismatch leads us to anticipate the wrong response type when generating the command. This is why the command does not support paging.

I've transferred the issue to the metadata repo at https://github.com/microsoftgraph/msgraph-metadata/issues/304 for this to be fixed.
