### ISSUE TITLE
Get-MgGroup doesn't return MembersWithLicenseErrors property

### ISSUE THREAD

**Issue by ztrhgf** [microsoftgraph/msgraph-sdk-powershell#1878]
Command Get-MgGroup doesn't return property MembersWithLicenseErrors even though direct api call does as can be seen in the screenshot bellow 
![image](https://user-images.githubusercontent.com/2930419/225273098-8aa32d86-cc7d-48cb-ae47-e520169c93bc.png)

**Comment by peombwa** [comment]
The command to use is `Get-MgGroupMemberWithLicenseError`. `MembersWithLicenseErrors` is a relationship of `Group` (exists as an API path), not a property.

Please use `Find-MgGraphCommand` to lookup commands by URLs. See https://learn.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-command.
``` powershell
➜ Find-MGgraphCommand -Uri "https://graph.microsoft.com/v1.0/groups/{group-id}/membersWithLicenseErrors"

   APIVersion: v1.0

Command                           Module Method URI                                         OutputType                     Permissions Variants
-------                           ------ ------ ---                                         ----------                     ----------- --------
Get-MgGroupMemberWithLicenseError Groups GET    /groups/{group-id}/membersWithLicenseErrors IMicrosoftGraphDirectoryObject {}          {List}

   APIVersion: beta

Command                               Module      Method URI                                         OutputType                     Permissions Variants
-------                               ------      ------ ---                                         ----------                     ----------- --------
Get-MgBetaGroupMemberWithLicenseError Beta.Groups GET    /groups/{group-id}/membersWithLicenseErrors IMicrosoftGraphDirectoryObject {}          {List}
```

**Comment by ztrhgf** [comment]
So why is MembersWithLicenseErrors shown in Get-MgGroup command output as a property? This is super confusing...

**Comment by peombwa** [comment]
[Relationship properties](https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#relationships) are included in the response object because some relationship properties can be expanded with `$expand`.

The naming convention of the commands in this module follows the naming of API paths. Customers are encouraged to consult the API reference docs to find which API/command to use for their scenarios. See https://learn.microsoft.com/en-us/powershell/microsoftgraph/navigating#command-naming-conventions.

**Comment by ztrhgf** [comment]
So you are telling me that every time I use new property that is being returned via some command, I need to check whether it returns some data. Because it can be a relationship property that can be expanded (or not and therefore will be always empty)? Sorry, but this is insane and makes graph api even more user-unfriendly.
