### ISSUE TITLE
Get-MgGroupDelta seems completely broken

### ISSUE THREAD

**Issue by gfree76** [microsoftgraph/msgraph-sdk-powershell#1879]
Documentation says that it can be used with -Filter.  Using the -Filter parameter results in 
```
Get-MgGroupDelta_Delta1: Filter not supported.
```
Using the -Search parameter doesn't seem to filter either, but it also doesn't error. The -Top parameter does not limit the number of returned items.

**Comment by peombwa** [comment]
Thanks for following up on this.

Some of these parameters have known API limitations that are documented at https://learn.microsoft.com/en-us/graph/delta-query-overview#optional-query-parameters.

`-Filter` /`$filter` is supported as described in the link above:
> Scoping filters allow you to track changes to one or more specific users or groups by object ID. For example, the following request returns changes for the groups matching the IDs specified in the query filter.

``` PowerShelll
Get-MgGroupDelta -Filter "id eq '477e9fc6-5de7-4406-bb2a-7e5c83c9ae5f' or id eq '004d6a07-fe70-4b92-add5-e6e37b8acd8e'"
```

Unfortunately, the service schema does not currently describe what parameters are not supported by the API for us not to generate them. I've opened an issue at https://github.com/microsoftgraph/msgraph-metadata/issues/298 to track this.

**Comment by gfree76** [comment]
If that's the case, then the error message is incorrect. -Filter IS supported, just not with the supplied filter. So it should be something like 
`Get-MgGroupDelta_Delta1: Filter only supports the id field with the eq operator`
