### ISSUE TITLE
getEmailActivityUserDetail syntax

### ISSUE THREAD

**Issue by Brownin88** [microsoftgraph/msgraph-sdk-powershell#1889]
I'm trying to use the powershell graph sdk to drill into reports of mail sent from users seeing as MS keep revoking all the useful stuff from powershell and cmdlets. I can do the full lookup using the following syntax in powershell 

get-EmailActivityUserDetail -period D30 -outfile <path.csv>

or in graph explorer:
GET https://graph.microsoft.com/beta/reports/getemailactivityuserdetail(period='D30')?$format=application/json

But I'm trying as per all the documentation (which is vague) to use the -inputobject parameter switch with a very simple hashtable of:

@{userid="emailaddress@example.com"} I also tried using the @{userid="<azure object id>"}

to get a limited view of data for a particular user

but I keep getting a failure: 

"Get-MgReportEmailActivityUserDetail : Parameter set cannot be resolved using the specified named parameters. "

There is no guidance, no syntax examples or anything in MS documents to help on this just use -inputobject with the IreportsIdentity syntax which is just generic and unclear.

Can you help please

**Comment by salbeck-sit** [comment]
I think you need to include Period or Date in the InputObject hash-table as you can't specify -InputObject with either -Period or -Date. See description of possible properties at the bottom of https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.reports/get-mgreportemailactivityuserdetail?view=graph-powershell-1.0

**Comment by peombwa** [comment]
The [InputObject](https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/two-ways-to-accept-pipeline-input-in-powershell/ba-p/258883) is a generic name used for a parameter that takes pipeline input. It's part of PowerShell's naming convention and there is nothing special about it.

You can use [PowerShell's splatting](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.3) technique to pass a hashtable to the command as such:
``` powershell
$Hash = @{ Period = "D7"; OutFile = "test.csv" }
Get-MgReportEmailActivityUserDetail @Hash
# Or
$Hash = @{ Period = "D7" }
Get-MgReportEmailActivityUserDetail @Hash -OutFile "test.csv" 
```
