### ISSUE TITLE
0.5.0 cmdlets referencing microsoft.graph.authentication version 0.2.0.0

### ISSUE THREAD

**Issue by MichaelLaMontagne** [microsoftgraph/msgraph-sdk-powershell#189]
installed latest version on PSGallery 0.5.0 via Install-Module Microsoft.Graph -Repository PSGallery -force. Able to use connect-graph but running get-mguser or other cmdlets returns: 
"Get-MgUser : Could not load file or assembly 'Microsoft.Graph.Authentication, Version=0.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified."

**Comment by NikCharlebois** [comment]
Looks like it works with PowerShell 7.0.

**Comment by peombwa** [comment]
We've tacked this issue to a hard dependency issue with PowerShell 5.1. As @nickgmicrosoft said, it works with PowerShell 7.0. We are currently working on a fix on our end to address this.

**Comment by peombwa** [comment]
This has now been fixed by 0.5.1. Run `Update-Module Microsoft.Graph​​​​​​​` to get the latest modules.

**Comment by MichaelLaMontagne** [comment]
Confirmed resolution.
