### ISSUE TITLE
Add the /Admin/ Path to the Module Mapping Config

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#1890]
Endpoints under the /admin (e.g. https://learn.microsoft.com/en-us/graph/api/adminreportsettings-get?view=graph-rest-beta&amp%3Btabs=http&tabs=http) are not currently included in any of the PowerShell module and need to be.

**Comment by peombwa** [comment]
Fixed by #1936. The commands will land in v2.
