### ISSUE TITLE
Get-Mguser in msgraph beta version cannot add parameter '-Property' 

### ISSUE THREAD

**Issue by caiwan-msft** [microsoftgraph/msgraph-sdk-powershell#1893]
Issue: 
Get-Mguser in msgraph beta version cannot add parameter '-Property' 

![image](https://user-images.githubusercontent.com/8428301/226833847-b77f77aa-ec47-45d9-9d2c-f6e798841394.png)

Compare with msgraph v1.0: 
![image](https://user-images.githubusercontent.com/8428301/226834221-432c0df8-a5e5-4336-a74f-9a14b7db4b4d.png)

Thanks, 
caiwan

**Comment by peombwa** [comment]
Thanks for following up on this.

This looks like a service issue in Microsoft Graph China cloud. As per the API reference, `$` prefix is optional in `beta` - https://learn.microsoft.com/en-us/graph/query-parameters.
> On the beta endpoint, the $ prefix is optional. For example, instead of $filter, you can use filter. On the v1 endpoint, the $ prefix is optional for only a subset of APIs. For simplicity, always include $ if using the v1 endpoint.

The SDK currently assumes `$` is optional in beta as per the above guideline. Infact, the same request works as expected when calling beta endpoint in Microsoft Graph global cloud:
> Get-MgUser -Select displayName, lastPasswordChangeDateTime | select DisplayName, LastPasswordChangeDateTime
![image](https://user-images.githubusercontent.com/7061532/227285530-3c63bb36-7c1b-425f-9b80-eb06188486ee.png)

We will use this issue to track adding `$` prefix to all OData query paramters in both v1.0 and beta to support all National Clouds.

**Comment by peombwa** [comment]
Fixed by #1993. The fix will ship as part of v2.0.0-preview9, scheduled for release this week.
