### ISSUE TITLE
Connect-MgGraph is not getting TenantId on 2.0.0-preview7

### ISSUE THREAD

**Issue by TestagonEins** [microsoftgraph/msgraph-sdk-powershell#1901]
My runbook graph cmdlets (get-mgapplication/get-mguser) started failing with the following statement: 
_Tenant id cannot be null. You can locate your tenant id by following the instructions listed here: https://docs.microsoft.com/partner-center/find-ids-and-domain-names_
When I performed Get-MgContext after connecting to Graph (with certificate) I can see that TenantId is empty (though I'm getting "Welcome to Microsoft Graph!" message). The same behavior occurs on the machine locally.
I tried to specify tenantId via variable or without dashes, it is still not applying and remains empty.
However, cmdlets are working when connected to Graph without certificate, though TenantId is still empty.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

I can indeed confirm that this is a bug emanating from how the claims in the access token are processed by the client. We will issue a patch to resolve the bug shortly. As a workaround, please fallback to preview6 as we address the bug.

**Comment by peombwa** [comment]
We've just issued a patch with a fix for the bug. Please update to the latest preview version. See https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview8 for more details.
