### ISSUE TITLE
Get-MgTeam command doesn't work with -All option

### ISSUE THREAD

**Issue by marikamiwa** [microsoftgraph/msgraph-sdk-powershell#1907]
According to the website below, it seems Get-MgTeam work with -All option.
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.teams/get-mgteam?view=graph-powershell-1.0

However, Get-MgTeam -All or Get-MgTeam won't work without $teamId.

I tried HTTP request GET /teams/{team-id} and it seems this request wouldn't work without {team-id}
https://learn.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&tabs=powershell

I assume the description about -All option in the first website needs to be fixed. 

I would appreciate your help in resolving this issue.
Thank you in advance.

**Comment by peombwa** [comment]
Thanks for following up on this.

The command reference doc is stale and needs to be updated. I've transferred the issue to the right repo at https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/234 for this to be fixed.

`-All` is not supported by the command in v1.0. The offline help, that ships with the SDK, is up-to-date though.
