### ISSUE TITLE
Getting existing access_token after Connect-Graph

### ISSUE THREAD

**Issue by jpalo** [microsoftgraph/msgraph-sdk-powershell#191]
Is there any way to get hold of the access_token fetched in `Connect-Graph`? Reasoning is that I need to fall back to `Invoke-RestMethod` in certain Graph API calls while waiting for this promising PowerShell SDK to evolve, and I'd like to reuse the access token I already have.

**Comment by MIchaelMainer** [comment]
See #127

**Comment by darrelmiller** [comment]
We don't actually have an easy way to get the token because we only ask MSAL for the token right before making the request.  However, the issue #127 shows a way to make custom calls. We will be wrapping this with a helper cmdlet in the near future.

**Comment by jpalo** [comment]
Thanks, let's close this for now.
