### ISSUE TITLE
Error on New-MgDeviceManagementDeviceEnrollmentConfiguration

### ISSUE THREAD

**Issue by LostLogic** [microsoftgraph/msgraph-sdk-powershell#1914]
I've been trying (and failing) to create a new Windows Hello for Business policy with the New-MgDeviceManagementDeviceEnrollmentConfiguration cmdlet.

Command 1:
```
$json = '{
        "@odata.type": "#microsoft.graph.deviceEnrollmentWindowsHelloForBusinessConfiguration",
        "displayName": "Display Name value",
        "description": "Description value",
        "priority": 8,
        "version": 7,
        "pinMinimumLength": 0,
        "pinMaximumLength": 0,
        "pinUppercaseCharactersUsage": "required",
        "pinLowercaseCharactersUsage": "required",
        "pinSpecialCharactersUsage": "required",
        "state": "enabled",
        "securityDeviceRequired": true,
        "unlockWithBiometricsEnabled": true,
        "remotePassportEnabled": true,
        "pinPreviousBlockCount": 5,
        "pinExpirationInDays": 3,
        "enhancedBiometricsState": "enabled"
      }'
```

Command 2

```
New-MgDeviceManagementDeviceEnrollmentConfiguration -BodyParameter $json

      $windowsHelloForBusiness = @{
        "@odata.type"= "#microsoft.graph.deviceEnrollmentWindowsHelloForBusinessConfiguration"
        "pinMinimumLength" = 0
        "pinMaximumLength" = 0
        "pinUppercaseCharactersUsage" = "required"
        "pinLowercaseCharactersUsage" = "required"
        "pinSpecialCharactersUsage" = "required"
        "state" = "enabled"
        "securityDeviceRequired" = $true
        "unlockWithBiometricsEnabled" = $true
        "remotePassportEnabled" = $true
        "pinPreviousBlockCount" = 5
        "pinExpirationInDays" = 3
        "enhancedBiometricsState" = "enabled"
      }

New-MgDeviceManagementDeviceEnrollmentConfiguration -DisplayName "Display Name value" -Description "Description value" -Priority 8 -Version 7 -AdditionalProperties $windowsHelloForBusiness
```

Both commands return the same error:
```
New-MgDeviceManagementDeviceEnrollmentConfiguration_CreateExpanded: {
  "_version": 3,
  "Message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 8bdd2bed-4e53-4725-9fb5-572f56631984 - Url: https://fef.msub06.manage.microsoft.com/StatelessOnboardingService/deviceManagement/deviceEnrollmentConfigurations?api-version=2022-12-05",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
```

I'm authenticated with DeviceManagementServiceConfig.ReadWrite.All and DeviceManagementConfiguration.ReadWrite.All, so it shouldn't be a permission issue. I'm also able to return the already configured default Windows Hello for Business policy with
`Get-MgDeviceManagementDeviceEnrollmentConfiguration | Where-object -Property Description -like -Value "*Windows Hello*"`

Am I doing something wrong, or have I hit a bug somewhere?

The licensing level of my tenant is E3.

Edit: Fix formatting in post due to hash sign referencing other issues which was not my intent

**Comment by peombwa** [comment]
Thanks for following up on this.

Running the command `-Debug` points to this being a service error. You've already consented to the required permissions and the command sending the correct request body as shown at [Create deviceEnrollmentWindowsHelloForBusinessConfiguration](https://learn.microsoft.com/en-us/graph/api/intune-onboarding-deviceenrollmentwindowshelloforbusinessconfiguration-create?view=graph-rest-1.0#request). The same can also be reproduced in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=deviceManagement%2FdeviceEnrollmentConfigurations&method=POST&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=eyJAb2RhdGEudHlwZSI6IiNtaWNyb3NvZnQuZ3JhcGguZGV2aWNlRW5yb2xsbWVudFdpbmRvd3NIZWxsb0ZvckJ1c2luZXNzQ29uZmlndXJhdGlvbiIsImRpc3BsYXlOYW1lIjoiRGlzcGxheSBOYW1lIHZhbHVlIiwiZGVzY3JpcHRpb24iOiJEZXNjcmlwdGlvbiB2YWx1ZSIsInByaW9yaXR5Ijo4LCJ2ZXJzaW9uIjo3LCJwaW5NaW5pbXVtTGVuZ3RoIjowLCJwaW5NYXhpbXVtTGVuZ3RoIjowLCJwaW5VcHBlcmNhc2VDaGFyYWN0ZXJzVXNhZ2UiOiJyZXF1aXJlZCIsInBpbkxvd2VyY2FzZUNoYXJhY3RlcnNVc2FnZSI6InJlcXVpcmVkIiwicGluU3BlY2lhbENoYXJhY3RlcnNVc2FnZSI6InJlcXVpcmVkIiwic3RhdGUiOiJlbmFibGVkIiwic2VjdXJpdHlEZXZpY2VSZXF1aXJlZCI6dHJ1ZSwidW5sb2NrV2l0aEJpb21ldHJpY3NFbmFibGVkIjp0cnVlLCJyZW1vdGVQYXNzcG9ydEVuYWJsZWQiOnRydWUsInBpblByZXZpb3VzQmxvY2tDb3VudCI6NSwicGluRXhwaXJhdGlvbkluRGF5cyI6MywiZW5oYW5jZWRCaW9tZXRyaWNzU3RhdGUiOiJlbmFibGVkIn0=).

Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support as this is a service issue. Rember to include the `requestId` and `date` of the affected request in your ticket/question. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for details on how to retrieve the `requestId` and `date`.

### Repro Steps:
``` powershell
$Body = @{
  "@odata.type" = "#microsoft.graph.deviceEnrollmentWindowsHelloForBusinessConfiguration"
  "displayName" = "Display Name value"
  "description" = "Description value"
  "priority" = 8
  "version" = 7
  "pinMinimumLength" = 0
  "pinMaximumLength" = 0
  "pinUppercaseCharactersUsage" = "required"
  "pinLowercaseCharactersUsage" = "required"
  "pinSpecialCharactersUsage" = "required"
  "state" = "enabled"
  "securityDeviceRequired" = $true
  "unlockWithBiometricsEnabled" = $true
  "remotePassportEnabled" = $true
  "pinPreviousBlockCount" = 5
  "pinExpirationInDays" = 3
  "enhancedBiometricsState" = "enabled"
}

New-MgDeviceManagementDeviceEnrollmentConfiguration -BodyParameter $Body -Debug
```

This repository is intended for issues related to the functionality of the module. We may not be the best place to answer some queries that are tied to the functionality of the API.

**Comment by LostLogic** [comment]
I'll follow up with MS Graph support directly and report back once they've come back to me.
Thanks Peter
