### ISSUE TITLE
no ability to setup linked Sign-on  for Azure Enterprise App

### ISSUE THREAD

**Issue by tikesavage** [microsoftgraph/msgraph-sdk-powershell#1915]
there is not option in new-mgapplication or update-mgappliaction to set the azure enterprise app as a "linked" for single sign on method,  NOR is there a way to populate the "sign on URL"  value for this.

here is the GUI instructions for ref.
https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/configure-linked-sign-on

i wanted to automate setting up an azure app per a physical location and set this to a local server IP and port (https://xxx.xxx.xxxx.xxx:8443)   so any user in the Azure AD group of that associate location would see it in their my apps portal.

We have hundreds of physical locations.  and this is preventing roll out

**Comment by SeniorConsulting** [comment]
I think you're looking at the wrong cmdlet. The MgApplication cmdlets are more for App Registrations.

Have a nosey into Get-MgServicePrincipal. The property you're probably interested in is LoginUrl. I'd also probably start with the beta endpoint while you sort out your properties:
https://learn.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-beta&tabs=http
And here's your reference for Get-MgServicePrincipal:
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.applications/get-mgserviceprincipal?view=graph-powershell-1.0

I'd recommend starting by interrogating an existing linked sign-on Enterprise Application.
$MyApplication = Get-MgServicePrincipal -ServicePrincipalId [YourEnterpriseApplicationObjecIdHere]
$MyApplication.LoginUrl

From here you should be able to build out the process using New-MgServicePrincipal
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.applications/new-mgserviceprincipal?view=graph-powershell-1.0

**Comment by tikesavage** [comment]
ahh okay let me   play around with that,  thank ya!

**Comment by tikesavage** [comment]
kind of akward, you need to use new-mgapplication  then take that ID and feed it to new-mgserviceprincipal.   wish they were just combined with extra switches.

should do what i want. thank you

**Comment by peombwa** [comment]
Thanks for the pointers @SeniorConsulting!

@tikesavage, this is by design.

What you are doing is "instantiating" a service principal (enterprise app) with an application's appId. See Azure AD's conceptual [doc on applications and service principals](https://learn.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals) for more details:
> An application object is used as a template or blueprint to create one or more service principal objects. A service principal is created in every tenant where the application is used. Similar to a class in object-oriented programming, the application object has some static properties that are applied to all the created service principals (or application instances).
