### ISSUE TITLE
No way to get Hardware Token assigned to User in Azure AD.

### ISSUE THREAD

**Issue by tikesavage** [microsoftgraph/msgraph-sdk-powershell#1921]
Have hundred users or so with Hardware Oath tokens and i need to automate some reporting on this. there needs to be a CMDlet to query for hardware tokens based on the user ID or UPN AND the serial number of the token in Azure.

also the get-mguser object needs an attribute object for the token as well with all relevant hardware token information.

tried running the software token to see if it would possible scoppe it. but nope.
and i am running this cmdlet Get-MgUserAuthenticationSoftwareOathMethod -userid {UserPrincipalNameorID} and it returns nothing at all. (makes sense i guess)

i am looking at the users in Azure Active Directory > Security > Multifactor authentication > OATH tokens, and have tried activated and non-activated tokens.

**Comment by andrueastman** [comment]
Transferring to the Powershell Repo as the questions seems to be powershell related.

**Comment by SeniorConsulting** [comment]
This is in the MS Graph SDK PowerShell forum. Currently the Microsoft Graph API does not support querying _**hardware**_ OATH tokens. See the second table in the link below:
https://learn.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0#what-authentication-methods-can-be-managed-in-microsoft-graph

You used to be able to do this with the [MSOnline module](https://learn.microsoft.com/en-us/powershell/module/msonline/?view=azureadps-1.0) (Get-MSOLUser), and by looking at the StrongAuthenticationMethods (Something like (Get-MsolUser -UserPrincipalName Bob@contoso.com).StrongAuthenticationMethods), but I believe that that module has been/is being deprecated.
https://learn.microsoft.com/en-us/powershell/azure/active-directory/overview?view=azureadps-1.0&preserve_view=true

**Comment by peombwa** [comment]
+1 to SeniorConsulting's response. The API does not support retrieving hardware tokens.

I'd recommend you open a feature request at https://developer.microsoft.com/graph/support for the API owners to consider your scenario.

This issue will be closed because this forum is for MS Graph SDK PowerShell issues only.
