### ISSUE TITLE
Get-MgUser returns error when retrieving property DeviceEnrollmentLimit

### ISSUE THREAD

**Issue by ztrhgf** [microsoftgraph/msgraph-sdk-powershell#1926]
When retrieving property DeviceEnrollmentLimit following error is returned
![image](https://user-images.githubusercontent.com/2930419/230404643-dd1b9675-e029-4944-990b-f6a819cd9414.png)

Version 1.20.0 of module is used.
![image](https://user-images.githubusercontent.com/2930419/230404885-7382b20e-d2ae-43a4-a54b-b05c95a84d22.png)

**Comment by peombwa** [comment]
Thanks for following up on this.

Using `-Debug` parameter on the commend points this being a service error. The error message, though not clear, hints to the API not supporting `$select` on `DeviceEnrollmentLimit` property. Unfortunately, this is not called out in the [API reference doc](https://learn.microsoft.com/en-us/graph/api/resources/intune-shared-user?view=graph-rest-beta#properties).

The error can also be reproduced by making a REST call to the API `GET https://graph.microsoft.com/v1.0/users?$select=DeviceEnrollmentLimit` via [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24select%3DDeviceEnrollmentLimit&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com).

Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from API owner.

This repository is intended for issues related to the functionality of the modules (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

**Comment by ztrhgf** [comment]
OK, so why is command/module that you manage, returning property that will be always empty? This doesn't make sense and is super confusing.
