### ISSUE TITLE
OnPremisesImmutableId doesnt return any value

### ISSUE THREAD

**Issue by jayarvin** [microsoftgraph/msgraph-sdk-powershell#1933]
Back in the old SDK (MSOL or Azure Active Directory Powershell, you can get (Get-MsolUser / Get-AzureADUser) an AAD user and there is a property called ImmutableID.

In AzPowershell (Get-AzADUser) or Microsoft Graph Powershell (Get-MgUser), you can get  an AAD User and now the property is called OnPremisesImmutableId but it is not returning any value even though the ImmutableId has value (using the old cmdlets)

To test if I created an AAD account (which by default wont have ImmutableId) and when I executethe following:

1. Verify if the ImmutableID is Null by using Get-AzureADUser or Get-MsolUser
2. Set the a value to the OnPremisesImmutableId by using Update-MgUser -UserId "xxxx@myorg.org" -OnPremisesImmutableId "xxxx@myorg.org" 
3. Execute Get-MgUser -UserId "xxxx@myorg.org"  | fl and OnPremisesImmutableId doesn't have any value.
4. Re-execute step 1 and I see the value I set in step 2

**Comment by SeniorConsulting** [comment]
Hi Jayarvin

To retrieve specific properties using the Graph API (and Graph PowerShell module), you'll need to specify the property you want to return. But just note that requesting one property alone will only return **_that_** property.

Try running:
Get-MgUser -UserId test.user@contoso.com -Property OnPremisesImmutableId

Or to make sure you've got the correct user record:
Get-MgUser -UserId test.user@contoso.com -Property OnPremisesImmutableId,UserPrincipalName | Format-List UserPrincipalName,OnPremisesImmutableId

**Comment by peombwa** [comment]
Also, see API reference at https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties for properties that are only returned on `$select`(`-Property`). In this case, `OnPremisesImmutableId`:
> This property is used to associate an on-premises Active Directory user account to their Azure AD user object. This property must be specified when creating a new user account in the Graph if you are using a federated domain for the user's userPrincipalName (UPN) property. NOTE: The $ and _ characters cannot be used when specifying this property.

> Returned only on $select. Supports $filter (eq, ne, not, ge, le, in)..

**Comment by albsol** [comment]
Hi SeniorConsulting,

I've tried your commands, but they don't work :-(
It seems Get-MgUser probabley has a bug, it's not able to display existing OnPremisesImmutableId attribute values.

I've tried this command, returns nothing:
> Get-MgUser -UserId a.alvarez@office365.upc.edu -Property OnPremisesImmutableId
>
>DisplayName Id Mail UserPrincipalName
>

This one only returns just UserPrincipalName attribute:
> Get-MgUser -UserId username@federated.domain.edu -Property UserPrincipalName,OnPremisesImmutableId
>
> DisplayName Id Mail UserPrincipalName
>
>                    username@federated.domain.edu


It I tried this other command where OnPremisesImmutableId attribute returns a null value (but its value exists !!!, it can be shown by Get-MsolUser command as ImmutableId attribute):

> Get-MgUser -UserId username@federated.domain.edu  | Select-Object -Property UserPrincipalName,OnPremisesImmutableId| fl
>
>UserPrincipalName     : username@federated.domain.edu 
>OnPremisesImmutableId :
>


This MSOnline command is able to return the ImmutableId attribute:
> Get-MsolUser -UserPrincipalName username@federated.domain.edu | Select-Object -Property UserPrincipalName,ImmutableId | fl
>
>    UserPrincipalName : username@federated.domain.edu 
>    ImmutableId : 1111111ceeeeeeeeeeeeeeeae8bc699c229999999999802e64bb8d666
>

I've been able to reproduce this issue in two diferent environments:

**Windows Environment:**
- OS: Windows Server 2016 Standard
- Architecture: x64

- Microsoft.Graph version:
PS C:\Users\Administrator> Get-Module Microsoft.Graph*
ModuleType Version    PreRelease Name                                ExportedCommands

Script     2.24.0                Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext…}
Script     2.24.0                Microsoft.Graph.Users               {Get-MgUser, Get-MgUserCount, Get-MgUserCreatedObject, Get-MgUserCreatedObjectAsServicePrincipal…}


- Powershell version:
PS C:\Users\Administrator> $PSVersionTable

Name                           Value

PSVersion                      5.1.14393.7693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.7693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


**Linux Environment:**
- OS: Ubuntu 20.04.6 LTS"
- Architecture: x64
- Microsoft.Graph version:
PS /root> Get-Module Microsoft.Graph.* | Where-Object {$_.Name -like "Microsoft.Graph.*"} | Format-Table Name,Version -AutoSize
Name                           Version

Microsoft.Graph.Authentication 2.25.0
Microsoft.Graph.Groups         2.25.0
Microsoft.Graph.Users          2.25.0

- Powershell version:
PS /root>  $PSVersionTable

Name                           Value

PSVersion                      7.2.11
PSEdition                      Core
GitCommitId                    7.2.11
OS                             Linux 5.15.0-131-generic #141~20.04.1-Ubuntu SMP Thu Jan 16 18:38:51 UTC 2025
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by duncansmart** [comment]
@albsol This works for me - they key is the `Get-MgUser -Property` parameter:

    Get-MgUser -UserId name@example.com -Property UserPrincipalName,OnPremisesImmutableId | Select-Object UserPrincipalName,OnPremisesImmutableId

**Comment by albsol** [comment]
Thank you @duncansmart , it works !!!

I see it's needed to pass twice the list of properties/attributes, first one into "-Property" and then into "Select-object"
Thank you again.
