### ISSUE TITLE
Update-MgUser: Unable to remove custom security attribute assignment for a single string value

### ISSUE THREAD

**Issue by rolyon** [microsoftgraph/msgraph-sdk-powershell#1938]
Custom security attributes examples
https://learn.microsoft.com/en-us/graph/custom-security-attributes-examples?tabs=http#remove-custom-security-attribute-assignments

To remove a multi-value attribute assignment, I was able to use this syntax:
```
$params = @{
CustomSecurityAttributes = @{
Engineering =@{
"@odata.type" = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue"
Project =@(
)
}
}
}
Update-MgUser -UserId "{userId}" -BodyParameter $params
```

I tried several ways to remove a single string value attribute assignment. For example, I tried using $null. Valid syntax and no errors, but does not remove attribute assignment.
```
$params = @{
CustomSecurityAttributes = @{
Engineering =@{
"@odata.type" = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue"
ProjectDate =$null
}
}
}
Update-MgUser -UserId "{userId}" -BodyParameter $params
```

I tried using an empty string. Valid syntax, but get the following update error:
Update-MgUser_Update1: 'Non empty string value expected for attribute.'. ParameterName: 'Engineering_ProjectDate' ParameterValue: ''.
```
$params = @{
CustomSecurityAttributes = @{
Engineering =@{
"@odata.type" = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue"
ProjectDate =""
}
}
}
Update-MgUser -UserId "{userId}" -BodyParameter $params
```

How do you remove a custom security attribute assignment for a single value?
thanks

**Comment by peombwa** [comment]
Thanks for following up on this.

The SDK does not currently support setting properties to null due to a design limitation with the code generator - https://github.com/Azure/autorest.powershell/issues/961.

As a workaround, please use [Invoke-MgGraphRequest](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-invoke-mggraphrequest) to set the extension properties to null.

``` powershell
$params = @{
	customSecurityAttributes = @{
		Engineering = @{
			"@odata.type" = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue"
			ProjectDate = $null
		}
	}
}

Invoke-MgGraphRequest -Uri "beta/users/{id}" -Method PATCH -Body $params
```

**Comment by peombwa** [comment]
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/833.
