### ISSUE TITLE
validation Status & Validation errors

### ISSUE THREAD

**Issue by DC-BX** [microsoftgraph/msgraph-sdk-powershell#1940]
hi there,
With the MSOL commandlets we can view validation status & validation errors of a user.  I don't see any way of doing this in MG Graph. I 
can see OnPremisesProvisioningErrors which im assuming is DirSyncProvisioningErrors from the msol commandlets but can't see anything on validation status
![image](https://user-images.githubusercontent.com/130675266/231784900-b16d6e7c-db9f-46d7-9d07-37dcc1f436bd.png)

**Comment by SeniorConsulting** [comment]
OK, I _**think**_ what you're trying to do is to retrieve errors which are generated when a user is being synchronised from an on-premises Active Directory environment, into Azure Active Directory using Azure Active Directory Connect.

I assume you've run Get-MgUser, and selected an individual, but didn't get any values for the OnPremisesProvisioningErrors. So let's step through this. If you're using version 1.0 of the PowerShell modules (i.e. not using Select-MgProfile beta), you'll need to select the property to be returned:

`Get-MgUser -UserId Test.User@contoso.com -Property UserPrincipalName,OnPremisesProvisioningErrors | Format-List UserPrincipalName,OnPremisesProvisioningErrors`

Note, **_you'll need to select a user who is actually having issues_** with being synchronised in Azure AD Connect to have a value returned. It won't return a value if everything is OK for that user.

If you're instead hunting for users who have issues, you could try:
```
$Users = Get-MgUser -All -Property UserPrincipalName,OnPremisesProvisioningErrors | Where-Object {$_.OnPremisesProvisioningErrors -ne ""}
$Users
```

I'll post back later on whether you can use something like Get-MgApplicationSynchronization - I'd need to confirm (and noting that it's only available in beta.
https://learn.microsoft.com/en-us/graph/api/resources/synchronization-overview?view=graph-rest-beta

**Comment by DC-BX** [comment]
Thanks for your response, so 'OnPremisesProvisioningErrors'  with a get-mguser  corresponds with DirSyncProvisioningErrors from a get-msoluser.
However this is different from the validationStatus from a get-msoluser:
![image](https://user-images.githubusercontent.com/130675266/232064443-49895c85-8f4e-45e6-afe5-f65f448e0cff.png)
Troubleshooting a user issue:
I can run  get-msoluser -searchstring "Test.User@contoso.com" | select validationstatus
and then 
$errors = (Get-MsolUser -UserPrincipalName "phx-keyer@m01rbsworkspace.onmicrosoft.com").Errors
$errors | foreach-object {"`nService: " + $_.ErrorDetail.Name.split("/")[0]; "Error Message: " + $_.ErrorDetail.ObjectErrors.ErrorRecord.ErrorDescription}
which will return the validation error, one example:
![image](https://user-images.githubusercontent.com/130675266/232066465-ac54e541-87b0-405c-9678-9be69654a58c.png)

**Comment by peombwa** [comment]
@adamedx, can some from your team help with the inquiry?

**Comment by peombwa** [comment]
Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.
