### ISSUE TITLE
Unable to send email using MS Graph API PowerShell Script

### ISSUE THREAD

**Issue by Bala2Gopal** [microsoftgraph/msgraph-sdk-powershell#1941]
Hi,

I am trying to send an email using the below said Graph PowerShell script from the Microsoft article. https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&amp%3Btabs=powershell&tabs=powershell#request

Import-Module Microsoft.Graph.Users.Actions

$params = @{
	message = @{
		subject = "Meet for lunch?"
		body = @{
			contentType = "Text"
			content = "The new cafeteria is open."
		}
		toRecipients = @(
			@{
				emailAddress = @{
					address = "frannis@contoso.onmicrosoft.com"
				}
			}
		)
		ccRecipients = @(
			@{
				emailAddress = @{
					address = "danas@contoso.onmicrosoft.com"
				}
			}
		)
	}
	saveToSentItems = "false"
}

# A UPN can also be used as -UserId.
Send-MgUserMail -UserId $userId -BodyParameter $params

and 

I am getting the below said error message. Can you please help me with the correct powershell script to send an email with MS Graph

Send-MgUserMail : A positional parameter cannot be found that accepts argument '    '.
At line:29 char:1
+ Send-MgUserMail " " $UserId -BodyParameter $par ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Send-MgUserMail], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Send-MgUserMail

**Comment by SeniorConsulting** [comment]
What the error message is telling you that you've entered something immediately after the cmdlet, but before any other parameters. The full command you stated looks correct i.e.
`Send-MgUserMail -UserId $userId -BodyParameter $params`

But the error message suggests that you've entered something different on this line:
`Send-MgUserMail " " $UserId -BodyParameter $par ...`

Note that immediately after Send-MgUserMail, there appears to be two empty quotation marks? What the error is saying is that it was trying to predict what parameter you were trying to use with the quote, but could not. I was able to replicate the error message by duplicating this:
![image](https://user-images.githubusercontent.com/110941550/231899336-b5a1c2bc-1adb-4d52-9043-99b4b3cba24b.png)

Maybe just confirm that you're actually entering Send-MgUserMail <span style="color:red">**`-UserId**</span> $UserID

**Comment by Bala2Gopal** [comment]
Apologies for the delay in responding. We have tried using the correct email address and here is the screenshot of the error message we still are getting
<img width="424" alt="image" src="https://user-images.githubusercontent.com/129751548/232266245-2f7269be-247d-4ed4-8455-d7efde4069d4.png">

**Comment by SeniorConsulting** [comment]
Hi Bala2Gopal. I think you're still getting a bit mixed up with the UserID bit.

Please enter:
`Send-MgUserMail -UserId Bxxxxx.Gxxxxx@Qxxxxx.onmicrosoft.com -BodyParameter $params`

**Comment by Bala2Gopal** [comment]
Thank you very much
We now are able to send the emails with your suggestion.
Thanks again
