### ISSUE TITLE
Get-MgPrivilegedAccessResource issue

### ISSUE THREAD

**Issue by vincentmiens** [microsoftgraph/msgraph-sdk-powershell#1945]
Hi,
I use this command to get all the resources of my tenant. The goal is, with antoher command, to get all the privileged access, direct and elligible.
It works fine, but I see the command does not return all the resources.
I'm connected with a Service Principal, tenant Reader, with the API permissions PrivilegedAccess.Read.AzureResources, PrivilegedAccess.Read.AzureADGroup, PrivilegedAccess.Read.AzureAD
My question is : **why the command is missing results** ?

Command used : **Get-MgPrivilegedAccessResource -PrivilegedAccessId azureResources -All**

Thanks a lot !

**Comment by peombwa** [comment]
Thanks for following up on this.

This sounds like a service issue. As the SDK team, we may not know why the API does not return all the results for your user/app.

Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support as this sounds like a service issue. See  the troubleshooting guide at https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug for more details.

This repository is intended for issues related to the functionality of the SDK. We may not be the best place to answer some queries that are tied to the functionality of the API.

**Comment by vincentmiens** [comment]
If I click on « New support request", I think the ticket will be again on your backlog.
Is it correct ?

[nouveau logo]
Vincent Miens
Développeur - Escouade IaaS Azure

Direction Principale Services Infonuagiques
Mouvement Desjardins




De : Peter Ombwa ***@***.***>
Envoyé : 14 avril 2023 14:09
À : microsoftgraph/msgraph-sdk-powershell ***@***.***>
Cc : Vincent Miens ***@***.***>; Author ***@***.***>
Objet : Re: [microsoftgraph/msgraph-sdk-powershell] Get-MgPrivilegedAccessResource issue (Issue #1945)

COURRIEL EXTERNE CONTENANT UNE PIÈCE JOINTE OU UN LIEN URL / EXTERNAL EMAIL WITH AN ATTACHMENT OR A URL LINK
Soyez vigilant, développez les bons réflexes et ne téléchargez aucune pièce jointe non sollicitée! Au besoin, cliquez sur l'icône Signaler ou faites suivre ce courriel à ***@***.******@***.***>. / Be vigilant, develop the right instincts and do not download any unsolicited attachment! If required, click the Report button or forward the email at ***@***.******@***.***>


Thanks for following up on this.

This sounds like a service issue. As the SDK team, we may not know why the API does not return all the results for your user/app.

Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support as this sounds like a service issue. See the troubleshooting guide at https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug for more details.

This repository is intended for issues related to the functionality of the SDK. We may not be the best place to answer some queries that are tied to the functionality of the API.

-

**Comment by peombwa** [comment]
> If I click on « New support request", I think the ticket will be again on your backlog. Is it correct?

No, the ticket will go to the API support team.

**Comment by vincentmiens** [comment]
Is it correct ?

***@***.***



[nouveau logo]
Vincent Miens
Développeur - Escouade IaaS Azure

Direction Principale Services Infonuagiques
Mouvement Desjardins




De : Peter Ombwa ***@***.***>
Envoyé : 14 avril 2023 14:24
À : microsoftgraph/msgraph-sdk-powershell ***@***.***>
Cc : Vincent Miens ***@***.***>; Author ***@***.***>
Objet : Re: [microsoftgraph/msgraph-sdk-powershell] Get-MgPrivilegedAccessResource issue (Issue #1945)

COURRIEL EXTERNE CONTENANT UNE PIÈCE JOINTE OU UN LIEN URL / EXTERNAL EMAIL WITH AN ATTACHMENT OR A URL LINK
Soyez vigilant, développez les bons réflexes et ne téléchargez aucune pièce jointe non sollicitée! Au besoin, cliquez sur l'icône Signaler ou faites suivre ce courriel à ***@***.******@***.***>. / Be vigilant, develop the right instincts and do not download any unsolicited attachment! If required, click the Report button or forward the email at ***@***.******@***.***>


If I click on « New support request", I think the ticket will be again on your backlog. Is it correct?

No, the ticket will go to the API support team.

-

**Comment by peombwa** [comment]
@vincentmiens, see the API's reliability and support page for more details - https://learn.microsoft.com/en-us/graph/best-practices-concept#reliability-and-support.

**Comment by peombwa** [comment]
Closing as service issue.

Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support for the API owner to investigate why the API is not returning the results as expected.
