### ISSUE TITLE
Get-AzureADPolicy -Type b2bmanagementpolicy mapping to MS Graph module

### ISSUE THREAD

**Issue by chaulagain123** [microsoftgraph/msgraph-sdk-powershell#1946]
Request to map cmdlets from AzureADPreview module to MSGraph PS module to Set the allow or blocklist External collaboration policy using PowerShell.

New-AzureADPolicy -Definition $policyValue -DisplayName B2BManagementPolicy -Type B2BManagementPolicy

Reason: The pink advisory that states "Note: The AzureADPreview Module is not a fully supported module as it is in preview." and we would like to use this command in our PROD ADO runbook.

Reference: https://learn.microsoft.com/en-us/azure/active-directory/external-identities/allow-deny-list#set-the-allow-or-blocklist-policy-using-powershell

**Comment by peombwa** [comment]
Thanks for following up on this.

The commands in this SDK exclusively call the Microsoft Graph API. As such, some features/APIs that were available in AzureAD Graph are not yet available in Microsoft Graph. See https://learn.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta for a list of Microsoft Graph supported policy types.

Based on what's provided in the [API reference docs](https://learn.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta) and https://learn.microsoft.com/en-us/answers/questions/269364/external-collaboration-settings-using-graph-api, it looks like Microsoft Graph API does not currently support managing B2B policy.

Please open a service feature request/question at https://developer.microsoft.com/en-us/graph/support to get assistance from subject matter experts.

This repository is intended for issues related to the functionality of Microsoft Graph PowerShell commands (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.
