### ISSUE TITLE
Update-MgPlannerTaskDetail If-Match need etag of TaskDetail but Get-MgPlannerTaskDetail cannot return etag

### ISSUE THREAD

**Issue by BruceEx** [microsoftgraph/msgraph-sdk-powershell#1950]
When we use Update-MgPlannerTaskDetail to update TaskDetail, ETag value for the plannerTaskDetails is required for If-Match.

However, it seems we cannot get ETag via PowerShell SDK. Get-MgPlannerTaskDetail cannot return ETag. 

Do we have workaround or design change plan?

This issue is reported from Mcrosoft premier customer.

**Comment by SeniorConsulting** [comment]
Gidday Bruce,

Reading into this article here:
https://learn.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-1.0#planner-resource-versioning

I was wondering whether the eTag could be found in a different place, as the Graph API does not return eTag details on neither the [taskdetails](https://learn.microsoft.com/en-us/graph/api/plannertaskdetails-get?view=graph-rest-1.0&tabs=http#response-1), nor the [task](https://learn.microsoft.com/en-us/graph/api/plannertask-get?view=graph-rest-1.0&tabs=http#response-1) itself.

However, I did manage to find an eTag value associated with the [list planner buckets](https://learn.microsoft.com/en-us/graph/api/plannerplan-list-buckets?view=graph-rest-1.0&tabs=powershell#response-1) endpoint, which you can call using the [Get-MgPlannerPlanBucket](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.planner/get-mgplannerplanbucket?view=graph-powershell-1.0) cmdlet.

**Comment by BruceEx** [comment]
Thanks. I suggested our customer to use Power Automate to do CRUD on
planner tasks.

SeniorConsulting ***@***.***> 于2023年4月20日周四 05:43写道：

**Comment by peombwa** [comment]
I'm not sure if this was a transit issue with the service, however, the API returns the `@odata.etag` value in the response for `Get-MgPlannerTaskDetail` as expected:
``` PowerShell
PS C:\> $TaskDetail = Get-MgPlannerTaskDetail -PlannerTaskId $TaskId -Debug
PS C:\> $TaskDetail.AdditionalProperties

Key            Value
---            -----
@odata.context https://graph.microsoft.com/v1.0/$metadata#planner/tasks('rc50c98JeEumr1ljUMiepWUAM7pQ')/details/$entity
@odata.etag    W/"JzEtVGFza0RldGFpbHMgQEBAQEBAQEBAQEBAQEBARXc="

PS C:\> $TaskDetail.AdditionalProperties."@odata.etag" # @odata.etag value is stored in the additional properties bag.
```

The eTag value can then be passed to `-IfMatch` header as shown below:
``` PowerShell
$eTag = $TaskDetail.AdditionalProperties."@odata.etag"
Update-MgPlannerTaskDetail -PlannerTaskId $TaskId -Description "Test Description" -IfMatch $eTag -Debug
```
