### ISSUE TITLE
Unable to connect to MG Graph due to keyset not existing

### ISSUE THREAD

**Issue by fusrohdan** [microsoftgraph/msgraph-sdk-powershell#1954]
Hey,

I created a PowerShell 7 script that connects to MS Graph.  This was working fine for a few days, but has now started failing with the error "Connect-MgGraph: Keyset does not exist"

I am connecting using the following commands and variables:
$clientid = 'REDACTED'
$tenantid = 'REDACTED'
$localMachineCert = Get-ChildItem -Path Cert:\LocalMachine -Recurse | Where-Object { $_.Thumbprint -eq 'REDACTED' }
Connect-MgGraph -ClientID $clientid -TenantId $tenantid -Certificate $localMachineCert

The certificate I am using is a self-signed certificate from the machine that script is running on.

I have verified that the certificate is present in the machine store, and is accessible to the service account this script runs from.  This was working anyway as the scheduled task ran successfully several times.  

The certificate thumbprint is present in Azure AD in the certificates and secrets section for the application.

I have tried to create 2 new self-signed certificates, both from my admin account and also from the service account.  When I import them into the application, I still get the same error as with the original certificate.  

All certificates I have tested with are valid until 2024, so they have not expired.  

I have logged this as an issue as the script was running fine and nothing has been changed, yet it stopped working with the connection error.  

I would appreciate any assistance in troubleshooting the cause of this.

Thanks!

**Comment by TechsUK** [comment]
How did you fix this? I am getting the same thing

**Comment by ttime007** [comment]
Running my powershell as an administrator (elevated) solved this for me.

**Comment by PrzemyslawKlys** [comment]
Late to the party but you can resolve this for any other account using this blog:
- https://improveandrepeat.com/2018/12/how-to-fix-the-keyset-does-not-exist-cryptographicexception/

**Comment by MalcolmMacMillan-Sage** [comment]
Not sure if this is being monitored
I had this issue when attempting to reuse some of a previously archived script. The solution that I found that worked was to add the gMSA/user account that is running the script to the manage private keys of the locally signed cert (i.e. right click the cert > All tasks > Manage private Keys > Add ; then add the user or gmsa). I found that adding groups did not resolve the issue.

**Comment by PrzemyslawKlys** [comment]
I wrote blog post about this issue: https://evotec.xyz/connect-mggraph-keyset-does-not-exist/ 

Maybe it will help

**Comment by johnmoru** [comment]
Para mi , esta fue la solución, muchas gracias 

 https://evotec.xyz/connect-mggraph-keyset-does-not-exist/

**Comment by nascentt** [comment]
> Running my powershell as an administrator (elevated) solved this for me.

Thanks for this @ttime007 this solved it for me too.

> I wrote blog post about this issue: https://evotec.xyz/connect-mggraph-keyset-does-not-exist/ 

Thanks for the blog post @PrzemyslawKlys - I actually found that before finding this GitHub issue.  @ttime007 's suggestion fixed it rather anything in your blog post though.

Can I suggest adding his suggestion of elevating as admin to your blog post too?
