### ISSUE TITLE
Possible bug with Search-MgDrive - Search-MgDrive_Search: General exception while processing

### ISSUE THREAD

**Issue by pgbfnf** [microsoftgraph/msgraph-sdk-powershell#1960]
The following command throws the following error:
Search-MgDrive -driveid "{drive id}" -Q 'randomtext'
Search-MgDrive_Search: General exception while processing

When using -Debug with the command, it translates to:
Absolute Uri:
**https://graph.microsoft.com/v1.0/drives/{drive-id}/microsoft.graph.search(q='randomtext')** 
...which works perfectly fine in Graph Explorer.

I have replicated this behavior in both release and prerelease versions:
1.25.0
2.0.0-preview8

**Comment by peombwa** [comment]
Thanks for following up on this.

Does the error still happen on your end? The command works as expected in both versions:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/7061532/234721127-50461d35-f692-4565-833f-dbf08b02723d.png">

**Comment by pgbfnf** [comment]
Still a problem:

PS C:\temp> Search-MgDrive -driveid $driveid -Q "proposed_vm_decoms.csv" -Debug
DEBUG: [CmdletBeginProcessing]: - Search-MgDrive begin processing with parameterSet 'Search'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', TokenCredentialType: 'ClientCertificate', ContextScope: 'Process', AppName: 'FNFCloudInfraEngAutomationSP.VMDecom'.
DEBUG: [Authentication]: - Scopes: [Sites.Selected].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/drives/b%21ba2z_YeKbEeesPm7PlP7GQqPG_-i0ddDnuru2W4zEWkEXm5559ZiSJVuNswKzkkr/microsoft.graph.search(q='proposed_vm_decoms.csv')

Headers:
FeatureFlag                   : 00000047
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.19044; en-US),PowerShell/7.3.4
SdkVersion                    : graph-powershell/2.0.0,Graph-dotnet-2.0.11
Accept-Encoding               : gzip

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
InternalServerError

Headers:
Cache-Control                 : no-store, no-cache
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : a89e8118-ab83-4b1a-ad52-9c28160b6350
client-request-id             : a89e8118-ab83-4b1a-ad52-9c28160b6350
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"West US","Slice":"E","Ring":"4","ScaleUnit":"001","RoleInstance":"BY1PEPF0000AD01"}}
Date                          : Wed, 26 Apr 2023 23:44:40 GMT

Body:
{
  "error": {
    "code": "generalException",
    "message": "General exception while processing",
    "innerError": {
      "date": "2023-04-26T23:44:41",
      "request-id": "a89e8118-ab83-4b1a-ad52-9c28160b6350",
      "client-request-id": "a89e8118-ab83-4b1a-ad52-9c28160b6350"
    }
  }
}


Search-MgDrive_Search: General exception while processing
DEBUG: [CmdletEndProcessing]: - Search-MgDrive end processing.

**Comment by pgbfnf** [comment]
I should also perhaps mention that if I have the ID of the file, I can download it just fine using:
Get-MgDriveItemContent -DriveID $DriveID -DriveItemID $DriveItemID -OutFile $path

I only have problems searching.

For what it's worth, I'm connecting using an Azure AD Enterprise Application and certificate thumbprint. The permissions for this account are scoped to Selected.Sites and the Sharepoint admin has supposedly set read/write permissions on the drive/collection in question. (I don't know the exact details)

I don't know what permission options exist on Sharepoint collections, but is it possible the account has permissions to download, but not search somehow? I would think read permissions would cover both, or if there was a permissions problem, the command would return better feedback for why it fails.

**Comment by peombwa** [comment]
Thanks for the `-Debug` log.

The `-Debug` log points to this being a service error `Status Code: InternalServerError`. With that being said, the [API](https://learn.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=http#permissions) does not support `Sites.Selected` permission.
> Note: This method does not support the Sites.Selected application permission.

You'll need to add the supported permissions to the enterprise app to use the API - https://learn.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=http#permissions. See https://learn.microsoft.com/en-us/powershell/microsoftgraph/app-only?toc=%2Fgraph%2Ftoc.json&view=graph-powershell-1.0&tabs=azure-portal#register-the-application for more details.

**Comment by pgbfnf** [comment]
This is a really poor design then, because it's not good security to grant site wide permissions when the account only needs access to a single container.
I'm also curious why I can download a file with no problem, but I can't search. Does downloading not use the API? I thought ALL commands in the MgGraph powershell module used the API. It seems inconsistent if one command works with Sites.Selected and another doesn't.

**Comment by pgbfnf** [comment]
Because of this poor design, we have decided to abandon using Graph API to interact with Sharepoint and move to using the PnP.Powershell module.

**Comment by peombwa** [comment]
The API owner defines the API permissions. This module simply follow's the authZ permission model as described at https://learn.microsoft.com/en-us/graph/permissions-overview?tabs=http.

Please upvote on the existing service feature request at https://feedbackportal.microsoft.com/feedback/idea/fe6a3e47-42d2-ec11-a7b6-000d3a54e061 for the API owner to support your scenario.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

**Comment by peombwa** [comment]
Closing as a service feature request that's being tracked at https://feedbackportal.microsoft.com/feedback/idea/fe6a3e47-42d2-ec11-a7b6-000d3a54e061.
