### ISSUE TITLE
Snippets generation failure for PowerShell & Go

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/msgraph-sdk-powershell#1962]
Bug: Code snippets are not generating for https://graph.microsoft.com/v1.0/organization/XXXX/branding/localizations for Powershell

![image](https://user-images.githubusercontent.com/9458079/168818454-6476bab1-35a9-4983-91e4-26fc0410e4ea.png)

**Comment by timayabi2020** [comment]
Closing this because the original issue has so far been resolved and other identified paths with missing snippets in the comments. 
<img width="891" alt="image" src="https://github.com/user-attachments/assets/a96cacd5-e3a4-40a4-9535-b0cd9a45c211">
