### ISSUE TITLE
Regression - App is Unverified

### ISSUE THREAD

**Issue by InspectorDetector** [microsoftgraph/msgraph-sdk-powershell#1964]
Public app should be verified. Previously addressed in issue #468 but has regressed.

![image](https://user-images.githubusercontent.com/123663766/234060837-5cc2a691-2d15-4115-9e98-37a8ddef14be.png)

**Comment by peombwa** [comment]
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/482.

See the explanation at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/482#issuecomment-1173893429 for what's blocking the change and workarounds.
