### ISSUE TITLE
New-MgEntitlementManagementCatalogAccessPackageAssignmentPolicy throws "No HTTP resource was found that matches the request URI"

### ISSUE THREAD

**Issue by brolifen** [microsoftgraph/msgraph-sdk-powershell#1970]
Using following cmdlet: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.governance/new-mgentitlementmanagementcatalogaccesspackageassignmentpolicy?view=graph-powershell-1.0
Example code:
```
$policyName = "Access Policy"
$organization = $ConnectedOrganization
$approvalGroup = $ApproverGroup
$accessPackage = $MyAccessPackage
$catalog = $MyCatalog

$params = @{
  accessPackage = @{
    id = $accessPackage.Id
  }
  displayName = $policyName
  description = $policyName
  allowedTargetScope = "specificConnectedOrganizationUsers"
  specificAllowedTargets = @(
    @{
      "@odata.type" = "#microsoft.graph.connectedOrganizationMembers"
      connectedOrganizationId = $organization.Id
      description = $organization.DisplayName
    }
  )
  expiration = @{
    type = "duration"
    endDateTime = $null
    duration = "P30D"
  }
  requestorSettings = @{
    enableTargetsToSelfAddAccess = $true
    enableTargetsToSelfUpdateAccess = $true
    enableTargetsToSelfRemoveAccess = $true
    allowCustomAssignmentSchedule = $false
  }
  requestApprovalSettings = @{
    isApprovalRequiredForAdd = $true
    isApprovalRequiredForUpdate = $false
    stages = @(
      @{
        durationBeforeAutomaticDenial = "P14D"
        isApproverJustificationRequired = $true
        primaryApprovers = @(
          @{
            "@odata.type" = "#microsoft.graph.groupMembers"
            groupId = $approvalGroup.Id
            description = $approvalGroup.DisplayName
          }
        )
      }
    )
  }

}
New-MgEntitlementManagementCatalogAccessPackageAssignmentPolicy -BodyParameter $params -AccessPackageId $accessPackage.Id -AccessPackageCatalogId $catalog.Id
```

Output error:
```
No HTTP resource was found that matches the request URI 'https://igaelm-asev3-ecapi-neu.igaelm-asev3-environment-neu.p.azurewebsites.net/api/v1/catalogs('aa6a18d7-63bf-415d-8a51-30e966cfed02')/accessPackages('4a7cd25a-6f49-42fb-8911-2be836e55e77')/assignmentPolicies'.
```

Graph explorer throws the same error. It seems the URI path catalogs/<catalogID>/accessPackages/<accessPackageID> is not working correctly?

Seeing this has no Beta counterpart I'm assuming this is a bug?

**Comment by peombwa** [comment]
Thanks for following up on this.

This looks like a bug in the service schema.

Could you try using `New-MgEntitlementManagementAssignmentPolicy` to create the access package assignment policy instead? See the examples at https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&tabs=powershell#example-1-create-a-direct-assignment-policy.

The error message points to the service not supporting the request URI despite it being described as supported in the service schema. Our SDKs and Graph Explorer use the service schema as the source of truth.

@markwahl-msft, is `POST   /identityGovernance/entitlementManagement/catalogs/{accessPackageCatalog-id}/accessPackages/{accessPackage-id}/assignmentPolicies` considered a valid request URI? The CSDL metadata says it is supported, which leads to the overgeneration issue described above.

**Comment by peombwa** [comment]
> Why would there be two cmdlets trying to essentially do the same thing?

This is because the CSDL metadata (service schema) wrongly describes the failing path/API as supported:
> The error message points to the service not supporting the request URI despite it being described as supported in the service schema. Our SDKs and Graph Explorer use the service schema as the source of truth.

This has to be fixed by the API owner as it's misleading. I'll transfer the issue to the metadata for tracking.

**Comment by peombwa** [comment]
I've transferred the issue to https://github.com/microsoftgraph/msgraph-metadata/issues/338 for it be addressed by the API owner.
