### ISSUE TITLE
Update-MgTeamworkTeamAppSetting function missing in Microsoft.Graph.Teams 1.26.0

### ISSUE THREAD

**Issue by crgbt** [microsoftgraph/msgraph-sdk-powershell#1973]
Microsoft announced the Update-MgTeamworkTeamAppSetting function in the Microsoft.Graph.Teams module via the Microsoft 365 Message Center on April 28th 2023 (MC411463). Upon updating to version 1.26.0 of the Microsoft.Graph.Teams module, this function is not present:

Installed module version
```
PS C:\Users\redacted> Get-Module -Name Microsoft.Graph.Teams

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.26.0                Microsoft.Graph.Teams               {Add-MgChatMember, Add-MgTeamChannelMember, Add-M…

```
Tested PowerShell versions
```
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Steps to reproduce
Install latest version of Microsoft.Graph.Teams module
`Install-Module -Name Microsoft.Graph.Teams -RequiredVersion 1.26.0`

Import module
`Import-Module Microsoft.Graph.Teams`

Try to locate function
`Get-Command -Noun *TeamworkTeam* -Module Microsoft.Graph.Teams`

Note the lack of output

Additionally, try to execute the function
```
PS C:\Users\redacted> Update-MgTeamworkTeamAppSetting
Update-MgTeamworkTeamAppSetting: The term 'Update-MgTeamworkTeamAppSetting' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

```

Additional info, FunctionsToExport in module version 1.26.0 shows the function(https://www.powershellgallery.com/packages/Microsoft.Graph.Teams/1.26.0/Content/Microsoft.Graph.Teams.psd1)

**Comment by peombwa** [comment]
@crgbt, the command/API only exists in `beta`. You'll need to switch to `beta` endpoint using `Select-MgProfile beta`. See https://learn.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0#api-version.

Also, please take note of the changes to `beta` commands in v2 at https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/docs/upgrade-to-v2.md#profile-support.

**Comment by Knurmia** [comment]
Maybe the need and the way to switch to beta should be mentioned, so people don't spend a lot of time trying to figure this out. The documentation for [Update-MgTeamworkTeamAppSetting](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.teams/update-mgteamworkteamappsetting?view=graph-powershell-beta) also does not mention anything about being in beta unless you notice it in the URL and there's no mention about switching the profile to beta to get access to this command.
