### ISSUE TITLE
I cannot uninstall the v2 Microsoft Graph Powershell SDK from PowerShell 7

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/msgraph-sdk-powershell#1976]
I have tried numerous times to get this preview version of the SDK uninstalled but I cannot.

I have numerous files like this: 2.0.0-preview8       Microsoft.Graph.Reports             PSGallery            Microsoft Graph PowerShell Cmdlets
2.0.0-preview8       Microsoft.Graph.SchemaExtensions    PSGallery            Microsoft Graph PowerShell Cmdlets
2.0.0-preview8       Microsoft.Graph.Search              PSGallery            Microsoft Graph PowerShell Cmdlets
2.0.0-preview8       Microsoft.Graph.Security            PSGallery            Microsoft Graph PowerShell Cmdlets
2.0.0-preview8       Microsoft.Graph.Sites               PSGallery            Microsoft Graph PowerShell Cmdlets
2.0.0-preview8       Microsoft.Graph.Teams               PSGallery            Microsoft Graph PowerShell Cmdlets
2.0.0-preview8       Microsoft.Graph.Users               PSGallery            Microsoft Graph PowerShell Cmdlets
2.0.0-preview8       Microsoft.Graph.Users.Actions       PSGallery            Microsoft Graph PowerShell Cmdlets
2.0.0-preview8       Microsoft.Graph.Users.Functions

The command Uninstall-Module Microsoft.Graph -AllVersions -AllowPrerelease    does not work.  No errors, just all modules still exist.  How do I uninstall this perview version?

**Comment by peombwa** [comment]
@RayGHeld, please follow the instructions at https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0#uninstalling-the-sdk.

You'll just need to `-AllVersions -AllowPrerelease` switch parameters to the `Uninstall-Module` command:
``` powershell
Uninstall-Module Microsoft.Graph -AllowPrerelease -AllVersions
Uninstall-Module Microsoft.Graph.Beta -AllowPrerelease -AllVersions # Assuming you have beta modules installed.

Get-InstalledModule Microsoft.Graph.* | %{ if($_.Name -ne "Microsoft.Graph.Authentication"){ Uninstall-Module $_.Name -AllowPrerelease -AllVersions } }

Uninstall-Module Microsoft.Graph.Authentication -AllowPrerelease -AllVersions
```

The steps above are needed because PowerShell does not allow you to uninstall dependent modules - https://github.com/PowerShell/PowerShellGet/issues/87.

**Comment by merill** [comment]
I work a lot with Graph PowerShell and kept hitting this issue all the time so I wrote a helper cmdlet to cleanly remove all the Microsoft Graph modules in your system.

See https://uninstall-graph.merill.net/
