### ISSUE TITLE
Get-MgEntitlementManagementAssignmentPolicy returns empty AccessPackage and Catalog properties

### ISSUE THREAD

**Issue by brolifen** [microsoftgraph/msgraph-sdk-powershell#1984]
Get-MgEntitlementManagementAssignmentPolicy returns empty AccessPackage and Catalog properties

![image](https://user-images.githubusercontent.com/20615514/235359595-df6fc9ea-6d16-4e79-9eab-732eb6bc7974.png)

**Comment by peombwa** [comment]
Sorry for the delayed response.

As per the [API reference](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&tabs=http), you'll need to specify the relationship to expand on in the `$expand`/`-ExpandProperty` as they are not returned by default:
> If the delegated user is an access package manager or catalog owner, they should instead retrieve the policies for the access packages they can read with [list accessPackages](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-list-accesspackages?view=graph-rest-1.0) by including $expand=accessPackage as a query parameter.

For example:
``` powershell
> (Get-MgEntitlementManagementAssignmentPolicy -Debug -ExpandProperty AccessPackage, Catalog).AccessPackage
```

See https://learn.microsoft.com/en-us/powershell/microsoftgraph/use-query-parameters?view=graph-powershell-1.0#expand-parameter for more details.
