### ISSUE TITLE
Get-MgReportAuthenticationMethodUserRegistrationDetail PageSize error

### ISSUE THREAD

**Issue by dwarfered** [microsoftgraph/msgraph-sdk-powershell#1987]
1.27.0               Microsoft.Graph

Issue: Adding a PageSize value to Get-MgReportAuthenticationMethodUserRegistrationDetail results in an incorrect number of results when fetching all results.

$resultA = Get-MgReportAuthenticationMethodUserRegistrationDetail -All -PageSize 999
$resultB = Get-MgReportAuthenticationMethodUserRegistrationDetail -All

$resultA.Count does not equal $resultB.Count

**Comment by peombwa** [comment]
Sorry for the delayed response.

The above behavior is not reproducible using the latest version of the SDK, v2.1.0. The count for `$resultA.Count` and `$resultB.Count` are always the same in my testing:

``` powershell
➜ $resultA = Get-MgReportAuthenticationMethodUserRegistrationDetail -All -PageSize 999
➜ $resultB = Get-MgReportAuthenticationMethodUserRegistrationDetail -All
➜ $resultA.Count
34
➜ $resultB.Count
34
```

Please follow the [troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) by calling the command with `-Debug` to identify where the discrepancy is coming from. The SDK simply returns the response as from the API.
