### ISSUE TITLE
Support Graph PowerShell SDK v2 preview for Managed Dependency in Azure Functions

### ISSUE THREAD

**Issue by JanVidarElven** [microsoftgraph/msgraph-sdk-powershell#1998]
I've been exploring using v2 preview of PowerShell Graph SDK in Azure Functions since the release of the preview. Because of the -AllowPrelease switch in PSGallery, I'm not able to use managed dependency in the requirements.psd1 file. Are there any workarounds or changes that can be made for v2 to be able to use managed dependency?

So far I have done the following to work around this:
1. Find and save the module inside the Functions /Modules folder: Eg.: Find-Module -Name Microsoft.Graph.Authentication -AllowPrerelease -Repository PSGallery -RequiredVersion '2.0.0-preview8' | Save-Module -Path .\Modules
2. Import the module in profile.ps1, eg:
Import-Module Microsoft.Graph.Authentication -RequiredVersion 2.0.0 -Force

**Comment by peombwa** [comment]
[V2 is now generally available](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/2.0.0) (GA). You should be able to use the module in Azure Function by specifying it in your functions `requirements.psd1` as per the instructions at https://learn.microsoft.com/azure/azure-functions/functions-reference-powershell?tabs=portal#dependency-management. Feel free to open a new issue should run into issues with v2 in Azure Functions.
