### ISSUE TITLE
Get-MgSite -All does not return all templates like TEAMSCHANNEL#0 OR TEAMSCHANNEL#1

### ISSUE THREAD

**Issue by brightlight12** [microsoftgraph/msgraph-sdk-powershell#1999]
Get-MgSite -All does not return all templates like TEAMSCHANNEL#0 OR TEAMSCHANNEL#1

**Comment by Briggidy** [comment]
I'm also trying to chase down the discrepancy between 

(Get-MgSite -PageSize 500 -All).count 
53020 
versus
(Get-SPOSite -IncludePersonalSite:$true -Limit All).count
56144.  

Do you think this could be a contributing factor?

**Comment by brightlight12** [comment]
Not sure. I decided to query using graph API.

**Comment by peombwa** [comment]
What's the output of running the command with `-Debug`? This will show the response the SDK gets from the API. See [troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details.
