### ISSUE TITLE
Get-MgDriveItem and Get-MgDriveItemChild - can't use filter for itemtype

### ISSUE THREAD

**Issue by mikemagarelli** [microsoftgraph/msgraph-sdk-powershell#2009]
I need to be able to use Get-MgDriveItem and Get-MgDriveItemChild and filter the results to only include folders or files. There is no documentation on how to identify item type or how to use filter with these cmdlets. Also, If I try to filter results with where-object, PowerShell does not respect the query. Can someone help or provide better documentation? Thanks!

**Comment by peombwa** [comment]
As far as I know, the API does not support `$filter` on item type. See https://learn.microsoft.com/en-us/answers/questions/501232/microsoft-graph-drive-filter-children-folder-file for more details. I'd recommend you also open a service feature at https://developer.microsoft.com/en-us/graph/support for the API owner.

> Also, If I try to filter results with where-object, PowerShell does not respect the query.

This should work. Could you share what you've tried so far?

**Comment by mikemagarelli** [comment]
> As far as I know, the API does not support `$filter` on item type. See https://learn.microsoft.com/en-us/answers/questions/501232/microsoft-graph-drive-filter-children-folder-file for more details. I'd recommend you also open a service feature at https://developer.microsoft.com/en-us/graph/support for the API owner.
> 
> > Also, If I try to filter results with where-object, PowerShell does not respect the query.
> 
> This should work. Could you share what you've tried so far?
where-object doesn't work when targeting the 'AdditionalProperties' of an item returned with the property emtpy....the query after the pipeline is -  "? {-not $_.AdditionalProperties}". But I've found other data to key off of, so I've moved on from that. The documentation around the mg cmdlets leaves a whole lot to be desired. All I'm trying to do is pull file data from all OneDrive's in my tenant and select files older that x. I've found the task to be next to impossible with the documentation and tooling provided.

**Comment by peombwa** [comment]
I'm glad you were able to resolve it. `AdditionalProperties` is meant to be used to access "extra" properties that are not defined on the type, such as open type properties. Item type properties (folder, file, etc.) should be accessible directly on the response object you get from the command.

I do agree with you on the need for scenario specific documentation. I've taken note of this, and I'll share it with the team. However, the PowerShell SDK is currently designed to expose Microsoft Graph APIs for use in Powershell. As such, the use of cmdlets in the module is largely influenced with how the API works. See [navigating Microsoft Graph PowerShell SDK doc](https://learn.microsoft.com/en-us/powershell/microsoftgraph/navigating?toc=%2Fgraph%2Ftoc.json&view=graph-powershell-1.0&viewFallbackFrom=graph-rest-1.0).

**Comment by mikemagarelli** [comment]
I appreciate your quick responses. As a Sys Admin / Engineer who has been using PowerShell successfully for years, I find the shift to Graph to be overly difficult, poorly documented, and will likely be a huge burden for a lot of IT Pros who aren't developers.

**Comment by peombwa** [comment]
Thanks for the candid feedback. I'll share the feedback with the team to see how best IT Pros can be supported with meaning samples and scenario focused scripts.
