### ISSUE TITLE
Update-MgBookingBusinessStaffMember unable to Modify Role of staff member

### ISSUE THREAD

**Issue by BaronVonFinchus** [microsoftgraph/msgraph-sdk-powershell#2012]
Scopes tested: Bookings.ReadWrite.All, Bookings.Manage.All
Microsoft.Graph.Bookings Version: 1.27.0

I'm attempting this using delegated permissions, I've granted the account that I'm using Full Access and SendAs permission on the Exchange Online scheduling mailbox object with Exchange Administrator permissions. I'm then able to access the bookings calendar via the GUI and manually change various properties like managing services, changing the business name e.t.c despite not being a listed administrator in the staff list but even in the GUI I cannot change the role of a staff member despite having the option to change and save.

First I get all staff members via Get-MgBookingBusinessStaffMember, once done I stored this to a variable. Then perform a for-each on this object and attempt to modify the role of the given staff member e.g.
`$staff = Get-MgBookingBusinessStaffMember -BookingBusinessId $calendar.UserPrincipalName
For-each ($staffmember in $staff){
$staff.Role = "administrator"
Update-MgBookingBusinessStaffMember -BookingBusinessId $calendar.UserPrincipalName -BookingStaffMemberId $staff.Id -BodyParameter $staff
}`

I'm able to modify any other property via Update-MgBookingBusinessStaffMember but not the role. The command returns no errors in console but fails to modify the Role property.

Note: I am able to remove the staff member and then readd them using the Remove-MgBookingBusinessStaffMember and New-MgBookingBusinessStaffMember commands, when I do this they are an administrator. However, they also get the "deletegateduseraccount has added you to bookingscalendarname" email which I want to avoid.

**Comment by peombwa** [comment]
Thanks for following up on this. 
>I'm then able to access the bookings calendar via the GUI and manually change various properties like managing services, changing the business name e.t.c despite not being a listed administrator in the staff list but even in the GUI I cannot change the role of a staff member despite having the option to change and save.

>I'm able to modify any other property via Update-MgBookingBusinessStaffMember but not the role. The command returns no errors in console but fails to modify the Role property.

This is a good question for the API owner. The API is meant to return a 204 (no content) on a successful PATCH update - https://learn.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-1.0#response. Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from subject matter experts.

This repository is intended for issues related to the functionality of the SDK (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.
