### ISSUE TITLE
Unable to use Select statement on nested hashtables

### ISSUE THREAD

**Issue by jonade** [microsoftgraph/msgraph-sdk-powershell#2020]
Hi

I'm trying to run queries on the Defender Incidents API (/security/incidents) but restricting which columns are returned by using the $select= query parameters because of PII / EUII constraints and avoiding collecting linked/linkable data.

I'm expanding out on Alerts, so I get data in nested hashtables in the format of Incidents --> Alerts --> Evidence
My most basic query and a sample of the output:
```powershell
(Invoke-MgGraphRequest GET "https://graph.microsoft.com/v1.0/security/incidents?`$expand=alerts" -OutputType Hashtable).Value | ConvertTo-Json -Depth 10
```
```json
{
    "determination":  "unknown",
    "assignedTo":  null,
    "alerts":  [
                   {
                       "alertWebUrl":  "https://security.microsoft.com/alerts/fa42525e1a-d335-83ef-ea00-08db509e7ae5?tid=2501b3e6-015c-4765-8174-859c873b1af5",
                       "evidence":  [
                                        {
                                            "remediationStatusDetails":  null,
                                            "antiSpamDirection":  null,
                                            "verdict":  "malicious",
                                            "receivedDateTime":  "\/Date(1683633441000)\/",
                                            "p2Sender":  {
                                                             "emailAddress":  "ceo@fabrikam.com",
                                                             "displayName":  null,
                                                             "domainName":  "fabrikam.com"
                                                         },
                                            ...
```

I can successfully do a restriction on the first level (Alerts) to control which data is returned here, by adding my $select= statement. This also implicitly expands out the Evidence, and adds it as a nested hastable in my results.

```powershell
(Invoke-MgGraphRequest GET "https://graph.microsoft.com/v1.0/security/incidents?`$select=id,status,displayName,createdDateTime,lastUpdateDateTime,classification,determination,severity&`$expand=alerts" -OutputType Hashtable).Value
```

I can also add my select= statement to control which columns are returned for my Alerts hashtable
```powershell
Invoke-MgGraphRequest GET "https://graph.microsoft.com/beta/security/incidents?`$select=id,status,displayName,createdDateTime,lastUpdateDateTime,classification,determination,severity&`$expand=alerts(`$select=id,incidentId,status,severity,classification,determination,serviceSource,detectionSource,detectorId,title,createdDateTime,lastUpdateDateTime,resolvedDateTime)" -OutputType Hashtable | ConvertTo-Json -Depth 10
```

But now the problem I have is that my nested Evidence hashtable has been completely dropped from the previous results, which had been implicitly expanded previously. If I now try to explicitly specify to expand Evidence, I now get an error that I can't specify expand twice:
```powershell
Invoke-MgGraphRequest GET "https://graph.microsoft.com/beta/security/incidents?`$select=id,status,displayName,createdDateTime,lastUpdateDateTime,classification,determination,severity&`$expand=alerts(`$select=id,incidentId,status,severity,classification,determination,serviceSource,detectionSource,detectorId,title,createdDateTime,lastUpdateDateTime,resolvedDateTime&`$expand=evidence)" -OutputType Hashtable | ConvertTo-Json -Depth 10

{"error":{"code":"BadRequest","message":"Query option '$expand/expand' was specified more than once, but it must be specified at most once."
```

So I can't explicitly do the expansions, even though implicitly it had worked? So I can try and simply add ",evidence" to my original select statement, and see if that works:
```powershell
Invoke-MgGraphRequest GET "https://graph.microsoft.com/beta/security/incidents?`$select=id,status,displayName,createdDateTime,lastUpdateDateTime,classification,determination,severity&`$expand=alerts(`$select=id,incidentId,status,severity,classification,determination,serviceSource,detectionSource,detectorId,title,createdDateTime,lastUpdateDateTime,resolvedDateTime,evidence)" -OutputType Hashtable | ConvertTo-Json -Depth 10

{"error":{"code":"InternalServerError","message":"Internal Server
```

So my question is whether it's possible to use a select statement (as recommended in [the Docs](https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#select-parameter) when running large queries) when there are _implicit expansions_ taking place?

The API happily gives me all the data (Incidents, Alerts and Evidence) back if I include all EUII columns. The errors occur only when I am trying to request specific columns that I require.

**Comment by peombwa** [comment]
Thanks for following up on this.

The repro steps show that the issue is with the API and not the SDK. Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from API owner on the question. Remember to include the `request-id` and `date` response header of the problematic request. See https://learn.microsoft.com/en-us/graph/best-practices-concept#reliability-and-support for more details.

This repository is intended for issues related to the functionality of the SDK (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.
