### ISSUE TITLE
Update-MgApplication - adding new AppRole to existing roles.

### ISSUE THREAD

**Issue by michalkrzych** [microsoftgraph/msgraph-sdk-powershell#2063]
Hello.

I'm looking at the AppRole model at https://learn.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-1.0 and trying to write some PS to automate adding AppRoles to an app registration. With the help of [this](https://jeevanbmanoj.medium.com/programmatic-ways-to-create-app-roles-in-azure-ad-a21fc93c531b#:~:text=You%20can%20leverage%20MS%20Graph%20API%E2%80%99s%20application%20update,your%20app%20registration%20with%20the%20new%20app%20roles.) I have come up with a script but I am struggling to get this to work. 

```ps
function Add-AppRoles {
        param(
            [String]$AppName,
            [String]$AppRoleDisplayName,
            [String]$AppRoleDescription,
            [String]$AppRoleValue
        )
    
        try {
    
            $Id = [Guid]::NewGuid().ToString()
        
            Create new AppRole object
            $newAppRole = New-Object Microsoft.Open.MSGraph.Model.AppRole
            $newAppRole.AllowedMemberTypes = New-Object System.Collections.Generic.List[string]
            $newAppRole.AllowedMemberTypes.Add("User")
            $newAppRole.AllowedMemberTypes.Add("Application")
            $newAppRole.DisplayName = $AppRoleDisplayName
            $newAppRole.Description = $AppRoleDescription
            $newAppRole.Value = $AppRoleValue
            $newAppRole.Id = $Id
            $newAppRole.IsEnabled = $true    
    
            # Add new AppRole and apply changes to Application object
            
            $App = Get-MgServicePrincipal -Filter "DisplayName eq '$AppName'"
            #Write-Output $App
        
            $appRoles = $App.AppRoles
            #Write-Output $appRoles
            
            # save the changes
            $SPNObjectId = (Get-MgApplication -Filter "DisplayName eq '$AppName'").Id
        
            $appRoles += $newAppRole
            Write-Output $appRoles
    
            Update-MgApplication -ObjectId $SPNObjectId -AppRoles $appRoles
        }
        catch {
            $message = $Error[0].Exception.Message
            Write-Host "##vso[task.logissue type=error;]$message.";
            Write-Error $message;
        }
    }

Add-AppRoles -AppName "SIF - Contact API - Int" -AppRoleDisplayName "Execute" -AppRoleDescription "Execute Contact API" -AppRoleValue "contactapi.access.execute"
```

The error message:

> ##vso[task.logissue type=error;]Cannot process argument transformation on parameter 'AppRoles'. Cannot convert the "class AppRole {
  AllowedMemberTypes: System.Collections.Generic.List`1[System.String]
  Description: Execute Contact API
  DisplayName: Execute
  Id: 7497856f-bd4c-4612-98b7-cea7ab15e138
  IsEnabled: True
  Value: contactapi.access.execute
}
" value of type "Microsoft.Open.MSGraph.Model.AppRole" to type "Microsoft.Graph.PowerShell.Models.IMicrosoftGraphAppRole"..

I'm not sure what the problem is but I am guessing it's the format of existing app roles vs. the newAppRole when trying to append to appRoles?

The `$appRoles` in the line where Im calling `Update-MgApplication` returns:

> AllowedMemberTypes  Description     DisplayName Id                                   IsEnabled Origin      Value                    
> ------------------  -----------     ----------- --                                   --------- ------      -----                    
> {User, Application} Contact.Process Process     17f042e0-39e5-4874-9a8b-44f4ec773905 True      Application contactapi.access.process
> {User, Application} Contact.Delete  Delete      ddefcbaa-c853-479b-b1ca-7a73b55b3435 True      Application contactapi.access.delete 
> {User, Application} Contact.Get     Get         0847f73d-030c-4ebf-a38c-619abdfa9695 True      Application contactapi.access.get    
> 
> AllowedMemberTypes : {User, Application}
> Description        : Execute Contact API
> DisplayName        : Execute
> Id                 : 7c07a6a3-fcf2-4c19-aaa5-c80b5710b403
> IsEnabled          : True
> Value              : contactapi.access.execute

I'd really appreciate any help with this or a link to a working example.

**Comment by michalkrzych** [comment]
The problem was caused by the wrong type I was building the newAppRole with. Instead of using `Microsoft.Open.MSGraph.Model.AppRole` it needed to be `Microsoft.Graph.PowerShell.Models.MicrosoftGraphAppRole`. Also a few more tweaks to the above script but made it work in the end:

```ps
$scopes = "Application.ReadWrite.All"
$AppName = "Manual App Registration"
$AppRoleDisplayName = "Execute"
$AppRoleDescription = "Execute New API"
$AppRoleValue = "Testing.Test2"


# Check MSGraph PS Installed, install/import as required.

if (Get-InstalledModule -Name "Microsoft.Graph" -MinimumVersion 1.0) {
    Import-Module Microsoft.Graph.Applications
} else {
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
    Install-Module Microsoft.Graph -Scope CurrentUser
    Import-Module Microsoft.Graph.Applications
}

Connect-MgGraph -Scopes $scopes

function Add-AppRoles {
        param(
            [String]$AppName,
            [String]$AppRoleDisplayName,
            [String]$AppRoleDescription,
            [String]$AppRoleValue
        )
    
        try {
    
            $Id = [Guid]::NewGuid().ToString()
        
            # Create new AppRole object
            $newAppRole = New-Object Microsoft.Graph.PowerShell.Models.MicrosoftGraphAppRole
            $newAppRole.AllowedMemberTypes = @("User", "Application")
            $newAppRole.DisplayName = $AppRoleDisplayName
            $newAppRole.Description = $AppRoleDescription
            $newAppRole.Value = $AppRoleValue
            $newAppRole.Id = $Id
            $newAppRole.IsEnabled = $true    
    
            # Add new AppRole and apply changes to Application object
            
            $App = Get-MgServicePrincipal -Filter "DisplayName eq '$AppName'"
            #Write-Output $App
        
            $appRoles = $App.AppRoles
            #Write-Output $appRoles
            
            # save the changes
            $SPNObjectId = (Get-MgApplication -Filter "DisplayName eq '$AppName'").Id
        
            $appRoles += $newAppRole
            Write-Output $appRoles
    
            Update-MgApplication -ApplicationId $SPNObjectId -AppRoles $appRoles
        }
        catch {
            $message = $Error[0].Exception.Message
            Write-Host "##vso[task.logissue type=error;]$message.";
            Write-Error $message;
        }
    }

Add-AppRoles -AppName $AppName -AppRoleDisplayName $AppRoleDisplayName -AppRoleDescription $AppRoleDescription -AppRoleValue $AppRoleValue
```

**Comment by adurtisai** [comment]
I am getting this error while running michal script @michalkrzych 

Update-MgApplication_UpdateExpanded: 
Line |
  36 |              Update-MgApplication -ApplicationId $SPNObjectId -AppRole …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Permission (scope or role) cannot be deleted or updated unless disabled first.

**Comment by michalkrzych** [comment]
@adurtisai 

I think you just have to set the isEnabled to false as suggested here: https://stackoverflow.com/a/53072952/6492655

In the future, I'd suggest you post the question/open a ticket at https://developer.microsoft.com/en-us/graph/support to get feedback directly from the workload owners.
