### ISSUE TITLE
Update-MgDevice -AccountEnabled for Non-Windows OS

### ISSUE THREAD

**Issue by GeoffOrlebeck** [microsoftgraph/msgraph-sdk-powershell#2066]
In the Azure portal I can disable non-Windows (e.g., iOS) devices. Using Update-MgDevice an error is generated:  

> _Properties other than ExtendedAttribute1..15 can be modified only on windows devices_

I am connecting via App Registration, with Device.ReadWrite.All and the app registration's service principal is added to the Cloud Device Administrator role. The two methods I attempted to update the AccountEnabled status, both result in the same error:

```
# Attempt 1
$DeviceID = '<Guid>'
Update-MgDevice -DeviceID $DeviceID -AccountEnabled:$false

# Attempt 2
$DeviceID = '<Guid>'
$Json = [PSCustomObject]@{accountEnabled = $false } | ConvertTo-Json
Update-MgDevice -DeviceID $DeviceID -BodyParameter $Json
```

Full error output:

```
Update-MgDevice : Properties other than ExtendedAttribute1..15 can be modified only on windows devices.
At line:1 char:1

+ Update-MgDevice -DeviceId '<GUID>' -Acc ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ DeviceId = 3f...ftGraphDevice }:<>f__AnonymousType7`2) [Update-MgDe
   vice_UpdateExpanded], RestException`1
    + FullyQualifiedErrorId : Request_BadRequest,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDevice_UpdateExpanded
```

When copying the API call from Developer Tools in Edge browser, I can see it is setting AccountEnabled to $false in the Invoke-WebRequest call, so I'm wondering if this is an issue with the Update-MgDevice cmdlet, specifically.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

This does appear to be a known issue with API. Here an excerpt from the [API known issue page](https://learn.microsoft.com/en-us/graph/known-issues#non-windows-devices-cant-be-updated-by-an-app-with-application-permissions):
>When an app with application permissions attempts to update any properties of the device object where the operationSystem property isn't Windows, apart from the extensionAttributes property, the [Update device](https://learn.microsoft.com/en-us/graph/api/device-update) API returns a 400 Bad request error code with the error message "Properties other than ExtendedAttribute1..15 can be modified only on windows devices.". Use delegated permissions to update the properties of non-Windows devices.

Your only option at the moment is to use delegated permissions (authenticate as a user) to update the property on a non-Windows device. I'd also recommend you open a service feature request at https://developer.microsoft.com/en-us/graph/support if this is a scenario you'd like to see supported.

**Comment by peombwa** [comment]
Closing as known API issue.

**Comment by Mailstorm-ctrl** [comment]
Not sure why this was closed. This isn't on the known API issues page. It's also just some arbitrary limitation that exist for no reason at all.

Feedback exist for this at:
https://feedbackportal.microsoft.com/feedback/idea/03f7b967-72f5-ed11-a81c-000d3ae5b6f4

**Comment by peombwa** [comment]
The known issue has since been changed since my comment at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2066#issuecomment-1585208508 - [Wayback link](http://web.archive.org/web/20230614212814/https://learn.microsoft.com/en-us/graph/known-issues#non-windows-devices-cant-be-updated-by-an-app-with-application-permissions).

The API limitation is now documented in the [API reference doc](https://learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-1.0&tabs=http) :
> In application-only scenarios and for non-Windows devices, that is, where the operatingSystem property is not Windows, the app can update only the extensionAttributes property.
