### ISSUE TITLE
softwareOneTimePasscode and isMfaCapable no longer returned correctly for Get-MgReportAuthenticationMethodUserRegistrationDetail since Monday

### ISSUE THREAD

**Issue by Borgquite** [microsoftgraph/msgraph-sdk-powershell#2071]
Hi,

Since Monday 5th June we have noted an unannounced change in the opearation of Get-MgReportAuthenticationMethodUserRegistrationDetail

https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.reports/get-mgreportauthenticationmethoduserregistrationdetail?view=graph-powershell-beta

Previously the 'isMfaCapable' returned 'true' for people registered with a third-party (non-Microsoft) authenticator app such as Google Authenticator. Those users are still able to use MFA and nothing has changed in our authentication policies - but overnight Graph changed to report 'isMfaCapable' as 'false'. It also appears that the value 'softwareOneTimePasscode' is no longer being returned for 'defaultMfaMethod' or 'methodsRegistered' as it should be by Microsoft Graph:

https://learn.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta

Please can this be fixed?

**Comment by Borgquite** [comment]
Example user - as seen under Azure Active Directory 'Authentication Methods':
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/53898223/23aabdd6-2919-4e96-96c9-b8e620b60f6c)

As returned by Get-MgReportAuthenticationMethodUserRegistrationDetail in PowerShell:
```
DefaultMfaMethod      : **none**
Id                    : [redacted]
IsAdmin               : True
IsMfaCapable          : **False**
IsMfaRegistered       : **False**
IsPasswordlessCapable : False
IsSsprCapable         : True
IsSsprEnabled         : True
IsSsprRegistered      : True
MethodsRegistered     : **{email}**
UserDisplayName       : [redacted]
UserPrincipalName     : [redacted]
UserType              : member
AdditionalProperties  : {[lastUpdatedDateTime, 2023-06-05T00:32:06.0019711Z]}
```

**Comment by Borgquite** [comment]
Please note that Third-party software OAUTH tokens ARE enabled for All Users in our tenant authentication policy, and we have completed migration to the new policy a few weeks ago.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/53898223/adec98a4-89d3-4508-90be-1be6d900a643)

**Comment by peombwa** [comment]
Hi @Borgquite, this sounds like a regression with API and not the SDK.

Please use the dedicate support channels at https://developer.microsoft.com/en-us/graph/support to open a support ticket with the API owner. `isMfaCapable` and `defaultMfaMethod` properties are returned by the service and the SDK simply renders as-is. You can see this by calling the `-Debug` parameter.

In your ticket/question, please include the `requestId` and `date` of the affected calls. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details. 

This repository is intended for issues related to the functionality of the module. We may not be the best place to answer some queries that are tied to the functionality of the API.

**Comment by Borgquite** [comment]
Thanks. I've opened a support case 2306120050002419

**Comment by Borgquite** [comment]
Just checked my script logs & actually the issue appears to have been resolved on Saturday. Thanks if anyone saw this!
