### ISSUE TITLE
Get-MgDeviceAppMgtMobileAppDeviceStatuses fails

### ISSUE THREAD

**Issue by andreiv3103** [microsoftgraph/msgraph-sdk-powershell#2074]
Hello.
I use Get-MgDeviceAppMgtMobileAppDeviceStatuses in a script and it started failing a few days ago.
The error is:
"Error: Resource not found for the segment 'deviceStatuses'"
I saw that some paths were changed in the API. So that is probably why it fails.

**Comment by andreiv3103** [comment]
This is the new way of retrieving the per device app deployment status:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2743608/0ed110dc-be4e-4f2c-92e3-bfb1ebbdb534)

**Comment by peombwa** [comment]
In this case, you can use `Find-MgGraphCommand` to locate the command for the new path as show below:
``` powershell
➜ Find-MgGraphCommand -Uri "/deviceManagement/reports/getDeviceInstallStatusReport"

   APIVersion: beta

Command                                               Module                   Method URI
-------                                               ------                   ------ ---
Get-MgDeviceManagementReportDeviceInstallStatusReport DeviceManagement.Actions POST   /deviceManagement/reports/getDeviceInstallStatusRe…
```
The new URI yields `Get-MgDeviceManagementReportDeviceInstallStatusReport` as the command to use.

Unfortunatly, beta APIs are subject to change and are not meant for production use. See the disclaimer at https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-beta.

**Comment by peombwa** [comment]
Closing since a new API/command is available as from v1.28.0.

**Comment by andreiv3103** [comment]
> In this case, you can use `Find-MgGraphCommand` to locate the command for the new path as show below:
> 
> ```powershell
> ➜ Find-MgGraphCommand -Uri "/deviceManagement/reports/getDeviceInstallStatusReport"
> 
>    APIVersion: beta
> 
> Command                                               Module                   Method URI
> -------                                               ------                   ------ ---
> Get-MgDeviceManagementReportDeviceInstallStatusReport DeviceManagement.Actions POST   /deviceManagement/reports/getDeviceInstallStatusRe…
> ```
> 
> The new URI yields `Get-MgDeviceManagementReportDeviceInstallStatusReport` as the command to use.
> 
> Unfortunatly, beta APIs are subject to change and are not meant for production use. See the disclaimer at https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-beta.

Yes, I know that, but there is no other way to get this information I need. Even Microsoft uses the beta version in the portal, as it can be seen in many of the blades.

But thanks for the info, now I know how to find the new cmdlet, in case something else changes.
👍

**Comment by andreiv3103** [comment]
I have one more question:
how do I get all the data about an app deployment status using:
Get-MgDeviceManagementReportDeviceInstallStatusReport

I copied JSON body from the request made in the portal.
I ran the command like this:
Get-MgDeviceManagementReportDeviceInstallStatusReport -BodyParameter $BB -OutFile D:\test.json

However, it only returns a few devices.

**Comment by Vishwjeet92502** [comment]
> This is the new way of retrieving the per device app deployment status: ![image](https://user-images.githubusercontent.com/2743608/244339528-0ed110dc-be4e-4f2c-92e3-bfb1ebbdb534.png)

Hi @andreiv3103 when I try the same method for my environment, I get an error like this. Any idea what it could be?
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/136671502/5246c496-9aa6-4848-9710-d5ca73b8b6e6)

**Comment by andreiv3103** [comment]
Hello [Vishwjeet92502](https://github.com/Vishwjeet92502)
You probably don't have the required permission to run the query.
Click on "Modify permissions" to see if all required permissions were granted:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2743608/88363ac8-c9fb-4d4b-ab80-23948dcd85b9)

**Comment by Vishwjeet92502** [comment]
> Hello [Vishwjeet92502](https://github.com/Vishwjeet92502) You probably don't have the required permission to run the query. Click on "Modify permissions" to see if all required permissions were granted:
> 
> ![image](https://user-images.githubusercontent.com/2743608/246014237-ed73416f-18f5-4fa6-9a20-d9e7adf3e425.png)

Hi @andreiv3103 , could you please share sample powershell function you are using, it seems we are not able to get this data through graph.

**Comment by Vishwjeet92502** [comment]
> > > Hello [Vishwjeet92502](https://github.com/Vishwjeet92502) You probably don't have the required permission to run the query. Click on "Modify permissions" to see if all required permissions were granted:
> > > ![image](https://user-images.githubusercontent.com/2743608/246014237-ed73416f-18f5-4fa6-9a20-d9e7adf3e425.png)
> > 
> > 
> > Hi @andreiv3103 , could you please share sample powershell function you are using, it seems we are not able to get this data through graph.
> 
> I can share the PS code I use but it still uses the Graph API. So if it doesn't work in Graph Explorer, it won't work from PowerShell either. You need to check your permissions.

Hi @andreiv3103 , Actually in our existing Powershell script we had tokens and credentials for one service account which has full permission to access the resources from graph so just wanted to give that a shot.

**Comment by Vishwjeet92502** [comment]
@andreiv3103 

Thanks, the script works fine.
Do you have any idea how to run this script with another user's credentials without any prompt as we are using the script for automation in service now.

I tried "connect-mggraph -accesstoken  $token" method but it says invalid token. Any help will be great here.

**Comment by RickB17** [comment]
I am running into the same issue if I do not introduce a three minute pause performing the queries. The Unknown Error arrives in the middle of paging through all records.

**Comment by andreiv3103** [comment]
> 

That is only a "resource not found error". Which command throws that error?

**Comment by Vishwjeet92502** [comment]
> > 
> 
> That is only a "resource not found error". Which command throws that error? If you run the code from a script file, wrap the entire code in a try/catch statement and you can get the exact line where the error occurs in the catch block like this:
> 
> ```powershell
> try {
>     <PUT THE CODE HERE>
> }
> catch {
>     Write-Host $ErrorObject.Exception.Message
>     Write-Host $ErrorObject.InvocationInfo.PositionMessage
> }
> ```

This error comes when script is checking for an application via it's ID, even if there is another app being provided as input it just failed with this error. This error comes randomly and happening with multiple apps where it just giving this random app ID as failure.
