### ISSUE TITLE
Update -debug to show complete HTTP request and response

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#208]
See how -debug works in Az for an example.

[AB#4719](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4719)

**Comment by finsharp** [comment]
Requires changes to autorest.powershell [generator](https://github.com/Azure/autorest.powershell/pull/602)
