### ISSUE TITLE
Update-MgUserMessage : The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.

### ISSUE THREAD

**Issue by MarkF26** [microsoftgraph/msgraph-sdk-powershell#2080]
A PS script that has been working for a few years suddenly started acting up on June 7th, 2023 without any changes in the script. The only assumption we can make is that the backend Graph API service must have done something to cause it, Basically the script creates a draft message with some basic information such as from, subject, sender, and then updates it with additional information such as recipients, attachments, etc.. 

It seems like Grpah API moves the message with some changes in its attributes causing the above message. The detailed error message is: 
`Update-MgUserMessage : The send or update operation could not be performed because the change key passed in the
request does not match the current change key for the item.`

`At C:\Scripts\xxxxxxxxxxxxxx.ps1:428 char:14`
`+` `...        Try {Update-MgUserMessage -MessageId $Message.Id -ToRecipients ...`
`+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`   + CategoryInfo          : InvalidOperation: ({ UserId = Aler...tGraphMessage }:<>f__AnonymousType55``3) [Update-MgUserMessage_UpdateExpanded1], RestException``1`
`    + FullyQualifiedErrorId : ErrorIrresolvableConflict,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUserMessage_UpdateExpanded1`

I was able to add a Prefer: IDTYpe = ImmutableID 
```
$authHeader = @{
    'Authorization' = "Bearer $Token"
    'Content-Type' = "application/json"
    'Prefer'       = 'IdType="immutableId"'
}
```
But the problem still remains. Any help is appreciated. 

**[Update on June 13, 23]**
I was able to bypass the problem if I make the USERID, and SENDER to be from the same. If they are different the problem persists: 
New-MgUserMessage -UserID $SenderEmail -sender $MGSender  -From $MgFrom -Subject $Subjline  -IsDraft

`Microsoft.graph.mail Version 1.28.0`

PSVersion___________5.1.17763.3770
PSEdition___________Desktop
PSCompatibleVersions_____ {1.0, 2.0, 3.0, 4.0...}
BuildVersion_________ 10.0.17763.3770
CLRVersion__________ 4.0.30319.42000
WSManStackVersion_______3.0
PSRemotingProtocolVersion___2.3
SerializationVersion_____ 1.1.0.1

**Comment by peombwa** [comment]
Thanks for following up on this.

As you've pointed out above, this is a service issue that recently started failing. Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support as this is a service issue.

Remember to include the `requestId` and `date` of the affected calls in your ticket/question. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details. 

This repository is intended for issues related to the functionality of the SDK. We may not be the best place to answer some queries that are tied to the functionality of the API.
