### ISSUE TITLE
get-mguser, additionalProperties did not retuen signinActivity for version 1.27.0

### ISSUE THREAD

**Issue by LloydLu** [microsoftgraph/msgraph-sdk-powershell#2082]
get-mguser, additionalProperties did not retuen signinActivity for version 1.27.0, but it can work for version 1.20.0 and 1.22.0.
Has there been any functional changes related to additionalProperties in version 1.27?

command: Get-MgUser -UserId "<ObjectId>" -Property id, userPrincipalName, signInActivity | select AdditionalProperties | ConvertTo-Json

Thank you in advance.

**Comment by peombwa** [comment]
Hello!

According to the API changelog at https://developer.microsoft.com/graph/changelog/?search=signinActivity, `signinActivity` was recently (March 30, 2023) added to the `user` resource/entity in v1.0. This means that the property can now be directly accessed on the user object:
``` powershell
$User = Get-MgUser -UserId "" -Property id, userPrincipalName, signInActivity
$User.SignInActivity
```

The property was previously only available on a user in beta as per the API changelog.
