### ISSUE TITLE
"Get-MgPolicyAuthenticationMethodPolicy" returns no "authenticationMethodConfigurations" objects

### ISSUE THREAD

**Issue by brolifen** [microsoftgraph/msgraph-sdk-powershell#2102]
When you run `Get-MgPolicyAuthenticationMethodPolicy `you get only the top level "authenticationMethodsPolicy"  the list of "authenticationMethodConfigurations" is not included wheras using the HTTP method does return all the authenticationMethodConfigurations objects.

Also tried to expand the property using:

`Get-MgPolicyAuthenticationMethodPolicy -ExpandProperty authenticationMethodConfigurations`

It runs without error but the same result is returned. It seems the internal powershell code is incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc141178-d5bb-6186-6f6c-706e5e253989
* Version Independent ID: 64070231-701c-25f3-4c24-40c8f37664e5
* Content: [Get authenticationMethodsPolicy - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/authenticationmethodspolicy-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/authenticationmethodspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationmethodspolicy-get.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by peombwa** [comment]
I'm not able to repro this behavior using the latest version of the SDK, v2.1.0. The `authenticationMethodConfigurations` is present in the response object:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/7061532/8e4a1e1c-57f8-42cd-9d1f-0bb9cc2f3f0f)

Please follow the troubleshooting guide at https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug verify if the property is returned by the API in the response body.

**Comment by brolifen** [comment]
This indeed works now and was probably a transient error.
