### ISSUE TITLE
got an error in ExpandProperty

### ISSUE THREAD

**Issue by muralikrishnarokkam** [microsoftgraph/msgraph-sdk-powershell#2103]
Got an below error while adding Expand Property 

((Get-MgServicePrincipalOwnedObject -ServicePrincipalId "xxxxxxx-xxxx-xxx-xxxx-xxxxxxxxxx" -Property appId,disyName,passwordCredentials -ExpandProperty passwordCredentials ).AdditionalProperties)    

Error:  
Get-MgServicePrincipalOwnedObject_List1: Parsing OData Select and Expand failed: Could not find a property named 'passwordCredentials' on type 'microsoft.graph.directoryObject'.

**Comment by peombwa** [comment]
@muralikrishnarokkam, could you please share the `-Debug` output as shown at https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug.

The service error message seems to suggest that you can't expand `passwordCredentials` on `ownedObjects` `/servicePrincipals/{id}/ownedObjects?$expand=passwordCredentials`. Are you able to expand `passwordCredentials` on an `ownedObjects` by calling the API directly via [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer)?
