### ISSUE TITLE
Get-MgSubscribedSku does not have parity with get-msolsubscription

### ISSUE THREAD

**Issue by mabaugh83** [microsoftgraph/msgraph-sdk-powershell#2108]
Get-msolsubscription provides following values that are not in get-mgsubscribedsku

	DateCreated
	NextLifeCycleDate
	Status
	IsTrial
	
is it possible to add those? This is stopping me from moving away from get-msolsubscription

**Comment by SeniorConsulting** [comment]
Gidday,

I'm not sure that this is the right forum for this. I've checked out the API endpoint you're looking at (https://graph.microsoft.com/v1.0/subscribedSkus), and it doesn't look as though they're returned by the API (https://learn.microsoft.com/en-us/graph/api/resources/subscribedsku?view=graph-rest-1.0#properties)

It might be worth a visit to https://developer.microsoft.com/en-us/graph/support to raise a case there, as this forum is for handling issues with the Graph PowerShell modules.

**Comment by SteveMutungi254** [comment]
@mabaugh83: The missing properties will be available in our next SDK release - but on **Beta** {first}.

For now, you can test using this endpoint on Microsoft Graph - https://graph.microsoft.com/beta/directory/subscriptions?$select=id,skupartnumber,skuid,nextLifecycleDateTime,createdDateTime,ocpSubscriptionId (via [Graph Explorer](https://aka.ms/ge))

**Note**: After the feature team has completed the tests, the same will be availed in our GA/v1.0 version {typically within 180 days}.

**Comment by mabaugh83** [comment]
this is great news. I tested and works great. Ultimately am trying to use as a automation runbook. Looks like only works for noe as delegated access not application. Will it support application (appid/cert) eventually? or does it do it now :)
many thanks
mike

**Comment by peombwa** [comment]
> The missing properties will be available in our next SDK release - but on Beta {first}.

> For now, you can test using this endpoint on Microsoft Graph - https://graph.microsoft.com/beta/directory/subscriptions?$select=id,skupartnumber,skuid,nextLifecycleDateTime,createdDateTime,ocpSubscriptionId (via [Graph Explorer](https://aka.ms/ge))

> Note: After the feature team has completed the tests, the same will be availed in our GA/v1.0 version {typically within 180 days}.

The command to call the API is now available under `Microsoft.Graph.Beta.Identity.DirectoryManagement` v2.1.0 as `Get-MgBetaDirectorySubscription`.

**Comment by cpunella** [comment]
Hi all, any idea when it will be available on V1?
