### ISSUE TITLE
Get-MgPolicyAuthorizationPolicy -Property defaultUserRolePermissions doest return the right value

### ISSUE THREAD

**Issue by yuhko-msft** [microsoftgraph/msgraph-sdk-powershell#2109]
When I tried to call the command, it returs 
DeletedDateTime Description DisplayName Id AllowEmailVerifiedUsersToJoinOrganization AllowInvitesFrom AllowUserConsentF
                                                                                                      orRiskyApps
--------------- ----------- ----------- -- ----------------------------------------- ---------------- -----------------

But the return should contain these attributes below: 
"allowedToCreateApps"
"allowedToCreateSecurityGroups"
"allowedToCreateTenants"
"allowedToReadBitlockerKeysForOwnedDevice"
"allowedToReadOtherUsers"
"permissionGrantPoliciesAssigned": [
       "ManagePermissionGrantsForSelf.my-custom-consent-policy"
        ]

**Comment by peombwa** [comment]
@yuhko-msft, the properties are returned by the command as expected. You'll just need to format the output to display the properties:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/7061532/07061148-289b-4a61-8d74-01717919f516)

By default, Microsoft Graph PowerShell cmdlets output in a table format. This format doesn't display all properties of the requested resource. The amount of data displayed by is based on your PowerShell session window. Please use PowerShell's `Format-*` or `Select-Object` to display the properties to your liking. See https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues.
