### ISSUE TITLE
Get-MgUser not at parity with Get-MsolUser. PreferredDataLocation values always blank.

### ISSUE THREAD

**Issue by briandaymsft** [microsoftgraph/msgraph-sdk-powershell#2111]
Get/Set-MsolUser returns values for the PreferredDataLocation attribute used by M365 Multi-Geo customers to define where data-at-rest should be located.

Get-MgUser seems to know the PreferredDataLocation attribute exists. If you execute something like **Get-MgUser -All | FL Pref*** the output returns a few attributes starting with Pref*, including PrefferedDataLocation, but the value for it is blank.

Examples from the same tenant are below.

Get-MsolUser, returns values as expected (and Set-MsolUser can set them).
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22648747/d79c3111-a614-4ad6-a02e-408e4e47fea6)

v1.28.0 Get-MgUser, no values returned.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22648747/5a9031e5-0cc7-47de-a874-eb5f6954e7e0)

**Comment by SeniorConsulting** [comment]
Hi Brian,

Not all properties are returned by the Graph API unless asked for specifically. One thing I haven't seen in your screenshots is whether you're trying to return that property too.

Could you please try:
`Get-MgUser -all -Property Id,PreferredDataLocation | FT Id,PreferredDataLocation`

**Comment by briandaymsft** [comment]
Thank you @SeniorConsulting . 

Here's why I didn't pass -Property at first. When you do **| FT ID,Pref*** it _does_ return the three attributes starting with **Pref***, which creates an illusion the values were returned but the blank ones are a $Null value. There's no visual indicator to suggest "Hey I know these attributes exist, but you didn't ask me for any data so they're blank."
 
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22648747/79cf8285-d888-4f70-b311-f7f9009ad21d)

You are correct, if you _do_ pass -Property ID,PreferredDatalocation, it _does_ return the information but only for the properties specified. Now the PreferredLanguage field which had values in the prior example no longer has values, since I didn't ask for them. This is definitely not the most user intuitive interface compared to historical PowerShell interactions. :) 

I think I have what I need though to update some documentation, thank you.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22648747/eb95ae49-afd1-4a6a-b59c-f0bf1e73fa6b)

**Comment by SeniorConsulting** [comment]
Yep, it certainly is different from other PowerShell interactions, one of the first gotchas of using the SDK. Of course, it behaves exactly like you'd expect if you started using the Graph API first - which I'll admit probably most people don't step into.

Some updated documentation would be fantastic.

**Comment by peombwa** [comment]
Sorry for the late response. I'm glad you were able to resolve the issue thanks the help from SeniorConsulting!

This is by design. As per the API reference - https://learn.microsoft.com/graph/api/user-list?view=graph-rest-1.0&tabs=powershell#optional-query-parameters:
> By default, only a limited set of properties are returned (businessPhones, displayName, givenName, id, jobTitle, mail, mobilePhone, officeLocation, preferredLanguage, surname, and userPrincipalName).To return an alternative property set, specify the desired set of [user](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0) properties using the OData $select query parameter. For example, to return displayName, givenName, and postalCode, add the following to your query $select=displayName,givenName,postalCode.

The examples in [API reference](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=powershell#example-2-get-a-user-account-using-a-sign-in-name) have since been updated to show how to use `-Property` (`$select`) for each documented example.

The SDKs will be updated in future versions to encourage callers to use `$select`/`-Property` when an API returns default set of properties - https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2175. This should help address the concerns raised above and optimize API calls from the SDKs.
