### ISSUE TITLE
Identifier with trailing slash is invalid

### ISSUE THREAD

**Issue by VirTechSystems** [microsoftgraph/msgraph-sdk-powershell#2113]
I have the following code to update an application.

```
Import-Module Microsoft.Graph.Applications

$web = @{
	redirectUris = @(
		"https://example.com/saml/?acs"
	)
}

$identifiers = @(
	"https://example.com/metadata/"
)

$applicationId = "<removed>"
$clientId = "<removed>"
$tenantId = "<removed>"
$certificate = "<removed>"
$defaultUri = "https://example.com/saml/?acs"

Connect-MgGraph -ClientId $clientId -TenantId $tenantId -CertificateName $certificate
Get-MgApplication -ApplicationId $applicationId
Update-MgApplication -ApplicationId $applicationId -Web $web -IdentifierUris $identifiers -DefaultRedirectUri $defaultUri
Disconnect-MgGraph
```

I get the following error when it runs
`Update-MgApplication : Application alias 'https://example.com/metadata/' value is invalid.`

If I remove the trailing slash, it runs fine.  However, it's required by the endpoint and can't be changed.

Is there any way to allow this URL type as an identifier?

**Comment by peombwa** [comment]
The service error message is correct. The API does not allow specifying an app identifier URI that ends with a slash. This is also mentioned in the [best practices for application properties in AAD](https://learn.microsoft.com/en-us/azure/active-directory/develop/security-best-practices-for-app-registration#application-id-uri):
> The application ID URI value must not end with a slash "/" character.

Even through Azure Portal, you can't use app URI that ends with a slash:
<img width="425" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/7061532/b6a49141-1d33-4938-b5bd-b6d02029e1fd">

**Comment by peombwa** [comment]
Aha, you are using the property to set basic SAML URIs. The property can also be used to set the application Id URI, which is what I shared above.

In this case, the API does not currently allow trailing slash for `identifiers` property despite it being supported in Azure Portal for SAML configuration. Please open a service feature request at https://developer.microsoft.com/en-us/graph/support for the API team to review the ask.
