### ISSUE TITLE
Authentication Issue when using DSC process

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#212]
Microsoft365DSC is leveraging the Graph to interact with resources in M365. We've implemented a wrapper command "Test-MSCloudLogin -Patform MicrosoftGraph" which simply calls into Connect-MSGraph passing in AppId, TenantId and Certificate Thumbprint.

Since release 0.5.1, calling Test-MSCloudLogin -Platform MicrosoftGraph directly now works fine and connects properly (didn't work with previous versions). Our issue now is that when calling our Test-MSCloudLogin cmdlet from the PowerShell DSC engine it fails to connect and simply states:

**_thumbprint_ certificate was not found or has expired.**

Now we know 100% sure that the thumbprint is valid since calling Connect-MSGraph directly passing that value works. DSC runs in the context of a local user, not sure if this helps troubleshoot the issue, but it looks like the authentication context is still not properly returned to the active thread somehow.

**Comment by NikCharlebois** [comment]
@peombwa let me know if you require assistance troubleshooting this. More than happy to jump on a quick screen sharing call to show you how to replicate.

**Comment by peombwa** [comment]
@NikCharlebois could you verify that the certificate is in the current user store? Connect-Graph currently looks for certificate in the current user store `cert:\CurrentUser\My`.

**Comment by NikCharlebois** [comment]
Wow, after much investigation with ProcMon I managed to find a work around. Every DSC resource can specify a PSDSCRunAsCredential property which impersonates a specific local user to execute the the commands. I had to create a new local user, impersonate it when executing the command and load the Certificate in this new user's personal certificate store.

How is Connect-MicrosoftGraph looking for the certificates? Is is only ever looking inside the current user's personal cert store or is there a hierarchy of checks being performed for the certificate to exist at other levels in other cert stores? Thanks

**Comment by darrelmiller** [comment]
It only looks in the cert store of the account the script is assigned to run as. This was an intentional choice.  Are there good reasons for looking into the computer store?  That seemed unwise to me.

**Comment by NikCharlebois** [comment]
Agreed 100% that is not good practice here to have it in the computer store. Just had to confirm. I will close the issue and follow-up with the DSC team to figure out what local users DSC runs under and update the Microsoft365DSC documentation accordingly. Thanks folks!

**Comment by NikCharlebois** [comment]
Actually I may have close this one out too soon. We are now passed the Certificate issue but are facing yet another problem. When calling Connect-Graph -ClientID <id> -TenantId <id> -CertificateThumbprint <thumbprint> from within the context of the DSC service, the command simply returns a classic: Object reference not set to an instance of an object.

Since debugging/breakpoints aren't available in the context of DSC, is there a log we can take a look at that would provide us with more insights as to what the issue with Connect-Graph is?

**Comment by peombwa** [comment]
Could you verify that the certificate has a private key? MSAL seems to be throwing a null reference exception when a certificate has no private key - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1719.

We will update our MSAL dependency in the next release.

**Comment by NikCharlebois** [comment]
Bingo. My current user had the private key, but not the 'impersonatted' DSC user. Using psexec to add the private key to the impersonated user fixed it. I confirm that it is now 100% working. Now, to figure out how to best document this for users :) Thanks Peter!

**Comment by weyCC81** [comment]
Would it be possible to add a Switch so it would also search in "cert:\LocalMachine\My"?

- Reason 1: As we are creating/delevoping scripts we switch between User and Service Account

- Reason 2: Currently the Exchange Online Module has the Default on "cert:\LocalMachine\My"
