### ISSUE TITLE
Authentication towards custom app fails with *authorization code grant flow*

### ISSUE THREAD

**Issue by danielniccoli** [microsoftgraph/msgraph-sdk-powershell#2127]
**Describe the bug**

Authenticating towards a custom registered app with the *authorization code grant flow* fails with error code AADSTS7000218, while using the *device authorization grant flow* (`-DeviceCode`) is successful.

**To Reproduce**
1. Execute `Connect-MgGraph -ClientId $clientId -TenantId $tenantId -Scopes Mail.Send.Shared`
2. Authenticate interactively using the *authorization code grant flow*.
3. The browser shows: *"Authentication complete. You can return to the application. Feel free to close this browser tab."*
4. Return to the PowerShell window and find the error message (find text version below).
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2971735/8bd4b374-eeb5-4460-a33f-58cc85b43a6d)

5. Execute `Connect-MgGraph -ClientId $clientId -TenantId $tenantId -Scopes Mail.Send.Shared -Device`
6. Authenticate interactively using the *device authorization grant flow*.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2971735/64dc3f72-28dc-4ec2-b5c3-2f36fc446e70)
4. Return to the PowerShell window and find that authentication was successful.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2971735/f1f8f781-6ef9-4371-9fe1-d9552251dc19)

**Expected behavior**
If the device code flow works, the auth code flow should work as well. They are virtually the same.

**Module Version**
```text
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.0.0                 Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGrap…
```

**Environment Data**
```text
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**
The *Azure Registered App* is configured as follows:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2971735/c276d020-d633-4777-9a4e-4151d4c05f47)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2971735/45b69948-f71a-4c83-9c16-8983f8f93308)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2971735/f42db395-965c-4892-83e8-a490546ad71f)

Error message:
```text
Connect-MgGraph: InteractiveBrowserCredential authentication failed: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: REDACTED
Correlation ID: REDACTED
Timestamp: 2023-07-06 15:45:18Z
```

**Comment by peombwa** [comment]
Thanks for following up on this.

The issue in this case is with the selected platform, `web` (web applications that run on a server), in Azure Portal. You'll need to specify the platform as `mobile and desktop applications` with a redirect URI of `http://localhost`. Alternatively, you can modify the app's manifest in Azure Portal by changing the `replyUrlsWithType` from `web` to `InstalledClient`:
``` json
	"replyUrlsWithType": [
		{
			"url": "http://localhost",
			"type": "InstalledClient"
		}
	],
```
PowerShell is considered a console app when it comes to auth.

See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2039 and https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#configure-platform-settings for more details.

**Comment by danielniccoli** [comment]
Hi @peombwa, I also tried that, but I have only used `https://login.microsoftonline.com/common/oauth2/nativeclient` as the redirect URL, not `http://localhost`. It was not easy finding the correct documentation about that, so thanks for pointing it out to me. We got the app working now!
