### ISSUE TITLE
Feature Request: Positional Parameters

### ISSUE THREAD

**Issue by Borkason** [microsoftgraph/msgraph-sdk-powershell#213]
This module should support positional parameters where possible. See Microsoft's recommendation in that matter.

> #### ℹ️ Note
> Good cmdlet design recommends that the most-used parameters be declared as positional parameters so that the user does not have to enter the parameter name when the cmdlet is run.

https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/types-of-cmdlet-parameters?view=powershell-7

```powershell
Get-MgUser e5c3398d-6401-4dd6-bb87-6d3f95499aef
Get-MgUser jon.doe@example.com

Get-MgGroup 0f764d03-afb6-45cd-a720-84708fc0d5dc
Get-MgGroup security-group-01
``` 
[AB#7445](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7445)

**Comment by MIchaelMainer** [comment]
Note to team - AutoREST doesn't support positional parameters.

**Comment by peombwa** [comment]
Will be fixed by https://github.com/Azure/autorest.powershell/issues/749.
