### ISSUE TITLE
Invalid algorithm specified

### ISSUE THREAD

**Issue by AkosBakos** [microsoftgraph/msgraph-sdk-powershell#2138]
I am using Connect-MgGraph in the OSD specialized phase with cert-base authentication and getting this error message:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/44706641/a814c1e9-d15b-4cac-926b-07f3bd6fb529)

Authentication with AppSecret in the same stage works just fine.
Is it possible that this kind of auth method won’t work in the specialize phase?

**Comment by peombwa** [comment]
The error message points to an invalid cryptographic algorithm on the provided certificate. Per the guidance at https://learn.microsoft.com/azure/active-directory/develop/howto-create-self-signed-certificate and https://learn.microsoft.com/en-us/azure/active-directory/develop/certificate-credentials#header, Azure AD currently only supports certificates with RSA cryptographic algorithm. Please verify that the correct algorithm is used for the certificate.

You can also use MSAL.NET or [MSAL.PS](https://www.powershellgallery.com/packages/MSAL.PS/4.37.0.0) to validate that you are able to get Microsoft Graph access token using the provided certificate.
