### ISSUE TITLE
Bug with Get-MgBetaDeviceManagementReportDeviceInstallStatusReport

### ISSUE THREAD

**Issue by MaciekBednarski** [microsoftgraph/msgraph-sdk-powershell#2140]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
> Everytime I try to use Get-MgBetaDeviceManagementReportDeviceInstallStatusReport I receive very generic error, when looking into Exception behind it there is information about trying to access disposed object of type System.Net.Http.StringContent

**To Reproduce**
1. Connect to MGGraph
2. Execute Get-MgBetaDeviceManagementReportDeviceInstallStatusReport -Filter "(ApplicationId eq '<appid>'" -OutFile "temp.csv"
3. Check error

**Expected behavior**
> Should return file with devices eligible for app with their installation status

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
Get-MgBetaDeviceManagementReportDeviceInstallStatusReport -Filter "(ApplicationId eq '$mobileAppId')" -ErrorVariable errd -OutFile "temp.csv" -Debug
DEBUG: [CmdletBeginProcessing]: - Get-MgBetaDeviceManagementReportDeviceInstallStatusReport begin processing with parameterSet 'GetExpanded'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: [Authentication]: - AuthType: 'AppOnly', TokenCredentialType: 'ClientCertificate', ContextScope: 'Process', AppName: 
'app-corp-intuneapi-prod'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: [Authentication]: - Scopes: [DeviceManagementManagedDevices.Read.All, Directory.ReadWrite.All, DeviceManagementServiceConfig.Read.All, 
Directory.Read.All, User.Read.All, DeviceManagementServiceConfig.ReadWrite.All, GroupMember.Read.All, DeviceManagementConfiguration.Read.All,       
DeviceManagementManagedDevices.ReadWrite.All, GroupMember.ReadWrite.All, DeviceManagementConfiguration.ReadWrite.All,
DeviceManagementManagedDevices.PrivilegedOperations.All, DeviceManagementApps.ReadWrite.All, DeviceManagementApps.Read.All].

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a

Confirm
Are you sure you want to perform this action?
Performing the operation "Get-MgBetaDeviceManagementReportDeviceInstallStatusReport_GetExpanded" on target "Call remote 'POST
/deviceManagement/reports/microsoft.graph.getDeviceInstallStatusReport' operation".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): a
DEBUG: [CmdletException]: Received exception with message 'AggregateException - One or more errors occurred. :    at 
System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Graph.Beta.PowerShell.EventFactory.CreateLogEvent(Task`1 message)
   at
Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaDeviceManagementReportDeviceInstallStatusReport_GetExpanded.<>c__DisplayClass84_0.<Microsoft.Graph 
.Beta.PowerShell.Runtime.IEventListener.Signal>b__1()
   at
Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaDeviceManagementReportDeviceInstallStatusReport_GetExpanded.<Microsoft-Graph-Beta-PowerShell-Runti 
me-IEventListener-Signal>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Beta.PowerShell.Module.<OnResponseCreated>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Beta.PowerShell.Module.<EventHandler>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Beta.PowerShell.Module.<Signal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaDeviceManagementReportDeviceInstallStatusReport_GetExpanded.<Microsoft-Graph-Beta-PowerShell-Runti 
me-IEventListener-Signal>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Beta.PowerShell.DeviceManagementActions.<DeviceManagementReportGetDeviceInstallStatusReport_Call>d__806.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.Beta.PowerShell.DeviceManagementActions.<DeviceManagementReportGetDeviceInstallStatusReport_Call>d__806.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Beta.PowerShell.DeviceManagementActions.<DeviceManagementReportGetDeviceInstallStatusReport>d__805.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaDeviceManagementReportDeviceInstallStatusReport_GetExpanded.<ProcessRecordAsync>d__86.MoveNext()'  

Confirm
One or more errors occurred.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
Get-MgBetaDeviceManagementReportDeviceInstallStatusReport : One or more errors occurred.
At line:1 char:1
+ Get-MgBetaDeviceManagementReportDeviceInstallStatusReport -Filter "(A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgBetaDevic...ort_GetExpanded], AggregateException
    + FullyQualifiedErrorId : Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaDeviceManagementReportDeviceInstallStatusReport_GetExpanded
 
DEBUG: [CmdletEndProcessing]: - Get-MgBetaDeviceManagementReportDeviceInstallStatusReport end processing.

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.
> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.
Script     2.0.0      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext...}
Script     2.0.0      Microsoft.Graph.Beta.DeviceManag... {Add-MgBetaDeviceManagementAndroidManagedStoreAccountEnterpriseSettingApp, Add-MgBetaD...

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.
Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/139131715/2c5af12e-5acc-45b6-84b3-9c8a4dc21e14)

**Additional context**
> Add any other context about the problem here.

**Comment by peombwa** [comment]
The issue is not reproducible when using the latest v2.0.0 stable version:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/7061532/c6dff473-65c1-45a3-bfa6-a67669df04b0)

Is this an intermittent issue? Could you try running `Install-Module Microsoft.Graph -AllowClobber -Force` to ensure the latest version of the SDK is installed on your machine, and that the prerequisites stated in the [installation guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0#prerequisites) are met.

**Comment by MaciekBednarski** [comment]
I don't understand your response... it's clearly stated in my bug reporting form, that I'm using v2.0.0. 
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/139131715/e0d62d38-93f4-4d9f-a415-f56129a4d0f3)
Updating module was the first thing I did before reporting issue.
