### ISSUE TITLE
MGGraph SignInActitivy returning blank

### ISSUE THREAD

**Issue by Tekwhat** [microsoftgraph/msgraph-sdk-powershell#2141]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
> SignInActivity does not produce any data

**To Reproduce**
I am currently having this issue when attempting to pull a report.

``````
# Authenticate with Office 365
Connect-MgGraph -Scopes "User.Read.All","AuditLog.Read.All"

# Get user information
$users = Get-MgUser -all -Select "displayName,accountEnabled,lastPasswordChangeDateTime,lastSignInDateTime" 

# Output the results
$report = @()
foreach ($user in $users) {
    $name = $user.displayName
    $isEnabled = $user.accountEnabled
    $lastPasswordReset = $user.lastPasswordChangeDateTime
    $lastLogin = $user.lastSignInDateTime

    $userReport = [PSCustomObject]@{
        Name = $name
        LastPasswordReset = $lastPasswordReset
        LastLogin = $lastLogin
        IsEnabled = $isEnabled
    }

    $report += $userReport
}

$report | Format-Table -AutoSize
``````

When I attempt to pull this for a user, I get blanks:

```
Get-Mguser -UserId [id] | select -ExpandProperty signinactivity

LastNonInteractiveSignInDateTime LastNonInteractiveSignInRequestId LastSignInDateTime LastSignInRequestId
-------------------------------- --------------------------------- ------------------ -------------------
```
**Expected behavior**
> I should be able to see the data under SignInActivity

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
2.0.0

**Comment by SeniorConsulting** [comment]
Gidday Tekwhat,

The property 'lastSignInDateTime' isn't presented by the Graph API, which is why you're not able to return any results from it:
https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties

Perhaps you could try Get-MgAuditLogSignIn instead?

**Comment by Tekwhat** [comment]
Hello SeniorConsulting,

get-mgauditlogsignin also didnt return any data for spesfic users. 

To your second part, yes I was using the object Guid/id for that query.

I believe this can be closed out, I just added an azuread query to the graph data I was pulling. 

Thank you for letting me know this isnt possible with the graph API, yet.

**Comment by SeniorConsulting** [comment]
The AzureAD modules will be getting deprecated soon. It might be worth spending a little bit more time and pain getting the newer stuff in the Graph API SDK up and running.

You've mentioned that Get-MgAuditLogSignIn didn't return any results. This cmdlet definitely works on my device/lab.

- Are any errors being displayed?
- If you run Get-MgContext, do the scopes show that you've actually authenticated with User.Read.All, and AuditLog.Read.All?
