### ISSUE TITLE
Undocumented Breaking change with WindowsAutopilotDevice Cmdlets

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/msgraph-sdk-powershell#2146]
**Describe the bug**
Windows Autopilot Device Cmdlets break after update due to renaming (breaking change without documentation)

**To Reproduce**
1. Install v1 Graph SDK
2. Write Script with Get-MgDeviceManagementWindowAutopilotDeviceIdentity
3. Update to v2 Graph SDK
4. -> Cmdlet is not found anymore

**Expected behavior**
After updating to 2.0.0 the Typo in the WindowAutopilotDeviceIdentity was fixed. e.g. Get-MgDeviceManagementWindow**(s)**AutopilotDeviceIdentity. As there is no Alias in place this is a breaking change that is not mentioned in the v1 to v2 migration path and should be aliased or documented as breaking change.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention!

The product name fix (`Window` -> `Windows`) happened in an upstream dependency, which led to it not being captured in the SDKs breaking change. We will update the breaking change guide to capture this breaking change. In this case, the new command in v2 should be `Get-MgDeviceManagementWindowsAutopilotDeviceIdentity`.
