### ISSUE TITLE
MgDeviceAppMgtiOS Cmdlets Renamed

### ISSUE THREAD

**Issue by tbisque** [microsoftgraph/msgraph-sdk-powershell#2159]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
> In 2.0, the cmdlets for MgDeviceAppMgtiOS were renamed to MgDeviceAppMgtiO (without the s).

**To Reproduce**
1. Get-command *Get-MgDeviceAppMgtIo* 

**Expected behavior**
> Have iOS in the name in the cmdlet

**Debug Output**
> N/A

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.

Name    : Microsoft.Graph.Authentication
Version : 2.0.0
Name    : Microsoft.Graph.Beta.Devices.CorporateManagement
Version : 2.0.0

> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

The `alias` has been corrected to its proper form in our latest release v2.1.0 - https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/2.1.0.

``` powershell
➜ Get-command Get-MgDeviceAppMgtiOSManagedAppProtection

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Get-MgDeviceAppMgtiOSManagedAppProtection          2.1.0      Microsoft.Graph.Devices.CorporateManagement
```

The resolved command name for the `alias` is `Get-MgDeviceAppManagementiOSManagedAppProtection`:
``` powershell
➜ Get-command Get-MgDeviceAppMgtiOSManagedAppProtection | select ResolvedCommand

ResolvedCommand
---------------
Get-MgDeviceAppManagementiOSManagedAppProtection
```
