### ISSUE TITLE
Incorrect cmdlet name in doc for Get-MgDeviceManagementWindowsAutopilotDeviceIdentity

### ISSUE THREAD

**Issue by merill** [microsoftgraph/msgraph-sdk-powershell#2166]
The generated doc has Window (missing the s) instead Windows.

https://learn.microsoft.com/powershell/module/microsoft.graph.devicemanagement.enrolment/get-mgdevicemanagementwindowautopilotdeviceidentity

**Expected cmdlet name in docs**
Get-MgDeviceManagementWindowsAutopilotDeviceIdentity

**Actual**
Get-MgDeviceManagementWindowAutopilotDeviceIdentity

Isn't this autogenerated? Not sure how it can be out of sync.

**Module Version**
2.1.0

See Twitter thread that prompted this: https://twitter.com/UgurKocDe/status/1680212594550865920?s=20

**Comment by ugurkocde** [comment]
Hi, there might be more issues related to this.

1. Some of the commands use different modules where a single letter is different:
[Microsoft.Graph.DeviceManagement.Enrolment](https://learn.microsoft.com/de-de/powershell/module/microsoft.graph.devicemanagement.enrolment/?view=graph-powershell-1.0) vs. [Microsoft.Graph.DeviceManagement.Enrollment](https://learn.microsoft.com/de-de/powershell/module/microsoft.graph.devicemanagement.enrollment/?view=graph-powershell-1.0)

2. I get a signage error when I try to install the Module [Microsoft.Graph.DeviceManagement.Enrolment](https://learn.microsoft.com/de-de/powershell/module/microsoft.graph.devicemanagement.enrolment/?view=graph-powershell-1.0): 
![grafik](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/43906965/c760c483-2bbd-4820-8712-e7f09611eed1)

3. There are more spelling errors e. g. in [Microsoft.Graph.DeviceManagement.Enrolment](https://learn.microsoft.com/de-de/powershell/module/microsoft.graph.devicemanagement.enrolment/?view=graph-powershell-1.0):
- Get-MgDeviceManagementWindowAutopilotSetting
- Get-MgDeviceManagementWindowAutopilotDeviceIdentityDeploymentProfile
- Get-MgDeviceManagementWindowFeatureUpdateProfile
- and more.

Possible solution would be to combine the commands from both modules into a single one and correct the typos.

**Comment by peombwa** [comment]
Thanks for following through on this.

This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2154#issuecomment-1638416214. In summary, the module and cmdlet name change are covered in the [breaking change guide](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/docs/upgrade-to-v2.md#renamed-devicemanagementenrolment-module-to-devicemanagementenrollment). The cmdlet reference docs wrongly shows stale cmdlet reference doc for the now replaced `DeviceManagement.Enrolment` module (single L) . The stale docs will be removed by https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/322.

Please use the reference docs for `DeviceManagement.Enrollment` (double LL) instead, [v1.0](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement.enrollment/?view=graph-powershell-1.0) and [beta](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.beta.devicemanagement.enrollment/?view=graph-powershell-beta), as the docs clean-up happens in https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/322.
