### ISSUE TITLE
No cmdlet for GetAllSites

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-powershell#2168]
**Is your feature request related to a problem? Please describe.**
There is a new [API](https://learn.microsoft.com/en-us/graph/api/site-getallsites?view=graph-rest-1.0&tabs=http) to list all root sites for multi-geo but no cmdlet for PowerShell SDK

**Describe the solution you'd like**
Add a new cmdlet `Get-MgAllSites`.

**Describe alternatives you've considered**
It supports OData query parameters except `$expand`

**Additional context**

**Comment by peombwa** [comment]
The command is expected to ship as part of this week's API refresh. `Get-MgAllSite` should be available in v2.2.0 later this week.

**Comment by peombwa** [comment]
The command is now available in [v2.2.0](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/2.2.0) - https://learn.microsoft.com/en-us/graph/api/site-getallsites?view=graph-rest-1.0&tabs=powershell#example-1-initial-request.

Closing as resolved.
