### ISSUE TITLE
Commands fail when issuing commands from both versions in the open session.

### ISSUE THREAD

**Issue by Cyb3r4rch3r** [microsoftgraph/msgraph-sdk-powershell#2174]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
`Get-MgBeta*` fails to load with the following error message:

`Get-MgBetaUser: The 'Get-MgBetaUser' command was found in the module 'Microsoft.Graph.Beta.Users', but the module could not be loaded due to the following error: [Assembly with same name is already loaded] For more information, run 'Import-Module Microsoft.Graph.Beta.Users'.`

**To Reproduce**
1. Execute `Get-MgUser`
2. Execute `Get-MgBetaUser` 

Alternatively
1. Execute `Get-MgBetaUser`
2. Execute `Get-MgUser`

**Expected behavior**
User data should be returned

**Debug Output**
> Get-MgBetaUser -All:$true -Debug
Get-MgBetaUser: The 'Get-MgBetaUser' command was found in the module 'Microsoft.Graph.Beta.Users', but the module could not be loaded due to the following error: [Assembly with same name is already loaded]
For more information, run 'Import-Module Microsoft.Graph.Beta.Users'.

**Module Version**
```
Version              Name                                Repository           Description
3.1.0                Microsoft.Graph.Beta                PSGallery            Microsoft Graph PowerShell module
```

**Environment Data**
PowerShell 5.1 and Core versions

```
$psversionTable

Name                           Value
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

$PSVersionTable

Name                           Value
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/6243762/cfbbef37-8a89-46e9-8122-e112c48f8abd)

**Additional context**
Tried removing the loaded modules, including the `-Force` switch, and reloading/importing the module or executing the command with the same results. The examples show the commands to retrieve users, but in testing this has been consistent with any `Get-MgBeta*` command in any version 1 command has been issued in the session. Similarly, this is repeatable with all version 1 commands if a new session is created and beta commands are issued first. This breaks any manual or scripted processes that utilize commands from both versions of the module. 
There is no mention of this behavior in the breaking changes, known issues, or docs pertaining to the recent module split.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/6243762/f8584da9-a9ab-48f4-9a53-d0c4c25a123a)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/6243762/d16ca735-b32a-42d5-bc9e-62c29b68c1e8)

**Comment by SeniorConsulting** [comment]
Hi Cyb3r4rch3r,

I can't replicate your issue:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/b1c14cb4-b430-4c52-8a01-6b9dcf878a4b)

Could you double check both your module versions are the same? i.e. Microsoft.Graph, and Microsoft.Graph.Beta. While you can run a get-module Microsoft.Graph*, another option might be to run the Get-Command functions as in my screenshot.

Also just checking you've done the basic ol' close PowerShell and open it again.

**Comment by Cyb3r4rch3r** [comment]
Yes, both Microsoft.Graph and Microsoft.Graph.Beta are/were version 2.1.0.
I was able to resolve this by uninstalling both modules and deleting the module folders from PSModulePath.

**Comment by khha** [comment]
I have the same issue on an Azure function. How to resove this?
