### ISSUE TITLE
Support ROPC i.e. username and password

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/msgraph-sdk-powershell#2185]
Other PowerShell modules supports this...
Connect-AzAccount -Credential
Connect-AzureAd -Credential

This helps with automating scripts using a user based service account. Especially with certain API calls that do not support client credentials.

**Comment by timayabi2020** [comment]
Hi, @willfiddes ,
Thank you for bringing this up, however we currently don't support ROPC due to the comments [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/148)
