### ISSUE TITLE
Update chatMessage with application permissions not working, 412 (PreconditionFailed) 

### ISSUE THREAD

**Issue by johnavalos274** [microsoftgraph/msgraph-sdk-powershell#2190]
I am using API version 1.0 with msgraph-sdk-powershell
I am trying to update the Violation Policy of a Teams chat message in chats with application permissions and I keep getting a 412 error code.
The code I am using is as follows:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/113067738/17ed60b0-8c5b-4980-8c52-c4d88d6e84f6)

I get the following error when running this script:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/113067738/c0befdac-dc9b-4c97-a255-76dd1b1a3bb2)

I'm not sure why I continue to get an error code for the Update chatMessage function.
I don't think it is a problem with authorization or bad credentials.

**Comment by timayabi2020** [comment]
Hi, @johnavalos274, based on the output, this is a service issue. Please open a support ticket/question at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner. See https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug for more troubleshooting details.

**Comment by johnavalos274** [comment]
Thank you for the information. I have submitted a ticket to the link you have provided above.
