### ISSUE TITLE
MgDeviceManagementTemplateInstance & MgDeviceManagementIntentMultipleSetting missing?

### ISSUE THREAD

**Issue by jpedlow** [microsoftgraph/msgraph-sdk-powershell#2194]
**Describe the bug**
> Issues creating intents in 2.0

Previously, if I wanted to make a bitlocker device intent under earlier versions of the SDK I would do the following:

```
$intentsettings = [abunchofJSON]
$newinstance = New-MgDeviceManagementTemplateInstance -DisplayName "bitlocker" -Description "bitlocker intent" -DeviceManagementTemplateId "d1174162-1dd2-4976-affc-6667049ab0ae"
Update-MgDeviceManagementIntentMultipleSetting -DeviceManagementIntentId $newinstance.id -BodyParameter $intentSettings
```
**To Reproduce**

get-command -noun MgDeviceManagementIntentMultipleSetting
get-command -noun MgBetaDeviceManagementIntentMultipleSetting
get-command -noun MgDeviceManagementTemplateInstance
get-command -noun MgBetaDeviceManagementTemplateInstance

All give no returns, there appears to be no replacement for these cmdlets in either the regular or beta side of the SDK. They appear to have vanished.

**Expected behavior**
> I would expect an intent to appear under Get-MgBetaDeviceManagementIntent (previously Get-MgDeviceManagementIntent), with an assigned template ID & settings.

```
get-mgbetadevicemanagementintent

Id                                   Description        DisplayName                 IsAssigned IsMigratingToConfigurationPolicy LastModifiedDateTime  RoleScopeTagIds TemplateId
--                                   -----------        -----------                 ---------- -------------------------------- --------------------  --------------- ----------
bitlocker                         bitlocker intent                                   False                                       7/7/2023 6:31:56 PM   {0}             d1174162-1dd2-4976-affc-66670ab0ae


```
**Debug Output**
> (Cmdlets not found)

**Module Version**
>2.1

**Additional**
I'm 100% willing to accept that I'm doing something WRONG, but I need clarification on how to do disk encryption under endpoint settings in any other fashion. 
Unfortunately, it appears the error handling may have also changed, I now get a rather generic response of "One or more errors occurred." when attempting to work through the cmdlets.

**Comment by timayabi2020** [comment]
Hi @jpedlow, kindly confirm if you have installed the beta version of the SDK as per the installation guide [here](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0#installation). 
Also have a look at the V2 upgrade [guide](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/docs/upgrade-to-v2.md)

**Comment by jpedlow** [comment]
HI @timayabi2020  - I hope you're well today. :) 

I updated to 2.2 and it's all showing up now.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/46536194/ccbbdf85-d74f-4a8d-9eaa-dbd51a923702)


Feel free to close  -  thanks for the rapid response.

**Comment by timayabi2020** [comment]
@jpedlow I am well.
Wonderful. Have a good one.
