### ISSUE TITLE
internalUrl is missing in the response for GET applicationtemplate

### ISSUE THREAD

**Issue by karpikpl** [microsoftgraph/msgraph-sdk-powershell#2195]
**Is your feature request related to a problem? Please describe.**
Graph API does not provide a method for reading `internalURL` of application proxy.
Powershell has `Get-AzureAdPplicationProxyApplication` that returns it but MS graph seems to be missing it.

**Describe the solution you'd like**
`internalURL` should be added to results of GET https://learn.microsoft.com/en-us/graph/api/resources/applicationtemplate?view=graph-rest-beta 

**Describe alternatives you've considered**
There are no alternatives. I asked internally at MS Graph team.

**Additional context**
Feature requested by customer. They are gathering both external and internal URLs of application proxies.  In Azure AD, there is the command `Get-AzureADApplicationProxyApplication`, using which you can gather the external and internal URLs. However, there is no MS Graph equivalent to this command, outside of being able to configure a proxy using the beta API, and the URLs do not show up in the MS Graph API explorer.

**Comment by timayabi2020** [comment]
Hi, @karpikpl thank you for bringing up this issue, however this is an API feature request, and it can be tracked by the API owner once you open a feature request [here](https://developer.microsoft.com/en-us/graph/support)

**Comment by karpikpl** [comment]
OK, I've created https://feedbackportal.microsoft.com/feedback/idea/dbd8f9c5-c02c-ee11-a81c-6045bdbbbc93

**Comment by timayabi2020** [comment]
@karpikpl nice. I hope it will be addressed ASAP.
