### ISSUE TITLE
Add `$` prefix to all OData query options.

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#22]
With Microsoft Graph v1.0, `$` prefix is only optional for a subset of the API. We should therefore **ALWAYS** include the `$` prefix in all OData query parameters.

Ref: https://docs.microsoft.com/en-us/graph/query-parameters

**Comment by darrelmiller** [comment]
Possible solution:  Middleware that looks for a v1.0 URL and adds $ prefix to all standard Odata query parameters.
