### ISSUE TITLE
Clarification specifying -Assignments for Update/New-mgPlannerTask 

### ISSUE THREAD

**Issue by jasonclamb** [microsoftgraph/msgraph-sdk-powershell#220]
I am creating new Planner Tasks using New-mgPlannerTask but I cannot figure out how to specify the correct value for -Assignments to assign tasks to particular users.  Please provide some guidance on how to create an object of type IMicrosoftGraphPlannerAssignments.
 
[AB#7449](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7449)

**Comment by MIchaelMainer** [comment]
We don't currently support this. Need to support for additional property bag.

Related to #119

**Comment by peombwa** [comment]
This is now supported. See https://docs.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=powershell#request.
