### ISSUE TITLE
Using "Get-MgUserEvent -filter" with apostrophe

### ISSUE THREAD

**Issue by rogers14k** [microsoftgraph/msgraph-sdk-powershell#2208]
Hi - Im trying to do a calendar search based on subject but the subject has an apostrophe and its causing the command to error out. Ive tried numerous workarounds such as adding a double apostrophe and $encodedFilter = [System.Uri]::EscapeDataString("") with no luck. Any workaround to this?

Examples:
Fail:
 Get-MgUserEvent -filter "subject eq 'What's new in the org'" -userid user@domain.com

Working:
 Get-MgUserEvent -filter "subject eq 'Daily Scrum'" -userid user@domain.com

**Comment by SeniorConsulting** [comment]
You've mentioned that [double apostrophe](https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#escaping-single-quotes) didn't work for you, however, I've managed to get it working using:
`Get-MgUserEvent -filter "subject eq 'What''s new in the org'" -userid user@domain.com`

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/97a25db9-d6ec-41d1-a72f-d09975c74edf)

**Comment by rogers14k** [comment]
I'm sorry this was user error and the double apostrophe was the resolution. Thanks for replying!
