### ISSUE TITLE
connect-mggraph define which browser is used for interactive login-sessions (macOS)

### ISSUE THREAD

**Issue by joergrenn** [microsoftgraph/msgraph-sdk-powershell#2214]
Hello,

is there a way to define which Browser is used for interactive logins for connecting to the Graph API?
When I issue "connect-mggraph" command my default browser opens. However I have a few different browsers installed and use them for different identities.
I know that there are other options like -useDeviceAuthentication, but it would be easier to be able to define which Browser is used by PowerShell / Grpah for these login sessions.

**Comment by peombwa** [comment]
Thanks for following up on this.

It is currently not possible to specify which browser is used for interactive authentication. The SDK does not open the browser; this is done by MSAL, the authentication library. MSAL uses your OS default browser to open the dialog box.

**Comment by serkonda7** [comment]
I want to perform the login  from  a private browser window. Is there by any chance a way to instruct MSAL to use a private browser window?
