### ISSUE TITLE
Known Issues Token Cache incorrect folder/file reference?

### ISSUE THREAD

**Issue by dotnvo** [microsoftgraph/msgraph-sdk-powershell#2215]
**Describe the bug**

This is more of a report of an issue with the docs. I have updated the PowerShell Graph module to the latest version.

On the known issues (https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues) doc, it references folks getting prompted for authentication over and over again to clear their token cache (which refers to a local file/folder with a name of .mg in the user's local user profile directory.  

Reviewing that directory, I did not see a .MG file or folder (I'm assuming it's a folder). Running `Get-ChildItem -Recurse` returns nothing.  However, I did find a .graph folder with a ecache.bin3 file in it. Should this known issues actually be pointing to that? Testing that folder does get created when `Connect-MgGraph` is called.

**Comment by peombwa** [comment]
`.graph` directory is only used by v1.x of the SDK. See known issues for v1.x at https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/support/1.x#known-issues.

The known issues doc in the dev branch (default) is for v2.x of the SDK. `.mg` directory is used in v2.x for token cache synchronization when logged in via current user context scope and other SDK configurations.

**Comment by dotnvo** [comment]
@peombwa  

Thanks, appreciate it. I didn't even know there was a v2 of PowerShell SDK for Graph.  Looks like it's somewhat new googling around a bit.

 I think that answers my question so will close this one out unless you want me to leave it open.
