### ISSUE TITLE
Get-MgServicePrincipal not returning anything for either AppRoles or OAuth2PermissionGrants

### ISSUE THREAD

**Issue by jwelker9** [microsoftgraph/msgraph-sdk-powershell#2221]
**Describe the bug**
Get-MgServicePrincipal doesn't return anything for the AppRoles or OAuth2PermissionGrants, despite the SP having both Delegated and App Perms assigned. 
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/15617006/863ef02c-ddfb-48ce-86f5-1a028dbf984d)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/15617006/f04625fc-ee76-46ad-a62f-fcb5dade879b)

I am a Global Administrator, so I don't suspect a permission issue, especially since the rest of the object returns ok. I have run into this issue in several tenants. I also get this issue If I use the associated API as the documentation states [here](https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-configure-permissions?tabs=http%2Cupdatepermissions-azureadgraph-powershell#step-1-identify-the-permission-ids-for-the-azure-ad-graph-permissions-your-app-requires)

**Expected behavior**
Per this [documentation](https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-configure-permissions?tabs=http%2Cupdatepermissions-azureadgraph-powershell#response-2), I would expect a similar response object as the one below:
```
Welcome To Microsoft Graph!
Azure AD Graph service principal object and its supported permissions:
Application permissions:
AllowedMemberTypes   : {Application}
Description          : Allows the app to read applications and service principals without a signed-in user
DisplayName          : Read all applications
Id                   : 3afa6a7d-9b1a-42eb-948e-1650a849e176
IsEnabled            : True
Origin               : Application
Value                : Application.Read.All
AdditionalProperties : {}

Delegated permissions:
AdminConsentDescription : Allows users to sign in to the app, and allows the app to read the profile of signed-in users. It also allow the app to read basic company information of signed-in users.
AdminConsentDisplayName : Sign in and read user profile
Id                      : 311a71cc-e848-46a1-bdf8-97ff7156d8e6
IsEnabled               : True
Origin                  :
Type                    : User
UserConsentDescription  : Allows you to sign in to the app with your work account and let the app read your profile. It also allows the app to read basic company information.
UserConsentDisplayName  : Sign you in and read your profile
Value                   : User.Read
AdditionalProperties    : {}
```

**Debug Output**
No results to share here, as it is not returning anything at all. No errors.

**Module Version**
<img width="306" alt="Screenshot 2023-08-04 161300" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/15617006/ea0d86e8-4311-473e-a5c2-1b48ebb22a1d">

**Environment Data**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/15617006/c80f7d8b-7733-4677-abe5-b5f151af8fcc)

**Screenshots**
Inserted above

**Additional context**
For what it's worth, I'm able to return the data using `Get-MgServicePrincipalAppRoleAssignment` and `Get-MgServicePrincipalOauth2PermissionGrant`, but the object supposedly returned by `Get-MgServicePrincipal` is much easier to work with and saves me from having to make a second call. Any help is appreciated. Thanks.

**Comment by peombwa** [comment]
Thanks for following up on this.

Please open a question/ticket at https://developer.microsoft.com/graph/support as this is an API issue:
> I also get this issue If I use the associated API as the documentation states [here](https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-configure-permissions?tabs=http%2Cupdatepermissions-azureadgraph-powershell#step-1-identify-the-permission-ids-for-the-azure-ad-graph-permissions-your-app-requires)

The issue is not with the client (PowerShell) as the service is not returning the expected results for your requests. See the [troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details.

**Comment by jwelker9** [comment]
Thanks for the response. Is there no associated repo for the Graph APIs generally? I'd prefer to leave feedback there, as I feel the Q+A site has left me hanging in the past. Anyway this ticket can be forwarded to that repo, if so?

Regardless, I have opened a [new ticket on the Learn Q+A](https://learn.microsoft.com/en-us/answers/questions/1344753/get-mgserviceprincipal-not-returning-anything-for) site. Thanks again.
