### ISSUE TITLE
Using PIM and AzureAD roles

### ISSUE THREAD

**Issue by triumfas** [microsoftgraph/msgraph-sdk-powershell#2229]
It would be good to get access based not only upon consenting each user or whole organization, but also get access when you have admin role activated through PIM. At the moment I can't think of a way how to deal with multiple users/teams and different access rights. It's either case by case or you grant too many rights over time. Am I missing something or it's how it works for now?

**Comment by jwelker9** [comment]
I'm not from Microsoft, to be clear, but trying to understand your question @triumfas. When you mention consenting each user or whole organization, I'm assuming you're referring to API permissions? And if so, are you asking if there's a way to leverage PIM to gain API permissions (aka as 'eligible)?

**Comment by triumfas** [comment]
You are correct. While using AzureAD module - you get permissions based on the active role for your account. And it's not the case with MSGraph. As it's going to be deprecated and MSGraph powershell is a suggested option, I'm trying to understand how to manage it in large organization. If you consent each user based on users case - there will be multiple users in each permission (governance would be a nightmare) and the access would be permanent. I could see an option to have enterprise application scope set with groups that you need to activate membership for (similar to activating role), but you can't set specific permissions per group. Or can you? 
Different option fixes one issue, but faces another and I'm wondering what is the proposed way to deal with it.

**Comment by peombwa** [comment]
Consent purely based on Azure AD roles is not supported by the Microsoft Graph API today. Each Microsoft Graph API endpoint has permission(s) which a user/app must consent to before accessing Microsoft Graph resources - https://learn.microsoft.com/graph/permissions-overview. Certain API endpoints will require you to have both Azure AD roles and Graph permissions to access a resource.

AzureAD module used pre-authorized overprivileged permissions to automatically grant access which [wasn't secure](https://learn.microsoft.com/en-us/azure/active-directory/develop/secure-least-privileged-access). With Microsoft Graph, permissions are not pre-authorized, and users must perform one-time request for app permissions depending on their needs. Exclusively using Azure AD roles is not sufficient to grant a user access to Microsoft Graph resource today.

Please ask your question/open a feature request at https://developer.microsoft.com/graph/support for recommendations from subject matter experts on how to manage consent in a large organization for multiple users. This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

**Comment by triumfas** [comment]
@peombwa Thank you for information provided. Will ask Graph support.

A sad thing is that Microsoft did not make AzureAD custom roles available (permissions from which you can choose for custom roles does not make any sense/help). Now MS is going to deprecate modules that used to work with PIM. From time to time it looks like nobody actually use PIM - you just grant permanent rights (application permissions) and forget and that contradicts best practices from MS itself.
