### ISSUE TITLE
Wrongly named cmdlets

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#223]
This issue it to keep track of cmdlets that are not properly named.

**Comment by peombwa** [comment]
- `{Remove | Update}-MgCertificateBasedAuthConfigurationCertificateBasedAuthConfigurationCertificateBasedAuthConfiguration`
- `{Get | New}-MgCertificateBasedAuthConfigurationCertificateBasedAuthConfigurationCertificateBasedAuthConfiguration`
- `{Remove | Update}-MgCertificateBasedAuthConfigurationCertificateBasedAuthConfigurationCertificateBasedAuthConfiguration`
- #204

**Comment by tommymaynard** [comment]
I have to admit, I'm curious to know why the `Connect` and `Disconnect` cmdlets from the `Microsoft.Graph.Authentication` module don't include the "Mg" prefix. It seems as though these should include the prefix, as they're members of a Microsoft.Graph.* module. Additionally, it's possible that the _first_ cmdlet to which someone may be introduced will be `Connect-Graph`. Why then shouldn't this command include the prefix? There's over 3,500 commands and as best as I can tell, only two didn't get the prefix. That should keep someone awake at night; it would me. ;)

**Comment by KirkMunro** [comment]
#75 was logged a while ago and should be tracked as part of this "bucket" issue.

**Comment by mabster** [comment]
Just spotted Get-MgBusinessFlowTemplateBusinessFlowTemplateBusinessFlowTemplate in module version 0.7.0.
