### ISSUE TITLE
Suggestion: Filter Cmdlets that are known to not work

### ISSUE THREAD

**Issue by BHoggs** [microsoftgraph/msgraph-sdk-powershell#2234]
**Is your feature request related to a problem? Please describe.**
More than once I have spent significant time wrestling with a few Cmdlets to get something to work... when hours later I encounter an issue on github that indicates it's a known issue that this feature is not yet implemented, or has known issues.

Some recent examples:
- Set-MgApplicationLogo
- *Delta Cmdlets

**Describe the solution you'd like**
Add some kind of build-time filter that either removes broken cmdlets, or perhaps injects a console warning that there are known issues with the Cmdlet. Bonus points if it can link to the github issue.

This could save many hours of lost productivity! This could also greatly reduce the number of duplicate issues that get opened on the daily.

**Describe alternatives you've considered**
I've considered a warning may be better than just removing them... as it's helpful to know the functionality is a WIP, rather than missing.

**Additional context**
N/A

**Comment by SeniorConsulting** [comment]
It could be beneficial that if there's an issue with the cmdlet rather than the API itself (Not a service issue), then including a message stating that as a workaround Invoke-MgGraphRequest can be used.

At least this workaround will still manage paging, and authentication - two of the most difficult things to work around without the SDK.

**Comment by BHoggs** [comment]
9/10 times the related github issue has a usable workaround in it (often using Invoke-MgGraphRequest). I think keeping it simple and providing a link to the github issue could be a universally simple way to "lead a horse to water" without going overboard and coding in workarounds to every issue the crops us.

Bit of a stretch, but it could also have the side effect of inviting more developers to come and contribute to the project. ;)

**Comment by timayabi2020** [comment]
@BHoggs thanks for those suggestions and I also agree that a warning/alert would be ideal for such cases. We will work towards having that suggestion implemented. Meanwhile, there is a similar issue [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/935) with a work around.

**Comment by BHoggs** [comment]
@timayabi2020 was this meant to be closed? Didn't think you were waiting on any feedback
