### ISSUE TITLE
Sign into Azure AD with a FIDO2 security key doesn't work in MS Graph PowerShell SDK

### ISSUE THREAD

**Issue by SteveMutungi254** [microsoftgraph/msgraph-sdk-powershell#2237]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
> A clear and concise description of what the bug is.

**To Reproduce**

Error encountered when running Connect-MgGraph.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/132555836/2846e2f3-d171-4a1c-9aed-bd7b5267486a)

**Expected behavior**
1. Successfully sign in to Azure AD (Microsoft Entra) via PowerShell Connect-MgGraph.
2. Update public documentation with a comprehensive guide, examples, and common errors or even known issues.

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.
> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by timayabi2020** [comment]
@SteveMutungi254 please try and use PowerShell 7 for passwordless authentication options.
Refer to this article on passwordless authentication options. https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0

**Comment by SteveMutungi254** [comment]
The customer has confirmed that FIDO2 capability works as expected from PowerShell 7+.
