### ISSUE TITLE
Graph SDK Enterprise Application - What's happening exactly?

### ISSUE THREAD

**Issue by adnkai** [microsoftgraph/msgraph-sdk-powershell#2244]
Can anyone tell me what the creation process of the Enterprise Application is?
I don't really get how it works.

We used `Connect-MGGraph` with interactive authentication (user login). And somehow there is an Enterprise Application now in Azure AD.
Get-MgContext shows said application is being used and the user who created it.
However, that user is not allowed to create Applications in Azure AD.

So what is happening here, exactly? How does the SDK create and determine which Client ID to use without specifying it?

**Comment by RayGHeld** [comment]
Anytime someone consents to permissions for an application, the enterprise app is created.  That is where consent for permissions is stored.  Every app registration, once consent is applied, will have an enterprise app associated with it.  I like to think of it like this, App registration is where permissions are configured, client secrets, etc.  The enterprise app is a copy of the app registration as far as configuration is concerned but also has the consent objects on it.  There are other things that can be done on the enterprise app but that is the jest of it.  If there is no enterprise app, then no one can sign in to that app.  Hope that helps!

**Comment by Akaino** [comment]
Yeah no, I get that one. How does my CLI know of this enterprise app though? Like, nobody created it in the first place. Anytime a user logs in with Connect-MgGraph that specific principal is being used.
We're not defining it anywhere though. No client ID or anything. Just simple interactive Auth against AzureAD.

So my question really is, how is it determined _which_ enterprise app is being used without specifying it explicitly.

**Comment by BHoggs** [comment]
The default client ID is hard-coded into the SDK, which is a multi-tenant app registration configured on the Microsoft tenant. So nothing needs to be added on your end. An enterprise application gets created in your tenant as a "representation" of the app, and as mentioned, just stores some local config like who has consented, or who can sign-in if you want to lock it down.

It's possible someone with admin rights consented to the graph sdk first, which adds the enterprise app. Subsequently, there are some basic permissions which then don't require admin consent - which could explain why your user was able to consent.

 The same thing happens with office 365 apps, azure portal, etc. It's fundamentally how oauth2 works.

**Comment by Akaino** [comment]
Thank you! That's what I needed to know.
So essentially the App Registration is provided by Microsoft.

Is that documented somewhere in the docs? Or mentioned anywhere by Microsoft on how the SDK works?
