### ISSUE TITLE
Get-MgDirectoryRoleTemplate does not return role that is not enabled/assigned to a user

### ISSUE THREAD

**Issue by connorcopusmsft** [microsoftgraph/msgraph-sdk-powershell#2257]
**Describe the bug**
Get-MgDirectoryRoleTemplate | ? DisplayName -eq "Exchange Admin" doesnt reutrn a template unless it is present on at least one user in the tenant. 

**To Reproduce**
1. Execute Get-MgDirectoryRoleTemplate | ? DisplayName -eq "Exchange Admin" when role is not assigned to a user
**Expected behavior**
> A clear and concise description of what you expected to happen.

**Module Version**
2.3

**Environment Data**
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
Role should return roles even if not enabled (assigned to a user) as they are still avalible in the admin center to assign to a user

**Comment by SeniorConsulting** [comment]
Hi Connor,

Please try "Exchange Administrator" on your pipeline.
`Get-MgDirectoryRoleTemplate | ? DisplayName -eq "Exchange Administrator"`

**Comment by timayabi2020** [comment]
@SeniorConsulting thanks alot,  your suggestion also worked for me.
@connorcopusmsft I also tried listing all the Display names that contains "Exchange" just to confirm if the one I'm looking for exists by running ```Get-MgDirectoryRoleTemplate | Where-Object -FilterScript {$_.DisplayName -LIKE 'Exchange*'}```. 
<img width="879" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/e9599ecc-2b44-43be-8e89-9bfd045667d6">
