### ISSUE TITLE
Disable Writeback For all Existing Microsoft 365 groups

### ISSUE THREAD

**Issue by Th3Gl1tch** [microsoftgraph/msgraph-sdk-powershell#2259]
Disabling Writeback for all Existing Microsoft 365 groups script doesn't work. 

Per this article 
https://learn.microsoft.com/en-us/azure/active-directory/hybrid/connect/how-to-connect-group-writeback-v2#understand-limitations-of-public-preview

"If isEnabled is null or true, the group will be written back."

![default-writeback](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13876134/07e56978-d233-4a32-8f3a-166dd4e78d8a)

All existing M365 groups are set as No writeback in portal but Null in Graph. The expected result when turning on group writeback would be that all the M365 groups will be written back. We don't want this to happen so I attempted to use the powershell command in this article to set isEnabled to false. 
https://learn.microsoft.com/en-us/azure/active-directory/hybrid/connect/how-to-connect-modify-group-writeback

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13876134/08602eda-3e6f-4161-b74b-5b1e24138b2b)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13876134/00dfeb71-06ff-464d-a621-a17ac42673e8)

I have installed powershell 7 and installed MSGraph modules (version 2.3.0)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13876134/9f5cee04-f59a-4de7-844f-fc6b1f2d14f0)

Attempting to run the provided powershell command results in the following error

Powershell script provided
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13876134/aa8512f8-7999-4d5f-83d1-dfadad1a4d01)

Results of running the script
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13876134/525c44eb-8cee-4106-99ca-7a8feacd29ef)
There appears to be issues on line 6 and 14 of the provided script. Line 14 shows the same error over and over for each group. 

I have reproduced these results on two different systems and did a fresh install of the MSGraph module. 
I also worked with Microsoft support from Graph and Portal departments and they have not been able to resolve this issue yet.

**Comment by SeniorConsulting** [comment]
Hi Th3Gl1th,

The first issue is that by moving to the latest version (2.x) of the PowerShell module, the cmdlet "Select-MgProfile" no longer exists. More information about that can be found here.

I'll edit this shortly after I've looked into the Update-MgGroup

**Comment by Th3Gl1tch** [comment]
Here is the output of Get-InstalledModule *Microsoft.Graph* I have installed


Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.3.0                Microsoft.Graph                     PSGallery            Microsoft Graph PowerShell module
2.3.0                Microsoft.Graph.Applications        PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Authentication      PSGallery            Microsoft Graph PowerShell Authentication…
2.3.0                Microsoft.Graph.Beta                PSGallery            Microsoft Graph PowerShell module
2.3.0                Microsoft.Graph.Beta.Applications   PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Bookings       PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Calendar       PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.ChangeNotific… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.CloudCommunic… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Compliance     PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.CrossDeviceEx… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.DeviceManagem… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.DeviceManagem… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.DeviceManagem… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.DeviceManagem… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.DeviceManagem… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Devices.Cloud… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Devices.Corpo… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Devices.Servi… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.DirectoryObje… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Education      PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Files          PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Financials     PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Groups         PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Identity.Dire… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Identity.Gove… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Identity.Part… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Identity.Sign… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Mail           PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.ManagedTenants PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Notes          PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.People         PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.PersonalConta… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Planner        PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Reports        PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.SchemaExtensi… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Search         PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Security       PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Sites          PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Teams          PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Users          PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Users.Actions  PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.Users.Functio… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Beta.WindowsUpdates PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Bookings            PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Calendar            PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.ChangeNotifications PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.CloudCommunications PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Compliance          PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.CrossDeviceExperie… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.DeviceManagement    PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.DeviceManagement.A… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.DeviceManagement.A… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.DeviceManagement.E… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.DeviceManagement.F… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Devices.CloudPrint  PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Devices.CorporateM… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Devices.ServiceAnn… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.DirectoryObjects    PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Education           PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Files               PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Groups              PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Identity.Directory… PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Identity.Governance PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Identity.Partner    PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Identity.SignIns    PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Mail                PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Notes               PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.People              PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.PersonalContacts    PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Planner             PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Reports             PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.SchemaExtensions    PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Search              PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Security            PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Sites               PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Teams               PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Users               PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Users.Actions       PSGallery            Microsoft Graph PowerShell Cmdlets
2.3.0                Microsoft.Graph.Users.Functions     PSGallery            Microsoft Graph PowerShell Cmdlets

**Comment by SeniorConsulting** [comment]
Great, it looks like you've got the beta modules installed. So remove line 6 from the script (Referencing Select-MgProfile), and on line 14, replace Update-MgGroup with Update-MgBetaGroup.

**Comment by Th3Gl1tch** [comment]
Thanks, Looks like those changes did the trick. 

New script used
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13876134/6e5225c9-8c36-43bc-baf9-0594828d2a8e)

The script ran without any errors and checked in Graph Explorer I can see the group now shows isEnabled=False

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13876134/50f5c2eb-d21a-4708-bf2c-cb4178d8e78b)


Thank you for your help and quick response on this issue.

**Comment by SeniorConsulting** [comment]
Awesome! No worries, and have a great day :)
