### ISSUE TITLE
Connect-MicrosoftGraph invalid CertificateThumbprint still connects 

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#226]
When calling the Connect-Graph cmdlet, if I pass in an invalid certificatethumbprint I am still able to connect and interact with the APIs.

For example, let's say that my certificate thumbprint is "22E75E5D37791759FE89ED48FF843BB5132B8E44". I am able to connect passing in "22E75E5D37791759FE89ED48FF843BB5132B8E44s" with an extra 's' at the end (which was a typo to begin with). Even if the certificate thumbprint is invalid it still let me connect. Is there internal logic in the connect-graph command that truncates the value down to 40 characters no matter what? In my opinion, it should fail to connect me if I do a typo in the certificate thumbprint even if the first 40 characters are valid. 
[AB#7404](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7404)

**Comment by peombwa** [comment]
@NikCharlebois Sorry for the late response on this. The truncation is done by .NET since the length of a thumbprint will always be 40 characters. This is because a thumbprint is dynamically calculated as a SHA-1 hash of a certificate's binary data, and a SHA-1 hash always has a length of 40.

**Comment by NikCharlebois** [comment]
Definitively not a high priority, but I could see this being a problem if by some reason a script is using an invalid thumbprint of 41 char length to connect to the Graph and then to some other workloads. Other modules will fail the thumbprint but not the graph, adding confusion to the experience in my opinion. 

My recommendation would be to add a check for length and throw a descriptive error if the length is anything other than 40 chararctes.
