### ISSUE TITLE
[BUG] Get-MgBookingBusiness -All returns only 500 results

### ISSUE THREAD

**Issue by ClassyGull** [microsoftgraph/msgraph-sdk-powershell#2274]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
> Get-MgBookingBusiness -All returns only 500 results, also tried -All:$true 

**To Reproduce**
1. Execute `Get-MgBookingBusiness` with `-All`
2. See error at `no error, but only returns 500 objects`

**Expected behavior**
> All Booking Businesses should be returned.

**Debug Output**
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.
DEBUG: [Authentication]: - Scopes: [Application.Read.All, Application.ReadWrite.All, AuditLog.Read.All, Bookings.Manage.All, Chat.Create, Chat.Read, Chat.ReadBasic, Chat.ReadWrite, ChatMessage.Read, ChatMessage.Send, CrossTenantInformation.ReadBasic.All, DelegatedPermissionGrant.ReadWrite.All, DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All,
DeviceManagementManagedDevices.Read.All, DeviceManagementManagedDevices.ReadWrite.All, DeviceManagementServiceConfig.Read.All, DeviceManagementServiceConfig.ReadWrite.All, Directory.AccessAsUser.All, Directory.Read.All, Directory.ReadWrite.All, Group.Read.All, openid, profile, RoleEligibilitySchedule.Read.Directory, RoleEligibilitySchedule.ReadWrite.Directory,
RoleManagement.Read.All, RoleManagement.Read.Directory, RoleManagement.ReadWrite.Directory, Sites.Read.All, User.Read, User.Read.All, User.ReadBasic.All, User.ReadWrite.All, UserAuthenticationMethod.ReadWrite.All, email].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/solutions/bookingBusinesses

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.20348; en-US),PowerShell/5.1.20348.1850
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell/2.4.0
client-request-id             : 86a32778-f750-434e-ba91-1e3e1a82927f

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : da7dbe4f-356f-47f4-b732-cfff123991da
client-request-id             : 86a32778-f750-434e-ba91-1e3e1a82927f
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"West US 2","Slice":"E","Ring":"1","ScaleUnit":"004","RoleInstance":"MW2PEPF0000E01A"}}
OData-Version                 : 4.0
Cache-Control                 : no-cache
Date                          : Thu, 31 Aug 2023 22:22:18 GMT

**Module Version**
2.4.0

**Environment Data**
Name                           Value
----                           -----
PSVersion                      5.1.20348.1850
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.1850
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by SeniorConsulting** [comment]
Hi ClassyGull,

The restriction here isn't on the PowerShell SDK, it's actually on the Graph API itself. You can find out more from here:
https://learn.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-1.0&tabs=http

I'm referring specifically to:

> Note: Results are limited to 500 mailboxes. Pagination of the results is not currently supported.

Please open an API feature request at https://developer.microsoft.com/graph/support if you'd like to see more than 500 results returned.

**Comment by ClassyGull** [comment]
Can you confirm if this limitation should apply when using -Filter parameter. For example:

Get-MgBookingBusiness -Filter "startswith(id,'SomeText')"

only returns partial results.

**Comment by peombwa** [comment]
@ClassyGull, yes, the limitation applies to all GET calls to the API, `-Filter` (`$filter`) included.

Please open a feature request at https://developer.microsoft.com/graph/support as suggested above.

**Comment by peombwa** [comment]
Closing as limited by service as documented at https://learn.microsoft.com/graph/api/bookingbusiness-list.

**Comment by ClassyGull** [comment]
https://feedbackportal.microsoft.com/feedback/idea/2854c076-084c-ee11-a81c-0022484eccc5
