### ISSUE TITLE
Question: Where is IMicrosoftGraphAttachment declartion?

### ISSUE THREAD

**Issue by soroshsabz** [microsoftgraph/msgraph-sdk-powershell#228]
ITNOA

Hi

I want to see IMicrosoftGraphAttachment deflation. but I couldn't find anything, where is declaration?

Another question is in [GetAttachment API](https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=csharp) we can see `FileAttachment` type as return type, but I couldn't find anything about this type in powershell sdk.

Where is this type? and how to download attachment file?

thanks

**Comment by soroshsabz** [comment]
related to #182

**Comment by MIchaelMainer** [comment]
Duplicate

**Comment by soroshsabz** [comment]
@MIchaelMainer duplicate with which issue?

I have just question

**Comment by MIchaelMainer** [comment]
You won't be able to download file attachments until we provide support for non-json responses.

**Comment by soroshsabz** [comment]
Thanks for answer 😊

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by soroshsabz** [comment]
@MIchaelMainer As I can see in version 1.1 stream support has been improvement, so Did you can say me to how can I download email attachement?

thanks
