### ISSUE TITLE
All documents link does not work

### ISSUE THREAD

**Issue by soroshsabz** [microsoftgraph/msgraph-sdk-powershell#229]
ITNOA

If I select any of doc link, I redirect to Microsoft site, and Microsoft says link does not found

for example in [Get-MgUserMessageAttachment.md](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/82f8d340febe1ed9cf17788c22c178dfad61fc56/src/Beta/Users.Mail/Users.Mail/docs/Get-MgUserMessageAttachment.md) if you click to link you can see this error.

thanks

**Comment by MIchaelMainer** [comment]
This is a known issue. Close as duplicate. #61
