### ISSUE TITLE
New-MgUserCalendarPermission/New-MgBetaUserCalendarPermission 400 : Bad, Bad 👎 Request 

### ISSUE THREAD

**Issue by Fefke** [microsoftgraph/msgraph-sdk-powershell#2296]
**Describe the bug**
> Running the Beta command returns an HTTP 400 Bad Request response
> Running the 1.0 command produces a generic failure message.

**To Reproduce**
Just run the command according to the documentation,
I tried it on my dev-tenant, as well as on two different productive systems (with test-users :)
yet it's always the same
`New-MgBetaUserCalendarPermission -UserID <User-ID> -EmailAddress @{ "name" = "<Benutzername>"; "address" = "<E-Mail-Adresse>" } -AllowedRoles @("read")`

**Expected behavior**
> Add a new calendar Permission for the user passed in the map

**Debug Output**
> DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command
 Line Tools'.

DEBUG: [Authentication]: - Scopes: [Calendars.Read.Shared, Calendars.ReadWrite, Calendars.ReadWrite.Shared, openid, profile, User.Read.All, email].

Ausführen des Vorgangs "New-MgUserCalendarPermission_CreateExpanded" für das Ziel "Call remote 'POST /users/{user-id}/calendar/calendarPermissions'
operation".

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.microsoft.com/v1.0/users/{user-id}/calendar/calendarPermissions

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.22621; de-DE),PowerShell/5.1.22621.1778
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell/2.4.0
client-request-id             : -trivial-

Body:
{
  "allowedRoles": [
    "read"
  ],
  "emailAddress": {
    "address": "different.user@example.com",
    "name": "different..user"
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : -trivial-
client-request-id             : -trivial-
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Germany West
Central","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"-trivial-"}}
Cache-Control                 : private
Date                          : -trivial-

Body:
{
  "error": {
    "code": "ErrorNotSupported",
    "message": "Specified method is not supported."
  }
}

Specified method is not supported.

Status: 400 (BadRequest)
ErrorCode: ErrorNotSupported
Date:

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : -trivial-
client-request-id             : -trivial-
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Germany West
Central","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"-trivial-"}}
Cache-Control                 : private
Date                          : -trivial-

New-MgUserCalendarPermission : Specified method is not supported.
Status: 400 (BadRequest)
ErrorCode: ErrorNotSupported
Date:
Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : -trivial-
client-request-id             : -trivial-
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Germany West
Central","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"-trivial-"}}
Cache-Control                 : private
Date                          : -trivial-
In Zeile:1 Zeichen:1
+ New-MgUserCalendarPermission -UserId {userid} ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = XXXX...darPermission }:<>f__AnonymousType59`2) [New-MgUserCalen..._CreateExpanded], Exception
    + FullyQualifiedErrorId : ErrorNotSupported,Microsoft.Graph.PowerShell.Cmdlets.NewMgUserCalendarPermission_CreateExpanded
DEBUG: [CmdletEndProcessing]: - New-MgUserCalendarPermission end processing.

**Module Version**
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.4.0      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext...}
Script     2.5.0      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext...}
Script     2.5.0      Microsoft.Graph.Beta.Calendar       {Get-MgBetaGroupCalendar, Get-MgBetaGroupCalendarEvent, Get-MgBetaGroupCalendarPermission, Get...
Script     2.4.0      Microsoft.Graph.Calendar            {Get-MgGroupCalendar, Get-MgGroupCalendarEvent, Get-MgGroupCalendarPermission, Get-MgGroupCale...
Script     2.4.0      Microsoft.Graph.Users               {Get-MgUser, Get-MgUserCount, Get-MgUserCreatedObject, Get-MgUserCreatedObjectAsServicePrincip...

**Environment Data**
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional context**
I also tried it via the MS Graph API Explorer and it's the same error.
So possibly it's a Graph API problem. I hope you can redirect it accordingly.

**Comment by SeniorConsulting** [comment]
Hi Fefke

There are a couple of things with this cmdlet:
1) You can only add the permissions to the calendar if you're the calendar owner. Trying to add permissions to a calendar you're not the owner of returns a 403 forbidden response

> List, create, get, update, and delete of calendar permissions is supported on behalf of only the calendar owner.

https://learn.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0

2) Try using the parameter -Role instread of -AllowedRoles
e.g. New-MgBetaUserCalendarPermission -UserID <User-ID> -EmailAddress @{ "name" = "<Benutzername>"; "address" = "<E-Mail-Address>" } -Roles "read"

I got it going using that combination.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/4f33e1b7-3bfd-4f52-a949-ac4960eaabb4)
