### ISSUE TITLE
MS Graph/PowerShell error 'The computer must be trusted for delegation and the current user account must be configured to allow delegation'

### ISSUE THREAD

**Issue by jorode25** [microsoftgraph/msgraph-sdk-powershell#2298]
A user is trying to run the cmdlet Connect-MgGraph in domain joined device(regular forest) using a red forest account.

The account from the red forest is configured with shadow principle

Connect-MgGraph -Scopes "Application.ReadWrite.All", "Directory.ReadWrite.All", "Group.ReadWrite.All", "User.ReadWrite.All", "UserAuthenticationMethod.ReadWrite.All" 

However, he is getting the below error message:

Connect-MgGraph : The requested operation cannot be completed. The computer must be trusted for delegation and the current user account must be configured to allow delegation.

• If the user signs-in to the server with local domain credentials from that Active Directory(regular forest), this problem does not happen.
• If user runs PowerShell from a workstation that is Azure AD Joined, it works fine.
• If the user signs-in to a domain joined device(from the regular forest) using his trusted red forest Domain credentials the issue happens.

The flow is the below:

• Customer login into the domain joined device using the shadow principal account(credentials from red forest).
• Open PowerShell.
• Run the command Connect-MgGraph and hit enter.
• Open a pop-up with the list of cloud accounts (tenant accounts in this case). Customer selects the azure cloud account.
• Type password and do MFA.
• After that, into PowerShell should show a message “Welcome to Microsoft graph”, however, it is showing the error: The requested operation cannot be completed. The computer must be trusted for delegation and the current user account must be configured to allow delegation.

From Procmon:

9:59:14.9625499 PM	powershell.exe	5024	CreateFile	C:\Windows\System32\wbem	SUCCESS	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened	Windows PowerShell	"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" 
9:59:14.9625658 PM	powershell.exe	5024	QueryDirectory	C:\Windows\System32\wbem\Connect-MgGraph.*	NO SUCH FILE	FileInformationClass: FileBothDirectoryInformation, Filter: Connect-MgGraph.*	Windows PowerShell	"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"

**Comment by timayabi2020** [comment]
Hi @jodelgad
From your explanation it seems like the accounts have been trusted for delegation but the domain joined device has not.
Please checkout this article https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/enable-computer-and-user-accounts-to-be-trusted-for-delegation, It may give insight on why you are having that experience.
