### ISSUE TITLE
Unsupported MailNickName Parameter on New-MgTeam documentation

### ISSUE THREAD

**Issue by timayabi2020** [microsoftgraph/msgraph-sdk-powershell#2301]
**Describe the bug**
> Both online and offline documentation for ``New-MgTeam`` show that MailNickName is a required parameter. Based on the Graph API [documentation]( https://learn.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0#properties), the parameter is not available and thus should not be documented.

**To Reproduce**
1. Execute `Get-Help New-MgTeam -Online`
2. See error below

<img width="823" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/256e526c-1b85-47c1-9c1b-2f7c347f6daa">

**Comment by peombwa** [comment]
This should be closed since `MailNickname` is not listed anywhere as parameter of `New-MgTeam` in the cmdlet reference doc:
``` pwsh
New-MgTeam
   [-AdditionalProperties <Hashtable>]
   [-AllChannels <IMicrosoftGraphChannel[]>]
   [-Channels <IMicrosoftGraphChannel[]>]
   [-Classification <String>]
   [-CreatedDateTime <DateTime>]
   [-Description <String>]
   [-DisplayName <String>]
   [-FunSettings <IMicrosoftGraphTeamFunSettings>]
   [-Group <IMicrosoftGraphGroup>]
   [-GuestSettings <IMicrosoftGraphTeamGuestSettings>]
   [-Id <String>]
   [-IncomingChannels <IMicrosoftGraphChannel[]>]
   [-InstalledApps <IMicrosoftGraphTeamsAppInstallation[]>]
   [-InternalId <String>]
   [-IsArchived]
   [-MemberSettings <IMicrosoftGraphTeamMemberSettings>]
   [-Members <IMicrosoftGraphConversationMember[]>]
   [-MessagingSettings <IMicrosoftGraphTeamMessagingSettings>]
   [-Operations <IMicrosoftGraphTeamsAsyncOperation[]>]
   [-PermissionGrants <IMicrosoftGraphResourceSpecificPermissionGrant[]>]
   [-Photo <IMicrosoftGraphProfilePhoto>]
   [-PrimaryChannel <IMicrosoftGraphChannel>]
   [-Schedule <IMicrosoftGraphSchedule>]
   [-Specialization <String>]
   [-Summary <IMicrosoftGraphTeamSummary>]
   [-Tags <IMicrosoftGraphTeamworkTag[]>]
   [-Template <Hashtable>]
   [-TenantId <String>]
   [-Visibility <String>]
   [-WebUrl <String>]
   [-WhatIf]
   [-Confirm]
   [<CommonParameters>]
```

The `MailNickname` in the above screenshot is a member of `AllChannels.FilesFolder.CreatedByUser` type (`User`) - https://learn.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0#relationships. This is due to how the code generator flattens the `team` members under the notes section of the help file.
