### ISSUE TITLE
Reading Sharepoint List Item Values with Powershell gives me a value factor 10 (60 instead of 6)

### ISSUE THREAD

**Issue by Kurt-Proviron** [microsoftgraph/msgraph-sdk-powershell#2305]
I'm using Powershell & MS-Graph API to read some information from a Sharepoint List.
The Sharepoint List have a Field Object_Capacity (Type : Number (1, 1.0, 100)) where I enter a value.
In the Sharepoint List I see the Correct Value

When Requesting the Sharepoint List item with powershell Command (**Get-MgSiteListItem** -SiteId $ICTTeamId -ListId $ICTObjectListNameId -ExpandProperty 'fields' -All).Fields.AdditionalProperties.Object_Capacity) I get values 10 times bigger than shown in the sharepoint List.
Ex 6 => 60 , 100 =>1000

Using Get-PnPListItem gives me the correct value

Using MS Graph Explorer [https://graph.microsoft.com/v1.0/sites/<SiteID>/lists/<ListID>/items/<ItemID>] gives me the correct value

Anyone any Idea how to fix this ?

Regards

Kurt

**Comment by SeniorConsulting** [comment]
Hi Kurt-Proviron,

I haven't been able to replicate this unfortunately. I've set up something similar in my lab
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/d5a2f171-762e-4e1b-b016-5d271784b8e1)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/33f4cabe-aeee-4b9c-bbad-3bbfea977aec)

Do you have any more information you could provide? PS versions, Graph SDK module versions etc? Or any other information you might be able to provide to allow me to replicate this?

**Comment by Kurt-Proviron** [comment]
Hi,
I Have done a test on an other tenant and have the same Issue.
Create a Sharepoint List in a site, with a Field OBJ-Capacity as **Value**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/102505992/8f5b97ca-9f6c-40d5-ad40-53bd835c3f33)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/102505992/83799274-254c-45c2-b663-381b556365da)
Then with the Powershell command Get-MGSiteListItem requesting the Value, I'll got values back as 100 & 50
Tried with Powershell versions 7.2.13 & 7.3.6
Tried with MSGraph Version 1.28.0 - 2.0.0 - 2.5.0
Always it give me the value, 10 times bigger.

**Comment by SeniorConsulting** [comment]
Thanks for the additional detail. I wasn't able to replicate this in PS 7.3.6 either :(

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/6ef3b6a7-3fc8-4a60-9948-dee583365025)


![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/37fdde2c-3981-4541-adab-b18d4e038cb6)


Could you please run the following command and report the output?
`Get-MgSiteListItem -SiteId $ICTTeamId -ListId $ICTObjectListNameId -ExpandProperty 'fields' -All -debug`

You may need to remove any identifying/personal information from the result, but I'm interested in whether the issue is on the PowerShell side, or on the Graph API side - I can see you've said that you get the correct result from Graph Explorer.

What I'm mainly interseted in is the response from Graph:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/3db66c21-ad3e-4e99-82c3-df504f7cf54a)

**Comment by Kurt-Proviron** [comment]
Getting the correct value, it is the powershell command that makes the error.
"Object_x0020_Capacity": **7.0**,

    {
      "@odata.etag": "\"36d3fe8f-aeae-4d7e-8cbd-a3a425b1186a,11\"",
      "createdDateTime": "2023-09-05T14:30:43Z",
      "eTag": "\"36d3fe8f-aeae-4d7e-8cbd-a3a425b1186a,11\"",
      "id": "2270",
      "lastModifiedDateTime": "2023-09-20T08:13:12Z",
      "webUrl": "https://xxxxx.sharepoint.com/sites/xxxxx/Lists/ICT%20Objects/2270_.000",
      "createdBy": {
        "user": {
          "displayName": "SharePoint App"
        }
      },
      "lastModifiedBy": {
        "user": {
          "email": "kurt.xxxxx@xxxxx.com",
          "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "displayName": "Kurtxxxxxxx"
        }
      },
      "parentReference": {
        "id": "xxxxxxxxxx",
        "siteId": "xxxxxxx.sharepoint.com,xxxxx,xxxxx"
      },
      "contentType": {
        "id": "xxxxxxxxxxx",
        "name": "OBJ_Rooms"
      },
      "fields@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites('xxxx')/lists('xxxxxx')/items('2270')/fields/$entity",
      "fields": {
        "@odata.etag": "\"36d3fe8f-aeae-4d7e-8cbd-a3a425b1186a,11\"",
        "Title": "Nikkel (Ni)",
        "id": "2270",
        "ContentType": "OBJ_Rooms",
        "Modified": "2023-09-20T08:13:12Z",
        "Created": "2023-09-05T14:30:43Z",
        "AuthorLookupId": "xxxx",
        "EditorLookupId": "xxx",
        "_UIVersionString": "11.0",
        "Attachments": false,
        "Edit": "",
        "LinkTitleNoMenu": "Nikkel (Ni)",
        "LinkTitle": "Nikkel (Ni)",
        "ItemChildCount": "0",
        "FolderChildCount": "0",
        "_ComplianceFlags": "0",
        "_ComplianceTag": "",
        "_ComplianceTagWrittenTime": "",
        "_ComplianceTagUserId": "",
        "AppAuthorLookupId": "70",
        "Object_x0020_Type10": "ROOM",
        "Object_x0020_Status": "Finished",
        "Object_x0020_Display_x0020_Name": "Nikkel (Ni)",
        "Object_x0020_Default_x0020_SMTP": "MR-Nikkel@xxxxxxx.com",
        "Object_x0020_ID": "xxxxxxxx",
        **"Object_x0020_Capacity": 7.0,**
        "_IsRecord": "0"
      }
    },

**Comment by Kurt-Proviron** [comment]
Last night did some extra tests, because that 7.0 was intrigued by me.
It look to a Regional setting Issue.
On my computers the regional setting is:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/102505992/bb9b957b-2ac4-49b2-9dfc-dcaddb6329e1)
I changed it to this:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/102505992/cf62bd44-f192-4436-aec0-e253b344f67f)
Now I'm getting the correct values.

In the sharepoint list, when changing the value into 5.6 (dot) it gives me 56 in the Browser
Entering 5,6 comma) gives me 5,6 in the Browser.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/102505992/58322320-8977-4879-bcf3-520105c52701)
Requesting the values with the Get-MgSiteListItem command gives me each time a value 10 times bigger.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/102505992/e46b90a6-f4fb-4619-81a1-583557f0495a)

Conclusing, Issue is caused by Regional setting of the computer running the script.

Regards
Kurt

**Comment by SeniorConsulting** [comment]
Hmm, @ddyett, I wouldn't close this as complete. While the bug cause has been identified, I don't think that asking users worldwide to change their regional settings to US or another English related one just so that the PowerShell SDK will work is a recommended solution.

I had not responded after Kurt's previous response as I was going to leave this to the dev team to investigate further.
