### ISSUE TITLE
'find-MgGraphCommand -Uri ' not working for /me endpoints

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-sdk-powershell#2306]
**Describe the bug**
There is a customer [complaint ]( https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/50)that they cannot find the permissions for a /me endpoint using find-MgGraphCommand -Uri. On testing, the /me endpoints are currently not working.

**To Reproduce**
1. Run find-MgGraphCommand -Uri '/me/events' or find-MgGraphCommand -Uri '/me/mailboxSettings'
2. Error thrown is
find-MgGraphCommand : URI ' https://graph.microsoft.com/v1.0/me/mailboxSettings' in  is not valid or is not currently supported by
the SDK. Ensure the URI is formatted correctly and try again.
3. Using find-MgGraphCommand -command Get-MgUserMailboxSetting works

**Expected behavior**
expected to return the command, URI and permissions

**Debug Output**
find-MgGraphCommand : URI ' https://graph.microsoft.com/v1.0/me/events' in  is not valid or is not currently supported by the SDK.
Ensure the URI is formatted correctly and try again.
At line:1 char:1
+ find-MgGraphCommand -Uri '/me/events' -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Find-MgGraphCommand

**Comment by ddyett** [comment]
should we expand me to users/user-id in these cases.  find-MgGraphCommand -Uri '/users/{id}/events/'

**Comment by CarolKigoonya** [comment]
Yes we should
