### ISSUE TITLE
New-MgUserLicenseDetail 'Unsupported resource type 'LicenseDetail' for operation 'Create'.'

### ISSUE THREAD

**Issue by ThePoShWolf** [microsoftgraph/msgraph-sdk-powershell#231]
When using the ```New-MgUserLicenseDetail``` cmdlet, the Graph API says:

```text
Unsupported resource type 'LicenseDetail' for operation 'Create'.
```

I've tried several different valid and invalid license details, all with the same result. My intent was to assign licenses, but research showed me that this won't work because it doesn't call the [assignLicense](https://docs.microsoft.com/en-us/graph/api/resources/assignedlicense?view=graph-rest-1.0) endpoint.

Is there another way to assign licenses using this module? Or is that not supported yet? 
[AB#7405](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7405)

**Comment by ThePoShWolf** [comment]
Ha, ok, if anyone else comes across this, the correct cmdlet to use is:

```powershell
Set-MgUserLicense
```

That is because the help for that command literally says:

```text
Invoke action assignLicense
```

I'll throw up a blog post or something to help out other folks that run into this issue.

**Comment by MIchaelMainer** [comment]
We shouldn't be generating a command for a new user license detail. This should be restricted via capability annotations. 

We will use this issue to track capability annotations.

**Comment by peombwa** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/458.

**Comment by peombwa** [comment]
Clean up done in #670
