### ISSUE TITLE
Any MG powershell cmdlet is prompting to pick an account if I have to connect to 2 different tenants and their IDs are cached.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#2316]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
[Any MG powershell cmdlet is prompting for selecting an account if I have to connect to 2 different tenants and their accounts are cached.
For each Cmdlet it is prompting to pick the account I like to use.
For example:

Below cmdlet prompts me to pick an account.
Get-MgUser -userid [mxxxx@microsoft.com](mailto:mxxxx@microsoft.com)
In the same session, If I run the same cmdlet, it prompts again to pick an account.
Get-MgUser -userid [mxxxx@microsoft.com](mailto:mxxxx@microsoft.com)
How can I specify the account in connect-mggraph like we can do in connect-azuread -accountid?
How can we automate tasks if it keeps prompting for every mggraph cmdlet?

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/73849846/bb327c74-c2f7-4906-a746-bdd4ab0bf0cc)

Driving me crazy..

]
**To Reproduce**
1. Execute `-Mg-` with `...`
2. See error at `...`

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.
> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by msewaweru** [comment]
Transferred from the docs repo: https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/379.

**Comment by SeniorConsulting** [comment]
My recommendation here is twofold:
1. Clear out the existing token cache following the instructions here:
https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues

> Customers upgrading from previous versions of the SDK may encounter auth prompts on every command call. If this happens, one can use the following steps to reset their token cache:
> 
> Use Disconnect-MgGraph to sign out of the current session.
> Run Remove-Item "$env:USERPROFILE\.mg" -Recurse -Force to delete your token cache.
> Run Connect-MgGraph to reconstruct a clean token cache.

2. When connecting to multiple tenants when using the same instance of PowerShell, considering using:
`Connect-MgGraph -ContextScope Process`
It may lead to less occurences of this issue.

**Comment by timayabi2020** [comment]
@msewaweru please refer to [this article](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-connect-mggraph) for connecting to a different identity other than the current user using the ``-ContextScope`` parameter
