### ISSUE TITLE
Not able to export 'teamsAppDefinition' data using Get-MgUserTeamworkInstalledApp cmdlet

### ISSUE THREAD

**Issue by rtrazvan** [microsoftgraph/msgraph-sdk-powershell#2319]
Hi,

I'm trying to export all Teams apps installed by users using MS Graph PowerShell cmdlet Get-MgUserTeamworkInstalledApp but I encounter some issue.

Basically I cannot export TeamsAppDefinition. It looks like this when executing the cmdlet:
TeamsAppDefinition     : Microsoft.Graph.PowerShell.Models.MicrosoftGraphTeamsAppDefinition

Cmdlet used:
Get-MgUserTeamworkInstalledApp -UserId $userId -ExpandProperty "teamsAppDefinition"

I used both 'Apponly' and 'Deletege' auth but the issues is the same.

When using MS Graph explorer no issue occurs.

Any ideas?
Thank you.

**Comment by timayabi2020** [comment]
@rtrazvan thank you for bringing this issue to our attention. Kindly confirm both the PowerShell and sdk version you are using to execute the command.
For PowerShell version use: ```$PSVersionTable```
For SDK version use : ```Get-Module -Name Microsoft.Graph -ListAvailable | Select Version```

**Comment by rtrazvan** [comment]
Hi @timayabi2020,
PowerShell version: 5.1
SDK version: 2.6.1

**Comment by timayabi2020** [comment]
Thank you. Kindly do the following.

1. Confirm the scopes you used to authenticate against graph i.e., ```Connect-MgGraph -Scopes <Your scopes>```. To view the scopes required for that command, you can run ``Find-MgGraphCommand -Command Get-MgUserTeamworkInstalledApp | Select-Object Permissions``
2. The output from running that command with a -Debug parameter. i.e., ```Get-MgUserTeamworkInstalledApp -UserId $userId -ExpandProperty "teamsAppDefinition" -Debug```. You can attach the screenshot here.

**Comment by rtrazvan** [comment]
1. The scopes used are:
Scopes: {TeamsAppInstallation.ReadForUser.All, TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWriteForUser.All}

2. When running -Debug parameter I see the data under "teamsAppDefinition", but the output contains only the highlighted ID:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/145687067/f7cc9a8f-fcf4-4516-800d-171980d06bef)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/145687067/a69d11fe-06db-413e-bec3-5617748a58ce)

**Comment by timayabi2020** [comment]
@rtrazvan For a work around, please use ``Get-MgUserTeamworkInstalledApp -UserId $UserId | ConvertTo-Json`` so that you can be able to grab contents of the "TeamsAppDefinition" property".
You'll get something similar to the screenshot below.
<img width="810" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/d9eb0f12-6e11-4f6d-9c8e-37579b37c326">

**Comment by rtrazvan** [comment]
@timayabi2020
Unfortunately ConvertTo-Json does not help because the values are 'null'.
But I found a way to get the data using:
Get-MgUserTeamworkInstalledApp -UserId $UserID -ExpandProperty TeamsAppDefinition | select -ExpandProperty TeamsAppDefinition | select DisplayName,PublishingState,ShortDescription,Description,TeamsAppId,Version

**Comment by timayabi2020** [comment]
@rtrazvan nice. So, there was another child navigation property with the same name as the parent "TeamsAppDefinition" navigation property.
