### ISSUE TITLE
MgDeviceRegisteredOwnerByRef gives Insufficient privileges for Global Admin

### ISSUE THREAD

**Issue by KentNordstrom** [microsoftgraph/msgraph-sdk-powershell#2320]
In the process of removing dependency of AzureAD powershell module and replace with Microsoft.Graph.

Calling Remove-MgDeviceRegisteredOwnerByRef or New-MgDeviceRegisteredOwnerByRef gives the error "Insufficient privileges to complete the operation." despite the fact that the call is made using a user with Global Admin role and the Scope defined is Directory.ReadWrite.All

The same identity can successfully call the old Add-AzureADDeviceRegisteredOwner command.

**To Reproduce**
Connect-MgGraph -TenantId $TenantId -Scopes Directory.ReadWrite.All
Get-MgDeviceRegisteredOwner -DeviceId $Device.Id
Remove-MgDeviceRegisteredOwnerByRef -DeviceId $Device.Id -DirectoryObjectId $User.Id
-- Gives error "Remove-MgDeviceRegisteredOwnerByRef_Delete1: Insufficient privileges to complete the operation."

Calling New-MgDeviceRegisteredOwnerByRef -DeviceId $Device.Id -OdataId $OdataId gives the same response.

**Expected behavior**
User is removed or added as owner of the device.

**Debug Output**
Remove-MgDeviceRegisteredOwnerByRef -DeviceId $Device.Id -DirectoryObjectId $User.Id -Debug
DEBUG: [CmdletBeginProcessing]: - Remove-MgDeviceRegisteredOwnerByRef begin processing with parameterSet 'Delete1'.
DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.
DEBUG: [Authentication]: - Scopes: [Directory.Read.All, Directory.ReadWrite.All, openid, profile, User.Read, email].

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
DELETE

Absolute Uri:
https://graph.microsoft.com/v1.0/devices/f4c8caa3-ad8f-4617-9bd9-e6e09e8ef07e/registeredOwners/f6cc6bb4-fd90-4e5a-98cf-0577f1ea11b3/$ref

Headers:
FeatureFlag                   : 00000047
Cache-Control                 : no-store, no-cache
SdkVersion                    : graph-powershell/1.27.0,Graph-dotnet-1.25.1
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.22621; en-SE),PowerShell/7.3.7
Accept-Encoding               : gzip

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Cache-Control                 : no-cache
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : c11dd5a0-6215-4507-b643-ed9388f6b9bf
client-request-id             : c11dd5a0-6215-4507-b643-ed9388f6b9bf
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Sweden Central","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"GVX0EPF00004C06"}}
x-ms-resource-unit            : 1
Date                          : Sun, 24 Sep 2023 07:53:22 GMT

Body:
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "date": "2023-09-24T07:53:22",
      "request-id": "c11dd5a0-6215-4507-b643-ed9388f6b9bf",
      "client-request-id": "c11dd5a0-6215-4507-b643-ed9388f6b9bf"
    }
  }
}

**Module Version**
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   1.27.0                Microsoft.Graph                     

**Environment Data**
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Screenshots**
Image showing that the used Scopes are indeed also granted in Entra ID.
<img width="1568" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/12670764/e7f11a09-54fc-47f2-981b-8d4a6cf9becc">

**Additional context**
The Identity I use to perform this is a B2B/Guest account in the target Tenant, but since most other Microsoft.Graph operations work as expected I don't think that's relevant.

**Comment by SeniorConsulting** [comment]
Hi KentNordstrom,

When I ran
`(Find-MgGraphCommand Remove-MgDeviceRegisteredOwnerByRef |Select -First 1).Permissions`

or 

`(Find-MgGraphCommand New-MgDeviceRegisteredOwnerByRef |Select -First 1).Permissions`

It says that the permissions required are Directory.AccessAsUser.All, rather than what you've been using (Directory.ReadWrite.All).

Just be very careful using that cmdlet, as it sounds like it may delete the user from Azure AD/Entra ID if you're using the remove version.
https://learn.microsoft.com/en-us/graph/api/device-delete-registeredowners?view=graph-rest-1.0&tabs=powershell

Please also note that there are _**no**_ application permissions for this cmdlet, in fact you can only use a delegated work or school account.

**Comment by KentNordstrom** [comment]
@SeniorConsulting Thanks for pointing out the .Permissions , never thought different commands around the same type of entity could use different Scopes.. in this case all other MgDevice management is working with Directory.ReadWrite.

I will keep this in mind and remember to check what odd permissions a specific command might require.

As feedback to the developers of this module (and others) I think it would be good if permissions errors like this showed the required permissions in the error message.

As for the warning about the Remove- command it should be safe to use since it makes the correct call with the /$ref in the end ,as we can see in the Debug output in my original post, making sure the object is not deleted just the reference.

**Comment by KentNordstrom** [comment]
Closing this issue since it showed to be by design. Maybe a new change request can be made to make the work with Directory.ReadWrite like all other MgDevice calls.
