### ISSUE TITLE
Access Denied when using Get-MgUserDefaultDrive, despite using delegated administrator permissions.

### ISSUE THREAD

**Issue by mkennedy-mqual** [microsoftgraph/msgraph-sdk-powershell#2338]
**Describe the bug**
Using an Azure Admin account, I still get 403 Access Denied when trying to use `Get-MgUserDefaultDrive`. I am able to access the users OneDrive using Office Admin center with the same credentials being used here. 

**To Reproduce**
```
$User = Get-MgUser -Filter "displayname eq '$Username'"
$UsersOneDrive = Get-MgUserDefaultDrive -UserId $User.Id
```
```
Get-MgUserDefaultDrive_Get: Access denied

Status: 403 (Forbidden)
ErrorCode: accessDenied
Date: 2023-10-03T17:50:42

Headers:
Cache-Control                 : no-store, no-cache
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : $REQUEST_GUID
client-request-id             : $RESPONSE_GUID
x-ms-ags-diagnostic           : $JSON_DIAGNOSTIC_INFO
Date                          : Tue, 03 Oct 2023 17:50:42 GMT
```

**Expected behavior**
I expect to be able to access a user's OneDrive, then move them to a SharePoint site. 

**Debug Output**
```
$UsersOneDrive = Get-MgUserDefaultDrive -UserId $User.Id -Debug
```
```
DEBUG: [CmdletBeginProcessing]: - Get-MgUserDefaultDrive begin processing with parameterSet 'Get'.
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.
DEBUG: [Authentication]: - Scopes: [Directory.Read.All, Files.ReadWrite, Files.ReadWrite.All, Group.Read.All, Mail.ReadWrite, openid, Organization.ReadWrite.All, People.Read.All, profile, Sites.FullControl.All, Sites.Manage.All, Sites.ReadWrite.All, User.Read, User.Read.All, User.ReadWrite, User.ReadWrite.All, UserAuthenticationMethod.ReadWrite.All, email].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/users/$ANOTHER_GUID/drive

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.19045; en-US),PowerShell/7.3.7
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell/2.6.1
client-request-id             : $CLIENT_REQUEST_GUID

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Cache-Control                 : no-store, no-cache
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : $REQUEST_GUID
client-request-id             : $CLIENT_REQUEST_GUID
x-ms-ags-diagnostic           : $JSON_DIAGNOSTIC_INFO
Date                          : Tue, 03 Oct 2023 17:52:24 GMT

Body:
{
  "error": {
    "code": "accessDenied",
    "message": "Access denied",
    "innerError": {
      "date": "2023-10-03T17:52:25",
      "request-id": "$REQUEST_GUID",
      "client-request-id": "$CLIENT_REQUEST_GUID"
    }
  }
}


Get-MgUserDefaultDrive_Get: Access denied

Status: 403 (Forbidden)
ErrorCode: accessDenied
Date: 2023-10-03T17:52:25

Headers:
Cache-Control                 : no-store, no-cache
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : $REQUEST_GUID
client-request-id             : $CLIENT_REQUEST_GUID
x-ms-ags-diagnostic           : $JSON_DIAGNOSTIC_INFO
Date                          : Tue, 03 Oct 2023 17:52:24 GMT

DEBUG: [CmdletEndProcessing]: - Get-MgUserDefaultDrive end processing.
```
**Module Version**
```
Get-Module Microsoft.Graph*
```
```
ModuleType Version    PreRelease Name                                ExportedCo
                                                                     mmands
---------- -------    ---------- ----                                ----------
Script     2.6.1                 Microsoft.Graph.Applications        {Add-MgAp…
Script     2.6.1                 Microsoft.Graph.Authentication      {Add-MgEn…
Script     2.6.1                 Microsoft.Graph.Files               {Add-MgDr…
Script     2.6.1                 Microsoft.Graph.Groups              {Add-MgGr…
Script     2.6.1                 Microsoft.Graph.Sites               {Add-MgSi…
Script     2.6.1                 Microsoft.Graph.Users               {Get-MgUs…
Script     2.6.1                 Microsoft.Graph.Users.Actions       {Add-MgUs…
```

**Environment Data**
```
$PSVersionTable
```
```
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Screenshots**
N/A

**Additional context**
N/A

**Pre-Bug Checklist**
[x] Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
[x] Please search the existing issues to see if there has been a similar issue filed.
[x] For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

EDIT: I forgot to include the loaded permissions, as it's an access denied / authn issue, here's what they are:
```
(Get-MgContext).Scopes
```
```
Directory.Read.All
Files.ReadWrite
Files.ReadWrite.All
Group.Read.All
Mail.ReadWrite
openid
Organization.ReadWrite.All
People.Read.All
profile
Sites.FullControl.All
Sites.Manage.All
Sites.ReadWrite.All
User.Read
User.Read.All
User.ReadWrite
User.ReadWrite.All
UserAuthenticationMethod.ReadWrite.All
email
```

**Comment by SeniorConsulting** [comment]
Hi mkennedy-mqual,

I can replicate your bug myself in the SDK
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/72227cf9-5110-49be-8bf7-f567d477411a)

However, I can also replicate the defect in Graph Explorer:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/3df855b0-0449-4884-a1e6-81d1eea362c6)

This suggests that the issue might be at the API end, and not the PowerShell SDK end.
I've done some other checks on the API documentation ([here](https://learn.microsoft.com/en-us/graph/api/drive-get?view=graph-rest-1.0&tabs=http)), and the permissions you have should be acceptable (delegated - Files.ReadWrite.All, Sites.ReadWrite.All. It also states that it's possible to do what you're trying to do under the "Get a user's OneDrive" section

As a side note, accessing my own drive succeeds. I'll see if I can find any other answers on this one.

**Comment by SeniorConsulting** [comment]
I've found a way (not programmatically so far, unfortunately) to get this to work. If you go to the M365 Admin centre (admin.microsoft.com) > Users > Active Users.

Find the user you're looking for, then select the OneDrive tab. From there, if you click the button below "Get access to files", the subsequent PowerShell query will work.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/1c32aea7-4f2e-4ea4-864b-7d509b1323f2)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/62e42b51-0d0e-4ddd-8156-223c640e75fe)

**Comment by timayabi2020** [comment]
@mkennedy-mqual I am only able to reproduce the issue if I don't have one of the required permissions. e.g. Files.ReadWrite.All.
<img width="635" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/49bde3cd-f3f4-4fc0-9cc6-78e07c3b24dc">
Maybe you can try out @SeniorConsulting's suggestion.

**Comment by mkennedy-mqual** [comment]
> @mkennedy-mqual I am only able to reproduce the issue if I don't have one of the required permissions. e.g. Files.ReadWrite.All. <img alt="image" width="635" src="https://user-images.githubusercontent.com/10947120/272509212-49bde3cd-f3f4-4fc0-9cc6-78e07c3b24dc.png"> Maybe you can try out @SeniorConsulting's suggestion.

I forgot to include the snippet showing my permissions. I've edited the issue to include it, but I believed I have the required permissions. Sites.ReadWrite.All & Files.ReadWrite.All.

**Comment by mkennedy-mqual** [comment]
I was able to get through to MS support and was provided with this suggestion: make admin user a SharePoint admin of the individual user's OneDrive via Set-SPOSite seen below:  

```
Import-Module Microsoft.Online.SharePoint.PowerShell 
Connect-SPOService -Url https://example-admin.sharepoint.com/
Set-SPOUser -Site https://lslog-my.sharepoint.com/personal/example_user_example_com -LoginName 
 sharepoint_administrator@example.com -IsSiteCollectionAdmin $true 
```

Where it failed before, now it succeeds: 
```
Get-MgUserDefaultDrive -UserId $User.Id 
PS C:\ > $UsersOneDrive

Name     Id                                                                 DriveType CreatedDateTime
----     --                                                                 --------- ---------------
OneDrive $DRIVE_ID business  $TIMESTAMP

```

This gets me past the authentication issue with Get-MgUserDefaultDrive, so I believe this ticket can be closed although it would be nice if the documentation that references this is included in the Microsoft Graph for SharePoint documentation, or maybe I missed it if someone happens to know and can provide a link to said documentation, I'd appreciate that.

Thanks for the quick response and the help.

**Comment by lrhazi** [comment]
I seem to be hitting the same issue... Is this still open case?

**Comment by worldsdream** [comment]
Same issue here. Needs to be reopened and looked into!

**Comment by mike240se** [comment]
still having issue in 2025, microsoft needs to fix this.  Unable to get size of onedrive via graph for users unless permissions are modified.

**Comment by alisalih1** [comment]
It looks like this issue is being ignored, for whatever reason. It is certainly still an issue with 2.26.0 Microsoft.Graph.Users
