### ISSUE TITLE
Restore-MgDirectoryDeletedItem missing in 2.7.0

### ISSUE THREAD

**Issue by cw433** [microsoftgraph/msgraph-sdk-powershell#2350]
The Command Restore-MgDirectoryDeletedItem is missing in 2.7.0. It was still available in 2.6.1 and is still mentioned in the Cmdlet map https://learn.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0 and has its own Reference Page: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/restore-mgdirectorydeleteditem?view=graph-powershell-1.0

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

The endpoint appears to have been accidentally removed by an upstream tool from the service description metadata that's used to generate the SDKs - https://github.com/microsoftgraph/msgraph-metadata/issues/449. We will unlist 2.7.0 until the service description metadata is fixed.

**Comment by peombwa** [comment]
Closing as fixed by [2.8.0 release](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.8.0).
