### ISSUE TITLE
PlannerTask AppliedCategories

### ISSUE THREAD

**Issue by mabster** [microsoftgraph/msgraph-sdk-powershell#237]
Hi gang,

Hope it's ok to ask a question in the form of an issue.

I've been playing with this module today and have been able to retrieve a list of tasks from a given Planner board using the `Get-MgPlannerTask` cmdlet. However, each task has an `AppliedCategories` property which is supposed to be a collection of the possible categories (labels) from the plan, yet I can't get that detail from the task.

The attribute reports itself to the console as `Microsoft.Graph.PowerShell.Models.MicrosoftGraphPlannerAppliedCategories`, and it has no meaningful properties of its own. I tried calling `ToJsonString()` on it but that just yields `{}` even for tasks that I know have labels applied.

What am I missing? Do I need to do something special in my original call to fetch the list of tasks?

Cheers,
Matt 
[AB#7407](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7407)

**Comment by peombwa** [comment]
Hi @mabster, `AppliedCategories` is an [OpenType](https://docs.microsoft.com/en-us/graph/api/resources/plannerappliedcategories?view=graph-rest-beta#properties) and it can be accessed via AdditionalProperties bag like this:

``` powershell
# A Hashtable of applied categories.
$PlanerTask.AppliedCategories.AdditionalProperties
# Get an indidual category
$PlanerTask.AppliedCategories.AdditionalProperties.category4
```
