### ISSUE TITLE
"Microsoft.Graph.Authentication being installed is not catalog signed" error

### ISSUE THREAD

**Issue by zrivkis** [microsoftgraph/msgraph-sdk-powershell#2378]
**Describe the bug**
When updating Microsoft.Graph modules receiving the following error:
Install-Package: The version '1.28.0' of the module 'Microsoft.Graph.Authentication' being installed is not catalog signed. Ensure that the version '1.28.0' of the module 'Microsoft.Graph.Authentication' has the catalog file 'Microsoft.Graph.Authentication.cat' and signed with the same publisher 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module 'Microsoft.Graph.Authentication' with version '2.8.0' under the directory ...\PowerShell\Modules\Microsoft.Graph.Authentication\2.8.0'. If you still want to install or update, use -SkipPublisherCheck parameter.

**To Reproduce**
Execute "Get-InstalledModule Microsoft.Graph.Financials | Update-Module"
Execute "Get-InstalledModule Microsoft.Graph.WindowsUpdates | Update-Module"
Execute "Get-InstalledModule Microsoft.Graph.ManagedTenants | Update-Module"

**Expected behavior**
Successful update to the module without errors or having to specify -SkipPublisherCheck parameter

**Debug Output**
DEBUG: 00:00:18.6137933 Catalog file 'Microsoft.Graph.Authentication.cat' is not found in the contents of the previously-installed module 'Microsoft.Graph.Authentication' with the same name.
DEBUG: 00:00:18.6146013 Using the previously-installed module 'Microsoft.Graph.Authentication' with version '2.8.0' under '...PowerShell\Modules\Microsoft.Graph.Authentication\2.8.0' for getting the publisher details.
DEBUG: 00:00:18.6151132 Using the '...PowerShell\Modules\Microsoft.Graph.Authentication\2.8.0\Microsoft.Graph.Authentication.psd1' file for getting the authenticode signature.
DEBUG: 00:00:18.7496098 For publisher validation, using the previously-installed module 'Microsoft.Graph.Authentication' with version '2.8.0' under '...PowerShell\Modules\Microsoft.Graph.Authentication\2.8.0' with publisher name 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' from root certificate authority 'CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US'. Is this module signed by Microsoft: 'True'.
VERBOSE: Catalog file 'Microsoft.Graph.Authentication.cat' is not found in the contents of the module 'Microsoft.Graph.Authentication' being installed.
DEBUG: 00:00:18.7510299 Using the 'Microsoft.Graph.Authentication.psd1' file for getting the authenticode signature.
DEBUG: 00:00:18.7558906 For publisher validation, current module 'Microsoft.Graph.Authentication' with version '1.28.0' with publisher name '' from root certificate authority ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, current module 'Microsoft.Graph.Authentication' with version '1.28.0' with publisher name '' from root certificate authority ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'Microsoft.Graph.Authentication' with version '2.8.0' under '...PowerShell\Modules\Microsoft.Graph.Authentication\2.8.0' with publisher name 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' from root certificate authority 'CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US'. Is this module signed by Microsoft: 'True'.
DEBUG: 00:00:18.7579358 Previously-installed module publisher: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
DEBUG: 00:00:18.7585333 Current module publisher:
DEBUG: 00:00:18.7590763 Is previously-installed module signed by Microsoft: True
DEBUG: 00:00:18.7595450 Is current module signed by Microsoft: False
Install-Package: The version '1.28.0' of the module 'Microsoft.Graph.Authentication' being installed is not catalog signed. Ensure that the version '1.28.0' of the
module 'Microsoft.Graph.Authentication' has the catalog file 'Microsoft.Graph.Authentication.cat' and signed with the same publisher 'CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module 'Microsoft.Graph.Authentication' with
version '2.8.0' under the directory '...PowerShell\Modules\Microsoft.Graph.Authentication\2.8.0'. If you still want
to install or update, use -SkipPublisherCheck parameter.

**Module Version**
$ Get-Module Microsoft.Graph*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.22.0                Microsoft.Graph.Applications        {Add-MgApplicationKey, Add-MgApplicationPassword, Add-MgServicePrincipalTokenSigningCertificate, Clear-MgApplicationVerifiedPublisher…}
Script     2.0.0                 Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext…}
Script     1.22.0                Microsoft.Graph.Authentication      {Find-MgGraphCommand, Find-MgGraphPermission}

**Environment Data**
Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Screenshots**
N\A

**Additional context**

**Comment by peombwa** [comment]
This is to be expected when installing a version that isn't signed:
- `'Microsoft.Graph.Authentication v1.28.0` was not signed.
- `'Microsoft.Graph.Authentication v2.8.0` (the latest version) is signed.

Please follow the upgrade instructions at when upgrading from v1.x to v2.x - https://github.com/microsoftgraph/msgraph-sdk-powershell/#1-installation:
> Run Install-Module with -AllowClobber and -Force parameters if you run into command name conflicts when upgrading to older versions of the module. This may be the case when upgrading from v1.x to v2.x:
>
> Install-Module Microsoft.Graph -AllowClobber -Force

**Comment by zrivkis** [comment]
I tried running the updates as recommended in the link, however, the issue still persists. Is this unique to the 3 modules specified? Thanks in advance.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/66017948/4e84cc9e-43e6-4066-bc8c-f053e15c71c4)

**Comment by peombwa** [comment]
The error is due to the module rename breaking change that's mentioned in the v2.x upgrade guide at https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/docs/upgrade-to-v2.md#profile-support. In v2.x, the modules are now divided based on the API version (v1.0 and beta). `Microsoft.Graph.Financials` is a beta only module that got renamed to `Microsoft.Graph.Beta.Financials` in v2.x. Attempts to update/install `Microsoft.Graph.Financials` (non-beta) will install the 1.x version thus the error.

To avoid the error, please install the complete v1.0 and/or beta (non-production use only) versions of the SDK by following the instructions at https://learn.microsoft.com/powershell/microsoftgraph/installation?view=graph-powershell-1.0#installation. Alternatively, you can individually install the beta modules via `Install-Module Microsoft.Graph.Beta.Financials -AllowClobber -Force`. See dependencies section of the modules at https://www.powershellgallery.com/packages/Microsoft.Graph/2.8.0 and https://www.powershellgallery.com/packages/Microsoft.Graph.Beta/2.8.0 for more details.

**Comment by zrivkis** [comment]
Thanks for the information and guidance.
