### ISSUE TITLE
Microsoft.Graph module import stuck "Module import in progress" Azure Automation

### ISSUE THREAD

**Issue by MatiasCloud2** [microsoftgraph/msgraph-sdk-powershell#2379]
**Describe the bug**
When adding Microsoft.Graph module to Azure Automation account, module import is stuck at "Module Import is in progress"
We have the issue in multiple azure tenants.
Also noticed that Microsoft.Graph.Files behaves similary to Microsoft.Graph. So it might be the reason for the "import loop"

**To Reproduce**
1. Add module from gallery in Azure Automation Account - Install dependent modules first if not yet installed
2. See Automation Account Modules page:
![image (10)](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/148042757/75d57396-ab8f-4d7a-b216-4d67f981b265)
2.1. Also can be checked via powershell. There ProvisioningState is ConnectionTypeImported for both Microsoft.Graph and Microsoft.Graph.Files

**Expected behavior**
Successfull module import

**Module Version**
2.8.0.

**Comment by peombwa** [comment]
Please open a question/ticket with the Azure Automation support team for them to investigate why the moule is stuck on import. We don't control how Azure Automation imports the module.

From previous issues, I would the import to fail with a known max function capacity exceeded as described at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1449. The workaround in this case is to use PowerShell 7.

**Comment by peombwa** [comment]
Closing as external to the SDK. Please open a ticket with the Azure Automation support team.
