### ISSUE TITLE
Site Url null when executing Get-MgReportSharePointSiteUsageDetail

### ISSUE THREAD

**Issue by OlivierWaterloos** [microsoftgraph/msgraph-sdk-powershell#2382]
Hello,
When I execute this command:
`        $nowFile = get-date -Format "yyyyMMdd-hhmm"
        $FileName = "C:\IO Collaboration\ESG\SharePointStat_$($nowFile).csv"
        Get-MgReportSharePointSiteUsageDetail -Period  D30 -OutFile $FileName`

The Site URL field in the FileName is empty. How can I have it fill in?

Please find the 3 first lines:
Report Refresh Date,Site Id,Site URL,Owner Display Name,Is Deleted,Last Activity Date,File Count,Active File Count,Page View Count,Visited Page Count,Storage Used (Byte),Storage Allocated (Byte),Root Web Template,Owner Principal Name,Report Period
2023-10-22,0069d72c-ed8d-4701-844a-d0af72a807fc,,Claims Noord GLTL Owners,False,2023-10-20,37,8,50,1,56688702,27487790694400,Group,claimsnoordgltl_Company_teams@groups.Company.be,30
2023-10-22,00e9d2f6-b190-4ce0-a58a-e885f0b5c844,,Opcos Common Owners,False,2023-05-15,10,0,0,0,68529676,27487790694400,Group,opcoscommon_Company_teams@Company.onmicrosoft.com,30

Version installed is 
2.8.0                Microsoft.Graph.Reports  
Thanks

**Comment by peombwa** [comment]
Thanks for following up on this.

Please open a question at https://developer.microsoft.com/graph/support to get assistance from the API experts as the is empty in the API response from the service.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

**Comment by peombwa** [comment]
According to an existing service question, this is a known issue with the API - https://learn.microsoft.com/en-us/answers/questions/1382535/getsharepointsiteusagedetail-response-missing-prop. Please open ticket/question per the instructions at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2382#issuecomment-1777635574.
