### ISSUE TITLE
Add -All parameter to Get-MgDirectoryDeletedItem

### ISSUE THREAD

**Issue by worldsdream** [microsoftgraph/msgraph-sdk-powershell#2393]
It would be great if we can get a -All parameter to list all the deleted users.

**Comment by timayabi2020** [comment]
Hi @worldsdream try and use this command ``Get-MgDirectoryDeletedItemAsUser``.
See also the equivalent API documentation for the command. https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http

**Comment by worldsdream** [comment]
Yes, that works. I will use that with my scripts. Thanks @timayabi2020.
