### ISSUE TITLE
Allow capture of HTTP response headers after a cmdlet is run

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-sdk-powershell#2394]
**Is your feature request related to a problem? Please describe.**
Since the guidance from MSFT is to use Graph API whenever possible to talk to SharePoint Online (since those requests are less subject to throttling than REST/CSOM), it would also help if the PowerShell module could either output HTTP headers so I can capture the recently-introducted IETF rate limiting headers.

**Describe the solution you'd like**
At the very least, I would like to be able to access response headers after calling a Graph API cmdlet. There are some other uses for this, particularly custom handling of HTTP 302s.

Much like PowerShell has the native `-WarningVariable` and `-ErrorVariable` arguments, it would be cool to have something like `-ResponseHeadersVariable` like the PWSH 7 version of `Invoke-RestMethod` has.

In a future state, after RateLimit gets a formally published spec, would really love to see those headers be taken into account for throttling control.

**Describe alternatives you've considered**
Writing a script that uses a lot of Invoke-WebRequest (for 5.1) or Invoke-RestMethod (for 7).

**Additional context**
As I understand it, the RateLimit-* headers only show up in the beta endpoints, and the IETF spec is still in draft status, so I know that getting this into the same pipeline that does throttling control for the other cmdlets is wishful thinking at this point. Simply returning the headers doesn't seem outside of the realm of possibility, though.

**Comment by timayabi2020** [comment]
Hi @joshtransient as we plan around having the requested feature, the ideal work around would be to use ``Invoke-MgGraphRequest``. i.e.  ``Invoke-MgGraphRequest -Method GET -Uri "/v1.0/me" -RHV rh`` then grab the response header contents from $rh.  Also see screenshot below.
<img width="707" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/801127ba-efb2-4c1e-80ae-c7853528b725">

**Comment by timayabi2020** [comment]
Hi @joshtransient we have included the response headers inside a hashtable and you can easily access the response header parameter that you need. Please let us know if this works for you.

<img width="851" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/7e0ddb14-c77f-47a0-93c6-b2a58c39517f">

**Comment by CarolKigoonya** [comment]
#2600 to resolve this issue

**Comment by timayabi2020** [comment]
Issue resolved in 2.15.0
