### ISSUE TITLE
MS Graph does not seem to return values for "Notes" field of managed devices. 

### ISSUE THREAD

**Issue by raymonette2000** [microsoftgraph/msgraph-sdk-powershell#2401]
The issue is present while using the graph explorer (https://developer.microsoft.com/en-us/graph/graph-explorer) as well when running the powershell command: Get-MgDeviceManagementManagedDevice -Filter "startswith(DeviceName, 'XXXXXXX')" | Format-List 
This happens with Beta and v 1.0 of MS-Graph. 
"DeviceManagementManagedDevices.Read.All" => Admin Consent set
"DeviceManagementConfiguration.Read.All" => Admin Consent set 
"Device.Read.All"  => Admin Consent set 

Notes are set to "null" in return answer. 

R

**Comment by timayabi2020** [comment]
Hi @raymonette2000.
Both Graph explorer and Microsoft Graph PowerShell SDK get data from the same API path ``/deviceManagement/managedDevices`` and pass in the query parameter ``$filter=startswith(DeviceName, 'XXXXXXX')``, so this is most likely a service issue and we may not be best placed to give a solution/answer to this issue. Please open a support ticket/question at https://developer.microsoft.com/en-us/graph/support to get assistance from API owner.

Also see https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug for more troubleshooting details.

**Comment by raymonette2000** [comment]
Hello Timayabi2020. Thank you for following up with me. I apologize for not mentionning this earlier: MOST of the fields are returned by MS Graph or PS. It looks like that particular field is NOT getting values. I ran the query via MS Graph and PS AND looked at the devices on my tenant. The values are in production... Just not getting picked up by Graph or PS. Ill try to reach out to the API owner
