### ISSUE TITLE
Add something like -AutoReconcileProxyConflicts for Graph

### ISSUE THREAD

**Issue by worldsdream** [microsoftgraph/msgraph-sdk-powershell#2410]
**Is your feature request related to a problem? Please describe.**
We normally used:

Restore-MsolUser -UserPrincipalName "davidchew@contoso.com" -AutoReconcileProxyConflicts

or

Restore-MsolUser -UserPrincipalName "davidchew@contoso.com" -NewUserPrincipalName "davidchew02@contoso.com"

More information:
https://learn.microsoft.com/en-us/powershell/module/msonline/restore-msoluser?view=azureadps-1.0

With graph, there is no option to do it with Restore-MgDirectoryDeletedItem.

**Describe the solution you'd like**
Add a parameter or anything that we can use just like we have with Restore-MsolUser -AutoReconcileProxyConflicts.

**Comment by timayabi2020** [comment]
@SteveMutungi254

**Comment by petrhollayms** [comment]
Hi @worldsdream ,

Thank you for reporting this issue. 
I see that the underlying Graph API does not support this operation, see https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-restore?view=graph-rest-1.0&tabs=http

Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*] tags, that way it will get routed to the appropriate team for them to triage:  
 
https://aka.ms/msgraphsupport or directly https://aka.ms/askgraph
