### ISSUE TITLE
Get-MgTeamChannel no email address for "Shared channel" Email "Empty" not null  MembershipType = unknownFutureValue

### ISSUE THREAD

**Issue by blatnis17** [microsoftgraph/msgraph-sdk-powershell#2411]
Hi,
I am trying to generate a report of all email addresses of shared Teams channels
For shared channels, I get that the email is empty, although the email is not empty if I look  via the client.
Also, the MembershipType  is displayed incorrectly. I also noticed that the email address is missing if MembershipType = private or standard

get-Module Microsoft.Graph.Teams => Version 2.8.0  (same with version 2.7.0 )

Command
$Channels = Get-MgTeamChannel -TeamId "Guid"
$Channels[5] | select-object Email,MembershipType

The expected result should be : 
Email ---> Email address 
MembershipType ---> Shared

Get-MgTeamChannel -TeamId "$Guid"  -debug
DEBUG: [CmdletBeginProcessing]: - Get-MgTeamChannel begin processing with parameterSet 'List1'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope:
'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: [Authentication]: - Scopes: [AuditLog.Read.All, Channel.ReadBasic.All, ChannelSettings.Read.All,
ChannelSettings.ReadWrite.All, openid, profile, TeamworkDevice.Read.All, User.Read, User.Read.All, User.ReadWrite.All,
UserAuthenticationMethod.Read.All, email].

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/teams/$Guid/channels

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.22621;
en-US),PowerShell/5.1.22621.2428
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell/2.8.0
client-request-id             : $client-request-id 

Body:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : d8fec0ce-e9ce-4077-****-c83e021f9921
client-request-id             : $client-request-id 
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Germany West
Central","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"FR1PEPF00000D38"}}
OData-Version                 : 4.0
Date                          : Mon, 06 Nov 2023 15:00:56 GMT

Body:
{
 *
*
*
*   
},
    {
      "id": "19:2******************a@thread.tacv2",
      "createdDateTime": "2021-08-03T13:58:49.76Z",
      "displayName": "******************",
      "description": "******************",
      "isFavoriteByDefault": null,
      "email": null,
      "tenantId": "$tenantID",
      "webUrl":
"https://teams.microsoft.com/l/channel/19%3************a%40thread.tacv2/Data%20Breach%203%20August%
202021?groupId=$Guid&tenantId=********************&allowXTenantAccess=Fa
lse",
      "membershipType": "standard"
    },
    {
      "id": "19:30*********1I1@thread.tacv2",
      "createdDateTime": "2023-10-11T10:08:20.392Z",
      "displayName": "********",
      "description": "**********************",
      "isFavoriteByDefault": null,
      "email": **null**,
      "tenantId": "$tenantID",
      "webUrl":
"https://teams.microsoft.com/l/channel/19%3A**************1%40thread.tacv2/AT%20EGHV?group
Id=$Guid&tenantId=******************&allowXTenantAccess=False",
      "membershipType": "unknownFutureValue"
    },
*
*
*
*
}

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.8.0      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, G...
Script     2.8.0      Microsoft.Graph.Teams               {Add-MgChatMember, Add-MgTeamChannelMember, Add-MgTeamMemb.

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.2428
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2428
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by petrhollayms** [comment]
Hi @blatnis17 ,

It looks like a limitation of the Graph API, when looking on the documentation: https://learn.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0#properties

Could you please try to set the header? Prefer: include-unknown-enum-members

Also, can you reproduce the issue in Graph Explorer or when using Invoke-MgGraphRequest? https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.authentication/invoke-mggraphrequest?view=graph-powershell-1.0
