### ISSUE TITLE
need ability to enable, and set type for writebackconfiguation. 

### ISSUE THREAD

**Issue by tikesavage** [microsoftgraph/msgraph-sdk-powershell#2412]
Need ability to enable, and set type for writebackconfiguation. 

there is currently no method to do.

please append ability to update-mggroup.  do not create a new module.

**Comment by timayabi2020** [comment]
@tikesavage  please refer to this doc https://learn.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=http#request-body. It's available on beta endpoint.

**Comment by tikesavage** [comment]
is there plans to add switched instead of passing over in the body parameters?  stream lines coding and logic.

**Comment by tikesavage** [comment]
the microsoft support page for  update-mgbetagroup  doesnt work either lol.
can you please give me an example  of  updating to TRUE and universalsecurity group. using 2 variables

https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.beta.groups/update-mgbetagroup?view=graph-powershell-beta
