### ISSUE TITLE
Quesion about Get-MgReportAuthenticationMethodUserRegistrationDetail's IsMfaRegistered

### ISSUE THREAD

**Issue by hootyjeremy** [microsoftgraph/msgraph-sdk-powershell#2413]
This may not be a PowerShell SDK question but I am not sure where to post for a question about the Graph API internals.

Running `Get-MgReportAuthenticationMethodUserRegistrationDetail` will return an `IsMfaRegistered` object of true or false but this cmdlet is only available for premium or B2C when I run it because I get the the `Authentication_RequestFromNonPremiumTenantOrB2CTenant` if not premium.

So if I won't be able to use this cmdlet for a majority of clients, I'd like to know what the Graph API looks at to make the determination that a user is registered for MFA. Are there other cmdlets that run for all tenants where I could make that determination by looking at other information to get the same answer?

**Comment by timayabi2020** [comment]
Hi  @hootyjeremy 
For API related issues/questions we are not best placed to give an answer. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.
