### ISSUE TITLE
Connect-Graph Client Secret

### ISSUE THREAD

**Issue by tommymaynard** [microsoftgraph/msgraph-sdk-powershell#242]
In Issue [#102](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/102) the OP says, _"...(Or, another alternative would be to allow the use of client_id + client_secret, but there may have been good reasons why client_secret support wasn't implemented; certs may be preferred.)"_ Is this accurate; is this why `Connect-Graph` doesn't include a Client secret parameter? Or rather, has it just not yet been implemented into this cmdlet? It's my understanding that a client secret can be passed via `Invoke-RestMethod`, and so I'm likely to believe it will be added in time. Any word?

**Comment by MIchaelMainer** [comment]
We are currently considering alternative authentication mechanism but won't be added until post general availability.
