### ISSUE TITLE
Showing Get-Mg.... code snippets instead of Update-Mg... code snippets 

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-sdk-powershell#2421]
See the documentation links below

- [ ] https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/new-mgcontact?view=graph-powershell-1.0
- [ ] https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.sites/get-mgsitelistitemfield?view=graph-powershell-1.0

- [ ] https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.beta.identity.directorymanagement/new-mgbetacontact?view=graph-powershell-beta

**Comment by timayabi2020** [comment]
Adding list of examples that need to be reviewed
[ExamplesToBeReviewed.csv](https://github.com/microsoftgraph/msgraph-sdk-powershell/files/14275716/ExamplesToBeReviewed.csv)

**Comment by timayabi2020** [comment]
Fixed in https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2590
