### ISSUE TITLE
Microsoft.Graph.authentication: Could not load file or assembly

### ISSUE THREAD

**Issue by AlexanderHolmeset** [microsoftgraph/msgraph-sdk-powershell#2424]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:

**Describe the bug**
> A clear and concise description of what the bug is.

**To Reproduce**
1. add Microsoft.graph.authentication in azure automation by browsing gallery.
2. Create runbook with the command: Connect-MgGraph -ManagedIdentity

**Expected behavior**
> To be  authenticated.

**Module Version**
2.9
PowerShell 7.2 (preview) runbook

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/86094924/03c4dacb-5bdf-4c4e-a151-c392991f6ef5)

**Additional context**
If i install 2.8 instead, by downloading to my computer, zip, upload to azure automation it works. Issue is with 2.9.

**Comment by ItsTerryDuckett** [comment]
Same issues here. May I ask, how can you download and upload an older version? I downloaded the nupkg of 2.8 and renamed it to a .zip for an upload, but the system did not like that.

**Comment by AlexanderHolmeset** [comment]
Install it to your computer:
Install-Module -Name Microsoft.Graph.Authentication -RequiredVersion 2.8.0

then zip the module folder:
[image: image.png]



torsdag 9. november 2023 skrev Terry Duckett ***@***.***>:

**Comment by tehmichael** [comment]
Similar issues here

**Comment by timayabi2020** [comment]
Hi @AlexanderHolmeset thank you for identifying and logging this issue. As a work around please use the script below to preload the missing DLL from AZ.Accounts module:

`# Preload missing System.Memory.Data.dll dependency from Az.Accounts module.`
`$azAccountsLibPath = Join-Path (Split-Path ((Get-Module Az.Accounts -ListAvailable)[0]).Path -Parent) "lib"`
`Write-Host "$azAccountsLibPath"`
`Add-Type -AssemblyName (Join-Path $azAccountsLibPath "netstandard2.0" "System.Memory.Data.dll")`

`# Connect to Microsoft Graph.`
`Connect-MgGraph -ManagedIdentity`

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/99b0dae6-e9c0-4684-b192-7c279d17e3d1)

**Comment by lorisAmbrozzo** [comment]
@timayabi2020, thanks for the workaround. 

I just added the script block to my script like you did:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/50479061/275b82c7-d82a-4acd-8155-c4d4c5a83437)

But I still get an error: 
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/50479061/9257bec5-1af7-4e73-b19f-fc0080e39f50)

I am using Powershell Runtime version 5.1. Does your workaround only work with Powershell Runtime 7.2?

Thanks for the clarification! 😊
