### ISSUE TITLE
Update-MgBetaOrganizationSettingPersonInsight throws Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by get-itips** [microsoftgraph/msgraph-sdk-powershell#2431]
**Describe the bug**
> When trying to use Update-MgBetaOrganizationSettingPersonInsight to set  IsEnabledInOrganization property, it fails with Unexpected character encountered while parsing value

**To Reproduce**
1. Run Update-MgBetaOrganizationSettingPersonInsight either with IsEnabledInOrganization or BodyParameter
2. See error that is thrown

**Expected behavior**
> The cmdlet should update the setting that is intended to update

**Debug Output**
DEPURACIÓN: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://graph.microsoft.com/beta/organization/<guid>/settings/peopleInsights

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.22621; es-CR),PowerShell/5.1.22621.1778
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell-beta/2.9.0
client-request-id             : 8387c3ba-9ae8-4ecb-a68a-09fdfbe9aaab

Body:
{
  "isEnabledInOrganization": false
}

DEPURACIÓN: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : d3613735-5a77-49e1-b70a-b3efdd226a9a
client-request-id             : 8387c3ba-9ae8-4ecb-a68a-09fdfbe9aaab
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"South Central
US","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"SN1PEPF000160FD"}}
Cache-Control                 : no-cache
Date                          : Fri, 10 Nov 2023 14:26:13 GMT

Body:
{
  "error": {
    "code": "UnknownError",
    "message": "{\"errors\":{\"\":[\"Unexpected character encountered while parsing value: ﻿. Path '', line 0, position
0.\"]},\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.1\",\"title\":\"One or more validation errors
occurred.\",\"status\":400,\"traceId\":\"00-d36137355a7749e1b70ab3efdd226a9a-43c47a25bc4e894a-01\"}",
    "innerError": {
      "date": "2023-11-10T14:26:14",
      "request-id": "d3613735-5a77-49e1-b70a-b3efdd226a9a",
      "client-request-id": "8387c3ba-9ae8-4ecb-a68a-09fdfbe9aaab"
    }
  }
}

**Module Version**
2.9.0      Microsoft.Graph.Beta

**Environment Data**
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/36666927/6627e43d-1401-4a55-8d57-c1fc26082f7c)

**Additional context**
The call also fails using Graph Explorer

**Comment by timayabi2020** [comment]
@get-itips This is an API issue and we may not be best placed to give an answer. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.
