### ISSUE TITLE
Unable to connect with PowerShell ISE

### ISSUE THREAD

**Issue by didierhMSFT** [microsoftgraph/msgraph-sdk-powershell#244]
`Connect-Graph` ends up in a timeout without any auth prompt
![Annotation 2020-06-02 120456](https://user-images.githubusercontent.com/66306658/83507772-4d457200-a4c9-11ea-8473-4a2b0ccab163.png)

**Comment by ddyett** [comment]
same as #247 .  We recommend not using PowerShell ISE right now.
