### ISSUE TITLE
Get-MgDeviceManagementWindowsAutopilotDeviceIdentity with a filter on a SerialNumber that has hyphens fails with "Bad Request"

### ISSUE THREAD

**Issue by HAL377** [microsoftgraph/msgraph-sdk-powershell#2464]
Hi,

I am trying to search for an Autopilot device using the device serial number, and while this works fine with a serial number without hyphens (ex. 5CD333527Z) it fails with a "Bad Request" when using a serial number with hyphens (ex. ec2a1bbf-7e9f-45f0-f404-bec2e9da6f35)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/56118373/055e0dde-2809-4934-aaaf-206e53f66232)

Error Message: _An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 5b9e3dd5-1c4f-4fbd-a5e1-a0c1411ad1b6 - Url: https://fef.msub01.manage.microsoft.com/DeviceEnrollmentFE/StatelessDeviceEnrollmentFEService/deviceManagement/windowsAutopilotDeviceIdentities?api-version=2021-01-22&$filter=contains(serialNumber%2c%27ec2a1bbf-7e9f-45f0-f404-bec2e9da6f35%27)_

I tried encoding the serial number but it does make any difference!

To reproduce the issue simply use
```
Connect-MgGraph -Scopes DeviceManagementServiceConfig.Read.All
Get-MgDeviceManagementWindowsAutopilotDeviceIdentity -Filter "contains(serialNumber,'ec2a1bbf-7e9f-45f0-f404-bec2e9da6f35')"

```
**Environment Data**

Microsoft Graph SDK modules are version 2.6.1

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Thank you in advance 

Sincerely,
Tonino Bruno

**Comment by michielvanheerde** [comment]
Just ran into this issue using Get-AutoPilotDevice when doing a check if a machine is already present as autopilot device and found that using serial numbers that exceed 32 characters (VMWare virtual machines are known to do this) are not accepted and always result in this error. I think both cmdlets have a maximum number of characters that can be entered.
