### ISSUE TITLE
[2.10.0] Graph.Groups Get-MgGroups ERROR on PS7.4.0  but OK on PS5.1

### ISSUE THREAD

**Issue by alexyvic** [microsoftgraph/msgraph-sdk-powershell#2467]
**Describe the bug**
This bug only exist with Powershell 7.4.0, when run under 5.1 there is no issue

**To Reproduce**
1. Execute `-Mg-` with `$AllGroups = Get-MgGroup -All`
2. See error at `ParentContainsErrorRecordException: C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Groups\2.10.0\exports\ProxyCmdletDefinitions.ps1:41287
 Line |
41287 |          $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvoc …
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block,
      | or a CommandInfo object."`

**Expected behavior**
> Get all AzureAD Groups.

**Debug Output**
```
ParentContainsErrorRecordException: C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Groups\2.10.0\exports\ProxyCmdletDefinitions.ps1:41287
 Line |
41287 |          $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvoc …
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block,
      | or a CommandInfo object."
```

**Module Version**
```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.0                Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext…}
Script     2.10.0                Microsoft.Graph.Groups              {Add-MgGroupDriveListContentTypeCopy, Add-MgGroupDriveListContentTypeCopyFromContentTypeHub, Add-MgGroupFavorite, Add-MgGroupSite…}
```

**Environment Data**
```
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by timayabi2020** [comment]
@alexyvic closing this because it's a duplicate.  Kindly let's engage on this thread https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2460
