### ISSUE TITLE
Connect to Graph fails in Windows PowerShell ISE

### ISSUE THREAD

**Issue by bpcastilho** [microsoftgraph/msgraph-sdk-powershell#247]
I was trying to use the MS Graph module in Windows PowerShell ISE, but when I ran the cmd:
`Connect-Graph -Scopes "User.Read"`

![image](https://user-images.githubusercontent.com/32835162/83531640-29902500-a4e5-11ea-894c-06985357ae14.png)
 
[AB#7409](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7409)

**Comment by ddyett** [comment]
yes PowerShell ISE does not support the Console class so we recommend not using ISE right now.

**Comment by jagrock** [comment]
I had to run the Connect-Graph command outside the ISE first, then it would work in ISE afterwards.

**Comment by o-l-a-v** [comment]
Are you not going to fix this anytime soon? I bet I'm not the only one still using PowerShell 5.1 and ISE.
At least detect if run from ISE, redirect output to different stream or something, like forced Information or Verbose maybe.

**Comment by o-l-a-v** [comment]
There is still no output in PowerShell ISE with the latest version of ```Microsoft.Graph.*``` modules available from PowerShellGallery.

![image](https://user-images.githubusercontent.com/6450056/119805344-754f9180-bee1-11eb-938e-4a374c387f8e.png)

But new PS module is probly not built against new SDK yet?
