### ISSUE TITLE
Can't Use ManagedTenant.Read.All Scope in PowerShell SDK

### ISSUE THREAD

**Issue by jreinhardtproarch** [microsoftgraph/msgraph-sdk-powershell#2472]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
The ManagedTenant.Read.All scope cannot be used with the module in the regular or Beta modules.

**To Reproduce**
Connect-MgGraph -Scopes ManagedTenant.Read.All

**Expected behavior**
Present the consent process where an admin can authorize this permission on the default Graph SDK app or start the admin consent workflow.

**Debug Output**
DEBUG: InteractiveBrowserCredential.Authenticate invoked. Scopes: [ managedtenant.read.all ] ParentRequestId:
DEBUG: Executing interactive authentication workflow inline.
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:11Z - b1974168-8f38-4ee7-a83a-30c52d0494be] MSAL MSAL.NetCore with assembly version '4.56.0.0'. CorrelationId(b1974168-8f38-4ee7-a83a-30c52d0494be)
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:11Z - b1974168-8f38-4ee7-a83a-30c52d0494be] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent:
Prompt: select_account
HasCustomWebUi: False

DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:11Z - b1974168-8f38-4ee7-a83a-30c52d0494be]
=== Request Data ===
Authority Provided? - True
Scopes - managedtenant.read.all
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - b1974168-8f38-4ee7-a83a-30c52d0494be
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:11Z - b1974168-8f38-4ee7-a83a-30c52d0494be] === Token Acquisition (InteractiveRequest) started:
         Scopes: managedtenant.read.all
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:11Z - b1974168-8f38-4ee7-a83a-30c52d0494be] [Instance Discovery] Instance discovery is enabled and will be performed
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:11Z - b1974168-8f38-4ee7-a83a-30c52d0494be] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:11Z - b1974168-8f38-4ee7-a83a-30c52d0494be] Using system browser.
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:11Z - b1974168-8f38-4ee7-a83a-30c52d0494be] Listening for authorization code on http://localhost:51498/
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:18Z - b1974168-8f38-4ee7-a83a-30c52d0494be] Default OS Browser intercepted an Uri with an error: invalid_client AADSTS650053: The application 'Microsoft Graph Command Line Tools' asked for scope 'managedtenant.read.all' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor. Trace ID: 860b68c9-2157-4039-81ee-22b4c7bd0103 Correlation ID: b1974168-8f38-4ee7-a83a-30c52d0494be Timestamp: 2023-11-30 15:50:18Z
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:18Z - b1974168-8f38-4ee7-a83a-30c52d0494be] Processing a response message to the browser. HttpStatus:OK
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:18Z - b1974168-8f38-4ee7-a83a-30c52d0494be] Authorization result was not successful. See error message for more details.
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22621 [2023-11-30 15:50:18Z - b1974168-8f38-4ee7-a83a-30c52d0494be] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: invalid_client
HTTP StatusCode 0
CorrelationId

   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.VerifyAuthorizationResult(AuthorizationResult authorizationResult, String originalState)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
DEBUG: InteractiveBrowserCredential.Authenticate was unable to retrieve an access token. Scopes: [ managedtenant.read.all ] ParentRequestId:  Exception: Azure.Identity.AuthenticationFailedException (0x80131500): InteractiveBrowserCredential authentication failed: AADSTS650053: The application 'Microsoft Graph Command Line Tools' asked for scope 'managedtenant.read.all' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor. Trace ID: 860b68c9-2157-4039-81ee-22b4c7bd0103 Correlation ID: b1974168-8f38-4ee7-a83a-30c52d0494be Timestamp: 2023-11-30 15:50:18Z
 ---> Microsoft.Identity.Client.MsalServiceException (0x80131500): AADSTS650053: The application 'Microsoft Graph Command Line Tools' asked for scope 'managedtenant.read.all' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor. Trace ID: 860b68c9-2157-4039-81ee-22b4c7bd0103 Correlation ID: b1974168-8f38-4ee7-a83a-30c52d0494be Timestamp: 2023-11-30 15:50:18Z
Connect-MgGraph: InteractiveBrowserCredential authentication failed: AADSTS650053: The application 'Microsoft Graph Command Line Tools' asked for scope 'managedtenant.read.all' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor. Trace ID: 860b68c9-2157-4039-81ee-22b4c7bd0103 Correlation ID: b1974168-8f38-4ee7-a83a-30c52d0494be Timestamp: 2023-11-30 15:50:18Z
**Module Version**

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.9.0                 Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-M…

**Environment Data**
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Screenshots**
None

**Additional context**
This concerns Microsoft 365 Lighthouse. I also attempted in the same target tenant to create a custom App Registration but had the same problem.

**Comment by jreinhardtproarch** [comment]
I think the difference is at the heart of the problem - https://learn.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&preserve-view=true. So your suggestion did work, and perhaps this issue can be closed but I would ask what this repo can do to ensure that the inconsistency is remediated in documentation. Thank you.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/49915885/f83782c1-8d18-4169-8ddd-2c76573d2899)

**Comment by peombwa** [comment]
Permission/scope names can vary from resource names and namespaces since they are independent concepts. The permissions are documented on the actual API request pages, not the resource type page. For example, [List Tenants API](https://learn.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenants?view=graph-rest-beta&tabs=http#permissions). The SDK also ships with a few helper commands that you can use to discover scopes of a given resource - https://learn.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-permission?view=graph-powershell-1.0.

 If you notice any discrepancies with the documented permissions, please use the feedback link located at the bottom of the API reference page to provide feedback to the documentation team.

**Comment by peombwa** [comment]
Closing as permission issue that's external to the SDK.
