### ISSUE TITLE
Get-MgIdentityConditionalAccess vs Get-MgIdentityConditionalAccessPolicy

### ISSUE THREAD

**Issue by LeandroRRocha** [microsoftgraph/msgraph-sdk-powershell#2500]
**Describe the bug**
Looking for the powershell cmdlet to get the Conditional Access Policies I came across these two commands:

**Get-MgIdentityConditionalAccess**: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/get-mgidentityconditionalaccess?view=graph-powershell-1.0

**Get-MgIdentityConditionalAccessPolicy**: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/get-mgidentityconditionalaccesspolicy?view=graph-powershell-1.0

However, the Get-MgIdentityConditionalAccess cmdlet and its documentation page appear to have been published automatically from MS Graph metadata, but they do not reflect the operation of getting data from conditional access policies.

**To Reproduce**
1. Execute Import-Module Microsoft.Graph.Identity.SignIns
2. Execute Connect-MgGraph
3. Get-MgIdentityConditionalAccess
4. Catch the output error: Get-MgIdentityConditionalAccess : {"Message":"No HTTP resource was found that matches the request URI 'https://eu.prod.graph.ipc.msidentity.com/conditionalAccess'.","MessageDetail":"No route providing a 
controller name was found to match request URI 'https://eu.prod.graph.ipc.msidentity.com/conditionalAccess'"}
Status: 404 (NotFound) / ErrorCode: UnknownError

**Expected behavior**
Unpublish the doc and the **Get-MgIdentityConditionalAccess** cmdlet, keeping only the **Get-MgIdentityConditionalAccessPolicy** cmdlet which already works as expected

**Debug Output**
DEBUG: [CmdletBeginProcessing]: - Get-MgIdentityConditionalAccess begin processing with parameterSet 'Get'.
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppNam
e: 'Microsoft Graph Command Line Tools'.
DEBUG: [Authentication]: - Scopes: [Application.ReadWrite.All, AuditLog.Read.All, Directory.Read.All, Group.ReadWrite.All, Group
Member.Read.All, openid, Policy.Read.All, Policy.ReadWrite.AuthenticationMethod, Policy.ReadWrite.PermissionGrant, profile, Role
Management.Read.All, RoleManagement.ReadWrite.Directory, User.Read, User.Read.All, User.ReadBasic.All, User.ReadWrite.All, UserA
uthenticationMethod.Read.All, UserAuthenticationMethod.ReadWrite.All, email].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/identity/conditionalAccess

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.22621; en-US),PowerShell/5.1.22621.2506

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Transfer-Encoding             : chunked
Connection                    : keep-alive
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
X-Cache                       : CONFIG_NOCACHE
Cache-Control                 : no-cache
Date                          : Wed, 20 Dec 2023 14:15:09 GMT

Body:
{
  "error": {
    "code": "UnknownError",
    "message": "{\"Message\":\"No HTTP resource was found that matches the request URI 'https://eu.prod.graph.ipc.msidentity.com
/conditionalAccess'.\",\"MessageDetail\":\"No route providing a controller name was found to match request URI 'https://eu.prod.
graph.ipc.msidentity.com/conditionalAccess'\"}",
    "innerError": {
      "date": "2023-12-20T14:15:09",
    }
  }
}

Get-MgIdentityConditionalAccess : {"Message":"No HTTP resource was found that matches the request URI 
'https://eu.prod.graph.ipc.msidentity.com/conditionalAccess'.","MessageDetail":"No route providing a controller name was found 
to match request URI 'https://eu.prod.graph.ipc.msidentity.com/conditionalAccess'"}
Status: 404 (NotFound)
ErrorCode: UnknownError
Date: 2023-12-20T14:15:09
Headers:
Transfer-Encoding             : chunked
Connection                    : keep-alive
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
X-Cache                       : CONFIG_NOCACHE
Cache-Control                 : no-cache
Date                          : Wed, 20 Dec 2023 14:15:09 GMT
At line:1 char:1
+ Get-MgIdentityConditionalAccess -debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Property = , ExpandProperty =  }:<>f__AnonymousType3`2) [Get-MgIdentityCond 
   itionalAccess_Get], Exception
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgIdentityConditionalAccess_Get
DEBUG: [CmdletEndProcessing]: - Get-MgIdentityConditionalAccess end processing.

**Module Version**
ModuleType Version  Name                                    
---------- -------  ----                                    
    Script 2.11.1   Microsoft.Graph.Authentication          
    Script 2.11.1   Microsoft.Graph.Identity.SignIns        
    Script 0.0      Microsoft.Graph.Identity.SignIns.custom 
    Binary 2.11.1.0 Microsoft.Graph.Identity.SignIns.private
    Script 2.11.1   Microsoft.Graph.Reports                 

**Environment Data**
Name                           Value                                                                                           
----                           -----                                                                                           
PSVersion                      5.1.22621.2506                                                                                  
PSEdition                      Desktop                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                         
BuildVersion                   10.0.22621.2506                                                                                 
CLRVersion                     4.0.30319.42000                                                                                 
WSManStackVersion              3.0                                                                                             
PSRemotingProtocolVersion      2.3                                                                                             
SerializationVersion           1.1.0.1    

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by LeandroRRocha** [comment]
Get-MgIdentityConditionalAccess calls the https://graph.microsoft.com/v1.0/identity/conditionalAccess URL witch is the entry point for the Conditional Access (CA) object model, so returning data (get method) seems not expected.

**Comment by timayabi2020** [comment]
@LeandroRRocha thank you for logging this issue. With the current release (2.16.0) the ``Get-MgIdentityConditionalAccess`` cmdlet was removed.
