### ISSUE TITLE
Unable to get Get-MgUser from Powershell 7.2 version however I am able to connect Connect-MgGraph -ClientId "xxxxxxxxx" -TenantId "xxxxxxxx" -CertificateThumbprint "xxxxx". Is this not support 

### ISSUE THREAD

**Issue by fcbtdoorga** [microsoftgraph/msgraph-sdk-powershell#2504]
Get-MgUser -Top 10 -Property Id, DisplayName, BusinessPhones, companyName | Format-Table Id, DisplayName, BusinessPhones, companyName
Get-MgUser: The 'Get-MgUser' command was found in the module 'Microsoft.Graph.Users', but the module could not be loaded due to the following error: [Assembly with same name is already loaded]
For more information, run 'Import-Module Microsoft.Graph.Users'.

this error appear in the PowerShell 7.4 (latest version)  but it's working fine in PowerShell ISE. so the question does Graph API does not support Power shell latest version?

**Comment by timayabi2020** [comment]
Hi @fcbtdoorga please confirm if you have Az.Accounts module installed by running ``Get-module az.accounts -ListAvailable``
