### ISSUE TITLE
Get-MgGroupTeamChannelFileFolder does not provision the Private Channel SharePoint site

### ISSUE THREAD

**Issue by StevieBleeds** [microsoftgraph/msgraph-sdk-powershell#2508]
Up until December, I have been able to successfully automate the creation of Private Channels using the Graph API in conjunction with the advice using the following article: https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http whereby hitting the filesFolder endpoint would "force" provision the SharePoint site.

However, over the last couple weeks, this endpoint doesn't appear to work programmatically anymore and requires manual intervention by either clicking on the Files tab in the Private Channel or by using the Graph Explorer to provision the underlying SharePoint site for the Private Channel. Using the endpoint using PowerShell for example does not provision the SharePoint site.

The error received when using the Graph command _Get-MgGroupTeamChannelFileFolder -ChannelId $channelID -GroupId $groupId_ is:

```
2024-01-01T19:11:00Z   [Error]   ERROR: [UnknownError] : 404 page not found

Exception             : 
    Type    : System.Exception
    Message : [UnknownError] : 404 page not found

    HResult : -2146233088
TargetObject          : { GroupId = REDACTED, ChannelId = REDACTED, Property = , ExpandProperty =  }
CategoryInfo          : InvalidOperation: ({ GroupId = 7c2d1be…ExpandProperty =  }:<>f__AnonymousType19`4) [Get-MgGroupTeamChannelFileFolder_Get], Exception
FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgGroupTeamChannelFileFolder_Get
ErrorDetails          : 404 page not found
                        
                        Status: 404 (NotFound)
                        ErrorCode: UnknownError
                        Date: 2024-01-01T19:11:00
                        
                        Headers:
                        Transfer-Encoding             : chunked
                        Vary                          : Accept-Encoding
                        Strict-Transport-Security     : max-age=31536000
                        request-id                    : f4f34fb0-524c-4355-bb0f-7adf70b45feb
                        client-request-id             : 7add7b3c-0a08-4013-940c-a903fc0d74ba
                        x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK 
  South","Slice":"E","Ring":"3","ScaleUnit":"005","RoleInstance":"LO2PEPF00001F24"}}
                        Date                          : Mon, 01 Jan 2024 19:10:59 GMT
    InvocationInfo        : 
    MyCommand        : Get-MgGroupTeamChannelFileFolder_Get
    ScriptLineNumber : 34
    OffsetInLine     : 1
    HistoryId        : 1
    ScriptName       : C:\home\site\wwwroot\TestInvokeMethodSiteCreation\run.ps1
    Line             : Get-MgGroupTeamChannelFileFolder -ChannelId REDACTED -GroupId REDACTED
                       
    PositionMessage  : At C:\home\site\wwwroot\TestInvokeMethodSiteCreation\run.ps1:34 char:1
                       + Get-MgGroupTeamChannelFileFolder -ChannelId REDACTED
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\home\site\wwwroot\TestInvokeMethodSiteCreation
    PSCommandPath    : C:\home\site\wwwroot\TestInvokeMethodSiteCreation\run.ps1
    InvocationName   : Get-MgGroupTeamChannelFileFolder
    CommandOrigin    : Internal
    ScriptStackTrace      : at Get-MgGroupTeamChannelFileFolder<Process>, 
 
C:\home\data\ManagedDependencies\2401011609454207601.r\Microsoft.Graph.Teams\2.10.0\exports\ProxyCmdletDefinitions.ps1: line 11656
                        at <ScriptBlock>, C:\home\site\wwwroot\TestInvokeMethodSiteCreation\run.ps1: line 34
```

Has there been a change with how the endpoint now works since it was working fine up until recently?

**Comment by StevieBleeds** [comment]
Up until December, I have been able to successfully automate the creation of Private Channels using the Graph API in conjunction with the advice using the following article: https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http whereby hitting the filesFolder endpoint would "force" provision the SharePoint site.

However, over the last couple weeks, this endpoint doesn't appear to work programmatically anymore and requires manual intervention by either clicking on the Files tab in the Private Channel or by using the Graph Explorer to provision the underlying SharePoint site for the Private Channel. Using the endpoint using PowerShell for example does not provision the SharePoint site.

The error received when using the Graph command _Get-MgGroupTeamChannelFileFolder -ChannelId $channelID -GroupId $groupId_ is:

`2024-01-01T19:11:00Z   [Error]   ERROR: [UnknownError] : 404 page not found

Exception             : 
    Type    : System.Exception
    Message : [UnknownError] : 404 page not found

    HResult : -2146233088
TargetObject          : { GroupId = REDACTED, ChannelId = REDACTED, Property = , ExpandProperty =  }
CategoryInfo          : InvalidOperation: ({ GroupId = 7c2d1be…ExpandProperty =  }:<>f__AnonymousType19`4) [Get-MgGroupTeamChannelFileFolder_Get], Exception
FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgGroupTeamChannelFileFolder_Get
ErrorDetails          : 404 page not found
                        
                        Status: 404 (NotFound)
                        ErrorCode: UnknownError
                        Date: 2024-01-01T19:11:00
                        
                        Headers:
                        Transfer-Encoding             : chunked
                        Vary                          : Accept-Encoding
                        Strict-Transport-Security     : max-age=31536000
                        request-id                    : f4f34fb0-524c-4355-bb0f-7adf70b45feb
                        client-request-id             : 7add7b3c-0a08-4013-940c-a903fc0d74ba
                        x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"005","RoleInstance":"LO2PEPF00001F24"}}
                        Date                          : Mon, 01 Jan 2024 19:10:59 GMT
                        
                        
InvocationInfo        : 
    MyCommand        : Get-MgGroupTeamChannelFileFolder_Get
    ScriptLineNumber : 34
    OffsetInLine     : 1
    HistoryId        : 1
    ScriptName       : C:\home\site\wwwroot\TestInvokeMethodSiteCreation\run.ps1
    Line             : Get-MgGroupTeamChannelFileFolder -ChannelId REDACTED -GroupId REDACTED
                       
    PositionMessage  : At C:\home\site\wwwroot\TestInvokeMethodSiteCreation\run.ps1:34 char:1
                       + Get-MgGroupTeamChannelFileFolder -ChannelId REDACTED
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\home\site\wwwroot\TestInvokeMethodSiteCreation
    PSCommandPath    : C:\home\site\wwwroot\TestInvokeMethodSiteCreation\run.ps1
    InvocationName   : Get-MgGroupTeamChannelFileFolder
    CommandOrigin    : Internal
ScriptStackTrace      : at Get-MgGroupTeamChannelFileFolder<Process>, C:\home\data\ManagedDependencies\2401011609454207601.r\Microsoft.Graph.Teams\2.10.0\exports\ProxyCmdletDefinitions.ps1: line 11656
                        at <ScriptBlock>, C:\home\site\wwwroot\TestInvokeMethodSiteCreation\run.ps1: line 34
PipelineIterationInfo :`

Has there been a change with how the endpoint now works since it was working fine up until recently?

**Comment by ashleywb** [comment]
@StevieBleeds are you still encountering this issue?

**Comment by StevieBleeds** [comment]
On one of our tenants, yes.

**Comment by rafa-ayadi-cloudm** [comment]
We have this issue as well. We are waiting for 5 minutes, and then invoking the Get filesFolder API as described in the doc, and it is still not working. Is there anyway to have a reliable way to provision the private channel site?
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/155651515/c5d09f36-68c1-41e4-a0d8-716b5f6aaea4)

**Comment by advdberg** [comment]
@StevieBleeds I guess it was going wrong only on a targeted release tenant before?
@rafa-ayadi-cloudm since when do you have the issue?

We had the same issue already since the end of November but only on targeted release tenants, see the following post of my colleague for more details:
https://learn.microsoft.com/en-us/answers/questions/1454815/could-not-create-a-private-channel-using-microsoft

From today on we see it now also happening on all of our Standard Release tenants, despite our contact with Microsoft Support from the beginning of December about this issue, they now seem to have pushed things to Standard Release.

**Comment by StevieBleeds** [comment]
@advdberg In my experience, yes, it was our targeted release tenant.

So far in my organisation , our automated process hasn't yet started to fail to create Private Channels through to completion.

**Comment by advdberg** [comment]
@StevieBleeds @rafa-ayadi-cloudm Since the 1st of February we see things to start working again. Do you see the same?

**Comment by rafa-ayadi-cloudm** [comment]
@advdberg Yes, this seems to work again now. Still not instantly though, we have to wait for 5 minutes and call the filesFolder API for the private channel site to be provisioned.

**Comment by StevieBleeds** [comment]
Yes, in our Standard Release tenant, it's working fine now. My Targeted Release one it wasn't quite working.
