### ISSUE TITLE
Get-MgGroup -Expand Owners only returns user Id and DeletedDateTime

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-sdk-powershell#252]
In Graph Explorer, the following commands return the expanded property set for users who are owners:

> https://graph.microsoft.com/v1.0/groups?$expand=Owners
> https://graph.microsoft.com/v1.0/groups/[guid]?$expand=Owners
> https://graph.microsoft.com/beta/groups?Expand=Owners
> https://graph.microsoft.com/beta/groups/[guid]?Expand=Owners

`Get-MgGroup -Expand Owners` only returns the properties Id and DeletedDateTime for Group owners.

Version: 0.5.1
PowerShell version: Windows PowerShell 5.1

**Comment by ddyett** [comment]
related to #19

**Comment by KirkMunro** [comment]
Please address this issue. Select is still useful without it, but hurts performance because many individual network calls are necessary to retrieve the full information that is needed.

**Comment by ddyett** [comment]
yes we do intend to address this.

**Comment by joshtransient** [comment]
This now appears to just throw an error with v1.0.1 of the module: `Get-MgGroup : Unrecognized query argument specified: '?$Expand'`

**Comment by KirkMunro** [comment]
@joshtransient See #409. It only happens in Windows PowerShell. If PowerShell 7 is an option for you, it doesn't happen there. Unfortunately PowerShell 7 is not an option for me. They're working on the issue though.

**Comment by ddyett** [comment]
yes #410 should address this bug.  We're working on getting an update out soon.

**Comment by peombwa** [comment]
Closing since this was fixed in 1.1.0. Use `Update-Module Microsoft.Graph` to update.
