### ISSUE TITLE
Unable to install modules in PowerShell 7

### ISSUE THREAD

**Issue by DanielBradley1** [microsoftgraph/msgraph-sdk-powershell#2526]
**Describe the bug**
> When attempting to install the Microsoft.Graph modules in PowerShell 7, I am met with the error: Install-PSResrouce: The signature for 'Microsoft.Graph' is 'NoSigned'. This is not happening on PowerShell 5. 

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/96792909/9ef0f62a-b2cf-4570-837b-baa8619f7ad0)

Both of the execution policies for PS7 and PS5 are configured as follows:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/96792909/2b817617-9886-41b3-aebe-cc9e759243d9)

This is occurring on any version of the modules I attempt to install. It is also happening when I set both execution policies to unrestricted and also any version of PowerShell 7.

Other modules, such as the AzureAD modules, install fine.

**Comment by timayabi2020** [comment]
Hi @DanielBradley1,
I am not able to reproduce your issue because I uninstalled my modules and successfully installed them back. Is your system configured to prevent any installation of unsigned modules?
