### ISSUE TITLE
Remove-MgBetaDirectoryAdministrativeUnit not working

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#2529]
**Describe the bug**
The Remove-MgBetaDirectoryAdministrativeUnit throws an Odata Path is invalid error.

```PowerShell
Remove-MgBetaDirectoryAdministrativeUnit -AdministrativeUnitId 4bb4d338-f61b-4a5d-8109-9a69b8a64844
Remove-MgBetaDirectoryAdministrativeUnit : {"Message":"The OData path is invalid."}
Status: 404 (NotFound)
ErrorCode: InternalServerError
Date: 2024-01-15T21:17:50
Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 1ee0ebbc-07e0-4808-a326-a57bc3e51427
client-request-id             : f5e01d91-4c18-4f4d-9c28-f415ecec8c3b
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Canada
East","Slice":"E","Ring":"2","ScaleUnit":"001","RoleInstance":"QB1PEPF00001034"}}
Date                          : Mon, 15 Jan 2024 21:17:49 GMT
At line:1 char:1
+ Remove-MgBetaDirectoryAdministrativeUnit -AdministrativeUnitId 4bb4d3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Administrativ...4, IfMatch =  }:<>f__AnonymousType136`2) [Remove-Mg
   BetaDi...tiveUnit_Delete], Exception
    + FullyQualifiedErrorId : InternalServerError,Microsoft.Graph.Beta.PowerShell.Cmdlets.RemoveMgBetaDirectoryAdminis
   trativeUnit_Delete
```

**To Reproduce**
Run Remove-MgBetaDirectoryAdministrativeUnit -AdministrativeUnitId <unitId>

**Expected behavior**
The Administrative Unit is deleted.

**Debug Output**
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
DELETE

Absolute Uri:
https://graph.microsoft.com/beta/directory/administrativeUnits/Test-Unit

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.26024;
en-US),PowerShell/5.1.26024.1000
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell-beta/2.11.1
client-request-id             : 7ae4166f-bc24-4c5c-9da9-783ccd048ce7

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 260d9065-8ac7-45c8-be98-b4a43db2583a
client-request-id             : 7ae4166f-bc24-4c5c-9da9-783ccd048ce7
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Canada
East","Slice":"E","Ring":"2","ScaleUnit":"002","RoleInstance":"QB1PEPF00001037"}}
Date                          : Mon, 15 Jan 2024 21:21:40 GMT

Body:
{
  "error": {
    "code": "InternalServerError",
    "message": "{\"Message\":\"The OData path is invalid.\"}",
    "innerError": {
      "date": "2024-01-15T21:21:41",
      "request-id": "260d9065-8ac7-45c8-be98-b4a43db2583a",
      "client-request-id": "7ae4166f-bc24-4c5c-9da9-783ccd048ce7"
    }
  }
}

Confirm
{"Message":"The OData path is invalid."}

Status: 404 (NotFound)
ErrorCode: InternalServerError
Date: 2024-01-15T21:21:41

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 260d9065-8ac7-45c8-be98-b4a43db2583a
client-request-id             : 7ae4166f-bc24-4c5c-9da9-783ccd048ce7
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Canada
East","Slice":"E","Ring":"2","ScaleUnit":"002","RoleInstance":"QB1PEPF00001037"}}
Date                          : Mon, 15 Jan 2024 21:21:40 GMT

**Module Version**
2.11.1

**Environment Data**
5.1

**Screenshots**
* N/A

**Additional context**
* N/A

**Comment by SeniorConsulting** [comment]
That's interesting. The paths differ between v1.0 and beta. The v.10 includes /directory/ 

- v1.0: DELETE https://graph.microsoft.com/v1.0/directory/administrativeUnits/{id}
- beta: DELETE https://graph.microsoft.com/beta/administrativeUnits/{id}

Sourced from:
- https://learn.microsoft.com/en-us/graph/api/administrativeunit-delete?view=graph-rest-1.0&tabs=http
- https://learn.microsoft.com/en-us/graph/api/administrativeunit-delete?view=graph-rest-beta&tabs=http

In your debug, we can see the SDK tried to get to https://graph.microsoft.com/beta/directory/administrativeUnits/Test-Unit.

**Comment by timayabi2020** [comment]
Hi @NikCharlebois this seems to be an API related issue and cmdlet was generated based on the path availed by the API owner. 
For API related issues/questions we are not best placed to give an answer. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.
Meanwhile you can use the work around suggested by @SeniorConsulting

**Comment by Borgquite** [comment]
Feedback posted here https://feedbackportal.microsoft.com/feedback/idea/bc1604dd-5141-f011-a2d9-7c1e5299279a
