### ISSUE TITLE
Why is "Microsoft Graph PowerShell" an "unverified" application?

### ISSUE THREAD

**Issue by edutrom** [microsoftgraph/msgraph-sdk-powershell#2537]
Good afternoon, when I try to run Microsoft Graph for the first time, it appears as "unverified", there was an issue with this case but it was closed..

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/157170252/a0207533-a35f-426f-a2e6-5eb38bb79c48)

**Comment by timayabi2020** [comment]
Closing this duplicate issue as it is being tracked [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/482)
