### ISSUE TITLE
Get-MgIdentityGovernancePrivilegedAccessGroup: The provider is missing

### ISSUE THREAD

**Issue by bridystone** [microsoftgraph/msgraph-sdk-powershell#2553]
**Describe the bug**
See Subject:
Get-MgIdentityGovernancePrivilegedAccessGroup fails to execute -> Error Message "The Provider is missing"
There is no documentation on any Provider. Nor is there a Parameter

**To Reproduce**
``` powershell
Connect-MgGraph
Get-MgIdentityGovernancePrivilegedAccessGroup
```
```
Get-MgIdentityGovernancePrivilegedAccessGroup_Get: {"errorCode":"MissingProvider","message":"The provider is missing.","instanceAnnotations":[]}

Status: 400 (BadRequest)
ErrorCode: UnknownError
Date: 2024-01-31T14:01:19

Headers:
Date                          : Wed, 31 Jan 2024 14:01:18 GMT
Connection                    : Keep-Alive
request-id                    : 166e5c20-0cea-40e7-9172-5480fe1d2eec
Cache-Control                 : private
client-request-id             : eb68d253-a28e-42a5-9450-359cedc452ef
Transfer-Encoding             : chunked
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Germany West Central","Slice":"E","Ring":"5","ScaleUnit":"004","RoleInstance":"FR2PEPF00000406"}}
Strict-Transport-Security     : max-age=31536000
```

**Expected behavior**

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.
```
 Get-MgIdentityGovernancePrivilegedAccessGroup -debug
DEBUG: [CmdletBeginProcessing]: - Get-MgIdentityGovernancePrivilegedAccessGroup begin processing with parameterSet 'Get'.
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.
DEBUG: [Authentication]: - Scopes: [Application.ReadWrite.All, AppRoleAssignment.ReadWrite.All, AuditLog.Read.All, Chat.Create, Chat.Read, Chat.ReadBasic, Chat.ReadWrite, ChatMessage.Read, ChatMessage.Send,
Directory.Read.All, Directory.ReadWrite.All, email, EntitlementManagement.Read.All, openid, Organization.Read.All, Policy.Read.All, profile, RoleManagement.Read.All, RoleManagement.ReadWrite.Directory, RoleM
anagementPolicy.Read.AzureADGroup, RoleManagementPolicy.ReadWrite.AzureADGroup, User.Read, User.Read.All, User.ReadWrite.All, UserAuthenticationMethod.Read.All, UserAuthenticationMethod.ReadWrite.All, Privil
egedAssignmentSchedule.Read.AzureADGroup, PrivilegedAssignmentSchedule.ReadWrite.AzureADGroup, PrivilegedAccess.Read.AzureADGroup, PrivilegedAccess.ReadWrite.AzureADGroup].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/identityGovernance/privilegedAccess/group

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.17763; de-DE),PowerShell/7.4.1
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell/2.11.1
client-request-id             : f2a59c03-a3c9-4979-8443-b8944a990526

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Date                          : Wed, 31 Jan 2024 14:23:15 GMT
Connection                    : Keep-Alive

request-id                    : fbf26c59-2237-47c8-bbf5-c1f34ee5ac50
Cache-Control                 : private
client-request-id             : f2a59c03-a3c9-4979-8443-b8944a990526
Transfer-Encoding             : chunked
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Germany West Central","Slice":"E","Ring":"5","ScaleUnit":"005","RoleInstance":"FR3PEPF00000366"}}
Strict-Transport-Security     : max-age=31536000

Body:
{
  "error": {
    "code": "UnknownError",
    "message": "{\"errorCode\":\"MissingProvider\",\"message\":\"The provider is missing.\",\"instanceAnnotations\":[]}",
    "innerError": {
      "date": "2024-01-31T14:23:15",
      "request-id": "fbf26c59-2237-47c8-bbf5-c1f34ee5ac50",
      "client-request-id": "f2a59c03-a3c9-4979-8443-b8944a990526"
    }
  }
}


Get-MgIdentityGovernancePrivilegedAccessGroup_Get: {"errorCode":"MissingProvider","message":"The provider is missing.","instanceAnnotations":[]}

Status: 400 (BadRequest)
ErrorCode: UnknownError
Date: 2024-01-31T14:23:15

Headers:
Date                          : Wed, 31 Jan 2024 14:23:15 GMT
Connection                    : Keep-Alive
request-id                    : fbf26c59-2237-47c8-bbf5-c1f34ee5ac50
Cache-Control                 : private
client-request-id             : f2a59c03-a3c9-4979-8443-b8944a990526
Transfer-Encoding             : chunked
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Germany West Central","Slice":"E","Ring":"5","ScaleUnit":"005","RoleInstance":"FR3PEPF00000366"}}
Strict-Transport-Security     : max-age=31536000

DEBUG: [CmdletEndProcessing]: - Get-MgIdentityGovernancePrivilegedAccessGroup end processing.
```

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.
> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.
```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.11.1                Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext…}
Script     2.11.1                Microsoft.Graph.Identity.Governance {Add-MgIdentityGovernanceAccessReviewDefinitionInstanceDecision, Get-MgAgreement, Get-MgAgreementAcceptance, Get-MgAgreementAcceptanceCo…
Script     2.11.1                Microsoft.Graph.Identity.SignIns    {Confirm-MgRiskyServicePrincipalCompromised, Confirm-MgRiskyUserCompromised, Get-MgDataPolicyOperation, Get-MgDataPolicyOperationCount…}
Script     2.11.1                Microsoft.Graph.Users               {Get-MgUser, Get-MgUserCount, Get-MgUserCreatedObject, Get-MgUserCreatedObjectAsServicePrincipal…}
```

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.
```
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by bernardw1** [comment]
I just ran into the same issue 

Get-MgIdentityGovernancePrivilegedAccess -debug
DEBUG: [CmdletBeginProcessing]: - Get-MgIdentityGovernancePrivilegedAccess begin processing with parameterSet 'Get'.
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.
DEBUG: [Authentication]: - Scopes: [Calendars.Read, Calendars.Read.Shared, Calendars.ReadBasic, Calendars.ReadWrite, Device.ReadWrite.All, DeviceManagementManagedDevices.ReadWrite.All, DeviceManagementServiceConfig.ReadWrite.All, Directory.AccessAsUser.All, Directory.Read.All, Directory.ReadWrite.All, email, Group.Read.All, Group.ReadWrite.All, GroupMember.Read.All, GroupMember.ReadWrite.All, openid, profile, RoleManagement.Read.Directory, RoleManagement.ReadWrite.Directory, Team.ReadBasic.All, TeamSettings.Read.All, TeamSettings.ReadWrite.All, TeamworkDevice.Read.All, User.Read, User.Read.All, User.ReadWrite, User.ReadWrite.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/identityGovernance/privilegedAccess

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.17763; en-US),PowerShell/7.4.1
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell/2.12.0
client-request-id             : efedcc4f-7608-42f3-920d-b9a21bf457c7

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : private
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : a0ef3629-9f7c-4891-ad11-e8663895b398
client-request-id             : efedcc4f-7608-42f3-920d-b9a21bf457c7
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Central US","Slice":"E","Ring":"2","ScaleUnit":"004","RoleInstance":"DS2PEPF000032F1"}}
Date                          : Thu, 01 Feb 2024 18:40:43 GMT

Body:
{
  "error": {
    "code": "UnknownError",
    "message": "{\"errorCode\":\"MissingProvider\",\"message\":\"The provider is missing.\",\"instanceAnnotations\":[]}",
    "innerError": {
      "date": "2024-02-01T18:40:43",
      "request-id": "a0ef3629-9f7c-4891-ad11-e8663895b398",
      "client-request-id": "efedcc4f-7608-42f3-920d-b9a21bf457c7"
    }
  }
}


Get-MgIdentityGovernancePrivilegedAccess_Get: {"errorCode":"MissingProvider","message":"The provider is missing.","instanceAnnotations":[]}

Status: 400 (BadRequest)
ErrorCode: UnknownError
Date: 2024-02-01T18:40:43

Headers:
Cache-Control                 : private
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : a0ef3629-9f7c-4891-ad11-e8663895b398
client-request-id             : efedcc4f-7608-42f3-920d-b9a21bf457c7
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Central US","Slice":"E","Ring":"2","ScaleUnit":"004","RoleInstance":"DS2PEPF000032F1"}}
Date                          : Thu, 01 Feb 2024 18:40:43 GMT

DEBUG: [CmdletEndProcessing]: - Get-MgIdentityGovernancePrivilegedAccess end **processing.**




 get-module microsoft.Graph*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.0                Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext…}
Script     1.22.0                Microsoft.Graph.Authentication      {Find-MgGraphCommand, Find-MgGraphPermission}
Script     2.12.0                Microsoft.Graph.Beta.Identity.Gove… {Add-MgBetaAccessReviewDecision, Add-MgBetaAccessReviewInstanceDecision,…
Script     2.12.0                Microsoft.Graph.Groups              {Add-MgGroupDriveListContentTypeCopy, Add-MgGroupDriveListContentTypeCop…
Script     2.12.0                Microsoft.Graph.Identity.Governance {Add-MgIdentityGovernanceAccessReviewDefinitionInstanceDecision, Get-MgA…
Script     2.12.0                Microsoft.Graph.Users               {Get-MgUser, Get-MgUserCount, Get-MgUserCreatedObject, Get-MgUserCreated…



`$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0`

**Comment by rpstester** [comment]
I have the same issue on Graph v 2.13.1.

**Comment by timayabi2020** [comment]
Hi @bridystone 
From the debug log, this seems to be a service issue and unfortunately for API related issues/questions we are not best placed to give an answer. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.

**Comment by mark3grahams** [comment]
Anything further?

**Comment by frazhamid** [comment]
Whilst I acknowledge that this issue is closed, I would also be interested to hear from anyone in the community who can advise on whether there is a fix or workaround for this logged issue.

**Comment by o-l-a-v** [comment]
Workaround:

```pwsh
$PimGroups = [array](
    (Invoke-MgGraphRequest -Method 'Get' -Uri 'https://graph.microsoft.com/beta/privilegedAccess/aadGroups/resources').'value'
)
```

**Comment by KonTheCat** [comment]
> Workaround:
> 
> ```powershell
> $PimGroups = [array](
>     (Invoke-MgGraphRequest -Method 'Get' -Uri 'https://graph.microsoft.com/beta/privilegedAccess/aadGroups/resources').'value'
> )
> ```
> 
> About:
> 
> * `Invoke-MgGraphRequest`: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.authentication/invoke-mggraphrequest

Thank you for this @o-l-a-v
