### ISSUE TITLE
Having a markdown document in this repo that shows how to use common odata query parameters with this module bundle would be most helpful

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#256]
The syntax differences between Graph and PowerShell, combined with various query parameters being supported, others not supported, make it difficult to know what is possible/supported/working already and what is not yet working, without having to browse through logged issues and manually try to piece that information together.

It would be great to have a document that lists odata query parameters with their PowerShell Graph parameter equivalent (including aliases), and shows examples how they could be used. Something like https://developer.microsoft.com/en-us/graph/docs/overview/query_parameters, but specific to this module bundle is what I had in mind. Starting much smaller than that document is fine, I'm just looking for a base set of examples to work with, ideally with links to open tickets if there are open issues that people can track to see when they are resolved. 
[AB#7410](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7410)

**Comment by MIchaelMainer** [comment]
Related to #257

**Comment by peombwa** [comment]
Something like this https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2Fbeta&view=graph-rest-beta but for Microsoft Graph PowerShell SDK.

**Comment by maisarissi** [comment]
Content around query parameters available in the Microsoft Graph PowerShell SDK online documentation: https://learn.microsoft.com/en-us/powershell/microsoftgraph/use-query-parameters?view=graph-powershell-1.0
