### ISSUE TITLE
Get-MgBookingBusinessService - Intermittent HTTP 500 Errors

### ISSUE THREAD

**Issue by YuriySamorodov** [microsoftgraph/msgraph-sdk-powershell#2567]
**Describe the bug**
Me and many of my colleagues are experiencing totally random HTTP 500 errors when running MgGraph and MgBetaGraph cmdlets. No correlation noticed.
Sometimes it takes up to a few minutes for Graph commands to complete (tested this with Graph Explorer)

**To Reproduce**
1. Authenticate as a user with ```Connect-MgGraph```
2. Create a booking mailbox with ```$mailbox = New-MgBetaBookingBusiness```
3. Create a booking staff with ```New-MgBetaBookingBusinessStaff```
4. Call for a default service with ```$service = Get-MgBookingBusinessService -BookingBusiness $mailbox.id
5. You may get an error below:
```
Status: 500 (InternalServerError)
ErrorCode: UnknownError
Date: 2024-02-06T02:13:13
 
Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : d48b357b-d8a2-4cc2-900f-747f27082512
client-request-id             : 9b939233-18da-459d-801e-94e4b66340d6
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Germany West Central","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"FR1PEPF000007AC"}}
Date                          : Tue, 06 Feb 2024 02:13:13 GMT
```
6. However, when you run ```$service``` it would return created object.

**Expected behavior**
HTTP 500 Errors definitely are not expected

**Module Version**
MG Graph 2.12.0

**Environment Data**
```
Name                           Value
----                           -----
PSVersion                      7.3.11
PSEdition                      Core
GitCommitId                    7.3.11
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Screenshots**
<img width="1294" alt="CleanShot 2024-02-06 at 06 16 20" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/5260172/403c0733-97fd-46c6-8dff-a9b5f6833a4e">

**Comment by calebkiage** [comment]
Hello @YuriySamorodov, HTTP 500 errors point to an issue in the service itself. To get support on service issues, please open an issue on their support page https://developer.microsoft.com/en-us/graph/support
