### ISSUE TITLE
Get-MgBetaIdentityGovernancePrivilegedAccess(Group) missing provider

### ISSUE THREAD

**Issue by rpstester** [microsoftgraph/msgraph-sdk-powershell#2579]
**Describe the bug**
Get-MgBetaIdentityGovernancePrivilegedAccess returns an error: 
{"errorCode":"MissingProvider","message":"The provider is missing.","instanceAnnotations":[]}
Status: 400 (BadRequest)
ErrorCode: UnknownError
Same error for Get-MgBetaIdentityGovernancePrivilegedAccessGroup

**To Reproduce**
1. Connect-MgGraph
2. Get-MgBetaIdentityGovernancePrivilegedAccess or Get-MgBetaIdentityGovernancePrivilegedAccessGroup

**Expected behavior**
Output one or more Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphPrivilegedAccessRoot or Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphPrivilegedAccessGroup

**Debug Output**
Get-MgBetaIdentityGovernancePrivilegedAccess -debug
DEBUG: [CmdletBeginProcessing]: - Get-MgBetaIdentityGovernancePrivilegedAccess begin processing with parameterSet 'Get'.
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.
DEBUG: [Authentication]: - Scopes: [AdministrativeUnit.Read.All, AdministrativeUnit.ReadWrite.All, Directory.Read.All, Group.Read.All, Group.ReadWrite.All, openid, PrivilegedAccess.ReadWrite.AzureADGroup, PrivilegedAssignmentSchedule.ReadWrite.AzureADGroup, profile, RoleAssignmentSchedule.ReadWrite.Directory, RoleEligibilitySchedule.ReadWrite.Directory, RoleManagement.ReadWrite.Directory, User.Read, User.Read.All, User.ReadWrite.All, email].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/beta/identityGovernance/privilegedAccess

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.19045; en-US),PowerShell/2024.0.0
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell-beta/2.13.1
client-request-id             : d96e860f-e3b0-478b-a66f-40b63661c8bc

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : private
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 435704f6-e222-407a-8255-7f4d15eb1e28
client-request-id             : d96e860f-e3b0-478b-a66f-40b63661c8bc
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"3","ScaleUnit":"002","RoleInstance":"CH01EPF0002F373"}}
Date                          : Fri, 09 Feb 2024 19:41:18 GMT

Body:
{
  "error": {
    "code": "UnknownError",
    "message": "{\"errorCode\":\"MissingProvider\",\"message\":\"The provider is missing.\",\"instanceAnnotations\":[]}",
    "innerError": {
      "date": "2024-02-09T19:41:18",
      "request-id": "435704f6-e222-407a-8255-7f4d15eb1e28",
      "client-request-id": "d96e860f-e3b0-478b-a66f-40b63661c8bc"
    }
  }
}

Get-MgBetaIdentityGovernancePrivilegedAccess_Get: {"errorCode":"MissingProvider","message":"The provider is missing.","instanceAnnotations":[]}

Status: 400 (BadRequest)
ErrorCode: UnknownError
Date: 2024-02-09T19:41:18

Headers:
Cache-Control                 : private
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 435704f6-e222-407a-8255-7f4d15eb1e28
client-request-id             : d96e860f-e3b0-478b-a66f-40b63661c8bc
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"3","ScaleUnit":"002","RoleInstance":"CH01EPF0002F373"}}
Date                          : Fri, 09 Feb 2024 19:41:18 GMT

DEBUG: [CmdletEndProcessing]: - Get-MgBetaIdentityGovernancePrivilegedAccess end processing.

**Module Version**
ModuleType Version Name                                     prerelease
    Script 2.13.1  Microsoft.Graph.Authentication
    Script 2.13.1  Microsoft.Graph.Beta.Identity.Governance
    Script 2.13.1  Microsoft.Graph.DirectoryObjects
    Script 2.13.1  Microsoft.Graph.Groups
    Script 2.13.1  Microsoft.Graph.Identity.Governance
    Script 2.13.1  Microsoft.Graph.Users

**Environment Data**
Name                           Value
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by timayabi2020** [comment]
Hi @rpstester thank you for logging this issue. Based on your debug information, this appears to be a service issue. 
For API related issues/questions we are not best placed to give an answer. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.

**Comment by majesticpancake** [comment]
I am also experiencing this issue as of today using version 2.17.0 of both the stable and beta versions of the module. If the original poster is not available, I can provide additional information.
