### ISSUE TITLE
ETA for 0.7.0 release?

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#258]
I suspect the answer for this is "any time now", but since I'm building product against this module bundle right now, and since I need some of the functionality in the 0.7.0 release for the product I'm working on, while working under tight deadlines, knowing when you expect to publish it would be helpful. Can anyone let me know when you hope to publish the 0.7.0 update to the PowerShell Gallery?

**Comment by ddyett** [comment]
hi Kirk we are looking at putting something out in the next week or so?  Which specific thing are you looking for?

**Comment by KirkMunro** [comment]
Paged data retrieval (e.g. Get-MgUser using -Top and -Skip to get all users in a large organization that has more than 999 users). This is a critical need for the product that I'm building, and we have a similar "in the next week or so" initial beta release that we're driving towards.

**Comment by ddyett** [comment]
yes paging should be coming out shortly.  And we are looking at an invoke request cmdlet possibly in 0.9.
