### ISSUE TITLE
Install-Module Microsoft.Graph does not install all depenences

### ISSUE THREAD

**Issue by jagrock** [microsoftgraph/msgraph-sdk-powershell#259]
Version 0.5.1

Installing from the PSGallery does not install all dependences.  There isn't a listing of the ones it should install.  A notable one not installed is: **Microsoft.Graph.Users.User**.  This means the Get-MgUser cmdlet isn't available as shown in the samples.

**These are the ones it installed**
Microsoft.Graph.Analytics
Microsoft.Graph.Authentication
Microsoft.Graph.CloudCommunications
Microsoft.Graph.Files.Drives
Microsoft.Graph.Files.Shares
Microsoft.Graph.Groups.Calendar
Microsoft.Graph.Groups.DirectoryObject
Microsoft.Graph.Groups.Endpoint
Microsoft.Graph.Groups.Extension
Microsoft.Graph.Groups.LifecyclePolicies
Microsoft.Graph.Groups.Planner
Microsoft.Graph.Identity.AdministrativeUnits
Microsoft.Graph.Identity.Application
Microsoft.Graph.Identity.ConditionalAccess
Microsoft.Graph.Identity.Devices
Microsoft.Graph.Identity.DirectorySettings
Microsoft.Graph.Identity.DirectorySettingTemplates
Microsoft.Graph.Identity.SubscribedSkus
Microsoft.Graph.Identity.TermsOfUse
Microsoft.Graph.Identity.UserFlows
Microsoft.Graph.OnlineMeetings
Microsoft.Graph.Places
Microsoft.Graph.Planner
Microsoft.Graph.Sites.Actions
Microsoft.Graph.Sites.Pages
Microsoft.Graph.Sites.Site
Microsoft.Graph.Teams.Team
Microsoft.Graph.Users.Calendar
Microsoft.Graph.Users.DirectoryObject
Microsoft.Graph.Users.Extensions
Microsoft.Graph.Users.Groups
Microsoft.Graph.Users.ProfilePhoto

**These are the ones it didn't install.**
Microsoft.Graph.Bookings
Microsoft.Graph.DevicesApps.DeviceAppManagement
Microsoft.Graph.DevicesApps.MobileAppManagement
Microsoft.Graph.DevicesApps.OfficeConfiguration
Microsoft.Graph.DevicesApps.SharedResources
Microsoft.Graph.Education
Microsoft.Graph.Files.Permissions
Microsoft.Graph.Financials
Microsoft.Graph.Groups.Actions
Microsoft.Graph.Groups.Conversation
Microsoft.Graph.Groups.ConversationThread
Microsoft.Graph.Groups.Drive
Microsoft.Graph.Groups.Functions
Microsoft.Graph.Groups.Group
Microsoft.Graph.Groups.OneNote
Microsoft.Graph.Groups.ProfilePhoto
Microsoft.Graph.Groups.Site
Microsoft.Graph.Identity.AccessReview
Microsoft.Graph.Identity.AppRoleAssignments
Microsoft.Graph.Identity.AuditLogs
Microsoft.Graph.Identity.AuthenticationMethods
Microsoft.Graph.Identity.AzureADPIM
Microsoft.Graph.Identity.CertificateBasedAuthConfiguration
Microsoft.Graph.Identity.Contracts
Microsoft.Graph.Identity.DataPolicyOperations
Microsoft.Graph.Identity.Directory
Microsoft.Graph.Identity.DirectoryObjects
Microsoft.Graph.Identity.DirectoryRoles
Microsoft.Graph.Identity.DirectoryRoleTemplates
Microsoft.Graph.Identity.Domains
Microsoft.Graph.Identity.Invitations
Microsoft.Graph.Identity.OAuth2PermissionGrants
Microsoft.Graph.Identity.OnPremisesPublishingProfiles
Microsoft.Graph.Identity.Organization
Microsoft.Graph.Identity.OrganizationContacts
Microsoft.Graph.Identity.Policies
Microsoft.Graph.Identity.Protection
Microsoft.Graph.Identity.Providers
Microsoft.Graph.Identity.RoleManagement
Microsoft.Graph.Identity.ServicePrincipal
Microsoft.Graph.Identity.TrustFramework
Microsoft.Graph.Intune
Microsoft.Graph.Notification
Microsoft.Graph.Reports
Microsoft.Graph.SchemaExtensions
Microsoft.Graph.Search
Microsoft.Graph.Security
Microsoft.Graph.Sites.Drive
Microsoft.Graph.Sites.Functions
Microsoft.Graph.Sites.List
Microsoft.Graph.Sites.OneNote
Microsoft.Graph.Subscriptions
Microsoft.Graph.Teams.AppCatalogs
Microsoft.Graph.Teams.Channel
Microsoft.Graph.Teams.Chats
Microsoft.Graph.Teams.Teamwork
Microsoft.Graph.Users.Actions
Microsoft.Graph.Users.ActivityFeed
Microsoft.Graph.Users.Contacts
Microsoft.Graph.Users.Devices
Microsoft.Graph.Users.Drive
Microsoft.Graph.Users.FollowedSites
Microsoft.Graph.Users.Functions
Microsoft.Graph.Users.InformationProtection
Microsoft.Graph.Users.LicenseDetails
Microsoft.Graph.Users.Mail
Microsoft.Graph.Users.OneNote
Microsoft.Graph.Users.OutlookUser
Microsoft.Graph.Users.People
Microsoft.Graph.Users.Planner
Microsoft.Graph.Users.User
Microsoft.Graph.Users.UserSettings

**Comment by ddyett** [comment]
see samples/0-InstallModule.ps1 for uninstall instructions.

**Comment by jagrock** [comment]
I did uninstall and install a couple of times.  The last 2 times had the same results.  The first time didn't have all either, but I didn't capture how many it had.  It did not have Microsoft.Graph.Users.User either.  This is what made me begin trouble shooting.

The uninstall doesn't remove all modules either.

**Comment by peombwa** [comment]
This issue shouldn't exist in v1. Use `Install-Module Microsoft.Graph -AllowClobber -Force` if you are upgrading from a preview version.

Feel free to open a new issue if this issue still occurs in v1.1.0 of the SDK.
