### ISSUE TITLE
Connect-Graph with invalid scopes causes device code flow error to hang terminal

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#26]
If the device code flow fails for some reason, it leaves the powershell window in a hung state that there seems to be no way of recovering from.

**Comment by peombwa** [comment]
Try using PowerShell's `Write-Host` as opposed to C#'s `Console.WriteLine` to log the device code.

**Comment by peombwa** [comment]
This can be resolved by introducing a timeout value lower than MSAL's default via a CancellationToken. The default timeout that's returned by the server is ~15 minutes. The same timeout applies to invalid scopes, and the terminal will wait for ~15 mins.

Ref: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow#code-snippet

**Comment by darrelmiller** [comment]
It doesn't hang anymore, now we get this error immediately
     connect-graph : Verification code expired before contacting the server
