### ISSUE TITLE
 Get-MgUserAuthenticationMethod* - Request Authorization failed

### ISSUE THREAD

**Issue by phl0x1** [microsoftgraph/msgraph-sdk-powershell#2602]
Get-MgUserAuthenticationMethod* commands are failing with error "Request Authorization failed" even with Global Admin priviliges. Tried in PS 5 and 7.4.

**To Reproduce**
1. Connect-mggraph
2.  Get-MgUserAuthenticationMethod -userid "id"
2. See error at `Get-MgUserAuthenticationWindowHelloForBusinessMethod : Request Authorization failed
At line:1 char:1
+ Get-MgUserAuthenticationWindowHelloForBusinessMethod -UserId "8e48aa2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = 8e48...ndProperty =  }:<>f__AnonymousType93`9) [Get-MgUser
   Authe...essMethod_List1], RestException`1
    + FullyQualifiedErrorId : accessDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgUserAuthenticationWindowHelloForBus
   inessMethod_List1`

**Module Version**
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.14.0                Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-…}
Script     2.14.0                Microsoft.Graph.Identity.SignIns    {Confirm-MgRiskyServicePrincipalCompromised, Conf…}

**Environment Data**
Name                           Value
----                           -----
PSVersion                      7.4.1

**Comment by SeniorConsulting** [comment]
Hi Phl0x1, what scopes are you using when you connect?

If you run
`(Get-MgContext).Scopes`

What do you see?

The permissions required to use that cmdlet are one of the following:
- UserAuthenticationMethod.Read
- UserAuthenticationMethod.Read.All
- UserAuthenticationMethod.ReadWrite
- UserAuthenticationMethod.ReadWrite.All

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/4f1f6e6d-3b94-4d6b-9e30-84e11934cbc9)
