### ISSUE TITLE
Update-MgDevice - Cannot Disable a non-Windows device in Entra ID using PowerShell

### ISSUE THREAD

**Issue by joshuahipple** [microsoftgraph/msgraph-sdk-powershell#2603]
Summary:
My goal is to disable a non-Windows device in Entra ID using PowerShell.  AzureAD modules work fine but the Graph modules fail.

Connection info:
Keeping it simple I am running this with an interactive PowerShell session with my user account and PIM roles properly activated.

AuthType               : Delegated
TokenCredentialType    : InteractiveBrowser
AppName                : Microsoft Graph Command Line Tools
ContextScope           : CurrentUser

The following PowerShell code using the AzureAD modules works just fine:

```
#Entra ID Object ID for non-Windows device
$ID = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#Legacy AzureAD command works just fine
Set-AzureADDevice -ObjectId $ID -AccountEnabled $false -Verbose
```

The following command using the Graph modules fails:

```
#Entra ID Object ID for non-Windows device
$ID = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
Update-MgDevice -DeviceId $ID -AccountEnabled:$false
```

**Error message:**
_Update-MgDevice : Properties other than ExtendedAttribute1..15 can be modified only on windows devices.
Status: 400 (BadRequest)
ErrorCode: Request_BadRequest_

My goal was to get this code working properly via an interactive session prior to migrating it to a registered application-based method.  AzureAD modules will be retired by Microsoft this year so want to plan to migrate to Graph.  Based on what I have read in these links there is still some issues with delegated app permissions:
https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2066
https://developer.microsoft.com/en-us/graph/known-issues/?search=17346

**Comment by timayabi2020** [comment]
Hi @joshuahipple thank you for identifying and logging this issue.  Unfortunately this is a known API issue as per the documentation [here](https://learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-1.0&tabs=http)
<img width="409" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/48e56aba-7cfc-457f-b429-a2d727d43fc8">.
However, you can try using delegated permissions (authenticate as a user) to update the property on a non-Windows device.

**Comment by PeterKlapwijk** [comment]
Can this please be re-opened as this issue is not solved. I have the same issue and it seems more people are having the issue.

**Comment by jvplopper** [comment]
Just ran into this issue today while working on some automation scripts for stale devices.  I'm using application permissions and unable to disable a non-Windows device.  Using the same perms I can delete that device, however.   This seems like a very odd limitation.

**Comment by milosbithawk** [comment]
I have the same issue, will this be solved?
