### ISSUE TITLE
Get-MGUser Strong Authentication methods

### ISSUE THREAD

**Issue by arvindsindhu** [microsoftgraph/msgraph-sdk-powershell#261]
I am looking for a solution to automatically download MFA Settings, such as MFA Registered information. and Set/Update MFA Mobile number for user's, But **Get-MgUser -UserId  | Select-Object Authentication -ExpandProperty Authentication | FL** is not returning anything. 

![image](https://user-images.githubusercontent.com/51983088/84601534-86ed8400-ae9e-11ea-9c87-bd226359c43f.png)

**Comment by MIchaelMainer** [comment]
Can you post this question to StackOverflow, and then provide a link to it in this issue?

**Comment by peombwa** [comment]
You can use `Get-MgUserAuthenticationPhoneMethod -UserId` to get a user's MFA settings as described in the docs https://docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&tabs=http.
