### ISSUE TITLE
 Set-MgUserPhotoContent (see below) - Registry error and Remove-MgUserPhoto - Cmdlet unavailable

### ISSUE THREAD

**Issue by zemuldo** [microsoftgraph/msgraph-sdk-powershell#2619]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

See original post [How to fix weird registry error when using PowerShell Graph SDK to update a user's profile photo](https://learn.microsoft.com/en-us/answers/questions/1598982/how-to-fix-weird-registry-error-when-using-powersh)

**Describe the bug**
Problems seen so far in Graph module v2.15.0 (not seen in v2.10.0):

Error when running Set-MgUserPhotoContent (see below) - Registry error
Error when running Remove-MgUserPhoto - Cmdlet unavailable

**To Reproduce**
Execute any of the Cmdlets using version 2,15.0.

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Debug Output**
 Problems seen so far in Graph module v2.15.0 (not seen in v2.10.0):

Error when running Set-MgUserPhotoContent (see below) - Registry error
Error when running Remove-MgUserPhoto - Cmdlet unavailable

**Module Version**
v2.15.0 

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by mike9701** [comment]
> @zemuldo thank you for logging this issue. However, I am not able to see the screenshots that you intended to share. I am also not able to reproduce the issue related to `Set-MgUserPhotoContent` executed without any error. <img alt="image" width="1271" src="https://private-user-images.githubusercontent.com/10947120/309779192-1416304a-14fd-454c-b8f8-7ebb9aebdc39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTE5OTYsIm5iZiI6MTcwOTcxMTY5NiwicGF0aCI6Ii8xMDk0NzEyMC8zMDk3NzkxOTItMTQxNjMwNGEtMTRmZC00NTRjLWI4ZjgtN2ViYjlhZWJkYzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA3NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMjhhZDliMzUxZGQwYmM2MjEwYTJlYTIxMjFhOGNjY2ZjYzhkYzM2OTZlZTM1N2U2MDc3OTdkZGVhMDM5ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jSnivIceMxXDgFEgOpMRUDxq_gfhJHcPciCXRn0FRgY"> <img alt="image" width="1266" src="https://private-user-images.githubusercontent.com/10947120/309779320-ce3665d8-c2e2-48e5-a719-49299a987717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTE5OTYsIm5iZiI6MTcwOTcxMTY5NiwicGF0aCI6Ii8xMDk0NzEyMC8zMDk3NzkzMjAtY2UzNjY1ZDgtYzJlMi00OGU1LWE3MTktNDkyOTlhOTg3NzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA3NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZmRiZjkyNWU0YWNhNWFlNzFkMDllZDg0MDdkZWZiZDZlYTc4ODE5MDA2OThjZjM4MGQwNzc0NzBlMWVhMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I5gk3ecdO72sL-u4Cle-nFVb-ktfBcmbhXq3_hR5E-g">
> 
> As for `Remove-MgUserPhoto` there is already a similar issue being tracked [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2613).


Hello @timayabi2020, i had this error also on the 2.15.0. 
Then i found this thread here: https://learn.microsoft.com/en-us/answers/questions/1598982/how-to-fix-weird-registry-error-when-using-powersh

and thats why i ended up downgrading to 2.10.0 again, where everything seems fine.

greetings
Mike
