### ISSUE TITLE
Get-MgDeviceAppManagementMobileApp does not list all apps

### ISSUE THREAD

**Issue by Nouneds** [microsoftgraph/msgraph-sdk-powershell#2628]
Get-MgDeviceAppManagementMobileApp command does not return full list of intune applications on tenant. Microsoft Store ( new ) apps are not visible on the list. Providing -ID argument with this application id works fine. 

**To Reproduce**
1. Execute Get-MgDeviceAppManagementMobileApp
2. No app that is created through Microsoft store (new) option is visible on the list. I've created visual studio code application in intune through GUI and its not searchable through script if i do not point at its ID

**Expected behavior**
All applications should be listed

**Module Version**
All modules are up to date 2.15.0

**Comment by SeniorConsulting** [comment]
Hi Nouneds,

I've headed over to Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer) to see if this is a problem with the API or the PowerShell SDK. The URI/query I ran was:
`https://graph.microsoft.com/v1.0/deviceAppManagement/mobileApps`

(per https://learn.microsoft.com/en-us/graph/api/intune-apps-webapp-list?view=graph-rest-1.0&tabs=http).

From the looks of things from my tenant, the API isn't returning all of the results (just as you've suggested it won't). Feel free to have a go yourself. Consequently, I think you'd be better off using https://developer.microsoft.com/en-us/graph/support to get support for this one, as it's not a Powershell SDK issue.
