### ISSUE TITLE
Authentication Methods - Incorrect Required Permissions from Find-MgGraphCommand

### ISSUE THREAD

**Issue by tbisque** [microsoftgraph/msgraph-sdk-powershell#2631]
**Describe the bug**
> `Get-MgPolicyAuthenticationMethodPolicy` & `Get-MgBetaPolicyAuthenticationMethodPolicy` both show only `Policy.ReadWrite.AuthenticationMethod` as the required permission. In reality, `UserAuthenticationMethod.Read.All` will also allow the ability to execute these cmdlets.

**To Reproduce**
1. Execute `Find-MgGraphCommand -Uri "/policies/authenticationMethodsPolicy" -Method GET`
2. Observe the `Permissions` property returned containing only `Policy.ReadWrite.AuthenticationMethod`
3. Execute `Connect-MgGraph -Scopes UserAuthenticationMethod.Read.All`
4. Confirm ability to still execute `Get-MgPolicyAuthenticationMethodPolicy` & `Get-MgBetaPolicyAuthenticationMethodPolicy` with this more restrictive scope

**Expected behavior**
> `Find-MgGraphCommand` & learn articles should reflect the ability to use this scope with more restrictive API permissions.

**Debug Output**
> N/A

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.
> `2.15.0`

**Environment Data**
> Name                           Value
> PSVersion                      7.4.1
> PSEdition                      Core
> GitCommitId                    7.4.1
> OS                             Microsoft Windows 10.0.22631
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0

**Screenshots**
> 

**Additional context**
>

**Comment by SeniorConsulting** [comment]
Curious. The API documentation doesn't list this as you've described:
https://learn.microsoft.com/en-us/graph/api/authenticationmethodspolicy-get?view=graph-rest-1.0&tabs=http

I also wasn't able to replicate what you were describing (and got a 403).
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/af10b07f-3303-4f9a-beff-cff218c4d43e)



If you run `(Get-MgContext).Scopes`, check that it hasn't already retained your previous scopes (including Policy.ReadWrite.AuthenticationMethod).

**Comment by tbisque** [comment]
@SeniorConsulting, worth noting that I was using an Azure (US) Gov tenant for the testing above. That's a good idea though. I will confirm the scopes were cleared with a `Disconnect-MgGraph`!

**Comment by timayabi2020** [comment]
@tbisque, I also checked the permissions defined in the API [reference doc](https://learn.microsoft.com/en-us/graph/api/authenticationmethodspolicy-get?view=graph-rest-1.0&tabs=http) for that path. They are the same as what is returned by ``Find-MgGraphCommand``
<img width="634" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/828bc309-f426-4f56-a298-75ecb14aa2f2">

**Comment by tbisque** [comment]
@timayabi2020, what I'm trying to say is that both are missing `UserAuthenticationMethod.Read.All`

**Comment by timayabi2020** [comment]
Hi @tbisque apologies for misinterpreting the issue. For the missing scope, kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.
