### ISSUE TITLE
Get-MgGroupMemberCount returns object instead of int

### ISSUE THREAD

**Issue by joergrenn** [microsoftgraph/msgraph-sdk-powershell#2633]
Hello,

I have an issue with Get-MgGroupMemberCount. 
According to the [documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/get-mggroupmembercount?view=graph-powershell-1.0#outputs) it is supposed to return an int32, but instead it returns an object.

> $count = Get-MgGroupMemberCount -GroupId "d2c75a71-97ad-4950-bbb4-d08fa0d53004" -ConsistencyLevel eventual
 $count.GetType()                                                                                          
<img width="569" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/62641471/84f2899f-c411-4225-997e-1561db3f065a">

How can I get only the number from that object?
When I try to put it into a string I get the object instead of the number.

> $count.ToString()  
System.Object[]

**Comment by joergrenn** [comment]
To answer my own question, Get-MgGroupMemberCount returns an array.
The first array member is the actual count and the second mebers seems to be request properties

> $count[0]
54
$count[1]
<img width="376" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/62641471/556d0f4f-6cb4-4066-9284-8047a43cbe31">

This does look like a bug to me?
Can someone check if this is the expected behavior? If yes then this can be closed. If no, do I need to create a bug report?

**Comment by timayabi2020** [comment]
Hi @joergrenn
Thank you for noticing and reporting this issue. I have tried it with the latest release (2.16.0) and it returns an ``Int32``. Please install the latest SDK.
<img width="634" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/124a5b9a-ac8a-4d11-873e-4a418bc66dd3">
