### ISSUE TITLE
Remove-MgGroupPhoto not recognized in Microsoft.Graph.Groups version 2.13 and higher

### ISSUE THREAD

**Issue by mastachon** [microsoftgraph/msgraph-sdk-powershell#2642]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
After updating to version 2.13.0 of the Microsoft.Graph.Groups module, the Remove-MgGroupPhoto command is no longer recognized. The Get-Command cmdlet returns null when attempting to find the command within the module.
Get-Command -Module Microsoft.Graph.Groups | ?{$_.Name -eq 'Remove-MgGroupPhoto'}

**To Reproduce**
1. Install Microsoft.Graph.Groups V2.13.0 or grater.
2. Execute Remove-MgGroupPhoto.

**Expected behavior**
Remove-MgGroupPhoto is decected and working.

**Module Version**
Microsoft.Graph.Groups: 2.13.0 - 2.16.0

**Environment Data**
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional context**
The current workaround is to either downgrade the module to version 2.12.0 or use the 'Invoke-MgGraphRequest' command instead.

**Comment by timayabi2020** [comment]
Issue resolved by 2.17.0 release.
