### ISSUE TITLE
``Set-MgUserPhotoContent`` not working in PowerShell 5

### ISSUE THREAD

**Issue by timayabi2020** [microsoftgraph/msgraph-sdk-powershell#2645]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
> The command fails with missing assembly error ``Microsoft.Win32.Registry.dll`` when used in a PowerShell 5 environment.

**To Reproduce**
1. Open PowerShell 5
2. Connect to graph using ``connect-mggraph -scopes "ProfilePhoto.ReadWrite.All,User.ReadWrite,User.ReadWrite.All"``
3. Execute ``Set-MgUserPhotoContent -UserId <UserId> -InFile "<Path to your image file>"``

**Expected behavior**
> No error thrown

**Debug Output**

**Module Version**
2.16.0

**Environment Data**
PowerShell 5

**Screenshots**
> <img width="827" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/452eff8a-00c4-4991-af45-3d227b776786">

**Additional context**
> The cmdlet works in PowerShell 7

**Comment by MaKraMc** [comment]
I have the same Issue. Using module version 2.12.0 has worked fine for me.

**Comment by MaKraMc** [comment]
There is also a discussion about this over on [microsoft learn](https://learn.microsoft.com/en-us/answers/questions/1598982/how-to-fix-weird-registry-error-when-using-powersh).

**Comment by timayabi2020** [comment]
Thanks @MaKraMc, we are working to resolve the issue.
