### ISSUE TITLE
An important question about paging results in the 0.7.0 release

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#266]
Now that 0.7.0 has shipped (thank you for that!), I see you've moved forward with a common `-All` parameter to retrieve paged data. That's great, but I need a few questions answered to make sure I understand how this works:

1. When you use `-All`, presumably behind the scenes the Graph module bundle is sending multiple requests to the appropriate REST endpoint to retrieve data pages, and returning those data pages to the caller via the pipeline as soon as they are ready, as opposed to bottlenecking the entire collection in memory and returning it only once it has all been retrieved. Can someone confirm whether or not this is the current design? If not, I have a design bug to log.

1. If you specify a page size using `-PageSize`, `-All` doesn't work, but it should. For example, I wanted to test the paging feature, and see if I actually get all data, but in my test tenant right now I don't have enough users to force paging to happen. I can create those users and then test this out, but instead I thought I'd try just forcing a page size, so I ran this:

    `Get-MgUser -PageSize 10 -All`

    That command only returned 10 users back to me, so you're not properly supporting paging in the Graph module bundle yet. Being able to control the page size while still being able to retrieve all data is important because if you are properly streaming out the pages (question 1, above), it allows me to get data in chunks of a size that is appropriate for my application. Can someone please confirm that you understand and agree with this need, and put it on your roadmap?

**Comment by peombwa** [comment]
@KirkMunro, thanks for the valuable feedback. To answer your questions:
1. Yes, `-All` sends the page collection to the pipe as soon as they are ready, we don't hold them in memory.
2. This is indeed missing, but it will be available in the next release. The initial implementation was primarily driven by option 2 in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/11#issuecomment-600790992. Allowing customers to specify their preferred `pageSize` as they iterate through a collection is a legitimate ask and we will prioritize it. I've created https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/271 to track this issue.

**Comment by KirkMunro** [comment]
Closed since you answered all of my questions. Thanks!
