### ISSUE TITLE
Remove-MgGroupMemberByRef 2.17.0 missing DirectoryObjectId parameter

### ISSUE THREAD

**Issue by WillPowerIsAll** [microsoftgraph/msgraph-sdk-powershell#2670]
**Describe the bug**
> The parameter **-DirectoryObjectId** is not available with the command **Remove-MgGroupMemberByRef** in the module **Microsoft.Graph.Groups** 2.17.0. 

The  **Microsoft.Graph.Groups** 2.16.0 have the **-DirectoryObjectId** parameter.

**To Reproduce**
1. Open PowerShell 7.4.1 as a user
2. `Install-Module -Name Microsoft.Graph -MaximumVersion 2.17.0 -Force -Confirm:$false -Scope CurrentUser`
3. `Connect-MgGraph -Scopes "User.Read.All", "Group.Read.All", "GroupMember.Read.All", "GroupMember.ReadWrite.All"`
4. `Remove-MgGroupMemberByRef -GroupId 123 -DirectoryObjectId`
_Remove-MgGroupMemberByRef: A parameter cannot be found that matches parameter name 'DirectoryObjectId'._

**Expected behavior**
> The parameter **-DirectoryObjectId** is supposed to be available with the command **Remove-MgGroupMemberByRef** in the module **Microsoft.Graph.Groups** 2.17.0. 

**Module Version**
```
Get-Module Microsoft.Graph*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.17.0                Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext…}
Script     2.17.0                Microsoft.Graph.Groups              {Add-MgGroupDriveListContentTypeCopy, Add-MgGroupDriveListContentTypeCopyFromContentTypeHub, Add-MgGroupFavorite, Add-MgGroupSite…}
```

**Environment Data**
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Screenshots**
![MgGraphError](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/166463196/16788add-7b98-493d-a3a3-94cafc5cfc79)

**Comment by lorisAmbrozzo** [comment]
I'm facing the same problem.

**Comment by bhoogerv** [comment]
I am on 2.17 (psversion 5.1) and also have the issue.

**Comment by timayabi2020** [comment]
Hello @lorisAmbrozzo @WillPowerIsAll thank you for reporting this issue. After checking the paths in the open API file provided by the Microsoft Graph API owner, I noticed that `Remove-MgGroupMemberByRef` which transalates to `/groups/{group-id}/members/$ref` doesn't have a ``directoryObject-id`` parameter. See image below.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/e9ac1ab4-11b1-41de-84ec-3218f1feb721)

Further checks revealed that the API endpoint containing the missing parameter is `/groups/{group-id}/members/{directoryObject-id}/$ref` which transalates to `Remove-MgGroupMemberDirectoryObjectByRef` cmdlet. See image below.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/c98ab537-9244-4182-b1a7-2cf97a3e3ba8)

There for the correct cmdlets to use are `Remove-MgGroupMemberDirectoryObjectByRef` and Remove-MgBetaGroupMemberDirectoryObjectByRef

**Comment by bhoogerv** [comment]
Thank you, Remove-MgGroupMemberDirectoryObjectByRef is working nicely.

**Comment by LeonarddeR** [comment]
Is it normal for such backwards incompatible changes to be made to Graph without mentioning it in any release notes?

**Comment by kpinel** [comment]
Still seeing this in our Azure automation and the modules haven't been updated yet.
I need to schedule an outage to roll back our modules to 2.16

**Comment by salbeck-sit** [comment]
It's right here: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/remove-mggroupmemberdirectoryobjectbyref?view=graph-powershell-1.0

**Comment by vtancredi-PNC** [comment]
> Hello @lorisAmbrozzo @WillPowerIsAll thank you for reporting this issue. After checking the paths in the open API file provided by the Microsoft Graph API owner, I noticed that `Remove-MgGroupMemberByRef` which transalates to `/groups/{group-id}/members/$ref` doesn't have a `directoryObject-id` parameter. See image below.
> 
> ![image](https://private-user-images.githubusercontent.com/10947120/320760629-e9ac1ab4-11b1-41de-84ec-3218f1feb721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTgyODAsIm5iZiI6MTcxMzkxNzk4MCwicGF0aCI6Ii8xMDk0NzEyMC8zMjA3NjA2MjktZTlhYzFhYjQtMTFiMS00MWRlLTg0ZWMtMzIxOGYxZmViNzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAwMTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZjg5ODdiMDVhYzk0Nzg3N2M3YWYwMDdkMDA3MjVhNzQxMTkwY2Y0Yzc3MmE5NDFkODQ2MDJjNmM0ZGQ0NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQGklUZEaZcnXNSbYJnQTb2-0TyhyzRjHTXE9zrOvLg)
> 
> Further checks revealed that the API endpoint containing the missing parameter is `/groups/{group-id}/members/{directoryObject-id}/$ref` which transalates to `Remove-MgGroupMemberDirectoryObjectByRef` cmdlet. See image below. ![image](https://private-user-images.githubusercontent.com/10947120/320762286-c98ab537-9244-4182-b1a7-2cf97a3e3ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTgyODAsIm5iZiI6MTcxMzkxNzk4MCwicGF0aCI6Ii8xMDk0NzEyMC8zMjA3NjIyODYtYzk4YWI1MzctOTI0NC00MTgyLWIxYTctMmNmOTdhM2UzYmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAwMTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1N2Q4Y2MyNDkwYTNlMjY4YzgzNWVhNjAxN2FiYzViMGU2NjcwYjFkN2Y1MmRhODNkZDE5ODI4ZWRmMmY0ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wjK4V8h3ObUPEky2I_iBXahY76Vs5DdE7-OC9_o0XnQ)
> 
> There for the correct cmdlets to use are `Remove-MgGroupMemberDirectoryObjectByRef` and Remove-MgBetaGroupMemberDirectoryObjectByRef

Fantastic work, thank you, this works for me. Must be a recent change within the last 2 months because the old command used to work for me at that time.

**Comment by sjm12** [comment]
I am trying to use the Remove-MgGroupMemberDirectoryObjectByRef -GroupId $groupId -DirectoryObjectId $userId to remove users from a group. It works fine when using an account that has global admin permissions but using a service principal with (GroupMember.ReadWrite.All Directory.ReadWrite.All, Group.ReadWrite.All) I get error "Insufficient privileges to complete the operation"

What other permissions is required?

**Comment by NPLznk** [comment]
> I am trying to use the Remove-MgGroupMemberDirectoryObjectByRef -GroupId $groupId -DirectoryObjectId $userId to remove users from a group. It works fine when using an account that has global admin permissions but using a service principal with (GroupMember.ReadWrite.All Directory.ReadWrite.All, Group.ReadWrite.All) I get error "Insufficient privileges to complete the operation"
> 
> What other permissions is required?

Same issue. I have 'UserAuthenticationMethod.ReadWrite.All','User.ReadWrite.All','GroupMember.ReadWrite.All','Group.ReadWrite.All','Directory.ReadWrite.All' and none of them let me use the command. Worth saying I am using a Global Admin account.

**Comment by kpinel** [comment]
Noticed that the cmdlet has changed with 2.18.0 to Remove-MgGroupMemberDirectoryObjectByRef, noted by samuelt81
The original cmdlet Remove-MgGroupMemberByRef is still broken.

If this cmdlet has changed, that means a lot of rewriting of runbooks. I could understand this with a major version change, but a point version seems a bit rediculous.
