### ISSUE TITLE
Remove-MgApplicationOwnerByRef 2.17.0 missing DirectoryObjectId parameter

### ISSUE THREAD

**Issue by TahaBenseddik** [microsoftgraph/msgraph-sdk-powershell#2674]
**Describe the bug**
> The parameter -DirectoryObjectId is not available with the command Remove-MgApplicationOwnerByRef in the module Microsoft.Graph.Applications 2.17.0.

**To Reproduce**
1. Execute `Install-Module -Name Microsoft.Graph.Applications -Force` 
2. Execute `Remove-MgApplicationOwnerByRef -ApplicationId $appId -DirectoryObjectId $OwnerId`

**Expected behavior**
> The parameter -DirectoryObjectId is supposed to be available with the command Remove-MgGroupMemberByRef in the module Microsoft.Graph.Applications 2.17.0.

**Module Version**
```
VERBOSE: InstallPackage' - name='Microsoft.Graph.Applications', version='2.17.0',destination='C:\Users\VssAdministrator\AppData\Local\Temp\1326736563'
VERBOSE: DownloadPackage' - name='Microsoft.Graph.Applications', version='2.17.0',destination='C:\Users\VssAdministrator\AppData\Local\Temp\1326736563\Microsoft.Graph.Applications.2.17.0\Microsoft.Graph.Applications.2.17.0.nupkg', uri='https://www.powershellgallery.com/api/v2/package/Microsoft.Graph.Applications/2.17.0'
```

**Environment Data**
```
Key   : PSVersion
Value : 7.4.1

Key   : PSEdition
Value : Core

Key   : GitCommitId
Value : 7.4.1

Key   : OS
Value : Microsoft Windows 10.0.20348

Key   : Platform
Value : Win32NT

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}

Key   : PSRemotingProtocolVersion
Value : 2.3

Key   : SerializationVersion
Value : 1.1.0.1

Key   : WSManStackVersion
Value : 3.0
```

**Screenshots**
> 
<img width="547" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/32578509/66c16446-31d5-43c1-998b-c82fbbcc4752">

**Additional context**
> The code is ran on a microsoft hosted agent from Azure DevOps
```
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 5.237.9
Author       : Microsoft Corporation
Help         : https://aka.ms/azurepowershelltroubleshooting

```

**Comment by ricmestre** [comment]
Already reported, see https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2670
