### ISSUE TITLE
Where can I find release notes?

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#268]
As someone who is building solutions that use this module bundle, I really need to know what to expect with an update. Where do you record the release notes for your updates (in particular I'd like to see the release notes for 0.7.0)?

**Comment by KirkMunro** [comment]
Nevermind, found them:

https://aka.ms/GraphPowerShell-Release

**Comment by darrelmiller** [comment]
Hey Kirk,  you should always be able to get to the release notes via the GitHub Release page https://github.com/microsoftgraph/msgraph-sdk-powershell/releases and the milestones page will give you advanced warning of what is coming in the next release.
