### ISSUE TITLE
12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR

### ISSUE THREAD

**Issue by alson26899** [microsoftgraph/msgraph-sdk-powershell#2685]
### Describe the bug

Getting this error while calling the graph api endpoint like the below code snippet
var callRecordSession = AsyncHelpers.RunSync<ICallRecordSessionsCollectionPage>(() =>
    graphServiceClient.Communications.CallRecords[Convert.ToString(callRecordId)].Sessions.Request(queryOptions).GetAsync());

### Expected behavior

API should return the callrecords

### How to reproduce

send a get  request  to fetch the callrecords its throwing the above mentioned error
graphServiceClient.Communications.CallRecords[Convert.ToString(callRecordId)].Sessions.Request(queryOptions).GetAsync());

### SDK Version

4.32.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

windows 10

**Comment by petrhollayms** [comment]
Hi @alson26899, 
You are using .NET SDK not PowerShell, right? Could you please try to reproduce it with the latest SDK version and if you still get an error, create a new issue in the correct repository i.e. https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/new/choose
with more information on the error you are getting? 
Thanks!
