### ISSUE TITLE
Incorrect Documentation Example for Remove-MgGroupMemberByRef cmdlet

### ISSUE THREAD

**Issue by MichaelPhillipsPS** [microsoftgraph/msgraph-sdk-powershell#2691]
### Describe the bug

This isn't really a bug, but the documentation for the aforementioned Remove-MgGroupMemberByRef cmdlet is out of date. It shows an example that no longer works. The example code snippet shows the following:

Remove-MgGroupMemberByRef -GroupId $groupId -DirectoryObjectId $directoryObjectId

But DirectoryObjectId is no longer a valid parameter for the cmdlet.

### Expected behavior

The example should match the updated syntax of that cmdlet.

### How to reproduce

Go to the documentation page and take a look: 

https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/remove-mggroupmemberbyref?view=graph-powershell-1.0

### Known Workarounds

Use the Remove-MgGroupMemberDirectoryObjectByRef cmdlet with the same parameter inputs instead.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by timayabi2020** [comment]
Thank you @MichaelPhillipsPS for reporting this issue. We will review the document update process and provide a long term solution for such issues.

**Comment by timayabi2020** [comment]
@MichaelPhillipsPS For backward compatibility purposes ``Remove-MgGroupMemberByRef`` cmdlet was reintroduced as an alias for ``Remove-MgGroupMemberDirectoryObjectByRef`` from version ``2.19.0`` and also the online document was updated.
