### ISSUE TITLE
Add-MgApplicationKey - Unexpected invalid input parameters.

### ISSUE THREAD

**Issue by BatmanAMA** [microsoftgraph/msgraph-sdk-powershell#270]
Hi, I can't get my application to update its own certificates and I'm wondering if anyone could help figure out how this command is supposed to be run or if it's just broken? I have the simplest case, but could create a more complex example if anyone wants me to try something.

```
Add-MgApplicationKey -ApplicationId $app.Id -KeyCredentialKeyInputFile .\example.cer -debug -Verbose

DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
Confirm
Are you sure you want to perform this action?
Performing the operation "Add-MgApplicationKey_AddExpanded" on target "Call remote 'ApplicationsAddKey' operation".
[Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "Yes"): a
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://graph.microsoft.com/beta/applications/54bae270-0997-4d8a-8f89-bec775594c77/microsoft.graph.addKey
DEBUG: RequestCreated: https://graph.microsoft.com/beta/applications/54bae270-0997-4d8a-8f89-bec775594c77/microsoft.graph.addKey
DEBUG: HeaderParametersAdded: https://graph.microsoft.com/beta/applications/54bae270-0997-4d8a-8f89-bec775594c77/microsoft.graph.addKey
DEBUG: BodyContentSet: https://graph.microsoft.com/beta/applications/54bae270-0997-4d8a-8f89-bec775594c77/microsoft.graph.addKey
DEBUG: BeforeCall: 
DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
Add-MgApplicationKey_AddExpanded: Unexpected invalid input parameters.
DEBUG: Finally: 
DEBUG: CmdletAfterAPICall: 
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: CmdletEndProcessing:
```

**Comment by MIchaelMainer** [comment]
Thank you for letting us know about this issue. We'll take a look at this issue.

**Comment by peombwa** [comment]
@BatmanAMA You can simply update the key of an existing application via 
``` powershell
$KeyCredential = @{ Type = "AsymmetricX509Cert"; Usage = "Verify"; Key= $Certificate.RawData } 
Update-MgApplication -ApplicationId Your_App_Id -KeyCredentials @($KeyCredential)
```
See the example here https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/9-Applications.ps1#L30-L47.


Adding an application key to an existing application will require you to also [set a proof](https://docs.microsoft.com/en-us/graph/api/application-addkey?view=graph-rest-beta&tabs=http). Your `Add-MgApplicationKey` call will end up looking like this:
``` powershell
$KeyCredential = @{ Type = "AsymmetricX509Cert"; Usage = "Verify"; Key= $Certificate.RawData } 
Add-MgApplicationKey -ApplicationId Your_App_Id -KeyCredential $KeyCredential -proof YOUR_PROFF
```

**Comment by BatmanAMA** [comment]
Oh, awesome, I'll change that over! What's the point of the add-mgapplicationkey command then?

**Comment by peombwa** [comment]
`Add-MgApplicationkey` is present as a command because the SDK is generated as mirror of the service. The REST API represents this as `applications/{id}/addKey`, and it's a fairly new API.

**Comment by peombwa** [comment]
Closing since we have an answer for this.
