### ISSUE TITLE
Get-MGSite Doesn't display any sites - returns null

### ISSUE THREAD

**Issue by bwya77** [microsoftgraph/msgraph-sdk-powershell#2710]
### Describe the bug

When running ```get-mgsite``` it does not return any sites. 
I have tried using several different tenants. I am connecting and can confirm I have Sites.Read.All permissions. 

Running ```Get-MgSite -All``` returns nothing as well. 

Running ```Get-MGSite -SiteId "0yx56.sharepoint.com,724aa3a4-1927-4aa1-b118-2221386c6d1f,31ad34a9-4e78-4854-969c-21795692f885"```
Returns: 
```
DisplayName      Id                                                                                             Name           WebUrl
-----------      --                                                                                             ----           ------
Sample Team Site 0yx56.sharepoint.com,724aa3a4-1927-4aa1-b118-2221386c6d1f,31ad34a9-4e78-4854-969c-21795692f885 SampleTeamSite https://0yx56.sharepoint.com/sites/SampleTeam…
```

Running ```Get-MgSite -Property "siteCollection,webUrl" -Filter "siteCollection/root ne null" ``` 
returns:
```
DisplayName Id Name WebUrl
----------- -- ---- ------
                    https://0yx56.sharepoint.com/
```

### Expected behavior

Returns data for the site. 

### How to reproduce

Execute ```Get-MgSite```

### SDK Version
Originally found in v2.17.0, but updated to 2.18.0 and still occurring
2.18.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:08 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8122
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by bwya77** [comment]
Looking at the authentication documents, I have a hunch this is because running Connect-MgGraph uses Delegated Access and according to the [documentation](https://learn.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0&tabs=http) for listing sites, only application access is supported.

**Comment by foss4ever** [comment]
Why is this issue marked as completed? What is the solution to the problem?

**Comment by OscarWoodsOryxAlign** [comment]
It sounds like the issue is that delegated access doesn't work, so the workaround is using application registration authentication for it to work, which is a bit ridiculous.
