### ISSUE TITLE
 Get-MgDevice -Search "displayName:XYZ" returns XYZ AND ABC

### ISSUE THREAD

**Issue by oingobo** [microsoftgraph/msgraph-sdk-powershell#2733]
### Describe the bug

I'm deleting EntraID device records and the search returns a display name match and another device that DOES NOT match the display name.  When performing bulk delete on a display name this is a major issue. 

### Expected behavior

Search and return only the device with the matching displayname.

### How to reproduce

Get-MgDevice -Search "displayName:$Computer" -CountVariable CountVar -ConsistencyLevel eventual -ErrorAction Stop

### SDK Version

2.18.0

### Latest version known to work for scenario above?

Don't know.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by petrhollayms** [comment]
Hi @oingobo ,

Could you please execute the cmdlet with a -debug parameter and post here the log?
The issue might be in the API interpreting a search parameter. Could you try to use a filter with "eq" operator to compare the results?

See also https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http

Thanks!

**Comment by oingobo** [comment]
I will run with debug the next time the problem occurs.  Thank you for reaching out.
