### ISSUE TITLE
Get-MgDirectoryDeletedItemMemberGroup should be removed

### ISSUE THREAD

**Issue by jugmethodman** [microsoftgraph/msgraph-sdk-powershell#2739]
### Describe the bug

We don't expect to call or support getMemberGroup on a deleted directory object. 
This was generated automatically and has been causing CRIs. Please remove this from the generated cmdlets.

### Expected behavior

The cmdlets should not exist

### How to reproduce

The cmdlet existing is the issue

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by petrhollayms** [comment]
The cmdlet seems to be generated correctly for the Graph API, which does support getting a deleted object, see https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-get?view=graph-rest-1.0&tabs=http

If you want to prevent getting the data for the user, the API is supporting a permanent delete, see https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-delete?view=graph-rest-1.0&tabs=http

Does it answer your question?
