### ISSUE TITLE
Something to consider regarding retrieval of paged data: replace -All with -Limit

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#275]
How often when you need to retrieve a certain resource using PowerShell do you not want all instances of that resource?

In general, in PowerShell if you only want some of a certain type of resource, you use parameters to indicate which ones you want, and if you want all of those resources, you simply invoke the `Get-*` command without any parameters.

Some modules over time have gone against this model, such as the AD module requiring users to use a `-Filter` parameter, even when you want all resources (i.e. even if there really is no filter), but this makes automation more complicated.

Why am I pointing this out?

Because the Graph module bundle now has a `-All` parameter that is required when you want all resources. Having used this new parameter with the 0.7.0 release a few times, this seems backwards to me, because I never want to invoke a command to retrieve resources only to get back some arbitrary number (whatever the max page size happens to be for that resource type).

I think a much better design would be to do away with `-All`, and instead break out the `-Top`/`-Limit` aliases for `-PageSize` as a new parameter. Consider this:

```powershell
# Retrieve all users (paged data retrieval, gathering all pages)
Get-MgUser

# Retrieve all users (paged data retrieval, gathering all pages, with pages of a specific size)
Get-MgUser -PageSize 50

# Retrieve a limited number of users (paged data retrieval, gathering as many pages as
# required until the number of users requested has been retrieved)
Get-MgUser -Limit 500

# Retrieve a limited number of users (paged data retrieval, with pages of a specific size,
# gathering as many pages as required until the number of users requested has been retrieved)
Get-MgUser -Limit 500 -PageSize 50

# Retrieve a specific set of users (paged data retrieval, gathering as many pages as required,
# using the default page size, until the users represented by the filter have been retrieved)
Get-MgUser -Filter $filter

# Retrieve a specific set of users (paged data retrieval, with pages of a specific size, gathering
# as many pages as required until the users represented by the filter have been retrieved)
Get-MgUser -Filter $filter -PageSize 50

# Retrieve a specific user
Get-MgUser -UserId $userId
```

You probably get the idea. The point is simple: don't make me have to use `-All` to get all records, because I naturally want to get all records when I invoke a `Get-` command without `-All`. Instead, allow me to limit the number of records I want for those very rare occasions where I really only want a glimpse of the data. That way, I only use parameters when I want to apply some sort of limit, filter, or configuration on the data I would normally retrieve by default.

This would require:

1. Remove `-All`, because that is the natural intention of all `Get-` commands.
1. Internally make all commands retrieve all pages all the time.
1. Add `-Limit` with alias `-Top` to limit the number of records requested, and stop paged data retrieval once that number has been reached. 
[AB#7415](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7415)

**Comment by KirkMunro** [comment]
Here's a use case that may help drive home while I think this is important:

I'm writing a bunch of scripts that work directly with Graph resources. With the retrieval (i.e. `Get` verb) scripts among that set of scripts, I typically want to either retrieve all records (the default), when I'm retrieving a data set for the first time or when I'm refreshing an entire data set, or some records, when I'm refreshing specific records in a dataset that I already retrieved. With the current model, it is harder to map my script parameter sets to the parameter sets used by graph, because the options are not simply additive. I need to instead build two different sets of parameters that will be passed into the command I invoke depending on whether I want all records or a subset (or just one) of them. This is an annoyance and doesn't fit how PowerShell was designed to work naturally. Instead, allow me to simply build one set of parameters that I can splat into my command in an additive fashion, so that I'm naturally reducing or configuring the data that the command retrieves as I add more parameters to the parameter set that I pass through.

**Comment by peombwa** [comment]
Thanks @KirkMunro, this is a justified approach and it fells natural to PowerShell.
@ddyett, @darrelmiller thoughts on this? The code change to support this is minimal, and can be done as part of PR #272.

**Comment by ddyett** [comment]
i'm good with it.

**Comment by darrelmiller** [comment]
I think the difference to consider is these PowerShell commands make calls to a remote resource where the consumer is not paying the majority of the costs to process that information.  I would argue that it is rare that a consumer wants to process all users, groups, applications, devices, etc.  While I accept that it is an inconvenience to be explicit to request all, I am reluctant to  make it a default. 

I don't want to be having conversations in a year or two about the fact that we need to make a breaking change to the PowerShell SDKs because telemetry is telling us that X% of customers are naively retrieving all users and using client side filtering to get at the rows they want.  We need to find a way to encourage PowerShell users to use server side filtering parameters to minimize the data brought across the wire, both to improve performance and reduce our costs.

This use of PowerShell commands to make HTTP requests across the Internet does provide some reasoning for non-necessarily following all PowerShell standard conventions.  I will discuss this further with @peombwa  and @ddyett

**Comment by KirkMunro** [comment]
Hey @darrelmiller, on this topic I wanted to provide one additional data point that is worth considering.

Going with `-All` without providing some way to tell the module bundle "yeah, I get it, but don't make me have to use -All to get all data" is a pain, because having to support multiple parameter sets programmatically is a pain.

An example:

I have a script that retrieves users from Graph, along with some related information, builds a custom object, and outputs it. This gives me a user record for the solution that my script belongs to. This script is used to retrieve all users (full run, scheduled) or specific users (update run, triggered when a user is added or edited). _It is very important that my script remains as simple and consise as possible so that customers can learn from it and build their own scripts like it._ To allow my script to retrieve all users _or_ individual user records, I would like to be able to simply take an additive approach to the command, with logic that looks something like this:

```powershell
$lookupParameters = @{}
if ($updateUserIds) {
    $lookupParameters['UserId'] = $updateUserIds
}
Get-MgUser @lookupParameters
```

That is fairly straightforward to a less experienced scripter. Unfortunately what we have to write in our script looks closer to what is shown below, because of the need for `-All` and because the specific user parameter set only accepts a single user id (this would be a great place to have an implicit batch command handled automatically by Graph):

```powershell
$lookupParameterSets = [System.Collections.ArrayList]::new()
if ($updateUserIds) {
    foreach ($updateUserId in $updateUserIds) {
        $null = $lookupParameterSets.Add(@{'UserId' = $updateUserId})
    }
} else {
    $null = $lookupParameterSets.Add(@{'All' = $true})
}
foreach ($lookupParameterSet in $lookupParameterSets) {
    Get-MgUser @lookupParameterSet
}
```

All of a sudden I've gone from relatively simple, additive logic defining how I will invoke `Get-MgUser` to significantly more complicated logic with multiple paths to determine how the cmdlet will be invoked, depending on what is being retrieved: all users or individual users.

This shows a solid entry in the "con" side demonstrating why having an independent parameter set with `-All` is not such a great idea (which is further complicated because of individual-focused parameter sets that are truly individual, and are not smart enough to work with basic collections).

Even if you resolve the collection issue so that either multiple calls are made in sequence to gather items passed in as a collection or so that batching is used to retrieve multiple records in a single call, having split, non-additive logic to decide between one/many and all is frustrating.

I know I can set `$PSDefaultParameterSets['Get-Mg*:All'] = $true` as a workaround, but that's sloppy/non-specific because of the wildcard, and `-All` doesn't even apply to all Graph data retrievals even though it is present on most (not all) Get-Mg* commands.

What if you supported checking for an in-process environment variable, with `-All` being unnecessary if that was present? That plus fixing multi-resource lookups so that they can be done in a single PowerShell command while absorbing the complexity of multiple sequential Graph endpoint invocations or a single batch endpoint invocation would go a long way towards promoting scripting simplicity, which is absolutely necessary when you want to demonstrate how easy it is to accomplish certain tasks in PowerShell.

**Comment by maisarissi** [comment]
Hi @KirkMunro, really appreciate all information you provided.

> I think the difference to consider is these PowerShell commands make calls to a remote resource where the consumer is not paying the majority of the costs to process that information. I would argue that it is rare that a consumer wants to process all users, groups, applications, devices, etc. While I accept that it is an inconvenience to be explicit to request all, I am reluctant to make it a default.

But as Darrel mentioned before, is rare that a consumer want to process all by default.
Instead of changing the default behavior, you can use pipe to make your script more readable.


```
$UpdateUserIds = @(id1, id2, id3 )
if ($updateUserIds) {
    $updateUserIds | % { @{userId=$_;} } | Get-MgUser -select userPrincipalName
} else {
    Get-MgUser -All
}
```

Once we fully support piping, you will also be able to:

#### Pipe ids directly to command without an intermediary object.
```
$UpdateUserIds | Get-MgUser
```

#### Multi-resource lookup won't be necessary since the piping will do the same.
```
$UpdateUserIds = @(id1, id2, id3 )
Get-MgUser -UserId $UpdateUserIds
```
#### or even
```
$UpdateUserIds = @(id1, id2, id3 )
$updateUserIds | % { @{userId=$_;} } | Get-MgUser
```

Closing this as we are not going to change the default behavior.
