### ISSUE TITLE
Update-MgOauth2PermissionGrant -Scopes should be case-insensitive

### ISSUE THREAD

**Issue by danielniccoli** [microsoftgraph/msgraph-sdk-powershell#2772]
### Describe the bug

I was assigning scopes and noticed that the scopes are case-sensitve. I assigned the following scopes: `IMAP.AccessAsUser.All offline_access openid smtp.send user.read`

And noticed that they have been added to the application all in lowercase, eg. `user.read`, instead of `User.Read`.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2971735/6d6defaa-4f2c-4299-b780-51ae49b41e22)

### Expected behavior

Scopes should be added case-insensitive

### How to reproduce

Update-MgOauth2PermissionGrant -OAuth2PermissionGrantId $grantid -Scope "IMAP.AccessAsUser.All offline_access openid smtp.send user.read"

### SDK Version

2.17

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by petrhollayms** [comment]
Hi @danielniccoli , 

The OAuth 2 scopes are case-sensitive, so one needs to pass the value as specified in the Graph API documentation.
https://datatracker.ietf.org/doc/html/rfc6749#section-3.3
