### ISSUE TITLE
Trying to use the command Update-MgUserAuthenticationPhoneMethod 

### ISSUE THREAD

**Issue by steele6599** [microsoftgraph/msgraph-sdk-powershell#278]
I'm trying to bulk update about 5,000 users phone authentication contact info for SSPR but have been unsuccessful at getting it to work. 

  I'm trying to figure out how to right this Graph PowerShell Command command but have been unable to fine any examples on how to do it.  I believe I want to use this command to add or replace users phone number.

Update-MgUserAuthenticationPhoneMethod -UserId 259089c6-10b8-4164-b537-0058b24459b7 -Id 3179e48a-750b-4051-897c-87b9720928f7 -phonenumber "+1 5409446666"

Supply values for the following parameters:
PhoneAuthenticationMethodId:  

I'm not sure what the difference is from "-ID" vs "-PhoneAuthenticationMethodId"

when i use the get-help Update-MgUserAuthenticationPhoneMethod -examples  there is nothing there and no online documentation.  get-help Update-MgUserAuthenticationPhoneMethod -online

Note, i was able to update users using the Graph and this article:  https://techcommunity.microsoft.com/t5/azure-active-directory-identity/manage-your-authentication-phone-numbers-and-more-in-new/ba-p/1257359
 
[AB#7416](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7416)

**Comment by dheuts** [comment]
I have the same issue, this is the error message I get:
Update-MgUserAuthenticationPhoneMethod : {"Message":"No HTTP resource was found that matches the request URI 'https://mface.windowsazure.com/odata/users('upn_of_user')/authentication/phoneMethods('3179e48a-750b-4051-897c-87b97
20928f7')'.","MessageDetail":"No type was found that matches the controller named 'users'."}

**Comment by steele6599** [comment]
I have had no luck trying to get this to work, not sure if anyone else has?



Update-MgUserAuthenticationPhoneMethod -PhoneAuthenticationMethodId "3179e48a-750b-4051-897c-87b9720928f7" -UserId "259089c6-10b8-4164-b537-0058b24459b7" -PhoneNumber "+1 540666666" -PhoneType "mobile"

Update-MgUserAuthenticationPhoneMethod : {"Message":"No HTTP resource was found that matches the request URI 'https://mface.windowsazure.com/odata/users('259089c6-10b8-4164-b537-0058b24459b7%407fef86bb-a3b9-46e0-a4a8-b3c0fb41a7d0')/authentication/phoneMethods('3179e48a-750b-4051-897c-87b9720928f7')'.","MessageDetail":"No type was found that matches the controller named 'users'."}
At line:1 char:1
+ Update-MgUserAuthenticationPhoneMethod -PhoneAuthenticationMethodId " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation: ({ UserId = 2590...icationMethod }:<>f__AnonymousType12`3) [Update-MgU
serAu..._UpdateExpanded], Exception
+ FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUserAuthenticationPhoneMethod_Up

dateExpanded

**Comment by peombwa** [comment]
This command should be updated to make PUT calls to `/users/{user-id}/authentication/phoneMethods/{phoneAuthenticationMethod-id}`. It currently makes PATCH calls. See https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&tabs=http

The [OpenAPI doc](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/beta/Identity.SignIns.yml#L11358) wrongly describes this as a PATCH request.

**Comment by ddyett** [comment]
moving the priority of underlying issue up to fix this correctly.

microsoftgraph/microsoft-graph-explorer-api#408

**Comment by jbpaux** [comment]
Do you have any news ?

**Comment by mortenlerudjordet** [comment]
This is still a blocker for using the command. Any updates on fixing this issue?

**Comment by peombwa** [comment]
@darrelmiller, @mairissi  Any news on this?

**Comment by mortenlerudjordet** [comment]
No movement on fixing this issue?

**Comment by vandeyv** [comment]
Guess not and is is still the same issue

**Comment by darrelmiller** [comment]
It turns out the workload team who had created an item to resolve this, were not able to prioritize it last semester.  I have emailed them to ask them to get it back on their backlog.

**Comment by andres-canello** [comment]
This command can be used as a workaround until we fix the API:
Invoke-MgGraphRequest -Method PUT -Uri https://graph.microsoft.com/beta/users/user@contoso.com/authentication/phoneMethods/3179e48a-750b-4051-897c-87b9720928f7 -ContentType "application/json" -Body '{"phoneType": "mobile","phoneNumber": "+123456789"}'

**Comment by misteriks** [comment]
This same issue exists on Update-MgUserAuthenticationEmailMethod. Will this be fixed as well or is a new open issue needed to get that fixed as well?

Now using the workaround suggested by @andres-canello  but slightly modified 
Invoke-MgGraphRequest -Method PUT -Uri "https://graph.microsoft.com/beta/users/user@contoso.com/authentication/emailMethods/3179e48a-750b-4051-897c-87b9720928f7" -ContentType "application/json" -Body '{"EmailAddress": "updated@mail.com"}'

**Comment by jbpaux** [comment]
@peombwa @darrelmiller @mairissi Any news on this?

**Comment by maisarissi** [comment]
Hi @jbpaux.
We are trying to get this prioritized with the API team, since they need to provide a fix.
@mmcla can you share info around this?

**Comment by andres-canello** [comment]
Hi all, thanks for your patience while we worked on fixing this issue. We have added PATCH support to the email and phone authentication methods API. The following cmdlets are now fully functional:

- Update-MgUserAuthenticationPhoneMethod
- Update-MgUserAuthenticationEmailMethod

We are working on making these methods available in v1.0.

**Comment by maisarissi** [comment]
Hello everyone.

Closing this as the API was fixed and the cmdlets should work as expected.
