### ISSUE TITLE
What happened to the parameters' descriptions?

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#2781]
`https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.authentication/find-mggraphpermission?view=graph-powershell-1.0`

Help for Find-MgGraphPermission used to have parameter descriptions. Not anymore.

**Comment by petrhollayms** [comment]
Hi @alexandair ,

Are you looking for a more detailed output as provided by the -Detailed option of the Get-Help command?

If you mean something else, could you please share the script or commands you are executing with the actual vs. expected output?

**Comment by timayabi2020** [comment]
@alexandair thank you for identifying this issue. It's indeed a bug in both offline and online documentation. We will work to resolve this.
