### ISSUE TITLE
Can we get application access to List shared?

### ISSUE THREAD

**Issue by AndersRask** [microsoftgraph/msgraph-sdk-powershell#2785]
### Is your feature request related to a problem? Please describe the problem.

We are doing a lot of clean up jobs in SharePoint for customers, where sharing have gone out of hand.
We help them set sharing capability that match the content, and help them educate their users.

However when fetching List shared (we use PnP.PowerShell a lot for this) I noticed I got "access denied" when trying to get the sharing links. I checked the code and that led me to the REST method below, where I noticed application access is not supported.

For clean up scripts, that usually are long running, it makes sense to allow application access, that are not as prone to throttling as a user session.
https://learn.microsoft.com/en-us/graph/api/insights-list-shared?view=graph-rest-1.0&tabs=http

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/1651150/e331b2e4-9354-489f-a57b-a274224df89a)

### Describe the solution you'd like.

I would like application access to be enabled for List shared, so that we can run clean up scripts without having to worry about throttling.

Also user accounts are almost always using MFA these days, so if you want to run a non-interactive scheduled script, this requires an application.

**Comment by timayabi2020** [comment]
Hi @AndersRask thank you for raising this issue. However, your request to include application permissions for that API can be raised here  https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.
