### ISSUE TITLE
Azure connection and user retrieval

### ISSUE THREAD

**Issue by danalden** [microsoftgraph/msgraph-sdk-powershell#2789]
Hello,

I am learning Azure with PowerShell. While connecting to Azure using PowerShell, I can connect but then get an error when attempting to get user information. I tried the advice shown by the arrow in the pic and other methods after searching online but nothing seems to work. I can get the user info using Cloudshell's PowerShell but can't get it from my local ISE logged in as Admin. Please see below

Thank you!

![Screenshot 2024-06-12 103755](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/29076990/fb62d4fc-60b8-4544-9d44-aa632b3a6d0b)

**Comment by timayabi2020** [comment]
@danalden thank you for logging this issue. However, for issues related to Azure PowerShell SDK we are not best placed to give an answer. Kindly raise an issue here https://github.com/Azure/azure-powershell so that the team over there can respond to it.
