### ISSUE TITLE
Implement a -WhatIf switch that returns the HTTP request that would be generated

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#28]
By plugging in a piece of middleware we can intercept the request prior to sending and emit the result to the host.  This would be useful for debugging cmdlets. 
[AB#6242](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6242)

**Comment by darrelmiller** [comment]
-debug shows the URL.  Which is part way there.  And fiddler does work, so this is a lower priority.

**Comment by georgend** [comment]
@darrelmiller Should we go ahead with this issue?
