### ISSUE TITLE
How is API throttling handled in the PowerShell Graph functions?

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#281]
From https://docs.microsoft.com/en-us/graph/throttling, Microsoft states:

> When a throttling threshold is exceeded, Microsoft Graph limits any further requests from that client for a period of time. When throttling occurs, Microsoft Graph returns HTTP status code 429 (Too many requests), and the requests fail. A suggested wait time is returned in the response header of the failed request. Throttling behavior can depend on the type and number of requests. For example, if you have a high volume of requests, all requests types are throttled. Threshold limits vary based on the request type. Therefore, you could encounter a scenario where writes are throttled but reads are still permitted.

That's somewhat...vague. In large environments where various resource types can easily exceed 50000 in number, when many API calls are one per resource (or multiple per resource if you're pulling back multiple pieces of information), two things become essential: [batching requests](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/116) (assuming that batched requests result in lower counts as far as API limits are concerned), and proper handling of API limits.

For the latter, since PowerShell abstracts away from all of the lower-level REST API calls, what is it doing to handle status code 429?

If the answer to that is simply "nothing yet", then I have a request: add a common parameter to Graph cmdlets called `-RetryCount` that identifies the number of times you want to retry a given command before it is considered failed, with an internal maximum limit that cannot be exceeded, and handle status code 429 by sleeping for the recommended wait period before trying again internally within Graph commands, up to the maximum number of retries.

Regardless of that request, please share details on what happens now when throttling comes into effect and what the plans are moving forward. Thank you. 
[AB#7417](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7417)

**Comment by KirkMunro** [comment]
Thinking about this some more, while having a `-RetryCount` (or `-RetryLimit`, which is probably a better name) parameter solves the simple case where I'm using a single script that possibly uses multiple runspaces/thread jobs to do some work against Graph, which I believe is necessary, there is an additional need that is not being covered with that approach, which is surfacing information that throttling/delays are taking place to the caller.

If you are performing large scale automation against a single tenant using Microsoft Graph within a distributed application where you may have multiple processes on a single system or across serverless functions, containers, etc. on different systems executing Graph API calls using PowerShell, it will be important for the calling application to know that throttling is taking place. I still believe auto-retry with handling for the delay time is the right thing to do so that automation logic can focus on the automation and not on the throttling management; however, it is important to let callers take appropriate action as well.

Consider this:

```
# This call retrieves all users, and if that results in a 429 return code, internally it will
# sleep for the Retry-After duration and then try again, up to -RetryLimit times
Get-MgUser -RetryLimit 5 

# This is the same call, but in addition to retrying a certain number of times and
# automatically sleeping, it will invoke a `-RetryAction` script block that lets me
# determine how I want to proceed
Get-MgUser -RetryLimit 5 -RetryAction {
    param($sender, $object)
    # This script block would be invoked if a 429 error occurred, allowing me
    # to do whatever I want with the information provided. A $sender variable
    # could contain the FunctionInfo object for the cmdlet where this happened,
    # and a $object variable could contain the headers that were returned with
    # the request so that I could see those details. With this information, I could
    # coordinate across multiple automation scripts running in different processes
    # on different systems, log the throttling events, perhaps take some action
    # that is more appropriate than the default "sleep" action because I happen to
    # be using graph a lot. The point is, this script block would allow me to scale
    # my work across systems.

    # In this logic, if I were to use the "continue" statement, then the command
    # would sleep the appropriate amount of time and then try again, and if I
    # were to use the "break" statement, then the command would terminate
    # and not sleep or continue, even if I could keep running based on the number
    # of retries.
}
```

By using a `-RetryAction` parameter, I could apply common logic across all Graph
commands I invoke by using `$PSDefaultParameterValues['*-Mg*:RetryAction'] = {...}`.

Something along those lines anyway. The point is, keep 429 handling built-in with simple retry logic support, while also allowing me to do additional work that my solution requires if a 429 happens to occur.

**Comment by MIchaelMainer** [comment]
The PowerShell SDK currently implements https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RetryHandler.md.

**Comment by KirkMunro** [comment]
@MIchaelMainer Does that mean that 429's are already automatically handled internally in the Graph PowerShell commands?

**Comment by darrelmiller** [comment]
@KirkMunro Yes they should be.

**Comment by KirkMunro** [comment]
Thanks @darrelmiller.

Since it's handled internally, how can I tell if throttling is happening in a script, and for which resource type (team service, excel service, outlook service, or a resource type like user, group, etc)?

**Comment by KirkMunro** [comment]
Following up on this, because I could really use a response.

How can I tell with the execution of a given PowerShell script that uses Microsoft.Graph whether or not throttling is occurring?

This is important information to surface because as you measure the execution times of various scripts and look at your overall automation strategy in your organization, you need to know if you're hitting throttling limits so that you can take appropriate steps to adjust how you perform automation so that you are less likely to hit those limits.

**Comment by marceleneco** [comment]
@KirkMunro In PowerShell it would return an error, see below output for Get-AzureAdAuditSigninLogs for example.

```
Get-AzureAdAuditSigninLogs : Error occurred while executing GetAuditSignInLogs 
Code: UnknownError
Message: This request is throttled. Please try again after the value specified in the Retry-After header. CorrelationId: 9b27c007-f9fb-4caa-8163-77f47e54ee99
InnerError:
  RequestId: 36111868-01f9-41ef-ba4b-386352b47b5a
  DateTimeStamp: Sun, 28 Mar 2021 12:07:31 GMT
HttpStatusCode: 429
HttpStatusDescription: Too Many Requests
HttpResponseStatus: Completed
At xxx.ps1:67 char:31
+ ... astsignin = Get-AzureAdAuditSigninLogs -top 1 -filter "userprincipaln ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADAuditSignInLogs], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.GetAuditSignInLogs
```

Unfortunately I don't see how I can retrieve the Retry-After header using PowerShell.

**Comment by robinmalik** [comment]
I've been hitting this issue with `Get-Team` in the `MicrosoftTeams` module, either when querying for all teams (where randomly teams will vanish and then reappear in the results), or when querying using `-DisplayName` or `-MailNickName`. Querying via `-GroupId` will result in a thrown exception that indicates a `429` error, but we can't always make lookups this way. A really easy way to replicate this is to run Get-Team twice in succession and the returned results fall off a cliff (this in a test tenancy with little use).

@KirkMunro Just as an additional FYI, I've spent a few weeks with Microsoft Premier Support trying to get traction on this issue but only today on a screensharing call was I able to demo the problem completely so the advisor could capture what was needed to take back to the product group.

**Comment by Mike-Crowley** [comment]
@marceleneco , to read the Retry-After header, you can do something like this:


    try {$webResponse = Invoke-RestMethod ...}
    catch {
        $webError = $_.Exception
        $mustRetry = 1
    }

    if ($mustRetry -and ($webError.Response.StatusCode -eq 429)) {
        $SleepDuration = ($webError.Response.Headers[“Retry-After”])
        Write-Output ("Too many requests. Waiting " + $SleepDuration + " seconds...")        
        sleep ([int32]$SleepDuration + 1) #extra second for good luck
        $webResponse = Invoke-RestMethod ...
    }

**Comment by ramonabadea** [comment]
Hi everyone,

I have been following this topic. Does anyone know if there is any update regarding this? I have seen that a request for the PG has been requested, but is it still under going? 

Thanks in advance,
Ramona

**Comment by insomniacc** [comment]
I've also found throttling/pagination in Microsoft.Graph functions a little bizarre.
I recently needed to use Get-MgGroup with certain properties properties to pull -all groups. 
In doing so I hit memory limitations within PS5, I read this is a known issue and had to use PS7 to get around it.
Also, it takes approx 15mins to get ~22k groups, but I'm also frequently getting http client timeout errors, the cmdlet stalls/bombs out.

Heres the command I was using:

```
$GroupProperties = "Description,DisplayName,Id,Visibility,Owners,AdditionalProperties,resourceProvisioningOptions"
$365Groups = Get-MgGroup -Filter "groupTypes/Any(c:c eq 'Unified')" -ExpandProperty Owners -Property $GroupProperties -PageSize 900 -all
```

In the end, I just resorted to using Invoke-GraphRequest and using the odata nextlink myself in a do while loop, along with a back off and retry policy if there are any timeouts, like this:

```
$uri = "https://graph.microsoft.com/v1.0/groups?`$filter=groupTypes/any(c:c+eq+'Unified')&`$select=Id,Description,DisplayName,Visibility,Owners,resourceProvisioningOptions&`$expand=owners(`$select=userPrincipalName,id)&`$top=200"
$GraphResponse = invoke-mgGraphRequest -method Get -uri $uri -erroraction stop -ResponseHeadersVariable "ResponseHeaders"
```
The value, from the response, I add to an array, and build up until there's no further '@odata.nextlink'

Couple of things I've noticed; doing it this way I can run the same query and get the same result without hitting the memory limits in PS5.1 infact the memory usage is astounding when using the regular cmdlets compared to just calling the endpoint directly like this. It also takes only 3mins to pull the same data in the second example, than it does to 15mins in the first one, and I've been running it multiple times without ever getting the same http client timeout errors.

One final issue that I've seen, even on calling the graph api directly, is that pagination doesnt seem to want to work.
I read that 999 is the max pagination amount, yet, when I use the following uri:
```
"https://graph.microsoft.com/v1.0/groups?`$filter=groupTypes/any(c:c+eq+'Unified')&`$select=Id,Description,DisplayName,Visibility,Owners,resourceProvisioningOptions&`$expand=owners(`$select=userPrincipalName,id)&`$top=200"
```

I'll only ever get 100 groups returned, not 200. I've also tried adding a header for 'odata.maxpagesize=200' which again seems to make no difference.

In the end, my final approach is a do while loop, (using the second example above), with a try catch that has an incremental back off and retry when http client timeouts or 429's are thrown, it's adequate for what I need but the above issues prevent me from using any of the PS functions in these modules for pulling large datasets.

**Comment by insomniacc** [comment]
Sorry if my previous comment is in the wrong place here but I hope it provides some constructive feedback on this discussion.
I would say that it would be useful to get some more verbose output on these commands so users can easily identify certain things - addressing some of the questions already raised about throttling above.

For example,
`Get-MgGroup -top 1 -verbose`
Provides no verbose output at present.
it would be beneficial to see both any full url endpoint being called and any retries or throttled information if they are being internally handled.
I'm currently using Microsoft.Graph.Groups 1.9.2

**Comment by JeremyTBradshaw** [comment]
I'm a little confused on whether or not the built-in handling of throttling (i.e., the "Retry Handler") is actually working or not.  If it is working, what are the conditions where it doesn't work, which would then indeed leave a need for us to be able to see the Retry-After value.  I implemented a sample [script](https://github.com/JeremyTBradshaw/MSGraphPSEssentials/blob/main/Samples/Demo-MSGraphPSEssentials.ps1) (see the `newMGRequest` function within the script) that works with my [MSGraphPSEssential](https://github.com/JeremyTBradshaw/MSGraphPSEssentials)'s module's functions, in order to handle automatic retrying based on the Retry-After value.  If the official Graph PowerShell SDK can have this built in, I would thereby be ready to retire MSGraphPSEssentials.  But until then, I would argue people might as well use MSGraphPSEssentials and mimic my retry logic while the official SDK awaits the functionality.

**Comment by peombwa** [comment]
Sorry for the delayed response to this topic. I'll try to answer the questions as follows:

How do the PowerShell Graph commands handle API throttling?
- The SDK has an in-built retry handler that handles retry based on the conditions outlined in https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RetryHandler.md. Service-specific limits are described in https://docs.microsoft.com/en-us/graph/throttling.

How do I know if the retry handler is working?
- User `-Debug` or fiddler to inspect the request when calling a command. Specifically, look for a `retry-attempt` header as described in https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RetryHandler.md#requirements. The SDK currently locks the maximum number of retry attempts to three. We will provide a global variable that customers can use to override this in #1106.

Are you getting an error signaling that your request has been throttled? If so, please open a new issue and share the `-Debug` log or fiddler capture for us to investigate.

**Comment by JeremyTBradshaw** [comment]
Thanks very much @peombwa .  Sounds like it's almost time for me to put MSGraphPSEssentials to bed 😭.  At the same time, this is awesome.  I guess we should subscribe to the feature request (#1106) to wait for the retry threshold to be customizable.  I've seen throttling for things like auditLogs\signIns last through 20+ retry attempts that all honored the retry-after, and then successfully proceeded once the service stopped throttling.  So 3 would be too low in those situations.  But fantastic to know this is built-in to all the commands and it's going to keep getting even better.

**Comment by maisarissi** [comment]
Hello everyone.


> Sorry for the delayed response to this topic. I'll try to answer the questions as follows:
> 
> How do the PowerShell Graph commands handle API throttling?
> 
> * The SDK has an in-built retry handler that handles retry based on the conditions outlined in https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RetryHandler.md. Service-specific limits are described in https://docs.microsoft.com/en-us/graph/throttling.
> 
> How do I know if the retry handler is working?
> 
> * User `-Debug` or fiddler to inspect the request when calling a command. Specifically, look for a `retry-attempt` header as described in https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RetryHandler.md#requirements. The SDK currently locks the maximum number of retry attempts to three. We will provide a global variable that customers can use to override this in [Powershell Microsoft.Graph- How to set MaxRetry #1106](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1106).
> 
> Are you getting an error signaling that your request has been throttled? If so, please open a new issue and share the `-Debug` log or fiddler capture for us to investigate.

As mentioned by @peombwa we do have a retry handler in place and everything should be working fine.
Don't hesitate to raise new issues if needed.

Closing this.
