### ISSUE TITLE
Missing Cmdlet for Identity Protection Settings

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#2836]
### Describe the bug

The following endpoint:
/identityProtection/policy

Doesn't have any cmdlet mapped to it. I believe there should be Get/Set cmdlets available for it.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/2547149/d157bee6-dfae-4e24-87af-6e0d7856b3b8)

### Expected behavior

Cmdlets should be available

### How to reproduce

Install Microsoft Graph 2.20.0 and run:

Find-MgGraphCommand -uri '/identityProtection/policy'

### SDK Version

2.20.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by NikCharlebois** [comment]
Same goes for the child endpoint:
/identityProtection/settings/notifications
![Uploading image.png…]()

**Comment by timayabi2020** [comment]
Hi @NikCharlebois are you able to locate the OpenApi reference docs for the missing APIs here ?https://learn.microsoft.com/en-US/graph/api/overview?view=graph-rest-1.0
