### ISSUE TITLE
Bring back -ForceRefresh for Connect-MgGraph

### ISSUE THREAD

**Issue by nkasco** [microsoftgraph/msgraph-sdk-powershell#2837]
### Is your feature request related to a problem? Please describe the problem.

I've identified scenarios with 2.x versions of the module that lead to unexpected auto-authentication with Connect-MgGraph in scripts. This is not expected behavior as I should be presented with an account picker since 2 accounts are logged in. 

### Describe the solution you'd like.

While it seems like running Disconnect-MgGraph before a script exists helps avoid this, if you run that cmdlet during a new PS session it does not know what to do. Therefore, rather than having to add that cmdlet with odd error handling or force clearing the token cache, I'd like to see -ForceRefresh be brought back so that it ensures the account picker is always visible.

**Comment by timayabi2020** [comment]
@nkasco it seems you are trying to connect to Microsoft Graph using two alternate credentials. If that's the case, then you can make use of ``Connect-MgGraph -ContextScope Process``
