### ISSUE TITLE
New-MgConditionalAccessPolicy Not Accepting -ApplicationIncludeApplications as Parameter

### ISSUE THREAD

**Issue by giorod3** [microsoftgraph/msgraph-sdk-powershell#284]
When using Microsoft.Graph and after authenticating, I am trying to create a new conditional access policy using New-MgConditionAccessPolicy. I have all the necessary scopes: "Policy.Read.All", "Policy.ReadWrite.ConditionalAccess", 
"Application.Read.All". 

The error is as follows:
```
New-MgConditionalAccessPolicy: A parameter cannot be found that matches parameter name 'ApplicationIncludeApplications'.
```

The full script is as follows:
``` 
Install-module Microsoft.Graph
Connect-Graph -Scopes "Policy.Read.All", "Policy.ReadWrite.ConditionalAccess", "Application.Read.All"
New-MgConditionalAccessPolicy -ApplicationIncludeApplications '6463xxxx-xxxx-xxxx-a2e8-xxxxxxxxxxxx' -State 'disabled' -GrantControlBuiltInControls @('mfa') -UserIncludeUsers 'None' -GrantControlOperator 'OR' -Confirm
```
I have hidden the applicationId for security purposes.

**Comment by giorod3** [comment]
I am using Cloud Shell Powershell with version 7.0.0

**Comment by MIchaelMainer** [comment]
Can you share with the version of the PowerShell SDK that you are using?

**Comment by giorod3** [comment]
> I am using Cloud Shell Powershell with version 7.0.0

**Comment by peombwa** [comment]
You can get the version of the MS Graph PowerShell SDK by running:
 `Get-Module Microsoft.Graph.Identity.ConditionalAccess -ListAvailable | Select Name, Version`.

**Comment by giorod3** [comment]
Sorry I thought you meant the powershell version.
```
Name                                       Version
----                                       -------
Microsoft.Graph.Identity.ConditionalAccess 0.7.0
```

**Comment by giorod3** [comment]
@peombwa @MIchaelMainer any updates on this?

**Comment by peombwa** [comment]
According to [docs](https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&tabs=http#request), `IncludeApplications` should be under `Conditions` > `Applications` > `IncludeApplications`, and not `Applications` > `IncludeApplications`. Our cmdlet generator can only flatten entity properties to a max depth of 2 to avoid long parameter names.

To pass an `includedApplications`, you should call `New-MgConditionalAccessPolicy` like this:
`New-MgConditionalAccessPolicy -Conditions @{applications = @{includeApplications = @($appId)}; users = @{includeGroups = 'None'}} -State 'disabled' -GrantControlBuiltInControls @('mfa') -GrantControlOperator 'OR'`

You can discover what a cmdlet accepts by running ` Get-Help New-MgConditionalAccessPolicy`.

**Comment by giorod3** [comment]
@peombwa Thank you for the clarification! I will try this out
