### ISSUE TITLE
Remove-MgTeam: Method Not Allowed and incorrect example

### ISSUE THREAD

**Issue by Lyx09** [microsoftgraph/msgraph-sdk-powershell#2841]
### Describe the bug

I'm working on a project where I need to delete unused Teams. I'm trying to use the "Remove-MgTeam" command with the "-TeamId" parameter, but I get the following error:
![1](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22379196/5314704c-3e14-4799-b236-5dd7f25ead4c)

The team exists, and I have do have permissions to delete the Team:
![6](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22379196/09985be6-015c-4203-a861-eb9e2bd491ba)

Trying to reach the endpoint directly, using Invoke-MgGraphRequest instead gives the same result (as expected):
![2](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22379196/75133cd1-ad48-4909-90aa-9e063e645f82)

The enpoint is defined when using "Find-MgGraphCommand":
![7](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22379196/059f4080-7198-42d7-9c31-10f2e2f32776)

The endpoint does not seem to allow the "DELETE" method, but the "GET" method works:
![3](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22379196/3dbaa740-dcdd-4277-a094-389797c9041c)

Moreover, the documentation and Get-Help shows incorrect examples:
![4](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22379196/45a78583-67f8-4fbd-aec1-507a8d98e855)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22379196/6c3e899a-17a4-4a0e-a9f7-1ae451b921d6)

### Expected behavior

The team should be deleted, no errors should be thrown.
Documentation should include example of Remove-MgTeam instead of Update-MgTeam

### How to reproduce

1. Connect to MgGraph
`Connect-MgGraph`
3. Execute Remove-MgTeam with the "-TeamId" parameter:
`Remove-MgTeam -TeamId "{teamid}"`

### SDK Version

```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.19.0                Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext…}
Script     2.19.0                Microsoft.Graph.Teams               {Add-MgChatMember, Add-MgTeamChannelMember, Add-MgTeamMember, Add-MgTeamPrimaryChannelMember…}
```

### Known Workarounds

Use MicrosoftTeams module instead with the "Remove-Team" and "-GroupId" parameter
![5](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/22379196/1d5f6517-9443-48fa-93a7-bcf1b5f43617)

### Debug output

<details><summary>Click to expand log</summary>
Note: identifying information has been removed

```
DEBUG: [CmdletBeginProcessing]: - Remove-MgTeam begin processing with parameterSet 'Delete'.
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.
DEBUG: [Authentication]: - Scopes: [DeviceManagementApps.ReadWrite.All, DeviceManagementConfiguration.ReadWrite.All, DeviceManagementManagedDevices.PrivilegedOperations.All, DeviceManagementManagedDevices.ReadWrite.All, Directory.AccessAsUser.All, Group.ReadWrite.All, openid, Organization.Read.All, profile, User.Read, User.Read.All, User.ReadWrite.All, email].

Confirm
Are you sure you want to perform this action?
Performing the operation "Remove-MgTeam_Delete" on target "Call remote 'DELETE /teams/{team-id}' operation".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
DELETE

Absolute Uri:
https://graph.microsoft.com/v1.0/teams/{teamid}

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.22631; fr-FR),PowerShell/2024.2.2
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell/2.19.0
client-request-id             : {client-request-id}

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
MethodNotAllowed

Headers:
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : {request-id}
client-request-id             : {client-request-id}
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"{DataCenter}","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"{RoleInstance}"}}
Date                          : Tue, 09 Jul 2024 14:00:19 GMT

Body:
{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2024-07-09T14:00:19",
      "request-id": "{request-id}",
      "client-request-id": "{client-request-id}"
    }
  }
}


Remove-MgTeam_Delete: 

Status: 405 (MethodNotAllowed)
ErrorCode: UnknownError
Date: 2024-07-09T14:00:19

Headers:
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : {request-id}
client-request-id             : {client-request-id}
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"{DataCenter}","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"{RoleInstance}"}}
Date                          : Tue, 09 Jul 2024 14:00:19 GMT

DEBUG: [CmdletEndProcessing]: - Remove-MgTeam end processing.

```
</details>

### Configuration

$PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
- OS: Windows 11
- Architecture: x64

**Comment by Eavzz** [comment]
Yes, i have the same problem, that infortunate...
@Lyx09 If u find the solution please contact me.
Thx

**Comment by timayabi2020** [comment]
@Lyx09 thank you for logging this issue and apologies for the experience you are having with that cmdlet. Having used the both the cmdlet and ``Invoke-MgGraphCommand`` cmdlet, clearly points to an API issue where ``DELETE`` operation is not supported. 
I've also tried the request on [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and got the same result.
<img width="911" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/4e9e2894-5a14-4439-9014-1cbd0cb713e7">

Further investigations also revealed that the documentation for that particular API is not available here https://learn.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0.

Unfortunately, for API related issues/questions we are not best placed to give an answer. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.

You can also consider archiving the team as described [here](https://learn.microsoft.com/en-us/graph/api/team-archive?view=graph-rest-1.0&tabs=http)

**Comment by Lyx09** [comment]
Thank you for your reply. I'll do as you said. However, even though the endpoint is broken, the examples are still incorrect (Get-Help).

**Comment by Lyx09** [comment]
I contacted the Microsoft support, and they suggested I use an alternative endpoint to delete a team, which I did not think about: `Remove-MgGroup -GroupId $groupId`
It works in a similar way as `Remove-MgTeam`.

**Comment by timayabi2020** [comment]
@Lyx09 thanks for noticing the examples issue. It will be resolved in the next release.

**Comment by Lyx09** [comment]
Thank you @timayabi2020.

As a final comment to close this issue, I'd like to add the Microsoft support response I got that confirms that the DELETE /teams/{team-id} endpoint is not valid:
![image](https://github.com/user-attachments/assets/50b61f3b-2698-421e-a945-81d343594576)

Regards,
