### ISSUE TITLE
Get-MgUser terminating PowerShell 5 shell

### ISSUE THREAD

**Issue by robinmalik** [microsoftgraph/msgraph-sdk-powershell#286]
Hi,

The following works fine under PowerShell 7+: `$AADAllUsers = Get-MgUser -All:$true -Property Id,UserPrincipalName -ErrorAction Stop`

Under PowerShell 5.1 I get: `Process is terminated due to a StackOverFlowException` and then the shell exits completely. It doesn't matter if this line is within a try/catch or not - it still terminates the shell.

```                                                                                 
PSVersion                      5.1.19041.1                                                                             
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1                                                                            
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

Dot NET:

```
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926 
Windows Presentation Foundation  3.0.6920.4902 
v3.5                             3.5.30729.4926
Client                           4.8.04084     
Full                             4.8.04084     
Client                           4.0.0.0       
```

Calling with `-Verbose` and `-Debug` doesn't give any useful information as far as I can see. 
[AB#7420](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7420)

**Comment by MIchaelMainer** [comment]
Can you use Fiddler to check that the requests are being sent as expected and share the results with us?
Are you using PowerShell Remoting?
Also, what are the max memory allocated for PowerShell 5?

**Comment by robinmalik** [comment]
Hi. Thanks for the reply. No remoting, nor is PowerShell configured for WinRM (`WSMan:\localhost\Shell` doesn't exist). The problem can be replicated with something as simple as:

```
Connect-Graph -ClientId $DeploymentDetails.ApplicationId -TenantId $DeploymentDetails.TenantId -CertificateThumbprint $DeploymentDetails.CertificateThumbprint -ErrorAction Stop
$AADAllUsers = Get-MgUser -All:$true -Property Id,UserPrincipalName
```
At the point of shell termination it was using 150MB of RAM.

I'll take a look at Fiddler later.

**Comment by robinmalik** [comment]
Before looking at Fiddler, I've confirmed the same behaviour on a separate Windows 10 machine (different build):

```                                                                               
PSVersion                      5.1.18362.752                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.18362.752                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

Dot NET:
```
Client      4.8.03752
Full        4.8.03752
Client      4.0.0.0  
```

**Comment by peombwa** [comment]
@robinmalik How many users do you have in your tenant?

I'm able to make the same call successfully against a tenant with 2,020 users:
![image](https://user-images.githubusercontent.com/7061532/87207137-0f095280-c2c0-11ea-82fa-0d4c1d285493.png)

**Comment by DaveyRance** [comment]
I also have the same issue and was able to replicate. I have more than 20k users.

**Comment by robinmalik** [comment]
@peombwa - As counted with Get-AzureADUser: 30976.

**Comment by twfce** [comment]
We have the same problem with 492698 users (according to Get-AzureADUser).

**Comment by peombwa** [comment]
Please see the resolution at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/949#issuecomment-989409428.

This is an issue with PowerShell 's 5.1 default memory allocation. Consider using PowerShell 7+ to fetch large data sets.
