### ISSUE TITLE
New-MgIdentityUserFlow command not working with option UserFlowTypeVersion 2

### ISSUE THREAD

**Issue by hamedur-rahiman** [microsoftgraph/msgraph-sdk-powershell#287]
New-MgIdentityUserFlow command not working with option UserFlowTypeVersion 2 but when I use UserFlowTypeVersion 1 it worked.

PS C:\Windows\system32> New-MgIdentityUserFlow -Id B2C_test_register -UserFlowType signUp -UserFlowTypeVersion 2
New-MgIdentityUserFlow : There is a problem with the service.
At line:1 char:1
+ New-MgIdentityUserFlow -Id B2C_test_register -UserFlowType signUp -Us ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ body = Micros...ntityUserFlow }:<>f__AnonymousType3`1) [New-MgIdent
   ityUserFlow_CreateExpanded], Exception
    + FullyQualifiedErrorId : AADB2C90063,Microsoft.Graph.PowerShell.Cmdlets.NewMgIdentityUserFlow_CreateExpanded

PS C:\Windows\system32> New-MgIdentityUserFlow -Id B2C_test_register -UserFlowType signUp -UserFlowTypeVersion 1

Id                      UserFlowType UserFlowTypeVersion
--                      ------------ -------------------
B2C_1_B2C_test_register signUp       1

I tried this on different tenants where I have already created user flow v2 using "Create User Flow" UI option.
PS C:\Windows\system32> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 
[AB#7421](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7421)

**Comment by MIchaelMainer** [comment]
This is likely a service issue. Can you reproduce the error by using Graph Explorer? Please share the results here.

**Comment by peombwa** [comment]
Closing this due to no response. Please reopen if the error is still present.
