### ISSUE TITLE
Error messages should contain the list of required permissions 

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#2873]
### Is your feature request related to a problem? Please describe the problem.

When you run a command without having required permissions, you get a generic "insufficient privileges" error message.
It would be more efficient if the error message contains the list of required permissions.

### Describe the solution you'd like.

As part of the security improvements, Microsoft Graph PowerShell commands should start outputting error messages with the list of required permissions instead of the generic "insufficient privileges" and similar messages.

Marking the least privileged permission too.

**Comment by timayabi2020** [comment]
Hi @alexandair this is a feature that needs to be added at Microsoft Graph API level then cascaded to all Microsoft Graph SDKs. Therefore, I would advise that you open an issue here https://developer.microsoft.com/en-us/graph/support so that API owners can plan to have the feature added.
