### ISSUE TITLE
Import Graph module fails with Could not load file or assembly 'Azure.Core, Version=1.39.0.0, Culture=neutral,  PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified

### ISSUE THREAD

**Issue by kpinel** [microsoftgraph/msgraph-sdk-powershell#2880]
### Describe the bug

Log into Graph in Azure Runbook

### Expected behavior

Log into Graph

### How to reproduce

```
Import-Module Microsoft.Graph.Authentication
Connect-MgGraph -Identity
```

### SDK Version

2.21.0

### Latest version known to work for scenario above?

2.20.0

### Known Workarounds

Roll back modules to 2.20.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

Azure runbook using both PowerShell 7 and 5

### Other information

I have other environments running 2.20.0 that are working as expected.
Error output
Error: Import-Module : Could not load file or assembly 'Azure.Core, Version=1.39.0.0, Culture=neutral, 
PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified.
At line:17 char:1
+ Import-Module Microsoft.Graph.Authentication -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
 

Error: Connect-MgGraph : The 'Connect-MgGraph' command was found in the module 'Microsoft.Graph.Authentication', but the 
module could not be loaded. For more information, run 'Import-Module Microsoft.Graph.Authentication'.
At line:18 char:1
+ Connect-MgGraph -Identity -NoWelcome
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-MgGraph:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

**Comment by timayabi2020** [comment]
@kpinel I wasn't able to reproduce your issue with 2.21.0. Could you try updating to the latest version and let us know if you are still experiencing the same issue.


![Image](https://github.com/user-attachments/assets/c522330f-47b7-44b0-b743-2bb660f6d4c9)

**Comment by jlrouzies-mantu** [comment]
Same issue here with version 2.22.0

![image](https://github.com/user-attachments/assets/558bc930-8297-42f9-9488-84a943f11a57)

![image](https://github.com/user-attachments/assets/3104b2f0-a74c-4d94-a30c-8015f0f04bf0)

**Comment by syne0** [comment]
Seems to be the same issue referenced here #2850 as both reference the azure.core.dll.

This is happening when I try to run a module that is dependent on EXO and Graph. Both EXO and Graph are on the most up to date versions on my end.

**Comment by kpinel** [comment]
I believe it's related to the Exchange 3.5.1 module and have had to roll back my Exchange module to 3.5.0 and Graph is working again.
Slowly bringing my environments up to 2.22.0 but that hasn't resolved the issue. I'll take this across to the Exchange team

**Comment by haruka-shawn** [comment]
Dear,
I get the same issue when trying to import PS modules as well.
How is it going about this issue now?
