### ISSUE TITLE
Stop-MgDeviceManagementVirtualEndpointCloudPcGracePeriod : One or more errors occurred.

### ISSUE THREAD

**Issue by ranjithckm7** [microsoftgraph/msgraph-sdk-powershell#2913]
### Describe the bug

Unable to end the Grace period of Cloud PCs

https://learn.microsoft.com/en-us/answers/questions/1857487/windows-365-end-grace-period-using-powershell-grap

### Expected behavior

Should end cloud PCs graceperiod

### How to reproduce

Run below script if you have cloud PCs in grace period status.

`# Set execution policy to bypass (if needed)
Set-ExecutionPolicy Bypass -Scope Process -Force

# Import required modules
Import-Module Microsoft.Graph.Authentication

# Connect to Microsoft Graph with appropriate permissions
Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"

# Retrieve all managed Cloud PCs and filter for those in grace period
$cloudPCs = Get-MgBetaDeviceManagementVirtualEndpointCloudPc -All | Where-Object { $_.status -eq 'inGracePeriod' }

#Get-MgBetaDeviceManagementVirtualEndpointCloudPc -All | Where-Object { $_.status -eq 'inGracePeriod' }|GM

foreach ($cloudPC in $cloudPCs)
{
    $cloudPC | Select-Object ID, ManagedDeviceName, DisplayName, ProvisioningPolicyName, Status, GracePeriodEndDateTime | Format-Table -AutoSize
    $cloudPCID = $cloudPC.ID
    Write-Host "Ending GracePeriod of $($cloudPC.ID)"
    
    try {
        Stop-MgDeviceManagementVirtualEndpointCloudPcGracePeriod -CloudPcID $cloudPCID -WhatIf
    }
    catch {
        Write-Host "Failed to stop grace period for Cloud PC ID $($cloudPCID): $_"
    }
}`

### SDK Version

2.22, 2.15

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by timayabi2020** [comment]
@ranjithckm7 Kindly share the debug output. Add a ``-Debug`` parameter at the end of the cmdlet that you suspect is throwing an error.
