### ISSUE TITLE
BackupRestore module actions still mapping to Booking module

### ISSUE THREAD

**Issue by agarwal-arjun** [microsoftgraph/msgraph-sdk-powershell#2926]
### Describe the bug

The Enable-MgBetaBackupRestore cmdlet is not working.
![image](https://github.com/user-attachments/assets/6a3cba1e-fc9e-4afa-953d-24842345fb80)

However, after installing Microsoft.Graph.Beta.Bookings , it is working fine.

Following are few more cmdlets which are not showing up in BackupRestore module but are part of booking, but should be part of BackupRestore module.

![image](https://github.com/user-attachments/assets/8a107eab-fa57-4943-aeae-d77ae42365be)

### Expected behavior

Expect following cmdlet to be part of BackupRestore module.

![image](https://github.com/user-attachments/assets/4a8836a8-1b56-45b9-a3bb-be046d187754)

### How to reproduce

On running below-

Find-MgGraphCommand -Uri "beta/solutions/backupRestore/enable"

we are getting following response-
![image](https://github.com/user-attachments/assets/191157f8-3d0b-442a-95d2-1fcdbd480017)

which suggests that the command is not in BackupRestore module.

### SDK Version

2.22.0

### Latest version known to work for scenario above?

NA

### Known Workarounds

NA

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by Ndiritu** [comment]
closing as similar to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2926

**Comment by Ndiritu** [comment]
Wrong link, similar to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2957
