### ISSUE TITLE
Documentation for Get-MgBetaOnPremisePublishingProfileConnectorGroup Gives 404

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#2949]
### Describe the bug

The documentation pages on learn.microsoft.com for the Get-MgBetaOnPremisePublishingProfileConnectorGroup cmdlet returns a 404

### Expected behavior

The page would show up as expected and provide details about the cmdlet.

### How to reproduce

1- Do a search on the web for Get-MgBetaOnPremisePublishingProfileConnectorGroup
2 - Click on the learn.microsoft.com link

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by timayabi2020** [comment]
Hi @NikCharlebois the issue was resolved, please confirm.
