### ISSUE TITLE
Install Microsoft.Graph.Authentication 0.7.1 causes issue

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#295]
Starting earlier today, Azure GitHub Actions that were using Microsoft.Graph.Authentication started showing a weird error:

Import-Module : An instance of GraphSession already exists. Call Initialize(Func<GraphSession>, bool) to overwrite it.
2020-07-10T18:38:17.6631140Z At C:\Program 
2020-07-10T18:38:17.6631789Z Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\0.7.0\Microsoft.Graph.Authentication.psm1:13 char:9
2020-07-10T18:38:17.6632889Z + $null = Import-Module -Name (Join-Path $PSScriptRoot '.\bin\Microsoft ...

I assumed that installing the new 0.7.1 version would fix it, but now other dependent modules are complaining that they still need 0.7.0. Ex:

Import-Module : The required module 'Microsoft.Graph.Authentication' with version '0.7.0' is not loaded. Load the 
module or remove the module from 'RequiredModules' in the file 'C:\Program 
Files\WindowsPowerShell\Modules\Microsoft.Graph.Groups.Planner\0.7.0\Microsoft.Graph.Groups.Planner.psd1'.

These are brand new installs of 0.7.1, not updates from a previous version.

**Comment by peombwa** [comment]
@NikCharlebois, sorry about that. You actions got a partial release of 0.7.1. `Update-Module Microsoft.Graph` should resolve the dependency issue. Also, the GraphSession exception as been fixed in 0.7.1, see [release notes](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/v0.7.1).
