### ISSUE TITLE
Conflict with AZ.Accounts

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#2952]
### Describe the bug

The module has a conflict with the Az.Account 3.0.4 module. Once a Graph module is imported, it breaks the connection to Microsoft Azure via Connect-AzAccount.

### Expected behavior

Importing Microsoft.Graph modules in a session should not break the Connect-AzAccount flow.

### How to reproduce

Import-Module Microsoft.Graph.Application
Connect-azAccount -CertificateThumbprint xxx `
    -ApplicationId xxx `
    -TenantId xxx

### SDK Version

2.23.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by timayabi2020** [comment]
@NikCharlebois thanks for logging this issue.  What is the exact error you are getting? Please share your debug output
