### ISSUE TITLE
Access Package Assignment Failing - "Connected Organization Not Found"

### ISSUE THREAD

**Issue by AKMWali** [microsoftgraph/msgraph-sdk-powershell#2958]
### Describe the bug

We successfully connected to the organization to retrieve users and assign the associated access package. However, we're still encountering an error stating that no connected organization was found.
<img width="504" alt="2" src="https://github.com/user-attachments/assets/c373fe5e-5061-4592-9458-63c69e5aa60b">
<img width="894" alt="1" src="https://github.com/user-attachments/assets/6dd626c6-a67a-46cc-875c-01123a0658fa">

### Expected behavior

It should successfully add the user as an external user from the connected organization and assign them to the associated access package.

### How to reproduce

New-MgBetaEntitlementManagementAccessPackageAssignmentRequest -AccessPackageId $engineerAccessPackage.Id -AssignmentPolicyId $engineerPolicy.Id -TargetEmail $email

### SDK Version

2.23.0

### Latest version known to work for scenario above?

2.23.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>
<img width="504" alt="2" src="https://github.com/user-attachments/assets/d25f4c21-e88f-4228-ba2d-c5dffbb658ae">
<img width="894" alt="1" src="https://github.com/user-attachments/assets/8bd611a4-aea3-4275-9e7d-86ef4cb7db6b">

**Comment by timayabi2020** [comment]
Hi @AKMWali please add a ``-Debug`` parameter and share the results.

**Comment by AKMWali** [comment]
The issue has been resolved. The failure was due to a duplicate entity. Thank you!
