### ISSUE TITLE
Invoke-GraphRequest fails for the following scenarios.

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#296]
1. When a GET call with a query parameter is made to `Invoke-GraphRequest`, it throws a null exception at [InvokeGraphRequest.cs#L352](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Authentication/Authentication/Cmdlets/InvokeGraphRequest.cs#L352) because we are calling `.FormatDictionary()` on a null `bodyAsDictionary`. We should check if `Body` is null before attempting to convert it to an `IDictionary`.
**Repro** - `Invoke-GraphRequest -Uri 'https://graph.microsoft.com/beta/groups?$count=true'`.

2. When a PowerShell hashtable with values is passed to `-Headers` parameter, a type conversion exception is thrown. This is because the parameter is written to accept `IDictionary<string,string>`, and not `IDictionary`. A non-generic dictionary maps to a PowerShell hashtable.
**Repro** - `Invoke-GraphRequest -Uri 'https://graph.microsoft.com/beta/groups?$count=true' -Headers @{"ConsistencyLevel" = "eventual"}`

**Comment by peombwa** [comment]
Also, returned response should be fully deserialized. It currently returns the following error when one tries to retrieve a collection of entities:
![image](https://user-images.githubusercontent.com/7061532/88216891-9638bd80-cc12-11ea-94f1-8f6d71755162.png)

**Comment by peombwa** [comment]
I've fixed some of these items in this branch as part of a demo I was making. Feel free to use it https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/po/IGRFix

**Comment by finsharp** [comment]
Resolution:
The outgoing request looks like this 
![image](https://user-images.githubusercontent.com/1641829/88227074-b9488900-cc75-11ea-8a69-1180264e5ddd.png)

**Comment by finsharp** [comment]
Count can be Passed through the `-Body` like shown below.
![image](https://user-images.githubusercontent.com/1641829/88334559-a3e96280-cd3a-11ea-9e27-072eab4c8f3d.png)
