### ISSUE TITLE
Update-MgGroup   Returns "The server responded with an unrecognized response, Status: OK"

### ISSUE THREAD

**Issue by benjimatt** [microsoftgraph/msgraph-sdk-powershell#298]
Update-MgGroup -HideFromOutlookClients:$False -GroupId $id

The Above command works when Executed but always returns an error which I now have to catch separately.  I'm assuming that this is a bug.  

Message: 
`The server responded with an unrecognized response, Status: OK`

Exception Type:
`Microsoft.Graph.PowerShell.Runtime.RestException`1[[Microsoft.Graph.PowerShell.Models.IOdataError, Microsoft.Graph.Groups.Group.private, Version=0.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]`

**Comment by peombwa** [comment]
This is a duplicate of #110. The bug has already been fixed via #272 and will be released in 0.9.0.
