### ISSUE TITLE
Send-MgUserMail: Issue with special characters

### ISSUE THREAD

**Issue by shredstick** [microsoftgraph/msgraph-sdk-powershell#2996]
### Describe the bug

Hello

Im trying to send an E-Mail using the following code:

```
$message = @{
    Subject      = 'TEST ÄÖÜ'
    Body         = @{
        ContentType = 'HTML'
        Content     = 'TEST ÄÖÜ'
    }
    ToRecipients = @(
        @{
            EmailAddress = @{
                Address = "test@test.com"
            }
        }
    )
}

Send-MgUserMail -UserId $SendEmailAccount -Message $message
```

Notice that im trying to send an email with special characters like Ä,Ö or Ü.
The delivery of the email works fine but somewhere along the way the special characters (ÄÖÜ) get messed up.
This is how the email looks like in the recipients mailbox:

![image](https://github.com/user-attachments/assets/1d6d065b-ff9d-40dc-8d70-9f6aaa8b391a)

I'm using the following versions:
Microsoft.Graph.Users.Actions: 2.15.0
Microsoft.Graph.Authentication: 2.15.0

Every help is greatly appreciated.

### Expected behavior

I expect the email to be delivered and the special characters to be handled accordingy and displayed properly.

### How to reproduce

Send an email containing special characters using something like this:

```
$message = @{
    Subject      = 'TEST ÄÖÜ'
    Body         = @{
        ContentType = 'HTML'
        Content     = 'TEST ÄÖÜ'
    }
    ToRecipients = @(
        @{
            EmailAddress = @{
                Address = "test@test.com"
            }
        }
    )
}

Send-MgUserMail -UserId $SendEmailAccount -Message $message
```

### SDK Version

2.15.0

### Known Workarounds

I have not found a workaround.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

Windows Server 2016 Version 1607

Name                           Value
----                           -----
PSVersion                      5.1.14393.7330
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.7330
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by timayabi2020** [comment]
Hi @shredstick thank you for raising this issue. Are there any errors thrown by the cmdlet? Could you please share the debug output?
