### ISSUE TITLE
Disconnect-Graph doesn't work unless you close the powershell session

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#30]
## Steps to repro:

Call Connect-Graph and sign in.
Call Disconnect-Graph
Call Connect-Graph again.

## Observed behavior
You will automatically get logged in and the old token cache will be recreated on disk.

## Expected behavior
You will be asked to log in again.

If you close the PowerShell terminal after doing Disconnect-Graph then next time you open the PowerShell window Connect-Graph will work as normal.   I think we just need to re-create the Application upon doing Disconnect-Graph.

**Comment by TheCloudCrafter** [comment]
Connect-Graph does not work when connecting with connect-msgraph. only works for connect-mggraph
Part of the microsoft.graph.intune module
