### ISSUE TITLE
Using Teams mentions, after a simple example please

### ISSUE THREAD

**Issue by thenecroscope** [microsoftgraph/msgraph-sdk-powershell#301]
Hi,

I'm just starting to play around with the Teams Graph module. So far so good, but...how do I use the Mentions parameter/method/switch, can anybody give a simple example please just to get my up and running. Also appreciate this is still quite new, can anybody point me to some documentation for the Teams MG module by any chance?

Many thanks,
Steve

**Comment by ddyett** [comment]
@peombwa  ddo we happen to have a sample handy?

**Comment by peombwa** [comment]
@thenecroscope, you can mention a user in Teams channel message like this:
``` 
$UserToMention = Get-MGUser -UserId $userUPN

New-MgTeamChannelMessage -ChannelId $ChannelId -TeamId $TeamId `
    -BodyContentType "html" `
    -BodyContent "Welcome to the channel! <at id='0'>$($UserToMention.DisplayName)</at>" `
    -Mentions @( `
        @{ `
            id          = 0; `
            mentionText = $UserToMention.DisplayName; `
            mentioned   = @{user = $UserToMention } `
        }) 
```
The sample will be updated via #310 .

**Comment by thenecroscope** [comment]
Perfect thank you! 👍
