### ISSUE TITLE
Get-MgTeamTemplate does not work

### ISSUE THREAD

**Issue by RyanMerton** [microsoftgraph/msgraph-sdk-powershell#302]
In addition to the issue logged in issue [119](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/119)  where New-MgTeam fails to execute because the Team Template binding is broken, the method for fetching the template - Get-MgTeamTemplate - returns a 404 not found.

So even if New-MgTeam was able to be executed properly, how do we get the Template details to pass into the -Template parameter?  I'm also not able to this endpoint in Graph Explorer - also a 404.

**Comment by peombwa** [comment]
`Get-MgTeamsTemplate` shouldn't have been generated in the first place, **beta/teamsTemplates** is an invalid path. We will remove all the `*-MgTeamsTemplate` cmdlets in the next release.

Teams template id is just a string that is only used when creating a team. Here is a complete list of accepted templates - https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-templates#what-are-base-template-types.

cc/ @ddyett, the CSDL represents teamsTemplates as an EntitySet hence the reason why it was generated.

**Comment by peombwa** [comment]
Related to #223
