### ISSUE TITLE
Get-MgServicePrincipa nor Get-MgServicePrincipalAppRoleAssignment return values for AppRoleAssignedTo

### ISSUE THREAD

**Issue by tikesavage** [microsoftgraph/msgraph-sdk-powershell#3027]
### Describe the bug

when using either cmdlet  there is not value returned.  but the graph API call works fine

Get-MgServicePrincipa nor Get-MgServicePrincipalAppRoleAssignment return values for AppRoleAssignedTo

### Expected behavior

expected behavior is to return the values that are returned using the graph api call, principalDisplayName and ID

https://graph.microsoft.com/beta/servicePrincipals/{APPID}/appRoleAssignedTo

### How to reproduce

oduleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Microsoft.Graph.Applications        {Add-MgApplicationKey, Add-MgApplicationPassword, Add-MgServicePrincipalKey, Add-MgServicePrincipalPassword…}

Get-MgServicePrincipal -Filter "displayName eq 'Xtra Chef'" | fl

AccountEnabled                         : True
AddIns                                 : {}
AlternativeNames                       : {}
AppDescription                         : 
AppDisplayName                         : Xtra Chef
AppId                                  : REDACTED
AppManagementPolicies                  : 
AppOwnerOrganizationId                 : REDACTED
**AppRoleAssignedTo                      :** 

Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId "APP_ID_HERE" 

* no output at all. no error.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by timayabi2020** [comment]
@tikesavage thank you for logging this request.  I was not able to reproduce your issue because the cmdlets are working as expected. Please upgrade to the latest SDK version ``2.25.0`` and try again. 
![image](https://github.com/user-attachments/assets/1c313692-c981-492b-ad75-88e906317fdb)

**Comment by tikesavage** [comment]
Hi  @timayabi2020     thanks for getting back to me!

I  installed the 2.25.0  and i imported that version when running. still an issue for me.  my account and 2 groups are assigned as "users"  

![image](https://github.com/user-attachments/assets/915831df-9916-4512-9d93-10a143f4faf7)

![image](https://github.com/user-attachments/assets/ce1361f6-8081-48d9-a9eb-357ac48e6928)
![image](https://github.com/user-attachments/assets/afde6cb1-9e28-4e76-9377-6f79f43230a7)

**Comment by timayabi2020** [comment]
Hi @tikesavage as per the first comment, the issue is that you are not able to get content from ``AppRoleAssignedTo`` property. From my initial comment, I provided a cmdlet ``Get-MgServicePrincipalAppRoleAssignedTo`` which corresponds to the endpoint ``https://graph.microsoft.com/beta/servicePrincipals/{APPID}/appRoleAssignedTo`` because I realized that this particular endpoint is the one that has values for the property in question.
Have you tried the cmdlet that I had suggested?

**Comment by tikesavage** [comment]
oh sorry i screen capped the wrong cmdlet in the first one. but issue is the same.

PS C:\Users\username> Get-MgServicePrincipalAppRoleAssignedTo -ServicePrincipalId "9875c76b-xxxxx-xxxxxxxxx-ec16d6325480"
>>
Get-MgServicePrincipalAppRoleAssignedTo_List: Resource '9875c76b-xxxxx-xxxxx-xxxxx-ec16d6325480' does not exist or one of its queried reference-property objects are not present.

Status: 404 (NotFound)
ErrorCode: Request_ResourceNotFound
Date: 2024-12-03T18:22:37

Headers:
Cache-Control                 : no-cache
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 120ddbf0-288d-4451-a2c9-f177bc6d5d76
client-request-id             : 06dd2562-681f-467c-9389-faa2bafcc515
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"East US","Slice":"E","Ring":"5","ScaleUnit":"007","RoleInstance":"MN1PEPF0001087E"}}
x-ms-resource-unit            : 1
Date                          : Tue, 03 Dec 2024 18:22:36 GMT
