### ISSUE TITLE
Get-MgBetaRoleManagementExchangeRoleDefinition is not recognized

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-powershell#3040]
### Describe the bug

Trying to call Get-MgBetaRoleManagementExchangeRoleDefinition, but it returns

The term 'Get-MgBetaRoleManagementExchangeRoleDefinition' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was 
     | included, verify that the path is correct and try again.

### Expected behavior

Can call Get-MgBetaRoleManagementExchangeRoleDefinition

### How to reproduce

Execute:

Get-MgBetaRoleManagementExchangeRoleDefinition

### SDK Version

2.25

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Other information

Get-MgBetaRoleManagementDirectoryResourceNamespace works

**Comment by timayabi2020** [comment]
@MartinM85 thank you for logging this issue. Kindly share the output of these commands. ``Get-Module -Name Microsoft.Graph.Beta -ListAvailable`` and ``$PSVersionTable``

**Comment by MartinM85** [comment]
Hi @timayabi2020, 
the output of the `Get-Module -Name Microsoft.Graph.Beta -ListAvailable` command is:

```


    Directory: C:\Users\mm\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.25.0     Microsoft.Graph.Beta
Manifest   2.17.0     Microsoft.Graph.Beta
Manifest   2.12.0     Microsoft.Graph.Beta
Manifest   2.11.1     Microsoft.Graph.Beta
Manifest   2.10.0     Microsoft.Graph.Beta


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.9.1      Microsoft.Graph.Beta
```

The output of the `$PSVersionTable` command is:

```
Name                           Value
----                           -----
PSVersion                      5.1.22621.4249
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.4249
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by timayabi2020** [comment]
Hi @MartinM85  I think there is a module conflict. You can try delete all the other module versions and restarting your PowerShell session.

**Comment by MartinM85** [comment]
Hi @timayabi2020, removing all older module versions resolved the issue. Thanks for help. I will close this.
