### ISSUE TITLE
Connect-Graph : Device code terminal timed-out after 120 seconds. Please try again.

### ISSUE THREAD

**Issue by DaveyRance** [microsoftgraph/msgraph-sdk-powershell#305]
It seems that this morning connection to Graph is not working.

Code to reproduce.

Open a fresh windows Sandbox
Install-module Microsoft.Graph -Force
Connect-Graph -Scopes 'User.Read'

Then after 2 minutes you will get the error.
Connect-Graph : Device code terminal timed-out after 120 seconds. Please try again.
At line:1 char:1
+ Connect-Graph -Scopes 'User.Read'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-Graph], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectGraph

I had another machine that was still running from yesterday and i am now getting.
Get-MgReportCredentialUserRegistrationDetail : Failed to do premium license check from ADGraph
At line:4 char:9
+         $MGUser = Get-MgReportCredentialUserRegistrationDetail -Filte ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ PageSize = , ...ndProperty =  }:<>f__AnonymousType2`8) [Get-MgReportCre...tionDetail_List], Exception
    + FullyQualifiedErrorId : Authentication_ApplicationHasNoDirectoryReadAccess,Microsoft.Graph.PowerShell.Cmdlets.GetMgReportCredentialUserRegistrationDetail_List

**Comment by ddyett** [comment]
@daveyrance is this still a problem and if so can you tell us more about the environment you are using. This sounds like you never saw the message show up to provide the link to sign in.  We have issues with that for things like Powershell ISE.

**Comment by DaveyRance** [comment]
Hi @ddyett just checked this morning and it is now looking good.

A good description would be the message never showed up to provide the link to sign in.

But all good thanks.
