### ISSUE TITLE
Get-MgUserContactFolder -> Access Denied

### ISSUE THREAD

**Issue by wasgehtsiedasan999** [microsoftgraph/msgraph-sdk-powershell#307]
When using "Get-MgUserContactFolder -UserID someuser@domain.de" I get an "Access is denied. Check credentials and try again." error.

Am I not using the correct scopes when connecting or do I need to set any permissions first?

Also is there any way to check for all available scopes?

**Comment by wasgehtsiedasan999** [comment]
Nevermind, I found out!

The correct Scope is "Contacts.ReadWrite" BUT you also have to enable it first in Azure!

Open this URL:
https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/ConsentPoliciesMenuBlade/Permissions

and add a permission, chose Microsoft Graph, search for "Contacts" and check the "Contacts.ReadWrite" one and add it.

**Comment by eriksrocha** [comment]
It doesn't work for me.
