### ISSUE TITLE
Sending Teams Message Automatically

### ISSUE THREAD

**Issue by thenecroscope** [microsoftgraph/msgraph-sdk-powershell#308]
I'm not able to Send a Teams Message non-interactively, using the powershell cmdlet Connect-Graph.

It looks as though to be able to send messages to Teams you need to use Azure Delegated permissions. I can use delegated permissions via the connect-graph cmdlets and this is working fine for me. But I need to be able to this automatically, non interactively.   

If I authenticate via the Certificate, this also works for me, but then I'm not able to send any messages to Teams as I'm using the incorrect Authentification method (Application)

I can achieve this using Powershell going directly to Teams API, but I'm trying to avoid using this approach and just use the new Graph Powershell module?

Is there anyway around this ?

Many thanks,
Steve 
[AB#7426](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7426)

**Comment by thenecroscope** [comment]
Actually perhaps this is just user error on my part or its a missing feature.

How long does the connect-graph authentication last (not using certificate method). I mean, is there an expiry time on the connection, also where is this token stored. Are the details held in the browser cache. 

I'm trying to run some commands as a scheduled task,  I'm interested to find out if this is a viable option if the connect-graph does not expire for x number of days. Hopefully that makes some sense.

thanks again

**Comment by peombwa** [comment]
@thenecroscope This is by design. The API does not support sending messages using application permission - https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=http#permissions-for-channel.

I would suggest you open a feature request here https://developer.microsoft.com/en-us/graph/support.
