### ISSUE TITLE
MgUserContact(FolderContact) Parameters missing

### ISSUE THREAD

**Issue by wasgehtsiedasan999** [microsoftgraph/msgraph-sdk-powershell#309]
I am using the command "New-MgUserContactFolderContact" to add contacts to contact lists in Outlook for my users.

I used this site to find parameters:
https://developer.microsoft.com/de-de/graph/graph-explorer

I can successfully create a contact with "givenName" and "surname" but as soon as I add "businessPhones", "mobilePhone" or "EmailAddresses" I get an error saying the parameter cannot be found. 

Is there any other documentation where I can find all parameters for the powershell commands or is this a bug? 
[AB#7427](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7427)

**Comment by ddyett** [comment]
@wasgehtsiedasan999  can you attach a snippet of the powershell call?

**Comment by wasgehtsiedasan999** [comment]
Sure! This one works:

`New-MgUserContactFolderContact -UserID me@domain.de -givenName "givenname" -surname "surname" -ContactFolderID "<left out here>"`

This one doesn't work:
`
New-MgUserContactFolderContact -UserID me@domain.de -givenName "givenname" -surname "surname" -businessPhones "0123341234" -ContactFolderID "<left out here>"`

Error:
`New-MgUserContactFolderContact : There was no parameter found that matches the parameter "businessPhones"`
(roughly translated)

Same with the parameter "mobilePhone" or "emailAddresses". At first I thought it's because the syntax needs to be different and I need to add "name" and "address" for "emailAddresses" (How do I even do this in the powershell module!?) but mobilePhone doesn't work either and the error message would be different.

Same with the command "New-MgUserContact".

**Comment by peombwa** [comment]
@wasgehtsiedasan999 Please note that `-BusinessPhones` parameter is only available in Microsoft Graph [v1.0](https://docs.microsoft.com/en-us/graph/api/resources/contact?view=graph-rest-1.0#properties) and not [beta](https://docs.microsoft.com/en-us/graph/api/resources/contact?view=graph-rest-beta#properties). 

`New-MgUserContactFolderContact -UserId $UserId -ContactFolderId $ContactFolderId  -GivenName "givenname" -Surname "surname" -BusinessPhones "0123341234"` works in v1.0 profile as expected. Use `Select-MgProfile v1.0` to load [v1.0 profile](https://docs.microsoft.com/en-us/graph/powershell/get-started?view=graph-rest-1.0#api-version).
