### ISSUE TITLE
Using Teams mentions, how to mention the channel name instead of user

### ISSUE THREAD

**Issue by thenecroscope** [microsoftgraph/msgraph-sdk-powershell#315]
When mentioning a channel name instead of a user, I'm not getting any response back. 
This is most likely user error on my part, here is my sample script:

`$chan = Get-MgTeamChannel -ChannelId $teamsConfigItemChannelID -TeamId $teamsConfigItemTeamID

New-MgTeamChannelMessage -ChannelId $teamsConfigItemChannelID -TeamId $teamsConfigItemTeamID  -BodyContent "Hello <at id ='0'>Channel Name</at>, Test message on the channel with at mention." -BodyContentType "html"  -Mentions @( `
        @{ `
            id          = 0; `
            mentionText = $chan.DisplayName; `
            mentioned   = @{channel = $chan } `
        })`

thanks again! 
[AB#7385](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7385)

**Comment by peombwa** [comment]
This is possible. You can do this by:
``` powershell
$Mentions = @(
    @{
        id          = 0;
        mentionText = $MyTeamChannel.DisplayName;
        mentioned   = @{user = $MyTeamChannel }
    })

New-MgTeamChannelMessage -TeamId $MyTeam.Id -ChannelId $MyTeamChannel.Id 
-Body @{
    ContentType = "html";
    Content     = "Welcome to the channel! <at id='0'>$($MyTeamChannel.DisplayName)</at>"
}
-Mentions $Mentions -Debug
```
