### ISSUE TITLE
Issue with Connect-Graph on Linux platform

### ISSUE THREAD

**Issue by Al-mcne** [microsoftgraph/msgraph-sdk-powershell#316]
Tried to use the MSGraph Powershell module on the Linux platform.
1. Executed **Connect-Graph** and received new successfully connected session.
2. Any attempts to execute other cmdlets (for example **get-MgUser**) can't see this session and required to repeat devicelogin.

The same order of commands on Windows platform has no issues.

PS /opt> Connect-Graph -Scopes "User.Read.All"
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code E44NCJ5QU to authenticate.
Welcome To Microsoft Graph!
PS /opt> get-MgUser -UserId AdeleV@midm.onmicrosoft.com |fl
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ELR729SLD to authenticate.
 
[AB#7386](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7386)

**Comment by Al-mcne** [comment]
System info:
PS /opt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 4.12.14-120-default #1 SMP Thu Nov 7 16:39:09 UTC 2019 (fd9dc36)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /opt> Get-Module -Name 'Microsoft.Graph.Authentication' | Format-List

Name              : Microsoft.Graph.Authentication
Path              : /root/.local/share/powershell/Modules/Microsoft.Graph.Authentication/0.7.1/Microsoft.Graph.Authentication.psm
                    1
Description       : Microsoft Graph PowerShell Authentication Module.
ModuleType        : Script
Version           : 0.7.1
PreRelease        : 
NestedModules     : {Microsoft.Graph.Authentication}
ExportedFunctions : 
ExportedCmdlets   : {Connect-Graph, Disconnect-Graph, Get-MgContext}
ExportedVariables : 
ExportedAliases   :

**Comment by peombwa** [comment]
@Al-mcne Thanks for reporting this. Which Linux distro are you using?

**Comment by Al-mcne** [comment]
SLES (SuSE)

**Comment by BrianTJackett** [comment]
I experienced the same behavior on Ubuntu 18.04 (running under WSL 2) with PowerShell 7.0.3 when using delegated authentication.  Does not occur when using application permissions with a certificate thumbprint.  Let me know if need additional system information.

**Comment by peombwa** [comment]
This has been fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/934 and will be released as part of version `1.9.0` next week -> https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/933.
