### ISSUE TITLE
Change default sign-in behaviour to use Interactive Browser Sign-in

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#334]
This will be the default behaviour on Windows.  Linux/MacOS will use Device Code flow by default.
We need to add a parameter to enable device code flow on windows. See #142
[AB#5758](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5758)

**Comment by peombwa** [comment]
Waiting on https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1991

**Comment by finsharp** [comment]
Depends on #534

**Comment by peombwa** [comment]
This has been resolved by #618.
