### ISSUE TITLE
Add support for -AccessToken in Connect-Connect

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#335]
[AB#5757](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5757)

**Comment by peombwa** [comment]
`-accessToken` should allow customers to BYOT. The SDK won't be able to refresh the access token, and customers will have to handle refreshing the access token when it expires.
