### ISSUE TITLE
Get-MgGroupMemberWithLicenseError does not list

### ISSUE THREAD

**Issue by trevonmckay** [microsoftgraph/msgraph-sdk-powershell#344]
I am trying to retrieve a list of users in a group with a license error similar to the endpoint https://graph.microsoft.com/v1.0/groups/{groupId}/membersWithLicenseErrors however the command 
```
Get-MgGroupMemberWithLicenseError -GroupId $group.Id
```
is expecting the parameter DirectoryObjectId to have a value thus making it not possible to list the members with a license error

![image](https://user-images.githubusercontent.com/18320804/90767123-9e8c2300-e2ba-11ea-921f-c71f6afea08a.png)

**Comment by peombwa** [comment]
This has already been fixed with 1.0.1. `Install-Module Microsoft.Graph -AllowClobber -Force`.
