### ISSUE TITLE
Duplicated Commands for returning Conditional Access Policies

### ISSUE THREAD

**Issue by Donovand4** [microsoftgraph/msgraph-sdk-powershell#345]
The below commands are all part of the updated module and only the last two work. They also return the same information.

Function        Get-MgIdentityConditionalAccess                    0.9.1      Microsoft.Graph.Identity.ConditionalAccess
Function        Get-MgIdentityConditionalAccessPolicy              0.9.1      Microsoft.Graph.Identity.ConditionalAccess
Function        Get-MgPolicyConditionalAccessPolicy                0.9.1      Microsoft.Graph.Identity.Policies

**Comment by peombwa** [comment]
Unfortunately, this is something that's represented this way in the metadata. We will remove Get-MgIdentityConditionalAccess and Get-MgPolicyConditionalAccessPolicy in the next release.

**Comment by MIchaelMainer** [comment]
Fixed #348
