### ISSUE TITLE
Update-MgApplication: A parameter cannot be found that matches parameter name 'WebRedirectUris'

### ISSUE THREAD

**Issue by Josverl** [microsoftgraph/msgraph-sdk-powershell#346]
Hi,
I'm working with a script to update the redirect urls of existing app registrations , and find that the WebRedirectUris
parameter is not recognized.

``` powershell
    $redirectUris = "https://$webAppSiteName.azurewebsites.net/signin-oidc","https://$webAppSiteName.azurewebsites.net/","https://$webAppSiteName.azurewebsites.net/home/SPHostedAddinEmbedContent"
    Update-MgApplication -ApplicationId $webApp.Id -WebRedirectUris $redirectUris
```
I then recieve the error `Update-MgApplication: A parameter cannot be found that matches parameter name 'WebRedirectUris'`

```
get-module Microsoft.Graph.Identity.Application

Name              : Microsoft.Graph.Identity.Application
Path              : <redacted>\Microsoft.Graph.Identity.Application\0.9.1\Microsoft.Graph.Identity.Application.psm1
Description       : Microsoft Graph PowerShell Cmdlets
ModuleType        : Script
Version           : 0.9.1
PreRelease        :
```

**Comment by peombwa** [comment]
The parameter type changed as of version 0.9.1. With the [latest version](https://www.powershellgallery.com/packages/Microsoft.Graph/1.0.1) (1.0.1), you should set `RedirectUris` like this:
```ps
Update-MgApplication -ApplicationId $webApp.Id `
         -Web @{ `
            RedirectUris = "https://localhost:3000/" `
        }  
```

The [samples](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/9-Applications.ps1#L21) have been updated with the new parameter type.
