### ISSUE TITLE
More intelligence for paging parameters in Graph cmdlet generation

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#349]
If you invoke `Get-MgDirectoryRoleTemplate -All`, you will receive the following error message:

```none
Get-MgDirectoryRoleTemplate : This resource does not support custom page sizes. Please retry without a page size argument.
At line:1 char:1
+ Get-MgDirectoryRoleTemplate -All
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = 100, Sk...ndProperty =  }:<>f__AnonymousType4`8) [Get-MgDirectoryRoleTemplate_List], RestException`1
    + FullyQualifiedErrorId : Request_UnsupportedQuery,Microsoft.Graph.PowerShell.Cmdlets.GetMgDirectoryRoleTemplate_List
```

I believe this is expected because DirectoryRoleTemplate resources do not support pagination.

The question then is: as you are auto-generating these cmdlets, can you either leverage existing metadata (assuming you have the necessary metadata information to work with) or add additional metadata as you auto-generate the Graph cmdlets such that pagination parameters are only added to those cmdlets where pagination is supported? 
[AB#7389](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7389)

**Comment by MIchaelMainer** [comment]
We will investigate the required annotations to properly document this scenario.

**Comment by peombwa** [comment]
Closing as fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.11.0. The SDK no longer sets a fixed page size.
