### ISSUE TITLE
Incorrect verbs (Update instead of Set or Edit)

### ISSUE THREAD

**Issue by alexbuzzbee** [microsoftgraph/msgraph-sdk-powershell#358]
This module uses the verb `Update` for cmdlets that change the properties of existing objects. However, the [Approved Verbs List](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7) defines `Update` as:

> Brings a resource up-to-date to maintain its state, accuracy, conformance, or compliance. For example, the `Update-FormatData` cmdlet updates and adds formatting files to the current PowerShell console.

That is not what the `Update` cmdlets in this module do. The correct verb to use for these is `Set`, which the Approved Verbs List defines as:

> Replaces data on an existing resource or creates a resource that contains some data. For example, the `Set-Date` cmdlet changes the system time on the local computer. (The `New` verb can also be used to create a resource.) This verb is paired with `Get`.

As this is a preview module, there should not be support requirements preventing this change. If there are, aliases could be used to prevent breakage.

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. We currently align to the Azure PowerShell SDK. We will follow up on this.

**Comment by peombwa** [comment]
We should treat all HTTP Put as `Set` and Patch as `Update`.

**Comment by alexbuzzbee** [comment]
Shouldn't `PUT` be `New`?

**Comment by alexbuzzbee** [comment]
I would strongly argue against continuing to use `Update` for this type of action, as it goes against PowerShell idioms and documentation and as a result breaks PowerShell users' expectations.

It might be best to use the infrequently-used `Edit` verb for `PATCH` methods; the Approved Verbs List defines it as:

> Modifies existing data by adding or removing content.

The documentation for `VerbsData.Edit` says:

> Performs an in-place modification of a resource.

The Approved Verbs List also explicitly says (of `Edit`):

> For this action, do not use verbs such as Change, **Update**, or Modify.

(Emphasis mine.)

**Comment by ddyett** [comment]
fixed with 1.0
