### ISSUE TITLE
V1.0 profile does not have default property list that is defined for beta profile.

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#362]
Try 
```
select-mgProfile -Name "v1.0"
Get-MgGroup
```

**Comment by peombwa** [comment]
This will be fixed with the release of 0.9.2

![image](https://user-images.githubusercontent.com/7061532/93253017-2430b080-f74b-11ea-9d75-13389fd678e2.png)

**Comment by peombwa** [comment]
This has be fixed in v1.0,  `Install-Module Microsoft.Graph -AllowClobber -Force`.
