### ISSUE TITLE
New-MgConditionalAccessPolicy Passing BodyParameter as a single nested has table results in error

### ISSUE THREAD

**Issue by laughtonsm** [microsoftgraph/msgraph-sdk-powershell#366]
I am converting the contents of a file in JSON format to a nested hashtable and trying to use this as an input to the New-MgConditionalAccessPolicy cmdlet.  I have checked the type of all levels within the nested hashtable and the correct type is returned.  However the following error is returned on execution:

New-MgIdentityConditionalAccessPolicy : An item with the same key has already been added.
At line:1 char:1
+ New-MgIdentityConditionalAccessPolicy -BodyParameter $hash
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-MgIdentityC...sPolicy_Create1], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.NewMgIdentityConditionalAccessPolicy_Create1

**Comment by MIchaelMainer** [comment]
Can you share the contents of the hash table with us in JSON form?

**Comment by peombwa** [comment]
@laughtonsm This has been fixed in version 1.0.1 of the SDK. `Install-Module Microsoft.Graph -AllowClobber -Force`.

Let us if it works for you with 1.0.1.
