### ISSUE TITLE
Update-MgUser failure: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by seanmcne** [microsoftgraph/msgraph-sdk-powershell#370]
It appears update-mgruser is broken: 

`
Update-MgUser -UserId $userGuid -Mail $userEmail -Verbose
`
![image](https://user-images.githubusercontent.com/2292260/93132295-fd1aa600-f69a-11ea-9860-fcab736ce47e.png)

**Comment by seanmcne** [comment]
![image](https://user-images.githubusercontent.com/2292260/93132573-86ca7380-f69b-11ea-9925-72359187b2f4.png)

**Comment by seanmcne** [comment]
FYI there is kind of a way to bend this into something that kind of works (at least it works to call the API but it ultimately generates an exception in PowerShell): 

![image](https://user-images.githubusercontent.com/2292260/93134599-97c8b400-f69e-11ea-97b4-176395c3d36d.png)

**Comment by peombwa** [comment]
This has be fixed in v1.0,  `Install-Module Microsoft.Graph -AllowClobber -Force`.
