### ISSUE TITLE
Regression: Update-MgUser fails to update manager

### ISSUE THREAD

**Issue by meta-anurag-chaturvedi** [microsoftgraph/msgraph-sdk-powershell#375]
```powershell
$manager = Get-MgUser -Userid $ManagerId 
Update-MgUser -Userid $userId -Manager $manager
```

this use to work before the recent module update but it fails with error

```none
Update-MgUser : Cannot process argument transformation on parameter 'Manager'. Cannot convert the "Microsoft.Graph.PowerShell.Models.MicrosoftGraphUser" value of type 
"Microsoft.Graph.PowerShell.Models.MicrosoftGraphUser" to type "Microsoft.Graph.PowerShell.Models.IMicrosoftGraphDirectoryObject".
At line:1 char:71
+ ... User -UserId '7b0595f7-7d3e-4846-8d21-d1e9d8bccb49' -Manager $manager
+                                                                  ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-MgUser], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Update-MgUser
```

cc: @KirkMunro

**Comment by KirkMunro** [comment]
FYI, for this issue we were able to work around it by using `Invoke-GraphRequest`, but that shouldn't be necessary. We had the logic shown above working at some point (maybe in version 0.5.1...not exactly sure right now), but it fails where it shouldn't.

The user object is derived from the `IMicrosoftGraphDirectoryObject` interface, so parameter binding should work, but it doesn't.

You can see this most simply in this script:

```powershell
$user = Get-MgUser -UserId $userId
[Microsoft.Graph.PowerShell.Models.IMicrosoftGraphUser]$user # this works
[Microsoft.Graph.PowerShell.Models.IMicrosoftGraphDirectoryObject]$user # this fails with error
```

**Comment by peombwa** [comment]
@meta-anurag-chaturvedi which version of the SDK are using? Run ` Get-Module Microsoft.Graph -ListAvailable | select Name, Version`.

**Comment by KirkMunro** [comment]
@peombwa: @meta-anurag-chaturvedi and I are using 0.9.1.

```none
Name            Version
----            -------
Microsoft.Graph 0.9.1
```

**Comment by peombwa** [comment]
The type conversion error has been resolved in v1.0.  `Install-Module Microsoft.Graph -AllowClobber -Force`.

You should be using `Set-MgUserManagerByRef` to assign a user's manager:
```ps 
  Set-MgUserManagerByRef -UserId $user.Id `
    -AdditionalProperties @{
         "@odata.id" = "https://graph.microsoft.com/v1.0/users/$ManagerId"
    }
   - Debug
```
This calls `/users/{id}/manager/$ref` as described in the docs - https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=http.

Use `Get-MgUserManager -UserId $user.Id` to confirm if the user has been set.

Navigation properties like manager cannot be used to update a user, and this will give you an error.

**Comment by alexandair** [comment]
"Navigation properties like manager cannot be used to update a user, and this will give you an error."

@peombwa If the manager property cannot be used, why do we have `Update-MgUser -Manager`?
What's the purpose of the `-Manager` parameter?

**Comment by peombwa** [comment]
@eyekelly, examples are available in the help files, provided you know the right command to use - `Get-Help Set-MgUserManagerByRef -Examples` or https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.users/set-mgusermanagerbyref?view=graph-powershell-1.0#example-1-update-a-users-manager. Given the API footprint of Microsoft Graph, we generally recommend that customers start with the [API reference documentation](https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0) to understand how each API functions. The API reference docs have Powershell code snippets for each HTTP example. The commands in this module simply call the API as-is.

@alexandair, the nav properties are unfortunately described as modifiable in the OpenAPI document used to generate the module. This is being tracked at https://github.com/microsoft/OpenAPI.NET.OData/issues/325. We hope to get this fixed before v2 goes GA.

The overall goal is not to surface nav properties as modifiable parameters in v2 once https://github.com/microsoft/OpenAPI.NET.OData/issues/325 is fixed. This is already the case for collection nav properties such as `Update-User -Messages`.

**Comment by sysupmah** [comment]
And it's still not working...
