### ISSUE TITLE
Graph cmdlets cause PipelineStoppedException to be surfaced incorrectly

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#379]
Take this script as an example, which is intentionally incorrect to illustrate the problem:

```powershell
$body = "{ `"@odata.id`": `"https://graph.microsoft.com/v1.0/directoryObjects/23523232323`"}"
try {
    Invoke-GraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/directoryRoles/qwqwqwqwqewe/members/`$ref" -Body $body -ContentType 'application/json'
} catch {
    Write-Host 'Test'
}
```

If you run that script you will see a `PipelineStoppedException` appear in your console, followed by the message "Test". The `PipelineStoppedException` appears due to incorrect handling of errors inside of the Graph cmdlets (or perhaps due to incorrect code in the AutoREST PowerShell foundation that it stands on, I'm not sure).

From the [relevant documentation](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.pipelinestoppedexception?redirectedfrom=MSDN&view=powershellsdk-7.0.0):

> When reported as the result of a command, PipelineStoppedException indicates that the command was stopped asynchronously, either by the user hitting CTRL-C, or by a call to Stop().
>
> When a cmdlet or provider sees this exception thrown from a Monad API such as WriteObject(object) this means that the command was already stopped. The cmdlet or provider should clean up and return. Catching this exception is optional; if the cmdlet or providers chooses not to handle PipelineStoppedException and instead allow it to propagate to the Monad Engine's call to ProcessRecord, the Monad Engine will handle it properly.

A `PipelineStoppedException` should never be surfaced by a cmdlet to the end user. When that happens, it highlights a problem with the implementation of a cmdlet. Typically the solution to this is to simply rethrow any `PipelineStoppedException` instances to allow PowerShell to handle them when you are using broad, generic catch all exception handlers.

The workaround to this issue is to use `-ErrorAction Stop` on the `Invoke-GraphRequest` invocation; however, that workaround should not be required. 
[AB#6784](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6784)

**Comment by finsharp** [comment]
@KirkMunro We made some changes to IGR, which also seem to have resolved this issue. 
![image](https://user-images.githubusercontent.com/1641829/104447028-4678f480-55ac-11eb-871f-2d3ccf3e027f.png)
