### ISSUE TITLE
Deserialization of additionalProperties in ComplexTypes

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#388]
Deserialization of additionalProperties in ComplexTypes is not properly handled by AutoREST i.e. all the properties of a ComplexType are deserialized to additionalProperties. This causes to a `duplicate key` error when a complexType object is reused in a request.

### Repro Steps
``` ps
$user = Get-MGUser -Top 1 -Property Id, Identities

# You'll notice all `ObjectIdentity` properties are deserialized in additionalProperties.

$user.Identities | ft SignInType, Issuer, IssuerAssignedId, AdditionalProperties
SignInType        Issuer     IssuerAssignedId      AdditionalProperties
----------        ------     ----------------      --------------------
userPrincipalName deleted     deleted              {[signInType, userPrincipalName], [issuer, deleted], [issuerAssignedId, deleted]}

# Reuse $user
Update-MgUser -UserId $anotherUserId -Manager $users
Update-MgUser_UpdateExpanded1: An item with the same key has already been added. Key: issuer
```

**Comment by peombwa** [comment]
This can be mitigated by a directive to fix AutoREST's serialization layer.

**Comment by darrelmiller** [comment]
I believe the issue here is that -Manager is not a valid property for updates.  Navigation properties should not be exposed for update models.
