### ISSUE TITLE
Scope for device management retire not valid

### ISSUE THREAD

**Issue by TobyHawkes** [microsoftgraph/msgraph-sdk-powershell#393]
When wanting to use the retire action for managed devices the DeviceManagementManagedDevices.PriviligedOperation.All scope as noted here:
https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-retire?view=graph-rest-1.0

When trying to connect the following error is returned

Connect-Graph -scope "DeviceManagementManagedDevices.PriviligedOperation.All"

Connect-Graph : AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'DeviceManagementManagedDevices.PriviligedOperation.All offline_access profile openid' does not exist. 
[AB#7394](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7394)

**Comment by peombwa** [comment]
@TobyHawkes Could you try passing your tenant's Id to `-TennantId`. Our auth library requires a tenant id to be passed when one is consenting to delegate scopes that require a work or school account.

```ps
Connect-Graph -scope "DeviceManagementManagedDevices.PriviligedOperation.All" -TenantId "YOUR_TENANT_ID"
```

**Comment by TobyHawkes** [comment]
@peombwa I have tried the command entering my tenantid, when I go to the device logon page the following error occurs


"Sorry, but we’re having trouble with signing you in.
 
AADSTS650053: The application 'Microsoft Graph PowerShell' asked for scope 'DeviceManagementManagedDevices.PriviligedOperation.All' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor. "

**Comment by TobyHawkes** [comment]
I can confirm the issue persists in v1.0.1

**Comment by TobyHawkes** [comment]
still persists in 1.2.0

**Comment by TobyHawkes** [comment]
now if i run Connect-MGGraph -scope "DeviceManagementManagedDevices.PriviligedOperation.All" nothing happens in the powershell console, the powershell prompt just goes to the next line and is ready to take the next command. if i run disconnect-mggraph after it says there is no application to sign out from

**Comment by peombwa** [comment]
This is an issue with the service. There is an ongoing discussion in the service Q&A about this permission at https://docs.microsoft.com/en-us/answers/questions/797694/graph-api-for-retire-device-has-incorrect-spelling.html. The suggestion of `DeviceManagementManagedDevices.PrivilegedOperations.All` works for me as expected.
