### ISSUE TITLE
Direct Invoke-RestMethod examples would be better

### ISSUE THREAD

**Issue by gwalkey** [microsoftgraph/msgraph-sdk-powershell#400]
reducing dependencies on changing APIs

**Comment by MIchaelMainer** [comment]
That is the PowerShell command to use when this SDK doesn't support a particular API.

**Comment by finsharp** [comment]
@gwalkey We added a new Cmdlet, `Invoke-GraphRequest` | `Invoke-MgGraphRequest` these was requested by customers a while back. Please see here #127
