### ISSUE TITLE
Mention channel instead of user - after simple example please

### ISSUE THREAD

**Issue by thenecroscope** [microsoftgraph/msgraph-sdk-powershell#404]
Hi,

I've managed to get all the Teams messaging features working now with version 1.0.1 :) using the New-MgChannelMessage cmdlet.
I'm having problems trying to mention a channel now though, I'm sure its user error on my part, but I just cannot get it to work.

Can anybody provide a simple example on how to mention a channel instead of a user.

Many thanks!!! 
[AB#7403](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7403)

**Comment by ddyett** [comment]
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/5-Teams.ps1 contains a sample using a mention but for a user.  you can see this document for more on passing in a conversation

 https://docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta

If it was a channel or team that was @mentioned, the identitySet contains a conversation property giving the ID of the team/channel, and a conversationIdentityType property that represents either the team or channel.
