### ISSUE TITLE
Define proper naming strategy for *.Actions and *.Functions cmdlets

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#41]
Currently, some generated cmdlets in *.Actions & *.Functions modules have duplicate names with cmdlets from other modules. This results in a cmdlet name conflict when generating the roll-up module.
e.g.
`Get-Site` in `Sites.Site` module and `Get-Site` in `Sites.Functions` module.

**Comment by darrelmiller** [comment]
Specific issues will be created for Actions/Functions with naming conflicts and will be handled in 0.5.0 Milestone.
