### ISSUE TITLE
Getting onenote page content

### ISSUE THREAD

**Issue by TobyHawkes** [microsoftgraph/msgraph-sdk-powershell#412]
I'm trying to work out if I can get onenote page content using Get-MgGroupOnenotePage (or a command I haven't come across yet). Get-help doesn't reveal any answers 
[AB#7396](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7396)

**Comment by peombwa** [comment]
You can now download the content of a OneNote page via `Get-MgGroupOnenotePageContent -GroupId $GroupId -OnenotePageId $PageId -OutFile myPage.html`.

Use ` Update-Module Microsoft.Graph` to install the latest version of the SDK.

**Comment by TobyHawkes** [comment]
Hi I can see this command is available now. It forces the outFile option however in my code I need to save the HTML output to a variable, is this supported?

**Comment by peombwa** [comment]
@TobyHawkes Unfortunately this is not supported. The commands only saves files to a disk via `-OutFile`. We can look at supporting this in the future via `FileVariable`.

**Comment by TobyHawkes-awin** [comment]
I have worked around the issue by using invoke-mggraphrequest -uri <page content url> which sends it to a variable

**Comment by TobyHawkes** [comment]
I have worked around the issue by using invoke-mggraphrequest -uri "page content url" which sends it to a variable
