### ISSUE TITLE
Can't create New-MgApplication using self-signed cert

### ISSUE THREAD

**Issue by mrkeiths** [microsoftgraph/msgraph-sdk-powershell#413]
Could documentation be expanded to include an example that creates a new application with self-signed certificate? (please include steps to generate the self-signed cert too)

I'm getting an error (details below) but have found if I create a new application in the Azure portal manually and upload the same self-signed certificate, the cert is accepted.

Details from $Error[0]:
Exception             : System.NullReferenceException: Object reference not set to an instance of an object.
                           at Microsoft.Graph.PowerShell.Runtime.DictionaryExtensions.HashTableToDictionary[V](Hashtable
                        hashtable, IDictionary`2 dictionary)
                           at Microsoft.Graph.PowerShell.Cmdlets.NewMgApplication_CreateExpanded.<ProcessRecordAsync>d__161.M
                        oveNext()
ScriptStackTrace      : at New-MgApplication<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Identity.Ap
                        plication\0.9.1\exports\v1.0-beta\ProxyCmdletDefinitions.ps1: line 11714
                        at <ScriptBlock>, <No file>: line 1

Details from $Error[1]: Exception calling "ReadPolicyId" with "1" argument(s): "Cannot find object or property. 0x80092004 (-2146885628 CRYPT_E_NOT_FOUND)"

Once my app is created and cert is uploaded manually, my test script that connects w/appropriate Scopes runs fine.  Since the cert works when it is manually uploaded via the Azure portal, it seems the issue may be with the SDK?

$splat = @{
    Subject = "CN={0}" -f $CertFriendlyName;
    FriendlyName = $CertFriendlyName;
    KeyDescription = "Sample app to read sign-in events using the Graph SDK.";
    CertStoreLocation = $CertLocation;
    NotBefore = $NotBefore;
    NotAfter = $NotAfter;
    KeyExportPolicy = 'Exportable';
    #KeySpec = 'Signature';
    #KeyLength = 2048;
    #KeyAlgorithm = 'RSA';
    #HashAlgorithm = 'SHA256';
    Provider = "Microsoft Enhanced RSA and AES Cryptographic Provider"; #"Microsoft Strong Cryptographic Provider";
    TextExtension = @("2.5.29.37={text}1.3.6.1.5.5.7.3.1"); # Server Authentication
}
$cert = New-SelfSignedCertificate @splat;

**Comment by MIchaelMainer** [comment]
Please update to the latest version of the SDK as it contains a fix for this scenario. Here is a sample: https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/9-Applications.ps1#L47

**Comment by mrkeiths** [comment]
Thanks Michael!  You were right, I wasn't using the current version.

Everything is working properly now.

Regards,
Keith
