### ISSUE TITLE
Consider adding interactive login for framework usage?

### ISSUE THREAD

**Issue by mlhickey** [microsoftgraph/msgraph-sdk-powershell#415]
Ever consider including Interactive for use in a framework world, e.g.
ConnectGraph.cs
#if NETFRAMEWORK
                    clientApplication = (authProvider as InteractiveAuthenticationProvider).ClientApplication;
#else
                    clientApplication = (authProvider as DeviceCodeProvider).ClientApplication;
#endif

AuthenticationHelper.cs
#if NETFRAMEWORK
                return new InteractiveAuthenticationProvider(publicClientApp, authContext.Scopes);
#else
                return new Microsoft.Graph.Auth.DeviceCodeProvider(publicClientApp, authContext.Scopes, async (result) =>
                {
                    await Console.Out.WriteLineAsync(result.Message);
                });
#endif 
[AB#7398](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7398)

**Comment by MIchaelMainer** [comment]
This will require us to follow up with MSAL.

**Comment by peombwa** [comment]
Related to #334

**Comment by peombwa** [comment]
This has been resolved by #618 and will be available in v1.6.0.
