### ISSUE TITLE
Several cmdlets don't report the right count when 1 owner/member

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-sdk-powershell#418]
On both 5.1 and 7, run:
    
    $owners = Get-MgGroupOwner -GroupId <ID of a Group with one owner>
    $owners.Count
    
    $members = Get-MgGroupMember -GroupId <ID of a Group with one member>
    $members.Count

Both .Count lines will return 2 instead of 1. `.GetType()` returns MicrosoftGraphDirectoryObject, and not an array. I'm using `$owners.Id.Count` and `$members.Id.Count` to get correct counts in the meantime.

Same for Get-MgDirectoryDeletedItem. The only way I get a usable object I can enumerate against is to run `$deletedItems = (Get-MgDirectoryDeletedItem -DirectoryObjectId 'microsoft.graph.group').ToJsonString() | ConvertFrom-Json` 
[AB#6870](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6870)

**Comment by ryanspletzer** [comment]
Bumping this one, I've experienced this as well.

**Comment by ryanspletzer** [comment]
It also occurs with something like this when filtering for a single object:

```powershell
$u = Get-MgUser -Filter "displayName eq 'Ryan Spletzer'"
$u.Count # 0
```

There is a Count property set on that outputted object and it returns `0`.

**Comment by peombwa** [comment]
@joshtransient, @ryanspletzer Thanks for reporting this to us. This is indeed a bug. Count property shouldn't be present when a command returns an object. We will fix this in the next release.

Note to self:
- The same should apply to Keys and Values properties.
