### ISSUE TITLE
Cannot use KQL in Get-MgSite (PowerShell 7 only)

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-sdk-powershell#419]
The following works on Windows PowerShell 5.1, but not PowerShell 7:

    Get-MgSite -Search 'GroupId:76493310-6708-48a9-a4dc-d36e7a239ff1'

Error message returned in 7 is "Syntax error: character ':' is not valid at position 7 in 'GroupId:76493310-6708-48a9-a4dc-d36e7a239ff1'". Fiddler shows that PowerShell 7 URL-encodes the value in -Search:

    /v1.0/sites?$search=GroupId%3A76493310-6708-48a9-a4dc-d36e7a239ff1

For whatever reason, the current 5.1 issue where an extra "?" appears with every query parameter call seems to do fine, as Fiddler captures this:

    /v1.0/sites??$search=GroupId%3A76493310-6708-48a9-a4dc-d36e7a239ff1

Invoke-MgGraphRequest also forcefully adds a "$" to the search parameter with this example:

    Invoke-MgGraphRequest -Uri '/v1.0/sites?search=GroupId:76493310-6708-48a9-a4dc-d36e7a239ff1'

...which causes it to fail with an HTTP 400 (again, only on 7) 
[AB#7399](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7399)

**Comment by joshtransient** [comment]
After a decent night's sleep, apparently adding quotation marks around the search string works great on both 5.1 and 7:

    Get-MgSite -Search '"GroupId:76493310-6708-48a9-a4dc-d36e7a239ff1"'

In 5.1, you can flip the quotation marks (e.g. `-Search "'GroupId:76493310-6708-48a9-a4dc-d36e7a239ff1'"`) and it'll still work, but not in 7.

**Comment by ATJSM** [comment]
I was experiencing a very similar issue with the Search switch in PowerShell 7.0.2.

```
$searchString = "Weekly digest: Office 365 changes"
$messages = Get-MgUserMessage -UserId $user -Search $searchString
```
Error:
$messages = Get-MgUserMessage -UserId $user -Search $searchString #`" …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Syntax error: character ':' is not valid at position 13 in 'Weekly digest: Office 365 changes'.

In order to fix it i had to use double quotes and escape them as follows:
```
$searchString = "Weekly digest: Office 365 changes"
$messages = Get-MgUserMessage -UserId $user -Search `"$searchString`"
```

**Comment by peombwa** [comment]
This is indeed a client bug and is being tracked by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/399. A workaround for now is to double quote your -Search value as mentioned by @ATJSM .

**Comment by joshtransient** [comment]
This won't fly for the /sites endpoint with ?search. ?search always works with KQL and ?$search does not. This issue was opened for a SharePoint-specific reason.
