### ISSUE TITLE
Connect-MgGraph fails when remoting over SSH to MacOS

### ISSUE THREAD

**Issue by lahell** [microsoftgraph/msgraph-sdk-powershell#424]
**Reproduce issue**
Connect to a remote session on MacOS and run `Connect-MgGraph`. You get the following error.
```
PS C:\Users\admin> Enter-PSSession -HostName imac -UserName admin
Password:
[admin@imac]: PS /Users/admin> Connect-MgGraph

Error: SecKeychainFindGenericPassword failed with result code -25308.
```
**Error details**
-25308 is result code for [errSecInteractionNotAllowed](https://developer.apple.com/documentation/security/errsecinteractionnotallowed) and it means:
Interaction with the Security Server is not allowed.

**Workaround**
If you SSH (`ssh admin@imac`) to MacOS, start `pwsh` and run `security unlock-keychain`, you will be prompted for password. After entering the password you can successfully use `Connect-MgGraph`.

Sadly it does not work the same way in PowerShell remoting over SSH (`Enter-PSSession` / `Invoke-Command`). I can only get it to work by running `security unlock-keychain -p plaintextpassword`.

This may be common knowledge for MacOS admins, but I wasted a lot of time trying to figure this out. Would be nice if we could catch this exception and write a helpful error message about using `security unlock-keychain`.

**Environment**
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```
Get-Module Microsoft.Graph.Authentication | Format-List Name, Version

Name    : Microsoft.Graph.Authentication
Version : 1.0.1
``` 
[AB#7401](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7401)

**Comment by peombwa** [comment]
@lahell Thanks for bring this to our attention. We will update our readme to mention this workaround since we do cache access tokens in a user's default keychain.
