### ISSUE TITLE
Get-MgUserPresence missing

### ISSUE THREAD

**Issue by broo0ose** [microsoftgraph/msgraph-sdk-powershell#430]
PowerShell 7.0.3
running on Linux on Raspberry Pi
Microsoft.Graph module v1.0.1

I can use the command Get-MgUser 
But if try to use the command Get-MgUserPresence I get. 

Get-MgUserpresence: The term 'Get-MgUserpresence' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by MIchaelMainer** [comment]
You'll need to use `-select-mgprofile beta`

**Comment by broo0ose** [comment]
thanks
