### ISSUE TITLE
Get-MgIdentityConditionalAccessPolicy Fails to Retrieve Policies that are configured with device states

### ISSUE THREAD

**Issue by Donovand4** [microsoftgraph/msgraph-sdk-powershell#431]
Get-MgIdentityConditionalAccessPolicy Fails to Retrieve Policies that are configured with device states.

The below output is when the "Session Management" policy is configured with device states. Both Policies are enabled.
PS C:\> Get-MgIdentityConditionalAccessPolicy | select id,displayname
Id                                   DisplayName
--                                   -----------
bda54249-01bc-48dd-acf8-93aa8215e482 Devman Duplicate CA

The below is the output when the device states on the policy is removed.  Both Policies are enabled.
PS C:\> Get-MgIdentityConditionalAccessPolicy | select id,displayname
Id                                   DisplayName
--                                   -----------
bb2f8905-ea35-495c-bede-849b3e72a033 Session Management
bda54249-01bc-48dd-acf8-93aa8215e482 Devman Duplicate CA

Below is a screenshot of the policy when the device state was configured.

![PolicyWithDeviceStates](https://user-images.githubusercontent.com/49915971/96182600-9accf380-0f2d-11eb-8033-4dfdb06f78ed.jpg)

PS C:\> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\> get-command Get-MgIdentityConditionalAccessPolicy
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-MgIdentityConditionalAccessPolicy              1.0.1      Microsoft.Graph.Identity.SignIns

**Comment by Donovand4** [comment]
The device states details is also missing from the module. It used to be located within the Conditions tabl and was reporting as DeviceStateIncludeStates.

**Comment by peombwa** [comment]
@Donovand4 The SDK calls MS Graph v1.0 endpoint by default.
You will need to switch to beta using `Select-MgProfile beta` since `deviceStates` is only [available in beta](https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta#properties).

``` powershell
# Switch to beta endpoint.
Select-MgProfile beta

# Get conditional access policies.
 Get-MgIdentityConditionalAccessPolicy | select -ExpandProperty Conditions | select ClientAppTypes, Devices, DeviceStates
```

**Comment by peombwa** [comment]
Feel free to close the issue if this answers your question.

**Comment by Donovand4** [comment]
Thank you for the response and I will close it.

**Comment by craig872** [comment]
In case the great search engine in the sky brings others here as it did me...
It is now 2023.
Select-MgProfile has been deprecated and graph v1.0 API `Get-MgIdentityConditionalAccessPolicy` still fails to list policies that use device state.
In order to use the beta profile now, you need to:
- Install-Module Microsoft.Graph.Beta
- Get-MgBetaIdentityConditionalAccessPolicy
