### ISSUE TITLE
Add deviceManagement OpenAPI specification / cmdlets

### ISSUE THREAD

**Issue by nicolonsky** [microsoftgraph/msgraph-sdk-powershell#432]
Currently, we have the deviceAppManagement entities covered but the deviceManagement is completely missing. Could you add them to the next release or do you have an explanation why they are not included within this module?

 
[AB#6407](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6407)

**Comment by peombwa** [comment]
This is in the works and will be available soon. We are trying to figure out the most optimal way to surface deviceManagement 
 & deviceAppManagement APIs as PowerShell commands.
