### ISSUE TITLE
Body to Query Parameters in GET Requests with InvokeMgGraphRequest

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/msgraph-sdk-powershell#437]
It appears here that the body for GET requests with InvokeMgGraphRequest is translated into query string params. Is this for ease of use in PowerShell? Would it be possible to document this in the help message for Body? I hadn't noticed this at all until I was digging into the code. :) 

https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/623bcd8b4558b378b1e0af27d8acfe4951964a93/src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs#L366-L406

**Comment by ryanspletzer** [comment]
I see now, it's mirroring how `Invoke-RestMethod` behaves:

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7#parameters

![image](https://user-images.githubusercontent.com/1481108/96793560-9b043d80-13ca-11eb-9229-9ba5972a01d9.png)

**Comment by finsharp** [comment]
@ryanspletzer Yes, the cmdlet was inspired by `Invoke-RestMethod` and `Invoke-WebRequest` as requested by our customers.
