### ISSUE TITLE
Get-MgUserAuthenticationMethod - Does not exist

### ISSUE THREAD

**Issue by ThePoShWolf** [microsoftgraph/msgraph-sdk-powershell#447]
This is a strange one for me. I can autocomplete ```Get-MgUserAuthenticationMethod```, but when I try to run it I get the following error:

```text
Get-MgUserAuthenticationMethod: The term 'Get-MgUserAuthenticationMethod' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I've also tried:

```powershell
Import-Module Microsoft.Graph.Identity.AuthenticationMethods
Get-Command -Module Microsoft.Graph.Identity.AuthenticationMethods
```

This returns nothing and attempting to run the command again results in the same error.

I can, however, query that API endpoint with:

```powershell
Invoke-GraphRequest -Method GET -Uri /beta/users/<UPN>/authentication/methods
```

**Comment by peombwa** [comment]
Hi @ThePoShWolf `Get-MgUserAuthenticationMethod` is only available in beta. The SDK makes calls to `v1.0` endpoint by default, but you can switch to beta profile via `Select-MgProfile -Name Beta`. See https://github.com/microsoftgraph/msgraph-sdk-powershell#api-version.

Feel free to close the issue if this answers your question.

**Comment by ThePoShWolf** [comment]
Ah, great. I was confused because the command autocompletes but then doesn't run.

Thats awesome, by the way, thank you!

**Comment by jd1984** [comment]
FYI - this is still the first result on Google for "The term 'New-MgUserAuthenticationPhoneMethod' is not recognized"
This can now be accessed via "Connect-MgGraph".
You may need to "Install-Module" Microsoft.Graph first.
