### ISSUE TITLE
Pagination and token refresh errors

### ISSUE THREAD

**Issue by DaveyRance** [microsoftgraph/msgraph-sdk-powershell#451]
Is it possible to improve the error handling for large requests that cause paging of the results.

This is happening on 1.01 and 1.1.0 versions.

Yesterday running `get-MgAuditLogSignIn -Filter '(createdDateTime gt 2020-10-14T00:00:00Z and createdDateTime lt 2020-10-15T00:00:00Z)'` would correctly return a large number of records and take a bunch of time to run (24 minutes and 100K + records)

Today I get a what feels like random number of results returned before getting 'Get-MgAuditLogSignIn_List1: Token not found: token is either invalid or expired'

The code returned when doing a debug
`DEBUG: BeforeCall:
DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
DEBUG: FollowingNextLink: 
DEBUG: GET /beta/auditLogs/signIns?$top=50&$filter=(createdDateTime+gt+2020-10-14T00%3a00%3a00Z+and+createdDateTime+lt+2020-10-15T00%3a00%3a00Z)&$skiptoken=3eaxxxxxxx0d548081e4c2459_1450 HTTP/1.1
HTTP: graph.microsoft.com
SdkVersion: Graph-powershell-Microsoft.Graph.Authentication-1.1.0, Graph-dotnet-1.20.1
FeatureFlag: 00000047
Cache-Control: no-store, no-cache
Accept-Encoding: gzip

DEBUG: BeforeCall:
DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
Get-MgAuditLogSignIn_List1: Token not found: token is either invalid or expired
DEBUG: GET https://graph.microsoft.com/beta/auditLogs/signIns?$top=50&$filter=(createdDateTime+gt+2020-10-14T00%3a00%3a00Z+and+createdDateTime+lt+2020-10-15T00%3a00%3a00Z)&$skiptoken=3eaxxxxxxx0d548081e4c2459_1450
HTTP/1.1 400 Bad Request
Cache-Control: private
request-id: d05d7a04-e05e-4b74-9662-963afc05507f
client-request-id: d05d7a04-e05e-4b74-9662-963afc05507f
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_77"}}
Strict-Transport-Security: max-age=31536000
Date: Thu, 29 Oct 2020 13:32:24 GMT
Content-Type: application/json
Content-Length: 305`

This may return anywhere from 100 -> 7000 records this morning.
This Exact same error is happening on `Get-MgReportCredentialUserRegistrationDetail -All` This would normally return the 35+k users that I have but this morning is only returning 100 - 4000 users.
 
[AB#6783](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6783)

**Comment by peombwa** [comment]
This looks like an [intermitted service issue](https://stackoverflow.com/questions/58176611/microsoft-graph-api-intermittent-error-token-not-found-token-is-either-invalid), and we may need to implement a more robust throttle handling strategy. I will try to repo this on my end.

**Comment by peombwa** [comment]
I couldn't reproduce this on my end. Please reopen if the issue is still present.
