### ISSUE TITLE
Allow me to get back the raw JSON output from any request easily with a `-Raw` common parameter

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#454]
I would like to be able to invoke any Graph cmdlet with a `-Raw` common parameter, with the results of that invocation returning the raw JSON output from the web request. This would be very helpful because Graph cmdlets allow me to easily write a command in a self-documenting way using PowerShell syntax while allowing me to get back the raw JSON output without it being processed/converted into custom objects for scenarios where I want to pass that JSON off to another service.

Today there are many scenarios where I am invoking Graph cmdlets, which then send receive results in JSON, convert it into objects, which I then convert back into JSON to send off to another service for processing. I'd like to avoid the overhead involved in converting from JSON to objects and then back into JSON, especially since the JSON isn't always converted into objects in a way that I would expect.

I know that I can use Invoke-MgGraphRequest to achieve this; however, that removes the benefit of being able to write self-documenting script logic that leverages PowerShell's strengths. A `-Raw` common parameter to get back just the JSON would give me the best of both worlds when I need it. 
[AB#7373](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7373)

**Comment by finsharp** [comment]
@KirkMunro All the modules return objects that implement a `ToJsonString()`
Such as below :-
```
$users = Get-MgUser -All
$users.ToJsonString()
```

It works for both for collections and single objects. 

cc @peombwa

**Comment by KirkMunro** [comment]
@finsharp: Thank you for sharing that, I had not thought to look for such a method.

Yes, the JSON produced by that method would suit my needs. As long as I can get back the raw JSON from a single graph API, ideally without any overhead involved in converting from JSON to PSObject since I wouldn't need that to be done, I'll be happy.

Also just to call it out, my expectation is that `-Raw` would result in the raw JSON being returned like it would from the Graph REST API invocation. i.e. If multiple records are being looked up and would be returned on a single page as a single JSON string, then just give me that string, but if multiple records are being looked up and the data would be returned from Graph on multiple pages, then stream the JSON strings for each of those pages out of the pipeline, and I'll handle joining the JSON arrays myself.

**Comment by finsharp** [comment]
@KirkMunro We have added this in linked PR, please take a look and see if its satisfactory.
