### ISSUE TITLE
Connect using BYOT via a Managed Identity in Azure Functions

### ISSUE THREAD

**Issue by colinrippeyfinarne** [microsoftgraph/msgraph-sdk-powershell#46]
I have tons of use cases for running Powershell scripts in Azure Functions. What I do at the moment is obtain my Managed Identity bearer token (which I have previously granted permissions to) and the use the Invoke-WebRequest commandlet against the raw Graph API.
It would be great if as part of the Connect commandlet I was able to either pass in my already obtained bearer token, or even maybe ask the Connect commandlet to go get it for me.
[AB#5613](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5613)

**Comment by darrelmiller** [comment]
This is a scenario that is definitely on our roadmap.

**Comment by edyoung** [comment]
This will also enable transparent auth in Cloud Shell

**Comment by darrelmiller** [comment]
This functionality is dependent on work we are doing in .Graph SDK .NET 2.0.

**Comment by tobvil** [comment]
Would be awesome if would could use the module in Azure Functions.

**Comment by jannickoeben** [comment]
Would love to see an accesstoken parameter. This would leave the option open to do cross-tenant/multi-tenant queries.

**Comment by finsharp** [comment]
We have a new `Invoke-GraphRequest` cmdlet, that is inspired by `Invoke-WebRequest`, it takes an `-Token` parameter that allows the user to pass-in their own token. if `-Token` is not provided it can use the already prior acquired token from `Connect-Graph`.

**Comment by ddyett** [comment]
This is for Connect-Graph having a -token option to allow bypassing the normal code.

**Comment by finsharp** [comment]
@colinrippeyfinarne we have added a new CmdLet `Invoke-GraphRequest`, inspired by `Invoke-WebRequest`.
The new cmdlet has a `-Token` parameter that enables you to pass your required token as a SecureString.
For example:-
`Invoke-GraphRequest -Uri https://graph.microsoft.com/beta/me -Token $token -Authentication UserProvidedToken'

**Comment by colinrippeyfinarne** [comment]
> @colinrippeyfinarne we have added a new CmdLet `Invoke-GraphRequest`, inspired by `Invoke-WebRequest`.
> The new cmdlet has a `-Token` parameter that enables you to pass your required token as a `SecureString`.
> For example:-
> `Invoke-GraphRequest -Uri https://graph.microsoft.com/beta/me -Token $token -Authentication UserProvidedToken`

Thanks for the details, but I hope that this is not the resolution to the request? I hope you are still looking to add a -Token parameter to the Connect commandlet as I want to use all the lovely wrapper commandlets after connecting via Connect.

It will of course be useful to have the Invoke-GraphRequest commandlet, but surely one of the points of this library is to abstract away having to craft up raw urls and deal in a higher level scripting model?

Thanks again though for the details, it will be very useful.

**Comment by finsharp** [comment]
@colinrippeyfinarne We have added `-AccessToken` to `Connect-Graph` cmdlet  in [v1.0.1](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.0.1). Please take a look and give us feedback if it suits your needs. Thanks

**Comment by finsharp** [comment]
@colinrippeyfinarne We have added -AccessToken to Connect-Graph cmdlet in v1.0.1. Please take a look and give us feedback if it suits your needs. Thanks

**Comment by colinrippeyfinarne** [comment]
> @colinrippeyfinarne We have added -AccessToken to Connect-Graph cmdlet in v1.0.1. Please take a look and give us feedback if it suits your needs. Thanks

Brilliant, thanks for the update.
