### ISSUE TITLE
Request: Update Environment Constants to match AzureAD constants

### ISSUE THREAD

**Issue by miketheitguy** [microsoftgraph/msgraph-sdk-powershell#461]
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/3bcab1322bdf01173042c7e185c1dceb69d5be17/src/Authentication/Authentication/GraphEnvironmentConstants.cs#L10

My proposal is to match the AzureAD cmdlet constants.
USGov -> AzureUSGovernment

etc.

**Comment by MIchaelMainer** [comment]
Please review our mappings for environments: https://docs.microsoft.com/en-us/graph/deployments

We don't use the same identifiers as it could cause confusion between the Azure AD endpoint and Graph endpoint.
