### ISSUE TITLE
Powershell 7

### ISSUE THREAD

**Issue by hugo-costa** [microsoftgraph/msgraph-sdk-powershell#462]
Hi,

When attempting to use this Module with Powershell 7.1.0 the following error is observed:
`Connect-MSGraph: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral`

**Comment by peombwa** [comment]
@hugo-costa `Connect-MSGraph` is not part of our modules. Our modules works well with PowerShell 7.1.0.

Follow the instruction here to install our SDK https://github.com/microsoftgraph/msgraph-sdk-powershell#installation.
