### ISSUE TITLE
Documentation for Send-MgUserMail

### ISSUE THREAD

**Issue by tyteen4a03** [microsoftgraph/msgraph-sdk-powershell#463]
I keep getting `Send-MgUserMail : At least one recipient isn't valid., A message can't be sent because it contains no recipients.` when I try to send an email out with the cmdlet, even though I did specify `ToRecipients` in the `Message` object. 
[AB#7375](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7375)

**Comment by peombwa** [comment]
`ToRecipients` needs to be initialized as an array. 

``` powershell
# Initialize as an array.
$ToRecipients = @()

# Add users to ToRecipients
$ToRecipients += @{ 
    emailAddress = @{
        address = $User.Mail
    }
}

# Compose message
$Message = @{
    subject = "Update Your Mailbox Settings!";
    toRecipients = $ToRecipients;
    body = @{
        contentType = "Text";
        content = "Content"
    }
}

# Send mail
Send-MgUserMail -UserId $Admin.Id -Message $Message
```

Have a look at this sample that uses `Send-MgUserMail` https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/Scripts/UsersAndGroups.ps1#L21-L54. We are working on improving our docs to make such scenarios clear.
