### ISSUE TITLE
Retrieving group properties that require $select

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#467]
If you invoke either of these commands today, you will get an error that indicates "This operation target is not yet supported":

```powershell
Get-MgGroup -All -Property AutoSubscribeNewMembers
```

```powershell
Get-MgGroup -All -Property AllowExternalSenders
```

This is the case whether you use v1.0 or beta.

When will it be possible to retrieve these properties using the Graph module bundle?

 
[AB#7376](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7376)

**Comment by peombwa** [comment]
This is an issue with the service.

The property can only be selected when fetching a single group:
``` powershell
Get-MgGroup -GroupId "GROUP_ID" -Property AllowExternalSenders
```

Please open a feature request/question at https://developer.microsoft.com/graph/support for the service owner to investigate.
