### ISSUE TITLE
Commandlet naming convention - are there plans to move to a more specific convention?

### ISSUE THREAD

**Issue by colinrippeyfinarne** [microsoftgraph/msgraph-sdk-powershell#47]
Are there any plans to rename all the commandlets to something more specific to the Graph?

For example instead of Get-User will this commandlet be renamed to something like Get-GraphUser

Apologies if this has been detailed on elsewhere.

**Comment by chrisgardnersage** [comment]
See #32 for more comments about this. More feedback there would be useful.

**Comment by colinrippeyfinarne** [comment]
Thanks for pointing out the previous issue.

In my experience across Microsoft Powershell commandlets it is pretty much a given that any module "should" have it's own unique naming convention. Go ask the Power Platform Powershell team for the feedback they got when they released their own preview modules with commandlets such as Get-App - they were very open to the feedback and quickly pivoted to use a specific naming convention and I've never heard anyone say "I wish I didn't have to type a prefix", intellisense takes care of our verbose typing lol.

I take the point made in #32 that modern Powershell can use a -Prefix etc. but really...are we, at this very early stage in this effort's lifetime, not able to choose a commandlet prefix and move onwards?

Think of all the potential sample scripts that will appear in blogs, stackoverflow comments, for solutions to common problems - every single one of these articles will be "forced"  to add a disclaimer "oh be sure to use the XYZ -Prefix with Import-Module for these samples to work".
