### ISSUE TITLE
Add better ways to get client-side diagnostics/debugging information

### ISSUE THREAD

**Issue by rtintor** [microsoftgraph/msgraph-sdk-powershell#477]
Add options to get client-side diagnostics/debugging information to troubleshot customer issues. For example SSL/TSL problems, connection problems, etc. 
[AB#6759](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6759)

**Comment by finsharp** [comment]
@rtintor Would `-Debug` and `-Verbose` aid in diagnosing the problems?
Would fiddler help?
`-Debug` and -Verbose` produce the following output:-
![image](https://user-images.githubusercontent.com/1641829/106499809-1e592300-64d2-11eb-9c76-fef268e312dc.png)

**Comment by finsharp** [comment]
@rtintor Can we close this? Was the response above satisfactory?

**Comment by rtintor** [comment]
> @rtintor Can we close this? Was the response above satisfactory?

That is helpful I was thinking if there is any kind of logging that we can output on a file to check. If there is no log to save we can work with that for now.

**Comment by finsharp** [comment]
@rtintor You can use PowerShell redirection features to redirect various streams accordingly. 
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-7.1
