### ISSUE TITLE
Get-MgUser -Select SignInActivity does not display values

### ISSUE THREAD

**Issue by ThePoShWolf** [microsoftgraph/msgraph-sdk-powershell#485]
This is in the latest v1.2 version of Microsoft.Graph using the beta profile.

Here's the command:

```powershell
$user = Get-MgUser -Id <guid> -Select SignInActivity
$user.SignInActivity
```

I would expect this to display the values of that property, instead the properties with no values are displayed:

```text
LastSignInDateTime LastSignInRequestId
------------------ -------------------

```

I confirmed in Fiddler that values are being returned for the user I'm testing on, which is my user account so I know that it has been logged into. 
[AB#7378](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7378)

**Comment by peombwa** [comment]
@ThePoShWolf Thanks for bring this to our attention. It looks like there is a service bug in beta when `$select` is set to `SignInActivity`. The service seems to be returning `SignInActivity` as a collection in a property called value on a user object (which is wrong). Our deserializer on the hand expects `SignInActivity` to be a property of a user.

### Current bad response
``` json
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users(signInActivity,id)/$entity",
    "value": [
        {
            "id": "<Redacted>",
            "signInActivity": {
                "lastSignInDateTime": "2020-12-08T20:59:33Z",
                "lastSignInRequestId": "ae8b9a4f-a0ee-4f5c-afb0-061da02f0c00"
            }
        }
    ],
    "id": "<Redacted>"
}
```

### Expected response
``` json
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users(signInActivity,id)/$entity",
    "id": "<Redacted>",
    "signInActivity": {
                "lastSignInDateTime": "2020-12-08T20:59:33Z",
                "lastSignInRequestId": "ae8b9a4f-a0ee-4f5c-afb0-061da02f0c00"
            }
}
```

I'll open an ticket with the team that owns this workload.

As a workaround, you can get the signinActivity from the additionalProperties on a user object like this:
``` powershell
$user = Get-MgUser -Id <guid> -Select SignInActivity
$user.AdditionalProperties.value.signInActivity
```

**Comment by peombwa** [comment]
Related to https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/106

**Comment by ThePoShWolf** [comment]
Great, thanks for the quick update and workaround!

**Comment by ThePoShWolf** [comment]
@peombwa This appears to be fixed in the beta profile. I'm running v1.3.1 and ran the following command:

```powershell
Get-MgUser -UserId <guid> -Select SignInActivity | Select -ExpandProperty SignInActivity
```

And see a good return:

```text
LastSignInDateTime   LastSignInRequestId
------------------   -------------------
3/3/2021 2:55:11 PM  <guid>
```

**Comment by spikedfuel** [comment]
We're seeing an issue with signInActivity where it comes back blank for users with activity. This occurs using the -property or -select as showin in other examples. Get-MgUser -Filter "UserPrincipalName eq '$lookupupn'" -Property "userPrincipalName, signInActivity" | select userPrincipalName,@{n="Interactive";e={($_.signInActivity).LastSignInDateTime.tolocaltime()}},@{n="NonInteractive";e={($_.signInActivity).LastNonInteractiveSignInDateTime.tolocaltime()}
![graphapi](https://user-images.githubusercontent.com/41805678/173135402-df05b5c4-6b8f-4450-b20a-2670d5326db4.jpg)
}

**Comment by ThePoShWolf** [comment]
@spikedfuel - You can only return the `SignInActivity` when you call the user directly by GUID. It does not work on filters or when querying by UPN. So you would have to get the users you want and then, for each user, get the `SignInActivity` using the user's ID (not UPN).

For example (untested code):

```powershell
Get-MgUser -UserId <upn> | %{ Get-MgUser -UserId $_.Id -Property UserPrincipalName,SignInActivity }
```

And then you could pipe it to your select statement.

**Comment by spikedfuel** [comment]
@ThePoShWolf - I've found you actually can use SignInActivity when doing the filter/query. Just oddly not for a few select users where the values return null. I think we can close this issue out - I validated in azure sign-in logs that whatever authentication activity exchange online is reporting, has not been a valid azure login [so the blank value I'm seeing == no sign-ins found].

**Comment by ThePoShWolf** [comment]
Well now, you are correct! Either that changed or I assumed it didn't work, hehe. Thanks for that!

**Comment by Tekwhat** [comment]
I am currently having this issue when attempting to pull a report.

`# Authenticate with Office 365
Connect-MgGraph -Scopes "User.Read.All"

# Get user information
$users = Get-MgUser -all -Select "displayName,accountEnabled,lastPasswordChangeDateTime,lastSignInDateTime" 

# Output the results
$report = @()
foreach ($user in $users) {
    $name = $user.displayName
    $isEnabled = $user.accountEnabled
    $lastPasswordReset = $user.lastPasswordChangeDateTime
    $lastLogin = $user.lastSignInDateTime

    $userReport = [PSCustomObject]@{
        Name = $name
        LastPasswordReset = $lastPasswordReset
        LastLogin = $lastLogin
        IsEnabled = $isEnabled
    }

    $report += $userReport
}

$report | Format-Table -AutoSize`

When I attempt to pull this for a user, I get blanks:
` Get-Mguser -UserId [id] | select -ExpandProperty signinactivity

LastNonInteractiveSignInDateTime LastNonInteractiveSignInRequestId LastSignInDateTime LastSignInRequestId
-------------------------------- --------------------------------- ------------------ -------------------`

**Comment by tankcr** [comment]
I am not sure why this is considered closed when you cannot pull all your users and get the last signindatetime, without having to then loop through every user using their ID. If you are generating a report with this data it is incredibly inefficient
