### ISSUE TITLE
Unable to pull Service Principal Synchronization Job with PowerShell Graph SDK

### ISSUE THREAD

**Issue by mmushatt** [microsoftgraph/msgraph-sdk-powershell#488]
Attempting to pull information using the MS Graph API PowerShell cmdlets 

**https://graph.microsoft.com/beta/servicePrincipals/c36acxxx-xxxx-xxxx-xxxx-xxxxc8721871/synchronization/jobs**/...

**Get-MgServicePrincipalSynchronizationJob**
cmdlet **Get-MgServicePrincipalSynchronizationJob at command pipeline position 1**
Supply values for the following parameters:
ServicePrincipalId: b060f345-xxxx-xxxx-xxxx-394af34bcf09

**Get-MgServicePrincipalSynchronizationJobSchema**
cmdlet **Get-MgServicePrincipalSynchronizationJobSchema at command pipeline position 1**
Supply values for the following parameters:
ServicePrincipalId: b060f345-xxxx-xxxx-xxxx-394af34bcf09

Neither cmdlet is returning the expected results. 

Either **Get-MgServicePrincipalSynchronizationJobSchema** or **Get-MgServicePrincipalSynchronizationJob** that is needing a fix. 

When you run the get from Graph Explorer with this URL https://graph.microsoft.com/beta/servicePrincipals/c36acxxx-xxxx-xxxx-xxxx-xxx6c8721871/synchronization/jobs/....

We do get the output.  What we are trying to pull the status section of the code so that I can have PowerShell email alerts when the job fails. 
[AB#7379](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7379)

**Comment by peombwa** [comment]
@mmushatt This should work. By default, the formatting only displays the Id and TemplateId of a job, but you can get the status of a job like this:
``` powershell
 $SyncJob = Get-MgServicePrincipalSynchronizationJob -ServicePrincipalId $SerivePrincipal.Id
 $SyncJob.Status
```
, or pipe the response to a` | Select-Object Id, Status`
