### ISSUE TITLE
Installing Microsoft.Graph.Authentiaction manually

### ISSUE THREAD

**Issue by keomor9327** [microsoftgraph/msgraph-sdk-powershell#489]
Hello there!

I've encountered a problem during installation of this module on my VM. Basically, I've created a local private repository, deployed microsoft.graph.authentication.1.2.0.nupkg there via DevOps. However, when I run

`Find-Module *` then this module isn't listed and it cannot be installed. Other modules like MicrosoftTeams are listed correctly and they can be installed. 

Details in the screenshot attached.

How to fix this?

![PowershellModule issue](https://user-images.githubusercontent.com/72193560/102227843-51c3fc00-3eea-11eb-8d1d-0bd17d38a333.png)
 
[AB#7380](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7380)

**Comment by keomor9327** [comment]
Anything new? :)

**Comment by maisarissi** [comment]
Hi @keomor9327 .

Can you confirm whether this is still an issue?
