### ISSUE TITLE
Update-MgUserMessage fails with null reference error

### ISSUE THREAD

**Issue by schue30** [microsoftgraph/msgraph-sdk-powershell#491]
Attemting to run the following command resulted in an error:
`Update-MgUserMessage -UserId $userId -MessageId $messageId -IsRead`

Error message:
`Update-MgUserMessage_UpdateExpanded: Object reference not set to an instance of an object.`

Exception message:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Graph.PowerShell.Runtime.DictionaryExtensions.HashTableToDictionary[V](Hashtable hashtable, IDictionary`2 dictionary)
   at Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUserMessage_UpdateExpanded.ProcessRecordAsync()
```

Graph version:
```
PS > Get-InstalledModule Microsoft.Graph | Select Name, Version, Repository

Name            Version Repository
----            ------- ----------
Microsoft.Graph 1.2.0   PSGallery
```

**Current Workaround**:

Issue https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/337
Running the command with ` -AdditionalProperties @{}` fixes the problem.

**Comment by peombwa** [comment]
@schue30 I'm not able to repro this on my end. Can you please share the following in order for us to repro this:
- Version of `Microsoft.Graph.Mail` module in use in : `Get-Module Microsoft.Graph.Mail`
- Your `$PSVersionTable`.

**Comment by schue30** [comment]
@peombwa 

I just rechecked the bug. After installing the "Microsoft.Graph.Mail" module again the bug went away. It looks like, that an old installation of the Module "Microsoft.Graph.Users.Mail" interfered with the other module.
Anyway, the bug was just a layer 8 problem by mixing some modules.

I will close the issue now. Thanks for your help.

```
PS > Get-Module Microsoft.Graph.Mail               

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.2.0                 Microsoft.Graph.Mail                {Get-MgUserInferenceClassification, Get-MgUserInferenceClassificationOverride, Get-MgUserMailFolder, Get-MgUserMailFolderChi…
```
```
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 5.9.16-200.fc33.x86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
