### ISSUE TITLE
Help with using Create Invitation in Bulk (from a CSV)

### ISSUE THREAD

**Issue by MSGRRojas** [microsoftgraph/msgraph-sdk-powershell#493]
Hey guys.  New to Graph so up front I apologize for posting up but here goes.

I'm working with a CSV to bulk invite users with a nice custom message and maybe CC other etc 

However, I don't even know where to start with Graph.  I mean I go to developer.microsoft.com/graph/graph-explorer and it looks cool.  But how do I test graph to use the Create Invitation?

THEN.....how do I call that API in PowerShell? 

SUUUUUUUUUUUUUUPER sorry for asking N00B questions but need some help.  
[AB#7381](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7381)

**Comment by maisarissi** [comment]
Hello @MSGRRojas .

Sorry for taking too long to answer you.
I hope that by now you are already familiar with Graph, but I will add a few information here in case someone else finds it.

The first step is to look at [our documentation](https://docs.microsoft.com/en-us/graph/). There you can find information on what is Microsoft Graph, dive deeper in the [API reference documentation](https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0), get familiar with [all our SDKs](https://docs.microsoft.com/en-us/graph/sdks/sdk-installation), try it out [Graph Explorer](https://aka.ms/ge) and much more.

The first thing I normally do is to go to the API reference documentation and find the right page.
![image](https://user-images.githubusercontent.com/22648831/155414574-b70c2249-ffa6-4442-8096-f15006029a20.png)

If I do have a clue on where the functionality that I want is, I use the TOC, so I can expand and look at everything I can do:
![image](https://user-images.githubusercontent.com/22648831/155415180-320d2fbc-0d08-4ba0-9d6c-f5034f24ec2f.png)

Then I go try it on Graph Explorer.

The default user (Megan Bowen) on Graph Explorer has some data for you to do some queries and play around. The best way though is to have your [own developer subscription](https://developer.microsoft.com/en-us/microsoft-365/dev-program).

In the docs page, you can find code snippets in your preferred language: https://docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&tabs=powershell#examples as well as in the code snippets tab on Graph Explorer.
![image](https://user-images.githubusercontent.com/22648831/155417058-0b9f371e-e9bf-43fd-9d49-293b09a0f68f.png)

After finding the right API to call, you can also use the [Find-MgGraphCommand](https://docs.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-command?view=graph-powershell-1.0) to discover the right command to run.

Also, pay attention to the permissions required when calling Graph. You can find it on the API reference documentation. e.g. https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#permissions

Using Microsoft Graph PowerShell SDK, you can take advantage of our authentication module. Check how to authenticate [here](https://docs.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0#authentication).

Please, feel free to reopen if you still need some help.
