### ISSUE TITLE
Can we specific a machine cert store for Connect-MSGraph?

### ISSUE THREAD

**Issue by SLeuthold** [microsoftgraph/msgraph-sdk-powershell#495]
Would very much like to do this! Is it possible with this cmdlet or is it in the roadmap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d211b6ad-20d1-8683-3562-04e35d8de652
* Version Independent ID: 926e81ea-63c6-ab12-3fa6-ef85070b106f
* Content: [Use app-only authentication with the Microsoft Graph PowerShell SDK - Microsoft Graph](https://docs.microsoft.com/en-us/graph/powershell/app-only?tabs=azure-portal)
* Content Source: [concepts/powershell/app-only.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/powershell/app-only.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam** 
[AB#7382](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7382)

**Comment by peombwa** [comment]
This is a valid feature that should be added to the SDK.

For now, you can use `-Certificate`, which was added to `Connect-MgGraph` in v1.2.0, to load a certificate from any store/location like this:
``` powershell
$localMachineCert = Get-ChildItem -Path Cert:\LocalMachine -Recurse | Where-Object { $_.Thumbprint -eq $Thumbprint }
Connect-Graph -Certificate $localMachineCert -TenantId <some-tenant-id> -ClientId <some-client-id>
```

**Comment by SLeuthold** [comment]
@peombwa excellent, this is good news! We'll try out and provide feedback and close if successful!

**Comment by finsharp** [comment]
Related to #522

**Comment by peombwa** [comment]
Closing as resolved.
