### ISSUE TITLE
Cannot list Microsoft Account OneDrive Personal files

### ISSUE THREAD

**Issue by pliniodepaula** [microsoftgraph/msgraph-sdk-powershell#498]
Cannot list Microsoft Account OneDrive Personal files with Microsoft Graph PowerShell SDK.
Listing is only working for OneDrive for Business but not OneDrive Personal.

Steps with Microsoft Account OneDrive Personal:
1. Connect-MgGraph -Scopes "User.Read","Files.Read","Files.Read.All"
2. $DriveId = Get-MgUserDrive -UserId <e-mail@outlook.com> OR
3. $DriveId = Get-MgDrive
4. $list = Get-MgDriveListItem -DriveId $DriveId.Id

Error:
_Get-MgDriveListItem_List: The property 'list' is null or does not exist_

PS: Listing files works as expected in Microsoft Graph Explorer website. 
[AB#6973](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6973)

**Comment by finsharp** [comment]
@pliniodepaula 
From the [docs](https://docs.microsoft.com/en-us/graph/api/resources/drive?view=graph-rest-1.0#relationships):-
Lists would only be available for OneDrive for Business.
![image](https://user-images.githubusercontent.com/1641829/106512798-1e155380-64e3-11eb-9f67-271da60ac6cf.png)

**Comment by pliniodepaula** [comment]
Actually I'm not trying to get any "following" list (NOT issuing _Get-MgDriveFollowing_ command).

I'm actually trying to get the "items" list ("All items contained in the drive") through _Get-MgDriveListItem_ or even "root" through _Get-MgDriveRoot_.

None of these commands seems to work for OneDrive Personal.

**Comment by finsharp** [comment]
@pliniodepaula 
I did reproduce your issue, however its not supported on OneDrive Personal.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/1641829/106575368-0d012c80-654d-11eb-8b5e-bd8ca2260efc.png)

From the above Debug log, `Get-MgDriveListItem` calls /drives/{id}/list/items, from the docs this path is only available for Drives in Sharepoint. 

The same command works with OneDrive for Business
![image](https://user-images.githubusercontent.com/1641829/106575473-2e621880-654d-11eb-9510-f7220125a134.png)

Maybe I have misunderstood your ask, kindly elaborate.

**Comment by pliniodepaula** [comment]
Hi @finsharp , 
As I said before, _Get-MgDriveRoot_ also fails (_Get-MgDriveRoot_Get: ObjectHandle is Invalid_). You'll most probably reproduce it too.

So how can one use PowerShell Graph API to retrieve equivalent operation to _GET_ https://graph.microsoft.com/v1.0/me/drive/root/children or any subfolder file listing with OneDrive Personal?!

This operation works OK in Graph Explorer (https://developer.microsoft.com/pt-br/graph/graph-explorer) with OneDrive Personal.

Unfortunately the PowerShell Graph API documentation is missing / very poor (no examples).

**Comment by peombwa** [comment]
This is a bug with the OpenAPI document that the SDK is generated from. This is related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/129 and is being tracked by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/393.

**Comment by peombwa** [comment]
We are tracking the missing `*/children` APIs in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/813, and a fix will be provided in the upcoming release.

Closing as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/813.
