### ISSUE TITLE
I stumbled across this repo...

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/msgraph-sdk-powershell#5]
Just FYI, if there are actually plans to make a Graph SDK / module for PowerShell, I am *super* stoked. :D 👍

**Comment by darrelmiller** [comment]
@ryanspletzer We are prototyping stuff using the Azure AutoREST Powershell generation mechanism.  Stay tuned!

**Comment by darrelmiller** [comment]
This library is now available on PowerShell Gallery.  Another update should be there tomorrow.
