### ISSUE TITLE
'No HTTP resource was found that matches the request URI' in Microsoft.Graph.Identity.Governance cmdlets

### ISSUE THREAD

**Issue by sergeyz7** [microsoftgraph/msgraph-sdk-powershell#505]
Some of Microsoft.Graph.Identity.Governance cmdlets fail trying to retrieve Access Package resource-specific entities (e.g. listing all resources in a catalog with _Get-MgEntitlementManagementAccessPackageCatalogAccessPackageResource_ 
succeeds but attempting to access a specific resource by its ID fails).
![2021-01-20_12-33-44](https://user-images.githubusercontent.com/45974226/105176721-8183a680-5b1d-11eb-8d57-f90cbc26a375.png)
 
[AB#7662](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7662)

**Comment by markwahl-msft** [comment]
Retrieving resource roles of a resource in a catalog requires the origin system type to also be included in the filter expression, see  https://docs.microsoft.com/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&tabs=http

**Comment by sergeyz7** [comment]
The first example from my original post is with _Get-MgEntitlementManagementAccessPackageCatalogAccessPackageResource_ - which works to list all resources but fails to retrieve a specific resource by ID. The _-Filter_ parameter for that cmdlet is not available in the same parameter set that _-AccessPackageResourceId_ is in.

**Comment by peombwa** [comment]
@sergeyz7 As per the docs, it looks like you can only list access package resources - https://docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&tabs=http. This command will be cleaned-up in the next SDK release.

**Comment by peombwa** [comment]
Clean up done in #670.
