### ISSUE TITLE
IdentityGovernanceEntitlementManagementConnectedOrganizationsCreateInternalSponsors and other tasks not using correct endpoints

### ISSUE THREAD

**Issue by sergeyz7** [microsoftgraph/msgraph-sdk-powershell#516]
Tasks manipulating internal and external sponsors in Entitlement Management connected organisations (e.g. `IdentityGovernanceEntitlementManagementConnectedOrganizationsCreateInternalSponsors`) attempt to call https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/connectedOrganizations/[orgid]/[internal|external]Sponsors rather than https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/connectedOrganizations/[orgid]/[internal|external]Sponsors/$ref
All attempts to use the corresponding cmdlets fail as a result. 
[AB#7747](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7747)

**Comment by peombwa** [comment]
Thanks for surfacing this. This is a bug in our OData -> OpenAPI layer. I've opened an issue here https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/433 to track its fix.

**Comment by markwahl-msft** [comment]
Looking at metadata update of the connectedOrganization when we bring this entity to Graph v1.0.
