### ISSUE TITLE
Connect-graph: Value cannot be null, Parameter name: certificate

### ISSUE THREAD

**Issue by Bjorn80** [microsoftgraph/msgraph-sdk-powershell#52]
Hi
I'm testing out the msgraph-sdk-powershell and have installed the module. Using powershell 5.1.
I have Registered an App in my Azure and added a certificate that was created based on .\Create-SelfSignedCertificate.ps1  (https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)

When trying to connect I get the following error:

`Connect-Graph -ClientId $clientId -TenantId $TenantId -CertificateName "CN=MyCompanyName"`
```
Connect-Graph : Value cannot be null.
Parameter name: certificate
At line:2 char:1
+ Connect-Graph -ClientId $clientId -TenantId $TenantId -CertificateNam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-Graph], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectGraph
```

I'm doing something wrong:s, but what?

Im able to get information via the app-registration using the 
`Invoke-RestMethod -Headers $Headers  -Uri "https://graph.microsoft.com/v1.0/users/$UserPrincipalName/photo" -Method Get`
Which means that the app registration and permissions are ok, perhaps I need to create a certificate another way?

Any tips are welcome!

brgs

Bjørn

**Comment by GSGBen** [comment]
Getting this as well

**Comment by peombwa** [comment]
The error indicates that the certificate was not found in `cert:\CurrentUser\My`, or it may have expired. Could you verify that the certificate is present in `cert:\CurrentUser\My` by running `Get-ChildItem -path "cert:\CurrentUser\My" | Where Subject -EQ "CN=MyCompanyName"`. If it is present, then check its expiry date by running `Get-ChildItem -path "cert:\CurrentUser\My" | Where Subject -EQ "CN=MyCompanyName" | Select Subject, NotAfter`, and ensure NotAfter is > today's DateTime.

**Comment by Bjorn80** [comment]
Hi @peombwa 
Im fairly certain that I always put my certificates on cert:\LocalMachine\My ^^.
I shall try it your way!
brgs
Bjørn

**Comment by iaragon76** [comment]
I was battling with the same issue, and indeed, I my certificate was in the localmachine, not in the current user. Other thing, I did export the certificate wihout keys, and uploaded in azuread into my app. Finally I got connected.

**Comment by milan-mb** [comment]
This helped me.. I was clueless on why the cert was failing error "certificate was not found or has expired" No logs were logged in CAPI which corresponds to the cert I am using.. Adding the cert to users store fixed the issue. That explained why it was failing with no cert found.

**Comment by yuhup2edy** [comment]
Trying to connect mg-graph via a certificate returned from my azure key vault. This runs fine locally but when i run it under an automation account, i get an error stating that the certificate has expired or not found. What might be causing this ? I know for sure that the certs are valid and work great when called locally.
