### ISSUE TITLE
Get-MGReportxxx commands fail if output file doesn't exist. 

### ISSUE THREAD

**Issue by jhoneill** [microsoftgraph/msgraph-sdk-powershell#524]
The following pattern seems to occur for all the report commands I've tested 

```Get-MgReportOneDriveActivityFileCount -Period D7 -OutFile foo.csv ```

results in
```
Get-MgReportOneDriveActivityFileCount : Cannot find path 'C:\Users\xxxxx\Documents\github\MsftGraph\foo.csv' because it does not exist.
```
The  help says 
```
    -OutFile <String>
        Path to write output file to
```

So this file should not need to exist
If I create an empty file it still fails 
```
Get-MgReportOneDriveActivityFileCount -Period D7 -OutFile foo.csv
Get-MgReportOneDriveActivityFileCount : Expected '{' or '['. Was String: Report. At line:1 char:1
 ```
[AB#7840](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7840)

**Comment by finsharp** [comment]
Related to #407

**Comment by peombwa** [comment]
Duplicated of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/407. We are tracking this bug in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/407.
