### ISSUE TITLE
6195 Copies of the wrong licence included 

### ISSUE THREAD

**Issue by jhoneill** [microsoftgraph/msgraph-sdk-powershell#529]
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/LICENSE.txt says that this work is distributed under the MIT license. 

The module builds a ProxycmdletDefinitions file. It appears that whatever builds these places the apache license before each function definition.  So the version for users which I'm looking at currently has 76 proxy functions and before each one is an apache licence. I just did a effectively a giant grep for  "Licensed under the Apache License"  and found 6195 matches - I assume each one is the full licence. Could this (a) be reduced to once per file or (b) replaced with a single licence file which covers everything and  (c) a single licence used throughout ? 

 
[AB#7861](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7861)

**Comment by peombwa** [comment]
This is done by the code gen tool we use (AutoREST.PowerShell). I'm not exactly sure why they add the license header per command in the ProxycmdletDefinitions.

I'd recommend you open an issue on AutoREST.PowerShell repo for them to fix this/ explain their justification for this https://github.com/Azure/autorest.powershell/issues. Let me know if you need help with this.

I'll update our LICENSE.txt to include Apache license as per Apache's recommendation https://www.apache.org/licenses/LICENSE-2.0#apply.

**Comment by jhoneill** [comment]
So you're switching the product form MIT to Apache ?

**Comment by peombwa** [comment]
Our goal going forward is to move everything to MIT. This will be fixed by https://github.com/Azure/autorest.powershell/issues/817 and https://github.com/Azure/autorest.powershell/issues/814.

**Comment by georgend** [comment]
Issue resolved in Autorest
