### ISSUE TITLE
Is the Microsoft.Graph module seen as a replacement for the AzureAD and AzureADPreview modules?

### ISSUE THREAD

**Issue by MarkDordoy** [microsoftgraph/msgraph-sdk-powershell#530]
Hello 

I wanted to try and get an understanding of the roadmap around what modules will have continued long term support to interact with Azure AD. 

Currently i use AzureADPreview, mainly around interacting with users, groups, Application registrations, Enterprise applications (SPNs) and Azure AD policies. 

Im about to start a new project and wanted to know is it worth me moving to what seems like the newer Microsoft module of Microsoft.Graph. I notice it supports core where AzureAD did not do, so it feels to me this is the future but id like to check. I'd also like to check this is not in a preview state.

Thanks  
[AB#7877](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7877)

**Comment by markwahl-msft** [comment]
FYI from the blog post [Automate and manage Azure AD tasks at scale with the Microsoft Graph PowerShell SDK](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/automate-and-manage-azure-ad-tasks-at-scale-with-the-microsoft/ba-p/1942489) 
> The Microsoft Graph PowerShell SDK is where all our current and future investments are being made.
