### ISSUE TITLE
Automation of app and service principal creation

### ISSUE THREAD

**Issue by premfix** [microsoftgraph/msgraph-sdk-powershell#531]
Hi!
I want to automate the process of custom SAML app creation. I've thought that I can instantiate an app using basic SAML application template by providing template value 8adf8e6e-67b2-4cf2-a259-e3dc5476c621 for ApplicationTemplateId parameter in New-MgServicePrincipal functionapp, but I receive an error: New-MgServicePrincipal : Property 'applicationTemplateId' is read-only and cannot be set. I don't understand the purpose of this parameter then.
Or maybe there is another way of automating custom SAML app creation? I found here a question about Invoke-MgInstantiateApplicationTemplate, but I don't have that function in msgraph-sdk-powershell module. 
[AB#7878](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7878)

**Comment by peombwa** [comment]
@premfix `Invoke-MgInstantiateApplicationTemplate` should be available in both `v1.0` (default) and `beta` profile and should work as expected:
``` powershell
Invoke-MgInstantiateApplicationTemplate -ApplicationTemplateId "8adf8e6e-67b2-4cf2-a259-e3dc5476c621" -DisplayName "Test App!!!"
```

The metadata, that the SDK is generated from, is missing annotations that should tell us what the mandatory parameters are.
