### ISSUE TITLE
-Debug does not print body for Service modules

### ISSUE THREAD

**Issue by finsharp** [microsoftgraph/msgraph-sdk-powershell#537]
`-Debug` does not print the request body for service modules.
![image](https://user-images.githubusercontent.com/1641829/106500090-75f78e80-64d2-11eb-84e6-acd91f42b5e3.png)
However, for `Invoke-MgGraphRequest` 
![image](https://user-images.githubusercontent.com/1641829/106500311-b7883980-64d2-11eb-9f30-43d7fd2a7eb7.png)

Should we keep the behavior or standardize on one?

cc @ddyett @darrelmiller @peombwa 
 
[AB#7922](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7922)

**Comment by peombwa** [comment]
As part of this work item, we should also enable MSAL logging when `-Debug` is specified - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging.
