### ISSUE TITLE
[FEATURE] Get-MgDirectoryObject Filter or Search

### ISSUE THREAD

**Issue by YuriySamorodov** [microsoftgraph/msgraph-sdk-powershell#538]
It would be great to have an option to run `Get-MgDirectoryObject` along with `-Filter` or `-Search` the same way we can run `Get-MgUser` and `Get-MgGroup`. This will help us avoid `if... else` hell.
As of now it would give an error:
![image](https://user-images.githubusercontent.com/5260172/106510381-e78a0980-64df-11eb-85c7-a35cfed28807.png)
 `Get-MgDirectoryObject_List1: Searches against this resource are not supported. Only specific instances can be queried.` 
[AB#7924](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7924)

**Comment by peombwa** [comment]
Thanks for taking the time to open this. This is currently not supported by the service. The PowerShell SDK mirrors the behavior of the service, i.e., what's not supported by the service will not be supported by the SDK.

Please open a feature request https://developer.microsoft.com/en-us/graph/support for the workload to consider your request.
