### ISSUE TITLE
[FEATURE] Get-MgUser and Get-MgGroup Filter or Search By All Properties

### ISSUE THREAD

**Issue by YuriySamorodov** [microsoftgraph/msgraph-sdk-powershell#539]
As of now we have to specify property to run search or filter against of when running `Get-MgUser` or `Get-MgGroup`.
Here is an example:
![image](https://user-images.githubusercontent.com/5260172/106511079-cc6bc980-64e0-11eb-905e-fcccca6ff672.png)

It would be beneficial to be able running search against all properties at once e.g:
`Get-MgUser -Search "Yuriy Samorodov"` 
so it would work like 
`Get-ADUser -LDAPFilter "(anr=Yuriy)"` 
[AB#7925](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7925)

**Comment by JustinGrote** [comment]
These just pass through to the graph search APIs so unless that functionality is added at that level it's unlikely to show up here.

**Comment by peombwa** [comment]
The API already supports `$search` (`-Search`). The support for the [$search](https://docs.microsoft.com/en-us/graph/search-query-parameter?view=graph-rest-beta&tabs=http) query parameter varies by entity, with some, such as Azure AD resources that derive from [directoryObject](https://docs.microsoft.com/en-us/graph/api/resources/directoryobject), supporting $search only in [advanced queries](https://docs.microsoft.com/en-us/graph/aad-advanced-queries).

As stated above, the commands pass through the query parameters straight to the API. Please post a feature request at https://developer.microsoft.com/en-us/graph/support for the API owner to support $search by all or select propertiess.
