### ISSUE TITLE
Uploading user photo

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-powershell#54]
Hi!
First off great job on this new PS "sdk", I think it looks super promising!
Now the question: I'm trying to upload the user's picture, which I think will be a common scenarios for IT pros around the world.
I'm now sure how I should pass the photo binaries however, I've tried something like that and a few variations but it doesn't seem to be working.
```PowerShell
update-userphoto -UserId ef1c916a-3135-4417-ba27-8eb7bd084193 -BodyParameter ([System.IO.File]::ReadAllBytes("C:\Users\vince\Desktop\00003IMG_00003_BURST20170402115324.jpg"))
```
At this point I'm not sure whether I missed something (hence the question) or whether this feature is currently missing in the SDK.
I'm running the beta SDK, updated/installed today.
Thanks for the help!

**Comment by peombwa** [comment]
@baywet, Thanks for bring this to our attention.

The "SDK" currently only supports retrieving the metadata of a user's photo. We will add this to our backlog, and surface cmdlets to retrieve, and set a user's photo $value.

**Comment by peombwa** [comment]
AutoREST open issue https://github.com/Azure/autorest.powershell/issues/206
