### ISSUE TITLE
Invoke-MgGraphRequest tries to deserialize JSON when response Content-Type is unknown

### ISSUE THREAD

**Issue by kamilzzz** [microsoftgraph/msgraph-sdk-powershell#545]
Steps to reproduce:

1. `Select-MgProfile -Name "beta"`
2. Try to upload B2C policy using Invoke-MgGraphRequest - ```Invoke-GraphRequest -Method PUT -Uri "https://graph.microsoft.com/beta/trustFramework/policies/$policyId/`$value" -Body $xml.OuterXml -ContentType 'application/xml' -StatusCodeVariable statusCode -ResponseHeaders responseHeaders -Verbose -Debug```
3. From the DEBUG output you can see the server responded with 200 OK but without content type (?)
```
VERBOSE: received 42555-byte response of content type **shouldn't application/xml be specified here?**
DEBUG: PUT https://graph.microsoft.com/beta/trustFramework/policies/B2C_1A_TrustFrameworkBase/$value
HTTP/1.1 200 OK
Cache-Control: private
Vary: Accept-Encoding
request-id: 2adf4e02-e648-4da7-bbb2-d791201af52d
client-request-id: 2adf4e02-e648-4da7-bbb2-d791201af52d
```
4. From the DEBUG output you can see response is plain XML string:
```
DEBUG: PUT https://graph.microsoft.com/beta/trustFramework/policies/B2C_1A_TrustFrameworkBase/$value
HTTP/1.1 200 OK
Cache-Control: private
Vary: Accept-Encoding
request-id: 2adf4e02-e648-4da7-bbb2-d791201af52d
client-request-id: 2adf4e02-e648-4da7-bbb2-d791201af52d
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"003","RoleInstance":"AGSFE_IN_62"}}
Strict-Transport-Security: max-age=31536000
Date: Sat, 06 Feb 2021 13:39:39 GMT

<TrustFrameworkPolicy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.microsoft.com/online/cpim/schemas/2013/06" PolicySchemaVersion="0.3.0.0" TenantId="kzhcp111.onmicrosoft.com" PolicyId="B2C_1A_TrustFrameworkBase" PublicPolicyUri="http://kzhcp111.onmicrosoft.com/B2C_1A_TrustFrameworkBase" TenantObjectId="5e74b3b3-981c-493d-b8ef-c85403cf40a4">
  <BuildingBlocks>
    <ClaimsSchema>
[...]
```
5. Error is written to the console
```
Invoke-MgGraphRequest: Conversion from JSON failed with error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```
I suspect error comes from https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/390706e3cbc026fc9f37267c8dd6cb2caad04c99/src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs#L461
6. Neither -StatusCodeVariable nor -ResponseHeaders are set (they are empty) 
[AB#8028](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8028)

**Comment by kamilzzz** [comment]
Turned out the code fragment I linked is not current version as I linked older branch...
Current version handles `-OutputType` but still fails with default value.

To not fail I have to use `-OutputType Json` (but the response isn't JSON at all) or `-OutputType HttpResponseMessage`

**Comment by finsharp** [comment]
@kamilzzz When we implement the referenced item ( #534 ), we will resolve this issue after.
