### ISSUE TITLE
Authorization issue accessing OneNote items

### ISSUE THREAD

**Issue by stevenbuehler** [microsoftgraph/msgraph-sdk-powershell#546]
Any idea how to fix? Using my personal MS Account trying to access OneNote. Identifying info removed for obvious reasons.

```
PS /Users/steven> connect-mggraph -Scopes "Notes.ReadWrite.All", "Files.ReadWrite.All", "offline_access"                                                                 

Welcome To Microsoft Graph!
PS /Users/steven> Get-MgUserOnenoteSection -UserId “<user>@outlook.com" -OnenoteSectionId “<section guid>”

Get-MgUserOnenoteSection_Get1: The request does not contain a valid authentication token. Detailed error information: {0}
``` 
[AB#8029](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8029)

**Comment by peombwa** [comment]
As per the [docs](https://docs.microsoft.com/en-us/graph/api/section-get?view=graph-rest-1.0&tabs=http#permissions), it looks like you need to consent to `Notes.Read, Notes.Create, or Notes.ReadWrite` since this is a delegated (personal Microsoft account) - `Connect-MgGraph -Scopes "Notes.Read"`.

**Comment by stevenbuehler** [comment]
That solved it; you would think that `Notes.ReadWrite.All` would be sufficient.
