### ISSUE TITLE
AssignedLicenses User Property is null

### ISSUE THREAD

**Issue by stvpwrs** [microsoftgraph/msgraph-sdk-powershell#547]
When running `Get-MgUser` the returned object's `AssignedLicenses` property is null. This is true for a single user that has confirmed licenses assigned and when run against all users, all instances being null.

There are no errors thrown and permissions are as follows:

Application - User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All

In general, a very significant amount of all properties appear null for objects returned from this Cmd-let.

 
[AB#8040](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8040)

**Comment by peombwa** [comment]
You need to specify a `-Property assignedLicenses` to `Get-MgUser` like this:
``` powershell
Get-MgUser -UserId $UserId -Select id, displayName, assignedLicenses
```

The API requires a `$select` inorder to retreive a user's assignedLicenses. See the explanation here https://stackoverflow.com/questions/36712058/how-to-obtain-the-assignedlicenses-using-microsoft-graph-client-library.

**Comment by stvpwrs** [comment]
Thanks for the reply on this. That makes sense. Can be tricky switching between modules and remembering that the Graph is under everything.
