### ISSUE TITLE
Implement interactive sign-in

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#555]
Device code flow is blocked by many corporations that have Intune managed devices.  The reason they block Device Code flow is because it is possible to run an app on an unmanaged device, but then do the device code flow handshake on a managed device, therefore circumventing the conditional access policy.

It is my understanding that MSAL.NET supports interactive flow cross platform, so we should investigate enabling this so that users can use our PowerShell modules in these Intune Managed environments. 
[AB#8122](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8122)

**Comment by finsharp** [comment]
Depends on #534
