### ISSUE TITLE
Get-MgServicePrincipalAppRoleAssignment unable to query role assignments for MSI

### ISSUE THREAD

**Issue by Ayanmullick** [microsoftgraph/msgraph-sdk-powershell#556]
How could one get the roles assigned to a service principal?

- `Microsoft.Graph.Identity.ServicePrincipal\Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId <>`  doesn't work.

- `Get-AzRoleAssignment -ServicePrincipalName  https://identity.azure.net/<>` doesn't work

https://github.com/Azure/azure-powershell/issues/10550#issuecomment-554844241  mentioned it needed access to the directory. I even added `Global Reader` role for the service principal. It still doesn't work.

`Get-MgUserAppRoleAssignment -UserId <>` and `Get-AzRoleAssignment` work for users. However, I can't get it to work for a service principal. 
[AB#8130](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8130)

<details>

<summary>$PSVersionTable</summary>

| Name                      | Value                        |
|---------------------------|------------------------------|
| OS                        | Microsoft Windows 10.0.19042 |
| PSVersion                 | 7.1.1                        |
| WSManStackVersion         | 3                            |
| PSCompatibleVersions      | {1.0, 2.0, 3.0, 4.0…}        |
| PSRemotingProtocolVersion | 2.3                          |
| PSEdition                 | Core                         |
| SerializationVersion      | 1.1.0.1                      |
| GitCommitId               | 7.1.1                        |
| Platform                  | Win32NT                      |

</details>

<details>

<summary>Get-Module -ListAvailable -Name Microsoft.Graph*|select ModuleType,Version,CompatiblePSEditions,Name</summary>

| ModuleType | Version    | CompatiblePSEditions | Name                                                       |
|------------|------------|----------------------|------------------------------------------------------------|
| Manifest   | 1.0.1      | {Core, Desktop}      | Microsoft.Graph                                            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Analytics                                  |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Analytics                                  |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Applications                               |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Authentication                             |
| Binary     | 0.1.5      | {Core, Desktop}      | Microsoft.Graph.Authentication                             |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Bookings                                   |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Bookings                                   |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Calendar                                   |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.ChangeNotifications                        |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.CloudCommunications                        |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Compliance                                 |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.CrossDeviceExperiences                     |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Devices.CloudPrint                         |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Devices.CorporateManagement                |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.DevicesApps.DeviceAppManagement            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.DevicesApps.MobileAppManagement            |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.DevicesApps.MobileAppManagement            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.DevicesApps.OfficeConfiguration            |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.DevicesApps.OfficeConfiguration            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.DevicesApps.SharedResources                |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.DevicesApps.SharedResources                |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.DirectoryObjects                           |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Education                                  |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Education                                  |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Files                                      |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Files.Drives                               |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Files.Drives                               |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Files.Permissions                          |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Files.Permissions                          |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Files.Shares                               |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Files.Shares                               |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Financials                                 |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Groups                                     |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Actions                             |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Calendar                            |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Calendar                            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Conversation                        |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Conversation                        |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.ConversationThread                  |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.ConversationThread                  |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.DirectoryObject                     |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.DirectoryObject                     |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Drive                               |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Drive                               |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Endpoint                            |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Endpoint                            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Extension                           |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Extension                           |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Functions                           |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Functions                           |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Group                               |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Group                               |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.LifecyclePolicies                   |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.LifecyclePolicies                   |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.OneNote                             |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.OneNote                             |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Planner                             |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Planner                             |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.ProfilePhoto                        |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.ProfilePhoto                        |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Site                                |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Groups.Site                                |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AccessReview                      |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AccessReview                      |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AdministrativeUnits               |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AdministrativeUnits               |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Application                       |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Application                       |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AppRoleAssignments                |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AppRoleAssignments                |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AuditLogs                         |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AuditLogs                         |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AuthenticationMethods             |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AzureADPIM                        |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.AzureADPIM                        |
| Script     | 0.7.1      | {Core, Desktop}      | Microsoft.Graph.Identity.CertificateBasedAuthConfiguration |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.CertificateBasedAuthConfiguration |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.ConditionalAccess                 |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Contracts                         |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Contracts                         |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DataPolicyOperations              |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DataPolicyOperations              |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Devices                           |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Devices                           |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Directory                         |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Directory                         |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectoryManagement               |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectoryObjects                  |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectoryObjects                  |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectoryRoles                    |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectoryRoles                    |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectoryRoleTemplates            |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectoryRoleTemplates            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectorySettings                 |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectorySettings                 |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectorySettingTemplates         |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectorySettingTemplates         |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Domains                           |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Domains                           |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Governance                        |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Invitations                       |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Invitations                       |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.OAuth2PermissionGrants            |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.OAuth2PermissionGrants            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.OnPremisesPublishingProfiles      |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.OnPremisesPublishingProfiles      |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Organization                      |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Organization                      |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.OrganizationContacts              |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.OrganizationContacts              |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Policies                          |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Policies                          |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Protection                        |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Protection                        |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Providers                         |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.Providers                         |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.RoleManagement                    |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.ServicePrincipal                  |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.ServicePrincipal                  |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Identity.SignIns                           |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.SubscribedSkus                    |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.SubscribedSkus                    |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.TermsOfUse                        |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.TermsOfUse                        |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.TrustFramework                    |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Identity.TrustFramework                    |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Identity.UserFlows                         |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Mail                                       |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Notes                                      |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Notification                               |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Notification                               |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.OnlineMeetings                             |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.OnlineMeetings                             |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.People                                     |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.PersonalContacts                           |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Places                                     |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Places                                     |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Planner                                    |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Planner                                    |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Reports                                    |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.SchemaExtensions                           |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.SchemaExtensions                           |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Search                                     |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Security                                   |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Sites                                      |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Sites.Actions                              |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Sites.Drive                                |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Sites.Drive                                |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Sites.Functions                            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Sites.List                                 |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Sites.List                                 |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Sites.OneNote                              |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Sites.OneNote                              |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Sites.Pages                                |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Sites.Pages                                |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Sites.Site                                 |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Sites.Site                                 |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Subscriptions                              |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Subscriptions                              |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Teams                                      |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Teams.AppCatalogs                          |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Teams.AppCatalogs                          |
| Script     | 0.5.1      | {Core, Desktop}      | Microsoft.Graph.Teams.Channel                              |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Teams.Channel                              |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Teams.Chats                                |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Teams.Chats                                |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Teams.Team                                 |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Teams.Team                                 |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Teams.Teamwork                             |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Teams.Teamwork                             |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Users                                      |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Users.Actions                              |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.ActivityFeed                         |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.ActivityFeed                         |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.Calendar                             |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.Calendar                             |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.Contacts                             |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.Contacts                             |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.Devices                              |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.Devices                              |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.DirectoryObject                      |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.DirectoryObject                      |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.Drive                                |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.Drive                                |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.Extensions                           |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.Extensions                           |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.FollowedSites                        |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.FollowedSites                        |
| Script     | 1.0.1      | {Core, Desktop}      | Microsoft.Graph.Users.Functions                            |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.Functions                            |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.Groups                               |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.Groups                               |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.InformationProtection                |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.InformationProtection                |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.LicenseDetails                       |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.LicenseDetails                       |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.Mail                                 |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.Mail                                 |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.OneNote                              |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.OneNote                              |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.OutlookUser                          |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.OutlookUser                          |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.People                               |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.People                               |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.Planner                              |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.Planner                              |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.ProfilePhoto                         |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.ProfilePhoto                         |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.User                                 |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.User                                 |
| Script     | 0.9.1      | {Core, Desktop}      | Microsoft.Graph.Users.UserSettings                         |
| Script     | 0.1.1      | {Core, Desktop}      | Microsoft.Graph.Users.UserSettings                         |
| Manifest   | 1.2.0      | {Core, Desktop}      | Microsoft.Graph                                            |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Applications                               |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Authentication                             |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Bookings                                   |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Calendar                                   |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.ChangeNotifications                        |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.CloudCommunications                        |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Compliance                                 |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.CrossDeviceExperiences                     |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Devices.CloudPrint                         |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Devices.CorporateManagement                |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.DirectoryObjects                           |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Education                                  |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Files                                      |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Financials                                 |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Groups                                     |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Identity.DirectoryManagement               |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Identity.Governance                        |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Identity.SignIns                           |
| Binary     | 6.1907.1.0 | {}                   | Microsoft.Graph.Intune                                     |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Mail                                       |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Notes                                      |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.People                                     |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.PersonalContacts                           |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Planner                                    |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Reports                                    |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.SchemaExtensions                           |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Search                                     |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Security                                   |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Sites                                      |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Teams                                      |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Users                                      |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Users.Actions                              |
| Script     | 1.2.0      | {Core, Desktop}      | Microsoft.Graph.Users.Functions                            |

</details>

**Comment by psignoret** [comment]
@Ayanmullick Apologies for the delay here. Could you clarify what kinds of roles you're referring to? Azure role assignments (e.g. "Owner", "Contributor", etc.)? Azure AD directory role assignments (e.g. "Application Administrator", etc.)? App role assignments?

**Comment by Ayanmullick** [comment]
@psignoret, I was unable to contact you in Teams. I'm looking to get the Azure role assignments for the service principal, like `Owner`, `Reader` or any custom role assigned at an Azure resource level.

**Comment by psignoret** [comment]
Querying Azure role assignments is not done with the Microsoft Graph API (or Microsoft Graph PowerShell). Azure role assignments are [managed with the Azure REST API](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-rest) (and [Azure PowerShell](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-powershell)).

**Comment by Ayanmullick** [comment]
`Get-AzRoleAssignment -ServicePrincipalName <>` isn't working either. Should one open a separate issue in the Azure PowerShell repository?

**Comment by psignoret** [comment]
If you're completely sure the value you're giving for the `-ServicePrincipalName` paramter is actually a `servicePrincipalName` for the managed identity's service principal—then yes, you should open an issue over there. In your issue, be sure to include a call to `Get-AzADServicePrincipal -ServicePrincipalName "{spn}"` to demonstrate that the service principal does exist.

**Comment by psignoret** [comment]
#please-close

**Comment by Ayanmullick** [comment]
Ok, @psignoret , And is there a way to query the Azure role assignments across subscriptions in one go like one can query all subscriptions from the tenant level in one go with Resource graph? I thought MSGraph would have a way to query these details from the tenant level.

**Comment by psignoret** [comment]
You'll need to ask those questions to the Azure RBAC folks.

**Comment by Ayanmullick** [comment]
> Ok, @psignoret , And is there a way to query the Azure role assignments across subscriptions in one go like one can query all subscriptions from the tenant level in one go with Resource Graph? I thought MSGraph would have a way to query the subscription-level role assignment details from the tenant level.

Maybe one is able to do this using resource graph. However, I couldn't locate any PowerShell documentation for it.

**Comment by psignoret** [comment]
@Ayanmullick This PowerShell module is for calling Microsoft Graph, which does not include any information about Azure role assignments. Please refer to the [Azure PowerShell](https://docs.microsoft.com/powershell/azure) documentation and raise issues/questions on the [Azure PowerShell repo on GitHub](https://github.com/Azure/azure-powershell).
