### ISSUE TITLE
Security cmdlets require additional permissions or roles?

### ISSUE THREAD

**Issue by melvinveenbrink** [microsoftgraph/msgraph-sdk-powershell#558]
## Connection Information
$ClientID = "<clientID>"
$TenantID = "<TenantID"
$thumbPrint = "<cert_thumbprint>"
$ClientCertificate = Get-Item "Cert:\CurrentUser\My\$($thumbPrint)"

##Connect to Graph Beta API
Connect-MgGraph -ClientID $ClientID -TenantId $TenantID -CertificateThumbprint $thumbPrint
Select-MgProfile "beta"
Get-MgSecurityTiIndicator -TiIndicatorId "<TiIndicatorID>"

The ServicePrincipal has the following API permissions:
Ti.Read.All - Application
Ti.ReadWrite - Delegated
Ti.ReadWrite - Application
Ti.ReadWrite.All - Application.

However when running the command Get-MgSecurityTiIndicator an permissions error occurs:
New-MgSecurityTiIndicator : Auth token does not contain valid permissions or user does not have valid roles.
At line:1 char:1
+ New-MgSecurityTiIndicator
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ body = Micros...phTiIndicator }:<>f__AnonymousType14`1) [New-MgSecurityTiIndicator_CreateExpanded], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.NewMgSecurityTiIndicator_CreateExpanded

 
[AB#8170](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8170)

**Comment by PsychoData** [comment]
Can you provide the output of `Get-MGContext` and `Get-MgContext |select -ExpandProperty Scopes` if you can't read all of the scopes?

**Comment by melvinveenbrink** [comment]
Scopes are empty as i'm connecting with a app only SP with certificate

Scopes                :
AuthType              : AppOnly
CertificateName       :
Account               :
AppName               : DefenderATP-Automation
ContextScope          : Process
Certificate           :

**Comment by peombwa** [comment]
As per the [docs](https://docs.microsoft.com/en-us/graph/api/tiindicators-post?view=graph-rest-beta&tabs=http#permissions), you'll need to grant your service principal `ThreatIndicators.ReadWrite.OwnedBy` permission.

**Comment by melvinveenbrink** [comment]
@peombwa  Yes this works! your help is appreciated,tnx!
