### ISSUE TITLE
New-MgTeamChannelMessage -From user configuration

### ISSUE THREAD

**Issue by smholvoet** [microsoftgraph/msgraph-sdk-powershell#559]
My goal is to send [chat messages](https://docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&tabs=http) in a specific Teams channel, using the identity of a specific 🤖 bot user, lets call him `my-bot-user`.

I've created an [app registration](https://docs.microsoft.com/en-us/graph/powershell/app-only?tabs=azure-portal), which gets me a token. I've gone through the docs multiple times, but can't seem to find which steps I need to go through exactly in order to use the identity of my generic "bot" account as the *from* user.

Could someone point into the right direction? This is what I have so far:

```powershell
Connect-MgGraph -ClientID $ClientId -TenantId $TenantId -CertificateName $CertificateName

$User = Get-MgUser -UserId "my-bot-user" | Select-Object id, displayName, userIdentityType

$BotUser  = @{
    Id = $User.Id;
    DisplayName = $User.DisplayName;
    UserIdentityType = "aadUser";
}

New-MgTeamChannelMessage -ChannelId $ChannelId 
                         -TeamId $TeamId `
                         -Body @{ `
                             Content = "Hello World" `
                         } `
                         -From @{ `
                             User = $BotUser `
                         } 
``` 
[AB#8182](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8182)

**Comment by peombwa** [comment]
@smholvoet I don't think sending a message from a user (bot) using [application permission](https://docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&tabs=http#permissions) is supported unless you are importing messages in [migration mode](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams#step-three-import-messages).

To send a message to a channel, you'll need to authenticate to using the identity of the user who is sending the message i.e. `Connect-MgGraph -Scopes 'ChannelMessage.Send'`. Your only option is to use a [Teams conversation bot](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=dotnet) as shown in this [sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel).

I would also suggest you open a feature request at https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests for the service team.

**Comment by smholvoet** [comment]
Thx for the swift response @peombwa.

Wouldn't this render the `-From` parameter redundant, even though it's explicitly mentioned in the help section of this cmldet?

```powershell
Get-Help New-MgTeamChannelMessage -Full  
```

```
...

-From <IMicrosoftGraphIdentitySet>
        identitySet
        To construct, see NOTES section for FROM properties and create a hash table.

        Required?                    false
        Position?                    named
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

...
```

I'm guessing this parameter just gets disregarded? 

In summary, there is no way for me to use delegated permissions and run this "unattended" (in Azure Pipelines) in order to use the identity of a specific user within my AAD? I'll have to use `Connect-MgGraph` which prompts me to a web page which ruins the "headless" / daemon workflow I'm after? 😞

**Comment by peombwa** [comment]
`-From` is only ever used in migration mode in conjunction with ` -CreatedDateTime` when importing messages from a 3rd party platform, see https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams#request-post-message-that-is-text-only.

That's right, currently there is no API is Microsoft Graph that supports this scenario. Your best bet is to open a feature request at https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests.

**Comment by smholvoet** [comment]
Thanks for clarifying 👌, too bad this currently isn't supported.
