### ISSUE TITLE
Get-MgUserTeamworkInstalledApp : The server responded with a Request Error, Status: Forbidden

### ISSUE THREAD

**Issue by sfaisalm** [microsoftgraph/msgraph-sdk-powershell#562]
Hi,

Getting below error for MgUserTeam related get command.
1.3.1                Microsoft.Graph                     PSGallery            Microsoft Graph PowerShell module
Tried to re install, no improvement. 

Get-MgUserTeamworkInstalledApp : The server responded with a Request Error, Status: Forbidden
At line:1 char:1
+ Get-MgUserTeamworkInstalledApp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = 5b64...ndProperty =  }:<>f__AnonymousType66`9) [Get-MgUser
   TeamworkInstalledApp_List1], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgUserTeamworkInstalledApp_List1
I am getting 
 Get-MgTeam 
[AB#8189](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8189)

**Comment by sfaisalm** [comment]
get-mgteam is working fine.

**Comment by peombwa** [comment]
Try running ` (Get-MgContext).Scopes` to see if you have the correct permission needed to make this call, see https://docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-1.0&tabs=http#permissions.

If you don't have the needed permission, use `Connect-MgGraph -Scopes "TeamsAppInstallation.ReadForUser"` to consent to the right permission.

**Comment by sfaisalm** [comment]
PS M:\> (get-mgcontext).scopes
Group.ReadWrite.All
openid
profile
User.Read
User.Read.All
email

**Comment by sfaisalm** [comment]
wow, cant believe Scopes "TeamsAppInstallation.ReadForUser" worked which i was struggling for weeks.
Thank you for your help

**Comment by sfaisalm** [comment]
Hi Peter,
Below command still giving same, is there any other scope we need?
PS M:\> Get-MgAppCatalogTeamApp
Get-MgAppCatalogTeamApp : The server responded with a Request Error, Status: Forbidden
At line:1 char:1
+ Get-MgAppCatalogTeamApp
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType12`8) [Get-MgAppC
   atalogTeamApp_List1], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgAppCatalogTeamApp_List1

thanks

**Comment by sfaisalm** [comment]
can anyone advise on this please?

**Comment by sfaisalm** [comment]
Objective is to get list of applications assigned to a user or assigned to any user. Unable to achieve this goal, any help will be highly appreciated.

**Comment by sfaisalm** [comment]
also i can see below command is working from Graph explorer, if this command can work from powershell, we can extract report of installed app fro all users.
How can we run below from powershell?

GET https://graph.microsoft.com/v1.0/users/5b649834-7412-4cce-9e69-176e95a394f5/teamwork/installedApps

**Comment by peombwa** [comment]
@sfaisalm Sorry for the delayed response. As per [the docs](https://docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-1.0&tabs=http#permissions), any of the following permissions should be sufficient to list apps installed for the signed in user:
- TeamsAppInstallation.ReadForUser
- TeamsAppInstallation.ReadWriteSelfForUser
- TeamsAppInstallation.ReadWriteForUser

You'll need to use [app-only authentication](https://docs.microsoft.com/en-us/graph/powershell/app-only?tabs=azure-portal) to list apps installed for any user is the above permissions do not work - https://docs.microsoft.com/en-us/graph/permissions-reference#application-permissions-61.
