### ISSUE TITLE
`Connect-GraphAPI` `ClientId` parameter should allow public client appid's

### ISSUE THREAD

**Issue by adamedx** [microsoftgraph/msgraph-sdk-powershell#563]
Currently it seems that a custom appid may only be used if you are doing app-only authentication. The request is to support this for delegated authorization via a public client appid. This would also allow administrators the ability to provide manage applications separate for different sets of delegated administrators and in general could allay concerns about the use of multi-tenant applications in some environments.

Currently specification of an appid fails due to the assumption of app-only flow when using the `ClientId` parameter:

```powershell
Connect-MgGraph -ClientId 8a6a62f3-e5f0-4a15-bb92-c9daf8a107c0

Connect-MgGraph : Must specify CertificateThumbprint or CertificateName
At line:1 char:1
+ Connect-MgGraph -ClientId 8a6a62f3-e5f0-4a15-bb92-c9daf8a107c0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-MgGraph], ArgumentException
    + FullyQualifiedErrorId : 9d7d02f2-6013-409d-a9c5-e5a922d744c1,Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph
``` 
[AB#8190](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8190)

**Comment by berviantoleo** [comment]
I am looking at this too. I am new here and new to powershell module code. Is it this feature good enough for newcomer like me? I would like to help if it is not really complex.

**Comment by peombwa** [comment]
Closed by https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/615
