### ISSUE TITLE
Commands should request permissions based on scopes in decorated metadata

### ISSUE THREAD

**Issue by adamedx** [microsoftgraph/msgraph-sdk-powershell#564]
Currently, users must know the permissions required for every command. Currently there are 497 (and counting!) permissions to choose from, so clearly this is an unreasonable expectation.

To address this, a solution like the following could be implemented:
* The [openapi specs](https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/dev/openApiDocs/v1.0) in this repo should support the ability to decorate the API and thus the associated commands with the most likely required permission.
  * This decoration could be manual or (even better) automated based on authoritative sources
* The generated command could then request this permission at runtime so that users would not have to do research.

 
[AB#8191](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8191)

**Comment by timayabi2020** [comment]
Solution to #2008 will probably address this one too.

**Comment by calebkiage** [comment]
@adamedx, we don't automatically request for permissions, but there's a [`Find-MgGraphCommand`](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.authentication/find-mggraphcommand?view=graph-powershell-1.0) cmdlet that shows you what permissions a command needs.
