### ISSUE TITLE
Connect-MgGraph doesn't have ContextScope in AccessTokenParameterSet

### ISSUE THREAD

**Issue by gaikovoi** [microsoftgraph/msgraph-sdk-powershell#572]
New module version (1.4) does not allow to set context scope for MS Graph connection using access token.
This used to work in v 1.3.x:

`Connect-MgGraph -AccessToken $t -ContextScope Process`

With 1.4, we get error:

Connect-MgGraph: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided. 
[AB#8455](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8455)

**Comment by peombwa** [comment]
@gaikovoi Sorry about that. You actually don't need specify `-ContextScope` when using `Connect-MgGraph` with `-AccessToken` parameter. `Connect-MgGraph -AccessToken` was always running under the context of a process and specifying `-ContextScope` didn't do anything as noted in this bug #510. 

Ref https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Authentication/Authentication/Cmdlets/ConnectMgGraph.cs#L195

**Comment by gaikovoi** [comment]
@peombwa 
Hi Peter,

Thank you for the explanation.
