### ISSUE TITLE
Get-MSGServicePrincipal cmdlet missing SearchString, uses Search instead

### ISSUE THREAD

**Issue by mlhickey** [microsoftgraph/msgraph-sdk-powershell#590]
Ver 1.4.2 - Using Get-MSGServicePrincipal to search by name, the cmdlet does not have the documented -SearchString <String> parameter.  Instead it has a -Search which ultimately renders into the following with has the $search collection parameter:

Get-MgServicePrincipal -Search "Microsoft Seller Dashboard" -Debug
DEBUG: RequestCreated: https://graph.microsoft.com/v1.0/servicePrincipals?$search="Microsoft Seller Dashboard"
DEBUG: HeaderParametersAdded: https://graph.microsoft.com/v1.0/servicePrincipals?$search="Microsoft Seller Dashboard"
DEBUG: GET /v1.0/servicePrincipals?$search=%22Microsoft%20Seller%20Dashboard%22 HTTP/1.1
HTTP: graph.microsoft.com 

This exists across other cmdlets as well, e.g. Get-MGUser, Get-MGDevice.  Seems pervasive
[AB#8687](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8687)

**Comment by peombwa** [comment]
@mlhickey Where is `-SearchString` parameter documented? `Get-Help  Get-MGServicePrincipal` yields the following:
![image](https://user-images.githubusercontent.com/7061532/112021937-09bb0380-8aef-11eb-8acf-4df86e4cb6be.png)

Where `[-Search <String>]` means -Search accepts values of type string.

**Comment by mlhickey** [comment]
-Search is invoking Graph with the $search parameter which (from my understanding and documentation) is for collections: Use query parameters to customize responses - Microsoft Graph | Microsoft Docs<https://docs.microsoft.com/en-us/graph/query-parameters#search-parameter> and does not seem relevant in this situation.

If attempting to search for a service principal by name it seems there should instead be -SearchString  which aligns with existing AzureAD* cmdlets and performs an ANR search, e.g.

Get-AzureADServicePrincipal -SearchString "KustoQueryExecute" | Select-Object DisplayName,ServicePrincipalType

DisplayName       ServicePrincipalType
-----------       --------------------
KustoQueryExecute Application

Vs.

Get-MGServicePrincipal -Search "KustoQueryExecute" -top 1 | Select-Object DisplayName,ServicePrincipalType

DisplayName                ServicePrincipalType
-----------                --------------------
Office 365 Exchange Online Application

I specified top because the query parameter is ignored and the default first 100 are returned.

(Get-MGServicePrincipal -Search "KustoQueryExecute" | Select-Object DisplayName,ServicePrincipalType).Count
100


Cheers,
Mike
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
