### ISSUE TITLE
Competing versions of the same class(es) in different modules. 

### ISSUE THREAD

**Issue by jhoneill** [microsoftgraph/msgraph-sdk-powershell#594]
I recently encountered errors as follows 
1. I fetched some contact data with  `invoke-mgGraphRequest`, 
2. I tried to use this data to populate a new  `Microsoft.Graph.PowerShell.Models.MicrosoftGraphContact` Object.
3. Some of the fields returned were _not present_ in the new  `MicrosoftGraphContact`  object.
4. When I fetched the same object using `Get-MgUserContact`  it returned `MicrosoftGraphContact`  _with all the fields_ returned at step 1  present and populated. 
5. On investigation `New-Object` created an object using the assembly from the `Users` module which was loaded first. The objects created by commands in the `Personal contacts` module uses the assembly from that module (but nothing else can). 

**Hypothesis** Many objects are defined in more than a single OpenAPI file (`users` contains many objects which relate to a user e.g. user's contacts, but a separate file deals with actions relating to contacts.)  A module is built from each file, which contains a  DLL with all the defined classes, so a class defined in more than one OpenAPI file will be present in more than one DLL.  The class definitions are not kept in sync between OpenAPI files.   This may be unique to `MicrosoftGraphContact` but it could happen to any class with duplicate definitions. The code below looks at all the YAML files there are 866 unique classes, but some - like `OutlookItem` are defined in many files.  So the total number of class declarations is 4807. 

```
#cd   msgraph-sdk-powershell\openApiDocs\v1.0

> $classes = Get-Item *.yml | ForEach-Object  {
     $y = convertfrom-yaml (Get-Content $_ -Raw)      
     $n = $_.Name
     $y.components.schemas.keys | ForEach-Object {[pscustomobject]@{file=$n;class=$_}} 
}
 
> $classes.Count

4807

> $gr = $classes | group -Property class -no
> $gr.count
866
```

# Repro

```
# Load the users module into a clean session 
> import-module Microsoft.Graph.users
> Connect-MgGraph
# Force personal contacts module to load
> $contacts = Get-MgUserContact -UserId  myID@mydomain.com 

#Get an object of the same type 
> $obj = New-Object -TypeName $contacts[0].GetType().FullName
> $pList = $contacts| gm -MemberType Property | % name
> $PList2 = $obj | gm -MemberType Property | % name
> $PList2 | where {$_ -notin $PList}
BusinessAddress
BusinessHomePage
BusinessPhones
HomeAddress
HomePhones
MobilePhone
OtherAddress
> $PList | where {$_ -notin $PList2}
Flag
Gender
IsFavorite
Phones
PostalAddresses
Websites
WeddingAnniversary

> $obj.GetType().Assembly

GAC    Version        Location
---    -------        --------
False  v4.0.30319     ...\Microsoft.Graph.users\1.4.0\bin\Microsoft.Graph.Users.private.dll

> $contacts[0].GetType().Assembly
GAC    Version        Location
---    -------        --------
False  v4.0.30319     ...\Microsoft.Graph.PersonalContacts\1.4.0\bin\Microsoft.Graph.PersonalContacts.private.dll
```
 
[AB#8709](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8709)

**Comment by peombwa** [comment]
Sorry for the delayed response.

The conflict was due to how v1.0 and beta model classes were namespaced  In v1.x of the module, all model classes were generated under the same namespace to support the use of `Select-MgProfile`. This led to competing model class names on import as there was no way to disambiguate between v1.0 and beta model types across modules.

In v2.x, we've changed how model classes are namespaced as explained in https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/docs/upgrade-to-v2.md#beta-namespace. The repro steps above no longer returns excluded property types when using `v2.x`. Please let us know if you are still having the same issue in `v2.x`.
