### ISSUE TITLE
Navigation Properties that do not support Expand should not be part of the response model

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#60]
Ideally we should remove all navigation properties that cannot be expanded.  They are just cluttering up the model.  This should actually be done in the OpenAPI generation step.
[AB#6083](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6083)

**Comment by darrelmiller** [comment]
Not sure what changed but the OpenAPI descriptions now how $expand https://graphexplorerapi.azurewebsites.net/openapi?operationIds=groups.group.ListGroup

**Comment by peombwa** [comment]
Duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/89.
