### ISSUE TITLE
Get-MgSite and Get-MgSubSite need to return the Permissions property

### ISSUE THREAD

**Issue by kathyblasco** [microsoftgraph/msgraph-sdk-powershell#600]
Permissions is a propery in both Get-MgSite and Get-MgSubSite but no data is returned for Permssions. Tried both commands using '-ExpandProperty' and '-Property' and there is still no data in the Permissions Property. I also need Permissions returned for Libraries, Files, and Folders.

See: [https://docs.microsoft.com/en-us/answers/questions/336355/has-anyone-been-able-to-retrieve-site-permissions.html](https://docs.microsoft.com/en-us/answers/questions/336355/has-anyone-been-able-to-retrieve-site-permissions.html)

Maybe what is needed is to develop the Graph Permissions module as described by: [https://docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&tabs=http](https://docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&tabs=http)

Are there any plans to provide SharePoint permissions at any level in upcoming versions? 
[AB#8791](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8791)

**Comment by peombwa** [comment]
Thanks for opening this bug. 

I can indeed confirm that the SDK is missing `Get-MgSitePermission` command that should call `/sites/{sitesId}/permissions`. We need to update our modules mapping to cover this. This should be available in upcoming versions.

**Comment by peombwa** [comment]
For driveItems, we will need to wait for `drives/driveItem/{driveItem-id}/permissions` to be added the OpenAPI document that this SDK is generated from. This can be tracked here https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/509.

**Comment by kathyblasco** [comment]
Thanks Peter!

I found some commands to gather permissions but I am betting that they will
be better and faster using Graph. The statements I found for Library
permissions on Stack Exchange don't report just the library
permissions either, they are reporting the Sites permissions. I might have
to manually check the permissions for each of my libraries that report
broken inheritance. At least I have that!

Kathy Blasco

**Comment by peombwa** [comment]
@kathyblasco, as a workaround, you could use `Invoke-MgGraphRequest` to list `site` and `driveItem` permissions like this:
``` powershell
# Authenticate as usual.
Connect-MgGraph

# Get site permissions
Invoke-MgGraphRequest -Uri "v1.0/sites/$SiteId/permissions"

# Get driveItem permissions
Invoke-MgGraphRequest -Uri "v1.0/drives/$DriveId/items/$DriveItemId/permissions"
```
 `Invoke-MgGraphRequest` is a command that we recently added to the SDK for making arbitrary requests to Graph.

**Comment by kathyblasco** [comment]
I would (and I already tried that) except that the graph Permissions call
isn't working either! That was also reported in a Q and A but I have not
gotten a response on that either! I think I posted wrong though as it was
my issue already posted by someone else.

https://docs.microsoft.com/en-us/answers/questions/307911/graph-api-sharepoint-site-permissions-operation-no.html

Kathy Blasco

**Comment by lbenkensteinGP** [comment]
How to update the necessary modules to 1.10.0?

**Comment by lbenkensteinGP** [comment]
I updated Microsoft.Graph to 1.10.0 but permissions output are still empty after running "_Get-MgSite -Property Permissions -SiteId <siteid>_" or "_Get-MgSitePermission -SiteId <siteid>_".

**Comment by teephysicist** [comment]
Hello, I am running into the same issue even after updating to v1.10.0.
I have connect using app only authentication with the Sites.Fullcontrol.All permission: 
![Get-MGcontext](https://user-images.githubusercontent.com/109595606/179744147-0e701d47-7b42-414e-a7fd-bfa1b62c64a7.png)
The Microsoft.Graph.Sites module has version 1.10.0:
![Get-module MGgraph](https://user-images.githubusercontent.com/109595606/179744354-d2f981c9-6cb8-4273-8811-12cae3e5c8fb.png)
Running get-mgsite -siteid root, the permissions are still empty:
![Get-MGsite](https://user-images.githubusercontent.com/109595606/179744930-3f5baabf-fcbd-4c23-a7bd-8c2da0cca071.png)
Running get-mgsitepermission -siteid root permissions are also empty: 
![Get-MgsitePermission](https://user-images.githubusercontent.com/109595606/179745044-e36ab173-9bd1-4ab2-bf4a-e65f4b8f2e29.png)

**Comment by Asaurdiff-Tillamook** [comment]
I am not sure why this issue was closed. This is still not resolved. Generally, we don't need permissions to the Root site. WE need permissions to the sites we have created. The Owner/Member/Visitor groups of each individual site. I understand if the sub library or broken inheritance is taken away, but this top level permissions should be seen. 
I am currently on Module Version 1.9.3 and this is still not showing up. Whether i look under Get-MGSite or Get-MGSitePermissions. If this was resolved please tell me how this can be addressed. currently: 
 Get-mgsite -All | Where {$_.WebUrl -eq <WebUrl>} | Get-MgSitePermission -siteId $_.Id 

Nor taking the Site ID as a variable or direct. The permissions still don't appear.

**Comment by Skaldhor** [comment]
@peombwa Please reopen this issue.
Just like @teephysicist I'm receiving the same output.
App-only auth with Sites.Fullcontrol.All permission is used, site can be found, Get-MgSitePermission returns nothing, also no error.
`Invoke-MgGraphRequest -Uri "v1.0/sites/$SiteId/permissions"` also returns an empty value.

**Comment by tberta** [comment]
The simplest and clearer method I've found to show the existing permissions is by using ToJsonString() method:
`$Perm = Get-MgSitePermission -SiteId $siteId `
`$Perm.ToJsonString()`
roles (read or write) are missing here. To get them, query with the PermissionId. I only have permission for 1 application. I suppose you need to adjust the `$Perm` index if several are defined:
`(Get-MgSitePermission -SiteId $siteId -PermissionId $perm.Id).ToJsonString()`
```
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites($SiteId)/permissions/$entity"
,
  "id": "aTowaS.....MxNzcw",
  "grantedToIdentities": [
    {
  "grantedToIdentities": [
    {
      "application": {
        "displayName": "MyAppName",
        "id": "abcd123-dead-beaf-dead-abcd123"
      }
    }
  ],
  "grantedToIdentitiesV2": [
    {
      "application": {
        "displayName": "MyAppName",
        "id": "abcd123-dead-beaf-dead-abcd123"
      }
    }
  ],
  "roles": [ "read" ]
}
```
