### ISSUE TITLE
Get-MgRiskDetection and Get-MgRiskyUser are only available with beta profile

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-sdk-powershell#602]
Both of these endpoints were promoted to v1.0 back in May 2020. Why are the cmdlets only available when using beta? 
[AB#8809](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8809)

**Comment by ddyett** [comment]
not currently in V1 metadata.

**Comment by peombwa** [comment]
The APIs got moved to a new `singleton`. We will need to add `identityProtection` singleton to the modules mapping under `Microsoft.Graph.Identity.SignIns` module.

See [v1.0](https://docs.microsoft.com/en-us/graph/api/riskdetection-list?view=graph-rest-1.0&tabs=http) vs [beta](https://docs.microsoft.com/en-us/graph/api/riskdetection-list?view=graph-rest-beta&tabs=http).
