### ISSUE TITLE
Access denied for Get-MGEducationClassAssignment

### ISSUE THREAD

**Issue by O365Tycho** [microsoftgraph/msgraph-sdk-powershell#606]
I'm trying to get an overview off all assignments in our environment for reporting use.  Unfortunatly there doesn't seem to be a function available to do this so i thought lets loop trough all Class teams and use Get-MgEducationClassAssignment to get this info per class. 
But calling the function gives an error: "Get-MgEducationClassAssignment : Access denied" . Doesn't matter if it's on a class that i'm owner of or another class and i think i have enough permissions on the graph.

**Comment by peombwa** [comment]
Sorry for the delayed response to this issue.

Have you consented to the required permissions as stated in https://docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&tabs=powershell#permissions?

I'm not an expert on education APIs, and I'd recommend you post this service-related question to https://developer.microsoft.com/en-us/graph/support to get assistance directly from the service owners/community. This repo is meant for issues related to the SDK and not the service.
