### ISSUE TITLE
Send-MgUserMail - Example script With Attachments

### ISSUE THREAD

**Issue by montereyharris** [microsoftgraph/msgraph-sdk-powershell#609]
Can we get an example with attachments for sending mail with attachment and attachments? I am tryng to send with the following code and it is not working
`$Message = @{
    subject = "Users ";
    toRecipients = $ToRecipients;
    body = @{
        contentType = "HTML";
        content = "$users"
    }
    attachments = @{
        "@@odata.type" = "#microsoft.graph.fileAttachment"
        name = "usersOwaEnabled.csv"
        contentType = "text/plain"
        ContentBytes = $base64Bytes
    }
}

Send-MgUserMail -UserId $from -BodyParameter @{ Message = $Message}`
 
[AB#8840](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8840)

**Comment by maisarissi** [comment]
Hi @montereyharris .

If I'm getting this correctly, we have this scenario covered in the docs: https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=powershell#request-2

Please, feel free to reopen if you are still not able to send email with attachments.
