### ISSUE TITLE
Generate valid help URL.

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#61]
Related to #369  
[AB#7428](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7428)

**Comment by darrelmiller** [comment]
Create autogenerated Help documentation here https://docs.microsoft.com/en-us/powershell/module/

**Comment by finsharp** [comment]
Related to #369
