### ISSUE TITLE
Feature Request: Device Management Configuration Settings Endpoint

### ISSUE THREAD

**Issue by dgitw** [microsoftgraph/msgraph-sdk-powershell#612]
Might be a bit premature here (is it officially published yet?), but it would be great to incorporate the [Device Management Configuration Settings](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta) and [Device Management Configuration Setting Definition](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta) endpoints into the Device Management module. 
[AB#8877](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8877)

**Comment by ddyett** [comment]
probably should just work but we'll check it's generated when published.

**Comment by peombwa** [comment]
These are missing in the OpenAPI document that we use to generate the SDK. I've opened a corresponding issue for the appropriate team to fix. This can be tracked here https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/509.
