### ISSUE TITLE
Connect-Graph : AADSTS50196: The server terminated an operation because it encountered a loop while processing a request.

### ISSUE THREAD

**Issue by rimroot** [microsoftgraph/msgraph-sdk-powershell#62]
Hi,
when running Connect-Graph I am getting an error:

Connect-Graph : AADSTS50196: The server terminated an operation because it encountered a loop while processing a request

I am using proxy

```
[system.net.webrequest]::defaultwebproxy = new-object system.net.webproxy('http://proxy.fqdn.com:8080')
[system.net.webrequest]::defaultwebproxy.credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
[system.net.webrequest]::defaultwebproxy.BypassProxyOnLocal = $true
```

**Comment by pminnebach** [comment]
I also have this problem when using ISE. But it works normally in the regular shell.

**Comment by rimroot** [comment]
> I also have this problem when using ISE. But it works normally in the regular shell.

It works with regular shell. Thanks.

I think it should be resolved for ISE, or at least properly documented.

**Comment by peombwa** [comment]
This is probable related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/82
