### ISSUE TITLE
Object Not Found in Store When Running Get-MgUserMailFolder

### ISSUE THREAD

**Issue by iperry-indigex** [microsoftgraph/msgraph-sdk-powershell#622]
Running Powershell 7.1.3, see example below.

```
PS C:\Users\iperry> Connect-MgGraph -Scopes "User.Read.All","Mail.Read","MailboxSettings.Read"
Welcome To Microsoft Graph!
PS C:\Users\iperry> $Members = Get-MgUser -All | Where-Object {$_.UserPrincipalName -NotLike "*#*"}
PS C:\Users\iperry> Get-MgUserMailFolder -UserId $Members[4].Id
Get-MgUserMailFolder_List: The specified object was not found in the store., The process failed to get the correct properties.
```

I've attempted `Connect-MgGraph -ForceRefresh`, as well as `Disconnect-MgGraph; Connect-MgGraph`. I've also verified that the user is a legitimate user. Suggestions? 
[AB#8987](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8987)

**Comment by peombwa** [comment]
This is a service issue. Could you try the following?
- From the [docs](https://docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=http), you can only get the mailbox folder collection of the signed-in user when in delegated mode. To get the mailbox folder of another user, you will need to authenticate in app-only mode via `Connect-MgGraph -ClientId $env:ClientId -TenantId $TenantId -CertificateThumbprint $CertThumbprint`. 
- Was the user account created recently? If so, you may need to wait for 15 minutes before making the call.

**Comment by iperry-indigex** [comment]
That (The app-only mode) seems to have been it, thank you.
