### ISSUE TITLE
Get-MGGroupEvent Access is denied

### ISSUE THREAD

**Issue by axc-msaner** [microsoftgraph/msgraph-sdk-powershell#623]
I'm attempting to list events in a group calendar with Get-MGGroupEvent

My Application connects successfully. I can lookup the group by ID using Get-MgGroup -Group $GroupID

However when I simply try Get-MgGroupEvent -Group $Group I get a response of "get-MgGroupEvent : Access is denied. Check credentials and try again."

The Application has Group.Read.All and User.Read.All Permissions. 
[AB#9011](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9011)

**Comment by peombwa** [comment]
@axc-msaner, are you authenticating to the SDK in app-only mode (using a certificate)? If so, please note that getting a group's events in only supported in delegated mode (`Connect-MgGraph -Scopes "Group.Read.All"`), see https://docs.microsoft.com/en-us/graph/api/group-list-events?view=graph-rest-1.0&tabs=http#permissions and https://docs.microsoft.com/en-us/graph/known-issues#permissions-for-groups-and-microsoft-teams.

If you are using delegated mode, ensure that the logged in user is a member of the group you are trying get its events. You can use either `Get-MgUserMemberOf -UserId $UserId | select Id, AdditionalProperties` or `Get-MgGroupMember -GroupId $GroupId | select id, AdditionalProperties` to do this.

**Comment by axc-msaner** [comment]
I am using app-only mode which would be my problem. The whole point of this is to write a script to read events off an on-call calendar and update permissions in an on prem AD instance.

Since connecting via delegated mode requires logging in through a web instance is there a way to handle that connection through an automated script with not user interaction? Also it appears Group.Read.All requires Admin permissions so I can't even read calendar events on a calendar I have permissions to without admin access which would also be a problem to get with an automated script.

It's sounding like Graph may not work for what I'm trying to do. Are there other APIs that would?

**Comment by peombwa** [comment]
This is a limitation of the service. At the moment, only user permissions are supported. I'd recommend you open a feature request [here](https://developer.microsoft.com/en-us/graph/support) for the service team to support this scenario.

**Comment by peombwa** [comment]
Closing as not actionable by the SDK.
