### ISSUE TITLE
Get-MgInformationProtectionSensitivityLabel Broken

### ISSUE THREAD

**Issue by joerodgers** [microsoftgraph/msgraph-sdk-powershell#629]
PS C:\Users\username> Get-MgInformationProtectionSensitivityLabel
Get-MgInformationProtectionSensitivityLabel : {"Message":"No HTTP resource was found that matches the request URI
'https://wus.prod.dataclassification.office.com/informationProtection/sensitivityLabels'.","MessageDetail":"No type was found that matches the controller named 'informationProtection'."}
At line:1 char:1
+ Get-MgInformationProtectionSensitivityLabel
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgInformati...ivityLabel_List], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgInformationProtectionSensitivityLabel_List 
[AB#9052](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9052)

**Comment by peombwa** [comment]
Thanks for surfacing this. We shouldn't be generating this command since it is not documented anywhere and returns 404.
