### ISSUE TITLE
Most of function is responding with error that doesn't exist, but is on listed commands

### ISSUE THREAD

**Issue by mimachniak** [microsoftgraph/msgraph-sdk-powershell#637]
Hi team I was trying to use module for Intune config, but most of functions end with error that don't exist. But when I look on commands, fuctions are listed and TAB give them as a suggested
![MSGarph](https://user-images.githubusercontent.com/40869985/115768052-1363af80-a3aa-11eb-943d-e45118127a7d.PNG)
 
[AB#9135](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9135)

**Comment by peombwa** [comment]
@mimachniak This happens when you haven't selected beta profile. By default, the SDK loads Microsoft Graph v1.0 commands. You can change this by using `Select-MgProfile beta`, see https://docs.microsoft.com/en-us/graph/powershell/get-started?view=graph-rest-1.0#api-version.

**Comment by mimachniak** [comment]
Yes is working on beta, thx :)
