### ISSUE TITLE
Connect-graph times out "Device Code terminal timed-out after 120 seconds"

### ISSUE THREAD

**Issue by avku** [microsoftgraph/msgraph-sdk-powershell#640]
Connect-graph times out  with error "Device Code terminal timed-out after 120 seconds" 
[AB#9151](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9151)

**Comment by peombwa** [comment]
@avku Are you using the command in Windows PowerShell ISE? If so, see our known issue sections https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues. I'd recommend you use VS Code with [PowerShell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell).

The timeout can also happen if you haven't copied and signed-in to the device login URL using the device code in more than 2 minutes.

**Comment by avku** [comment]
Running the command in PowerShell worked fine, thank you for sharing the details. Will close this thread :) !!
