### ISSUE TITLE
PowerShell to get latest updates

### ISSUE THREAD

**Issue by ToddKlindt** [microsoftgraph/msgraph-sdk-powershell#65]
If you installed the module when it was first released, like I did, you can use this PowerShell to get the latest version of the modules:

```
Set-PSRepository -Name GraphPowerShell -InstallationPolicy Trusted
Get-InstalledModule -Name "*graph*" | foreach { $b = (find-module $_.name).version ; if ($b -ne $_.version) { Write-host "Updating $($_.name) from $($_.version) to $b" } ; Update-Module -Name $_.name }
```

tk

**Comment by michevnew** [comment]
A simple Update-Module Microsoft.Graph.Beta should do, as it lists all the others as required. Or:

Install-module Microsoft.Graph.Beta -Repository GraphPowerShell -Force

**Comment by ToddKlindt** [comment]
> A simple Update-Module Microsoft.Graph.Beta should do, as it lists all the others as required. Or:
> 
> Install-module Microsoft.Graph.Beta -Repository GraphPowerShell -Force

That does look easier. I'll give that a shot when the next update comes out.

**Comment by BrianTJackett** [comment]
I used the install-module approach @michevnew mentioned and it works as expected.
