### ISSUE TITLE
Include all identityGovernance.* navigation properties

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#653]
Identity.Governance module is currently missing the following navigation properties in its module mapping:
- identityGovernance.termsOfUseContainer
- identityGovernance.appConsentApprovalRoute
- identityGovernance.accessReviewSet 
[AB#9289](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9289)

**Comment by markwahl-msft** [comment]
Might be related to #680

**Comment by peombwa** [comment]
Closed by #680
