### ISSUE TITLE
Get-MgApplicationOwnerByRef doesn't return owner

### ISSUE THREAD

**Issue by erwinkramer** [microsoftgraph/msgraph-sdk-powershell#658]
Using the latest stable release and calling:
`Get-MgApplicationOwnerByRef -ApplicationId "90c732ce-9a36-4d77-bf43-c2683cbf5773"` doesn't return an owner, it returns an empty, yet successful, response. I double checked if the AAD App contains an owner (type Member, a user). 

Also, shouldn't it be called **Id** instead of **ApplicationId**? Because it requires the object ID of the Azure AD Object, and not the Application (client) ID. If you try the Application ID it returns a _does not exist_ error. 
[AB#9382](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9382)

**Comment by peombwa** [comment]
As per the [docs](https://docs.microsoft.com/en-us/graph/api/application-list-owners?view=graph-rest-1.0&tabs=http), you should be using `Get-MgApplicationOwner` to list application owners. This returns a [directory object](https://docs.microsoft.com/en-us/graph/api/resources/directoryobject?view=graph-rest-1.0#properties). The command can be used like this:
``` powershell
Get-MgApplicationOwner -ApplicationId $AppId | ForEach-Object { 
    $_.Id, #Id of the owner
    $_.AdditionalProperties #Additonal properties of the owner e.g. displayName
}
```

Also, `$ref` is currently not supported for Gets, see https://docs.microsoft.com/en-us/graph/known-issues#query-parameter-limitations.

On the applicationId parameter, we plan to alias it `Id` to avoid breaking existing scripts. See my comment here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/593#issuecomment-808493653.

**Comment by erwinkramer** [comment]
Thanks for the answer. 

Did Get-MgApplicationOwner just got added though? Yesterday I didn't see it in the latest stable package when browsing all powershell functions in my shell. Maybe it's just me...
