### ISSUE TITLE
New-MgApplicationOwnerByRef throws: A 'StartObject' node was expected

### ISSUE THREAD

**Issue by erwinkramer** [microsoftgraph/msgraph-sdk-powershell#659]
Using the latest stable release. 

Can't seem to get **New-MgApplicationOwnerByRef** working, I've tried a few solutions but this what i think should be working: 

 ```
$body = @{
            "UserId" = $user.Id
        }
       
 New-MgApplicationOwnerByRef -ApplicationId $adApp.Id -BodyParameter $body
```

Which returns the following error:

```
New-MgApplicationOwnerByRef : An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.
At somefile.ps1:359 char:9
+         New-MgApplicationOwnerByRef -ApplicationId $adApp.Id -BodyPar ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ApplicationId...ionJsonSchema }:<>f__AnonymousType0`2) [New-MgApplicationOwnerByRef_Create1], RestException`1
    + FullyQualifiedErrorId : Request_BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgApplicationOwnerByRef_Create1
``` 
[AB#9383](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9383)

**Comment by peombwa** [comment]
You'll need to explicitly provide the `@odata.id` to the body parameter as shown in the [docs](https://docs.microsoft.com/en-us/graph/api/application-post-owners?view=graph-rest-1.0&tabs=http#request). This can be done in PowerShell:
``` powershell
$Body = @{ "@odata.id" = "htps://graph.microsoft.com/v1.0/directoryObjects/$UserId" }
New-MgApplicationOwnerByRef -ApplicationId $AppId -BodyParameter $Body
```

We may also need to provide a simplified parameter set of this command that just accepts a `directoryObjectId` and builds the `@odata.Id` behind the scene. Something like this:
``` powershell
New-MgApplicationOwnerByRef -DirectoryObjectId $UserId
```

**Comment by peombwa** [comment]
All `$ref` (`*ByRef`) commands now support `-ODataId`. In v2, `-ODataId` is [required](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1967) for `POST`, `PATCH`, and `PUT`. See https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.applications/new-mgapplicationownerbyref?view=graph-powershell-1.0,
