### ISSUE TITLE
Missing Remove-* functions on various owner objects.

### ISSUE THREAD

**Issue by erwinkramer** [microsoftgraph/msgraph-sdk-powershell#660]
Call : `Get-Command -Module Microsoft.Graph* *owner*`

The following objects have a **New** function, but don't seem to have a **Remove** function:

```
Function        New-MgApplicationOwnerByRef                        1.5.0      Microsoft.Graph.Applications
Function        New-MgDeviceManagementAndroidDeviceOwnerEnrollm... 1.5.0      Microsoft.Graph.DeviceManagement.Enrolment
Function        New-MgDeviceManagementAndroidDeviceOwnerEnrollm... 1.5.0      Microsoft.Graph.DeviceManagement.Actions
Function        New-MgDeviceRegisteredOwnerByRef                   1.5.0      Microsoft.Graph.Identity.DirectoryManagement
Function        New-MgGroupOwnerByRef                              1.5.0      Microsoft.Graph.Groups
Function        New-MgServicePrincipalOwnerByRef                   1.5.0      Microsoft.Graph.Applications
Function        New-MgTeamOwnerByRef
```

They are included in the Graph API, for instance, the delete method for **MgApplicationOwnerByRef**: https://docs.microsoft.com/en-us/graph/api/application-delete-owners?view=graph-rest-1.0&tabs=http 
[AB#9384](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9384)

**Comment by peombwa** [comment]
This is missing from the OpenAPI document that the SDK is generated from. I've opened an issue for the appropriate team to fix this here https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/567.

As a workaround, you could use `Invoke-MgGraphRequest` like this to remove an application owner like this.
``` powershell
Invoke-GraphRequest -Method 'Delete' -Uri "https://graph.microsoft.com/v1.0/applications/$appId/owners/$ownerId/`$ref"
```

**Comment by erwinkramer** [comment]
Thanks. 

Also it's not just the ref types, I think it's missing these as well: 
- Remove-mgApplicationOwner
- Remove-mgServicePrincipalOwner

**Comment by kaiaschulz** [comment]
Hey @peombwa ,
you marked this as resolved.
Unfortunately, this is still not available within the following version:
```
1.9.2                Microsoft.Graph.Applications
1.9.2                Microsoft.Graph.Authentication
```

In the meantime, I am trying to use [your mentioned workaround](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/660#issuecomment-840134839).

**Comment by kaiaschulz** [comment]
Additionally, the links within the [mapping table](https://docs.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-beta) are somehow available (404) or have a wrong linking:

### Not available (404):
```
<td>Connect-AzureAD</td>
  <td><a href="/en-us/powershell/module/microsoft.graph.authentication/connect-mggraph?view=graph-powershell-1.0&amp;preserve-view=true" data-linktype="absolute-path">Connect-MgGraph</a></td>

  <td>Disconnect-AzureAD</td>
  <td><a href="/en-us/powershell/module/microsoft.graph.authentication/disconnect-mggraph?view=graph-powershell-1.0&amp;preserve-view=true" data-linktype="absolute-path">Disconnect-MgGraph</a></td>
```

The documentation for the module `microsoft.graph.authentication` doesn't exist:
`https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.authentication/connect-mggraph?view=graph-powershell-1.0&preserve-view=true`

### Wrong linking (404):
```
<td>Add-AzureADApplicationOwner</td>
<td><a href="/en-us/powershell/module/microsoft.graph.applications/new-mgapplicationownerbyref.md?view=graph-powershell-1.0&amp;preserve-view=true" data-linktype="absolute-path">New-MgApplicationOwnerByRef.md</a></td>
```
The `.md` is the problem within the link. The correct link would be `https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.applications/new-mgapplicationownerbyref?view=graph-powershell-1.0&preserve-view=true`

**Comment by maisarissi** [comment]
Hi @kaiaschulz .

You are right, the issue was not resolved. A fix was deployed back in August, but it seems like we are still missing "delete operations" in the OpenAPI document.

So, I've raised a [new issue](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/888) and I'm engaging with that team to get this fixed as soon as possible.
