### ISSUE TITLE
Updating Web.HomePageUrl is slow on Update-MgApplication

### ISSUE THREAD

**Issue by erwinkramer** [microsoftgraph/msgraph-sdk-powershell#664]
Updating a few paramters on `Update-MgApplication` goes pretty quick (around 20ms). 
```
 $mgApplicationParams = @{
        "DisplayName"    = $appName
        "ApplicationId"  = $adApp.Value.Id
        "IdentifierUris" = $appUri
        "Web"            = @{
            "RedirectUris"          = $replyUrlsWeb
            "ImplicitGrantSettings" = @{
                "EnableIdTokenIssuance"     = $allowImplicitOAuthIdTokens
                "EnableAccessTokenIssuance" = $allowImplicitOAuthAccessTokens
            }
        }
    }
 Update-MgApplication @mgApplicationParams

```

If  I add `HomePageUrl` to the object, it suddenly takes almost 2 seconds:

```
 $mgApplicationParams = @{
        "DisplayName"    = $appName
        "ApplicationId"  = $adApp.Value.Id
        "IdentifierUris" = $appUri
        "Web"            = @{
            "HomePageUrl"           = $homePage
            "RedirectUris"          = $replyUrlsWeb
            "ImplicitGrantSettings" = @{
                "EnableIdTokenIssuance"     = $allowImplicitOAuthIdTokens
                "EnableAccessTokenIssuance" = $allowImplicitOAuthAccessTokens
            }
        }
    }
 Update-MgApplication @mgApplicationParams

```

I also noticed that it doesn't like `$null` values, not even as a value to a single input paramter, which could be very convenient to use if you're just trying to update provided values. Is that something that could be supported? The `AzureAD` module does support this.   
[AB#9473](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9473)

**Comment by peombwa** [comment]
Thank you for your question about the Microsoft Graph.

As this is a service issue, I'd recommend you open a question/ticket at https://developer.microsoft.com/graph/support for the service owners to investigate. This repo is for issues directly caused by the SDK.
