### ISSUE TITLE
Validate scopes and better error handling

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/msgraph-sdk-powershell#67]
So this one is on me, but can we have proper error messages and some validation on the Scopes parameter? Here's what happens if I mistype the scope level (Mail.Read.All instead of Mail.Read):

![image](https://user-images.githubusercontent.com/38553333/70727047-ac3ee100-1d07-11ea-8c44-3f1daf10e87b.png)

Of course if I remove it or fix the typo it works fine.

Better error handling throughout the module is needed IMO...

**Comment by darrelmiller** [comment]
MSAL appears to be reporting an incorrect error message.  To followup with MSAL team.

**Comment by peombwa** [comment]
@darrelmiller [MSAL v4.8.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.8.0). fixed the error message that's returned when an invalid scope is present.

The new error message is more clear on the cause of the error: 
```
AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'Invalid.Scope User.Read offline_access profile openid' does not exist.
Trace ID: <GUID>
Correlation ID: <GUID>
Timestamp: 2020-01-21 22:56:11Z
```
I'll update the auth module to use the latest version of MSAL.

**Comment by darrelmiller** [comment]
Updated MSAL provides better error reporting.  Next release will include these fixes.
