### ISSUE TITLE
Cannot use -Filter with Get-MgDirectoryRole

### ISSUE THREAD

**Issue by Dragonsong3k** [microsoftgraph/msgraph-sdk-powershell#674]
I am trying to run 

`Get-MgDirectoryRoleMember -Filter "DisplayName eq 'Global Administrator'"`

But it seems DirectoryRoleID is required. Which kind of defeats the purpose of using -Filter.

```
Get-MgDirectoryRoleMember -Filter "DisplayName eq 'Global Administrator'"

cmdlet Get-MgDirectoryRoleMember at command pipeline position 1
Supply values for the following parameters:
DirectoryRoleId:
``` 
[AB#9599](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9599)

**Comment by peombwa** [comment]
@Dragonsong3k Was your intention to filter directory roles with `Get-MgDirectoryRole -Filter`? If so, then this works in 1.5.0:
![image](https://user-images.githubusercontent.com/7061532/119736268-4fb77f00-be32-11eb-86aa-599cb513ae94.png)

**Comment by Dragonsong3k** [comment]
Thanks. Derf. I was trying to get a list members in the Global Administrator Role but I used the wrong command. Thanks for pointing that out. LOL
