### ISSUE TITLE
open Unable to authenticate using Connect-MgGraph with certificate on Windows Server or Azure HybridWoker error is  "certificate was not found or has expired."

### ISSUE THREAD

**Issue by rajeshnaik2020** [microsoftgraph/msgraph-sdk-powershell#675]
I am Unable to authenticate to Azure using Connect-MgGraph with a self-signed certificate on Windows Server or Azure HybridWoker. It works fine on machine once you login using windows user credential. But if you want to automate it using Azure automation, I get the error "**XXXXX certificate was not found or has expired.**" I don't see the same issue with Connect-AzAccount or Connect-AzureAD. It seems that Connect-MgGraph looks the certificate only in the user store and not it in Local machine store. 
[AB#9605](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9605)

**Comment by peombwa** [comment]
@rajeshnaik2020 `Connect-MgGraph` looks for certificates only in the user store, see https://docs.microsoft.com/en-us/graph/powershell/app-only?view=graph-rest-1.0&tabs=powershell#certificate.  You can use `-Certificate` parameter to load your self-signed certificate from any path/store like this:
``` powershell
# Load from local machine store.
$cert = Get-ChildItem Cert:\LocalMachine\My\$CertThumbprint
Connect-Graph -Certificate $cert -TenantId $TenantId -ClientId $ClientId

# Load from path.
$password= "SomePassword"
$passwordSecure = ConvertTo-SecureString -AsPlainText -Force $password

$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2("C:\Certificates\mycert.pfx", $passwordSecure)
Connect-Graph -Certificate $cert -TenantId $TenantId -ClientId $ClientId
```

**Comment by peombwa** [comment]
Closing as resolved as per offline sync with the customer.

**Comment by rajeshnaik2020** [comment]
> ```powershell
> # Load from local machine store.
> $cert = Get-ChildItem Cert:\LocalMachine\My\$CertThumbprint
> Connect-Graph -Certificate $cert -TenantId $TenantId -ClientId $ClientId
> 
> # Load from path.
> $password= "SomePassword"
> $passwordSecure = ConvertTo-SecureString -AsPlainText -Force $password
> 
> $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2("C:\Certificates\mycert.pfx", $passwordSecure)
> Connect-Graph -Certificate $cert -TenantId $TenantId -ClientId $ClientId
> ```

Thanks that worked.
