### ISSUE TITLE
Remove "Beta" from the module names, in favor of semver in the module manifest, please

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#69]
Why are you using "Beta" in the module names? That's unnecessary, and you're just pushing work on users who try the pre-release versions by forcing them to change the module names later if they build any tooling using a pre-release.

Instead, drop "Beta" from the names (it adds no value in modern versions of PowerShell), and add a `PSData.Prerelease` value to your manifest that identifies the module prerelease version. PowerShell Gallery will then take care of the rest, only allowing users to find/install the module if they do so with the `-AllowPrerelease` parameter.

For a good example, of this, have a look at version 5 of the `Pester` module, which is currently release `5.0.0-alpha4`, as can be seen by invoking `Find-Module Pester -AllowPrerelease` in PowerShell.

**Comment by darrelmiller** [comment]
Beta is not an indication of the release state of the modules.  It is a reflection of the API that it calls.  Microsoft Graph has a V1.0 API and a Beta API.  These are effectively two distinct APIs and currently we are only targeting the Beta Microsoft Graph API.  The Beta API is a superset of the Microsoft Graph V1.0 API.

The AutoREST PowerShell has a mechanism that allows different API versions to be targeted with a single PowerShell module.  We are investigating the possibility of using that mechanism to switch between the different API versions.  This version is unrelated to the Prerelease status of a PowerShell module.

Additionally, we will not be able to use the "prerelease" portion of a semver version when we publish to PowerShell Gallery as there is an open issue that PowerShell Gallery doesn't handle pre-release modules that point to other pre-release modules.  We have worked with the PowerShell team to find a resolution to this and for the moment we will use the 0.x.x version number to indicate the "prerelease" status of our modules.

**Comment by darrelmiller** [comment]
We have now removed the Beta from the name in the PowerShell modules that are on PowerShell Gallery.  However, the modules are currently still targeting the Beta API.  The modules will remain with version 0.x.x until they are out of preview.  By that time there will be a configuration setting that will allow you to switch between targeting the beta API and V1 API.
