### ISSUE TITLE
Question: Using Connect-MgGraph to authenticate using an existing app registration and Delegated permissions

### ISSUE THREAD

**Issue by Zerg00s** [microsoftgraph/msgraph-sdk-powershell#691]
Is it possible to authenticate via `Connect-MgGraph` using a specific App ID and delegated permissions

When I am using the following commandlet, I am forced to use an unverified "Microsoft Graph PowerShell" app.

```
Connect-MgGraph -Scopes "User.Read.All"
```

![image](https://user-images.githubusercontent.com/2797648/121430966-ca11f400-c946-11eb-8f5d-cc7011624d7e.png)

Is there an alternative method of using the Connect-MgGraph commandlet where I can specify an App ID for delegated authentication?

I am looking for something like this:

```
Connect-MgGraph -ClientId 611ed52b-21af-4af1-ba14-b2b3a2c19646 -Scopes "User.Read.All"
```

Any help will be greatly appreciated:
 
[AB#9834](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9834)

**Comment by georgend** [comment]
We do support supplying the following parameters. 
`Connect-MgGraph -TenantId <tenantidentifier> -ClientId <clientidentifier> -Scopes "User.Read.All"`

Would this be satisfactory?

**Comment by Zerg00s** [comment]
Thank you, @georgend. THis is exactly what I was looking for.
