### ISSUE TITLE
Question: How to Assign Autopilot Deployment Profile to Group?

### ISSUE THREAD

**Issue by DaehyunSim** [microsoftgraph/msgraph-sdk-powershell#693]
I have created a new Autopilot profile using the **New-MgDeviceManagementWindowAutopilotDeploymentProfile** cmdlet and am trying to assign it to a group. I have tried using the **New-MgDeviceManagementWindowAutopilotDeploymentProfileAssignment** cmdlet, however am having issues with the -Target parameter. 
Is this the correct way to assign my profile to a group? If so, are there any examples I can look at for creating the _DeviceAndAppManagementAssignmentFilter_ necessary for the -Target parameter?

I was able to successfully do something similar using the **New-DeviceAndAppManagementAssignmentTargetObject** cmdlet from the old Microsoft.Graph.Intune PowerShell SDK 
[AB#9855](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9855)

**Comment by peombwa** [comment]
@DaehyunSim. I see how this can be a challenge to use. 

`-Target` is of type `deviceAndAppManagementAssignmentTarget`, which is an abstract type. This means that the API expects you to provide a concrete implementation of `deviceAndAppManagementAssignmentTarget` via an `@odata.type` when sending the request. The possible derived types of `deviceAndAppManagementAssignmentTarget` are:
- [allDevicesAssignmentTarget](https://docs.microsoft.com/en-us/graph/api/resources/intune-shared-alldevicesassignmenttarget?view=graph-rest-beta)
- [allLicensedUsersAssignmentTarget](https://docs.microsoft.com/en-us/graph/api/resources/intune-shared-alllicensedusersassignmenttarget?view=graph-rest-beta)
- [groupAssignmentTarget](https://docs.microsoft.com/en-us/graph/api/resources/intune-shared-groupassignmenttarget?view=graph-rest-beta)
- [groupAssignmentTarget](https://docs.microsoft.com/en-us/graph/api/resources/intune-shared-configurationmanagercollectionassignmenttarget?view=graph-rest-beta)
- [exclusionGroupAssignmentTarget](https://docs.microsoft.com/en-us/graph/api/resources/intune-shared-exclusiongroupassignmenttarget?view=graph-rest-beta)

In this case, your PowerShell script will be something like:
``` powershell
$Params = @{
    WindowsAutopilotDeploymentProfileId = "Id"
    Source   = "policySets"
    SourceId = "id"
    Target   = @{
        "@odata.type" = "microsoft.graph.allDevicesAssignmentTarget" # or any type that derives from deviceAndAppManagementAssignmentTarget.
        DeviceAndAppManagementAssignmentFilterId   = "id"
        DeviceAndAppManagementAssignmentFilterType = "include"
    }
}

New-MgDeviceManagementWindowAutopilotDeploymentProfileAssignment @Params
```

We will need to simplify this in the next iteration of the SDK. I'll keep this issue open to track this enhancement.

**Comment by peombwa** [comment]
Closing since the API reference example now show the OData type.
