### ISSUE TITLE
custom module Finally should not dereference ResponseMessage as it suppresses network exception

### ISSUE THREAD

**Issue by markwahl-msft** [microsoftgraph/msgraph-sdk-powershell#700]
Cmdlets are returning a surprising exception if there is a client-side network issue, that makes it difficult for a script to detect and recover from transitory network issues.

For background, it appears that the autorest.powershell generator method.ts will generate `try` and `finally` blocks similar to

``` cs
global::System.Net.Http.HttpResponseMessage _response = null;
try
{
...
    _response = await sender.SendAsync(request, eventListener);
...
}
finally
{
   // finally statements
  await eventListener.Signal(Microsoft.Graph.PowerShell.Runtime.Events.Finally, request, _response);
...
}
```

If the *sending* of the request fails, maybe the network is down and the endpoint is unreachable from the client, then an exception is generated within the `try` block.  In that  `finally` block , note that `_response`. a `HttpResponseMessage`, that is being passed to `eventListener.Signal()` will be null in this case where there is an exception being thrown. In several ...\custom\Module.cs there are `Finally()` methods, each which have calls to`new HttpMessageFormatter()`.  This ctor throws `ArgumentNullException` if the `responseMessage` parameter is null.  If a request cannot be sent, then this `ArgumentNullException` hides the actual network exception.  For example, after `Connect-MgGraph`, disconnect the network and you will get

```cmd
PS > Get-MgBusinessFlowTemplate
Get-MgBusinessFlowTemplate_List: Value cannot be null. (Parameter 'httpResponse')
```
rather than 
```cmd
PS > Get-MgBusinessFlowTemplate
Get-MgBusinessFlowTemplate_List: No such host is known. (graph.microsoft.com:443)
```

The ...\custom\Module.cs `Finally()` methods should have added to them

```cs
                if (eventData.ResponseMessage == null) {
                    return;
                }
```
 
[AB#9893](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9893)

**Comment by georgend** [comment]
@markwahl-msft Thank you for reporting this, linked PR integrates your suggestion.
