### ISSUE TITLE
incomplete results returned as network errors occurring during paging are not written

### ISSUE THREAD

**Issue by markwahl-msft** [microsoftgraph/msgraph-sdk-powershell#702]
In a script that uses a cmdlet to list a large result set, such as `try { $res = Get-Mg... -All -ErrorAction Stop} catch { ... }` the cmdlet is expected under normal circumstances to page through and return the complete result set, and under abnormal circumstances such as an Internet outage, report a terminating or non-terminating error.  The caller indicates with `ErrorAction Stop`  that it wants the PSh runtime to use the `catch` block for a non-terminating error.

If the network is up the whole time, this script works as expected and a complete result is returned.  And, if the network has gone down before the cmdlet starts processing, then an error is caught by the script, as expected.

However, if the network goes down in the middle of processing, after some calls have been made and partial results returned, but not before the last page has been returned, then no error is provided to the script, and incomplete results are returned.  For example, there might be 430 entries (5 pages of 100) in the Graph-based service, but if the network goes down partway through, $res.Count is 200 and no error is reported.

This can cause problems for client automation since there is no indication that there is an incomplete result set or what the cause might be, even with -Verbose -Debug present as well. 
 
[AB#9914](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9914)

**Comment by peombwa** [comment]
Thanks for bringing this to our attention. We will fix it in the next releases.

**Comment by markwahl-msft** [comment]
FYI also observed that if the service returns a service error (e.g., 500-series result code) for a GET of a page after the first, then this is not being returned (or included in the debug/verbose log).

**Comment by peombwa** [comment]
@markwahl-msft, an exception is always thrown whenever the network goes down and the request [times out (100 seconds)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-5.0#remarks). e.g., The script below captures a network error as expected, albeit suppressed.
``` powershell
$stopwatch = [System.Diagnostics.Stopwatch]::new()
try {
    Connect-MgGraph
    $stopwatch.Start()
    $messages = Get-MgUserMessage -UserId $env:App_User_Id -All -ErrorAction Stop
}
catch {
    $stopwatch.Stop()
    Write-Error "Something happened!!"
    Write-Host "Elapsed Time: $($stopwatch.Elapsed.TotalSeconds) seconds."
    $_.Exception
    $stopwatch.Reset()
}
```
![image](https://user-images.githubusercontent.com/7061532/123174014-55ee4a80-d434-11eb-84fc-792305710bc9.png)

The network error is indeed suppressed as noted [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/700) and will be fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/712.

Is there a specific command that's not throwing an exception when a network error occurs?

**Comment by markwahl-msft** [comment]
> Is there a specific command that's not throwing an exception when a network error occurs?
Yes, a list cmdlet that is paging.  When I used Get MgEntitlementManagement AccessPackageAssignment to list all assignments, with -ErrorAction Stop, and the service had 430 result objects to return.  In one case, the network connection went down after the second page and the service could not return the data for the third page. Then the cmdlet returned 200 result objects in the pipeline, and did not throw an exception.  With ErrorAction Stop the caller should have received an indication that this was not a complete result.  I also observed this behavior when the network was up but the Microsoft Graph endpoint returned a 500-series error on that third page, again only 200 (two pages) of data was returned and no indication to the caller that the results were incomplete.

**Comment by peombwa** [comment]
I'm still not able to repro this on my end, even with `Get-MgEntitlementManagementAccessPackageAssignment`. I'm testing a network connection drop by disconnecting from my wifi and waiting for the request to timeout (100 seconds):
``` powershell
@peter ➜ M $assignments =  $null
@peter ➜ M $assignments = Get-MgEntitlementManagementAccessPackageAssignment -All -ErrorAction Stop
Get-MgEntitlementManagementAccessPackageAssignment_List: C:\Users\peter\Documents\PowerShell\Modules\Microsoft.Graph.Identity.Governance\1.6.0\custom\Get-MgEntitlementManagementAccessPackageAssignment.ps1:159
Line |
 159 |      Microsoft.Graph.Identity.Governance.private\Get-MgEntitlementMana …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'httpResponse')

@peter ➜ M $assignments.count
0
@peter ➜ M $stopwatch = [System.Diagnostics.Stopwatch]::new()
@peter ➜ M try {
>>     Connect-MgGraph
>>     $stopwatch.Start()
>>     $assignments = $null
>>     $assignments = Get-MgEntitlementManagementAccessPackageAssignment -All -ErrorAction Stop
>> }
>> catch {
>>     $stopwatch.Stop()
>>     Write-Error "Something happened!!"
>>     Write-Host "Assignment count: $($assignments.count)."
>>     Write-Host "Elapsed Time: $($stopwatch.Elapsed.TotalSeconds) seconds."
>>     $_.Exception
>>     $stopwatch.Reset()
>> }
Welcome To Microsoft Graph!
Write-Error: Something happened!!
Assignment count: 0.
Elapsed Time: 105.4817364 seconds.

Message        : Value cannot be null. (Parameter 'httpResponse')
ParamName      : httpResponse
TargetSite     : Void .ctor(System.Net.Http.HttpResponseMessage)
StackTrace     :    at Microsoft.Graph.PowerShell.HttpMessageFormatter..ctor(HttpResponseMessage httpResponse)
                    at Microsoft.Graph.PowerShell.Module.Finally(String id, CancellationToken cancellationToken, Func`1
                 getEventData, Func`4 signal)
....
```

Are you able to repro this with v1.6.0? Also, can you please share your `$PSVersionTable`.

**Comment by peombwa** [comment]
Also, does this happen intermittently, or it constantly never throws an error when the network is down?
