### ISSUE TITLE
Microsoft Graph Threat Assessment - Any schedule for integration?

### ISSUE THREAD

**Issue by dodge1350-frp** [microsoftgraph/msgraph-sdk-powershell#708]
I was not able to find the threat assessment api for Microsoft Graph reflected here.  Is there a plan for this, or possibly I missed it?

https://docs.microsoft.com/en-us/graph/api/resources/threatassessment-api-overview?view=graph-rest-1.0 
[AB#9959](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9959)

**Comment by peombwa** [comment]
This is missing in the current SDK. We will add it under `Microsoft.Graph.Security` module in the next releases.
