### ISSUE TITLE
As the docs teams, we would like access to the source that generates the docs to manually update the cmdlet and parameter descriptions straight from the Microsoft Graph APIs.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#719]
The team working on automating this process is currently in the investigation stage and no indicative timeline to work with. I'm therefore requesting to have access to manually update this for completeness of the docs.

The fact that the docs are autogenerated emphasizes the need for human input to make them friendlier and more customer-centric.

Cc: @davidmu1  
[AB#10046](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10046)

**Comment by adamedx** [comment]
@mairissi , we need a way to customize the descriptions for commands. This is causing a regression from our previous AzureAD Documentation -- @msewaweru  can provide more detail.

**Comment by msewaweru** [comment]
There current cmdlet and parameter descriptions are incomplete and customers won't be successful with them as they are. There is also the parity issue with the Azure AD PowerShell cmdlets because there the descriptions have been good enough for the customers.
I would like to be able to:

- Manually update the cmdlet and parameter descriptions. Even when there is an automated process around fetching them from the Graph APIs, we will still need to add some human touch to it.
- Is it possible to have this done the same way we are doing the cmdlets examples? We were provided with a place to drop the examples for each cmdlet and later this is integrated into the source and it surfaces on docs. Can we have such a setup for the descriptions?

**Comment by darrelmiller** [comment]
The descriptions of the commands and parameters are in the API reference documentation.  Changing the documentation there, will also change it in the PowerShell documentation.

**Comment by msewaweru** [comment]
@darrelmiller, I don't think we are getting the command descriptions from the APIs and this has been reported to be something that needs to be resolved from the API doctor side. As an example, take a look at the descriptions in [PowerShell doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/get-mguser?view=graph-powershell-1.0) and [API ref](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http) for the Get-MgUser cmdlet.
For the parameters, I confirm that the descriptions are as in the API ref except for the Odata query parameters, some of which will need to be described better for the customer. E.g 
![image](https://user-images.githubusercontent.com/73849846/125931705-0f3572b8-73af-430b-9298-fec155516ce2.png)

**Comment by darrelmiller** [comment]
Yes. We have some content that is not yet being transferred through from the API Reference documentation to the PowerShell reference documentation. We are continuing to work on that.

-ExpandProperty is a standard PowerShell property, it is not the OData expand.  See details here https://devblogs.microsoft.com/powershell/select-expandproperty-propertyname/ 

Can we agree that the place to manually update the property descriptions and command descriptions are is in the API Reference documentation here (https://github.com/microsoftgraph/microsoft-graph-docs) and close this issue?

**Comment by msewaweru** [comment]
Thanks @darrelmiller. We can close this issue as we wait to have the tooling to transfer the info ready.

**Comment by mmacy** [comment]
@msewaweru Here's the issue in APIDoctor to follow that's blocking API ref ingestion:

https://github.com/OneDrive/apidoctor/issues/114
