### ISSUE TITLE
Use AutoREST Profile feature for switching between V1.0 and beta

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#72]

**Comment by dolauli** [comment]
Following steps are required
1. Generate profiles for your service - one for v1.0 and the other for beta
You may find some profile samples under https://github.com/Azure/azure-rest-api-specs/tree/master/profiles/definitions for azure-powershell. To generate profile, you may refer to the script https://github.com/Azure/azure-rest-api-specs/blob/master/scripts/latest-profile-generator.ts which is used to generate latest profiles based on swagger in the repo.
2. Refer to https://github.com/Azure/azure-powershell/blob/generation/src/Dns/readme.md and https://github.com/Azure/azure-powershell/blob/generation/src/readme.azure.md for a sample with two profiles
3. After the code is generated, you may find how to load a profile in the *.psm1 file.
4. You may need to implement a cmdlet to switch the profile.

**Comment by darrelmiller** [comment]
Open issue https://github.com/Azure/autorest.powershell/issues/587

**Comment by peombwa** [comment]
AB#4769
