### ISSUE TITLE
Sign in Data

### ISSUE THREAD

**Issue by scm7ak** [microsoftgraph/msgraph-sdk-powershell#720]
When using the Rest API to connect to the cloud, Sign in Data is available.

When using the Powershell SDK, Signin Data is always blank for a user, even though the context is switched to the beta endpoint.

The enterprise app for both connections are the same.

Any insight here? 
[AB#10048](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10048)

**Comment by peombwa** [comment]
@scm7ak, which REST API path/command are you using to get "sign in data"?

**Comment by scm7ak** [comment]
$user = get-mguser -id upn | select signinactivity

$user.signinactivity

The result shows two attributes that are empty. It uses the beta endpoint after having it switched using the mgprofile command

**Comment by peombwa** [comment]
I see. As per the [API reference docs](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta), you'll need to ensure you've met the following requirements to retrieve this property:
![image](https://user-images.githubusercontent.com/7061532/124194900-3384ae80-da7e-11eb-8efa-57179a1dd1a4.png)

These requirements can be fulfilled as such using the Microsoft Graph PowerShell SDK:
- Ensure you have an Azure AD Premium P1/P2 license.
- Consent to `AuditLog.Read.All` scope via `Connect-MgGraph -Scopes "AuditLog.Read.All"`.
- Explicitly `$Select` `SignInActivity` property via `-Property SignInActivity` parameter of `Get-MgUser`.

Your final script should be something like:
``` powershell
# Consent to the required permission.
Connect-MgGraph -Scopes "AuditLog.Read.All"

# $select Signinactivity.
Get-MgUser -UserId $UserId -Property Signinactivity, Id, DisplayName | Select -ExpandProperty SignInActivity

LastSignInDateTime   LastSignInRequestId
------------------   -------------------
6/29/2021 5:59:57 PM d228ff59-d2c2-405e-8162-1f11b9328111
```

**Comment by peombwa** [comment]
Closing as answered.
