### ISSUE TITLE
Surface surveys in Identity APIs under "Related Links" of PowerShell cmdlets

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-powershell#737]
Priority? | Graph Explorer Endpoint | PowerShell cmdlet | Survey Link
-- | -- | -- | --
  | /conditionalAccess/policies | Get-AzureADMSConditionalAccessPolicy | https://aka.ms/caapifeedback
  |   | New-AzureADMSConditionalAccessPolicy |  
  |   | Set-AzureADMSConditionalAccessPolicy |  
  |   | Remove-AzureADMSConditionalAccessPolicy |  
  | /conditionalAccess/namedLocations | Get-AzureADMSNamedLocationPolicy |  
  |   | New-AzureADMSNamedLocationPolicy |  
  |   | Set-AzureADMSNamedLocationPolicy |  
  |   | Remove-AzureADMSNamedLocationPolicy |  
  |   |   |  
Yes | /applications | Get-AzureADApplication | https://aka.ms/applicationsAPISurvey
  |   | New-AzureADApplication |  
  |   | Set-AzureADApplication |  
  |   | Remove-AzureADApplication |  
  |   |   |  
  | /servicePrincipals | Get-AzureADServicePrincipal | https://aka.ms/servicePrincipalAPISurvey
  |   | New-AzureADServicePrincipal |  
  |   | Set-AzureADServicePrincipal |  
  |   | Remove-AzureADServicePrincipal |  
  |   |   |  
  | /servicePrincipals/{id}/appRoleAssignments | Get-AzureADServiceAppRoleAssignment | https://aka.ms/appRoleAssignmentAPISurvey
  |   | New-AzureADServiceAppRoleAssignment |  
  |   | Remove-AzureADServiceAppRoleAssignment |  
  |   |   |  
  | /onPremisesPublishingProfiles/applicationProxy/connectors | Get-AzureADApplicationProxyConnector | https://aka.ms/msgraphaadsurveyconnectors
  |   |   |  
  | /onPremisesPublishingProfiles/applicationProxy/connectorgroups | Get-AzureADApplicationProxyConnectorGroup | https://aka.ms/msgraphaadsurveyconnectorgroups
  |   |   |  
Yes | /groups | Get-AzureADGroup | https://aka.ms/GroupsAPIFeedback
  |   | New-AzureADGroup |  
  |   | Add-AzureADGroupMember |  
  |   | Remove-AzureADGroupMember |  
  |   | Remove-AzureADGroup |  
  |   |   |  
Yes | /devices | Get-AzureADDevice | https://aka.ms/deviceAPIFeedback
  |   | Set-AzureADDevice |  
  |   | Remove-AzureADDevice |  
  |   |   |  
Yes | /users | Get-AzureADUser | https://aka.ms/UsersAPIFeedback
  |   | Get-AzureADUserThumbnailPhoto |  
  |   | New-AzureADUser |  
  |   | Remove-AzureADUser |  
  |   | Set-AzureADUser |  
  |   | Set-AzureADUserThumbnailPhoto |  
  |   | Revoke-AzureADUserAllRefreshToken |   
[AB#10134](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10134)

**Comment by peombwa** [comment]
Will be fixed by https://github.com/Azure/autorest.powershell/issues/805.
