### ISSUE TITLE
Get-MgDirectoryrole does not return all of the Azure AD roles.

### ISSUE THREAD

**Issue by MatthewJDavis** [microsoftgraph/msgraph-sdk-powershell#739]
Graph module version: 1.6
PSVersion: 7.1.3
PSEdition: Core

Hello, 

Currently using the Get-MgDirectoryrole Cmdlet only returns 12 Azure AD directory roles.

![image](https://user-images.githubusercontent.com/10107936/124674351-89939080-de88-11eb-800d-595dbb5baa4c.png)

There are more roles as can be seen on the [official docs](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference) and it would be good to be able to return all of the roles.

Adding the -All parameter produces the following error:

`Get-MgDirectoryRole_List: This resource does not support custom page sizes. Please retry without a page size argument.`

Thanks,

Matt 
[AB#10139](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10139)

**Comment by peombwa** [comment]
According to the [API reference docs](https://docs.microsoft.com/en-us/graph/api/directoryrole-list?view=graph-rest-1.0&tabs=http), 
> When assigning a role using the Azure portal, the role activation step is implicitly done on the admin's behalf. To get the full list of roles that are available in Azure AD, use List directoryRoleTemplates.

you should be using `Get-MgDirectoryRoleTemplate | select DisplayName, Id | Sort-Object DisplayName` to get a list of roles that are available in Azure AD.

**Comment by MatthewJDavis** [comment]
Thank you for the explanation. 

I've created a [PR](https://github.com/microsoftgraph/microsoft-graph-docs/pull/13414) for the docs to include the information in the beta endpoint documentation.
