### ISSUE TITLE
Get-MgAccessReview Disappears

### ISSUE THREAD

**Issue by rpstester** [microsoftgraph/msgraph-sdk-powershell#742]
Hello. Whenever I first open PowerShell, already having installing the full Microsoft.Graph module, if I use get-command *accessreview*, then I see ones like Get-MgAccessReview, Stop-MgAccessReview, etc.
However, when I try to call the cmdlet, or import its module, then it gives me the message: The term 'Get-MgAccessReview' is not recognized as a name of a cmdlet, function...
Then when I rerun get-command, then none of these cmdlets are visible.  
Am I missing some trick to correctly running Get/New/Remove/Stop/Update-MgAccessReview, or is this a bug?
I have tried both WinPoSh 5.1 and PoSh 7.1.  
Thanks!
 
[AB#10153](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10153)

**Comment by peombwa** [comment]
@rpstester, `Get-MgAccessReview` is only available in beta, and you'll need to use `Select-MgProfile beta` to load beta commands. By default, the SDK uses the Microsoft Graph REST API v1.0, see https://docs.microsoft.com/en-us/graph/powershell/get-started?view=graph-rest-beta#api-version

**Comment by rpstester** [comment]
OK, using Beta worked for me. Thanks!
