### ISSUE TITLE
Get-MgDirectorySetting has filter parameters but cannot be filtered and does not have the eventualconsistency parameter

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#743]
```
Get-MgDirectorySetting -filter "DisplayName eq 'Group.Unified'"

Get-MgDirectorySetting_List: Filtered searches against this resource are not supported.
```

```
Get-MgDirectorySetting -search 'notrealproperty:notrealresult'


Id                                   DisplayName             TemplateId
--                                   -----------             ----------
517318d7-5173-4250-8fb3-295c7d9e3e4c Consent Policy Settings dffd5d46-495d-40a9-8e21-954ff55e1… 
``` 
[AB#10159](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10159)

**Comment by peombwa** [comment]
ConsistencyLevel is only supported by commands that return the following objects https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-advanced-queries-for-directory-objects-are-now-generally-available/. `Get-MgDirectorySetting` is expected not to have a ConsistencyLevel parameter.

The command having a -Filter parameter that is not supported by the workload is a known issue and will be resolved by the workload owners by adding an annotation to the [metadata](http://graph.microsoft.com/beta/$metadata) from which this SDK is generated.

The broken `-Search` issue is a service bug and not an SDK issue. I'd recommend you either:
- Use the "feedback" section in the [documentation page of the API](https://docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&tabs=http) to create an issue in the docs repo which will get routed to the right service team.
- Create a [support](https://developer.microsoft.com/en-us/graph/support) ticket.
- Ask your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/topics/single/128334.html).

**Comment by peombwa** [comment]
Transferred the issue to the metadata repro - https://github.com/microsoftgraph/msgraph-metadata/issues/225. The metadata lacks the annotation needed to suppers `-Filter`.
