### ISSUE TITLE
Publish deprecated modules with a warning about their new location

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#744]
All the 0.9.1 modules that were deprecated need a 0.9.2 published with a warning when you import the module saying "THis module has been deprecated, the new module is Microsoft.Graph.XXX"

![image](https://user-images.githubusercontent.com/15258962/124985183-fa54bd00-dfee-11eb-9df5-2679e81310d3.png)

 
[AB#10160](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10160)

**Comment by peombwa** [comment]
Thanks for surfacing this @JustinGrote!!! We will add this to the deprecated modules.

**Comment by JustinGrote** [comment]
@peombwa thank you. Also the old packages should also just be delisted from the gallery, they will still be installable for those who have specified them as dependencies, but things like `find-command` won't show them anymore, which is how I got into this mess in the first place :)

**Comment by peombwa** [comment]
All old packages have now been unlisted (deprecated) from PSGallery and won't be available for install.
![image](https://user-images.githubusercontent.com/7061532/125364690-c7306780-e327-11eb-96db-3fa0f5a1b9a8.png)

**Comment by JustinGrote** [comment]
To be clear, they are still available to install (if you specify them explicitly), they just won't show up in searches.
