### ISSUE TITLE
Token is not persisting, being prompted on every command at BeforeCall step

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#746]
Browser: Edge
PS Version: 7.1.3
Graph Version: 1.6.0

https://user-images.githubusercontent.com/15258962/124997187-0a749880-dfff-11eb-9657-b756fbfcb0bf.mp4

Anything I can flush to troubleshoot? 
[AB#10165](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10165)

**Comment by peombwa** [comment]
@JustinGrote This can happen if you had installed the preview versions of the SDK on your machine. Use the following to reset your token cache:
- Use `Disconnect-MgGraph` to sign-out of the current session.
- Run `Remove-Item "$env:USERPROFILE\.graph" -Recurse -Force` to delete your token cache.
- Run `Connect-MgGraph` to reconstruct a clean token cache.

Chances are that your token cache is in an invalid state from the preview versions of the SDK.

**Comment by JustinGrote** [comment]
@peombwa wasn't aware of the graphcontext.json, that fixed it. Thanks!
