### ISSUE TITLE
Get-MgAuditLogSignIn -All Returns Blank AppDisplayName and ResourceDisplayName values

### ISSUE THREAD

**Issue by patrickkorger** [microsoftgraph/msgraph-sdk-powershell#757]
When running the command "Get-MgAuditLogSignIn -All", Microsoft Graph is pulling over 830k results, however, some data come with back AppDisplayName and ResourceDisplayName fields. However, if you filter the .csv you can see the AppDisplayName and\\or ResourceDisplayName entries with some 
![Get-MgAuditLogSignIn](https://user-images.githubusercontent.com/87391466/125511589-fa4c4c50-6c97-4b3c-b3c6-e8fe9bf5aa3a.png)
data for matching resourceId entries. 
[AB#10205](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10205)

**Comment by peombwa** [comment]
Could run `Get-MgAuditLogSignIn -All -Debug` with a `-Debug` to see if this is indeed the response from service. Alternatively, you can use fiddler to inspect the response from the service.

Also, the CSV you shared above shows blank AppDisplayName and ResourceDisplayName for the filtered appId which seems to suggest that this is indeed the response from the service.
