### ISSUE TITLE
Getting fields with Get-MgSiteListItem

### ISSUE THREAD

**Issue by maryha** [microsoftgraph/msgraph-sdk-powershell#764]
Perhaps I am doing something wrong, but I cannot seem to get any fields other than Id when getting list items from SharePoint.  I have a list with custom columns for Category, Description, and TeamLink, but when I run the following command, all I get back in the "fields" set of properties is "Id":

Get-MgSiteListItem -ListId $listId -SiteId $SiteId -ExpandProperty "fields(`$select=Title,Description,ID,Category)"

Get-MgSiteListItem -ListId $listId -SiteId $SiteId -ExpandProperty "fields" also only returns Id in the set of fields

![image](https://user-images.githubusercontent.com/7673459/125791184-9162338e-b285-47e0-8095-899fb624d54f.png)

 
[AB#10229](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10229)

**Comment by peombwa** [comment]
@maryha This because `fields` is defined as OpenType in the metadata (it can have any property). You should be able to get the properties in the `AdditionalProperties` property bag like this:
``` powershell

$items[0].fields.AdditionalProperties

Key                       Value
---                       -----
@odata.etag               "bc724093-7acc-4e3c-82ef-24e422e0aa2a,1"
ContentType               Item
Title                     Item
Modified                  2021-07-15T23:21:59Z
Created                   2021-07-15T23:21:59Z
AuthorLookupId            11
EditorLookupId            11
_UIVersionString          1.0
Attachments               False
Edit
LinkTitleNoMenu           Item
LinkTitle                 Item
ItemChildCount            0
FolderChildCount          0
```

**Comment by maryha** [comment]
Yes, that did work!! Thank you for the response :-).  Just need that documented somewhere
