### ISSUE TITLE
Version or build number in the openAPIDocs

### ISSUE THREAD

**Issue by haneef95** [microsoftgraph/msgraph-sdk-powershell#769]
Hi,

It would be good to get an additional line with the version of the Open API Specification (OAS) YAML/YML file, even as a comment, as the files do get regularly updated.

Potentially on Line 5 in the example below:
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/75bbe6a4f23935941ec228755e057e1285a2aff5/openApiDocs/v1.0/Users.yml#L2-L4

Thanks, 
[AB#10271](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10271)

**Comment by peombwa** [comment]
@haneef95, the OpenAPI documents in this repo is just a mirror of the [public metadata](https://graph.microsoft.com/v1.0/$metadata), but in OpenAPI. The metadata, which isn't versioned per release, is updated every week and is a mirror of the service. i.e., a metadata from last week may not work with this week's service release.
