### ISSUE TITLE
Get-MgUser does not get msExchExtensionCustomAttribute1 values

### ISSUE THREAD

**Issue by john-s-au** [microsoftgraph/msgraph-sdk-powershell#770]
Using Get-MgUser to get msExchExtensionCustomAttribute1 yields no result in the $user.AdditionProperties field
`$user = Get-MgUser -UserId <User> -Property extension_<guid>_msExchExtensionCustomAttribute1`

The value can be retrieved when querying Graph API using REST, so it is definitely populated
`https://graph.microsoft.com/v1.0/users/<user>?$select=extension_<guid>_msExchExtensionCustomAttribute1` 
[AB#10279](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10279)

**Comment by peombwa** [comment]
Directory extensions should be accessible via additionalProperties as shown below.
![image](https://user-images.githubusercontent.com/7061532/126535639-4fffa8cb-bc84-4e43-a53a-589c8dd5c682.png)

Which version of the SDK are you using? I tested this using the latest version (1.6).

Also, you can run `Get-MgUser -UserId <User> -Property extension_<guid>_msExchExtensionCustomAttribute1 -Debug` to see what request and response was received from the service.
