### ISSUE TITLE
CloudCommunication MSGraph Powershell

### ISSUE THREAD

**Issue by samljac** [microsoftgraph/msgraph-sdk-powershell#780]
i want to get all the callRecords with this cmd Get-MgCommunicationCallRecord but it requires a callRecord Id, where can i find the callRecord Id, which method can help me find it? 
[AB#10382](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10382)

**Comment by peombwa** [comment]
This is all defined here https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0&tabs=http. A call record id can be retrieved by:
> - Subscribing to change notifications to the /communications/callRecords endpoint.
> - Using the callChainId property of a call. The call record is available only after the associated call is completed.

**Comment by samljac** [comment]
you can get the call  id from the teams admin center > users>meetings&calls
