### ISSUE TITLE
 New-MgDeviceAppMgtMobileAppConfiguration not working

### ISSUE THREAD

**Issue by FAGschuricht** [microsoftgraph/msgraph-sdk-powershell#790]
Hi, 

I try to build iOS LOB app configurations with the Powershell SDK. I found the command "New-MgDeviceAppMgtMobileAppConfiguration" which sounds great. But I am not able to create any lines with it.  I looked it up in the Microsoft [Docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/new-mgdeviceappmgtmobileappconfiguration?view=graph-powershell-beta) and with "Get-Help New-MgDeviceAppMgtMobileAppConfiguration" but neither gave me the needed information. There aren´t  examples `Get-Help New-MgDeviceAppMgtMobileAppConfiguration -examples`

I would like to fill an variable called "ServerURL" with an URL. So I tried: 

`New-MgDeviceAppMgtMobileAppConfiguration -TargetedManagedAppConfigurationId "AppName" -BodyParameter "=@{"ServerURL"="https:/URL"}"`

The following error message is displayed: 
```
In Line:1
+ ... argetedManagedAppConfigurationId "AppName" -BodyParameter "=@{"ServerUR ...
+                                                             ~~~~~
+ CategoryInfo          : InvalidData: (:) [New-MgDeviceAppMgtMobileAppConfiguration], ParameterBinding 
ArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,New-MgDeviceAppMgtMobileAppConfiguration
```

So I looked up how to build hash tables in [Powershell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hash_tables?view=powershell-7.1).
But he does not take the hash table.

`=@{"ServerURL"="https://URL"}`
 

I tried different things but I am not able to create an app-config. Do you have any ideas.
This is my first github issue post, please tell me if you need further information.

Greetings Lucas

 
[AB#10434](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10434)

**Comment by peombwa** [comment]
Sorry for the delayed response.

The error message is accurate, `TargetedManagedAppConfigurationId` is defined as a parameter of `New-MgDeviceAppMgtMobileAppConfiguration`. See `Get-Help New-MgDeviceAppMgtMobileAppConfiguration`.

Which API are you trying to call? According to the API reference doc, only GET and LIST are supported; you cannot create a managedDeviceMobileConfiguration. See https://docs.microsoft.com/en-us/graph/api/resources/intune-apps-manageddevicemobileappconfiguration?view=graph-rest-beta. Please share a link from the API reference page of the API you are trying to use.
