### ISSUE TITLE
Cmdlets should support both flattened and nested objects as parameters

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#798]
Cmdlets should support both nested and flattened parameters. e.g.,
#### Flattened parameters (not supported)
``` powershell
New-MgApplication -WebRedirectUris = "MY_URI"
```

#### Nested parameters (currently supported)
``` powershell
New-MgApplication -Web @{ RedirectUris = "MY_URI" }
``` 
[AB#10467](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10467)

**Comment by sebastienlevert** [comment]
This seems like a big change and would require heavy changes on AutoREST and would also impact a lot the parameters we generate. Also, what does it mean for "sub" objects... I understand this could simplify the experience, but I feel we are getting into documentation hell. 

I would close this one as not planned.
