### ISSUE TITLE
Mail At least one recipient is not valid., Recipient 'xxx@ecgmc.com;yyy@ecgmc.com;zzz@ecgmc.com' is not resolved

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/msgraph-sdk-powershell#803]
I am using the sample from [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/A-Mail.ps1)
I need n number of Recipients So I tried the addresses separated by comma and ; But I get error: 
`At least one recipient is not valid., Recipient 'xxx@ecgmc.com;yyy@ecgmc.com;zzz@ecgmc.com' is not resolved.`
Is there another way to do it?

Thank you 
[AB#10523](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10523)

**Comment by peombwa** [comment]
@Ofer-Gal, you'll need to add each email address as an `emailAddress` object to `toRecipient` collection. See sample [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/Scripts/UsersAndGroups.ps1#L21-L54).

In this case, your call will be something like this:
``` powershell
$Message = @{
    subject      = "Yo"
    body         = @{
        content = "Here is my message"
    }
    toRecipients = @(
        @{
            emailAddress = @{
                address = "user1@example.com"
            }
        },
        @{
            emailAddress = @{
                address = "user1@example.com"
            }
        }
    )
}

Send-MgUserMail -userId sender@domain.org -Message $Message
```

This will all be simplified once we implement https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/798.
