### ISSUE TITLE
How to get Channel messages and replies 

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/msgraph-sdk-powershell#804]
When I used only PnP.powershell, I could get a token and use it to do pure Graph REST call
```
$token = Get-PnPGraphAccessToken 
$header = @{ Authorization = "Bearer $($token)" }
$Uri = "https://graph.microsoft.com/v1.0/teams/$($team.GroupId)/channels/$($channel.Id)/messages/$($message.Id)/replies" 
$response = Invoke-RestMethod -Uri $Uri –Headers $header –Method Get –ContentType "application/json"
```
I added Microsoft.Graph.Mail to the script to send email (works fine) but now I get error:
```
Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.11.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find
     | or load a specific file. (0x80131621)
```
On the line `$token = Get-PnPGraphAccessToken `
So I thought I replace the pure Graph REST call with a call using -Module -Name Microsoft.Graph.Teams
I can't find any documentation that will show how to get replies with it.
Can someone please show an example?
Thanks  
[AB#10530](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10530)

**Comment by peombwa** [comment]
Hi @Ofer-Gal, this is an issue with the PnP module and not our module. We use version `5.6.0` of [`System.IdentityModel.Tokens.Jwt`](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Authentication/Authentication.Core/Microsoft.Graph.Authentication.Core.csproj#L16.) and [handle dependency resolution on our own](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/585). 

I would suggest you open an issue with PowerShell PnP for them to fix it - https://github.com/pnp/powershell/issues.

This could be related to https://github.com/pnp/powershell/issues/488.

**Comment by peombwa** [comment]
Closing since the error is from PowerShell PnP module.
