### ISSUE TITLE
How to move a user message with attachments?

### ISSUE THREAD

**Issue by bwarren18** [microsoftgraph/msgraph-sdk-powershell#814]
Hello,
I am trying to move a user message with attachments into a desired mail folder.  

Ideally there would be a simple move command but it seem we have to create a new message copy and remove the original.

I can create a copy as a draft in the desired folder but it does not have the attachments:
$newMessage = $Message | New-MgUserMailFolderMessage -UserId $UserId -MailFolderId $MailFolderId

I've tried using:
Update-MgUserMailFolderMessage -MailFolderId $newMessage.Id -MessageId $newMessage.Id -UserId $UserId -Attachments $Message.Attachments

Update-MgUserMailFolderMessageAttachment -MailFolderId $newMessage.Id -MessageId $newMessage .Id -UserId $UserId -AttachmentId $Message.Attachments.Id

**Comment by peombwa** [comment]
Sorry for the delayed response.

You should be able to add an attachment to a draft message using `New-MgUserMailFolderMessageAttachment`. See the example at https://learn.microsoft.com/en-us/graph/api/message-post-attachments?view=graph-rest-1.0&tabs=powershell#example-file-attachment for additional info.

The functionality of the commands in this module are limited to what is supported by the service.
