### ISSUE TITLE
Introduce capability to Exclude .Notes Section from ProxyCmdletsDefinitions.ps1 

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#815]
Fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/805 
[AB#10614](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10614)

**Comment by peombwa** [comment]
AutoREST.PowerShell PR -> https://github.com/Azure/autorest.powershell/pull/813

**Comment by georgend** [comment]
Waiting for confirmation on whether npm release will be done so we can migrate back to npm package.

**Comment by georgend** [comment]
Added autorest as a submodule.
