### ISSUE TITLE
Get-MgUserPlannerPlanTask returns Error

### ISSUE THREAD

**Issue by icedkopi4me** [microsoftgraph/msgraph-sdk-powershell#821]
After getting the userid and plannerplan id, I tried to run them with the get-mguserplannerplantask command but the following error occurred. Could this be a bug?

Get-MgUserPlannerPlanTask : No HTTP resource was found that matches the request URI 'https://tasks.office.com:444/taska
pi/V3.0/users('_UserIDMasked_')/details/plans('_PlannerPlanIDMasked_')/tasks'.
At line:1 char:1
+ Get-MgUserPlannerPlanTask -UserId _UserIDMasked_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = ce12...ndProperty =  }:<>f__AnonymousType29`10) [Get-MgUse
   rPlannerPlanTask_List1], RestException`1
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgUserPlannerPlanTask_List1 
[AB#10672](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10672)

**Comment by peombwa** [comment]
@icedkopi4me, thanks for surfacing. The error message is saying that the service doesn't support this call (`GET /users/{user-id}/planner/plans/{plan-id}/tasks`). Unfortunately, the metadata that this SDK is generated from isn't fully annotated to tell us whether or not this API path is supported. We will remove `Get-MgUserPlannerPlanTask` in our next release.

According to the [API reference docs](https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-beta&tabs=http), you can only list planner tasks attached to a user using `Get-MgUserPlannerTask` - `GET /users/{id}/planner/tasks`. In your case, you can use this command and filter the response by `planId` like this:
``` powershell
Get-MgUserPlannerTask -UserId $env:App_User_Id -Debug | where PlanId -eq $PlanId
```

I'd also recommend you open a feature request [here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) for the service team to add this API in the future.
