### ISSUE TITLE
Get-MgUserMailFolder cmdlets very spammy in transcript

### ISSUE THREAD

**Issue by ildjarnisdead** [microsoftgraph/msgraph-sdk-powershell#823]
In the console, Get-MgUserMailFolder is quiet, but in the transcript a lot of INFO noise is generated. Similar with Get-MgUserMailFolderChildFolder.

Get-MgUserMailFolder -UserId $MyUser -All results in the following output in a transcript:

INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData
INFO: Microsoft.Graph.PowerShell.Runtime.EventData 
[AB#10693](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10693)

**Comment by ProgrammingWithDJ** [comment]
Hello @peombwa thanks for looking into it.

I am getting this error aftering running this command Connect-MgGraph and this is the below output I get.

The command is working as expected however I am spammed with **Info: Microsoft.Graph.PowerShell.Runtime.EventData**

is there any way we can avoid that ?


Connect Success
● CSV file read check

Read CSV file: Success

Number of readings: 2

The following email addresses are already licensed.
test01@abc.onmicrosoft.com

● License grant
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData

**Comment by peombwa** [comment]
@ProgrammingWithDJ, the issue was fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/868. Please update to the latest version of the module - `Update-Module Microsoft.Graph`.
