### ISSUE TITLE
Whe creating a new application from template the owner is not set

### ISSUE THREAD

**Issue by Lumute** [microsoftgraph/msgraph-sdk-powershell#829]
Hello,

I have an application that creates other applications using Invoke-MgInstantiateApplicationTemplate.

This main application has Application.ReadWrite.OwnedBy permission but the problem is that this method of creating the application is leaving the owners empty (verified using Get-MgApplicationOwner), so I cannot update the application after created, including adding itself as the owner...

When creating an application using New-MgApplication the owner is automatically set to the ServicePrincipal of the main application, I think Invoke-MgInstantiateApplicationTemplate should do the same...

Am I doing something wrong or is it a problem of the template I'm using? (8adf8e6e-67b2-4cf2-a259-e3dc5476c621)?

The only workaround I found was to give the main application Application.ReadWrite.All but would like to avoid this.

 
[AB#10869](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10869)

**Comment by peombwa** [comment]
Sorry for the delayed response.

Please see the answer at https://github.com/microsoftgraph/microsoft-graph-docs/issues/16545.
> You/the app can modify the service principal and assign it an owner, but you must grant the app the Application.ReadWrite.All and Directory.Read.All permissions.

Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from subject matter experts for additional help.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.
