### ISSUE TITLE
Transferring issue #12655 - Update synchronizationSchema - HTTP Method mismatch with OpenAPI definition (MG Powershell)

### ISSUE THREAD

**Issue by lramosvea** [microsoftgraph/msgraph-sdk-powershell#831]
Please take a look at this issue which was raised on the microsoft-graph-docs repo:
https://github.com/microsoftgraph/microsoft-graph-docs/issues/12655

Seems like the issue is with the OpenAPI definition. The PowerShell team needs to ensure that the OpenAPI definition explicitly defines the method required. 
[AB#10882](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10882)

**Comment by peombwa** [comment]
Thanks for surfacing this! This is a known issue with the metadata annotation, and we are tracking it here https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/607 and https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/714.

Closing as duplicate.
