### ISSUE TITLE
Cannot use Get-MgUserAuthenticationPhoneMethod more than once per session

### ISSUE THREAD

**Issue by olaholtberget** [microsoftgraph/msgraph-sdk-powershell#835]
Trying to use it for another user in the same session does not work. Have to start a new powershell session.

**Comment by darrelmiller** [comment]
Can you describe the error that you are getting?  Can you show the -debug output of the call?  I tried to repro the issue but I was not able to.

**Comment by olaholtberget** [comment]
Thanks for taking a look! Here is the debug output, right now only in norwegian. If it helps, I'll reproduce in english.

`DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://graph.microsoft.com/beta/users/____________/authentication/phoneMethods
DEBUG: RequestCreated: https://graph.microsoft.com/beta/users/____________/authentication/phoneMethods
DEBUG: HeaderParametersAdded: https://graph.microsoft.com/beta/users/____________/authentication/phoneMethods
DEBUG: GET /beta/users/____________/authentication/phoneMethods HTTP/1.1
HTTP: graph.microsoft.com


DEBUG: BeforeCall: 
DEBUG: Finally: 
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletException: HttpRequestException - Det oppstod en feil under sending av forespørselen. :    ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Graph.RedirectHandler.<SendAsync>d__6.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Graph.RetryHandler.<SendAsync>d__9.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Graph.CompressionHandler.<SendAsync>d__2.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Graph.AuthenticationHandler.<SendAsync>d__16.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Graph.PowerShell.IdentitySignIns.<UsersAuthenticationListPhoneMethods_Call>d__1497.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved Microsoft.Graph.PowerShell.IdentitySignIns.<UsersAuthenticationListPhoneMethods_Call>d__1497.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Graph.PowerShell.IdentitySignIns.<UsersAuthenticationListPhoneMethods>d__1495.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Graph.PowerShell.Cmdlets.GetMgUserAuthenticationPhoneMethod_List.<ProcessRecordAsync>d__82.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved Microsoft.Graph.PowerShell.Cmdlets.GetMgUserAuthenticationPhoneMethod_List.<ProcessRecordAsync>d__82.MoveNext()
Get-MgUserAuthenticationPhoneMethod : Det oppstod en feil under sending av forespørselen.
At line:1 char:1
+ Get-MgUserAuthenticationPhoneMethod -UserId $user -debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgUserAuthenticationPhoneMethod_List], HttpRequestException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgUserAuthenticationPhoneMethod_List
 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: CmdletEndProcessing: 
`

**Comment by peombwa** [comment]
@olaholtberget, please share the output of the following for us to try repo this on our end:
#### Environment
- `$PSVersionTable`
- `$host.CurrentCulture`

#### Modules
- `Get-Module Microsoft.Graph -ListAvailable`

**Comment by olaholtberget** [comment]
Thank you. The issue was related to ServerCertificateValidationCallback and unrelated to Get-MgUserAuthenticationPhoneMethod and is fixed now. The issue can be closed.
