### ISSUE TITLE
Improve PowerShell ease of use and documentation

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/msgraph-sdk-powershell#836]
Tracks all the work related to increasing discoverability and better documentation 
[AB#10962](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10962)

**Comment by cparkerx** [comment]
I just want to draw attention to this again. The documentation is nearly non-existent for this SDK.

**Comment by ddyett** [comment]
tracking with other items, closing legacy issue.
