### ISSUE TITLE
Multi-choise SP column with New-MgSiteListItem

### ISSUE THREAD

**Issue by apospa** [microsoftgraph/msgraph-sdk-powershell#839]
Hi, i'm trying to create list items using New-MgSiteListItem but i have problem with multiple choise column. PnP works well but i need to use MG now.

When i change column to single value it works great bud after switch to multiple value it goes to error.

`New-MgSiteListItem -ListId $ListId -SiteId $SiteId -Fields @{ "Title" = $user.DisplayName ; "UPN" = $user.UserPrincipalName ; "TestChoise" = @("A", "B") }`

Error:
New-MgSiteListItem : Invalid request
At line:1 char:1

New-MgSiteListItem -ListId $ListId -SiteId $SiteId -Fields @{
  + CategoryInfo          : InvalidOperation: ({ SiteId = f812...GraphListItem }:<>f__AnonymousType4`3) [New-MgSiteListItem_CreateExpanded], RestExc  
 eption`1
  + FullyQualifiedErrorId : invalidRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgSiteListItem_CreateExpanded

**Comment by apospa** [comment]
sorry, now i got it

**Comment by hpascaud** [comment]
Hello,
I come back always on your post when I am searching on the internet how to create a new item using New-MgSiteListItem and setting directly a multi-choice column value.
This is very frustating to read that you got it but you do not explain how you solved the case.
Can you explain, please ?

**Comment by apospa** [comment]
@hpascaud Hi, it log time ago so i can't remeber what was the use case, but for example this worked: 
Licence is multi-choise column. 

`New-MgSiteListItem -ListId $ListId -SiteId $SiteId -Fields @{
        "UserUPN" = $user.UserPrincipalName ; 
        "Title" = $user.DisplayName;
        "City" = $user.city
        "Licence@odata.type" = "Collection(Edm.String)" ;
        "Licence" = $lic ;    
    
    }`

**Comment by hpascaud** [comment]
I thank you so much for your quick answer, it helped me a lot.
It confirmed that it works by adding the odata.type information and I finally found the solution.
Additionnaly to the odata.type information, it is mandatory to give to the "Fields" parameter an array of string [string[]] (not a simple array) for the specific MultiChoice field.

For example:
The following line does not work: 
New-MgSiteListItem -SiteId $SiteId -ListId $ListId -Fields @{"Title" = "TEST"; "ChoiceColumnIntenalName@odata.type" = "Collection(Edm.String)" ; "ChoiceColumnIntenalName" = "Choice1" }

The following line will work even with only one data in $Choice: 
[string[]]$Choice = "Choice1", 'Choice2'
New-MgSiteListItem -SiteId $SiteId -ListId $ListId -Fields @{"Title" = "TEST"; "ChoiceColumnIntenalName@odata.type" = "Collection(Edm.String)" ; "ChoiceColumnIntenalName" = $Choice }
