### ISSUE TITLE
Get-MgUser not returning per-user MFA status

### ISSUE THREAD

**Issue by jasonfritts** [microsoftgraph/msgraph-sdk-powershell#841]
Currently using MSOnline module and the Get-MsolUser cmdlet will return per-user MFA status for a user like the following:

> (get-msoluser -UserPrincipalName 'username@domain.com’).strongauthenticationrequirements.state
> 
> Enabled

However the MSGraph SDK PowerShell module's Get-MgUser cmdlet doesn't return per-user MFA status or strongauthenticationrequirements.state attribute of user.  The closest option is Get-MgUserAuthenticationPhoneMethod, which only returns any registered methods.  Not whether the user is enabled\disabled for per-user MFA as documented here https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-userstates#view-the-status-for-a-user

Will this functionality be added prior to MSOnline module \ AAD Graph API being deprecated on 6/30/2022?

**Comment by peombwa** [comment]
Hi @jasonfritts, this functionality is missing in Microsoft Graph API. You can use `Get-MgReportCredentialUserRegistrationDetail -Filter "UserPrincipalName eq '$Upn'"` to get a user's MFA registration status, but that won't let you know if a user has enabled/disabled MFA.

I would recommend you open a feature request [here](https://developer.microsoft.com/en-us/graph/support) for the workload owners to add this.

**Comment by peombwa** [comment]
Closing as not actionable by the SDK since API is missing.
