### ISSUE TITLE
devicemanagement.enrolment module has entitlement management cmdlets

### ISSUE THREAD

**Issue by markwahl-msft** [microsoftgraph/msgraph-sdk-powershell#842]
It is confusing that there are cmdlets for managing entitlement management roles in the `Microsoft.Graph.DeviceManagement.Enrolment` package, such as "Get-MgRoleManagementEntitlementManagementRoleDefinition".  I would expect them in either identity governance or unified RBAC.

I believe this may originate from the modulemapping file in which the line for `1DeviceManagement.Enrolment` includes

```
^roleManagement\\.",
 ```
 
this is too broad a namespace since Graph role management https://docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta 
currently supports the following RBAC providers in Microsoft 365:

* Cloud PC
* device management (Intune)
* directory (Azure AD directory roles)
* entitlement management (Azure AD entitlement management)

but only the 2nd of the 4 are relevant to this module.
This line should be changed in 

https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/92cfeb72b714e24a0b2b700a7c49aa30585ae12c/config/ModulesMapping.jsonc#L13

to allow other modules to have their rolemanagement cmdlets relevant to them.

**Comment by peombwa** [comment]
We will address this in v2 of the SDK since changing it now would result in a breaking change. Is there someone from the workload team we can work with to help with the module classification?

cc\ @maisarissi

**Comment by peombwa** [comment]
Fixed by #1573
