### ISSUE TITLE
OData 4.0 $value?

### ISSUE THREAD

**Issue by Viajaz** [microsoftgraph/msgraph-sdk-powershell#843]
How do I obtain `$value` of something? Is this supported?
https://docs.microsoft.com/en-us/graph/query-parameters?view=graph-rest-1.0#other-odata-url-capabilities

Example:
`Get-MgUserMessage`
`https://graph.microsoft.com/v1.0/me/messages/4aade2547798441eab5188a7a2436bc1/$value`
https://docs.microsoft.com/en-us/graph/outlook-get-mime-message

**Comment by Viajaz** [comment]
For my use-case, it appears to be `Get-MgUserMessageContent`
Is this Cmdlet naming convention `*Content` used throughout the module for calls to `$value` of an item?

**Comment by peombwa** [comment]
@Viajaz, yes, that's the naming convention used for all commands that call `$value` and return a binary.
