### ISSUE TITLE
Send-MgUserMail: Send a new message using MIME format

### ISSUE THREAD

**Issue by Viajaz** [microsoftgraph/msgraph-sdk-powershell#844]
Support for sending a new message using MIME format with `Send-MgUserMail`

https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#example-4-send-a-new-message-using-mime-format

**Comment by Viajaz** [comment]
For those in the same position, use `Invoke-MgGraphRequest` for now:

Delegated permissions
```powershell
Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/me/sendMail" -Body $RequestBody -ContentType 'text/plain'
```

Application level permissions
```powershell
Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/users/$($UserId)/sendMail" -Body $RequestBody -ContentType 'text/plain'
```

An example using [Mailkit](url) ([DE0005](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md))
```powershell
Add-Type -Path MailKit.dll
$Message = [MimeKit.MimeMessage]::new()
$Message.From.Add([MimeKit.InternetAddress]'sender@example.com')
$Message.To.Add([MimeKit.InternetAddress]'receiver@example.com')
$Message.Subject = 'Test'
$BodyBuilder = [MimeKit.BodyBuilder]::new()
$BodyBuilder.TextBody = 'This is a test message'
$Message.Body = $BodyBuilder.ToMessageBody()
$MessageStream = [System.IO.MemoryStream]::new()
$Message.WriteTo($MessageStream)
$MessageStream.Position = 0
$MessageStreamReader = [System.IO.StreamReader]::new($MessageStream, [System.Text.Encoding]::UTF8)
$MessageMIME = $MessageStreamReader.ReadToEnd()
$RequestBody = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($MessageMIME))
Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/me/sendMail" -Body $RequestBody -ContentType 'text/plain'
```

**Comment by ddyett** [comment]
@peombwa is this something implemented in V2.

**Comment by peombwa** [comment]
@ddyett, MIME format is currently [not supported by all SDKs](https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=powershell#example-4-send-a-new-message-using-mime-format) due to missing MIME path in the metadata used to generate the SDKs. A workaround is to fall back to `Invoke-MgGraphRequest` as documented https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/844#issuecomment-913372673. I'll transfer the issue to the metadata repo for visibility.

**Comment by peombwa** [comment]
Transferred to https://github.com/microsoftgraph/msgraph-metadata/issues/389.
