### ISSUE TITLE
Error: New-MgServicePrincipal : The appId of the  service Principal does not reference a valid application object

### ISSUE THREAD

**Issue by ranabanerjee15** [microsoftgraph/msgraph-sdk-powershell#846]
Hello Microsoft Graph Team,

I am attempting to create a Service Principal with SAML as preferedSingleSignOnMode.

I get the following error while running the command.

"The appId <GUID> of the service principal does not reference a valid application object"

Please guide me, what am I doing wrong? 

Screenshot below
![New-MGServicePrincipal_Error](https://user-images.githubusercontent.com/33179430/132302497-cbcaf14d-c605-4b6a-a811-4d368993baaf.png)

The objective here is to register a Non-Gallery application
![LegacyApp - NonGalleryApp](https://user-images.githubusercontent.com/33179430/132423743-e435abf7-84be-40c9-8d9d-ba1bb5b4b5d7.png)

**Comment by peombwa** [comment]
The AppId should be the appId of an existing [application](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0); that's what the error is saying. See our samples on how to create a corresponding [service principal](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0) from an [application](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0), https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/9-Applications.ps1#L97-L103.

You can also use [this guide](https://docs.microsoft.com/en-us/graph/application-saml-sso-configure-api) for instructions on how to configure SAML-based sign-on for your application.

**Comment by ranabanerjee15** [comment]
@peombwa Thank you for your guidence. I Used the non-gallery app template to create it. please see my working code below:
### Non Gallery App template
```'8adf8e6e-67b2-4cf2-a259-e3dc5476c621'```

### App roles. please replace these roles as required by you
```powershell
$roles = 'role1','role2','role3'
```

### SAML Tagsare required for the service principal for SAML/SSO
```powershell
$samlTags = @(
	'8adf8e6e-67b2-4cf2-a259-e3dc5476c621'
	'WindowsAzureActiveDirectoryGalleryApplicationNonPrimaryV1'
	'WindowsAzureActiveDirectoryCustomSingleSignOnApplication'
	'WindowsAzureActiveDirectoryIntegratedApp'
)
```

### Creates Non Gallery App using template
```powershell
Invoke-MgInstantiateApplicationTemplate -ApplicationTemplateId '8adf8e6e-67b2-4cf2-a259-e3dc5476c621' -DisplayName TestApp1 -ErrorAction Stop
```

### Get the created Service principal
```powershell
$sp = Get-MgServicePrincipal -Filter "DisplayName eq 'TestApp1'"
```
### AppRoles will hold all the roles. below code will save the default 2 roles.
```powershell
$appRoles = $sp.AppRoles
```
### This will create the requred app roles object 
```powershell
foreach ($role in $roles)
{
	$null = $roleObj
	[PscustomObject]$roleObj = @{
		AllowedMemberTypes = @('User')
		Description	       = $role
		DisplayName	       = $role
		Id				   = $((New-Guid).Guid)
		IsEnabled		   = $true
		Origin			   = 'ServicePrincipal'
		Value			   = $role
		AdditionalProperties = $null
	}
	$appRoles += $roleObj
}
```

### This will add a token signing cert
```powershell
Add-MgServicePrincipalTokenSigningCertificate -ServicePrincipalId $sp.Id -ErrorAction stop
```

# This updates the Service Principal with the correct App Roles, SAML tags and notification Email
```powershell
$paramUpdateMgServicePrincipal = @{
    ServicePrincipalId = $sp.Id
    PreferredSingleSignOnMode = 'saml'
    Tags			   = $samlTags
    NotificationEmailAddresses = 'notifications@yourdomain.com'
    AppRoles		   = $appRoles
}

Update-MgServicePrincipal @paramUpdateMgServicePrincipal
```
