### ISSUE TITLE
Every single cmdlet requests another authentication prompt

### ISSUE THREAD

**Issue by ToninoBruno** [microsoftgraph/msgraph-sdk-powershell#851]
Hi,

I do a Connect-MgGraph with the scopes I need and authenticate successfully, I launch the first cmdlet (ex. Get-MgGroup) and it asks me again to authenticate and then constantly repeats this for every single cmdlet I run. Once I pass the authentication I do get the results I need from the cmdlet, but unless I am missing something I should not be prompted each time right?

Sincerely,
Tonino Bruno

**Comment by maisarissi** [comment]
Hello @ToninoBruno.

I couldn't repro your issue. We have docs on how to use Connect-MgGraph using scopes on the [docs site](https://docs.microsoft.com/en-us/graph/powershell/get-started).

I was able to connect successfully after giving admin consent.

```powershell
Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"

Welcome To Microsoft Graph!
```

And I was able to successfully call the cmdlets without having to sign in again.

Can you provide more information about what are you trying to accomplish, which permissions are you getting when connecting to Graph and whether is a delegated access or app-only?

**Comment by Clifra-Jones** [comment]
> Hello @ToninoBruno.
> 
> I couldn't repro your issue. We have docs on how to use Connect-MgGraph using scopes on the [docs site](https://docs.microsoft.com/en-us/graph/powershell/get-started).
> 
> I was able to connect successfully after giving admin consent.
> 
> ```powershell
> Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"
> 
> Welcome To Microsoft Graph!
> ```
> 
> And I was able to successfully call the cmdlets without having to sign in again.
> 
> Can you provide more information about what are you trying to accomplish, which permissions are you getting when connecting to Graph and whether is a delegated access or app-only?

I am having the same issue.
PowerShell Core 7.1.4
Microsoft.Graph module 1.7.0
Operating System Ubuntu 20.04
Browser Chrome

Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"

This opens browser and authenticates fine.

Get-MgUser I get prompted to authenticate again.

I have not tried this in PowerShell Core on Windows I will tomorrow and post results here.

**Comment by HAL377** [comment]
I am doing precisely the steps as documented and the authentication happens fine and the cmdlet I used returns the results I need. Issue is that each time I use any of the cmdlets it opens the browser and asks to authenticate again, which makes automation a bit complicated ☺️

**Comment by Clifra-Jones** [comment]
Ok, was finally able to test this in Windows. On windows, with PS Core 7.1.4, this works as expected.

So is this not cross-platform?

**Comment by HAL377** [comment]
Hi,

In my case I am running this on Windows 10 with Powershell 5.2…

What can I provide as additional details or logs to help  troubleshoot this? 

Thanks again 🤗

**Comment by Clifra-Jones** [comment]
> Hi,
> 
> In my case I am running this on Windows 10 with Powershell 5.2…
> 
> What can I provide as additional details or logs to help troubleshoot this?
> 
> Thanks again

Working for me in Windows with both Windows PowerShell 5.1 and Powershell 7.1.4
I am wondering if this has something to do with local security settings.
Clarification: I am running windows on an AWS Workspaces system with in fact is Windows Server 2019, not Windows 10.

Can anyone from the Dev team comment on this?

**Comment by peombwa** [comment]
This seems to be an issue with how the access token is encrypted and cached on disk on Ubuntu/Linux distros. It works fine on Windows and MacOS.

As a workaround, you can change the auth session context to process only via `Connect-MgGraph -ContextScope Process`. By default, signing in as a user sets the `ContextScope` to `CurrentUser`.

We will fix this in the next release of the SDK.

**Comment by peombwa** [comment]
I'm only able to repro this when using Ubuntu via WSL. Regular versions of Ubuntu and Ubuntu Server work fine without any issues.

@Clifra-Jones, @HAL377, @ToninoBruno, please share the output of the following for us to try repo this on our end:
#### Environment
- `$PSVersionTable`
- `$host.CurrentCulture`

#### Modules
- `Get-Module microsoft.graph -ListAvailable`

**Comment by christiandekker** [comment]
I'm experiencing the same issue on Windows in both PowerShell and Powershell ISE, running with or without elevated permissions. The workaround of setting the ContextScope to Process works for me. 


#### Environment
`
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value                                                                                                                                                                                                                             
----                           -----                                                                                                                                                                                                                             
PSVersion                      5.1.19041.1237                                                                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                           
BuildVersion                   10.0.19041.1237                                                                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                               
SerializationVersion           1.1.0.1                                                                                                                                                                                                                           



PS C:\WINDOWS\system32> $host.CurrentCulture

LCID             Name             DisplayName                                                                                                                                                                                                                    
----             ----             -----------                                                                                                                                                                                                                    
1043             nl-NL            Dutch (Netherlands)                                                                                                                                                                                                            



PS C:\WINDOWS\system32> Get-Module microsoft.graph -ListAvailable


    Directory: C:\Users\ChristianDekkerLemon\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Manifest   1.7.0      Microsoft.Graph  
`

**Comment by ToninoBruno** [comment]
> I'm only able to repro this when using Ubuntu via WSL. Regular versions of Ubuntu and Ubuntu Server work fine without any issues.
> 
> @Clifra-Jones, @HAL377, @ToninoBruno, please share the output of the following for us to try repo this on our end:
> 
> #### Environment
> * `$PSVersionTable`
> * `$host.CurrentCulture`
> 
> #### Modules
> * `Get-Module microsoft.graph -ListAvailable`

Hi,

With the suggested workaround "-ContextScope Process" it's working fine, when I try -ContextScope CurrentUser it ask for authentication on each cmdlet.

Here is what you asked on my machine:

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

$host.CurrentCulture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)

Get-Module microsoft.graph -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.7.0      Microsoft.Graph
Manifest   1.6.1      Microsoft.Graph

**Comment by ToninoBruno** [comment]
Apologies closed by accident ...

ps: HAL377 and Tonino@brunonilis.com are both my accounts :-)

**Comment by mariussm** [comment]
I have this issue aswell:

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



$host.CurrentCulture

LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)



Get-Module microsoft.graph -ListAvailable

    Directory: C:\Users\solbamar\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.8.0                 Microsoft.Graph                     Core,Desk
Manifest   1.6.1                 Microsoft.Graph                     Core,Desk
Manifest   1.6.0                 Microsoft.Graph                     Core,Desk


Had the issue on all versions. ContextScope solves nothing.

**Comment by ztrhgf** [comment]
I have also exactly the same problem (on Windows).

I tried module Microsoft.Graph.Authentication in versions 1.9.5 and 1.9.2.

BUT when I use an account that has no MFA protection it works! So it seems the problem is related just to MFA protected accounts.

**Comment by peombwa** [comment]
@ztrhgf, could you try cleaning your cache as described in the known issues to see if this fixes the issue for you - https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues.

**Comment by 410sean** [comment]
`Remove-Item "$env:USERPROFILE\.graph" -Recurse -Force` so far is working as a fix. myself and a coworker have run into this problem.

**Comment by mariussm** [comment]
Same for me - removing the .graph cache works. Finally!

**Comment by Canthv0** [comment]
Removing the Graph Cache fixed it for me as well.

Windows 11 with PowerShell 7.2.4

**Comment by magic-happenz** [comment]
I am also on Windows 11 with PowerShell 7.2.4 and the cache removal fixed it for me.

**Comment by weyCC81** [comment]
This happened to me again with the following Module Version installed:
```
Directory: C:\Program Files\WindowsPowerShell\Modules
Manifest   1.19.0     Microsoft.Graph
Manifest   1.16.0     Microsoft.Graph
Manifest   1.11.0     Microsoft.Graph
```
I have now upgraded to "1.22.0" and removed the cache again
```
Directory: C:\Program Files\WindowsPowerShell\Modules
Manifest   1.22.0     Microsoft.Graph
```
