### ISSUE TITLE
New-MgUserMessage (and friends)

### ISSUE THREAD

**Issue by stefan923456** [microsoftgraph/msgraph-sdk-powershell#854]
Hello,

I am trying to use the New-MgUserMessage commandlet to create and send mailmessages. In the help files it only says "create hash" tables, but no examples on how to format the hash tables, the suggested help is not sufficient and I cannot find any example anywhere.

The examples on GitHub or Microsoft only state:
PS C:\> {{ Add code here }}

{{ Add output here }}

Please update the documentation and add examples on how to construct the different hash tables with PowerShell.

I got stuck at the -torecipients hash table for example, but please add all the examples you can think of.

At this point the commands are useless at least to me.

thx.
Stefan

**Comment by vandreytrindade** [comment]
@stefan923456 
I've managed to do it using this code:

```
$MailParams = @{
    Subject = “Mail test”
    UserId = “admin@domain.com”
    Body = @{
        content = “This is a test mail!”
        contentType = “HTML”
    }
    ToRecipients = @(
        @{
            emailAddress = @{
                address = “user1@domain.com”
            }
        },
       @{
           emailAddress = @{
               address = “user2@domain.com”
           }
       }
    )
}


$NewMessage = New-MguserMessage @MailParams
Send-MgUserMessage -UserId $MailParams.UserId -Messageid $newmessage.id
```

All credits go to Tony Redmond:
- https://practical365.com/send-mail-exchange-online-graph-powershell/
- https://practical365.com/upgrade-powershell-scripts-sendmailmessage/

**Comment by peombwa** [comment]
You can also find how-to examples in the API reference pages as snippets for most APIs. See:
- https://docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&tabs=powershell#example-1-create-a-message-draft-in-json-format.
- https://docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&tabs=powershell#example-1-create-a-message-draft-in-json-format
