### ISSUE TITLE
Adding/Removing members from AU

### ISSUE THREAD

**Issue by andersjulton** [microsoftgraph/msgraph-sdk-powershell#857]
Does the SDK lack a CMDLET for adding and removing members from an AU?

**Comment by peombwa** [comment]
@andersjulton Is this API currently available through Microsoft Graph service - https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0? If so, you can pass the API URL to `Find-MgGraphCommand` to find which command calls it. e.g., `Find-MgGraphCommand -Uri /directory/administrativeUnits`. See, https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/816.
