### ISSUE TITLE
Update-MgDevice - Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by sergiopenteado** [microsoftgraph/msgraph-sdk-powershell#858]
Even when connected with the right scope (DeviceManagementManagedDevices.ReadWrite.All) and having global admin privileges the cmdlet update-mgdevice asks for more privileges.

Update-MgDevice -DeviceId $a.Id -DeviceOwnership company

Update-MgDevice : Insufficient privileges to complete the operation.
At line:1 char:1
+ Update-MgDevice -DeviceId $a.Id -DeviceOwnership company
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ DeviceId = 5d...tGraphDevice1 }:<>f__AnonymousType4`2) [Update-MgDevice_UpdateExpanded1], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDevice_UpdateExpanded1

**Comment by peombwa** [comment]
@sergiopenteado, `DeviceManagementManagedDevices.ReadWrite.All` is not one of the permissions needed to update a device. Here are all the permissions needed to update a device https://docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-1.0&tabs=http#permissions.

**Comment by peombwa** [comment]
Also, please not that `deviceOwnership` property is set by Intune, see https://docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta#properties.
