### ISSUE TITLE
How to add members to administrative unit using 'New-MgDirectoryAdministrativeUnitMemberByRef'

### ISSUE THREAD

**Issue by thuld** [microsoftgraph/msgraph-sdk-powershell#859]
I try to add a user to an administrative unit in Azure AD using `New-MgDirectoryAdministrativeUnitMemberByRef` but I do not understand how to use this cmdlet. The following code results in error

````PowerShell
New-MgDirectoryAdministrativeUnitMemberByRef -AdministrativeUnitId $unit.id -BodyParameter  @{ 'UserId' = '83b01168-c419-43de-ad46-dbcf15e6976b'}
````

Error raised
````
New-MgDirectoryAdministrativeUnitMemberByRef : An unexpected 'EndOfInput' node 
was found when reading from the JSON reader. A 'StartObject' node was expected.
````

**Comment by thuld** [comment]
Ok, found the solution:

````PowerShell
New-MgDirectoryAdministrativeUnitMemberByRef -AdministrativeUnitId $unit.id -BodyParameter @{
            "@odata.id" = "https://graph.microsoft.com/v1.0/users/$($user.UserPrincipalName)"
        }
````

**Comment by peombwa** [comment]
Awesome! Closing as resolved.

**Comment by Borgquite** [comment]
Also works, and shorter:
`New-MgDirectoryAdministrativeUnitMemberByRef -AdministrativeUnitId $unit.id -OdataId "https://graph.microsoft.com/v1.0/users/$($user.UserPrincipalName)"`
Can also use the Id parameter in Get-MgUser

**Comment by hhbadarin** [comment]
Thank you to everyone!

**Comment by hhbadarin** [comment]
Thank you to everyone,
I have a csv file with UPNs, the code you provided above helped with adding multiple users to a single administrative unit. But i'm wondering if there's a way to modify the code so we can add each UPN to a corresponding AU in another column in the CSV file?
