### ISSUE TITLE
Get-MsolPasswordPolicy.  How to retrieve this information in msgraph-sdk-powershell?

### ISSUE THREAD

**Issue by glennmspeasy** [microsoftgraph/msgraph-sdk-powershell#860]
What is the equivalent command to Get-MsolPasswordPolicy?
How can the tenant password policy be accessed via ms graph sdk powershell?

**Comment by peombwa** [comment]
Chances are Microsoft Graph API does not support retrieving a tenant's password policy. Please open a question/feature request for the workload owners to look into this here https://developer.microsoft.com/en-us/graph/support.

Here is the list of policies currently available on Microsoft Graph - https://docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta.

**Comment by peombwa** [comment]
Closing as service feature request.
