### ISSUE TITLE
Get-MgOrganization does not consistently return CountryLetterCode

### ISSUE THREAD

**Issue by kfehribach** [microsoftgraph/msgraph-sdk-powershell#861]
In looking to move from the Azure Active Directory/Azure APIs to the MS Graph SDK PowerShell we have found that the Get-MgOrganization call does not always return a CountryLetterCode (but does for some tenants).

![Powershell issue](https://user-images.githubusercontent.com/4000311/134041334-fe09f060-cb37-4db7-b670-2d9b34c7e39b.png)

Here you can see the difference in the AAD call versus the MS Graph.

**Comment by peombwa** [comment]
@kfehribach, this looks like a service issue. Could you try running this in Graph Explorer to see if you get the same response.

**Comment by kfehribach** [comment]
I've added my work address to be able to more promptly reply.
+Brian Jackett from Graph API Team

You are correct that Graph Explorer also does not return the value. I
opened the ticket here because I was directed by Brian Jackett to do so,
but it makes sense that if you guys are just a pass through, to the API
that it's not on your end. But this DOES represent an issue for anyone that
is trying to migrate to your APIs from Azure Active Directory because of
the difference in behavior/inability to transition because of the failing
nature of this call.

Thanks,

**Comment by peombwa** [comment]
Closing as a service issue.

Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support as this is a service issue. In your ticket/question, please include the `requestId` and `date` of the affected calls. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details.
