### ISSUE TITLE
Investigate support for OpenType entities.

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#87]
[AB#4596](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4596)

**Comment by peombwa** [comment]
Related to #19

**Comment by darrelmiller** [comment]
This is not the same as OpenTypes.  OpenTypes are needed for Planner and Sharepoint List Items.

**Comment by peombwa** [comment]
This will also fix https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/119.

**Comment by peombwa** [comment]
We should add `additionalData` property bag to all entities.

**Comment by peombwa** [comment]
To fully support OpenType entities, we need to:
1. Add `additionalProperties` - [JSON Schema](https://json-schema.org/understanding-json-schema/reference/object.html#properties) - to [OpenAPI schema objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object) that are defined as OpenType entities in the CSDL.
![image](https://user-images.githubusercontent.com/7061532/84452269-3a8a1600-ac0a-11ea-8607-f58cc83c2eb6.png)
2. At generation time, AutoREST will generate a dictionary property named `AdditionalProperties` that will hold extra properties that are not defined in the properties property of a schema object.
![image](https://user-images.githubusercontent.com/7061532/84453188-6e663b00-ac0c-11ea-9d68-467b31e32969.png)

Unfortunately, AutoREST doesn't allow us to change the name of the `additionalProperties` bag - [source code ref](https://github.com/Azure/autorest.powershell/blob/c380cbef327b78bee84f1dc4569d28639c1a23da/powershell/llcsharp/model/model-class-dictionary.ts#L33).

**Comment by ddyett** [comment]
deployment scheduled for 8/5-8/7
