### ISSUE TITLE
MgDeviceManagementDomainJoinConnector Functions Not Listed

### ISSUE THREAD

**Issue by brmcmill** [microsoftgraph/msgraph-sdk-powershell#871]
Hello!

I was trying to see if I can leverage the MgDeviceManagementDomainJoinConnector functions in this module and I do not see them available after being imported from PS Gallery, yet in our docs it states they should be.

[Microsoft Docs: Microsoft.Graph.DeviceManagement.Administration](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement.administration/?view=graph-powershell-beta)

Is there a reason for this?  It would be great to have that ability at some point! Cheers!

**Comment by peombwa** [comment]
Hi @brmcmill, the commands you are looking for are only available in `beta`. Use `Select-MgProfile beta` to load beta command, see https://docs.microsoft.com/en-us/graph/powershell/get-started?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#api-version.

You can use [`Find-MgGraphCommand`](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/816) to find info about a particular command/API endpoint like this:
``` powershell
Find-MgGraphCommand -Command .*-MgDeviceManagementDomainJoinConnector

   APIVersion: beta

Command                                      Module                          Method URI
-------                                      ------                          ------ ---
Get-MgDeviceManagementDomainJoinConnector    DeviceManagement.Administration GET    /deviceManagement/domainJoinConnector…
Get-MgDeviceManagementDomainJoinConnector    DeviceManagement.Administration GET    /deviceManagement/domainJoinConnectors
New-MgDeviceManagementDomainJoinConnector    DeviceManagement.Administration POST   /deviceManagement/domainJoinConnectors
Remove-MgDeviceManagementDomainJoinConnector DeviceManagement.Administration DELETE /deviceManagement/domainJoinConnector…
Update-MgDeviceManagementDomainJoinConnector DeviceManagement.Administration PATCH  /deviceManagement/domainJoinConnector…
```

**Comment by brmcmill** [comment]
Hey @peombwa , that was very helpful and educational.  Once I figured how to give consent via with PowerShell, I still could not remove an existing DomainJoinConnector.  Error below.  Same issue I received using MS Graph Explorer as well.

```
Remove-MgDeviceManagementDomainJoinConnector : {"ErrorCode":"Forbidden","Message":"{\r\n  \"_version\": 3,\r\n
\"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 -
Activity ID: 63da3dd3-b5dc-42eb-9a53-cef1b7b77df3 - Url: https://fef.msua08.manage.microsoft.com/RAODJPlus/StatelessODJ
Service/34893bcc-ffff-3193-0930-092118415083/deviceManagement/domainJoinConnectors%28%278744a9e6-ac76-4aa5-a085-133c88e
dbd5a%27%29?api-version=5018-08-30\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n
\"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\":
\"{}\"\r\n}","Target":null,"Details":null,"InnerError":null,"InstanceAnnotations":[]}
At line:1 char:1
+ Remove-MgDeviceManagementDomainJoinConnector -DeviceManagementDomainJ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ DeviceManagem...a, IfMatch =  }:<>f__AnonymousType90`2) [Remove-MgD
   evice...onnector_Delete], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.RemoveMgDeviceManagementDomainJoinConnec
   tor_Delete
```

MS Graph
```
{
    "error": {
        "code": "UnknownError",
        "message": "{\"ErrorCode\":\"Forbidden\",\"Message\":\"{\\  \\\"_version\\\": 3,\\  \\\"Message\\\": \\\"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: e4243233-6675-dd47-c9de-581529834840 - Url: https://fef.msua08.manage.microsoft.com/RAODJPlus/StatelessODJService/34893bcc-ffff-3193-0930-092118415083/deviceManagement/domainJoinConnectors%28%278744a9e6-ac76-4aa5-a085-133c88edbd5a%27%29?api-version=5018-08-30\\\",\\  \\\"CustomApiErrorPhrase\\\": \\\"\\\",\\  \\\"RetryAfter\\\": null,\\  \\\"ErrorSourceService\\\": \\\"\\\",\\  \\\"HttpHeaders\\\": \\\"{}\\\"\\}\",\"Target\":null,\"Details\":null,\"InnerError\":null,\"InstanceAnnotations\":[]}",
        "innerError": {
            "date": "2021-09-30T18:47:34",
            "request-id": "68dcd1ab-6dd6-4b76-816d-b0aedae16062",
            "client-request-id": "e4243233-6675-dd47-c9de-581529834840"
        }
    }
}
```

Consent for **DeviceManagementConfiguration.ReadWrite.All** access was approved.  Appreciate any feedback!  Thanks again.

**Comment by peombwa** [comment]
This looks like a service issue. As per the [docs](https://docs.microsoft.com/en-us/graph/api/intune-odj-devicemanagementdomainjoinconnector-delete?view=graph-rest-beta), the request and permission you have are valid, and you should be able to remove an existing `DomainJoinConnector`.

Please open a support ticket at https://developer.microsoft.com/en-us/graph/support for this to be investigated/resolved by the workload.

**Comment by brmcmill** [comment]
Sounds great, thanks.  Opened a support request: ID | 2110040040002964.

**Comment by brmcmill** [comment]
@peombwa, after opening up a service request, I was told these connectors will purge after 30 days inactivity so I'm satisfied, but I would be interested in learning if/when the ability remove these connectors on demand can be made available. 

https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid#install-the-intune-connector
