### ISSUE TITLE
`externalDocs` support for the auto-generated PowerShell reference documents

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-powershell#876]
1. Find a way of linking from the PowerShell reference page back to the API reference page.

1. Human written content in API reference page that describes the purpose of the cmdlet/api is not being migrated. Links also need to be migrated to PowerShell reference page.
- Extract the right information that we have in the API page:
   ![image.png](https://images.zenhubusercontent.com/612e38e2887234c73d32e2f9/7f908b21-a34e-429d-bc07-bb9f2b7e2485)
   ![image.png](https://images.zenhubusercontent.com/612e38e2887234c73d32e2f9/39de837c-5341-408b-ba3e-3260836b59b2)
 - And than, use it as the first paragraph. 
   ![image.png](https://images.zenhubusercontent.com/612e38e2887234c73d32e2f9/05116ed8-e260-4214-8999-979c7ce316e7)

      The current information is being retrieved from the relationships session on the doc page:
      ![image.png](https://images.zenhubusercontent.com/612e38e2887234c73d32e2f9/648217a7-c1a0-4b5e-9277-7cb14e8d2fbc)
 

3. Some parameters/properties are not bringing the right description from the API page. (Enum for sure, maybe others too)
- E.g., color in Update-MgUserCalendar ([Update-MgUserCalendar - PowerShell Reference Docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.calendar/update-mgusercalendar?view=graph-powershell-1.0#parameters) // [calendar resource type - Microsoft Graph Docs](https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0#properties))

![image](https://user-images.githubusercontent.com/22648831/143301823-a40a13d4-9e12-4214-8ce8-861cde2b48b1.png)

![image](https://user-images.githubusercontent.com/22648831/143301861-a0c9e423-47e4-4780-a41c-054b4f02bbdd.png)

**Comment by georgend** [comment]
These all map to Operation descriptions in the OpenAPI:
PATCH on a collection: Autogenerate description when DeepInsertSupport or DeepUpdateSupport is present.
PATCH/PUT on a collection item: Use UpdateRestrictions.Description 
GET on a collection: Use ReadRestrictions.Description.
GET on collection item: Use ReadRestrictions.ReadRestrictionByType.Description
POST on a collection: InsertRestriction.Description
DELETE on collection item: DeleteRestrictions.Description

OpenAPI PathItem descriptions are autogenerated and are used by the CLI tooling for things like e.g.  mgc applications -h .  

Relevant Capability Annotations:
https://github.com/oasis-tcs/odata-vocabularies/blob/758e454f012dd50de1f96a51953054ead7ad4656/vocabularies/Org.OData.Capabilities.V1.md#ReadRestrictionsType
https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md#UpdateRestrictionsType

Actions:  
@georgend  to use ApiDoctor to inject from documentation into the CSDL metadata
@irvinesunday  to implement conversion to OpenAPI for operation descriptions in OpenApi.Net.OData library.

**Comment by maisarissi** [comment]
Hey @georgend . As part of our discussion, one of the things we want to investigate is whether is possible to use DevX API permissions endpoint (same endpoint used by @peombwa in the Find-MgGraphCommand) as part of our docs generation to fix https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/132.

**Comment by maisarissi** [comment]
Hi @georgend .
As part of the ask I mentioned 

> Find a way of linking from the PowerShell reference page back to the API reference page.

I was talking to @darrelmiller about linking back to the API page as part of the effort this effort, so I was wondering whether you are going to open a new PR in the APIDoctor to address it or [update the existing one](https://github.com/OneDrive/apidoctor/pull/116).
Can you help me clarify it?

**Comment by darrelmiller** [comment]
Ping @georgend

**Comment by peombwa** [comment]
- [ ] We should investigate if AutoREST supports links.

**Comment by peombwa** [comment]
To have links supported in the command reference, the following prerequisites must be met first:
1. [ ] `ApiDoctor` will need to inject the CSDL metadata with `Links` annotation. https://github.com/OneDrive/apidoctor/issues/114.
2. [ ] `OpenAPI.NET.OData` will need to support converting the OData links annotation to OpenAPI `externalDocs` property of an operation object. https://github.com/microsoft/OpenAPI.NET.OData/issues/230.
3. [ ] `AutoREST.PowerShell` will need to support `externalDocs` on an operation object. https://github.com/Azure/autorest.powershell/issues/960.
