### ISSUE TITLE
New-MgIdentityConditionalAccessNamedLocation discrepancy

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#878]
The New-MgIdentityConditionalAccessNamedLocation cmdlet should access a parameter named ipRanges based on official documentation:

https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-namedlocations?view=graph-rest-1.0&tabs=http

But it doesn't, preventing IP Based Named Locations from being created.

**Comment by NikCharlebois** [comment]
Currently trying:
`
$params = @{
    DisplayName          = "NikIPNamedLocation";
    AdditionalProperties = @{
        '@odata.type' = "#microsoft.graph.ipNamedLocation";
        ipRanges = @(
            @{
                "@odata.type"= "#microsoft.graph.iPv4CidrRange"
                cidrAddress = "1.1.1.1/27";
            }
        )
        isTrusted     = $False;
    }
}

New-MgIdentityConditionalAccessNamedLocation @params
`
Which results in New-MgIdentityConditionalAccessNamedLocation : Property ipRanges in payload has a value that does not match schema.

**Comment by peombwa** [comment]
Hi Nik, this is due to a bug with how the code generator serializes the values of `ipRanges`. We are tracking this under #785.

A workaround is to use `Invoke-MgGraphRequest` as we work on fix:

``` powershell
$params = @{
    DisplayName          = "NikIPNamedLocation";
    AdditionalProperties = @{
        '@odata.type' = "#microsoft.graph.ipNamedLocation";
        ipRanges = @(
            @{
                "@odata.type"= "#microsoft.graph.iPv4CidrRange"
                cidrAddress = "1.1.1.1/27";
            }
        )
        isTrusted     = $False;
    }
}

Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/identity/conditionalAccess/namedLocations" -Body ($params | ConvertTo-Json)
```

**Comment by peombwa** [comment]
Closing as duplicate of #785.
