### ISSUE TITLE
Retrieve role assignment for 'Service Principals' via 'Get-MgDirectoryRoleMember'

### ISSUE THREAD

**Issue by thuld** [microsoftgraph/msgraph-sdk-powershell#880]
Using the Azure AD module and cmdlet `Get-AzureADDirectoryRoleMember` could we retrieve the service-principals that are provided with a given directory role (e.g. "_Directory Readers_"), but the cmdlet `Get-MgDirectoryRoleMember` does not return service-principals:

````PowerShell
Get-MgDirectoryRole | Foreach-Object { 
   $members = (Get-AzureADDirectoryRoleMember -ObjectId $_.Id | Where-Object { $_.ObjectType -ne 'User'})
    ## does not work
    # $members = Get-MgDirectoryRoleMember -DirectoryRoleId $_.Id
}
````

How could I retrieve a list of service-principals that are provided with directory role X?

**Comment by peombwa** [comment]
You can use `additionalProperties` property bag to filter the response by type like this this:
``` powershell
Get-MgDirectoryRole | Foreach-Object { 
    $members = Get-MgDirectoryRoleMember -DirectoryRoleId $_.Id | where { $_.AdditionalProperties."@odata.type" -eq "#microsoft.graph.servicePrincipal"}
}
```

With Microsoft Graph, `GET /directoryRoles/{role-id}/members` returns a collection of [directoryObject](https://docs.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-1.0&tabs=http#response), a base type for user, service principal, application, etc. Customers can use `additionalProperties` to access properties of the derived types.

**Comment by thuld** [comment]
This does not return any members when only service principles are provided with that role. Is this working when using the beta API?
________________________________

**Comment by peombwa** [comment]
@thuld, that's right. This only works in beta. Use `Select-MgProfile beta` to switch to beta.

**Comment by thuld** [comment]
@peombwa thanks man - that was the missing piece!

**Comment by quartelh** [comment]
Hi, when will retrieving role asignments for service principles using Get-MgDirectoryRoleMember work without the need to set the profile to beta?

**Comment by rvdwegen** [comment]
Same question from me since it's been well over a year since the question was first asked.

**Comment by tobywicks-cv** [comment]
As of Nov 2023 - you've got to now use the `Microsoft.Graph.Beta` module and use the Get-MgBeta* functions - i.e. `Get-MgBetaDirectoryRoleMember`. Select-MgProfile beta does not work: https://o365reports.com/2023/07/12/the-term-select-mgprofile-is-not-recognized-error/

**Comment by rvdwegen** [comment]
> Same question from me since it's been well over a year since the question was first asked.

For anyone else, I've personally just dropped the module completely in favor of straight API calls. Once you get a handle on authentication its arguiably siimpler to work with the API than with the modules.
