### ISSUE TITLE
How to access a client tenants?

### ISSUE THREAD

**Issue by stevenrombauts** [microsoftgraph/msgraph-sdk-powershell#885]
As an indirect CSP partner, we can list all our client tenants and then run tasks for these tenants using the old MSOnline PowerShell module by adding the `-TenantId` argument to each cmdlet. It seems this is no longer possible with the new Microsoft Graph API and cmdlets. 

For example:

```
# MSOnline will return results from client tenant
Get-MsolSubscription -TenantId <client id> 
# MS Graph will only return results from our own partner tenant
Get-MgSubscribedSku ??
```

Will this functionality be made available to bring these modules up to speed? At this time we can not replace the MSOnline module with the MS Graph Powershell SDK. We've been waiting for years for this functionality to land in the Azure AD modules so we could upgrade, but now these are to be replaced by the MS Graph modules again.

Or is there another way to automatically access these client tenants now?

**Comment by peombwa** [comment]
Hi @stevenrombauts, this functionality isn't available on Microsoft Graph at the moment. I would recommend you open an API feature request at https://developer.microsoft.com/en-us/graph/support for this to be added to the service.

**Comment by stevenrombauts** [comment]
@peombwa Apologies, I never got around to thank you. Thanks for the information, I will open a feature request for this then.
