### ISSUE TITLE
Converting Get-Mg* PSObjects to JSON challenges

### ISSUE THREAD

**Issue by AlexFilipin** [microsoftgraph/msgraph-sdk-powershell#886]
I think it would be great if using `ConvertTo-Json -Depth 100` on PSObjects retruned from Get-Mg* calls would produce valid JSONs that can be POSTed back to Microsoft Graph. As a example `Get-MgIdentityConditionalAccessPolicy` will result in JSONs with Proper Case instead of Lower Case, also DateTime variables are not formatted/converted correctly. 

For several use-cases this forces you to use Invoke-MgGraphRequest instead of the Get-Mg* calls.

**Comment by peombwa** [comment]
This is an issue with `ConvertTo-Json` and not our SDK. You can test this out using the example below:
``` powershell
C:\> @{ Name = "John Doe"; Age = 10 } | ConvertTo-Json
# JSON is in pascal case because the original object has properties in pascal case.
{
  "Age": 10,
  "Name": "John Doe"
}
```


We do provide a `.ToJsonString()` method on all objects returned by Get-Mg* commands that you can use to convert the objects to JSON like this:
``` powershell
$Policies = Get-MgIdentityConditionalAccessPolicy
$JsonString = $Policies.ToJsonString()
```
The resulting JSON will have all the property names in camel case.

Please note that the [API returns](https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicy?view=graph-rest-1.0#properties) dateTime properties as `DateTimeOffset` using `ISO 8601` format and is always in UTC. This is what `.ToJsonString()` returns as well.

**Comment by AlexFilipin** [comment]
Thank you! I totally missed that method, I will check it out going forward.
