### ISSUE TITLE
`Invoke-MgGraphRequest` should not require `-Body` to be present to make a `POST` request

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#887]
Given https://docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http, `-Body` should be made optional when making `POST` requests.
![image](https://user-images.githubusercontent.com/7061532/135663340-0ab8f422-095b-4fb4-ac93-973e8ff5bc3c.png)

Also, `Invoke-MgGraphRequest` should support relative URIs Irregardless of the `-Method`.

**Comment by georgend** [comment]
@peombwa
