### ISSUE TITLE
Could the permissions files that the Find-MgGraphCommand cmdlet is reading from be outdated?

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#889]
When I try to get the permissions for the Get-MgUser cmdlets, I get;
`Find-MgGraphCommand -command Get-MgUser | Select Permissions`

Permissions
-----------
{DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementManagedDevices.Read.All, DeviceManagementManagedDevices.ReadWrite.All...}
{DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementManagedDevices.Read.All, DeviceManagementManagedDevices.ReadWrite.All...}
{DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementManagedDevices.Read.All, DeviceManagementManagedDevices.ReadWrite.All...}
{DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementManagedDevices.Read.All, DeviceManagementManagedDevices.ReadWrite.All...}

From the API reference I get; 

<html>
<body>

Permission type | Permissions (from least to most privileged)
-- | --
Delegated (work or school account) | User.ReadBasic.All, User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All, Directory.AccessAsUser.All
Delegated (personal Microsoft account) | Not supported.
Application | User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All

</body>
</html>

**Comment by peombwa** [comment]
@msewaweru, you need to expand the `permissions` property since it is a collection, i.e., `Find-MgGraphCommand -command Get-MgUser | Select -First 1 -ExpandProperty Permissions`:

``` powershell
@peter ➜ C Find-MgGraphCommand -command Get-MgUser | Select -First 1 -ExpandProperty Permissions

Name                                         IsAdmin Description                                   FullDescription
----                                         ------- -----------                                   ---------------
DeviceManagementApps.Read.All                True    Read Microsoft Intune apps                    Allows the app to r…
DeviceManagementApps.ReadWrite.All           True    Read and write Microsoft Intune apps          Allows the app to r…
DeviceManagementManagedDevices.Read.All      True    Read devices Microsoft Intune devices         Allows the app to r…
DeviceManagementManagedDevices.ReadWrite.All True    Read and write Microsoft Intune devices       Allows the app to r…
DeviceManagementServiceConfig.Read.All       True    Read Microsoft Intune configuration           Allows the app to r…
DeviceManagementServiceConfig.ReadWrite.All  True    Read and write Microsoft Intune configuration Allows the app to r…
Directory.AccessAsUser.All                   True    Access the directory as you                   Allows the app to h…
Directory.Read.All                           True    Read directory data                           Allows the app to r…
Directory.ReadWrite.All                      True    Read and write directory data                 Allows the app to r…
User.Read.All                                True    Read all users' full profiles                 Allows the app to r…
User.ReadBasic.All                           False   Read all users' basic profiles                Allows the app to r…
User.ReadWrite.All                           True    Read and write all users' full profiles       Allows the app to r…
```

**Comment by msewaweru** [comment]
Thanks Peter for the clarification. This is ok.
