### ISSUE TITLE
[Fetaure request] Add function to convert Autopilot profile to configuration JSON

### ISSUE THREAD

**Issue by o-l-a-v** [microsoftgraph/msgraph-sdk-powershell#891]
Feature request to create a function to convert a Autopilot profile fetched with [Microsoft.Graph.DeviceManagement.Enrolment](https://www.powershellgallery.com/packages/Microsoft.Graph.DeviceManagement.Enrolment):

```powershell
Microsoft.Graph.DeviceManagement.Enrolment\Get-MgDeviceManagementWindowAutopilotDeploymentProfile
```

to a Autopilot configuration JSON file, that can be used in SCCM task sequence, or slipstreamed to install.wim. Just like [WindowsAutoPilotIntue](https://www.powershellgallery.com/packages/WindowsAutoPilotIntune):

```powershell
WindowsAutoPilotIntune\ConvertTo-AutopilotConfigurationJSON
```

Maybe it could be a optional parameter for  ```Get-MgDeviceManagementWindowAutopilotDeploymentProfile```, so it could output the profiles in a compatible format that one could just ```ConvertTo-Json``` later?

**Comment by peombwa** [comment]
Hi @o-l-a-v,
Microsoft Graph PowerShell objects have a `.ToJsonString()` that you can call to convert an output to a JSON string. See my comment here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/886#issuecomment-931451466.

**Comment by o-l-a-v** [comment]
> Hi @o-l-a-v,
> Microsoft Graph PowerShell objects have a `.ToJsonString()` that you can call to convert an output to a JSON string. See my comment here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/886#issuecomment-931451466.

That or ConvertTo-Json will not produce the same output as the cmdlet in the first post, as they convert the whole object as is to JSON. Or at least, I assume .ToJsonString() produces the same as ConvertTo+Json?

**Comment by peombwa** [comment]
Got it! This is a reasonable ask and is something we can add as a [scenario command](https://github.com/microsoftgraph/msgraph-sdk-powershell/wiki/Generation-Process#customization) for.

With this command, customers will be able to perform the following workflow -> https://docs.microsoft.com/en-us/mem/autopilot/existing-devices.

**Comment by peombwa** [comment]
The API owner now provides a wrapper, that's built on top of this SDK, that allows ConvertTo-AutopilotConfigurationJSON to be used with Microsoft Graph types - https://learn.microsoft.com/en-us/autopilot/existing-devices#create-the-json-file.
