### ISSUE TITLE
$ErrorActionPreference has no effect

### ISSUE THREAD

**Issue by J0F3** [microsoftgraph/msgraph-sdk-powershell#896]
Hi there

The MS Graph SDK Cmdlets seems not to honor the `$ErrorActionPreference` Variable if set in a Script. 

I usually set `$ErrorActionPreference` to `'Stop'` in my Script so it stop on any error and was also even suggested in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/792.
But this does not work with the MS Graph Cmdlets. Script still continues when one of the MS Graph Cmdlet has errors. 

The same is true for the $VerbosePreference and $DebugPreference which get also not honored by the Cmdlets like this is for other binary Moduls or native Cmdlets. 

As a workaround I use currently the following in my script:
```powershell
$PSDefaultParameterValues[ "*Mg*:ErrorAction" ] = $ErrorActionPreference
$PSDefaultParameterValues[ "*Mg*:Verbose" ] = $VerbosePreference
$PSDefaultParameterValues[ "*Mg*:Debug" ] = $DebugPreference
```
But is the behavior intended or is this a bug?

Thanks!

**Comment by peombwa** [comment]
Hi @J0F3, this is a known PowerShell issue that is currently being discussed here https://github.com/PowerShell/PowerShell/issues/4568:
>A script module's functions do not see the preference-variable values set in the caller's context (except if that context happens to be the global one), which means that the caller's preferences are not honored.

This SDK exports its binary cmdlets as proxy script-module functions, see https://github.com/Azure/autorest.powershell/blob/main/powershell/resources/assets/exports/README.md#purpose.
 
A workaround is to use `-ErrorAction`, `-Debug`, `-WarningAction`, and `-Verbose` as noted above.

Currently, there is nothing we can do about the issue except for the workaround.

**Comment by J0F3** [comment]
@peombwa Aha, thank you for the explanation! I was just not aware of the proxy script-module functions but this explains it. 
Thx!
