### ISSUE TITLE
Support long-running operations (New-MgTeam async operation is not handled within PowerShell SDK)

### ISSUE THREAD

**Issue by mhupfauer** [microsoftgraph/msgraph-sdk-powershell#897]
The teamsAsyncOperation returned by POST /beta/teams is not handled within the PowerShell SDK.
The [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.teams/new-mgteam?view=graph-powershell-beta#outputs) however mentions the return of an object typed as `Microsoft.Graph.PowerShell.Models.IMicrosoftGraphTeam`

**Comment by timayabi2020** [comment]
Similar to #2394

**Comment by timayabi2020** [comment]
Closing this issue because the latest release deserializes headers and outputs them to a hash table.
<img width="757" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/536b8cc4-d8c0-45a0-90b2-1b7672a5c3e1">

**Comment by CarolKigoonya** [comment]
#2600 to resolve this

**Comment by timayabi2020** [comment]
Issue resolved in 2.15.0 release.
