### ISSUE TITLE
Using the existing ref content for New-MgEntitlementManagementAccessPackageResourceRequest does not help work with the cmdlet. Error returned not intuitive to guide user to resolution.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#900]
New-MgEntitlementManagementAccessPackageResourceRequest -CatalogId '54152ecb-c65d-47f2-8a4d-ba2732de0a7b' -RequestType "AdminAdd"
New-MgEntitlementManagementAccessPackageResourceRequest : Value cannot be null.
Parameter name: resource
At line:1 char:1
+ New-MgEntitlementManagementAccessPackageResourceRequest -CatalogId '5 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ body = Micros...sourceRequest }:<>f__AnonymousType59`1) [New-MgEntitleme..._CreateExpanded], RestException`1
    + FullyQualifiedErrorId : ArgumentNullException,Microsoft.Graph.PowerShell.Cmdlets.NewMgEntitlementManagementAccessPackageResourceRequest_CreateExpanded

There is no parameter named resources as per the error and the ref content does not correctly highlight the required parameters.

**Comment by peombwa** [comment]
The error message from the service doesn't make it clear as to which parameter/property one should use to set the required resource. According to the docs, the parameter to use to set a resource is `-AccessPackageResource`, see https://docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&tabs=http#examples.

Only the workload owners can change the error message in this case. The SDK is just a pass through to the service.
