### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by phatcher** [microsoftgraph/msgraph-sdk-powershell#903]
Apologies if I'm asking in the wrong place.

I am trying to acquire details for users/groups during a deployment pipeline and am using the Microsoft.Graph powershell library to do so. I'm running this locally so I can prove it out before executing as in the pipeline.

I authenticate as my service principal and then acquire the security token via

`$graphToken = (az account get-access-token --resource=https://graph.microsoft.com --query accessToken)`

and this seems to have the permissions I'm expecting i.e. "Directory.Read.All", however when I authenticate to Microsoft Graph via

`Connect-MgGraph -AccessToken $graphToken`

I get an error

`Connect-MgGraph: The provided access token is invalid. Set a valid access token to `-AccessToken` parameter and try again.`

Any ideas?

**Comment by peombwa** [comment]
This error message is correct. The access token retrieved from `az` CLI has a leading and trailing `"`, which is not a valid JWToken string. Please trim the leading and trailing `"` from the access token before using it.

``` powershell
$graphToken = (az account get-access-token --resource=https://graph.microsoft.com --query accessToken).Trim('"')
```

As @darrelmiller mentioned above, reusing the CLI appId is not recommended for prod scenarios.

**Comment by RyanTuplin** [comment]
i am having this error now eventhough it states this issue has been resolved

**Comment by helplessJ** [comment]
getting this on a fresh ubuntu 22.02 install with vanilla Connect-MgGraph
:\

**Comment by helplessJ** [comment]
update nevermind, happens on my winderps pc too.

i guess its something with either free tier tenant that i'm trying to dev-test in before blowing up the corporate tenant.

Does anyone know if P2 is required to connect to MsGraph?  frustrating that I only receive the most generic error that could be produced :\

**Comment by MikeOtown** [comment]
Getting this in PS 7:

PS C:\Users\micha> Connect-MgGraph -Scopes 'User.Read.All'
Connect-MgGraph: Invalid JWT access token.

**Comment by phazlett** [comment]
I'm also getting the error with PS 7.

Connect-MgGraph -Identity

EXCEPTION: Invalid JWT access token.

**Comment by helplessJ** [comment]
> Getting this in PS 7:
> 
> PS C:\Users\micha> Connect-MgGraph -Scopes 'User.Read.All' Connect-MgGraph: Invalid JWT access token.

in my experience, this is due to Az.Identity being out of date/incompatible.  Usually from an old onedrive sync brining old modules in.  I'd purge you Az.* modules and re-install your az modules.  Its a pain, and part of powershell hell as far as I can tell
