### ISSUE TITLE
Get-MgUser returns "Insufficient privileges to complete the operation"

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoftgraph/msgraph-sdk-powershell#92]
After connecting (just simple Connect-Graph) I tried to run Get-MgUser, without parameters, but it's returning "Insufficient privileges to complete the operation".

I'd think this should just hit the "/me" endpoint?

**Comment by mrvladis** [comment]
Any updates? I have got an exactly the same issue.

**Comment by darrelmiller** [comment]
Get-MgUser attempts to read all users.  This requires the permission User.Read.All to be consented.

```
 Connect-Graph -scopes "User.Read.All"
```

By default the PowerShell SDK uses an application that already exists and is registered in our tenant.  Upon consenting, it will create a service principal (shown as an "Enterprise Application" in the portal).  The default permissions that are consented when you use `Connect-Graph` are only to read your profile, not someone elses.  You can do this with:

```
Get-MgUser -UserId "<me@mydomain.com>"
```

**Comment by mrvladis** [comment]
@darrelmiller  is this part documented anywhere?

**Comment by darrelmiller** [comment]
Which part?  

The difference between Applications vs Service Principals are here: https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals

The fact that PowerShell uses non-plural names to get lists of things is a convention of PowerShell.  I'm not sure where that would be documented.

The details around Microsoft Graph permissions are here https://docs.microsoft.com/en-us/graph/permissions-reference

**Comment by mrvladis** [comment]
I mean default behaviour and requirement to provide a scope.

**Comment by darrelmiller** [comment]
It is not specifically documented for PowerShell because the default permissions are listed on the consent dialog that is presented on first sign in and the behavior is the same for any Microsoft Graph application.  

I talk through this issue here around 11:45 into this video [here]( https://www.bing.com/videos/search?view=detail&mid=6CED6F7ECE8791C839B76CED6F7ECE8791C839B7&shtp=GetUrl&shid=ddea127d-155c-4a25-81ee-08a0400065f7&shtk=TWljcm9zb2Z0IEdyYXBoIGRldmVsb3BlciBjb21tdW5pdHkgY2FsbC1EZWNlbWJlciAyMDE5&shdk=QWdlbmRhIGZvciB0aGlzIG1vbnRo4oCZcyBjYWxsIGluY2x1ZGVkOiAtSmFwaGV0aCBPYmFsYSAtIEdyYXBoIEV4cGxvcmVyIFByZXZpZXcgRXhwZXJpbWVudHMuIC1EYXJyZWwgTWlsbGVyIC0gTWljcm9zb2Z0IEdyYXBoIFBvd2VyU2hlbGwgU0RLIFByZXZpZXcgaW50cm9kdWN0aW9uLiAtVG9kZCBLbGluZHQgLSBNaWNyb3NvZnQgR3JhcGggUG93ZXJTaGVsbCBTREsgaGlnaHMgYW5kIGxvd3MuIC1EYXJyZWwgTWlsbGVyIC0gTWljcm9zb2Z0IEdyYXBoIFBvd2VyU2hlbGwgU0RLIFJvYWRtYXAgYW5kIGJlaGluZCB0aGUgc2NlbmVzIEZvciBtb3JlIGluZm9ybWF0aW9uLCBwbGVhc2UgdmlzaXQgaHR0cHMgLi4u&shhk=X%2BOv%2BQOLgAdzzdLxMIqjWPsuWIe0x0WqeyROwKtdV5g%3D&form=VDSHOT&shth=OSH.iopQeaCdnfausFN17rJoAg)

**Comment by tibereus** [comment]
where we at with this problem?

**Comment by hhbadarin** [comment]
I'm having the same problem, any updates!!

**Comment by hhbadarin** [comment]
I had the same issue but was able to resolve it by running the **Connect-MgGraph -Scopes "Directory.AccessAsUser.All"** script.

**Comment by RDavis3000** [comment]
I'm trying to follow the quickstart at https://learn.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0

I've tried various combinations of scopes but I keep getting the ProfileAccessDeniedException:

`PS C:\Users\Richa> Find-MgGraphCommand -command Get-MgUser | Select -First 1 -ExpandProperty Permissions

Name                    IsAdmin Description                             FullDescription
----                    ------- -----------                             ---------------
Directory.Read.All      True    Read directory data                     Allows the app to read data in your organization's director…
Directory.ReadWrite.All True    Read and write directory data           Allows the app to read and write data in your organization'…
User.Read.All           True    Read all users' full profiles           Allows the app to read the full set of profile properties, …
User.ReadBasic.All      False   Read all users' basic profiles          Allows the app to read a basic set of profile properties of…
User.ReadWrite.All      True    Read and write all users' full profiles Allows the app to read and write the full set of profile pr…

PS C:\Users\Richa> Connect-MgGraph -Scopes "User.Read.All,Group.ReadWrite.All, Directory.Read.All,Directory.ReadWrite.All,User.ReadBasic.All,User.ReadWrite.All,Directory.AccessAsUSer.All"
Welcome To Microsoft Graph!
PS C:\Users\Richa> Get-MgUser
Get-MgUser_List1: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.
PS C:\Users\Richa>`

Can anyone tell me what I am doing wrong?

> It is not specifically documented for PowerShell because the default permissions are listed on the consent dialog that is presented on first sign in and the behavior is the same for any Microsoft Graph application.
> 
> I talk through this issue here around 11:45 into this video [here](https://www.bing.com/videos/search?view=detail&mid=6CED6F7ECE8791C839B76CED6F7ECE8791C839B7&shtp=GetUrl&shid=ddea127d-155c-4a25-81ee-08a0400065f7&shtk=TWljcm9zb2Z0IEdyYXBoIGRldmVsb3BlciBjb21tdW5pdHkgY2FsbC1EZWNlbWJlciAyMDE5&shdk=QWdlbmRhIGZvciB0aGlzIG1vbnRo4oCZcyBjYWxsIGluY2x1ZGVkOiAtSmFwaGV0aCBPYmFsYSAtIEdyYXBoIEV4cGxvcmVyIFByZXZpZXcgRXhwZXJpbWVudHMuIC1EYXJyZWwgTWlsbGVyIC0gTWljcm9zb2Z0IEdyYXBoIFBvd2VyU2hlbGwgU0RLIFByZXZpZXcgaW50cm9kdWN0aW9uLiAtVG9kZCBLbGluZHQgLSBNaWNyb3NvZnQgR3JhcGggUG93ZXJTaGVsbCBTREsgaGlnaHMgYW5kIGxvd3MuIC1EYXJyZWwgTWlsbGVyIC0gTWljcm9zb2Z0IEdyYXBoIFBvd2VyU2hlbGwgU0RLIFJvYWRtYXAgYW5kIGJlaGluZCB0aGUgc2NlbmVzIEZvciBtb3JlIGluZm9ybWF0aW9uLCBwbGVhc2UgdmlzaXQgaHR0cHMgLi4u&shhk=X%2BOv%2BQOLgAdzzdLxMIqjWPsuWIe0x0WqeyROwKtdV5g%3D&form=VDSHOT&shth=OSH.iopQeaCdnfausFN17rJoAg)

That video is gone now, not a great experience!

**Comment by toddalbers** [comment]
> **[hhbadarin](/hhbadarin) ** commented

This worked for me also.  I also threw these on also "User.ReadWrite.All", "Group.ReadWrite.All".

**Comment by robinmalik** [comment]
Thank you @hhbadarin! I wasted an hour trying to figure out if it was something I was doing wrong. Problem solved now, as strange as it is.
