### ISSUE TITLE
Install via Install-Module is really slow

### ISSUE THREAD

**Issue by Bernd-Spieth** [microsoftgraph/msgraph-sdk-powershell#921]
I am in the process of downloading the version 1.8 modules via Install-Module, but it takes a very long time, currently around 15 minutes. Is there a problem with the Gallery?

**Comment by peombwa** [comment]
This may have been a transient issue with PowerShell Gallery. The SDK install only went up by `~35 MB` between `1.7.0` and `1.8.0`.

We will also drastically reduce the install size when we implement https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/692 in v2 of the SDK.
