### ISSUE TITLE
Get-MgGroupMember does not return 'Service Principal' members

### ISSUE THREAD

**Issue by thuld** [microsoftgraph/msgraph-sdk-powershell#923]
We are trying to update our code (system-tests that important groups are correctly configured, for example only approved members exists for group X).

The cmdlet `Get-AzureADGroupMember` yields the members of a given group, including users, contact and service-principals. But cmdlet `Get-MgGroupMember` does not return a set that includes the service-principals.

**Comment by peombwa** [comment]
The service does not currently support this on v1.0. See, https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http
> Currently service principals are not listed as group members due to staged roll-out of service principals on Graph V1.0 endpoint. This operation is not transitive.

Please use `Select-MgProfile beta` to switch use the `beta` version of the service.

**Comment by pamitha89** [comment]
This is now possible with beta version. I was able to retrieve the service principal id with Get-MgBetaGroupMember

https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.beta.groups/get-mgbetagroupmember?view=graph-powershell-beta
