### ISSUE TITLE
M365 DSC: Teams Meeting Policy AutoAdmittedUsers attribute has issue with InvitedUsers value

### ISSUE THREAD

**Issue by anpiskai** [microsoftgraph/msgraph-sdk-powershell#926]
Found a bug with Teams Meeting Policy. It doesn't support the InvitedUsers value that the M365 DSC documentation and Set-CSTeamsMeetingPolicy documentation claim.
![image](https://user-images.githubusercontent.com/48796638/139722240-3cd416ad-1cef-4e8a-815f-88e03aec4a16.png)

It appears in Get-TargetResource but seems to be missing in the Set-TargetResource and Test-TargetResource parameters
![image](https://user-images.githubusercontent.com/48796638/139722303-3f6c7a21-e721-4dcb-a1cd-cfed26bd3e50.png)

Hopefully should be a quick fix to copy the value in the validation set for Set and Test

**Comment by peombwa** [comment]
@anpiskai, please transfer this issue to https://github.com/microsoft/Microsoft365DSC repo. This repo is only for Microsoft Graph PowerShell SDK-related issues and not M365 DSC.
