### ISSUE TITLE
Beyond commercial cloud

### ISSUE THREAD

**Issue by damorris** [microsoftgraph/msgraph-sdk-powershell#93]
will this eventually be available in sovereign clouds Govt etc...

**Comment by darrelmiller** [comment]
Yes.  That is definitely our goal.  We are working with the MSAL team to identify the right way to do this.

**Comment by peombwa** [comment]
This is now support in version 1.1.0 and can be used as show here https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/425.
