### ISSUE TITLE
Generate Boolean properties as Boolean and not switch parameters.

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#931]
Currently, customers have to explicitly set SwitchParameters to false to deserialize boolean properties to false. e.g., `-SecurityEnabled:$false`. This is because switch parameters are false by default, and we don't deserialize false values that haven't been explicitly set via a parameter when a command is invoked.

### Solution
Let's work with AutoREST to ensure that all parameters of boolean properties are always generated as boolean and not SwithParameter. e.g, `-SecurityEnabled $false` and `-SecurityEnabled $true`.

Related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/748

**Comment by peombwa** [comment]
Closing as this is by design. See https://github.com/Azure/autorest.powershell/issues/1040#issuecomment-1352442281 for more details.

Required Boolean properties will be marked as mandatory as part of https://github.com/microsoftgraph/msgraph-metadata/issues/128.

**Comment by NuAlex** [comment]
As of today, `Update-MgUser` is still using a switchParameter, e.g.: 
```PowerShell
Update-MgUser -UserId $userId -AccountEnabled:$false
```
This isn't user friendly (i.e. really annoying :-D, aka embarrassing) and it's not even documented here: https://learn.microsoft.com/en-us/microsoft-365/enterprise/block-user-accounts-with-microsoft-365-powershell?view=o365-worldwide

Any hopes this will be fixed one day?
