### ISSUE TITLE
Allow localmachine store search with GetCertificateByThumbprint and GetCertificateByName

### ISSUE THREAD

**Issue by Monte-Hazboun** [microsoftgraph/msgraph-sdk-powershell#936]
Hello graph sdk PowerShell team, My name is Monte - I'm an internal MSFT employee.  This came up in a discussion with a customer, so relaying here. 

**Problem statement**

When authenticating a service principal inside of an Azure automation hybrid runbook worker, service principal certificates for azure automation are exported to the local machine certificate store.  This leads to inconsistent behavior when authenticating to graph in a cloud worker vs a hybrid worker since Connect-MgGraph only looks in the current user store during authentication.  

**Workaround**

Customers using a hybrid runbook worker have to find their own certificate and pass the certificate object to connect-mggraph via the certificate parameter in their runbooks.

**Solution**

By allowing the [GetCertificateByThumbprint](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/036a9c064815bd7074cb846e858456b4cc51622d/src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs#L214) and [GetCertificatebyName ](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/036a9c064815bd7074cb846e858456b4cc51622d/src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs#L244)methods to look in the Local Machine store, we can alleviate users from having to manually find certificates on their HRW to successfully auth to graph.

**Comment by peombwa** [comment]
Thanks for opening this feature request. We will implement this in [v2](https://github.com/microsoftgraph/msgraph-sdk-powershell/milestone/23) of the SDK as we will be replacing our auth provider with Azure Identity.

**Comment by peombwa** [comment]
Closed by #1387.

Will be released in v2.
