### ISSUE TITLE
Get windowsUpdateForBusinessConfiguration properties differences

### ISSUE THREAD

**Issue by aslan-im** [microsoftgraph/msgraph-sdk-powershell#938]
I'm getting the WindowsUpdatesForBusiness policies using this commandlet:
`Get-MgDeviceManagementDeviceConfiguration | Where-object { $_.AdditionalProperties.'@odata.type' -eq '#microsoft.graph.windowsUpdateForBusinessConfiguration'}`
If I'm calling the $_.AdditionalProperties.installationSchedule, it is returning:
```
$Ring[0].AdditionalProperties.installationSchedule

Key              Value
---              -----
@odata.type      #microsoft.graph.windowsUpdateActiveHoursInstall
activeHoursStart 08:00:00.0000000
activeHoursEnd   17:00:00.0000000
```

The installationSchedule property refers to [this page](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-windowsupdateforbusinessconfiguration?view=graph-rest-beta) in documentation, where we can see this information:

```
Property                   | Type                                                   | Description
installationSchedule | windowsUpdateInstallScheduleType | Installation schedule
```

When I'm checking the windowsUpdateInstallScheduleType using [link](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-windowsupdateinstallscheduletype?view=graph-rest-beta), I see that there is no properties in the documentation page. But I can find [this one](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-windowsupdatescheduledinstall?view=graph-rest-beta):
```
{
  "@odata.type": "#microsoft.graph.windowsUpdateScheduledInstall",
  "scheduledInstallDay": "String",
  "scheduledInstallTime": "String (time of day)"
}
```

Then if I check the documentation to the patch method of the windowsUpdateForBusinessConfiguration resource, I see there an example:
```
"installationSchedule": {
    "@odata.type": "microsoft.graph.windowsUpdateScheduledInstall",
    "scheduledInstallDay": "everyday",
    "scheduledInstallTime": "11:59:31.3170000"
  }
```
that matches with the windowsupdatescheduledinstall resource type. But in the first commandlet output above, we see the different structure of the installationSchedule property. There is the question, how to use New and Update MgDeviceManagementDeviceConfiguration if the windowsUpdateScheduledInstall in documentation and in commandlet differs?
Is it by design?

**Comment by peombwa** [comment]
@aslan-im, the documentation page isn't clear on what `windowsUpdateInstallScheduleType` is and how to use it. According to the [metadata](https://graph.microsoft.com/beta/$metadata), `windowsUpdateInstallScheduleType` is an abstract type that has two derived types:
- `windowsUpdateActiveHoursInstall` (which is what the `Get-MgDeviceManagementDeviceConfiguration` sample above is returning) - https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-windowsupdateactivehoursinstall?view=graph-rest-1.0.
- `windowsUpdateScheduledInstall` - https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-windowsupdatescheduledinstall?view=graph-rest-beta.

![image](https://user-images.githubusercontent.com/7061532/141861612-b564a5c0-1e5b-452e-b9fd-7ac803587555.png)

This means that any property of type `windowsUpdateInstallScheduleType` can have either `windowsUpdateActiveHoursInstall` or `windowsUpdateScheduledInstall` as its content and you should use `@odata.type` to check for the type and handle the response appropriately:
``` powershell
if ($Ring[0].AdditionalProperties.installationSchedule['@odata.type'] -eq "#microsoft.graph.windowsUpdateActiveHoursInstall"){
# Is of type windowsUpdateActiveHoursInstall
} else {
# Is of type windowsUpdateScheduledInstall
}

```

Please open an issue on the [documentation page](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-windowsupdateinstallscheduletype?view=graph-rest-beta) for the workload to fully document the entity.

**Comment by aslan-im** [comment]
@peombwa but how to use the update function with this data type? 
I have already opened issue in documentation repo.

**Comment by peombwa** [comment]
@aslan-im, you can use `Update-MgDeviceManagementDeviceConfiguration` to update your device configuration as describe here https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-windowsupdateforbusinessconfiguration-update?view=graph-rest-beta#request:

``` powershell
$Body = @{
    "@odata.type" = "#microsoft.graph.windowsUpdateForBusinessConfiguration"
    DisplayName = "Windows Updates"
    installationSchedule = @{
        "@odata.type"        = "microsoft.graph.windowsUpdateScheduledInstall"
        scheduledInstallDay  = "everyday"
        scheduledInstallTime = "11:59:31.3170000"
    }
    ...
}

Update-MgDeviceManagementDeviceConfiguration -DeviceConfigurationId "{Your-Id}" -BodyParameter $Body
```
