### ISSUE TITLE
Microsoft.Graph.Identity.SignIns not exporting MgUserAuthenticationPhoneMethod 

### ISSUE THREAD

**Issue by AvrumFeldman** [microsoftgraph/msgraph-sdk-powershell#940]
Microsoft.Graph.Identity.SignIns = 1.8.0

When initially installing the `Microsoft.Graph.Identity.SignIns` module, the `*-MgUserAuthenticationPhoneMethodcmdlets` work fine, but as soon you actually import the `Microsoft.Graph.Identity.SignIns` (or restart the ps session) those cmdlets stop working with error cmdlet doesn't exists. I can confirm that by importing the module using the verbose parameter those cmdlets are not listed as imported.

Please see attached screenshot from vscode before and after importing the module.

Issue is same on PS 7 and 5.1

![image](https://user-images.githubusercontent.com/42219106/141664368-fa9deab3-6cfb-465f-9b83-ab379bab3c7d.png)

**Comment by peombwa** [comment]
@AvrumFeldman, the commands you are looking for are only available in beta. Use `Select-MgProfile beta` to switch to beta, see https://docs.microsoft.com/en-us/graph/powershell/get-started?view=graph-rest-beta#api-version.
