### ISSUE TITLE
microsoftgraph/service principal permissions

### ISSUE THREAD

**Issue by MattiasSjobom** [microsoftgraph/msgraph-sdk-powershell#944]
I want to perform AD tasks using a service principal, this via Azure DevOps pipeline using powershell or az cli task. This is possible using Azure Active Directory Graph, but since deprecated I instead looking into using Microsoft Graph. Can only get it to work via API though, is there a way to run it with service principal some how? Getting "Insufficient privileges to complete the operation" error regardless of the permissions assigned

**Comment by peombwa** [comment]
Hi @MattiasSjobom, which Microsoft Graph PowerShell command are you using? Some commands/APIs only work using [app-only authentication](https://docs.microsoft.com/en-us/graph/powershell/app-only?tabs=azure-portal) or may require [admin consent](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#admin-restricted-permissions) before using them.

**Comment by MattiasSjobom** [comment]
Eg Add-AzureADGroupMember since I'm trying to use the service principal to manage an AD group, consent is in place including application.read.all. directory.read.all, user.read.all and groupmember.readwrite.all

**Comment by peombwa** [comment]
The MS Graph PowerShell equivalent of `Add-AzureADGroupMember` is `New-MgGroupMember`. `Add-AzureADGroupMember` is part of AzureAD module and not Microsoft Graph PowerShell SDK, see https://docs.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-beta#groups.

You can use  `New-MgGroupMember` to add a member to a group like this:
``` powershell
Connect-MgGraph -Scopes "GroupMember.ReadWrite.All"

New-MgGroupMember -GroupId $GroupId -DirectoryObjectId "{Directory_Object_Id}"
```

You can find more Microsoft Graph PowerShell samples here -> https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/4-UsersAndGroups.ps1#L37

**Comment by MattiasSjobom** [comment]
Thanks @peombwa, is there any way that you can limit the scope of this permission, "GroupMember.ReadWrite.All", so that its only applicable for selected scope like one AD group and not all?

**Comment by peombwa** [comment]
@MattiasSjobom, permissions are pre-configured, and their scope cannot be changes, see https://docs.microsoft.com/en-us/graph/permissions-reference.
