### ISSUE TITLE
Directory Role Management and Entitlement Management are in wrong module

### ISSUE THREAD

**Issue by JefTek** [microsoftgraph/msgraph-sdk-powershell#946]
I noticed that many cmdlets for Directory Role Management and Entitlement Management are mistakenly included in the Microsoft.Graph.DeviceManagement.Enrolment module.

[Microsoft.Graph.DeviceManagement.Enrolment](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/DeviceManagement.Enrolment/DeviceManagement.Enrolment/Microsoft.Graph.DeviceManagement.Enrolment.psd1)

*-MgRoleManagementDirectory*
*-MgRoleManagementEntitlementManagement*
*-MgFilterRoleManagementDirectory*
*-MgFilterRoleManagementEntitlementManagement*

These should likely be in the Microsoft.Graph.Identity.Governance module instead.

[Microsft.Graph.Identity.Governance](https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/dev/src/Identity.Governance/Identity.Governance)

**Comment by peombwa** [comment]
Thanks for surfacing this. We plan to address the mismatched cmdlets in [v2](https://github.com/microsoftgraph/msgraph-sdk-powershell/milestone/23) to avoid breaking existing customers. We will do this by updating our REGEX-based module mapping config to mirror the current state of the service.

**Comment by bgold09** [comment]
Confirming that the `RoleManagementDirectory` cmdlets an Identity module instead. @peombwa let's address this in the v2 milestone.

**Comment by peombwa** [comment]
Fixed by #1573
