### ISSUE TITLE
Remove-MgDevice insufficient privileges

### ISSUE THREAD

**Issue by aexlz** [microsoftgraph/msgraph-sdk-powershell#952]
Hello Everyone,

I know there is already something going on sanitizing the id-parameter for the Mg-Endpoint (https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906).

However since today I receive "Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.RemoveMgDevice_Delete" on one of our tenants. 
I have the e.g. following device:

```
Get-MgDeviceById -DeviceId 6cde9e87-6821-44ea-93ae-09e7c0eb5cf7

DeletedDateTime Id                                   AccountEnabled ApproximateLastSignInDateTime ComplianceExpirationDateTime DeviceId                             Devi
                                                                                                                                                                    ceMe
                                                                                                                                                                    tada
                                                                                                                                                                    ta  
--------------- --                                   -------------- ----------------------------- ---------------------------- --------                             ----
                6cde9e87-6821-44ea-93ae-09e7c0eb5cf7 True           30.08.2021 09:58:04                                        8793d591-6e1b-41a9-b9f9-4923a81cb22e     
```

According to the other issue I use the id-field:
```
PS D:\> Remove-MgDevice -DeviceId 6cde9e87-6821-44ea-93ae-09e7c0eb5cf7
Remove-MgDevice : Insufficient privileges to complete the operation.
At line:1 char:1
+ Remove-MgDevice -DeviceId 6cde9e87-6821-44ea-93ae-09e7c0eb5cf7
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ DeviceId = 6c...7, IfMatch =  }:<>f__AnonymousType69`2) [Remove-MgDevice_Delete], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.RemoveMgDevice_Delete
```

The Enterprise Application, that I use to sign in has the appropriate application-permission (Device.ReadWrite.All):

![image](https://user-images.githubusercontent.com/10604188/143872371-ce73e0b4-7f95-4b78-83f3-0e2df03f44d9.png)

Which permission is needed here? 
```

 Get-MgContext


ClientId              : 10ff5241-d640-RandomNumbers
TenantId              : 45597f60-6e37-RandomNumbers
CertificateThumbprint : 
Scopes                : {Device.ReadWrite.All, User.Read.All, GroupMember.Read.All, DeviceManagementManagedDevices.ReadWrite.All}
AuthType              : AppOnly
AuthProviderType      : ClientCredentialProvider
CertificateName       : 
Account               : 
AppName               : DeviceCleanUp
ContextScope          : Process
Certificate           : [Subject]
                          CN=DeviceCleanUpPROD, O=MyCompany, C=CH
                        
                        [Issuer]
                          CN=MyCompany CA 22, O=MyCompany, C=CH
                        
                        [Serial Number]
                          736AnySerialNumberEF5
                        
                        [Not Before]
                          15.11.2021 11:30:39
                        
                        [Not After]
                          08.02.2024 11:30:39
                        
                        [Thumbprint]
                          A0047DThisIsAThumbprintC3B3A4D
```

The same command is working in NonProd. 
Get-MgContext shows the exact same Scopes and AuthType.

Deleting in Intune with:
Remove-MgDeviceManagementManagedDevice is working without any problem.

**Comment by aexlz** [comment]
I added a Client-Secret to better receive an access token. Pasted into jwt.ms I receive the correct roles:
"roles": [
    "Device.ReadWrite.All",
    "User.Read.All",
    "GroupMember.Read.All",
    "DeviceManagementManagedDevices.ReadWrite.All"
  ],

**Comment by aexlz** [comment]
I think I found the solution. MgDevice calls this endpoint in the background", where Application-Permission are not supported?

![image](https://user-images.githubusercontent.com/10604188/144405594-5da2af3a-058c-4626-8d74-f71bbfa853a6.png)

The ServicePrincipal has the Device-Administrator-Role in the other tenants. That is the reason, why it is working there.

If those permissions are not supported for Application-Based Permission, I have no idea, why they are listed...I expect only those permissions to be listed, which are supported.

Can you please confirm?

**Comment by peombwa** [comment]
Hi @aexlz, a device can only be deleted with `Directory.AccessAsUser.All` delegated permission. Would you please upvote this existing feature request for the service owners to add application permission support to this API: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-application-permission-support-to-delete-aad-devices/idi-p/2899794?

**Comment by mikebeaton** [comment]
> a device can only be deleted with `Directory.AccessAsUser.All` delegated permission

So `Connect-MgGraph -Scopes "Directory.AccessAsUser.All"` before using `Remove-MgDevice` - works for me. Tyvm.

**Comment by NoralfG** [comment]
> Connect-MgGraph -Scopes "Directory.AccessAsUser.All"

Thanks a lot, this did the trick for me as well! :-)
