### ISSUE TITLE
New-MgTeamMember versus New-MgGroupMember

### ISSUE THREAD

**Issue by HAL377** [microsoftgraph/msgraph-sdk-powershell#966]
Hi,

perhaps a silly question but I am automating a Group/Teams membership and I was wondering if there is a strong dependency on the purpose of the group? In other words can I not always use New-MgGroupMember cmdlet and manage the deletion of the owner on the /Group endpoint, even if the group is used for Teams?

I know there is a back-end sync between AAD Group and Teams, but is there anything else that might break if I add/remove owners and members using the /group endpoint only?

ps: I hope there will be a Remove-MgGroupMember and Remove-MgGroupOwner soon :-)

Sincerely,
Tonino Bruno

**Comment by peombwa** [comment]
@HAL377, the differences between a Team and Group are documented here: https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0#teams-and-groups.

Yes, you can use group APIs to manage Teams membership, but you should take note of the subtle differences such https://docs.microsoft.com/en-us/graph/known-issues#removing-a-group-owner-also-removes-the-user-as-a-group-member.

Please consider posting this question to https://docs.microsoft.com/en-us/answers/products/graph to get an answer from the service owners. This repo is for PowerShell SDK related issues and not API.

**Comment by HAL377** [comment]
Appreciate the answer and have a great day!
