### ISSUE TITLE
Update-MgDevice : Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by mgajda83** [microsoftgraph/msgraph-sdk-powershell#968]
Hi,
I have problem with disabling devices in Azure AD. My App have this permissions: 
Device.ReadWrite.All. I also test it with Directory.ReadWrite.All - the same result.

My code is:
`Update-MgDevice -DeviceId $AADDevice.Id -AccountEnabled:$false`
and still getting:
Update-MgDevice : Insufficient privileges to complete the operation.

How to disable AzureAD device using Graph module?

Regards 
Michal

**Comment by peombwa** [comment]
You/the caller will need to have the following roles.
- Global Administrator
- Cloud Device Administrator

See https://docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-1.0&tabs=http#request-body.
> true if the account is enabled; otherwise, false. Only callers in Global Administrator and Cloud Device Administrator roles can update this property.
https://github.com/microsoftgraph/microsoft-graph-docs/issues/14298

Please consider posting API related questions to https://docs.microsoft.com/en-us/answers/products/graph to get faster responses.

**Comment by treestryder** [comment]
Sorry to resurrect this old issue, however it exactly matches my situation and is exactly where I would have turned for help. Until there is a way to disable an Azure AD joined device using Microsoft Graph Powershell module through a non-interactive logon, I will have to continue using the AzureAD Powershell module authenticated using a securely stored credential object. 

- Is there a way to grant the "Cloud Device Administrator" role to an Azure AD app configured for app-only access? 
- If not, is there a secure way to perform unattended/non-interactive delegated access?

Any help would be greatly appreciated.

**Comment by kpinel** [comment]
> Sorry to resurrect this old issue, however it exactly matches my situation and is exactly where I would have turned for help. Until there is a way to disable an Azure AD joined device using the Microsoft Graph PowerShell modules, through a non-interactive logon, I will have to continue using the Azure AD PowerShell module authenticated using a securely stored credential object.
> 
> * Is there a way to grant the "Cloud Device Administrator" role to an Azure AD app configured for app-only access?
> * If not, is there a secure way to perform unattended/non-interactive delegated access?
> 
> Any help would be greatly appreciated.

You can create a Service Principal and grant that the role. This isn't ideal as it does give a lot of access and you need to ensure that you ignore Intune devices in your searches.
![image](https://user-images.githubusercontent.com/875143/226496650-5cebb719-fccf-42c4-85da-8a6760457df0.png)
This has worked for us

**Comment by treestryder** [comment]
I forgot to update this thread.

It turns out that every Enterprise Application already has (is?) a service principal. From the Azure AD roles blade, this can be granted the "Cloud Device Administrator" role. This works as well as (and is probably as insecure as) the Azure AD module.
