### ISSUE TITLE
Support for OData system query options

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#97]
I noticed that you have partial support for OData system query options, with `-OrderBy`, `-Search`, `-Select` and `-Top` parameters for some cmdlets (`Get-MgUser` and `Get-MgGroup`). Regarding this support, I have some questions:

1. Will you be adding this support to additional cmdlets as well?
1. What about other query options such as `-Filter`, `-Expand`, and `-Count`?

Also, I have some concern about mixing areas of knowledge with these. PowerShell users have had sorting, grouping, filtering, selecting, etc. since v1 in 2006, and these parameters require knowledge of Graph and the OData system query options. I understand that this is easier since these cmdlets are auto-generated; however, having a `-Top` parameter in `Sort-Object` for performing a top-N sort and a `-Top` parameter here that really means page size isn't consistent.

If you're willing to consider it, I think you would do better for the PowerShell community if you chose parameter names for these that mapped to PowerShell domain knowledge, with aliases that map to Graph API/IData system query domain knowledge (i.e. `-Sort` with alias `-OrderBy`, `-PageSize` with alias `-Top`, `-Property` with alias `-Select`, and if you add more, `-ExpandProperty` with alias `-Expand` -- the other names can stay the same since they map to PowerShell just fine). That serves both worlds, opens the door for discovery from either side of the fence, while maintaining consistency with PowerShell. This approach has been the recommended way to bring functionality into PowerShell from disparate domains into one consistent environment since day 1.

**Comment by darrelmiller** [comment]
> (i.e. -Sort with alias -OrderBy, -PageSize with alias -Top, -Property with alias -Select, and if you add more, -ExpandProperty with alias -Expand

I really like this idea.  

Our OpenAPI was missing a bunch of query parameters.  The most recent OpenAPI has many more.  These should appear in the next update we release.

**Comment by KirkMunro** [comment]
Just FYI, here is a specific scenario highlighting the need for this support:

I want to retrieve users from my graph, along with their managers.

The beta Graph SDK supports via the `$expand` OData query parameter, as identified [here](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/37700059-add-manager-to-list-users-graph-api); however, also as identified in that same discussion, it doesn't seem that mixing `$select` and `$expand` works as expected yet.

This specific scenario is a huge pain today without Graph.

If I use the `MSOnline` module to enumerate my O365 users, and I want their managers as well I can use the `Get-AzureADUserManager` cmdlet from the `AzureAD` module, but that cmdlet can only be used to retrieve a single manager for a single user, which results in abysmal performance at scale. The Graph PowerShell module seems like it will make this easier, but only if it gets the OData query options supported to enable these more powerful data retrieval scenarios. We must be able to retrieve bulk record collections with the data properties we need using the fewest network calls possible.

The [other issue I raised today](#116) about batching commands is also related to this need.

**Comment by JustinGrote** [comment]
+1 for -Filter

Most Powershell users are familiar with OData filtering syntax from the ActiveDirectory module, so this filter should follow suit.

My use case (one of MANY): Filtering to just O365 Teams groups with Get-MGGroup, I don't want to have to pull the entire list to then filter client-side.

**Comment by JustinGrote** [comment]
@peombwa thank you so much for you PR, but it doesn't address -Filter, -Expand, and -Count. Should this be opened as a new issue or should this issue be reopened?

**Comment by darrelmiller** [comment]
@JustinGrote OData already uses the term filter and so where the filter parameter is supported by the API, then -filter will work from PowerShell.  Having said, that, not all APIs support filter and sadly for the moment you will need to use the ugly OData expressions.  This is exacerbated by the fact that somewhere in the pipeline there is some helpful URLEncoding going on that is then breaking the call to Graph.

e.g.  This URL works from Graph Explorer
```
     https://graph.microsoft.com/beta/groups?$filter=groupTypes/any(c:c+eq+'Unified')
```
This command should work:
```powershell
Get-MgGroup -filter "groupTypes/any(c:c+eq+'Unified')" -debug
```
but it sends this URL
```http
https://graph.microsoft.com/beta/groups?$filter=groupTypes%2Fany%28c%3Ac%2Beq%2B%27Unified%27%29
```
Which should be considered equivalent to the first, but I suspect there is double-encoding happening.  We will investigate and figure out how to fix this.  I'll open a new issue for this issue.

The count parameter is a bit of a challenge, even when it is supported.  We are tracking that issue here:  https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/152

Expand is now aliased as ExpandProperty by PR #153
