### ISSUE TITLE
How to get user custom properties

### ISSUE THREAD

**Issue by julmsy** [microsoftgraph/msgraph-sdk-powershell#971]
Hello everyone,

I'm currently writing a PowerShell script where I need to get all properties from users.
For that, I have an Azure AD App with User.Read.All and Directory.Read.All application permissions.

However, when I run the following code:

```
$cert = Get-Item -Path "Cert:\LocalMachine\Root\$certificateThumbprint"
Connect-MgGraph -ClientId $appClientId -Certificate $cert -TenantId $azureADTenant -ForceRefresh | Out-Null
Get-MgUser -UserId xxx@yyy.com -Property * | fl *
```

The result looks quite empty... To resume, I'm only getting:
- DisplayName
- GivenName
- JobTitle
- Mail
- Surname
- UserPrincipalName
- MobilePhone

CompanyName, Country, Department, etc. properties are empty. Moreover, all custom/added properties that I'm looking for are not present.

Do I need more permission on the Azure AD App, or do I need to call another command to get custom properties?

**Comment by peombwa** [comment]
@julmsy, please consider posting API related questions to https://docs.microsoft.com/en-us/answers/products/graph to get faster responses.

Microsoft Graph API has two options for adding/retrieving custom data, open extensions and schema extensions. Which option are you using? See https://docs.microsoft.com/en-us/graph/extensibility-overview

**Comment by peombwa** [comment]
As for the empty properties, please note that only a limited set of properties are returned unless you explicitly ask for them via `-Property id, displayName, Country`. `*` only returns the default properties. See https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters
>By default, only a limited set of properties are returned (businessPhones, displayName, givenName, id, jobTitle, mail, mobilePhone, officeLocation, preferredLanguage, surname, and userPrincipalName). To return an alternative property set, specify the desired set of user properties using the OData $select query parameter. For example, to return displayName, givenName, and postalCode, add the following to your query $select=displayName,givenName,postalCode.

**Comment by oshihirii** [comment]
I am also trying to figure out how to return custom attributes (added via `Azure Portal` > `Azure AD B2C` > `User Attributes`).  

I am currently using this to try and return the `CompanyName` value for all users:

```
Get-MgUser | Format-List  ID, DisplayName, UserPrincipalName, extension_<extensions_app_id>_CompanyName
```

It only returns three properties:
 - ID
 - DisplayName
 - UserPrincipalName

What is the required syntax for getting custom attributes when using Microsoft Graph PowerShell SDK?  

The code below returns a result in `key:value` style, but it is for a SINGLE user, not ALL users.  

Also, I would like to just be able to run a single command to get the desired result.

(i.e. a list of all users with their custom attributes displayed)  

```
$existingUser = Get-MgUser -UserId "<user_id>" -Property "ID, DisplayName, UserPrincipalName, extension_<extensions_app_id>_CompanyName"  
$existingUser.AdditionalProperties | Format-List
  
  
/* 

returns:  

Key   : @odata.context
Value : https://graph.microsoft.com/v1.0/$metadata#users(id,displayName,userPrincipalName,extension_<extensions_app_id>_
        CompanyName)/$entity

Key   : extension_<extensions_app_id>_CompanyName
Value : My Company

*/
```
