### ISSUE TITLE
Get-MgUserAuthenticationWindowHelloForBusinessMethodDevice does not work and other related bugs

### ISSUE THREAD

**Issue by nielsranosch** [microsoftgraph/msgraph-sdk-powershell#975]
Hello!

The CmdLet `Get-MgUserAuthenticationWindowHelloForBusinessMethodDevice` does not work; see (1) for more details.
The `device`-property of the output of the CmdLet `Get-MgUserAuthenticationWindowHello` does not work either; see (2) for more details.
Both of these may or may not be related to a bug in Microsoft Graph. A workaround to this bug is described in (3).

(1) `Get-MgUserAuthenticationWindowHello`

```powershell
$key = Get-MgUserAuthenticationWindowHello -UserId $user.Id
$key[0].device | convertto-json
```

Expected Output: At least `Id` and `DisplayName` should be different from `null`.

Actual Output:

```json
{
    "AccountEnabled":  null,
    "AlternativeSecurityIds":  null,
    "ApproximateLastSignInDateTime":  null,
    "ComplianceExpirationDateTime":  null,
    "DeletedDateTime":  null,
    "DeviceId":  null,
    "DeviceMetadata":  null,
    "DeviceVersion":  null,
    "DisplayName":  null,
    "Extensions":  null,
    "Id":  null,
    "IsCompliant":  null,
    "IsManaged":  null,
    "MdmAppId":  null,
    "MemberOf":  null,
    "OnPremisesLastSyncDateTime":  null,
    "OnPremisesSyncEnabled":  null,
    "OperatingSystem":  null,
    "OperatingSystemVersion":  null,
    "PhysicalIds":  null,
    "ProfileType":  null,
    "RegisteredOwners":  null,
    "RegisteredUsers":  null,
    "SystemLabels":  null,
    "TransitiveMemberOf":  null,
    "TrustType":  null,
    "AdditionalProperties":  {}
}
```

(2) `Get-MgUserAuthenticationWindowHelloForBusinessMethodDevice`

```powershell
$key = Get-MgUserAuthenticationWindowHello -UserId $user.Id
Get-MgUserAuthenticationWindowHelloForBusinessMethodDevice -UserId $user.id -WindowsHelloForBusinessAuthenticationMethodId $key[0].id
```

Throws an exception:

```
Get-MgUserAuthenticationWindowHelloForBusinessMethodDevice : {"Message":"No HTTP resource was found that matches the request URI 'https://mface.windowsazure.
com/odata/users('*CENSORED*')/authentication/windowsHelloForBusinessMethods('*CENSORED*')/device'.","MessageDetail":"No type was found that matches the controller named 'users'."}
At line:1 char:1
+ Get-MgUserAuthenticationWindowHelloForBusinessMethodDevice -UserId $u ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = cf16...ndProperty =  }:<>f__AnonymousType65`4) [Get-MgUserAuthe...thodDevice_Get1], RestExceptio
   n`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgUserAuthenticationWindowHelloForBusinessMethodDevice_Get1
```

(3) Calling the advertised NavigationProperty `device` directly

Microsoft Graph API's Metadata advertises the NavigationProperty `device` for the EntityType `windowsHelloForBusinessAuthenticationMethod`:

```xml
<EntityType Name="windowsHelloForBusinessAuthenticationMethod" BaseType="graph.authenticationMethod">
  <Property Name="createdDateTime" Type="Edm.DateTimeOffset" />
  <Property Name="displayName" Type="Edm.String" />
  <Property Name="keyStrength" Type="graph.authenticationMethodKeyStrength" />
  <NavigationProperty Name="device" Type="graph.device" ContainsTarget="true" />
</EntityType>
```

However, calling this NavigationProperty is not possible: 

```
GET https://graph.microsoft.com/v1.0/users/*CENSORED*/authentication/windowsHelloForBusinessMethods/*CENSORED*/device
```

```json
{
    "error": {
        "code": "UnknownError",
        "message": "{\"Message\":\"No HTTP resource was found that matches the request URI 'https://mface.windowsazure.com/odata/users('*CENSORED*')/authentication/windowsHelloForBusinessMethods('*CENSORED*')/device'.\",\"MessageDetail\":\"No type was found that matches the controller named 'users'.\"}",
        "innerError": {
            "date": "2021-12-14T14:53:57",
            "request-id": "2cfdd9f6-470d-4cf1-a9b0-7b1e28e5031c",
            "client-request-id": "f4b4ae01-ab3d-f1af-b093-443958cf5252"
        }
    }
}
```

As a workaround, `?$expand=device` can be used:

```
GET https://graph.microsoft.com/v1.0/users/*CENSORED*/authentication/windowsHelloForBusinessMethods/*CENSORED*?$expand=device
```

```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('*CENSORED*')/authentication/windowsHelloForBusinessMethods(device())/$entity",
    "id": "*CENSORED*",
    "displayName": "O365-822enpbTSK",
    "createdDateTime": "2021-12-14T09:29:39Z",
    "keyStrength": "normal",
    "device@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('*CENSORED*')/authentication/windowsHelloForBusinessMethods('*CENSORED*')/device/$entity",
    "device": {
        "id": "*CENSORED*"
    }
}
```

**Comment by nielsranosch** [comment]
I just noticed that for (1), `-ExpandProperties 'device'` can be used. Unfortunately, this is not documented anywhere. If anyone stumbles on this Issue, the following worked for me:

```powershell
$key = Get-MgUserAuthenticationWindowHello -UserId $user.Id -ExpandProperty 'device'
$key[0].device.id
```


Number (2) is still definitely a bug.

**Comment by peombwa** [comment]
1. You'll need to explicitly expand the reference property using `-ExpandProperty 'device'` to retrieve `device`. The SDK is currently built with the assumption of existing MS GraphAPI knowledge, but we are working to simplify the documentation. In the meantime, please check our [samples](https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/dev/samples) and [API reference docs](https://docs.microsoft.com/en-us/graph/api/resources/windowshelloforbusinessauthenticationmethod?view=graph-rest-1.0) to see how one can currently use the SDK.

2. & 3. The error means that the service does not support the request being made. Unfortunately, `device` is marked as a containment navigation property (`ContainsTarget="true"`) in the metadata. `ContainsTarget="true"` means that the contained navigation property can be called using its canonical API, hence why we generate - `Get-MgUserAuthenticationWindowHelloForBusinessMethodDevice`.  The containment will have to be removed from the metadata in order for us to generate the right commands.

**Comment by peombwa** [comment]
Will be fixed by https://github.com/microsoftgraph/msgraph-metadata/issues/106.
