### ISSUE TITLE
Using Get-MgGroupSite is returning all SPO Sites, not just those for the Group

### ISSUE THREAD

**Issue by lrarbin** [microsoftgraph/msgraph-sdk-powershell#976]
Using Get-MgGroupSite is returning all SPO Sites, not just those for the Group.
```
#Connect to Graph
Select-MgProfile -Name "beta"
Connect-MgGraph -TenantId $TenantID -AppId $AppIDGraph -CertificateThumbprint $CertificateThumbPrintGraph

#Get Groups
$Groups = Get-MgGroup -all:$true | where-object {$_.GroupTypes -eq 'Unified'}

#Select First Item
$g=$Groups[0]

# Get the Sites for the Group
Get-MgGroupSite -GroupId $($g.Id) 

```
This then returns all the SharePoint Site Collections for the Tenant, not just the one linked to the Group.

The module versions are:
```
Script     1.9.0      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext...}
Script     1.9.0      Microsoft.Graph.Groups              {Add-MgGroupFavorite, Add-MgGroupToLifecyclePolicy, Confirm-MgGroupGrantedPermission, Confirm-MgGroupMemberGroup... 
Script     1.9.0      Microsoft.Graph.Sites               {Add-MgSiteContentTypeBaseTypeCopy, Add-MgSiteContentTypeCopy, Add-MgSiteListContentTypeBaseTypeCopy, Add-MgSite...
```
The Application Registration has these permissions:
```
Directory.ReadWrite.All | Application | Read and write directory data | Yes | 
Group.ReadWrite.All | Application | Read and write all groups | Yes |   
Reports.Read.All | Application | Read all usage reports | Yes |  
Sites.ReadWrite.All | Application | Read and write items in all site collections | Yes |  
User.Read | Delegated | Sign in and read user profile | No |  
User.Read.All | Application | Read all users' full profiles | Yes |
```
Tested in both PowerShell 5.1 and 7.2.

Thanks for the help, I look forward to hearing back.
Laurence

**Comment by peombwa** [comment]
@lrarbin, you'll need to specify `-SiteId "root"` to access a group team site, see https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-beta&tabs=http#access-a-group-team-site.

**Comment by lrarbin** [comment]
@peombwa - Thanks that has solved the problem. This was something I had working using 'Invoke-WebRequest' but I'm trying to convert my code to use the Graph SDK Module. I didn't find the documentation on:
https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.sites/get-mggroupsite?view=graph-powershell-beta
very helpful. I assumed the SiteID was:
![2021-12-15 08_10_52-● #Get Graph Certificate Thumbprint, App I • Untitled-10 - IS-CS-UCC_Collaborati](https://user-images.githubusercontent.com/8376969/146148756-fd20b531-c870-4d97-8e3b-d740bc30bbfb.png)

Thanks for the help!
Laurence
