### ISSUE TITLE
App registration object doesn't have Oauth2Permissions property

### ISSUE THREAD

**Issue by aremo-ms** [microsoftgraph/msgraph-sdk-powershell#977]
Hello guys

I'm creating an App Registration using **New-MgApplication**
I do see the app registration is created on the portal and I do see it have **Oauth2Permissions** inside it's Manifest
But when I read the object using **Get-MgApplication**, the property is missing. 

Please let me know if I'm missing something here

Best Regards
Alex

**Comment by peombwa** [comment]
@aremo-ms, `Oauth2Permissions` should be returned albeit in a different property since Azure's app manifest is not a one-to-one mapping of MS Graph application resource type. As per the API reference docs, `oauth2PermissionScopes` is accessible under `apiApplication` resource type - https://docs.microsoft.com/en-us/graph/api/resources/apiapplication?view=graph-rest-1.0. This translates to the following in PowerShell:
``` powershell
$App = Get-MgApplication -ApplicationId "your_id"
$App.Api.Oauth2PermissionScopes
```

**Comment by aremo-ms** [comment]
@peombwa thanks so much for rapid response
Just in case, can you advise how may I UPDATE my application with the new object of Oauth2PermissionsScopes?
I don't see a flag for it. Thanks in advance!

**Comment by aremo-ms** [comment]
@peombwa I've figured out all I need for the moment. Thanks for the response.

**Comment by tkoseoglu** [comment]
I am NOT able to update "Oauth2PermissionsScopes". 

This is my request

###############################################################################
#Connect-MgGraph
#Connect to your Azure Active Directory with "Application Adminstrator" or "Global Administrator" Role
###############################################################################
Connect-MgGraph -Scopes "Application.Read.All", "Application.ReadWrite.All", "User.Read.All"
Get-MgContext

$AppName = "DemoApp"
$App = Get-MgApplication | Where-Object { $_.DisplayName -eq $AppName } | Select-Object -First 1
$AppId = $App.AppId
$AppObjectId = $App.Id 
"App" + $AppName + " successfully found! (AppId:" + $AppId + ", AppObjectId:" + $AppObjectId + ")"

###############################################################################
#API
###############################################################################

$adminConsentDescription = "Access as an admin"
$adminConsentDisplayName = "Access as an admin"
$userConsentDescription = "Access as a user"
$userConsentDisplayName = "Access as a user"

$params = @{     
  Api = @(
    Oauth2PermissionScopes = @(
      @{
        AdminConsentDescription = $adminConsentDescription
        AdminConsentDisplayName = $adminConsentDisplayName
        UserConsentDescription  = $userConsentDescription
        UserConsentDisplayName  = $userConsentDisplayName        
      }
    )    
  )  
}
Update-MgApplication -ApplicationId $AppObjectId -BodyParameter $params

"API information added successfully!"

This is my response
The term "Oauth2PermissionScopes" is not recoginzed as the name of a cmdlet, ...


Thank you
