### ISSUE TITLE
Get-MgReportCredentialUserRegistrationDetail -All prompts for authentication several times

### ISSUE THREAD

**Issue by Agazoth** [microsoftgraph/msgraph-sdk-powershell#978]
I have a relative small test tenant with 336 users. I need to test code that assesses the MFA status and plan to use `Get-MgReportCredentialUserRegistrationDetail`

When I run the cmdlet without any parameters, I get a list of the status of all the users (336 users), but when running `Get-MgReportCredentialUserRegistrationDetail -All` I get prompted 3 times for authentication in the browser.

Powershell versions tested: 7.2.1 and 7.2.0
Microsoft.Graph version: 1.9.0

**Comment by peombwa** [comment]
@Agazoth, I am not able to repro this on my end. Could you please share the output of the following for us to investigate this further?
#### Environment
- `$PSVersionTable`
- `$host.CurrentCulture`

#### Modules
- `Get-Module microsoft.graph -ListAvailable` 

Also, could you try the steps mentioned in the second known issue to see if this resolves it for you - https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues.

**Comment by Agazoth** [comment]
It was caused by a known issue. This fixed it:
* Use `Disconnect-MgGraph` to sign out of the current session.
* Run `Remove-Item "$env:USERPROFILE\.graph" -Recurse -Force` to delete your token cache.
* Run `Connect-MgGraph` to reconstruct a clean token cache.
