### ISSUE TITLE
Get-MgServicePrincipal -All terminates with StackOverflowException (PS 5)

### ISSUE THREAD

**Issue by commakoerschgen** [microsoftgraph/msgraph-sdk-powershell#979]
Against a large tenant with approximately 40k service principals, the command
`Get-MgServicePrincipal -All`
terminates with a StackOverflowException after a while, also crashing the PS host.

This only occurs on Powershell 5 (verified with version 5.1.19041.1320). On PS 7.1.4, it works fine.

Graph SDK version is 1.9.0.

**Comment by peombwa** [comment]
This is known memory issue with PowerShell 5.1, please see https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/949#issuecomment-989404660.

**Comment by peombwa** [comment]
Closing as duplicate of #949.
