### ISSUE TITLE
What about /me?

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#98]
It seems that if you want to retrieve information related to your own account from the Graph, that there is a `/me` endpoint that facilitates that work. This doesn't seem to be covered by this module bundle. Are there plans for this support? 
[AB#7429](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7429)

**Comment by MIchaelMainer** [comment]
We intentionally excluded /me with the belief that this is primarily aimed at administrators and they wouldn't be looking at their own information. Are their scenarios where you think /me would be valuable?

**Comment by KirkMunro** [comment]
For automation purposes, absolutely. I may want to use a mail-enabled automation account to perform various tasks, and tie in automation that uses a /me endpoint to process messages. That's one example that comes to mind. But speaking for myself, I use automation all over the place -- not just to manage systems, but to work with my own accounts/data, so this feels like a gap to /me. ;)

**Comment by MIchaelMainer** [comment]
cc @darrelmiller

**Comment by AlanMcBee** [comment]
My thought was that it could be incredibly helpful to fill the gap that is the missing Microsoft Graph Service Connector for Azure Logic Apps / Power Automate.

**Comment by BHoggs** [comment]
This could also be resolved by #127. Calls could be made to /me directly without making explicit cmdlets.

**Comment by peombwa** [comment]
> We intentionally excluded /me with the belief that this is primarily aimed at administrators and they wouldn't be looking at their own information. Are their scenarios where you think /me would be valuable?

This can now be called from `Invoke-MgGraph -Uri "https://graph.microsoft.com/v1.0/me"`.
