### ISSUE TITLE
Get-MgReportOneDriveUsageAccountDetail has random characters at end

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#985]
Looks like two conflicting commands get generated:
Get-MgReportOneDriveUsageAccountDetailDd7F
Get-MgReportOneDriveUsageAccountDetailE827

The parameter sets indicate one is by period and one is by date, so the commands should either be aliased/renamed to be "ByDate" and "ByPeriod", or they should be two parameter sets to the same command.

**Comment by peombwa** [comment]
This was [an issue with the OpenAPI file](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/728) that the command is generated from. We've already fixed this in 1.9.1.
