### ISSUE TITLE
Remove-MgUserMessage is not getting generated.

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#99]
The OpenAPI description is not generating a delete for this entity for some reason:
![image](https://user-images.githubusercontent.com/447694/73575916-3291bc80-4447-11ea-9ef6-b399380a0d77.png)
I'm not sure if the ContainsTarget is wrong or just that the OData.OpenApi.Reader library is not handling it properly.

**Comment by peombwa** [comment]
Will be fixed by https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/217
