### ISSUE TITLE
New-MgTeam doesn't appear to return an Object

### ISSUE THREAD

**Issue by lrarbin** [microsoftgraph/msgraph-sdk-powershell#991]
Hello,
I'm trying to use New-MgTeam to create a Team which is working fine, but the transaction doesn't appear to be returning an Object, so when scripting I can't process the new Team any further as there is no record of what was created.

```
$TeamParam = @{
    Owners = @(Get-MgUser -UserId $owner)
    DisplayName             = $GroupName
    Description             = $Description
    Visibility              = $AccessType
    Classification          = $Classification
    AdditionalProperties    = $AdditionalProperties
}
  Write-Verbose "Team - $($TeamParam.DisplayName)"

    $UnifiedGroup = New-MgTeam @TeamParam -Verbose
    Write-Host $UnifiedGroup # <<<<This returns no data
```
I'm using module version 1.9.1 and PowerShell 7.2.
Thanks
Laurence

**Comment by peombwa** [comment]
The [API to create a team is non-committal](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http#response-2) (returns HTTP status code 202) and no response object is returned. Please the workarounds mentioned in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/897#issuecomment-945991022.

This will be fixed when we add support for long running operations.

Closing as duplicate of #897.
