### ISSUE TITLE
Need guidance with certificate

### ISSUE THREAD

**Issue by aremo-ms** [microsoftgraph/msgraph-sdk-powershell#995]
Hello guys
I'm part of AAD Guidance Team and we support samples from [Azure-Samples repo](https://github.com/Azure-Samples).
Recently we decided to migrate our PowerShell scripts to Graph API. 
One of the last things to resolve is to reproduce next command which upload a certificate:
```powershell
New-AzureADApplicationKeyCredential -ObjectId $clientAadApplication.ObjectId `
        -CustomKeyIdentifier "CN=DaemonConsoleCert" `
        -Type AsymmetricX509Cert `
        -Usage Verify `
        -Value $certBase64Value `
        -StartDate $certificate.NotBefore `
        -EndDate $certificate.NotAfter
```
**Then I see next in Azure Portal App Registration (notice Thumbprint):**
![image](https://user-images.githubusercontent.com/85962119/148122278-290cdd7c-4bbb-4ae7-847e-1ec9cc227242.png)

**So I was able to create next command with Graph API**
```powershell
$keyCredential = New-Object Microsoft.Graph.PowerShell.Models.MicrosoftGraphKeyCredential
        $keyCredential.CustomKeyIdentifier = $certificateName.ToCharArray();
        $keyCredential.Type = "AsymmetricX509Cert";
        $keyCredential.Usage = "Verify";
        $keyCredential.StartDateTime = $certificate.NotBefore;
        $keyCredential.EndDateTime = $certificate.NotAfter;
        $keyCredential.DisplayName = $certificateName;
        $keyCredential.Key = $certBase64Value.ToCharArray();
        $keyCredential.KeyId = (New-Guid).ToString();
                                                  
        $clientKeyCredentials = Update-MgApplication -ApplicationId $clientAadApplication.Id -KeyCredentials $($keyCredential) 
```

**The problem is - I don't see any Thumbprint when looking into certificate of App registration on Azure Portal**
![image](https://user-images.githubusercontent.com/85962119/148122444-49599fd7-5262-431d-babf-a4db2070f254.png)

**My question is - what do I do wrong?**

Thanks in advance

**Comment by peombwa** [comment]
@aremo-ms, the keyCredential's `Key` needs to be `byte[]` and not `char[]` since it is a binary - `Key= $Certificate.RawData`. The `RawData` property of `X509Certificate2` will give you the certificate's raw data in byte array.  Please see that sample here: https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/samples/9-Applications.ps1#L100.

**Comment by aremo-ms** [comment]
Thank you @peombwa 
I've managed to get it look as expected on App Registration.
