### ISSUE TITLE
Update-MgDirectoryRole Incorrect Documentation \ Internal Server Error

### ISSUE THREAD

**Issue by NickGraham101** [microsoftgraph/msgraph-sdk-powershell#996]
The documentation for [Update-MgDirectoryRole](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Identity.DirectoryManagement/Identity.DirectoryManagement/docs/v1.0-beta/Update-MgDirectoryRole.md) says that for the -`Member` parameter you should refer to the [NOTES](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Identity.DirectoryManagement/Identity.DirectoryManagement/docs/v1.0-beta/Update-MgDirectoryRole.md#notes) section and construct a hashtable, no example is provided.  I've tried the following permutations:

```
Connect-MgGraph -Scopes RoleManagement.ReadWrite.Directory, Directory.AccessAsUser.All
Select-MgProfile -Name beta
Update-MgDirectoryRole -DirectoryRoleId 00000000-0000-0000-0000-000000000000 -Members @{ Id = 00000000-0000-0000-0000-000000000000 }
Update-MgDirectoryRole -DirectoryRoleId 00000000-0000-0000-0000-000000000000 -Members @(@{ Id = 00000000-0000-0000-0000-000000000000 })
Update-MgDirectoryRole -DirectoryRoleId 00000000-0000-0000-0000-000000000000 -Members @{ Id = 00000000-0000-0000-0000-000000000000; DeletedDateTime = $null }
Update-MgDirectoryRole -DirectoryRoleId 00000000-0000-0000-0000-000000000000 -Members @(@{ Id = 00000000-0000-0000-0000-000000000000; DeletedDateTime = $null })
# actual guids omitted
```
All return an internal server error, it's unclear if the error is because I'm constructing the parameters incorrectly or if something is actually failing.  Passing some other object type into `-Members`, eg an array of PSCustomObjects, results in a translation error so it seems that the values being passed to `-Members` are valid.

Can an example be added to the documentation and the internal server error return a more useful message

**Comment by peombwa** [comment]
As per the API reference docs, the API to add a directory role member is https://docs.microsoft.com/en-us/graph/api/directoryrole-post-members?view=graph-rest-1.0&tabs=http, which translates to `New-MgDirectoryRoleMemberByRef` in PowerShell. 

The metadata that the SDK is generated from isn't fully annotated to tell us which properties are read-only, and which ones aren't. Workload owners are addressing this.

We strongly encourage customers to use the API reference as a guide when discovering which APIs to use as the metadata is not 100% accurate. PowerShell snippets will also be add to the API reference samples to make it easy for customers to find what they need.

**Comment by thy143** [comment]
@peombwa Do you have an example of how i can find the powershell module based on the API? (i might be missing something obvious)  I want to do the reverse of the above and remove a user form a directory role, but cannot locate the powershell cmdlet. 

API reference for removing a user:  https://docs.microsoft.com/en-us/graph/api/directoryrole-delete-member?view=graph-rest-1.0&tabs=http

**Comment by NickGraham101** [comment]
The following works:

```
$DirectoryRole = Get-MgDirectoryRole | Where-Object { $_.DisplayName -eq "Global Administrator" }
$AdUser = Get-AzADUser -UserPrincipalName $UserPrincipalName
$DirObject = @{ "@odata.id" = "https://graph.microsoft.com/v1.0/directoryObjects/$($AdUser.Id)" }
New-MgDirectoryRoleMemberByRef -DirectoryRoleId $DirectoryRole.Id -BodyParameter $DirObject
```

**Comment by peombwa** [comment]
Read-only properties will be addressed by https://github.com/microsoftgraph/msgraph-metadata/issues/128.
